### ISSUE TITLE
new container type

### ISSUE THREAD

**Issue by KyndallH** [ArctosDB/arctos#1021]
I need a new container type added. I have a 96-well plate ("microplate" in Arctos), and I need to assign a barcode to each well. Right now, there is nothing that would work for the wells in the plate. Can I get "well" added to container type?

**Comment by KyndallH** [comment]
I hate positions because I can never edit them without a massive headache. Other than that, I think that will work. The sample will go directly into the position, will that cause problems? The microplate grid is 12 across (4.75"), 8 down (3.25").

**Comment by KyndallH** [comment]
A DNA extraction

**Comment by campmlc** [comment]
We do need to re-visit the question of editing positions. I cannot delete
or modify a container with positions; I cannot transfer all specimens out
of one freezer box to another (if say, the box disintigrates or the barcode
falls off) because the specimens themselves are in positions and can only
be moved by rescanning..  I cannot list all the number of ways it has been
problematic. Also, there are still containers in the system from before the
positions restrictions were put into place that cannot be edited at all
because they contain both position and non-position container types. I come
across these and have to abandon any attempt to deal with them because I
have no access. Hugely frustrating and a huge waste of valuable time.

**Comment by dustymc** [comment]
You never HAVE to use positions. Nothing stops you from, eg, creating a "not-position" container type and scanning 100 of them into a freezer box. 

Positions exist only in support of specialized forms (although I'm not sure how that intersects with reality - freezer rack positions for example may just be a pain without much real benefit). In order to do that, they have to be predictable. In order to be predictable, I have to maintain fairly tight control over how they're edited. (The "both position and non-position container types" problem comes from insufficient control coupled with user actions that I never anticipated.)

I don't have any sort of personal attachment to positions. If the idea (and the forms it supports) isn't useful, we can get rid of it. If the forms are useful and there's some approach other than the current one which will keep them working, we can go there. 

A "the barcode fell off" app should be a straightforward development.

**Comment by KyndallH** [comment]
Back to the wells in a plate. Are you creating positions for those? If so, will I be able to bulkload the barcodes into the positions? I have 4,466 samples (wells/positions) and I don't want to manually enter them - not safe since they don't have scannable barcodes. The plate has a scannable barcode and each well is getting assigned the barcode and the well. Example sample in well H05 in plate barcode CCDB-19868 is CCDB-19868-H05.

[CreateContainerTemplate 2017.xlsx](https://github.com/ArctosDB/arctos/files/685542/CreateContainerTemplate.2017.xlsx)

**Comment by dustymc** [comment]
I'm just trying to understand what you're doing enough to do whatever you need me to do!

If you want to bulkload, positions may not be the right direction - positions are usually things without independent unique identifiers, and are mostly aimed at a person with a scanner.

And you're not putting anything scannable into the wells, which is probably another strike against positions.

From that and looking at your spreadsheet, a "well" container type does seem most appropriate.

How do you plan to get the sample into the well - might that somehow be important for something about what sort of thing the wells should be?

**Comment by KyndallH** [comment]
So - under a microscope, I pulled off an insect leg and put it in the well. Then we sent it to Canada where they extracted the DNA and sent it back - in that same well that once held the insect's leg. :) 

I started this project of getting them uploaded in the fall when you were out so now trying to remember why I wanted wells and not positions. It may be due because I want to bulkload them. Having the H01 tells me exactly where in the plate they are. Top of the plate are numbers and along the edge is letters so it is a grid system. No way to attach a physical, scannable barcode to each of the wells.

**Comment by dustymc** [comment]
OK, thanks. I think I'm NOT seeing a use for positions in that, I think, so let's create "well" and see what happens, if that sounds reasonable to you. We can re-visit positions later if necessary.

Actually, can I create "microwell" instead? "Well" seems potentially generic enough to find a way to confuse someone, somehow. "Microplate" says "A microwell (usually 96-well) plate, containing small wells for processing or archiving aliquots of samples."

**Comment by KyndallH** [comment]
Microwell sounds perfect! Thanks!

**Comment by dustymc** [comment]
Whew! Done.
