### ISSUE TITLE
remove constraints on container type under create container

### ISSUE THREAD

**Issue by KyndallH** [ArctosDB/arctos#1025]
Currently, we can only upload new barcodes as "container label, cryovial label, specimen label or "position" under Create Container (Object Tracking). 

I request that that constraint is removed and we can enter any valid container type.  Often, I know exactly what the barcodes I made or ordered are going to be used for (box, cryovial, shelf, etc.). If I need to change them later, I can use the Bulk Edit Container but I don't want to have to use it every single time I create a barcode series.

**Comment by dustymc** [comment]
No particular objections from me - just be aware that SOMEONE must have found a way to break SOMETHING to cause the restrictions in the first place....

**Comment by KyndallH** [comment]
I'm racking my brain on how you could screw this up. You enter a valid container type. Whoops. It is the wrong container so as punishment, you have to do the edit container bulkloader. Maybe I'm not thinking outside the box enough? 

I start training Angie next week on Object Tracking and I would like it to be as easy as possible for them. And me!

**Comment by dustymc** [comment]
Given that, is there any benefit to keeping the "label" container types at all?

**Comment by KyndallH** [comment]
I say no - it is not a valid container.

**Comment by campmlc** [comment]
We do use label for rolls of labels that get assigned to different
container types. I would like to keep that. On the other hand, it would be
helpful to be able to create containers de Novo without forcing everything
to start out as a label and later be converted. Freezer rack positions, for
example.

On Jan 6, 2017 4:49 PM, "KyndallH" <notifications@github.com> wrote:

I say no - it is not a valid container.

—
You are receiving this because you were assigned.

Reply to this email directly, view it on GitHub
<https://github.com/ArctosDB/arctos/issues/1025#issuecomment-271041191>,
or mute
the thread

**Comment by campmlc** [comment]
We also generate labels only for a specific container type, e.g. vials or
shelves. It makes sense that these could be created directly as the
appropriate container type in Arctos without having to create first as
labels. I agree with Kendall. I don't see how this could be misused in a
way that cannot be corrected easily by the cm.

On Jan 6, 2017 6:11 PM, "Mariel Campbell" <campbell@carachupa.org> wrote:

We do use label for rolls of labels that get assigned to different
container types. I would like to keep that. On the other hand, it would be
helpful to be able to create containers de Novo without forcing everything
to start out as a label and later be converted. Freezer rack positions, for
example.


On Jan 6, 2017 4:49 PM, "KyndallH" <notifications@github.com> wrote:

I say no - it is not a valid container.

—
You are receiving this because you were assigned.

Reply to this email directly, view it on GitHub
<https://github.com/ArctosDB/arctos/issues/1025#issuecomment-271041191>,
or mute
the thread

**Comment by KyndallH** [comment]
Think the consensus is to remove constraints and keep labels. Works for me!

**Comment by dustymc** [comment]
>remove constraints

done for next release
