### ISSUE TITLE
Specimen Search custom ID in range vs in list

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#1040]
Recently my default seach page options in Arctos for custom ID changed from "in list" to "in range".  Is there a way I can change it back to "in list" or "contains"? I rarely use "in range", and this creates an unnecessary step of changing the default for every search, or I end up having to do the same search twice. Alternately, can we allow a single number to be accepted for an "in range" search?
Error message:
You must specify a range of values separated by ' - ' to search for ranges of Your Identifier.

**Comment by dustymc** [comment]
Arctos should remember the last value you used. If it didn't, something is wonky in your browser or being blocked by your network or etc. If this is still a problem, can you try it elsewhere and let me know details if it's still not working?

FYI, yours should be going to LIST at the moment:

```
UAM@ARCTOS> select CUSTOMOIDOPER from cf_users where username='campmlc';

CUSTOMOIDOPER
------------------------------------------------------------------------------------------------------------------------
LIST

```

> single number to be accepted for an "in range" search?

Yes, we could, but that exists because of usability issues; forcing an error when a user does something other than the search type demands lets people know how to use the search. I'm always up for better ideas.

**Comment by dustymc** [comment]
closing....
