### ISSUE TITLE
Arctos need an SSL certificate

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#1046]
>Beginning in January 2017, Chrome (version 56 and later) will mark pages that collect passwords or credit card details as “Not Secure” unless the pages are served over HTTPS

https://security.googleblog.com/2016/09/moving-towards-more-secure-web.html

**Comment by dustymc** [comment]
@mkoo is dealing with .museum

**Comment by mkoo** [comment]
Too awful to enumerate all the steps and emails to MUSEDOMA and DOTSTER but we finally got a SSL certification from Berkeley May 18 that Chris J. was able to add to arctos host. Still working out wrinkles but mostly secure now. Some browsers refuses to green-light a website because of mixed content but arctos.database.museum proper is secure.
Closing for now but reopen or make a new issue if security is still a problem!
