### ISSUE TITLE
Please add other ID type

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1083]
Please add

ANSP - Academy of Natural Sciences of Drexel University (http://www.ansp.org/research/)

**Comment by Jegelewicz** [comment]
Also please add:

PRC:TEX University of Texas Herbarium (http://prc-symbiota.tacc.utexas.edu/collections/index.php)
RSA-POM Herbarium of Rancho Santa Ana Botanic Garden and Pomona College (http://www.rsabg.org/collections/120)
UCR University of California Riverside Herbarium (http://www.herbarium.ucr.edu/UCRDB.html)

**Comment by ekrimmel** [comment]
Also please add:

[ISM: Illinois State Museum](http://sweetgum.nybg.org/science/ih/herbarium_details.php?irn=124803)
[CHIC: Chicago Botanic Garden](http://sweetgum.nybg.org/science/ih/herbarium_details.php?irn=124263)

Thank you!

**Comment by dustymc** [comment]
done

**Comment by ccicero** [comment]
Should the UCR Herbarium be something like UCR-H to distinguish from other UCR collections?

**Comment by Jegelewicz** [comment]
That's a good point.  I also notice that UCR calls their collections "CNAS" - http://cnas.ucr.edu/about/facilities/collections.html
A can of worms?
Wait, the nematode collection has UCRNC, so I think UCRH or UCR-H would be good.

**Comment by Jegelewicz** [comment]
Can we also add Alan Hancock Foundation as an other ID type?

**Comment by dustymc** [comment]
>UCR

Herbaria almost always have a 3-character "guid prefix" that's stamped on their sheets and recognized by other herbaria. http://sweetgum.nybg.org/science/ih/herbarium_list.php?col_NamOrganisationAcronym=ucr is about as authoritative as that sort of thing gets.

Most non-herbaria are only very recently tentatively considering the possibility of adopting something like unique identifiers - I wouldn't really expect UCRNC to be used for much more than perhaps as a local curatorial identifier.

>Alan Hancock Foundation

Definition please. (And see http://handbook.arctosdb.org/documentation/other-identifying-numbers.html#general-guidelines, particularly item 3. Is there a reason to not just use "original identifier"?)

**Comment by ccicero** [comment]
in GRBIO, UCR Herbarium is coded as UCR<IH>

**Comment by ccicero** [comment]
hmmm, doesn't show the code in GRBIO

![image](https://cloud.githubusercontent.com/assets/967275/24967598/abf525b8-1f78-11e7-92bf-d5dcf21f6ac0.png)

**Comment by Jegelewicz** [comment]
That should work for the foundation.

Could we add TEX-LL - University of Texas at Austin, Plant Resources Center http://prc-symbiota.tacc.utexas.edu/collections/index.php

**Comment by dustymc** [comment]
>TEX-LL

done

>GRBIO

The <IH> signifies that they imported those data from Index Herbariorum (which had at one point intended to merge with GRBIO's predecessor, but I'm not sure how that went). GRBIO seems to be operating under the assumption that they can get everyone to adopt a unique human-readable collection identifier, which seems very unlikely to me. (E.g., there are at least three UAM:Mamm collections, and I doubt any of them are willing to no longer be UAM:Mamm. Even if they were, changing that does nothing useful for old publications citing UAM:Mamm=Universidad Autónoma de Madrid Mammal Collection.) http://grbio.org/institution/university-california-riverside-herbarium is still a useful "GUID" and searching UCR does something useful (lets you pick from the various UCRs) so they are providing something of value, but I don't see them as being or becoming a useful "acronym authority."

**Comment by ccicero** [comment]
Here's an example where they were useful. University of Alabama was using (or going to use?) UAM for their acronym, then realized that it was already in use so chose a different institutional acronym. There may be legacy data where different institutions used the same acronym, but it is useful for collections moving forward. Without GRBIO, there would have been a fourth UAM:Mamm!

For UCR, I'm not suggesting we use that format - just that we distinguish the Herbarium because we may need to add other UCR collections that are not Herbarium.

**Comment by Jegelewicz** [comment]
I think that's a good point and I am OK with UCR-H, because someone, somewhere will likely want to reference the UCR nematodes....

**Comment by dustymc** [comment]
>fourth

Fifth!

Fafirbanks, Madrid, Mexico City, Monticello - and probably dozens of others that we don't (yet) know about. 

The functional split is after one, at which point the "ID type" can no longer be resolvable and computers are extremely unlikely to figure out the intent. But yea, fewer duplicates probably make things a bit easier for humans to sort through.

URLs are nice GUIDs for a few reasons - the ID itself tells you where to find a resolution service (http/DNS), the "base" (arctos.database.museum) is known-unique because it's issued by a global authority, the "local ID" part (guid/UAM:Mamm:12) is known-unique because that's how the protocol works, and there is universal adoption. Almost everyone knows what to expect from/do with things that look like http://arctos.database.museum/guid/UAM:Mamm:12. Even if someone managed to print that string before Arctos (or http of whatever) the obvious universal resolver still leads to us, and from there it'd hopefully be easy to at least figure out you're not where you want to be.

"UAM:Mamm:12" has none of those attributes and could be anything - maybe it's a collector number or an identifier from some completely-unrelated system or something someone made up because they can. GRBIO probably won't discourage the University About Mammals in Lower Sloblovia from using UAM:Mamm - there's no universal adoption. Nothing about the ID makes me think of going to GRBIO for a resolver, and probably less so if I'm Romanian. If I somehow did get to GRBIO and they gave me an answer, it could still be a collector number or something unrelated.

That carries over to the code tables. An ID with a base URL is unambiguous - the combination either resolves to the intended target or it doesn't. For those that do not resolve, I agree that we should be as unambiguous as possible, but that probably means different things to different users. UCR is obvious to a botanist (I think...), but may be used for "some sort of thing from some UCR collection" by anyone else. UCR-H may confuse the botanists (and everyone else??). The embedded descriptive string ("University of California Riverside Herbarium") hopefully helps. Getting the documentation closer to users might help more generally. There are "define" links (which open code tables) scattered around, but I don't know if anyone clicks them - clever ideas always appreciated.

**Comment by dustymc** [comment]
I think these all exist now, closing....
