### ISSUE TITLE
Barcode hardware and supplies

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1101]
I am making wish lists and one thing I would love to add to our collections is the ability to barcode and make use of containers in Arctos.  In order to ask for the equipment, I need to know what to ask for!  I would appreciate any information on barcode readers, especially vendor/cost information as well as any other supplies I would need to create and use barcodes in my collections.

Thanks in advance!

**Comment by dustymc** [comment]
@amgunderson @KyndallH @campmlc 

>create

Certainly possible, but I think it's generally cheaper and more reliable to buy them.

See also http://handbook.arctosdb.org/documentation/container.html#guidelines-for-barcode-containing-labels, and please summarize whatever you learn in the documentation somewhere - it might make a good how-to. (I thought we already had something but can't find it.)

**Comment by campmlc** [comment]
We order preprinted barcode labels from Electronic Imaging Materials. They
make barcode labels that will adhere to cold -80C tubes and work in liquid
nitrogen. They also make two- or three-part labels with duplicate labels
that can be applied to a collection object and also to data sheets, which
work great in the field. We also use their labels for our parasite vials
and skull tags. We use base 36 labels to minimize size, and we give EIM a
series to pre-print for us after we first reserve this series in Arctos to
make sure there are no duplicates.
Cost is $600 -$2,900/ 50,000 cryovial labels depending on the kind of
labels.I can provide more details and contact info if you are interested.

We are currently using Symbol DS6708 2D scanners (Motorola = Zebra)  which
run $2-300. They are programmable to switch from tab to return, which is
useful when going back and forth between Arctos and Excel. These are older
models so there may be newer things out there. I would avoid going very
cheap because we have poor quality scanners from other manufacturers. Make
sure you get a stand and a USB cable included.

**Comment by AJLinn** [comment]
We're in the process of implementing a barcode/object tracking grant with @KyndallH and we opted to buy a printer, ribbons, and labels and print them in-house. If you want to see our supplies list and anything else, I'd be happy to share.
Angie

**Comment by dustymc** [comment]
>print them in-house

In almost every series of in-house printed things with which I have experience (barcodes, NK pages, AF pages, etc.), at some point a printer will jam or etc and duplicates will be created. In the case of barcodes, having physical duplicates will just result in everything except the last scan being tossed into the one container record's history. Just something to be cautious of!

I threw together an outline at http://handbook.arctosdb.org/how_to/Barcode-Supplies.html - please fill in the blanks or edit however you want. You can use git or edit online at https://github.com/ArctosDB/documentation-wiki/blob/gh-pages/_how_to/Barcode-Supplies.markdown
