### ISSUE TITLE
More stuff for ES collections

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1106]
Can we get the cultural terms “Prehistoric”; “Pueblo”; and “Pueblo,  Ancient” added to the Earth Sciences attributes?

Thanks

**Comment by dustymc** [comment]
Seems useful to keep the code table synced across collection types - please comment on #1111.

I'll need definitions. Current are http://arctos.database.museum/info/ctDocumentation.cfm?table=CTCULTURE.

@AJLinn

**Comment by AJLinn** [comment]
Right now the cultures listed in the CT are heavily skewed towards Alaska and our holdings at UAM. I'd be happy to work with anyone who needs/wants to add additional cultures. In general, I was only using Indigenous cultures and then we use "non-Native" for everything else. I opted to not use "nationalities" to be equivalent with "culture" (e.g., Russian, Japanese, Swedish, etc.) because the culture we are examining in the material objects (aka 'material culture') - an Inuit person is also Canadian, a Gwich'in Athabascan could be either an American or Canadian.

Complicated... let's move forward with additions based on what folks need.

**Comment by Jegelewicz** [comment]
The definitions as listed in the EH collections are fine.

**Comment by ekrimmel** [comment]
We need to have some additional values added to culture code table. @AJLinn, would you mind advising on our proposed values below? I am not really familiar with cultural collections, but our collections tech @showes put this wish-list together and may have additional comments.

| Culture | Documentation | Link |
| - | - | - |
| Berber | ethnic group indigenous to North Africa | https://en.wikipedia.org/wiki/Berbers |
| Masai | ethnic group inhabiting southern Kenya and northern Tanzania | https://en.wikipedia.org/wiki/Maasai_people |
| Hutu and Tutsi | Bantu ethnic group native to African Great Lakes region of Africa, often separated into 'Hutu' and 'Tutsi' by socioeconomic class. | https://en.wikipedia.org/wiki/Origins_of_Hutu,_Tutsi_and_Twa |
| Mbenga | pygmy ethnic group inhabiting the Congo region in Africa | https://en.wikipedia.org/wiki/Mbenga_people |
| Mbuti | pygmy ethnic group inhabiting the Congo region in Africa | https://en.wikipedia.org/wiki/Mbuti_people |
| Twa | pygmy ethnic group inhabiting the Congo region in Africa | https://en.wikipedia.org/wiki/Twa |
| Celtic | ethnolinguistic group living during the Iron Age and Medieval Europe | https://en.wikipedia.org/wiki/Celts |
| Maya | ethnic group indigenous to Mesoamerica | https://en.wikipedia.org/wiki/Maya_peoples |
| Mississippian | ethnic group indigenous to what is now the eastern United States; includes cultural subdivisions Middle Mississippian, South Appalachian, Caddolan, and Plaquemine | https://en.wikipedia.org/wiki/Mississippian_culture |
| Seminole | ethnic group indigenous to what is now the U.S. state of Florida | https://en.wikipedia.org/wiki/Seminole |
| Creek | ethnic group indigenous to the Southeastern Woodlands region of what is now the United States | https://en.wikipedia.org/wiki/Muscogee |
| Roman, Ancient | catch-all for objects originating in mainland Italy between the end of the First Punic War ca. 241 BCE to the founding of Constantinople in 330 CE. This period roughly corresponds to Rome’s dominance of the peninsula and all of its cities, including formerly Greek colonies to the south. During this period, Italy was a region with a relatively stable collection of cultural traditions distinct from the rest of the Mediterranean world. | https://en.wikipedia.org/wiki/Ancient_Rome |
| Modern, Italian | ? | ? |
| Modern, Native American | ? | ? |
| Modern, Mexican | ? | ? |
| Modern, Scottish | ? | ? |
| Non-native, French Colonial, Caribbean | culturally French colonizers occupying various regions of the Carribbean beginning in the 17th century | https://en.wikipedia.org/wiki/French_colonial_empire |
| Non-native, British Colonial, Massachusetts Bay | culturally British colonizers occupying what is now the Massachusetts Bay region of the United States beginning in the 17th century | https://en.wikipedia.org/wiki/Massachusetts_Bay_Colony |

Not sure what to do about modern cultures, above. We would like to use these terms for objects originating from the geographic areas included in the table, but within the past century or so.

Also, would it make sense to have a value for "indigenous" to counter "non-Native"? We are thinking of this for objects related to, say, an African culture but unknown exactly *which* African culture... or might it be appropriate to have something like "indigenous, Eastern North America, Woodlands Period" for an object where we know the region and time period but not specific culture...??

**Comment by dustymc** [comment]
Be consistent please - **Roman, ancient** and **Scottish, modern** OR **Ancient, Roman** and **Modern, Scottish**. (I think maybe the former sorts nicer??)

>includes cultural subdivisions Middle Mississippian, South Appalachian

Should we create those now as well? 

SOME indication (in the definition??) of where "ancient" stops and "modern" starts is probably useful.

Or maybe that could be solved with interfaces/documentation - place of manufacture is Scotland @ 1970 + no 'culture...' attributes exist==modern Scottish??

I'm not suggesting anything specific with this, and it comes from staring at https://terms.tdwg.org/wiki/dwc:establishmentMeans rather than anything that might be considered cultural, but I dislike terms like "indigenous" - they usually prove impossible to define. Does something like "Eastern North America, Woodlands Period" (or 'Eastern North American Woodlands Period'???) convey the same information without forcing users to figure out what we meant by "indigenous"?

**Comment by samuelhowes24** [comment]
"Roman, ancient" would definitely be the way to go considering the major cultural shifts over the entirety of Roman history. I used 241 BCE to 330 CE as the bounds for "ancient" because Roman culture and its institutions remained relatively stable and dominant throughout the period. This is not to say that after 330 Italian peoples become "modern", but rather that the region gradually transitioned into a new cultural epoch as Christianity rose and Gothic kings established themselves in formerly Roman cities. So yes, complicated. For the purposes of our collection, a single designation for ancient Roman artifacts, bounded within the period and region specified, will suffice.

"Modern" objects are a bit more complicated because there is no clear line for modernity in any culture. Do we use technological development? Nationality? Markers of globalization? All of these are part of today's cultural identities, but I'm not sure there is just one way to label something as modern. Yet, we do have contemporary objects which belong to some kind of cultural tradition. 

As for the Woodlands Period, that's really just an archaeological term for the period in the Eastern United States when different tribes were adopting and disseminating technological developments in things like cultivation and pottery. I'm not sure it corresponds to a specific culture, but that's how the objects were described by the collector. However, this brings up the question that @ekrimmel  asked earlier, which is "how do we address objects which definitely belong to one of the cultures in a given region, but we aren't sure which one?" Many of our objects from the Northwest Coast fall into this category, and it would be beneficial to have a catch-all category for these cases.

"Indigenous" is certainly problematic for a whole slew of reasons, but it is the broadest opposite term for the category "non-native" already used in Arctos. These two designations could also be used for objects in colonial contexts, where there are many cultures negotiating the same social spaces.

**Comment by AJLinn** [comment]
Thanks @ekrimmel @samuelhowes24 and @dustymc  for an engaging discussion this afternoon.

> Not sure what to do about modern cultures, above. We would like to use these terms for objects originating from the geographic areas included in the table, but within the past century or so.

As I mentioned already (April 24), I choose not to equate nationality with culture, it's just too complicated. Here's how we handle it: 'place of manufacture' + 'contemporary date range' + 'known maker/unknown maker' + 'specimen remarks' that explain the situation = 'culture of origin' non-native

> Also, would it make sense to have a value for "indigenous" to counter "non-Native"? We are thinking of this for objects related to, say, an African culture but unknown exactly which African culture... or might it be appropriate to have something like "indigenous, Eastern North America, Woodlands Period" for an object where we know the region and time period but not specific culture...??

It's preferable to have 'culture of origin' = unknown and have an explanation in the remarks + good provenience/locality information than to simply say 'indigenous.' It's just too broad and means next to nothing on its own unless you know the geography, and that will be provided in the locality area, not the culture section. Non-Native, on the other hand, just means it's not made by a Native person and so you can get the info thru the locality and remarks.

> As for the Woodlands Period, that's really just an archaeological term for the period in the Eastern United States when different tribes were adopting and disseminating technological developments in things like cultivation and pottery. I'm not sure it corresponds to a specific culture, but that's how the objects were described by the collector. 

I wouldn't use the collector's description as any sort of requirement for how you provide attribution. That should go into the specimen remarks field, but there are many outdated and racist attributions that are provided by collectors and while we should note them as part of the documentation, they should not be how we develop our code table nor what dictates their cultural attribution in Arctos.

> However, this brings up the question that @ekrimmel asked earlier, which is "how do we address objects which definitely belong to one of the cultures in a given region, but we aren't sure which one?" Many of our objects from the Northwest Coast fall into this category, and it would be beneficial to have a catch-all category for these cases.

I would be up for a discussion of creating cultures that correspond with [culture areas](https://www.britannica.com/topic/culture-area) that could be used for the broader regional attributions (e.g., Wissler's Northwest Coast, Arctic, California, etc.), with an 'unknown' behind it to indicate a guess but no solid attribution (e.g., "Northwest Coast, unknown"). I'm most familiar with Wissler's culture areas for North America, but that culture area map for Europe at the britannica page linked above looks pretty good too. I wonder if there's something similar for other continents? Maybe that can be our homework?

**Comment by dustymc** [comment]
My primary goal here is to have "bla" mean one clear thing. A user who searches for "bla" should get everything for which we've asserted "bla" and nothing for which we haven't. We should know what we mean by "bla" and have only one way of saying that. Etc. To facilitate that, we need definitions and consistent terminology.

The precision, terminology (as long as it's consistent!), and definition of "bla" don't matter so much. Those three people during that 5 minute interval or anyone from that half of the continent sometime in the last 20K yrs or WHATEVER all fits. (And I like the "culture area" thing - it's something like solidly identifying a biological specimen to genus rather than guessing at subspecies.)

>specimen remarks

Those data might be more searchable if they're closer to the attribute (even if the attribute is extremely vague). Given culture "unknown" (or "super-vague thing" or whatever) and remarks "collector said something mostly irrelevant" I can still find things with SOME sort of culture data by the presence of the attribute. Given "collector said something mostly irrelevant about culture-stuff" in specimen remarks and no culture-attributes, I probably won't find what I want.

Any specimen can have any number of attributes of any type, and they can all have a determiner (and method etc.). It might require some additional documentation, but I think I'd rather see "bla" used with various levels of precision (eg, method="collector said but we're not sure we believe them" vs. "person who wrote the book defining bla said") rather than trying to somehow embed precision or confidence in the terms themselves ("bla" vs. "bla (but mostly unknown)").

**Comment by ekrimmel** [comment]
Thanks, all! 

I like the idea of adding culture areas to get at the balancing act of being findable even when we can't be as specific as we'd prefer.

In addition to cultural areas, how do we feel about adding the modified list of values below (I'm thinking just to cover the data we need to migrate)? @samuelhowes24 am I missing anything?

| Culture | Documentation | Link |
| - | - | - |
| Berber | ethnic group indigenous to North Africa | https://en.wikipedia.org/wiki/Berbers |
| Masai | ethnic group inhabiting southern Kenya and northern Tanzania | https://en.wikipedia.org/wiki/Maasai_people |
| Hutu and Tutsi | Bantu ethnic group native to African Great Lakes region of Africa, often separated into 'Hutu' and 'Tutsi' by socioeconomic class. | https://en.wikipedia.org/wiki/Origins_of_Hutu,_Tutsi_and_Twa |
| Mbenga | pygmy ethnic group inhabiting the Congo region in Africa | https://en.wikipedia.org/wiki/Mbenga_people |
| Mbuti | pygmy ethnic group inhabiting the Congo region in Africa | https://en.wikipedia.org/wiki/Mbuti_people |
| Twa | pygmy ethnic group inhabiting the Congo region in Africa | https://en.wikipedia.org/wiki/Twa |
| Celtic | ethnolinguistic group living during the Iron Age and Medieval Europe | https://en.wikipedia.org/wiki/Celts |
| Maya | ethnic group indigenous to Mesoamerica | https://en.wikipedia.org/wiki/Maya_peoples |
| Mississippian | ethnic group indigenous to what is now the eastern United States; includes cultural subdivisions Middle Mississippian, South Appalachian, Caddolan, and Plaquemine *(I don't care if we create these subdivisions now--we don't need them and my instinct would be to wait until someone does...)* | https://en.wikipedia.org/wiki/Mississippian_culture |
| Seminole | ethnic group indigenous to what is now the U.S. state of Florida | https://en.wikipedia.org/wiki/Seminole |
| Creek | ethnic group indigenous to the Southeastern Woodlands region of what is now the United States | https://en.wikipedia.org/wiki/Muscogee |
| Roman, ancient | catch-all for objects originating in mainland Italy between the end of the First Punic War ca. 241 BCE to the founding of Constantinople in 330 CE. This period roughly corresponds to Rome’s dominance of the peninsula and all of its cities, including formerly Greek colonies to the south. During this period, Italy was a region with a relatively stable collection of cultural traditions distinct from the rest of the Mediterranean world. | https://en.wikipedia.org/wiki/Ancient_Rome |

The modern and colonial objects we can take care of per @AJLinn's suggestion with 'place of manufacture' + 'contemporary date range' + 'known maker/unknown maker' + specimen/attribute remarks. Does 'Roman, ancient' make sense to have, or should we also treat this as  'place of manufacture=Italian peninsula' + 'date range=241 BCE to 330 CE' + 'known maker/unknown maker' + specimen/attribute?

**Comment by samuelhowes24** [comment]
That's all that our collection needs in regards to specific cultural
designations, Erica. Outside of those, most of the artifacts we'll need
designations for are either prehistoric stone tools or artifacts from the
Northwest Coast.

**Comment by AJLinn** [comment]
Sounds good to me.

> Those data might be more searchable if they're closer to the attribute (even if the attribute is extremely vague). Given culture "unknown" (or "super-vague thing" or whatever) and remarks "collector said something mostly irrelevant" I can still find things with SOME sort of culture data by the presence of the attribute. Given "collector said something mostly irrelevant about culture-stuff" in specimen remarks and no culture-attributes, I probably won't find what I want.

So are you saying @dustymc that rather than using specimen remarks, use the remarks in the attribute line? One big benefit I would see to this is that the 'attribute remark' field is searchable for a public (non-logged-in) user, where 'specimen remarks' is not (is there a reason why that field is not accessible for public users? We put a lot of important info in that field that would be useful for folks to search. Maybe I should create a new issue for that?).

So, we could put Culture of Origin = Northwest Coast and then in the attribute remarks we could enter the qualifying information (e.g., "possibly Tlingit or Haida") to give a bit more information.

For the modern and colonial stuff, you can do as described, but then in the attribute remarks something to give more clarification for the user.

@dusty is it possible to use "or" searches on the main search page rather than "and" when entering multiple values in different search boxes? So if I was looking for Tlingit pieces, I could do my standard 'Culture of origin contains Tlingit' but I could also enter "Tlingit" in the 'attribute remarks' field and catch records that contained Tlingit in either field? That way folks wouldn't have to execute 2 or more separate searches for the same value. Just curious - we used to do that in 4D all the time and it was a really valuable search ability.

I'll work on developing the CT values & definitions for the North American culture areas if someone else wants to take on others?

I don't have any Roman items, ancient or modern, that I know of, so I don't really have an opinion on that one. The [AMNH anthropology online database](https://anthro.amnh.org/collections) is a pretty good one, and cultures are broken down by "Collection Area" (i.e., geography) and then you get a list of cultures that correspond with that area. Could be useful for building or refining our list. Just a thought. I know the director of collections there and could ask him about how they built that system if it's useful, if nothing else as an export of cultures to pick from.

**Comment by dustymc** [comment]
>specimen remarks...not accessible for public users

File a new Issue - I have no preferences and it's easy enough to rearrange the form (or make the "curatorial" pane available to anyone or whatever). But keep reading....

> use "or" searches on the main search page rather than "and"

Also an Issue please. It would require some development (mostly in figuring out usability, I think) but I don't see any technical hurdles. But keep reading....

The real issue is that uncontrolled text is simply not usefully searchable. Maybe you'll type "Tlingit" every time and I'll somehow know that's how you spelled it and find what I want, but that's exceedingly unlikely. You'll actually enter (and/or I'll actually search for) "Tilngit" (typos happen) or "Tgt." (weird conventions exist) or "Tlinkit" (equally-correct term) or .... and I'll not find anything, or I'll find 7 of your 18000 Tlinget (oops again!) items and absolutely no indication that I'm missing most of what I'm looking for, or I'll find a bunch of stuff with remark "this is definitely not Tlingit" or etc. Maybe you have some local definition of "Tlingit" that includes (or doesn't) a bunch of stuff I don't (or do) care about and which is different than other collection's local definitions. MAYBE I'll find some of the spelling variations if I use the Google search option, but no bets there either. Uncontrolled text is just unpredictable. A user entering uncontrolled text in hopes of matching some previously-stored uncontrolled text - most users are just not going to find most of what they want most of the time.

Attributes are controlled and defined. Anyone can access the terms and vocabulary at http://arctos.database.museum/info/ctDocumentation.cfm?table=CTCULTURE, so we can all know how you spell Tlingit AND what you mean by it. Arctos won't let you enter anything that's not in the vocabulary; "Tlinkit" is simply not possible. If you use Attributes, I should find all of what I want and nothing that I do not want. Yay everybody!

Along with searching for specific values in Attributes, I can search for the presence of an Attribute (eg, http://arctos.database.museum/SpecimenResults.cfm?guid_prefix=UAM%3AEH&culture_of_origin=_ is UAM:EH data with at least one "culture of origin" determination). If I have to dig through remarks to find what I want, at least I'm digging through fewer remarks, and I should only be seeing things pertaining to culture in those remarks (vs. eg specimen remarks, which are/should be "doesn't fit anywhere else" data).

That is, I can use the STRUCTURE of the data, possibly along with the data itself, to at least narrow down the pile of things which might contain what I'm looking for, and to limit the number of "fields" in which I have to look. I pretty much never attempt to search uncontrolled text, but I might download the data, extract unique values of the free-text column, sort them, and just read through what's left - it's almost always a tiny (=more-manageable) fraction of what I started with. 

If for whatever reason you think there's culture information but can't make a specific assertion (maybe you can't read the label or decipher the collector's scribblings) you could enter culture=unknown (so I can find it by the presence of the culture attribute) and copy the scribblings into the associated remarks (maybe it'll make perfect sense to me-the-user, and if so hopefully I'll become the determiner of an additional less-vague attribute). That's not quite as nice as a direct "this is Tlingit" assertion, but I'm vastly more likely to find that than I am if it's buried in amongst a bunch of unrelated stuff in some general-purpose remarks field.

**Comment by AJLinn** [comment]
Agree 100%.
Using a CT controlled vocabulary for cultures in the attributes is the best-case scenario. However, I can't ethically give an attribution that I know is not true, if I only suspect it might possibly be true. "Unknown" with an explanation in the attribute remarks is better for these situations until we have someone who can definitively ID it to be Tlingit. (see below)

However, general "things that don't fit anywhere else" go into specimen remarks, like a story that the object tells; the context of how and when and by whom an object was used or made; the context of how an attribution to a certain culture or maker or collector was made by by whom.  I know it's not the best for discoverability, but it remains the case that we historians/anthropologists will search for things in different ways than a biologist might search for something. And the data we curate is sometimes very different, for better or worse. I'm very open to discussions of how and where that data can best be placed and discovered by users.

I'll start some new issues as suggested.

**Comment by dustymc** [comment]
>how and where that data can best be placed 

Attributes (eg, free-text; no value nor units code tables) are always available. I (or anyone else with code table access) could throw up a "object story" attribute in a couple minutes, for example. The data would be free-text and so not very searchable, but as above that would allow me-the-user to very easily find the items with SOMETHING about "object story" and to isolate "object story" data from other kinds of free-text data.

You should probably have a defensible use case (eg, a bunch of users interested in that sort of thing) before making such a request - just because we CAN create 9000 pigeonholes doesn't mean we SHOULD.

>the context of how and when and by whom an object was used or made

Some of "how" could perhaps be moved to http://arctos.database.museum/info/ctDocumentation.cfm?table=CTCOLLECTING_SOURCE (or similar - or not, I really don't know, but "collected" on ebay and "collected" from a zoo seem somewhat analogous to me....)

"When" is structured by datatype (a pair of ISO8601 date fields - collecting_event.began_date and collecting_event.ended_date) and supported by a dedicated free-text field (collecting_event.verbatim_date).

"Whom" is Agents (they're scattered all over the place and probably too dependent on procedures, but http://arctos.database.museum/info/ctDocumentation.cfm?table=CTCOLLECTOR_ROLE is one example).

Whatever's left of "...was used or made..." belongs in the relevant specimen event remarks; it's unstructured data (or data for which we have no appropriate structures) which relates to/expands on/whatever the "place of [use, manufacture, whatever]" specimen_event. But of course reality isn't always that clean - whether some comment pertains more to the specimen itself (and so belongs in cataloged item remarks) or the event (specimen event remarks) or an ID or any of the dozens of other things which have available accompanying remarks fields is almost always a little debatable. 

>search for things in different ways

Probably true, and interfaces can ALWAYS be made better, but that's also (somewhat) separate from the structure of the data. Structure provides predictable organization. (THAT is always THERE.) Code tables, datatypes, and authorities provide another level of structure - predictable data predictably organized. With that, there are lots of ways to effectively search (eg, to find all of what you're looking for, nothing that you're not looking for, and reasons to trust that those things are true). Without, there are none(ish). ("Be Google" is getting close - maybe some day none of this will matter!)

**Comment by dustymc** [comment]
Should I load the data in @ekrimmel 's June 1 comment?

**Comment by AJLinn** [comment]
Sounds good to me.

**Comment by dustymc** [comment]
Great - @ekrimmel do you have those data as CSV by any chance?

**Comment by ekrimmel** [comment]
Just emailed it to you @dustymc

**Comment by dustymc** [comment]
Done, closing - please re-open if anything still needs attention.
