### ISSUE TITLE
Loans across collections

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1124]
Any instructions on creating a loan that includes specimens from multiple collections?

**Comment by dustymc** [comment]
Should be the same as any other loan. The only potential gotcha involves users and VPDs - a future bird-only user may not be able to get at what they need if it's a mammal loan (transactions are owned by collections), for example. If your users regularly work across collections you'll probably never encounter that.

MVZ does this regularly - @ccicero @mkoo @atrox10 does that all seem correct?

**Comment by Jegelewicz** [comment]
So just pick a collection to put the loan under, but add specimens from other collections?  Any thoughts on being able to create an "all collections" loan (not choosing a collection to which the loan "belongs")?

**Comment by dustymc** [comment]
>So just pick a collection to put the loan under, but add specimens from other collections?

Yup.

>not choosing a collection to which the loan "belongs"

I'd have to research a bit, but on the surface that looks like a Really Big Deal requiring a rework of some very fundamental things, and I'm not absolutely sure it would be possible then.

**Comment by campmlc** [comment]
Would this loan require multiple signatures from each curator? Could we
cross list in each collection, e.g.give it a loan number in each collection?

**Comment by AJLinn** [comment]
Would you want to do this as a Project? You could create individual loans for each collection, that could all come together in one spot as the Project?

**Comment by campmlc** [comment]
That makes sense.

**Comment by ebraker** [comment]
We do. I usually select whichever collection most material will be loaned from to be the designated collection for the loan (e.g., 8 mammals and 3 birds would be entered as a mammal loan) rather than creating two separate loans for the same transaction. But, we are a vertebrate collection with 1 curator and 1 collection manager and our loan numbers were merged into a single series (V-##) several years ago to streamline the process, so I’m not sure if I would do this if we had separate discipline collections managed by different people as it might be harder to track across VPDs.

**Comment by Jegelewicz** [comment]
Thanks for the suggestions!  I like the project idea and will probably use that in the future.

**Comment by dustymc** [comment]
>Would this loan require multiple signatures from each curator?

That would depend on your policies. Agents are fully-shared in Arctos so no problems there - I think the forms require one primary contact (something about reports) but otherwise you can attach as many agents as you want.

>give it a loan number in each collection

Yup, loan numbers are just strings. But seems like there'd be significant benefits to sharing.

> all come together in one spot as the Project

Yes, but how the loans are set up doesn't effect projects. Projects are fully shared for just that reason - a LOT of research involves multiple Arctos collections.

> track across VPDs

That depends on how your users are set up, which is probably a reflection of how the collections interact with each other - you don't want to end up with someone not being able to manage "their" stuff because it's on a VPD to which they have no access.
