### ISSUE TITLE
download columns - media and citations

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#1130]
In the Arctos Working Group meeting on 8 May 2017, we discussed adding a column with 'Cite by' information - i.e., to provide users with guidelines on how to cite records, and to encourage citation of cataloged items by their GUID.

We also discussed eliminating the column labeled 'Media' in the download, which appears if a user has 'media' checked in the search results customizable options. To restate, I think we should include 'Media' in the download if users want it (e.g., give me all records of species X with audio), but ONLY if a cataloged item is related to a media record. The way it is now, if you have media checked, then all downloads will contain a link in the Media column for each record, even if the link does not work. Here is an example of such a link for a record not associated with any media (MVZ:Bird:180010).

e.g., http://arctos.database.museum/MediaSearch.cfm?collection_object_id=21065456

**Comment by dustymc** [comment]
http://handbook.arctosdb.org/how_to/cite-specimens.html is a slightly different angle on https://arctosdb.wordpress.com/how-to/cite-specimens/, and hopefully addresses some of the comments and concerns which came up in the AWG meeting.

**Comment by Jegelewicz** [comment]
This may be off topic, but I think that having two sets of instructions for how to cite is a problem.  How do I know which one of these is most useful?

**Comment by dustymc** [comment]
Not sure what you mean but...

https://arctosdb.wordpress.com/how-to/cite-specimens/ is deprecated - it's the old doc, I just included it in case I missed bringing something over.

http://handbook.arctosdb.org/how_to/cite-specimens.html is a draft of a new doc.

If you're a user, there are two recommendations:

* cite specimens individually. To do so, use the information in the “cite_this_as” field in the Arctos download (and we need to decide what to put there - my recommendation is the specimen URL/GUID), or 
* contact the Curator(s) of the collection(s) with which you are working for guidance.

If you're making those recommendations, you're just going to have to wade through the rest of the document - there is no single thing that works well for all use cases.

**Comment by Jegelewicz** [comment]
I just want to make sure that we don't have more than one set of instructions floating around that might cause confusion.  Should the old Wordpress site offer up documentation that it has been deprecated?  Perhaps in the header?

As for the citation column, I think this is an excellent idea and although I see the many limitations, I think that at least offering up the full specimen GUID makes sense.

**Comment by dustymc** [comment]
> more than one set of instructions floating around 

Good call: the header on https://arctosdb.wordpress.com/ is now

<img width="824" alt="screen shot 2017-05-10 at 11 42 17 am" src="https://cloud.githubusercontent.com/assets/5720791/25915266/d6789cbc-3575-11e7-9ac9-94579e15e967.png">

**Comment by Jegelewicz** [comment]
Where's the thumbs up emoji? :-)

**Comment by dustymc** [comment]
<img width="275" alt="screen shot 2017-05-10 at 1 14 04 pm" src="https://cloud.githubusercontent.com/assets/5720791/25919141/963c8ee4-3582-11e7-9d32-7d63a2dd3c86.png">

**Comment by dustymc** [comment]
Media code to return NULL instead of JSON if no Media is found is in the DDL. Need to modify app code to deal with that in specimenresults, and ignore media where it's NULL in the download.

Need AWG feedback on two things:

1. Is http://handbook.arctosdb.org/how_to/cite-specimens.html acceptable?
2. What do we put in the "cite_this_as" download column

**Comment by ekrimmel** [comment]
I am in favor of the "full specimen GUID" option presented on the handbook page. 

As for what to put in "cite_this_as" what if we just do *[text from Citation field under Manage Collections] + ": " + [full specimen GUID]*. For example, *Ornithology Collection, Chicago Academy of Sciences: http://arctos.database.museum/guid/CHAS:Bird:2015.1.45*

**Comment by dustymc** [comment]
Bumping priority and reclassifying.

1) Can http://handbook.arctosdb.org/how_to/cite-specimens.html be made better?
2) For "cite as" in results/downloads, can we go with https://github.com/ArctosDB/arctos/issues/1130#issuecomment-311106752

>[text from Citation field under Manage Collections] + ": " + [full specimen GUID]. For example, Ornithology Collection, Chicago Academy of Sciences: http://arctos.database.museum/guid/CHAS:Bird:2015.1.45

**Comment by dustymc** [comment]
The Media column will be JSON for next release. "cite as" still needs resolution.

**Comment by dustymc** [comment]
All of our citation recommendations (http://handbook.arctosdb.org/how_to/cite-specimens.html) seem lacking.

Arctos is now deeply integrated in the DOI system. DOIs are discoverable in that system; other things are not. We don't currently have the capacity to assign DOIs to anything that might get cited, nor to re-label all parts with DOI barcodes if we did, although that is probably the ideal. The discoverability factor isn't critical when authors report publications and we enter them and link citations, but our usage statistics suggest that doesn't happen very consistently. The discoverability of DOIs can cover a lot of gaps, and save a tremendous amount of work in the process.

Citing specimens by any identifier is often (usually??) not sufficient for scientific replication. Some cataloged items do or did contain multiple individuals (lots, embryos, etc.), parts collected at multiple Events, unrelated parts that someone scanned in to the wrong record when entering data, etc. http://arctos.database.museum/guid/MSB:Mamm:292063 is "something someone felt like cataloging," NOT "the thing that got measured/sequenced/etc. for {publication}." It may also contain parts that were collected (or found in the the bugroom) after the citation.

Citing by barcode (or "part identifier") is severely lacking. They're not usually resolvable, and they're not usually globally unique. There's no reason to expect "A3QXW" is anything other than a random string. We can fix that, but not with fewer than 35 characters and probably not for things which already have barcodes. (ARKs are not as discoverable as DOIs, but they are resolvable and I can procure any number of them - let me know if you'd like some for barcodes.)

Barcodes are also somewhat ephemeral - they get damaged and are replaced, for example. Containers which are not used in object tracking (e.g., because the part they used to contain has been moved to a new container with a new barcode) may be permanently deleted.

I think the ideal situation contains three components:

1) Cite specimens by Locked Archive DOI. This adds some stability to the specimen record (specimens in locked archives cannot be deleted or encumbered under "mask record") and provides a compact, discoverable identifier to include in publications: https://dx.doi.org/10.7299/X78C9WJW

2) "Clarify" by citing physical material (parts) by barcode. In the context of a locked archive which contains http://arctos.database.museum/guid/MSB:Mamm:292063, A3QXW identifies a part from a specimen at an event.

<img width="1352" alt="screen shot 2018-10-03 at 8 14 48 am" src="https://user-images.githubusercontent.com/5720791/46420262-7dc97d00-c6e4-11e8-9534-20c0157d19ae.png">

3) For that to work, we need to add stability to barcodes. I think that's as simple as creating a new Part Attribute which is automatically created when a part and barcode are disassociated. Ideally these would be created only by automation and not editable, which would mean parts that have had barcodes are not deletable - disposition could mark them as unavailable, as usual.

Does this seem like something we should pursue?

@Jegelewicz @DerekSikes

**Comment by dustymc** [comment]
>The web address ... not a true GUID

On what basis do you say that?

> unique identifiers and how they are "free"

I suspect that centered around UUIDs? Those are in fact unique(ish...) identifiers and they are in fact free - https://www.uuidgenerator.net/ (and lots of other things) will spit out as many as you want - but they don't really DO anything.

>community can agree on what a catalog number is

At some level I don't care what "the community" thinks a catalog number is or should be, I only care what things have been cataloged in Arctos - what catalog numbers ACTUALLY represent. (Perhaps Curators should care, but that's not something I can make happen. I can only explain the technical implications of cataloging various things.) Catalog numbers are identifiers assigned to "whatever someone felt like cataloging." Any proxy to that (Arctos GUIDs, Locked Archives, DOIs, LSIDs, iDigBio-assigned UUIDs, whatever) are also necessarily identifiers assigned to "whatever someone felt like cataloging." 

If "the community" did something amazing right now it would almost certainly center on Occurrences, and we don't really have those.

>appease the SCAN people

I don't entirely understand what the SCAN people are up to, so I'm not sure if this will appease them or not. What I've outlined unambiguously identifies everything that exists, so I'd think we could build services around that to appease anyone. I doubt we can accurately pipe it all through an exchange standard, but there's a process to modify or extend that Standard.

DOIs do seem like ideal barcodes, but we'd have to buy them and you'd have to fit 35 characters on your labels (and those labels on everything) for that to really work. ARKs are the same character count and I can get them now, but they don't have the buy-in (and system) of DOIs. Limiting the "globe" to 'things contained in this Archive' allows barcodes to serve as GUIDs, which is a huge leap forward in supporting replicability (as long as we can provide persistence, and we can if we decide to). It's not ideal, but we can do it right now simply by providing instructions to users, and I can (increasingly as Crossref and Datacite build tools) do stuff with the publications which contain those citations.

**Comment by campmlc** [comment]
Agree.

**Comment by Jegelewicz** [comment]
>    The web address ... not a true GUID
> 
> On what basis do you say that?

If a collection leaves Arctos, that link would no longer be a valid identifier.

**Comment by dustymc** [comment]
"Is a good GUID" and "is persistent" and "DOES something" are all entirely different things.

I suppose we could add another collection with similar abbreviations and recycle URLs, but we probably won't. Lacking that, URLs are valid persistent GUIDs even if they're not resolvable (eg, the "DOES something" component). And we could set up redirects for them - technically trivial (there's a bulkloader), just needs the admin stuff sorted out.

DOIs don't solve this - I (via MVZ via UC via EZID via DataCite) control them, if a collection leaves Arctos their DOIs also need administratively sorted out to get back to "DOES something" as well. MAYBE keeping DOIs resolvable is slightly simpler than URLs (or not - perhaps someone in that chain won't give up control), but it's exactly the same situation as far as being good GUIDs and persistence goes.

If a collection wants to take their identifiers with them, they probably need to bring them in as well. Maybe that's just a better approach all around - if you want DOIs (or any other ID), you can purchase or create them and do with them what you will. From that perspective Arctos is just managing data, not creating it (as we are with both the current DOIs and URIs) - "we" would have no interest or control, and no ability to "keep" your identifiers even if we wanted to for some unimaginable reason.

**Comment by dustymc** [comment]
resolve https://github.com/ArctosDB/arctos/issues/1966 then return here

**Comment by Jegelewicz** [comment]
Currently waiting on #1966

**Comment by dustymc** [comment]
#1966 does not seem to be going in a direction that would be useful for this.

This has been hanging for way too long. Lacking better ideas, I'll just make the 'guid' in the download the actual GUIDs (eg, UAM:Arc:UA2015-097-05442 will become https://arctos.database.museum/guid/UAM:Arc:UA2015-097-05442)

**Comment by ccicero** [comment]
Revisiting this....in addition to making the 'guid' in the download the actual GUID, have we resolved the media issue for the download. That's what started this whole thread (first comment)?

**Comment by dustymc** [comment]
You can download some Media data since Mar 14, 2018 - I don't know if it resolves the actual problem or not. It's limited to 4K characters, and I think basically all Media need more than that. We can theoretically bump that to 32K - which still won't be sufficient for many use cases - if I ever get a working copy of Oracle12.

**Comment by campmlc** [comment]
What is our timeframe for Oracle12?

**Comment by Jegelewicz** [comment]
I think we should leave this until after we have migrated to Postgres?

**Comment by dustymc** [comment]
There are two things here:

1. Media - yes, PG is going to change everything
2. "Cite_this_thusly" - this is a social problem, PG won't change anything, it needs resolved

**Comment by Jegelewicz** [comment]
Media - cool.
"cite this thusly" - sort of addressed in #1895

**Comment by dustymc** [comment]
>#1895

I'm not sure I see a functional distinction - something I can use to find citations when nothing else works as it should, which is really the only situation in which this matters - between citing

* nothing at all
* "three rats from Alaska"
*  iDigBio's UUID 
* "12" 
* "MSB 12"
* "MSB:Mamm:12"
* etc.

**Comment by Jegelewicz** [comment]
Yeah - I mean that discussion is (or could be) there, so we can use this for the media work, which needs to wait.

**Comment by dustymc** [comment]
I don't care where we discuss, but I also don't think we're going to get any outside help. iDigBio and GBIF are working mostly with identifiers like "12" - anything they do is likely an improvement! We are starting from a position of solid actionable identifiers, the ability to abstract them through other identifiers, the ability to roll them up into packages, and the ability to make precise pointers to other identifiers of various kinds. AFAIK those two situations are the absolute extreme ends of the spectrum, and I think we have both very different problems and very different abilities to solve them.

**Comment by dustymc** [comment]
Tentatively closing this

* Media download is not length-limited under PG
* "Cite this thusly" can and should be embedded in collection terms and/or license.

**Comment by dustymc** [comment]
License and terms handles this.
