### ISSUE TITLE
Request for new part disposition

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1153]
We have a large comparative collection that is used by our paloebiologist.  It is made up of items from our other collections and I would like to be able to have their disposition be "comparative collection" just as I have some items in "teaching collection".  Possible?

**Comment by dustymc** [comment]
https://arctos.database.museum/info/ctDocumentation.cfm?table=CTCOLL_OBJ_DISP

I think we abandoned an effort to update definitions and documentation many years ago.

AWG, can we finalize and define a vocabulary?

FWIW, that still sounds like a loan to me - stuff's being used, supporting research (or teaching or whatever), could be damaged, etc.

Alternatively, part attribute "location" will allow a location history.

**Comment by Jegelewicz** [comment]
Both good ideas - I will think it over and might use a combination of them.

**Comment by ekrimmel** [comment]
@Jegelewicz you can find the location attribute under "Manage Attibutes" when you are editing a specimen part. You can create multiple location attributes.

@dustymc  and AWG, I think the what's currently in the code table for disposition makes sense for us. We don't use any of the "DO NOT USE" values. We do use "on exhibit" and while we certainly could use only "on loan," we like being able to differentiate because of the documentation disparity we have between items on loan and on exhibit (e.g. a rock that's been on exhibit for 50 years doesn't have loan paperwork vs. a bird being used for research where we want to track results, citations, etc.).

Thinking about this brought to mind some questions about teaching collections, which I made a new issue for (#1157)...

| COLL_OBJ_DISPOSITION | Documentation |
|--- | --- |
| **being processed** | Object is in between being accessioned and appearing in the collection. We don't know exactly where it is right now, but we could find it. |
| ~deaccessioned~ | DO NOT USE THIS - use either "discarded" or "transfer of custody" |
| **discarded** | Object has been discarded. Do not use this to mean "used up." |
| **in collection** | Object is where it should be. |
| **missing** | Object cannot be found. |
| **not applicable** | Disposition applied to virtual objects, such as observations. Also use this for objects that were never received but that we want to track, e.g., tissue vouchers that are deposited in another collection. |
| ~observation~ | DO NOT USE THIS - "not applicable" is applicable. |
| **on exhibit** | Object is on exhibit, which hopefully makes some sense in light of local conditions.  Somehow different than "in collection" or "on loan," apparently. |
| **on loan** | Object is currently on an active loan, so is not available in the collections. |
| ~recataloged~ | DO NOT USE THIS - use either "discarded" or "transfer of custody" |
| ~released~ | DO NOT USE THIS - parts are "missing" or "used up" and cataloged items do not have disposition, so this is a nonsensical value. |
| ~subsampled~ | DO NOT USE THIS - it says nothing about the part and just makes no sense. |
| ~teaching collection~ | DO NOT USE THIS - transfer of custody + a loan is appropriate |
| ~transfer of custody~ | DO NOT USE THIS - transfer of custody is a loan type. Use "on loan" for the objects which have been transferred.
| ~unchecked~ | DO NOT USE THIS - Often misused in lieu of "being processed," may also apply to legacy objects which not tracked but are presumably "in collection."
| ~unknown~ | DO NOT USE THIS - "we checked but could think of nothing clever to say after having done so"??
| **used up** | the part has been entirely consumed

**Comment by campmlc** [comment]
All,
I would like to argue for keeping dispostion = transfer of custody. We use
this for parasites that were collected as mammal or bird parts, which have
been transferred to the parasite division to be cataloged as separate
cataloged organisms. This is more than a permanent loan. Specimens are
tracked via accessions into the parasite division, not as an incoming loan
into the parasite division. Also, unlike loan samples these specimens are
available, but through a different division.

I do like getting rid of unchecked and unknown.  Dusty, can we migrate all
dispostions that currently use these terms to "being processed"?

Mariel

**Comment by AJLinn** [comment]
When did we eliminate Deaccession as a disposition? Not everything that is deaccessioned is 'discarded' and 'transfer of custody'  says DO NOT USE.

We have objects that were deaccessioned (removed from the collection) and then sold (mode of disposal). [https://arctos.database.museum/guid/UAM:EH:0392-0019](url)

Discarded implies thrown away, which is a very different process (we can also use "discard" as a mode of disposal).

Can someone explain to me what the rationale is for this change?

**Comment by dustymc** [comment]
Transfer of custody is available in https://arctos.database.museum/info/ctDocumentation.cfm?table=CTLOAN_TYPE. An item is in a loan (maybe with other stuff), the loan (which here is just a convenient mechanism for saying "has left the building") is not something we expect back.

>permanent loan

....

>tracked via accessions

That's not a problem.

>can we migrate all dispostions

That would be lovely, but it's not my call.

```

select
  guid_prefix,
  count(*)
from
  collection,
  cataloged_item,
  specimen_part,
  coll_object
where
  collection.collection_id=cataloged_item.collection_id and
  cataloged_item.collection_object_id=specimen_part.derived_from_cat_item and
  specimen_part.collection_object_id=coll_object.collection_object_id and
  coll_obj_disposition in ('unchecked','unknown')
group by guid_prefix order by guid_prefix;


GUID_PREFIX						       COUNT(*)
------------------------------------------------------------ ----------
CUMV:Amph							   3072
CUMV:Bird							  18243
CUMV:Fish							  54723
CUMV:Mamm							  19256
CUMV:Rept							   6718
DGR:Bird							   3591
DGR:Ento							     35
DGR:Mamm							   1612
DMNS:Bird							  40144
DMNS:Egg							   6924
DMNS:Inv							      2
DMNS:Mamm							    160
KWP:Ento							  43548
MSB:Bird							  31968
MSB:Fish							   4933
MSB:Herp							   1819
MSB:Host							  19969
MSB:Mamm							 301715
MSB:Para							  19898
MVZ:Bird							      7
MVZ:Herp							     20
MVZ:Mamm							     20
MVZObs:Mamm							      1
NBSB:Bird							    649
NMU:Bird							      3
UAM:Alg 							   4639
UAM:Bird							   7789
UAM:EH								      3
UAM:ES								     17
UAM:Ento							   8198
UAM:Fish							   3482
UAM:Herb							  86671
UAM:Herp							     43
UAM:Inv 							   7911
UAM:Mamm							 107130
UAMObs:Ento							  25639
UAMObs:Mamm							      1
UAMb:Herb							      3
UCM:Herp							      4
UCM:Mamm							      1
UWYMV:Bird							      3
WNMU:Mamm							      1
```

**Comment by campmlc** [comment]
Yes, but if an ectoparasite sample is mammals is transferred to the
parasite division via a loan process, it will show up in the mammal record
as "on loan", suggesting that the parasites are not available for further
loans. Transfer of custody, on the other hand, directs people to look for
these samples elsewhere, with the idea that they are still available for
loan request.


I for one vote for the consolidation of all "unknown" and "unchecked"
dispositions to "being processed".

Mariel

**Comment by dustymc** [comment]
> it will show up in the mammal record as "on loan", suggesting that the parasites are not available for further loans. 

Which is exactly the case! The mammal folks do not have access to those parts and so cannot loan them. Users can click the "related" link to find things that can be loaned (by the parasite collection). Citations made against the parasites-as-parts continue to work. Yay everybody!
