### ISSUE TITLE
teaching collections in Arctos

### ISSUE THREAD

**Issue by ekrimmel** [ArctosDB/arctos#1157]
We are curious how other institutions deal with their teaching collections. Our teaching collection is interdisciplinary and mostly not data bearing, but it would be helpful to have in Arctos because it would be more accessible (internally to our Education and Public Programs departments) and because we could better track usage with loans in Arctos. 

I see a few different options for dealing with a teaching collection:

1. Specimens reside in their discipline collections and have a particular **disposition**, e.g. "teaching collection." Problem here is that when a specimen goes on loan its disposition would change to "on loan" and it would lose the teaching collection association.

2. Specimens reside in their discipline collections and have a particular **location** to indicate that they belong to the teaching collection (as suggested in #1153). Specimens can have multiple location attributes which means they can also have a physical location if, as in our case, the teaching collection specimens are physically located all over. Problem here is semantics, as I think of location being physical and teaching collection being use.

3. Specimens reside in their discipline collections and are all attached to a teaching collection **loan**. Problem here is that we loan specimens from the teaching collection frequently. Can an object be on loan to two loans at once? I would think not since an object can't be in two physical places at once. Unless the teaching collection loan is a data loan?

4. Specimens reside in their discipline collections and are all attached to a teaching collection **project**?? I haven't used Arctos projects enough to know if this makes sense.

5. Specimens reside in a **multi-disciplinary "teaching" collection** with no(minal) collection-specific attributes. This would digitally separate these specimens from their scientific counterparts, while still allowing them to interact with loans/accessions/projects/etc. This would also prevent them from being published on the IPT. Although actually, I'm not sure--is there a way (and/or does it already happen) that our data get subsetted prior to pushing them to the IPT?

Anyway, I'm sure other people have thought about this already and might have suggestions for us...

@droberts49

**Comment by dustymc** [comment]
Ideally, I'd get rid of disposition altogether - it's (mostly) a poor substitute for real object tracking. But reality.... 

Loan forms may object to adding a part which is already "on loan," but that's just to help curators keep things straight. Structurally, things never get "unloaned" they just get a new location (eg back in the collection, via barcodes, disposition, and/or part location). I'm sure we can find a suitable workaround which won't break anything else.

Data loans are intended for usage which does not involve physical bits (but see #799 - they've not consistently been used that way). I'd think a "real" loan (=usage documentation) to a teaching collection would be more appropriate (and would better help some future user understand why an item was damaged etc.).

Projects can be useful to group related loans (of any type). Among other things, "donors" seem to really like the ability to see how "their" stuff gets used (which happens automagically when something accessioned by one project is used by another).

DWC "datasets" are analogous to collections. You could use Encumbrances to keep select material out of DWC. (But why? That no-data stuff might turn out to be really useful to someone!)

**Comment by campmlc** [comment]
We have used the "location" approach to allow specimens to be tracked in
object tracking, although ideally we need something other than "room" or
"case" as a container type. This method does not interfere with loans.

But whichever method you use, I would highly recommend creating a Teaching
Collection project that would track all accessions and loans and even media
(maybe a video was made of classroom use, or a teaching module etc).  This
is a great way to document usage through time.

**Comment by droberts49** [comment]
Hi Dusty,

We've been doing some further thinking about how to handle our teaching collection in Arctos. Referring back to Erica's list, the first option of using the disposition field, I don't like, for the reasons listed. I find the disposition field helpful, and it should be paired with the location of the physical specimen, not a use category. The third option, using the loan fields, presents many tracking challenges and just basically muddies things up too much.

Options 2 and 4, using the location fields or possibly a project to designate specimens with a particular level of assigned use, are ones we'll look into. I am not familiar with using the projects option yet! The fifth, having a multi-disciplinary teaching collection, would definitely work in our situation. This option would also allow us to easily pull specs about the collection for reporting.  

Having specimens and artifacts in our teaching collection in Arctos would help us track these specimens for loans, photo documentation, etc. There are such different kinds of usage permitted with specimens in the scientific/accessioned collections versus the teaching collection and we receive a lot of inquiries internally for these items (from education departments). I am hesitant to send these users to Arctos and not have things clearly defined about what is available to them.

**Comment by dustymc** [comment]
>projects

Projects have been stretched in all sorts of interesting directions, but the real magic involves transactions - accessions and loans. http://handbook.arctosdb.org/documentation/projects.html

Creating a loan and adding stuff to it should be an almost-effortless part of normal "usage," and definitely should not muddy anything. I'm happy to talk specifics, help with documentation or procedures, develop new tools/polish old ones, or WHATEVER it takes to make loans more approachable. 

I don't think loans/projects are much of a substitute for physical object location, but might somehow work anyway. (But an "in teaching collection" flag, whatever it ends up being, might be all that's needed to add items to loans.)

Cataloging material from one individual in two collections (tissues+skull, things that might have been cited being "recataloged", etc.) will GREATLY complicate - well, everything! If you don't do that, collection probably doesn't much matter and a teaching collection collection might be a good option.

**Comment by Jegelewicz** [comment]
> I don't think loans/projects are much of a substitute for physical object location

All of our teaching collection isn't necessarily in a single location and it moves around quite a bit within our facility, especially during the fall and spring semesters. We are going to experiment with the project option for both our teaching and comparative collections.

> I am hesitant to send these users to Arctos and not have things clearly defined about what is available to them.

Will the project allow the creation of a set of just the teaching specimens so that you can have those who wish to use teaching specimens only search those? (Of course, they could always clear the search parameters and search all of Arctos, but you might be able to start them off with only the subset of your collection they are interested in.)

**Comment by dustymc** [comment]
>project

Sorta? It's not clear to me what "the project option" is, but eg, http://arctos.database.museum/project/beringian-coevolution-project-bcp then "specimens used.." goes to http://arctos.database.museum/SpecimenResults.cfm?loan_project_id=51

**Comment by campmlc** [comment]
One thing to consider is to save the list of specimens in your teaching
collection as a saved search. Then you could post the saved search url in
your project description or email it to anyone who is interested in the
teaching collection so they can see what specimens are available.

**Comment by droberts49** [comment]
Regarding using loans for the teaching collection, it appears that I was not clear; I was building on what others had previously written in the thread. Loans are a great way to track specimens going out for use. The issue was having a specimen attached to **multiple** loans at the same time. A loan to "create" the teaching collection in the first place. Then regular loan creation for use on top of that. There is higher risk that the original loan designating a specimen to the teaching collection could inadvertently become undone, thereby taking that specimen out of the teaching collection association.

We have been learning how to save searches of a specific subset of specimens and make those available to people. So far, I've only sent someone an email link to the search. Is there a way to make a search available to anyone using the Arctos portal? Which brings my mind back to why not just have a teaching collection...

**Comment by campmlc** [comment]
If you create a project, you can put the link to the teaching collection
saved search in the project description.

**Comment by dustymc** [comment]
>loans

Gotcha. Stuff never gets "unloaned" but I think your concerns are still valid - nobody would expect a part to be in two loans simultaneously. I would still create loans for usage (it just helps document collections), but it's probably not a great way to designate a "subcollection." 

Saved searches (and Archives - http://handbook.arctosdb.org/documentation/archive.html, more at http://handbook.arctosdb.org/how_to/cite-specimens.html) work for anyone, but there's no internal mechanism to share them. Adding link(s) to project description would work, or just add the loan(s) to provide specimen links (under "specimens used"). 

>Which brings my mind back to why not just have a teaching collection...

I don't think I see any particular reason to avoid that, as long as it wouldn't involve cross-cataloging stuff in the teaching collection and elsewhere. Given different loan request guidelines and such.....I think I'm convinced. (And it's easy enough to recatalog the stuff and keep the old links working if a new collection somehow turns out to be a mistake!)

**Comment by Jegelewicz** [comment]
> I don't think I see any particular reason to avoid that, as long as it wouldn't involve cross-cataloging stuff in the teaching collection and elsewhere. Given different loan request guidelines and such.....I think I'm convinced. (And it's easy enough to recatalog the stuff and keep the old links working if a new collection somehow turns out to be a mistake!)

Just want to be sure I understand what you are convinced of.  A single, multi-disciplinary teaching collection or a teaching collection for each discipline?  I would love to get a resolution on this and set up teaching collection(s) NOW so that I can catalog the stuff and keep better track of it.

**Comment by campmlc** [comment]
Dusty, I would like to set up a teaching collection in object tracking, but
that also means allowing "division" and "collection" as valid container
types. Then we could have MSB " Division of Mammals" with " teaching
collection" nested beneath, or have "teaching collection" directly under
institution, as each institution chooses.

Right now we are forced to use " room" for divisions, e.g. MSB Mammals,
which doesn't work because the division itself contains rooms and object
tracking constraints will not allow a container to be nested in a container
of the same type.

**Comment by ekrimmel** [comment]
If I understand correctly, @Jegelewicz, we are suggesting and Dusty is on board with a single, multi-disciplinary teaching collection. So we might have CHAS:Mamm, CHAS:Bird, CHAS:Teach, etc.

I like this solution. I think it most accurately reflects the way we (at least at CHAS) manage teaching collections in reality, and I am also a fan of having the option to not publish teaching collection specimen data to aggregators, which this would allow very easily. Nothing wrong in general with publishing low-data specimen records, but where we get antsy is feeling like if we publish the existence of a specimen to the broader biodiversity research community, that specimen should exist if anyone finds our record and cares to request it. In reality, our teaching collection consists of specimens that we fully expect to wear out and, at some point, be discarded.

**Comment by campmlc** [comment]
That sounds reasonable, but it would not work for our institution. In our
case, each division has it's own teaching collection. So for us, I'd like
the option of using object tracking.
I think that there shouldn't be a problem with different institutions using
different protocols for this?

**Comment by ekrimmel** [comment]
@dustymc have we reached a point where we could have a 'teach' collection added? If so, we'll use it.

**Comment by dustymc** [comment]
> single, multi-disciplinary teaching collection or a teaching collection for each discipline

Whatever works for you.

>container type

#1002

> point where we could have a 'teach' collection added

http://handbook.arctosdb.org/documentation/catalog.html#collection-code
http://handbook.arctosdb.org/documentation/catalog.html#guid-prefix

I'd probably use the "host" collection code (because it's about the same sort of thing and probably has a lot of the data you'll need). I don't really care what you use for guid_prefix, as long as it's fairly short and contains a colon.

@lkvoong can create collections when you're ready for them.

**Comment by ekrimmel** [comment]
> I'd probably use the "host" collection code (because it's about the same sort of thing and probably has a lot of the data you'll need).

Sounds good to use host as a template. The host/parasite-specific attributes aren't necessary for educational specimens, and we'd like to add "unformatted measurements" as an attribute, but otherwise I think it'd be good to go.

> I don't really care what you use for guid_prefix, as long as it's fairly short and contains a colon.

@droberts49 and I like "Teach" (e.g. "CHAS:Teach:") but are open to other opinions.

Might this be a good time to clean-up and/or add really brief descriptions for the COLLECTION_CDE table? e.g. so far as I can tell the following aren't in use and are either covered elsewhere by other codes or (to me) inexplicable....

- Bryo
- Corr
- Crus
- ECDM
- Mala
- Moll
- Samp
- Tape

**Comment by dustymc** [comment]
>clean-up

Yes please!

>really brief descriptions

I'm not sure that's possible, but I can add it if so. That is, "Host" is really "random stuff about random stuff that nobody cataloged in a usable manner elsewhere" and just has a funny name because "hosts of parasites" got there first. Hosts of parasites (so, like, everything) are certainly not the only reason to have a "random stuff about random stuff that nobody cataloged in a usable manner elsewhere" collection, and I don't see much reason to maintain an extra set of code tables for another "random stuff about random stuff that nobody cataloged in a usable manner elsewhere" collection-type which isn't "hosts." Er sumthin.

These are not used. I'm happy to get rid of them if nobody has other plans.

```
UAM@ARCTOS> select collection_cde from ctcollection_cde where collection_cde not in (select collection_cde from collection) order by collection_cde;

COLLECTION_CDE
---------------
Alg
Bryo
Corr
Crus
ECDM
Moll
Paleo
Samp
Tape

9 rows selected.
```

**Comment by ekrimmel** [comment]
We intend to use paleo! Otherwise my vote is scrap 'em.

@dustymc are you saying to catalog teaching specimens in the existing host collection? I get why that's appealing from a streamlining-the-database perspective, but isn't the whole purpose of collection codes to be administrative? And administratively, a teaching collection is not the same as a bunch of "random stuff about random stuff that nobody cataloged in a usable manner elsewhere." Amph and Rept get to be distinct in addition to Herp, even though they all have overlapping attributes...

**Comment by dustymc** [comment]
> catalog teaching specimens in the existing host collection

NO, in a new collection which uses collection_cde "host" (so you have access to the random assortment of attributes-n-such linked to "host").

>collection codes to be administrative

No.

Collections are administrative/arbitrary.
GUID_Prefix ("collection's primary key") is administrative/arbitrary.
collection_cde is functional - it controls the code tables a collection can access.
collection_cde is NOT meaningful (more below)

>Amph and Rept get to be distinct

Amph and Rept could (now, anyway - maybe not when they were created) use the "Herp" collection code if they wanted - but that'd make "carapace length" available to salamanders (which may be viewed as a good tradeoff, or not).

If your teaching collection has no/loose taxonomic boundaries, then "host" (or maybe something new) collection code probably works best for you.

If you want a mammal teaching collection, it should probably use the "Mamm" collection code - unless you intend to do something weird that the mammal folks won't want to deal with (eg, add 900 attributes that nobody else will use), or if you don't want to deal with the stuff that's already there (eg, 900 weird bat and parasite attributes), in which case you could go your own way and make a "not-those-mammals" collection_cde populated with your own attributes-n-such.

I recently "normalized" the shared code table forms, so I think forcing people into existing collection_codes is not really important anymore - "liver" means the same thing wherever it's used, and adding it to a "mamm2" collection type wouldn't create a lot of extra work.

**Comment by ekrimmel** [comment]
Roger that, thanks for the explanation! We manage our teaching collection across taxonomic boundaries so are happy to use "host" or something new. I'm still advocating the latter--a new "teach" collection code--if for nothing else because it formalizes the idea of hosting teaching collections in Arctos.

**Comment by dustymc** [comment]
>formalizes the idea 

Fine by me - lemme know when you're sure and I'll make that collection_cde.

But....nobody without manage collection access to your collection will ever see it. This is a functional, meaningless, internal bit of data. I'm not sure how we'd announce to the world that some collection exists for teaching, but I don't see how it could be through collection_cde.

**Comment by ekrimmel** [comment]
> Fine by me - lemme know when you're sure and I'll make that collection_cde.

We're sure

> I'm not sure how we'd announce to the world that some collection exists for teaching, but I don't see how it could be through collection_cde.

Not to the world, just internally. We reference those codes and their associated attributes when we're migrating data into Arctos, e.g. we're going to stick our malacology collection data in an "inv" vs. "mala" collection because that's what DMNS is using and then both of us can coordinate on improving the existing attributes to cover our needs by adding age classes, etc. If another institution is doing something cool with the way they manage their teaching collection it's likely to show up in the way they manage their teaching collection data. The most basic, centralized way Arctos has of sharing that is via collection_cde.

**Comment by dustymc** [comment]
Fair enough.

@lkvoong  one CHAS:Teach collection please....

Collection code cleanup is now #1192

**Comment by ekrimmel** [comment]
@dustymc, you're the best, thanks! And thanks to you too, Lam!

**Comment by lkvoong** [comment]
@ekrimmel  CHAS:Teach has been created.  As usual, please log in to edit collection profile and assign operator privileges.

**Comment by Jegelewicz** [comment]
@dustymc @lkvoong may UTEP also have a TEACH collection!
Thank you!

**Comment by ekrimmel** [comment]
Much thanks @lkvoong!

**Comment by lkvoong** [comment]
@Jegelewicz 
UTEP:Teach has been created.  I also added it to the UTEP_ALL portal:
http://arctos.database.museum/utep_teach
http://arctos.database.museum/utep_all
Please log in to update the collection profile.

**Comment by Jegelewicz** [comment]
Everyone in this thread, please help with #1203

**Comment by Jegelewicz** [comment]
> But....nobody without manage collection access to your collection will ever see it. This is a functional, meaningless, internal bit of data. I'm not sure how we'd announce to the world that some collection exists for teaching, but I don't see how it could be through collection_cde.

So that means only myself and some curators can search the Teach collection.  I know this because I wanted a student to help me tag some things and she couldn't see it until I gave her access.  That is a bit unhelpful because I would like my faculty and grad students to be able to search this collection for things they need for classes.  Any other way we can handle this?  I don't want it published to the ipt (but I tell them what to publish, so I can leave it off - correct?).  I'd like it to be public on Arctos, but not show up anywhere else....suggestions?

**Comment by dustymc** [comment]
>So that means only myself and some curators can search the Teach collection

No, it means only you who have manage_collection access to the Teach collection can access the one form in which collection_cde is visible (Manage Collection). Access to the collection is the same as any other collection. Operators can only see (and "operate") collections to which they have assigned access. Anyone can see stuff in public portals. It takes ~24H for things to find their way to the public portal (which I think is the problem here??). Lemme know if that doesn't explain what's going on.

**Comment by Jegelewicz** [comment]
@dustymc Damn my impatient nature!  Sorry about that - i believe you are correct about the 24 hours and I should have remembered it.  Many apologies!!!

**Comment by dustymc** [comment]
I think this is all done - tentatively closing....
