### ISSUE TITLE
request new attribute - user-contributed comments

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#1162]
I would like to propose a new attribute for the EH collections specifically, but could be used possibly by anyone. If there is a better way of integrating this content, I'd be happy to hear suggestions.

Attribute type:
user-contributed comments

Documentation:
Comments associated with the specimen, contributed by users of the collection. May or may not be part of the original documentation. Submitted to or collected by collection staff and subject to curatorial approval.

Value = Comments submitted to collections staff
Remarks = verified by curator
Date = date submitted by user
Det. Meth = mode by which comments submitted/received (could be a drop-down list with values like: email; letter; phone call; in-person)
Determiner = name of the person submitting user-contributed content

Rationale:
The cultural collections of UAMN have a goal of collecting and preserving "intangible cultural heritage / local knowledge" as well as the material objects in our collections. A primary way we collect this information is through collection visits and conversations with Indigenous people or community members who have personal experiences with the objects or the people associated with the objects. The data collected with our collections is sometimes inaccurate or incomplete and while the results of academic and professional researchers is one way of adding information to our records, the anecdotal and personal stories shared by visitors to and users of the collection is another.

Currently information is recorded in the Remarks field. For example: [https://arctos.database.museum/guid/UAM:EH:0236-3951](url) indicates that the place of origin could/should be changed and that the basket "was probably made by an elderly lady." While the information regarding the place of manufacture can be qualified in the specimen/event remarks field, notions regarding the age of the maker does not fit anywhere.

Information contributed during consultations with Native researchers may be requested to be masked because it is inappropriate or potentially harmful for those not of the culture. Community members could request that the information be masked from public browsers. With the current practice of including this information in Remarks, all of the content in Remarks would be masked rather than only particular statements.

This request will be accompanied with another issue, to change the "Report Bad Data" button to say something more friendly and open-ended, like "Submit comments or questions about this record".

**Comment by dustymc** [comment]
>Report Bad Data

At least as a long-term goal, it might be worth looking at consolidating what you're requesting and the "annotate" function. Those are (sorta, I think) the same type of thing, seems useful to somehow get them in the same place. Annotations are not "encumbrance-able" and don't have the structure you're looking for, so I'm not sure that's a quick/easy/short-term solution.

>another issue

Yes please. "Report Bad Data" was originally (and the table name and probably some internal labels remain) "Annotations" - but "annotate" means something weird to botanists or something so we changed it in an attempt to reduce confusion.

And while you're thinking about it, there's a constant struggle to get people to click annotate (=something wonky about data on the page you're looking at) vs. contact (=something wonky not involving data) - suggestions always appreciated.


>Det. Meth = ... could be a drop-down 

Our one experiment in going there failed - turns out users (at least sometimes) prefer "used techniques in _Bla and Blah 2017_" over some generic categorization of those techniques. I'd still like to see some sort of control there, but I'm not sure how to go about it. (Good candidate for some sort of "let's all get together and figure this out" proposal?)

Otherwise, this looks reasonable/feasible to me.

And Media (PDF of the correspondence, audio recording, whatever) in support of these data would be cool when available....

**Comment by Jegelewicz** [comment]
@AJLinn is this still of interest to you? I was looking at old issues and I have now added this to the Code Table Committee Project, so it will stay more on my radar.  Maybe we can discuss at next Code Table Meeting!

**Comment by AJLinn** [comment]
yes please! Thanks for bringing it back into the sunlight. I think about this every time I get a letter from the donor that clarifies documentation or provides supplemental info or work with a researcher who provides cultural context and I have to dump it in Remarks.

**Comment by mkoo** [comment]
This would be used by the Archives, too.

**Comment by krgomez** [comment]
This would be super helpful!

**Comment by Jegelewicz** [comment]
> it might be worth looking at consolidating what you're requesting and the "annotate" function. 

Maybe a path to turn a comment into a value for this attribute?

**Comment by Jegelewicz** [comment]
I think I would change to simply

user contributed comments (no dash - which is subject to weirdness like we are experiencing in #2362 )

The other thing kinda bugging me is

Remarks = verified by curator

it feels as if this should be tied to an agent?

**Comment by Jegelewicz** [comment]
I say we add this - eventually a migration from "report bad data" to here might be cool - but let's see if that ever seems needed?

**Comment by Jegelewicz** [comment]
added for all collection types
