### ISSUE TITLE
"Please comment" button

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#1169]
Please add a new button at/near the top for users to click to "Comment on this Record." A new window would open like the annotate action, to submit an email to the official contact for that collection.

**Comment by dustymc** [comment]
Is this a REPLACEMENT for "report bad data"?

If so, vocab recommendations for multi-record datasets (eg, specimen results)?

FYI, "report bad data" makes the comment a permanent part of the record(s), in addition to the email notification.

**Comment by AJLinn** [comment]
I think it's a new button, based on your statement:
> FYI, "report bad data" makes the comment a permanent part of the record(s), in addition to the email notification.

What I want to see is an email that comes directly to me, rather than the whole group of people who get the emails submitted via the "Report a bug or request support" button at the bottom. Then I want to be able to review the content and make appropriate changes in the record, which I document as a response to a submitted request/comment.

**Comment by dustymc** [comment]
That's basically what the 'report bad data' button does (but it also works if the collection doesn't have a curator at the moment etc.)

I just clicked it for one of your specimens - you should have email.

**Comment by AJLinn** [comment]
I got the email. You mentioned this makes the comment a permanent part of the record. Where do I find that in the specimen record data?

**Comment by dustymc** [comment]
<img width="201" alt="screen shot 2017-06-09 at 12 38 04 pm" src="https://user-images.githubusercontent.com/5720791/26991759-83aaf41e-4d10-11e7-91dc-9526fbef0ebb.png">

red=1 unreviewed annotation

Click and at the bottom...

<img width="591" alt="screen shot 2017-06-09 at 12 38 26 pm" src="https://user-images.githubusercontent.com/5720791/26991770-8fdd93fe-4d10-11e7-8875-008c61e1231c.png">

**Comment by campmlc** [comment]
I think Comment on this Record is a good change that would include data
 reporting. Maybe change the vocab  to "Comment on this record or report
bad data".

**Comment by AJLinn** [comment]
Got it. I also see that annotations are there for everyone to see in the Reports/Annotations.

I think this is not be what I want to happen.
My proposal would prevent the comments submitted from being viewable by everyone who has access. This might be the beginning of a thread of information that folks would want masked. It also could contain information that needs to be validated by curatorial review. This annotation system also is a bit confusing for someone who has no database experience and is looking at a mask and wants to tell me that they've seen similar masks in their home community or that their grandfather made carvings that look just like one that is listed with a maker: unknown.

Am I providing enough of a justification to create a new button/action?

**Comment by dustymc** [comment]
>My proposal would prevent the comments submitted from being viewable by everyone who has access. 

Perhaps we should do that with annotations as well, but annotations also work for arbitrary datasets: I might annotate your mask by finding things involving some collector and saying you've spelled their name wrong or etc. And I think we're CCing DATA_REPORT_EMAIL (under manage/meta/global settings) in the hopes that SOMEONE will see this stuff, but that's easy to change. And see below....

>could contain information that needs to be validated by curatorial review.

Ditto annotations. (And if someone is submitting lots of annotations that consistently don't need reviewed, you might just make them an Operator.)

>s a bit confusing

One button is generally less confusing than two, especially when they both look like they do the same thing.

>grandfather

I don't think that's limited to cultural stuff either - people make all sorts of comments, some of them are obviously relevant (in which case we might want to update the "real" data), some less so (in which case we might just thank them and hope it helps someone out in the future). I like having the annotations public in case the less-relevant stuff does make more sense to some other user or at some other time or whatever.

Perhaps we should add a notice of that to the form. 

And the RBD button is right beside the "collection" link by design - users who don't want their comments public can click that, where they'll hopefully find some way of contacting you directly. (Maybe that should be part of the "this will be public" thing, if that should be a thing).

**Comment by dustymc** [comment]
These are the affected forms:

MediaDetail.cfm
MediaSearch.cfm
ProjectDetail.cfm
SpecimenDetail.cfm
SpecimenResults.cfm
SpecimenUsage.cfm
taxonomy.cfm

**Comment by Jegelewicz** [comment]
I see no issues with "Comment on this record or report bad data" on any of these forms except MediaSearch. A search form seems like an odd place for people to report anything. Also, would it make sense to have this available on Agent Detail pages like [this one](http://arctos.database.museum/agent.cfm?agent_id=1008959&agent_name=Arthur%20H.%20Harris)?

**Comment by dustymc** [comment]
>A search form seems like an odd place for people to report anything

It's also a search results form - eg, https://arctos.database.museum/MediaSearch.cfm?action=search&specimen_id=23812639

>have this available on Agent Detail pages 

Makes sense to me.

**Comment by Jegelewicz** [comment]
Cool.

**Comment by dustymc** [comment]
"Comment on this record or report bad data" doesn't make sense; this thing works for multiple records. I'll go with "Comment or report bad data" unless someone stops me.
