### ISSUE TITLE
Request for a report or downloadable file

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1195]
Dr. Harris has asked if there would be an easy way to print the details he gets when he completes the following search:
![search](https://user-images.githubusercontent.com/5725767/28040710-e24a2a04-6583-11e7-8f47-06a73139a7d3.jpg)

**Comment by Jegelewicz** [comment]
Incidentally, if the search results had a web address other than http://arctos.database.museum/SpecimenUsage.cfm could I just use that address to take someone to the list of Dr. Harris' work?  Man, that would be awesome!

**Comment by dustymc** [comment]
There's no print handler. You could save ("print") to PDF, but I doubt that's what you're asking for.

We could develop some sort of report, but I'm not sure how that might print. (Eg the interesting thing here might be that http://arctos.database.museum/guid/UTEP:ES:1-1197, which was cited in http://arctos.database.museum/SpecimenUsage.cfm?action=search&publication_id=10004548 which is from http://arctos.database.museum/project/a-new-leporine-from-the-chihuahuan-desert-late-pleistocene has a part "dentary," and that's about 4 clicks away from anything you might print. I'd sorta always rather just give users everything and let them decide what's important instead of pre-packaging what we think they'll think is important.) Just let me know exactly what you want to see if a report is something you'd like to pursue.

http://arctos.database.museum/SpecimenUsage.cfm?action=search&author=Arthur%20H.%20Harris is the URL you're looking for.

Search/Agents will get you to [https://arctos.database.museum/agent.cfm?agent_name=Arthur H. Harris](https://arctos.database.museum/agent.cfm?agent_name=Arthur H. Harris) which is a more comprehensive "list of Dr. Harris' work."

**Comment by Jegelewicz** [comment]
Actually, the print to pdf worked for him.  Thanks!
