### ISSUE TITLE
Teach collections need parts

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1203]
Since the Teach collections could include any object from any kind of collection, it needs access to all of the part names.  I tried to upload some teaching collection stuff today and nothing will load because there are no part names associated with Teach.

**Comment by dustymc** [comment]
Yes, that's what collection type does.

http://handbook.arctosdb.org/documentation/catalog.html#collection-code

I need a list of parts that you want associated with Teach and, if they're not defined, definitions. (Code tables can no longer be updated without definitions.)

http://arctos.database.museum/info/ctDocumentation.cfm?table=CTSPECIMEN_PART_NAME

This situation will exist across all type-specific code tables.

**Comment by Jegelewicz** [comment]
I guess I figured it would be likely that many of the part names will be needed, so why not add all of them.  If it is preferable to add as we need them, then here is what I need for now:

antler
egg
egg shell (dry)
feather
mounted skeleton
mounted skin
postcranial skeleton
skeletal element(s)
skeleton
skin (ethanol)
skull
study skin
tail
whole organism
whole organism (50% isopropanol)
whole organism (70% ethanol)
wing

**Comment by dustymc** [comment]
Definitions please. 

I'm happy to help, but I seriously have no earthly idea what "skeletal element(s)" is or how it might differ from the half-dozen or so other things that look to me like "we hacked something random off some critter" parts. I suspect the people who use it and search for it don't either, so now it's not possible to do much with undefined parts.

Definitions do need to work across all collection types - here's how these are currently used:

antler
--ES
--Mamm
egg
--Amph
--Bird
--Egg
--Fish
--Herp
--Rept
egg shell (dry)
--Bird
--Rept
feather
--Bird
--ES
mounted skeleton
--Amph
--Bird
--Hild
--Mamm
--Rept
mounted skin
--Bird
--Fish
--Herp
--Mamm
postcranial skeleton
--Bird
--ES
--Fish
--Herp
--Mamm
skeletal element(s)
--Bird
--ES
--Fish
--Herp
--Mamm
--Rept
skeleton
--Amph
--Bird
--ES
--Herp
--Hild
--Mamm
--Rept
skin (ethanol)
--Herp
--Mamm
--Rept
skull
--Bird
--ES
--Fish
--Herp
--Hild
--Mamm
--Rept
study skin
--Bird
--Herp
--Mamm
tail
--Bird
--Mamm
whole organism
--Alg
--Art
--Bird
--Ento
--Fish
--Herb
--Inv
--Mala
--Mamm
--Para
whole organism (50% isopropanol)
--Herp
whole organism (70% ethanol)
--Bird
--Fish
--Herp
--Host
--Mamm
--Para
wing
--Bird
--ES

It seems unlikely that a Teach collection will contain ~500 types of tissues, and I'd rather not have un-used parts looking like they're "claimed" - that complicates eg #1131.

**Comment by dustymc** [comment]
antler is used for cervids and pronghorn - not sure if we need an inclusive definition or to move pronghorn to "horn sheath" (or ??)

**Comment by Jegelewicz** [comment]
So I need to define all of these things that we are already using?  I am not sure that this should be up to just me!  Perhaps this needs to be labeled "Needs Discussion".

**Comment by dustymc** [comment]
> I need to define 

No, sorry, I'm not trying to put this all off on you. I'm just trying to stop digging, having found ourselves in the bottom of a hole...

I don't even really expect GOOD definitions at this point - we probably have too much background noise for that to happen - but if you can tell me something about why you want to use eg "wing" instead of the other wing-options it might lead to - well, I have no idea, but I hope somewhere better! (In that particular case I of suspect we have 9 ways of saying one thing, and if that's the case then getting rid of 8 of them is a pretty significant step.)

>Needs Discussion

Done.

**Comment by Jegelewicz** [comment]
Here is what I feel comfortable defining from my list.

antler - extensions of the skull grown by members of the deer family
egg (50% isopropanol) - whole ovum, stored in a solution of 50% isopropanol
egg (70% ethanol) - whole ovum, stored in a solution of 70% ethanol
egg shell (dry) - outer covering of an egg with contents removed
feather - any of the flat appendages growing from a bird's skin and forming its plumage, consisting of a partly hollow horny shaft fringed with vanes of barbs
mounted skeleton - articulated skeleton mounted for display
mounted skin - taxidermy mount for display
postcranial skeleton - skeleton excluding skull
skeletal element(s) - any parts of an incomplete skeleton
skeleton - complete skeleton, including skull
skin (50% isopropanol) - skin removed from body, stored in a solution of 50% isopropanol
skin (70% ethanol) - skin removed from body, stored in a solution of 70% ethanol
skull - cranium and mandibles
study skin - dry skin from which almost all of the body has been removed and replaced with cotton so that the final result resembles a bird lying on its back with its wings folded
whole organism (dry) - entire organism, air dried
whole organism (50% isopropanol) - entire organism or individual, stored in a solution of 50% isopropanol
whole organism (70% ethanol) - entire organism or individual, stored in a solution of 70% ethanol
wing (dry) - entire wing, dried

Finally, I propose we add:
**herbarium sheet - material that has been dried, pressed and mounted on a sheet**
to Teach as well as Herb collections.  I would much prefer that my pressed plant parts be herbarium sheets as opposed to "whole organism" as they are generally NOT the entire plant.

Comments, questions and additions are welcome, but I am trying to get my teaching collection up and running before the fall semester, so I hope we can get some of this resolved quickly.

**Comment by campmlc** [comment]
Teresa, some of this is in conflict with other collections usage, such as
skeleton, which has been used with skull as separate part. Also, study
skins can be mammals or other taxa. Antlers can be proghorn. Just points to
why we need definitions, but this shouldn't have to hold you up. I am
traveling with limited internet, but can try to add comments and
definitions over next week.
Mariel

On Jul 14, 2017 5:22 PM, "Teresa Mayfield" <notifications@github.com> wrote:

Here is what I feel comfortable defining from my list.

antler - extensions of the skull grown by members of the deer family
egg (50% isopropanol) - whole ovum, stored in a solution of 50% isopropanol
egg (70% ethanol) - whole ovum, stored in a solution of 70% ethanol
egg shell (dry) - outer covering of an egg with contents removed
feather - any of the flat appendages growing from a bird's skin and forming
its plumage, consisting of a partly hollow horny shaft fringed with vanes
of barbs
mounted skeleton - articulated skeleton mounted for display
mounted skin - taxidermy mount for display
postcranial skeleton - skeleton excluding skull
skeletal element(s) - any parts of an incomplete skeleton
skeleton - complete skeleton, including skull
skin (50% isopropanol) - skin removed from body, stored in a solution of
50% isopropanol
skin (70% ethanol) - skin removed from body, stored in a solution of 70%
ethanol
skull - cranium and mandibles
study skin - dry skin from which almost all of the body has been removed
and replaced with cotton so that the final result resembles a bird lying on
its back with its wings folded
whole organism (dry) - entire organism, air dried
whole organism (50% isopropanol) - entire organism or individual, stored in
a solution of 50% isopropanol
whole organism (70% ethanol) - entire organism or individual, stored in a
solution of 70% ethanol
wing (dry) - entire wing, dried

Finally, I propose we add:
*herbarium sheet - material that has been dried, pressed and mounted on a
sheet*
to Teach as well as Herb collections. I would much prefer that my pressed
plant parts be herbarium sheets as opposed to "whole organism" as they are
generally NOT the entire plant.

Comments, questions and additions are welcome, but I am trying to get my
teaching collection up and running before the fall semester, so I hope we
can get some of this resolved quickly.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ArctosDB/arctos/issues/1203#issuecomment-315470988>,
or mute
the thread

**Comment by dustymc** [comment]
I think I killed off "herbarium sheet" in the first place, so I suppose I need to object to its resurrection....

"whole organism" is often not the whole organism either - many of them have tissues removed etc. 

There's plenty of room to object to the word "organism" when talking about plants and squishy marine-things and etc. as well.

As always I don't much care about the specific terminology, but I think "herbarium sheet" and "whole organism" and whatever might get introduced if we get a slime mold collection all mean about the same thing ("most of the normal thing, prepared in the normal way...") and I maintain that users should not have to guess at our administrative decisions (eg, collection or collection-type specific vocabulary) to find what they're looking for.

All that said, this is about #800 on my list of part-priorities at the moment, and if having "whole-ish plant" and "whole-ish not-plant" somehow provide significant usability benefits for ya'll I can make that happen. 

Mostly so I don't forget: Some loosely-coupled apps create "whole organism" in Herb collections; those would need tracked down and adjusted if this goes through.

**Comment by ekrimmel** [comment]
My suggestions and a couple additions that we would need are below. I am fine with using "whole organism" for "herbarium sheet"...

| part name | description |
| --- | --- |
| antler | extensions of the skull *often* grown by members of the deer family |
| egg (50% isopropanol) | whole ovum, stored in a solution of 50% isopropanol |
| egg (70% ethanol) | whole ovum, stored in a solution of 70% ethanol |
| egg shell (dry) | outer covering of an egg with contents removed, ~air~ dried |
| *exoskeleton* | *external skeleton typically found in invertebrates* |
| feather | any of the flat appendages growing from a bird's skin and forming its plumage, consisting of a partly hollow horny shaft fringed with vanes of barbs |
| mounted skeleton | articulated skeleton mounted for display |
| mounted skin | taxidermy mount for display |
| postcranial skeleton | skeleton excluding skull |
| skeletal element(s) | any parts of an incomplete skeleton |
| skeleton | complete skeleton, including skull |
| skin (50% isopropanol) | skin removed from body, stored in a solution of 50% isopropanol |
| skin (70% ethanol) | skin removed from body, stored in a solution of 70% ethanol |
| skull | cranium and mandibles |
| *shell* | *protective armor that maybe be part of an exo- (as in Mollusca) or endo- (as in Testudines) skeleton* |
| study skin | ~dry skin from which almost all of the body has been removed and replaced with cotton so that the final result resembles a bird lying on its back with its wings folded~ *skin prepared by replacing organic matter prone to decay with cotton or similar inert material, then dried, often in a linear position to conserve storage space*  |
| *tooth* | *calcified structure found in vertebrate mandibles and used as a tool for biting, eating, etc. *|
| whole organism (dry) | entire organism, ~air~ dried *[ Maybe to include herbarium sheets: 'representative portion of or entire organism, dried'...? ]* |
| *whole organism (pinned)* | *entire organism, dried and mounted on a pin* |
| *whole organism (vial)* | *entire organism in vial, generally with preservation fluid.* |
| whole organism (50% isopropanol) | entire organism ~or individual~, stored in a solution of 50% isopropanol |
| whole organism (70% ethanol) | entire organism ~or individual~, stored in a solution of 70% ethanol |
| wing (dry) | entire wing, dried |

@dustymc only No. 800?! You must be having a slow week :)

**Comment by dustymc** [comment]
Done, except...

I did not add "shell" to the Teach collections or change the definition - using the same term for turtles and clams would make finding specimens difficult (and the clam-people got here first!). Should I add "plastron" and "carapace" to Teach?

Note that "whole organism (dry)" is NOT used by Herb collections - they use plain ol' "whole organism." Which brings us back to the longstanding question, what DO we mean by "thing" when we also have part "thing (prepared in the way you'd expect")? Other than making sure that most users don't find all of what they want....

Is "pinned" vs. "dry" really useful? Same thing but impaled, no? @DerekSikes

**Comment by dustymc** [comment]
>separated part fixation and storage vocab from part names

That's possible now: https://github.com/ArctosDB/arctos/issues/1119#issuecomment-298777350. I'm happy to move existing not-part-type data into either of those structures and out of part name if that's where ya'll want to go.

>condition

Condition is uncontrolled so you can put whatever you want in there, but "preserved in formalin" and "is rotten" seem like very different types of data to me and so probably deserve to be structurally separate.

>unmanageable

Agreed - SOMETHING needs to change!

**Comment by ekrimmel** [comment]
Thanks Dusty! 

> I did not add "shell" to the Teach collections or change the definition - using the same term for turtles and clams would make finding specimens difficult (and the clam-people got here first!). Should I add "plastron" and "carapace" to Teach?

Hear, and that makes sense. Yes, please on plastron and carapace.

> Note that "whole organism (dry)" is NOT used by Herb collections - they use plain ol' "whole organism." Which brings us back to the longstanding question, what DO we mean by "thing" when we also have part "thing (prepared in the way you'd expect")? Other than making sure that most users don't find all of what they want....

I would be pleased to stop putting part fixation/storage vocab in the part name. Seems like that's where a lot of our discrepancies between what each collection needs come from.

> Is "pinned" vs. "dry" really useful? Same thing but impaled, no?

IMO no, especially when our pinned specimens age, degrade, fall off their pins and get rehoused differently. I was just trying to follow part names that already exist in use in different types of collections, but am more than happy to stick to "whole organism (dry)" for pinned insects here.

**Comment by dustymc** [comment]
>plastron and carapace

done

>part fixation/storage vocab in the part name

https://github.com/ArctosDB/arctos/issues/1119#issuecomment-298777350

>"pinned" vs. "dry" 

I'm trying to avoid saying the same thing multiple ways "because that's how we've always done it" etc. - not-quite-the-same-thing because there's useful information in the difference is worth keeping.

**Comment by Jegelewicz** [comment]
Just uploaded my first batch of teaching specimens and they are stuck in the bulkloader with the following error:
; called from b_bulkload_parts: ORA-06502: PL/SQL: numeric or value error: character string buffer too smallORA-06512: at "UAM.TRG_CMPD_SPECIMENPART", line 15ORA-04088: error during execution of tri {snip...}

**Comment by dustymc** [comment]
I don't see them in the bulkloader - email me your data, please.

**Comment by ekrimmel** [comment]
May we please have a "whole organism (dry)" part added to TEACH? Or a "whole organism"? At this point I've lost track of where the parts discussion stands because it got sidetracked into genetic land priorities, so this is just a selfish request for a specimen stuck in our bulkloader.

**Comment by dustymc** [comment]
Done (with parens).

>"whole organism (dry)" or "whole organism"

And there's a preview of the next spreadsheet!

**Comment by ekrimmel** [comment]
thank you!

**Comment by dustymc** [comment]
CLosing - I think this is all done?
