### ISSUE TITLE
Add Borrows to Projects

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1220]
This is not an urgent issue and one that I would like to have a little discussion about.  I am trying to make use of Borrows so that people will stay on top of the things we have here at UTEP that belong elsewhere.  I would like to see a few changes to the borrow form and a bit more functionality associated with borrows. We also need documentation for all of it.  I have put myself on "document borrow" duty and I will try to get something up for how to create a borrow in the near future.  In the mean time this is what I would like to see happen to borrows:

1. If one Arctos institution loans specimens to another Arctos institution a borrow is generated for the borrowing institution automatically.
2. A simple way to document the items borrowed from non-Arctos institutions other than a block of text.  I would suggest an image of the loan form, but I believe that would make it public on TACC? Ideas welcome!
3. The ability to add a borrow to a project. (Maybe this exists, but I couldn't readily see it.)

If anyone else has requests or ideas about borrows in Arctos, let's discuss them here.
Thanks!!!

**Comment by dustymc** [comment]
>generated automatically

Possible, but I'm not sure how folks would feel about having borrows magically appear. Maybe a pull button to create borrows would be better? In either case, the loaning institution would need to "approve" (in general, or by setting the public flag, or ????) sharing what's generally internal data with another collection.

>media

http://handbook.arctosdb.org/documentation/media.html#accessibility

>add a borrow to a project

That exist structurally (borrows are just transactions), but I would need to know what borrows are supposed to DO/how you want to see them/what can be made public/etc. (Eg, you can't see any loan/accn data in projects, adding a loan/accn to a project just makes the specimens available to the project, and borrows don't generally have specimens.)

**Comment by ccicero** [comment]
The issue of borrows came up in a discussion with Dusty re: the Arctos Transactions webinar. 

"Local borrow number" has issues - same number repeated multiple times.
Only 59 borrows in Arctos.
Dusty wrote "My vague impression is that people want to use it, but nobody quite knows why they should or something."

Let's discuss at the December AWG meeting.

**Comment by AJLinn** [comment]
> add a borrow to a project
That exist structurally (borrows are just transactions), but I would need to know what borrows are supposed to DO/how you want to see them/what can be made public/etc. (Eg, you can't see any loan/accn data in projects, adding a loan/accn to a project just makes the specimens available to the project, and borrows don't generally have specimens.)

YES!!! I would love this - when we do in-house special exhibits we create them as a project (well, I haven't had a chance to do this yet since we've been in Arctos, but we _would_ do it!) and then we could track our incoming loans (i.e., "borrows") from private and institutional lenders. Right now I do this via my UAMObs:EH by assigning temporary numbers and keeping track of them in my file cabinet and my computer (I know... BAD system). Borrows would involve objects (we could borrow 1 or 20 items from single lenders; these could theoretically be Arctos-cataloged items or not) and we could either just maintain a list within the "Nature of Material" box or maybe have an associated media (PDF) of the images of the items, condition reports, or full loan form, which would list all the items, etc.

I'd like to discuss this at the December AWG meeting.

**Comment by Jegelewicz** [comment]
Reviving this because of [DISSCO](https://dissco.eu/content/technical-design-dissco), which plans to use a shared loan system for all participating institutions via [Synthesis+](https://www.synthesys.info/joint-research-activities.html)

**Comment by dustymc** [comment]
>shared loan system

We should have patented Projects 15 years ago....

**Comment by Jegelewicz** [comment]
DISSCO should just be Arctos...

**Comment by ccicero** [comment]
@dustymc @Jegelewicz 
I'm bringing this up again and increasing its priority because I just had to make two borrows to track incoming condor samples, and anticipate making more in the near future including tracking specimens collected on NPS property and 'loaned' to use for accessioning.  The numbering system makes no sense because there is no institution associated with the number that's auto-generated, e.g., 

![image](https://user-images.githubusercontent.com/967275/61657223-4f1e9200-ac77-11e9-804d-1e72e332fd07.png)

Adding borrows to projects is also a necessity!

There are two related issues, can these be merged?
https://github.com/ArctosDB/arctos/issues/1064
https://github.com/ArctosDB/arctos/issues/1063

**Comment by campmlc** [comment]
Carla, are you not accessioning NPS samples? I'd be interested to know how
you are using borrows in this instance.

**Comment by dustymc** [comment]
>The numbering system makes no sense

It's just a suggestion (and I have no idea where it came from). I'd think it would be best to use "their" loan number.

> tracking specimens...'loaned' 
>Adding borrows to projects

These don't make much sense to me. Borrows are text - there's no association with specimens, because they reference specimens that are probably not in Arctos. (There's some cross-collection usage for that, but that is arguably best just done via the loan so everyone's on the same page.)

Can you elaborate on what precisely you're trying to do?

**Comment by ccicero** [comment]
---> Carla, are you not accessioning NPS samples? I'd be interested to know how
you are using borrows in this instance.

This came up recently because of a Barred Owl project where researchers at U Wisc are collecting owls and depositing them in MVZ and CAS. They have permission to collect in Yosemite, and the national park folks would make any specimens from there on loan to us. We would eventually accession them, but I'd also want to enter that transaction as a borrow so we can track it including the NPS loan number.

I'd also want to attach that to the project for tracking purposes (both for us and the NPS).

---> **numbering system:** I'm ok with 2019.001.Bird etc. and have been using that (letting it increment automatically), but there are many entries for 2019.001.Bird so when I created the borrows it incremented one of them but the list doesn't indicate which institution goes with which number. The numbers should be like loans, MVZ:Bird 2019.001.Bird etc. There is also a place for the other institutional loan number, but it's nice to track with our number as well so we can say that we had 'n' borrows in 2019.

---> borrows and projects: Exactly what I said above re: the NPS specimens. Another example is a California Condor project that I just created, it will eventually be linked to a publication, we are getting tissue samples from other institutions (e.g., Peregrine Fund, San Diego Zoo) that we want to track and so I created borrows and also want to be able to link those transactions to the project.

**Comment by dustymc** [comment]
>numbering system

Gotcha - I can fix that.

>projects

I don't see any technical barriers, as long as we're all aware of the limitations of borrows (eg, no specimens, so they're not capable of doing the stuff projects are designed to do). We'll need to 

* add public_fg to borrows (projects are public)
* add a way to make the link to the borrow form
* add a display handler to the project page

If all that sounds reasonable, please flip this to 'next task.'

**Comment by Jegelewicz** [comment]
@ccicero do you still want this?

**Comment by ccicero** [comment]
YES. DO IT!
