### ISSUE TITLE
unable to link publication to taxonomic name

### ISSUE THREAD

**Issue by KyndallH** [ArctosDB/arctos#1221]
Margaret in the UAM Herbarium created a new taxonomic name and added a publication to support it (O'Brien and Horton 2000), but Arctos won't let her select the publication to add it as non-classification data. It would let her select other publications but not the one she created. She logged out and back in, and nope.

**Comment by dustymc** [comment]
What's the name?

**Comment by KyndallH** [comment]
Echinophyllum

**Comment by dustymc** [comment]
Selecting that pub is fixed and patched in. It was a little weird because that O'Brien has an apostrophe (which breaks javascript), most of the rest have "right single quotation mark" (O’Brien - just another unicode character) instead.

The search/pick still cannot deal with apostrophe, needs fixed.

The form is submitting on ENTER - should treat enter as tab and open the pick.
