### ISSUE TITLE
"431 -" error message when removing checked rows from specimen results list

### ISSUE THREAD

**Issue by gordonhlau** [ArctosDB/arctos#1229]
Often times when I try to remove checked rows from a specimen results list (such as an accession with X number of specimens) by selecting "Remove Checked Rows", I simply get a blank page that reads "431 -". I want to generate a useful URL that I can refer back to the accession at a later date that excludes all the specimens that I have already checked from the previous time, yet I keep getting a "431 -" message instead of an updated specimen results list. This also prevents Arctos from generating said useful URL that I can use as a "save point" on my current progress.

**Comment by dustymc** [comment]
There is a URL length limit which TACC can't further increase.

The data are in the URL at specimenresults due to numerous requests for a "portable" link. I can POST data of any length, but that's incompatible with allowing eg, copy/paste of the specimenresults URL.

I have no solution which doesn't break something for someone.
