### ISSUE TITLE
Add Parts to Teach Collections

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1235]
skeleton - Full skeleton including skull, may be fully or partially articulated

skeleton, partial - Partial vertebrate endoskeleton. See also skeleton, postcranial and skeletal elements.

skeleton, mounted - Articulated skeleton that is mounted for display.

skin, flat - Skin (including feathers, hair, scales) that is removed from the body, pinned flat and dried rather than stuffed with cotton.

skin, mounted - Taxidermy mount for display.

skin, study - Skin (including feathers, hair, scales) that is removed from the body and stuffed with cotton or similar inert material, preserved by drying (often in a linear position to conserve storage space, in contrast to a mount).

**Comment by dustymc** [comment]
skeleton=Full skeleton including skull, unknown preservation/preparation.

>skeletal elements.

Since you brought it up... WHAT IS THAT!?! I want to delete it; I think it's "partial skeleton" that doesn't sort properly. 

I also removed the "see also..." from the definitions - anything that can't stand on it's own should be merged into something that can.  "skeleton, partial" is now "Partial vertebrate endoskeleton, unknown preservation/preparation."

Otherwise, done.

**Comment by Jegelewicz** [comment]
@dustymc  I used skeletal elements to denote any "bunch of bones" that didn't constitute a full skeleton and hadn't really been described in my data.  I would not mind changing any of my parts listed as "skeletal elements" to "skeleton, partial".  I also prefer your definition for "skeleton, partial".  Thanks!
