### ISSUE TITLE
Search Agent Remarks?

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#1247]
UAM EH uses the Agent Remarks field a great deal to note important biographical information about people associated with our collections (e.g., vocation, places they've lived, media in which they work, manufacturing history of a company, etc.). Is it possible to add the ability to search the agent remarks as a "contains" search? We also note "UAM ethnology & history" in the agent remarks for those agents used by our collection, as a quick reference. It would be great to be able to pull up all the agents associated by our collection at one time.

Thank you for considering.

![agentsearch-ss](https://user-images.githubusercontent.com/17605945/29671388-e8d60c32-8895-11e7-9314-8541c3e52753.jpeg)

**Comment by dustymc** [comment]
I'll add remarks search - should be easy and useful. BUT, remarks cannot "pull up all the agents associated by our collection at one time." I've attached remarks for agents which act as collectors (from table collector, no specific role) for UAM:EH - there's nothing unifying in there, I'd expect that to get less consistent over time, and many of "your" agents do not have remarks data at all (possibly because they cross collections/were pre-existing).

If you can come up with an actionable definition for "agents associated by our collection" I can add a search for that as well. E.g., is an agent who acted as an author on a publication which is linked to a taxon used in an unaccepted ID by your collection "associated"? If so, this will not be straightforward (and we may not have the processing power to support it!) If "agents who appear in table collector" (or similar) is useful, I could add a "collected for collection(s)" (or whatever) dropdown.

[temp_uamehuagentremark.csv.zip](https://github.com/ArctosDB/arctos/files/1249415/temp_uamehuagentremark.csv.zip)

**Comment by AJLinn** [comment]
> I'll add remarks search - should be easy and useful. 

Great, this will be super handy.

> many of "your" agents do not have remarks data at all (possibly because they cross collections/were pre-existing).

IF my IMLS grant is funded, that will change over the next 3 years as it's a major focus of the project. Maybe we'll be able to come up with something as a result of that.

>  is an agent who acted as an author on a publication which is linked to a taxon used in an unaccepted ID by your collection "associated"?

I don't think so, in the way that I'm thinking of using this. It would be more like agent role "received from" in Accession or "collector/maker/preparator".

> If "agents who appear in table collector" (or similar) is useful, I could add a "collected for collection(s)" (or whatever) dropdown.

That sounds useful for sure. Thanks!

**Comment by dustymc** [comment]
To make sure this is clear, NO free-text field contents can support any sort of defensible (eg, you can trust the results) query. 

As long as we don't need to consider all of the infinite ways in which an agent can be (tenuously!) "associated" then I think a "does stuff for collection..." dropdown will be straightforward. How about collectors (https://arctos.database.museum/info/ctDocumentation.cfm?table=CTCOLLECTOR_ROLE) and transaction agents (https://arctos.database.museum/info/ctDocumentation.cfm?table=CTTRANS_AGENT_ROLE) for a start, and we can play with tuning from there?

**Comment by AJLinn** [comment]
Yup, that sounds great.

**Comment by dustymc** [comment]
done for next release
