### ISSUE TITLE
noncomplaint Agent

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1260]
I have received the message below at least 5 times in the last two days. I added an unampersanded variant (the old name Texas Agricultural and Mechanical University), and still get the message.  What do I need to do to make Arctos happy? (There is no such thing as Texas A and M University, but I added it anyway....)

Agents which may not comply with the Arctos Agent Creation Guidelines (http://handbook.arctosdb.org/documentation/agent.html#general-agent-creation-and-maintenance-guidelines) have been detected. If you are receiving this email, you have either created a potentially noncompliant agent or have manage_collection roles for a user who has created a potentially noncompliant agent. If you are a collection manager, please ensure that everyone with manage_agents rights in your collection has read and understands the agent creation guidelines. 
Please use the contact link at the bottom of any Arctos form if you believe you have received this mail in error, or if you wish to discuss the Arctos Agent Creation Guidelines. 
Please review the following agents and make corrections or additions as appropriate. 

Texas A&M University - Commerce 
   CreatedBy: Carl S. Lieb 
   Problem: no_unampersanded_variant 
-- 
Don't want these messages? Update Collection Contacts. 
Want these messages? Update Collection Contacts, make sure you have a valid email address. 
Links not working? Log in, log out, or check encumbrances. 
Need help? Send email to arctos.database@gmail.com

**Comment by dustymc** [comment]
Neato...

It's looking for a "REPLACE('&','and')" variant - I added "Texas AandM University - Commerce" which should get the scripts to stop complaining. 

There's no such thing as "Smith and Wesson" either, but users still search for it and operators create it rather than using "Smith & Wesson" - this is an attempt to get everyone where they need to be, not to be "correct." "Texas A and M University - Commerce" should do that, even if the scripts aren't yet smart enough to recognize it.

Leaving this open - scripts need adjusted to deal with non-separated ampersands.

**Comment by dustymc** [comment]
see also Tower & Lyon Co.

**Comment by dustymc** [comment]
Edit Agent now provides the alternatives which will satisfy the "funky agent" detector (added through #1350).
