### ISSUE TITLE
New higher geography needed for Solomon Islands

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#1275]
Pacific Ocean, Solomon Islands, Western Province, Ranongga Island
Pacific Ocean, Solomon Islands, Western Province, Kolombangara Island

And yes, islands are important!

**Comment by dustymc** [comment]
I made

Pacific Ocean, Solomon Islands, Western Province, Solomon Islands, Ranongga
Pacific Ocean, Solomon Islands, Western Province, Solomon Islands, Kolombangara

You should be able to create geography as well - just be paranoid about carefully following http://handbook.arctosdb.org/documentation/higher-geography.html#guidelines-for-geographic-terms-in-arctos.

SOME islands are certainly important, but there are a lot of the things, some of them aren't very big, many of them are very close to each other, etc. My question is if there is some limit where that becomes locality data rather than geography? I have two concerns:

1. Creating geography is some work, especially when it requires creating an authority (wiki page) first. Meh, whatever.
2. Is there any reason to think having an authority file for sometime hundreds of close-together [tiny Philippine islands, Keys, etc.] helps anyone find specimens? I suspect they'd be better served by something "bigger" - island group, sea, etc.

**Comment by campmlc** [comment]
Thanks! I don't have permission to create geography?
Also, some of these have Island as last term and some don't . . .

**Comment by dustymc** [comment]
You do now.

#1276 - I don't have time to deal with it now, hopefully someone will get it eventually....
