### ISSUE TITLE
Geography: minimum "size"?

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#1278]
I have a request to create "Wood Cay" in the Bahamas. It's a real place, but it is a small, apparently uninhabited island, and seems to be one of many (hundreds) such things in the area. It exists in Wikipedia, but is redirected to Abaco Islands (https://en.wikipedia.org/wiki/Wood_Cay).

The lack of a dedicated page on wikipedia prevents verification, and will probably do weird things to any future attempts at bringing the wikipedia article closer to specimens. The requirement to link a wikipedia page to geography has drastically reduced the number of duplicates created, and I believe generally improved the quality of geography data in Arctos.

It seems unlikely that specimens from Wood Cay are in any way *ogically distinct from specimens collected on any of the similar surrounding islands. (There are a half-dozen within a mile, and this is in reference to marine inverts which were probably not collected ON any island - #1107.)

I think "rounding off" this and similar geography to something of a more significant size - the island group probably makes the most sense here - would have little effect on how specimens are found, and would perhaps help keep our list of geography somewhere this side of infinity. I don't have firm guidelines in mind, but I do feel as if this and similar "insignificant" places may make more sense in specific locality than geography.

Thoughts?

**Comment by jtgiermakowski** [comment]
I think the requirement to link to Wikipedia is a good way to control quality, as you point out. I'm running into the same issue with Galapagos specimens right now because we have specimens from islets that are "insignificant" to most people (save the geologists and biologists). It looks like an argument of creating "Wood Cay" and corresponding Wiki entry vs. lumping the cay with the larger island. Do we actually have the coordinates and/or WKT extent of the cay? if so, add that to Wikipedia entry and to ARCTOS. It will be a chore to do that to the Galapagos islets as well, but ultimately result in a clean and complete set for those islands.

my three cents (adjusted for inflation)

**Comment by campmlc** [comment]
Tiny islands are relevant biologically, especially in the Bahamas, where
there has been considerable research on island biogeography in reference to
spider and anole populations.

On Sep 21, 2017 10:12 AM, "dustymc" <notifications@github.com> wrote:

I have a request to create "Wood Cay" in the Bahamas. It's a real place,
but it is a small, apparently uninhabited island, and seems to be one of
many (hundreds) such things in the area. It exists in Wikipedia, but is
redirected to Abaco Islands (https://en.wikipedia.org/wiki/Wood_Cay).

The lack of a dedicated page on wikipedia prevents verification, and will
probably do weird things to any future attempts at bringing the wikipedia
article closer to specimens. The requirement to link a wikipedia page to
geography has drastically reduced the number of duplicates created, and I
believe generally improved the quality of geography data in Arctos.

It seems unlikely that specimens from Wood Cay are in any way *ogically
distinct from specimens collected on any of the similar surrounding
islands. (There are a half-dozen within a mile, and this is in reference to
marine inverts which were probably not collected ON any island - #1107
<https://github.com/ArctosDB/arctos/issues/1107>.)

I think "rounding off" this and similar geography to something of a more
significant size - the island group probably makes the most sense here -
would have little effect on how specimens are found, and would perhaps help
keep our list of geography somewhere this side of infinity. I don't have
firm guidelines in mind, but I do feel as if this and similar
"insignificant" places may make more sense in specific locality than
geography.

Thoughts?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ArctosDB/arctos/issues/1278>, or mute the thread

**Comment by campmlc** [comment]
I agree with Tom

**Comment by dustymc** [comment]
We only have text in all cases to date, no spatial data.

If wikipedia is serving as quality control (and to reiterate, that does work well most of the time), should an article being deleted in wiki not have some effect on the Arctos record? Are redirect links better than no links? (Probably, but they make it impossible for me to confirm anything - I can't tell "deleted because the place doesn't exist" from "deleted because wikipedia is weird.")

Adding to wiki can be complicated for we casual users. I don't have the time or knowledge to do whatever it is that might stop the wikipedians from redirecting https://en.wikipedia.org/w/index.php?title=Balicasag_Island&redirect=no to https://en.wikipedia.org/wiki/Panglao,_Bohol (to use another frustrating example). http://arctos.database.museum/geography.cfm?higher_geog=Balicasag%20Island is still linked, sorta, but the result is anything but clear. 

Should we recruit an Arctos/Wikipedia ambassador? (Not it!)

I'm NOT proposing lumping, just a lack of creation. Geography would be:

* SomeIslandGroup
* SomeIslandGroup, SomeBigIsland

with "smallIsland" in specific locality under "SomeIslandGroup" - NOT under "SomeIslandGroup, SomeBigIsland"

**Comment by sharpphyl** [comment]
Bryan feels more strongly about adding islands to higher geography than I do but I don't think he's been able to access Github lately so he may not reply immediately.  Islands are, of course, particularly important to our marine collection. In this case, Wood Cay is, as Dusty points out, tiny and perhaps not distinct from many other cays in the area.  But our current higher geography for the Bahamas doesn't provide for island groups that would provide intermediate specificity. If we could add multiple island groups to island countries, that would be helpful.  In this case, selecting Abaco Island is misleading but only identifying the locality as the Bahamas significantly reduces the quality of the locality data.  Could we at least have an additional level for the Abacos as a group within the Bahama Islands?  

It also looks like there are already some tiny cays (non-Wiki supported) in the Bahamas that are in higher geography.  I assume we want to retain them as they are linked to a specimen record but it does make for inconsistency in application.

**Comment by dustymc** [comment]
>selecting Abaco Island is misleading

Yes, please don't do that! #1107 

>Abacos as a group within the Bahama Islands

That's what makes sense to me - end Geography and begin locality at some sort of "county-sized" named place. This one is easy: https://en.wikipedia.org/wiki/Abaco_Islands.

I'm not advocating any deletion at the moment; we do need to somehow react to authority changes, but not today. I'm not advocating policy - if for whatever reason some tiny speck of an island makes sense in light of your data/specimens/whatever, use it. (I don't see anywhere we could draw a hard line anyway.) I'm just looking for guidelines (and selfishly trying to avoid interacting with the Wikipedians, who scare me). 

I made West Indies, Bahamas, Abaco Islands, Bahama Islands in case it's useful. I'm not sure what to do about West Indies, Bahamas, Bahama Islands, Abaco - I'd move it under the new feature, but as far as I can tell there is no such thing as "Abaco Island" (without Great or Little), and I don't really want to deal with the Wikipedians there either....maybe it needs merged into the thing I just created?? @ccicero there's an MVZ:Bird involved.

**Comment by mkoo** [comment]
Bumping up Priority-- has this been resolved such that Wood Cay is included in Spec_Loc as part of the Abaco Islands group in HG. (my read on the discussion thread)?

**Comment by dustymc** [comment]
I think we've just gone the other way - by refusing an "authority" (however non-authoritative it might be) in https://github.com/ArctosDB/arctos/issues/1465 we are implicitly allowing anything to be geography. Nothing now stops me from creating my back yard as geography and linking it to https://en.wikipedia.org/wiki/North_America.

**Comment by Jegelewicz** [comment]
Island groups, islands, features, quad maps move to Locality Attributes eventually.

**Comment by dustymc** [comment]
#3272 has radically changed my view of this - closing for lack of interest.
