### ISSUE TITLE
Diaperia verna var. verna

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1300]
I added this variety and made an error. When I try to correct the error (it was entered as Diaperia verna var.verna) the edit page just keeps auto-adding a subspecies with Diaperia verna var.verna and then the bulkloader doesn't recognize the correct term.

First, apologies for introducing the problem in the first place.
Second, can we get this taxon to stop auto-adding a subspecies and correct it for good?

Thank you!!!!

**Comment by dustymc** [comment]
I fixed the name - I did not touch the classification.

If this happens again, PLEASE do not use the bad name.

The bulkloader only looks at name-in-classification; classification data cannot break it. 

See https://github.com/ArctosDB/arctos/issues/1188 regarding suggestions in the editor. tl;dr: they make more workable data than not having them, and I think we should get rid of that form entirely. (I think this was making bad suggestions because there was a bad name?? Not much I can do about that!)
