### ISSUE TITLE
Question about higher classification synonymies

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#1310]
Is there a way to fix a GBIF classification error that causes problems on higher taxon search in Arctos?

I want to search on Phylum Platyhelminthes, Class Rhopaliidae without getting arthropods in family Rhopalidae.  But GBIF must have some records somewhere with arthropods mistakenly in Rhopaliidae, because the classification shows up in Arctos for GBIF, although I can't find the records . I'm not familiar enough with GBIF to resolve this - does anyone else know?

**Comment by dustymc** [comment]
The "any taxonomy" option usually finds some false positives for one reason or another.

You can always search "your taxonomy" - http://handbook.arctosdb.org/documentation/taxonomy.html#searching. (Which often "includes" false negatives due to local data inconsistency.)

I don't think there's anything in class Rhopaliidae, but there are some family Rhopaliidae - same thing?? https://arctos.database.museum/SpecimenResults.cfm?family=Rhopaliidae

https://arctos.database.museum/name/Jadera#GBIFBackboneTaxonomy seems to be (part of?) the problem. https://www.gbif.org/species/2050226 - looks like they've fixed, but either haven't pushed it to GlobalNames or GlobalNames hasn't processed it or similar. Maybe file an Issue at https://github.com/GlobalNamesArchitecture

Related: https://github.com/ArctosDB/arctos/issues/1291. Data portal "repackaging" causes a constant stream of problems.

**Comment by campmlc** [comment]
Yes, I can file an issue with Global Names. And of course, family not
class. Too late at night.
