### ISSUE TITLE
geography cleanup: Italy

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#1320]
data are inconsistent

**Comment by ccicero** [comment]
Fixed except for the following:

- Sardinia:  geog_auth_rec_id=1005096 ---> merge into geog_auth_rec_id=10000855

- locality_id=1115650 ---> probably 'Cavallino-Treporti', not 'Carallino' ???

- locality_id=79775 ---> probably 'Gorgona Island', not 'Gorgoma Island' ??? if so, geog_auth_rec_id=10007894

- locality_id=79771 ---> probably 'Santa Marinella Beach, near Civitavecchia', not 'St. Marinella Beach, near Cintarecchia' ??? if so, geog_auth_rec_id=10000847

Once we fix these last two, we can delete geog_auth_rec_id=4959

- geog_auth_rec_id=10000858 ---> fixed localities (moved them to a different higher geog), tried to delete but getting a 'child record found' error although there should not be any more localities attached to this higher geog.

**Comment by dustymc** [comment]
>Sardinia

done

>locality_id=1115650

@jldunnum 

>locality_id=79775

annotated the specimen

>locality_id=79771

annotated the specimen

>4959

Is "Europe, Tyrrhenian Sea, Italy" wrong or just unused pending cleanup? If it's good I say keep it, if it's wrong I'll force those specimens to "Italy" and leave current geog in verbatim locality.

>child record found

Well that was fun...

the cryptic error is because a search term exists. You have to remove them and save to delete those, you have to escape the "probably yet another way of describing an island" thing to do that, and you have to force-use the source because it's a duplicate. Issue if you want to make that better. I vote "meh" because we very rarely delete geog.

Thanks for the cleanup!

**Comment by ccicero** [comment]
geog_id=4949:  Tyrrhenian Sea is valid but is part of the Mediterranean Sea
https://en.wikipedia.org/wiki/Tyrrhenian_Sea

So ok to keep, or change to Mediterranean Sea which is more well-known?

**Comment by dustymc** [comment]
Thanks.

https://github.com/ArctosDB/arctos/issues/1102

Our model isn't really sufficient for this. Mediterranean Sea exists (variously under continent/ocean Africa, Europe, and Atlantic),  Tyrrhenian is a "sub-sea," I don't see any way to both be consistent and find "Tyrrhenian" while searching on "Mediterranean," which probably ALL users would want (eg a user probably does not want "Mediterranean excluding Tyrrhenian" but that's all our data structure can support).

I have absolutely no idea what to do about that.

@sharpphyl ??

**Comment by mkoo** [comment]
Seems we've dealt with that before:
https://arctos.database.museum/Locality.cfm?Action=editGeog&geog_auth_rec_id=10007832

Add Tyrrhenian to Features to be consistent.

I am about to share the What is geography doc soon but we have not
sufficiently dealt with Features.

**Comment by dustymc** [comment]
>feature

Of course...

>consistent

https://github.com/ArctosDB/arctos/issues/1378

**Comment by sharpphyl** [comment]
Looking at the Mediterranean, we have already added a number of its sub-seas as Features:

Aegean Sea <http://arctos.database.museum/geography.cfm?FEATURE=Aegean%20Sea>		Mediterranean Sea <http://arctos.database.museum/geography.cfm?SEA=Mediterranean%20Sea> 					 					
Edit 10007833 <http://arctos.database.museum/Locality.cfm?Action=editGeog&geog_auth_rec_id=10007833>
https://en.wikipedia.org/wiki/Balearic_Sea <https://en.wikipedia.org/wiki/Balearic_Sea>
Specimens <http://arctos.database.museum/SpecimenResults.cfm?geog_auth_rec_id=10007833>	
Atlantic Ocean, Mediterranean Sea, Balearic Sea
Atlantic Ocean <http://arctos.database.museum/geography.cfm?CONTINENT_OCEAN=Atlantic%20Ocean>		Balearic Sea <http://arctos.database.museum/geography.cfm?FEATURE=Balearic%20Sea>		Mediterranean Sea <http://arctos.database.museum/geography.cfm?SEA=Mediterranean%20Sea> 					 					
Edit 10007838 <http://arctos.database.museum/Locality.cfm?Action=editGeog&geog_auth_rec_id=10007838>
https://en.wikipedia.org/wiki/Black_Sea <https://en.wikipedia.org/wiki/Black_Sea>
Specimens <http://arctos.database.museum/SpecimenResults.cfm?geog_auth_rec_id=10007838>	
Atlantic Ocean, Mediterranean Sea, Black Sea
Atlantic Ocean <http://arctos.database.museum/geography.cfm?CONTINENT_OCEAN=Atlantic%20Ocean>		Black Sea <http://arctos.database.museum/geography.cfm?FEATURE=Black%20Sea>		Mediterranean Sea <http://arctos.database.museum/geography.cfm?SEA=Mediterranean%20Sea> 					 					
Edit 10007834 <http://arctos.database.museum/Locality.cfm?Action=editGeog&geog_auth_rec_id=10007834>
https://en.wikipedia.org/wiki/Ionian_Sea <https://en.wikipedia.org/wiki/Ionian_Sea>
Specimens <http://arctos.database.museum/SpecimenResults.cfm?geog_auth_rec_id=10007834>	
Atlantic Ocean, Mediterranean Sea, Ionian Sea
Atlantic Ocean <http://arctos.database.museum/geography.cfm?CONTINENT_OCEAN=Atlantic%20Ocean>		Ionian Sea <http://arctos.database.museum/geography.cfm?FEATURE=Ionian%20Sea>		Mediterranean Sea <http://arctos.database.museum/geography.cfm?SEA=Mediterranean%20Sea> 					 					
Edit 10007835 <http://arctos.database.museum/Locality.cfm?Action=editGeog&geog_auth_rec_id=10007835>
https://en.wikipedia.org/wiki/Ligurian_Sea <https://en.wikipedia.org/wiki/Ligurian_Sea>
Specimens <http://arctos.database.museum/SpecimenResults.cfm?geog_auth_rec_id=10007835>	
Atlantic Ocean, Mediterranean Sea, Ligurian Sea
Atlantic Ocean <http://arctos.database.museum/geography.cfm?CONTINENT_OCEAN=Atlantic%20Ocean>		Ligurian Sea <http://arctos.database.museum/geography.cfm?FEATURE=Ligurian%20Sea>		Mediterranean Sea <http://arctos.database.museum/geography.cfm?SEA=Mediterranean%20Sea> 					 					
Edit 10007836 <http://arctos.database.museum/Locality.cfm?Action=editGeog&geog_auth_rec_id=10007836>
https://en.wikipedia.org/wiki/Sea_of_Sardinia <https://en.wikipedia.org/wiki/Sea_of_Sardinia> 							 						
Specimens <http://arctos.database.museum/SpecimenResults.cfm?geog_auth_rec_id=10007836>	
Atlantic Ocean, Mediterranean Sea, Sea of Sardinia
Atlantic Ocean <http://arctos.database.museum/geography.cfm?CONTINENT_OCEAN=Atlantic%20Ocean>		Sea of Sardinia <http://arctos.database.museum/geography.cfm?FEATURE=Sea%20of%20Sardinia> 					 						Mediterranean Sea <http://arctos.database.museum/geography.cfm?SEA=Mediterranean%20Sea> 					 					
Edit 10007837 <http://arctos.database.museum/Locality.cfm?Action=editGeog&geog_auth_rec_id=10007837>
https://en.wikipedia.org/wiki/Strait_of_Sicily <https://en.wikipedia.org/wiki/Strait_of_Sicily>
Specimens <http://arctos.database.museum/SpecimenResults.cfm?geog_auth_rec_id=10007837>	
Atlantic Ocean, Mediterranean Sea, Strait of Sicily
Atlantic Ocean <http://arctos.database.museum/geography.cfm?CONTINENT_OCEAN=Atlantic%20Ocean>		Strait of Sicily <http://arctos.database.museum/geography.cfm?FEATURE=Strait%20of%20Sicily>

So it would seem that the Tyrrhenian Sea would fit in here as a Feature.  It is one of the major sub-seas listed by Wikipedia.  (https://en.wikipedia.org/wiki/Mediterranean_Sea).  We also have Prince William Sound and a few other smaller water bodies in Features.

Am I missing something?  I don’t like subseas being in Features either, but I don’t see any other option right now.  If we decide to subdivide the Features, then “sub-sea” or “sea division” or whatever might make sense.

I do agree that we are totally inconsistent in whether seas and subseas are assigned to a continent or an ocean. Prince William Sound is in North America because it’s assigned to Alaska, not the Pacific Ocean.  My only question, is “can our users find our data either way?"

I see that I made an error on the list of seas that I sent you to add back on October 30.  The Black Sea is a sub-sea of the Atlantic Ocean, not the Mediterranean Sea.  https://en.wikipedia.org/wiki/Black_Sea.  Can you make that adjustment?  Sorry, my “copy, paste” got ahead of me.

Phyllis
  

On Dec 20, 2017, at 4:01 PM, Michelle Koo <notifications@github.com> wrote:

Seems we've dealt with that before:
https://arctos.database.museum/Locality.cfm?Action=editGeog&geog_auth_rec_id=10007832

Add Tyrrhenian to Features to be consistent.

I am about to share the What is geography doc soon but we have not
sufficiently dealt with Features.
