### ISSUE TITLE
add [unassigned] Caenogastropoda as an Order

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#1321]
WoRMS has several classifications that begin with [unassigned].  One is the order [unassigned] Caenogastropoda (temporary name) within the subclass Caenogastropoda.  http://marinespecies.org/aphia.php?p=taxdetails&id=382204

In using the hierarchical tool to update the Epitonoidea, the export was unaccepted because it lacked an order.  Each entry read "Variable variables. ORDER is undefined."  The correct order is  [unassigned] Caenogastropoda but I get this error message when I try to create it.  Error Executing Database Query.
[Macromedia][Oracle JDBC Driver][Oracle]ORA-20013: Save rejected: Invalid characters. ORA-06512: at "UAM.TRG_TAXON_NAME_BIU", line 6 ORA-04088: error during execution of trigger 'UAM.TRG_TAXON_NAME_BIU' 

Can you create this Order for us?  

Other unassigned classifications that we may need are:
Superfamily: [unassigned] Neogastropoda (temporary name) - http://marinespecies.org/aphia.php?p=taxdetails&id=746698
Family: [unassigned] Conoidea (temporary name) - http://marinespecies.org/aphia.php?p=taxdetails&id=432363
Superfamily: [unassigned] Vetigastropoda (temporary name)

**Comment by dustymc** [comment]
That is not taxonomy and does not belong in our taxonomy table. I suppose you can use it in classification data if you must, but I don't see the point.

The hierarchical tool doesn't care about ranks at all, and the classification loader doesn't require anything taxonomy (it does require some metadata), so I'm not sure what you're seeing there. Send me your data and a screenshot+URL of the error.

**Comment by sharpphyl** [comment]
Here's a screen shot of the errors I'm getting for the export of Epitonioidea.  This is what raised the question.  

![csv errors for epitonioidea](https://user-images.githubusercontent.com/15368365/32522300-0d4a5aea-c3d4-11e7-894a-7523c69a1d62.JPG)

This is the WoRMS entry for Epitonioidea within Arctos taxonomy.  They omit Order which is what I've been doing up to now
![worms entry in arctos taxonomy](https://user-images.githubusercontent.com/15368365/32522612-3e205fba-c3d5-11e7-85f2-6d951602e4e7.JPG)
.  

Next is screen shot of the error message I get when I try to add [unassigned] Caenogastropoda as a classification.  I assume it doesn't like either the brackets or having two words in the classification.

![error for unassigned caenogastropoda](https://user-images.githubusercontent.com/15368365/32522321-1f535926-c3d4-11e7-8289-5c427173ca81.JPG)

Lastly is the WoRMS entry for this order at the WoRMS website.  Until now, I have been omitting anything that is preceded by [unassigned].  I don't think we want Caenogastropoda to be both a subclass and an order so we need someway to indicate these superfamilies aren't yet assigned to an order within the subclass Caenogastropoda.  Or we need to be able to not have an ORDER or other classification levels where they have not yet been assigned.

![worms unassigned caenogastropoda](https://user-images.githubusercontent.com/15368365/32522440-7f804e26-c3d4-11e7-9fad-6f08903670a1.JPG)

**Comment by dustymc** [comment]
Thanks. I think the missing order thing has a band-air in the appropriate spot now.

Arctos proper is fine with unranked terms, but I have no idea how I might write a bulkloader which would both deal with unranked terms and be usable. I'm always up for ideas.

That error is ___NOT___ classification; that is taxonomy (taxon_name). Arctos (correctly!) doesn't think that looks like a taxon name. It considers a variety of factors in making that decision.

>Caenogastropoda to be both a subclass and an order 

Arctos proper doesn't care about ranks or consistency or much of anything else in classifications. Using "Someterm" in 50 different ways across 50 classifications is just fine (because that's the sort of data we get in - it has to be fine). Those data cannot be made hierarchical and so cannot exist in the hierarchical editor, and they're going to prevent people from finding specimens. Omitting them, or adding some weird parenthetical metadata, or maybe anything else you do will prevent finding specimens too. There is no solution - the data themselves are inconsistent. 

FWIW, I'd probably just make an executive decision - "we shall consider THIS as THAT" - and run with it. I think consistency and completeness are more useful than the apparent alternatives.

**Comment by sharpphyl** [comment]
Thanks.  That "missing order" error has disappeared so I think we'll be
fine with what we currently have in the classification.  We'll let the
[unassigned] taxa wait until they assign them somewhere and then we'll
update them.  I don't want to put Caenogastropoda anyplace but as a
subclass where I'm sure it's correct for our purposes.  Much too confusing
otherwise.

I think we can close this one now if you're ok with it.
