### ISSUE TITLE
accessions

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#1323]
@ccicero 

add a link from edit accn to public accn form - one by the "public" flag edit and another from near projects

from specimendetail for logged-in users, include links to both edit accn and view(public)accn

Add a public accn search form??

**Comment by dustymc** [comment]
Added links for next release. Not clear why a public search form would be useful, eg, what would it look like and who would use it? Dropping priority.

**Comment by ccicero** [comment]
This issue came up (when preparing Arctos webinar on transactions) because it wasn't clear how to find 'public' accessions. Dusty added a 'view accession' link from the specimen detail page. Now the issue is that when you're  logged in as a user to an accn you control through your collection, and click 'View accession', a message pops us saying 'Data restricted by Collection' if the accession is not public which is the default. This is not what one would expect for users who have permissions for that collection. 

Suggested change: display the link on specimen detail page only IF the accession is public.

**Comment by jtgiermakowski** [comment]
It seems that it should be "Edit ACC-X" for logged in users that have permissions to edit public/private and
"View ACC-X" for all cases where accession is public and "Data restricted by collection" when accession is private and user does not have any permission.

**Comment by dustymc** [comment]
edit+view links long implemented
