### ISSUE TITLE
Geology attributes hierarchical?

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#1356]
Is it possible to create a hierarchical system for geology attributes, e.g. formation, epoch etc so that if one level is entered that all higher levels are automatically generated and searchable?

**Comment by dustymc** [comment]
<img width="678" alt="screen shot 2017-12-12 at 8 48 39 am" src="https://user-images.githubusercontent.com/5720791/33897186-a91cac6a-df19-11e7-9584-9a8af6e0dbd2.png">

<img width="572" alt="screen shot 2017-12-12 at 8 48 47 am" src="https://user-images.githubusercontent.com/5720791/33897192-ad8dc3c4-df19-11e7-8429-3d7e1972d8b2.png">

<img width="676" alt="screen shot 2017-12-12 at 8 49 00 am" src="https://user-images.githubusercontent.com/5720791/33897201-b2901a84-df19-11e7-8422-99cb8f16374a.png">

<img width="496" alt="screen shot 2017-12-12 at 8 50 08 am" src="https://user-images.githubusercontent.com/5720791/33897215-b8984c76-df19-11e7-9b79-ed99f6d11d86.png">

**Comment by dperriguey** [comment]
@dustymc 
Can we make it so I can more easily edit the hierarchy for each specimen? Occasionally, when I edit the geology attributes it puts the new determination at the top (see below). I would like to be able to either move a determination up or down. 

![image](https://user-images.githubusercontent.com/32556913/63541117-a87a1b00-c4da-11e9-9da2-420c4a71042d.png)

**Comment by dustymc** [comment]
Ordering is Major Surgery territory.

I still don't understand how you're using that. Did someone (who can't be named?!?) say "Cretaceous" and someone else (also anonymous) say "Upper Cretaceous" and then again for "Cenomanian"? If not, what are you trying to do with those?

**Comment by dperriguey** [comment]
I have to go in and reenter every determination every time if I can't reorder. Usually in our legacy data, the person that collected it said, "Mancos Shale," for instance. If the data came from a certain area in New Mexico where the geology was refined or the locality is refined, I can say Mancos Shale Formation and give the range of chronostratigraphic age for that section. I said Cretaceous, because Mancos Shale are Cretaceous rocks. They are also Upper Cretaceous rocks for that matter. If the data give the member, then I can have it down to a single Stage/Age most times. This is important for downloading data. Because we have not set up geology attributes to be hierarchical (in the arbitrarily loose way they are) then I do it for each individual specimen. Sure someone can search Upper Cretaceous in Arctos and find Mancos Shale stuff, but that might not be so for other databases and someone downloading data may want to see how different subsets of data respond within their statistical models. It's important. I need to be able to simply move these around so they look clean. 

I really think you and I should skype about the larger issue. I'd hope that it could help clear this up. It's been almost a year and a half now that we've been discussing this in various ways on here.

**Comment by dustymc** [comment]
Yes there was some pow-wow that I hope I didn't miss - we definitely need to talk.

Re-entering things won't do anything for the order, except perhaps accidentally, and that should not necessarily be expected to survive a reload, much less a different query for a different UI. There is no order to geology attributes, period. I can easily sort by date-or-whatever, but "this one always appears before that one" is explicitly not part of the model.

The hierarchy is in http://arctos.database.museum/info/ctDocumentation.cfm?table=CTGEOLOGY_ATTRIBUTE.

A search for "Mancos Shale Formation" will find things explicitly identified to that term, and things which are contained within Mancos Shale Formation (so are the search term, just with more precision). That's this:

<img width="420" alt="Screen Shot 2019-08-22 at 12 25 40 PM" src="https://user-images.githubusercontent.com/5720791/63543630-1b35c700-c4d8-11e9-8fe3-afc0551e4dd6.png">

There's no link to cretaceous.

There IS a link from Cenomanian (is contained by) Upper Cretaceous (is contained by) Cretaceous (and up a couple more).

<img width="393" alt="Screen Shot 2019-08-22 at 12 28 10 PM" src="https://user-images.githubusercontent.com/5720791/63543750-589a5480-c4d8-11e9-99f1-3c90beee1f5f.png">

A "Cenomanian" assertion is implicitly a "Cretaceous" assertion; adding an explicit Cretaceous assertion isn't necessary unless that's reflective of the data.

**Comment by sharpphyl** [comment]
I don't need to be on the call as we only have, perhaps, <300 fossil specimens to database.  But I would love to see the geology attributes be hierarchical so that once I type in the formation name Caloosahatchee, the rest of the levels auto-populate just as they do when I type in Denver County.  I could also benefit from the knowledge of the rest of the Arctos community.
