### ISSUE TITLE
Check bulk taxonomy

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#1370]
I'm trying to check several hundred taxa to be sure they're already in Arctos prior to doing a bulkload.  I'm trying to follow the pre-bulkload directions but it's written in a language I don't speak well.  Is it possible to submit a .csv list of taxa in the pre_bulk_taxa?  Did I do that?  

![screen shot 2017-12-18 at 3 05 51 pm](https://user-images.githubusercontent.com/15368365/34130430-021471d2-e405-11e7-89fd-9aa65f52db21.png)

Don't think it was successful.
![screen shot 2017-12-18 at 3 03 33 pm](https://user-images.githubusercontent.com/15368365/34130439-0a97af36-e405-11e7-95c8-8ca537eda4d8.png)

If I were to categorize this, it's just a need for more/better training and instructions for non-database professionals.  Thx.

**Comment by ekrimmel** [comment]
I was just trying to figure out how to do this last week, so maybe can shed some light. You should be able to download a .csv file with only the TAXON_NAME rows that have issues (aka the taxa that do not exist in Arctos yet) by clicking on the "Download pre_bulk_taxa (396)" link. There are two paths from here...

**PATH A: Fix taxon names in your data**

Within the .csv that you downloaded, you can provide updated names to correct the affected rows in your data if, for instance, a name does not exist because it was misspelled. To do this, you need to 

1. fill in content in the column called (I think) "SHOULDBE" 
2. save the .csv file
3. uploaded your edited .csv file under the pre-bulkloader step 9 
<img width="347" alt="screen shot 2017-12-18 at 7 23 22 pm" src="https://user-images.githubusercontent.com/11165319/34135925-0d0908ea-e429-11e7-818d-f8ce02a19a9d.png">

4. click on the link in the pre-bulkloader step 10 named "repatriate the stuff you just reloaded" to correct the TAXON_NAME values in your own data per the edits you made to the .csv
5. go back to the pre-bulkloader step 4 and click the link for "Mark for pre-check" to refresh the results for step 7 (where you downloaded you .csv in the first place from)

**PATH B: Add taxa to Arctos**

This steps above are only really helpful if your names don't exist in Arctos because they are incorrect in your data. If the names in your data are correct but they just don't exist yet in Arctos--which it sounds like is more your problem--then you want to use the pre-bulkloader to identify what names need to be created. In this case, I would download the .csv file same as above, verify that all the rows are indeed valid names, and then send the file along to Dusty so that he can add those names in bulk. 

If you are only checking the existence of taxon names in Arctos, you could also use the taxon name checker available under "Reports-->Data Services-->Taxon Name Checker" from the Arctos homepage, but this tool does not work well for names that are anything other than genus + species (+ infrasp.)

**Comment by sharpphyl** [comment]
I really appreciate your help, Erica.  I tried your steps above without success BUT the Taxon Name Checker is exactly what I need and probably better for my purposes.  Thanks so much for alerting me to it.  Let's consider this issue closed.  Thanks!

**Comment by ekrimmel** [comment]
Good!

**Comment by campmlc** [comment]
This is helpful info. We should add this to the documentation.

**Comment by Jegelewicz** [comment]
I have to add and/or correct taxa with every batch of plants I upload. I just prepare my data and put it in the bulkloader which then tells me which taxa are problematic. I either download the .csv with all of the errors or take screenshots. I delete my data from the bulkloader then either correct my data or add the taxa if that is what is needed and then upload again. I like this process because the pre-bulkloader catches almost all of the problem data, from taxon misspellings to missing agents.  I never expect a bulkload to work the first time, I expect it to help me clean up my data even further.

**Comment by sharpphyl** [comment]
That's helpful information.  I didn't put anything in the bulkloader, just
in the pre-bulk-load-taxa field.  Next time I'll start with the entire csv
and see if that helps find problem data.  Thanks again for your help.

**Comment by dustymc** [comment]
move to https://github.com/ArctosDB/documentation-wiki/issues/59
