### ISSUE TITLE
add geology attributes to any geography search?

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#1397]
Should we?

What should it do - traverse hierarchies, direct-match, ??

Can we afford that?

**Comment by dperriguey** [comment]
I think so. If not, at least directions on where to go to be able to search. I'm still trying to familiarize myself with how stuff works on the structure side of things, so I'm not sure of what it should do. 

As a new user, I only knew how to find potential paleontological data through any taxon. I only knew this because I also knew that there were Alaska collections in here, so surely if I put in hadrosaur I should get a result. If I were a google searcher for paleontology collections and stumbled upon Arctos, unless it explicitly says somewhere where I'm supposed to go to search for geologic stuff on Arctos, I would go to another more user friendly site.

**Comment by dustymc** [comment]
>still trying to familiarize myself with how stuff works on the structure side of things, so I'm not sure of what it should do

Any Geog exists in part to deal with the fact that we partition geography data completely arbitrarily - same data, three collections (or 3 days of the week), they'll find three places for it. On top of that, we sometimes cram island group into feature, use geography as a reference (6000 miles E Hawaii....), etc. WE can't figure it out, users have no chance. That "field" also considers webservice data (georeferences and/or reverse georeferences) - it's not all things asserted by humans.

Geology looks pretty different to me - it's all in one place, it's all consistent, it's all assertions, and it never would have occurred to me that it would be seen as geography. (More like "depth" I'd think.)

That's not meant as how anything SHOULD work, just background.

>paleontology collections 

Mostly unrelated: things aren't that neat. http://arctos.database.museum/guid/UAM:Mamm:53942 is "paleontological data" in a mammal collection, for example. Users should not need to predict arbitrary administrative decisions (eg, where something is cataloged) to find material.

**Comment by dustymc** [comment]
Locality Attributes address this
