### ISSUE TITLE
Loan types need clear definition 

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#1412]
What's the difference between data loans and media loans (collections across Arctos are not consistently practised)? Can we come up with definitions that we can all agree and live with?
 - Data Loans - metadata only? (parts cannot be added to a data loan)
 - Media Loans - any digital imagery? (parts can be added to a media loan)
Input from other museums using media loans?

Once we have definitions, add a "info" button to loan.cfm!

**Comment by Jegelewicz** [comment]
I can see how the definition of media loan:

> Loan primarily involving media; specimen material or hard-copy archives may have been handled for digitizing purposes.

might be confusing. Did we send them a photograph or just a digital image of one? Since media should be a part of any particular record, we could loan physical media (and for art collections this could be really confusing!). Are media loans necessary? If we send someone a bunch of digital images of objects, isn't that a data loan? This might need a bit of discussion and ties in with the project thread. If items are digitized for a "media" loan, then using an in-house loan would make sense for the "handling" part and a data loan for the images sent. Both loans could be added to a project, or not, as any collection sees fit to handle it.

**Comment by AJLinn** [comment]
Dusty and I came up with media loans as a separate type to handle all of the image request loans I've been creating since our collection moved into Arctos. Previously I was using data loans for this type.

Currently, I use this whenever someone requests photographs for publication (my old database listed this type of loan as a "photo request". As the definition indicates, the image request typically includes only a transfer of a digital image file, but sometimes it might require that I pull and object and take a new photograph of it. It may also involve scanning of a photograph or slide, which is then transferred to the requestor as a digital image file. All of these actions are listed in the loan remarks or instructions sections. 

I personally don't really care what this type of transaction is called, but I prefer to not create two or three different transactions in order to cover the single request, unless this is considered the most accurate way to document the entire process. I should think we can collectively come up with something more efficient, however.

> Did we send them a photograph or just a digital image of one? Since media should be a part of any particular record, we could loan physical media (and for art collections this could be really confusing!). 

This type of loan in an art collection should be returnable, unless the media was copied onto a drive or sent as a video file, for example, and not expected to be returned to us, in which case it would still just be a media loan.

I'd be happy to discuss this at an AWG upcoming meeting.

**Comment by dustymc** [comment]
merge>https://github.com/ArctosDB/arctos/issues/1450
