### ISSUE TITLE
Add "not" operator to taxonomy search

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#1435]
Any way to add a boolean "not" operator (or other operators - "and' and "or" could be useful) to the Specimen Search page (or to the Specimens Results search)? I'd like to limit the extraneous results I get as a result of classification weirdness. For example, when I search on "Arthropoda" I get Acanthocephala, Trematoda, and Taenia as returns - I'd like to exclude these from the results. Not sure why these others are showing up - because there are Arthropod classifications that are just Animalia: Arthropoda?

Anyway, I'd like to be able to search for "Arthropoda not Acanthocephala not Trematoda not Taenia". Possible?

**Comment by dustymc** [comment]
Try Arthropoda in Phylum (or wherever you use it in your classification). I suspect you're in any taxa, I can dig deeper but I doubt we can afford (processors) more than "in string" there, and I think it would exclude what you're looking for here anyway.

I could probably do more in ID...

<img width="615" alt="screen shot 2018-02-12 at 10 26 38 am" src="https://user-images.githubusercontent.com/5720791/36112665-3f50b6ea-0fdf-11e8-97e2-d0b10ece3acb.png">

...but I don't think that's what you're asking.

Taxon pages should show why something's there.

https://arctos.database.museum/name/Taenia finds Arthropoda because...

<img width="857" alt="screen shot 2018-02-12 at 10 30 35 am" src="https://user-images.githubusercontent.com/5720791/36112856-cdf83c1a-0fdf-11e8-8d2d-7e14b099e651.png">

(and about a dozen more), for example.

**Comment by campmlc** [comment]
Yes, a Phylum search works much better. How does the "does not contain"
option work in ID? Can you show an example?

**Comment by dustymc** [comment]
it works the same as everything else - it's just ANDed on to the query.

<img width="764" alt="screen shot 2018-02-12 at 10 50 33 am" src="https://user-images.githubusercontent.com/5720791/36113712-97c64260-0fe2-11e8-8f77-bcaf7c9de475.png">

finds "things someone once thought should be called Mustela vison which aren't currently IDed as Mustela vison" (useful for taxonomy revisions and where this came from).

```
 SELECT 
   bla bla bla
FROM 
   flat 
WHERE 
   ...  AND 
   upper(flat.scientific_name) NOT LIKE '%MUSTELA VISON%' and
   anything-in-any-classification LIKE 'MUSTELA VISON%' 
```

http://arctos.database.museum/SpecimenResults.cfm?scientific_name=Mustela%20vison&scientific_name_scope=currentID&scientific_name_match_type=notcontains&taxon_name=Mustela%20vison&debug=1

will spit out the full SQL

**Comment by dustymc** [comment]
closing - please re-open+comment if this is still a problem
