### ISSUE TITLE
Scientific name for a slab of rock

### ISSUE THREAD

**Issue by dperriguey** [ArctosDB/arctos#1481]
@dustymc
@KatherineLAnderson
@Jegelewicz

I am wondering how we might address what to put in for a scientific name of a specimen record that is a rock which has many different types of fossils on it/in it? Any thoughts?

**Comment by KatherineLAnderson** [comment]
As far as I know, the best way to do this right now is to assign the specimen multiple catalog numbers, one for each identification.

**Comment by dustymc** [comment]
http://handbook.arctosdb.org/how_to/How-to-Use-Complex-Identifications.html
http://handbook.arctosdb.org/documentation/identification.html
http://handbook.arctosdb.org/documentation/taxonomy.html
http://handbook.arctosdb.org/documentation/catalog.html#understanding-cataloged-items

* catalog each of the fossils
* enter mineral taxonomy (if you care about the rock - you probably don't here) and use it in IDs
* use the "A {string}" formula - ID it as whatever you want ("slab of rock" works but isn't very informative), point to however many (biological) taxa you need
* some mix of that stuff

Cataloging each of the fossils is certainly "correct" from a repeatability standpoint - if I look at one of the fossils and cite it in a publication, this is the clear pathway to the next user being able to figure out what I looked at. Cataloged items are "things to which a Curator felt like giving a number for some reason" so the fact that they're all in the same rock doesn't really matter.

Reality might get in the way of that, so you could catalog the rock (get it into the system at least) and just recatalog the individuals (or "items of scientific interest") as they get loaned - about the same thing insect collections (those that want useful citations, anyway...) do with lots.

**Comment by AJLinn** [comment]
We have many "complex objects" in the ethnology & history collection at UAM and we just enter them as multiple identifications. See this parka for example:
http://arctos.database.museum/guid/UAM:EH:UA91-014-0001

**Comment by Jegelewicz** [comment]
I would go with the method @AJLinn suggests which is Dusty's "use the "A {string}" formula - ID it as whatever you want ("slab of rock" works but isn't very informative), point to however many (biological) taxa you need".

As for an identification, I don't think "slab of rock" is the best possible description. Do paleontologists or geologists have a name for rock embedded with multiple fossils? Matrix? Fossiliferous sandstone? Fossil conglomerate?

Fossil conglomerate seems like a pretty descriptive identification that would lead someone to check out the identifications included in the specimen. However, if you have an identification of the rock in which the fossils are embedded, then perhaps fossiliferous sandstone (or whatever the rock identification) would be even better.

**Comment by Jegelewicz** [comment]
Any chance we have thought about adding a "taxonomy" for cultural items? http://cco.vrafoundation.org/

See the Native American Basket example: http://cco.vrafoundation.org/index.php/toolkit/index_of_examples/category_examples_2_decorative_arts_and_utilitarian_objects/example_102_native_american_basket

**Comment by AJLinn** [comment]
> Any chance we have thought about adding a "taxonomy" for cultural items? http://cco.vrafoundation.org/

We've been talking about this for a while (since we started our migration process back in 2013). There are a number of good thesauri and standardized nomenclatures for cultural collections but either they are proprietary or not totally suitable for our collections. I'm certainly open to additional discussions!

**Comment by dustymc** [comment]
Screenshot of the parka's ID:

<img width="663" alt="screen shot 2018-03-15 at 5 24 07 pm" src="https://user-images.githubusercontent.com/5720791/37497477-b78d18a2-2875-11e8-9eec-2bab6c190b80.png">


>check out the identifications included in the specimen

Meh - if they get that far they'll figure it out. Linking taxa makes it discoverable - Probainognathia (http://arctos.database.museum/SpecimenResults.cfm?taxon_name=Probainognathia&guid_prefix=UAM%3AEH)   finds the parka because the ID uses Rangifer and http://arctos.database.museum/name/rangifer%20tarandus#ThePaleobiologyDatabase contains that term. The (uncontrolled and maybe misspelled) text string that gets entered into ID is just another path, rather than the only path.



>"taxonomy" for cultural items

http://handbook.arctosdb.org/documentation/taxonomy.html

>“Taxonomy” ... is “some formal naming system.” 

It should fit. (Finding something worth investing in seems to be the bottleneck - someone should convince GlobalNames that taxonomy doesn't stop at biology!)

**Comment by Jegelewicz** [comment]
> Linking taxa makes it discoverable

Agree, and my preference for things like the object @dperriguey describes would be to treat them like the parka.

> someone should convince GlobalNames that taxonomy doesn't stop at biology!

Yep!

**Comment by Jegelewicz** [comment]
Ran across this today - adding it for future discussion: http://network.icom.museum/cidoc/working-groups/lido/what-is-lido/
