### ISSUE TITLE
add agents directly from loans and data entry

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#1489]
It would be very useful to be able to add new agents directly into Arctos either when you are creating a loan or adding a record via data entry.

**Comment by AJLinn** [comment]
I've often thought it would be handy to have a direct link/shortcut on both of these pages (on the Create Accession Record page as well) to create an agent. 

However, I do worry about an excess of accidental duplicates because you don't go thru the process of looking for variations on the accepted name when you're at the Manage Agents page.  (e.g. I'm trying to enter John Smith as an agent when he's been added as John G. Smith as the preferred name)

**Comment by dustymc** [comment]
I'll just (somehow, I hope....) add a create option to the pick form, so it'll be available anywhere you can pick an agent.

The standard check/suggestions is built in to agent creation and will follow this. Please let me know if you discover duplicates that it's not catching, and do please read the "force agent creation" alerts and check anything that looks suspicious. (Let me know if you're willing to do that but aren't getting them.) Given those tools, and everyone with manage_agent rights having an intimate familiarity with http://handbook.arctosdb.org/documentation/agent.html#creating--maintaining-agents (right?!?), I think the benefit is worth any additional risk of duplicates this might introduce.

**Comment by dustymc** [comment]
It's "next task" = I think I have what I need to write code - just needs prioritized....

**Comment by campmlc** [comment]
I support prioritizing this.

**Comment by dustymc** [comment]
At some point we were going to prioritize via the thumbs-up thingee, which is useful for me because it's a sortable attribute (https://github.com/ArctosDB/arctos/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Next+Task%22+sort%3Areactions-%2B1-desc). There are also priority labels - I'm not sure the discussions on how we should be using them went anywhere, but if something somehow turns Priority-High red I'll probably work on it first....

**Comment by Jegelewicz** [comment]
Done and done. @AJLinn @ccicero please add your thumbs up!

**Comment by dustymc** [comment]
This is implemented. It won't be everywhere until https://github.com/ArctosDB/arctos/issues/732 is fully implemented, which occasionally takes a ridiculous amount of time (and sometimes not). Just open an Issue or comment there if something is causing problems, and I'll continue converting agent picks as it's convenient to do so.
