### ISSUE TITLE
Indent when creating a how-to document

### ISSUE THREAD

**Issue by KyndallH** [ArctosDB/arctos#1496]
I've been following the guide: http://handbook.arctosdb.org/how_to/How-to-Contribute-Content-to-Arctos-Handbook.html

but it doesn't say how to indent. I want it to look like this:
<img width="169" alt="screen shot 2018-04-09 at 1 55 53 pm" src="https://user-images.githubusercontent.com/16887896/38525167-c4813782-3bfd-11e8-9f2a-1f6aa7136bf7.png">

But it currently looks like:

<img width="889" alt="screen shot 2018-04-09 at 1 54 45 pm" src="https://user-images.githubusercontent.com/16887896/38525173-c864da48-3bfd-11e8-96c2-6dde13d181e6.png">

**Comment by dustymc** [comment]
https://github.com/adam-p/markdown-here/wiki/Markdown-Here-Cheatsheet#lists

**Comment by KyndallH** [comment]
How do you have two together?

So a ##### and *?

**Comment by KyndallH** [comment]
And can you put a link to the cheat sheet in the how-to guide on how to do a how-to guide? 

http://handbook.arctosdb.org/how_to/How-to-Contribute-Content-to-Arctos-Handbook.html

**Comment by KyndallH** [comment]
Okay, so I need to go work on some other stuff BUT I have a temporary solution on the how-to guide for today. We need them to be able to follow along with tomorrow's webinar but I *promise* I'll finish making it official later this week/early next. It is simply taking too long right now to figure out all the code I need. 

So I hit commit but it isn't showing up on the how-to guide page. Should I just wait for a bit? Or am I missing a step?

https://github.com/ArctosDB/documentation-wiki/blob/gh-pages/_how_to/start-object-tracking.markdown

**Comment by dustymc** [comment]
>How do you have two together?

Hu?

>link

It's about halfway down - "nt (see Markdown definition and Markdown cheatsheet"

>isn't showing up 

It takes a few minutes and requires a header

---
title: How To Do Anything in Arctos
layout: default_toc
---

**Comment by KyndallH** [comment]
Okay - I've added a header (or so I think I added the type of header you are talking about) but now it looks funky.

<img width="744" alt="screen shot 2018-04-09 at 3 22 09 pm" src="https://user-images.githubusercontent.com/16887896/38527930-d1538918-3c09-11e8-959e-9b7e61e67acf.png">

<img width="464" alt="screen shot 2018-04-09 at 3 22 14 pm" src="https://user-images.githubusercontent.com/16887896/38527932-d43d58a2-3c09-11e8-8d34-0a7c1a4bf05b.png">

You know why no one ever wants to contribute to the How-Tos??

Because we are not computer coding people and this consumes so much of my time trying to figure this out when I have a million other things I have to do and we are only doing this how-to documents out of the goodness of our hearts. **Grrr**

**Comment by dustymc** [comment]
http://handbook.arctosdb.org/how_to/How-to-Contribute-Content-to-Arctos-Handbook.html

find

<img width="766" alt="screen shot 2018-04-09 at 5 23 19 pm" src="https://user-images.githubusercontent.com/5720791/38529615-c0b10368-3c1a-11e8-8148-71f47fee3e82.png">

Copy, paste into the top of your doc, change the title and nothing else.

<img width="924" alt="screen shot 2018-04-09 at 5 34 04 pm" src="https://user-images.githubusercontent.com/5720791/38529845-3b4dd9f6-3c1c-11e8-9409-872dfd2f1bd3.png">

auto-pushes it to http://handbook.arctosdb.org/how_to/ which now links to http://handbook.arctosdb.org/how_to/start-object-tracking.html

https://word-to-markdown.herokuapp.com/ (first google result, no idea if it works) claims to convert word to markdown - I think there are converters for most every file format.

Or start an Issue, use the WYSIWYG editor, copy/paste to the how-to.

We're using this system because we decided (at the ABQ meeting a few years back) it was the most user-friendly thing out there. We should probably talk if the system is what's preventing people from contributing.

@mkoo @ccicero

**Comment by campmlc** [comment]
I agree that markdown is not intuitive and that a word conversion format
would get much more participation.

**Comment by KyndallH** [comment]
The converter somewhat worked and it may be must faster than me typing out all the code. Now 
 I would just need to go clean it up and add the links to the photos.

While it Markdown may be user-friendly after you learn to use it, a lot of us don't have the time to learn yet another computer program (language or whatever Markdown of this is).
