### ISSUE TITLE
licensing

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#1532]
From a recent MOU:

>By participating in the Arctos Consortium, the xxx agrees to the
Arctos statement on ownership and use of data (https://arctosdb.org/data/). The collections
also agree to license their data under one of three Creative Commons (CC) licenses, as
required by GBIF (http://www.gbif.org/terms/licences). The collections may have their own
policy on terms of use that supplements the Arctos statement and CC license. The collections
may choose separate licenses for data and media.

First, we should clarify that Media are individually licensed while collections are licensed as a whole.

Second, I do not think there is any legal basis for claiming a license can be "supplemented." The purpose of a CC license is to present legally-defensible (and machine-readable) terms of use. There's an entire section on Wikipedia dedicated to lawsuits lost by people who tried to "supplement" a CC license. Can we remove that section and re-do the MOUs that have been signed with that verbiage?

Third, I see no need to share a license across the data in Arctos and GBIF. They're very different data, they're deserving of different licenses. CC0-licensed encumbered data (eg, commercially-valuable endangered herp localities) may not be legally defensible, for example. (And it's likely expensive to find out the real answer.) We don't share encumbered data via DWC, so there's nothing to reveal there.

I'm obviously no lawyer, but this looks like it's unnecessarily putting "us" (I'm not sure who that is - whoever signs the MOU?) in a legally-precarious position. That's concerning, especially with the talks of creating some sort of entity for Arctos.

Thoughts?

**Comment by Jegelewicz** [comment]
> First, we should clarify that Media are individually licensed while collections are licensed as a whole.

That is covered on the data licensing and use page which states:

> Arctos media (image, audio, video) may be licensed differently from specimen data, and users must adhere to the media license if they wish to include media records in publications, reports, websites, or other means of dissemination.

However, the license and use information at https://arctosdb.org/data/ is directed to those USING data from Arctos and in my opinion, the reference in the MOU doesn't really make sense. Perhaps this wording should also be modified a bit and slapped right into the MOU.

> Second, I do not think there is any legal basis for claiming a license can be "supplemented."

I agree. I dislike this wording and would like to see it gone. You pick a license and that's it!

> Third, I see no need to share a license across the data in Arctos and GBIF.

I also don't see the need for the GBIF reference, especially since some of our collections will never be shared with GBIF and each collection has to decide to publish to GBIF and then will be subject to GBIF rules and standards.

As I have been working with Austin Peay on this, I began to wonder what this section was trying to accomplish. I think we want data in Arctos to be as public as possible but we aren't really saying that directly. I think this section could use a re-write, probably just to say that each collection will select one of the CC licenses available in Arctos but that they may encumber sensitive data and media will be assigned a license independent of the data license.

I'll try to work on a draft...Not sure how easy it would be to change previously signed MOUs where they exist - working with university administration is a huge pain.

**Comment by dustymc** [comment]
> I think we want data in Arctos to be as public as possible

I think we (justifiably!) want everything. We want people to use the data, but we also want them to provide useful citations (which means specific formatting etc.) when they do.

>select one of the CC licenses available in Arctos

CC is not currently a requirement - they can select anything from http://arctos.database.museum/info/ctDocumentation.cfm?table=CTMEDIA_LICENSE

**Comment by Jegelewicz** [comment]
> CC is not currently a requirement - they can select anything from http://arctos.database.museum/info/ctDocumentation.cfm?table=CTMEDIA_LICENSE

Then we just need to word the MOU to reflect that. Thanks!

**Comment by Jegelewicz** [comment]
@dustymc Can we move this issue to the new collections issues? I want to start an MOU template project there and this should be there.

**Comment by dustymc** [comment]
I don't know how if so - I'll just close this and open https://github.com/ArctosDB/new-collections/issues/37
