### ISSUE TITLE
Tagging media images

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#1537]
When adding TAGs to media images that have been linked to multiple cataloged items, it would be nice if you could just select one of the items from a list instead of searching for the item in a popup and then selecting. 
For example, I have uploaded the following image which contains 26 cataloged items (https://web.corral.tacc.utexas.edu/arctos-s3/acdoll/2018-05-17/CT_E1S12_01122016_front_label.jpg). In 'Edit Media' I was able to relate all items using the 'Add multiple "shows cataloged_item" records' options (very handy, btw). It would be great if this list of items came up on the tagging page and I could just go down the list, select an item, resize/reposition the tag box, add a remark, and then create TAG. Keeping the current method  ('create TAG type...' with the dropdown) would also be necessary to create any additional tags (e.g., comments) or add a missed cataloged item. 

![image](https://user-images.githubusercontent.com/12507297/40206941-4c4e4272-59ef-11e8-8d12-2ee9c919a413.png)

THANKS!

**Comment by dustymc** [comment]
http://arctos.database.museum/showTAG.cfm?media_id=10579618 is the public link to the TAGged image.

Good timing - see https://github.com/ArctosDB/arctos/issues/1519#issuecomment-387620667 - I think TAGs should probably auto-create "normal" Media Relationships; the TAG link between the specimen and Media and the Media Relationship link are more or less redundant, but people often make both because TAGs aren't as integrated as Media.

**Comment by acdoll** [comment]
The tagged view is nice so you can quickly scroll over the image and see what the specimen ID is (however, in a long list like this you have to scroll down the list to find the later entries). For additional functionality, it would be handy to be able to zoom in on the image from this page.

**Comment by dustymc** [comment]
Addressed via 1519?
