### ISSUE TITLE
Add Arctos titles to agent record

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1548]
Mariel and I want to add status items to agent records that designate agents as:

Arctos Working Group Member
Arctos Steering Committee Member
Officers, chairs, etc.

Or maybe this would be better in relationships? “Member of”, etc. with Arctos Working Group as the related agent.

We are attempting to make it easy to figure out who is working with the various Arctos governance groups without going outside of Arctos. We thought the statuses would be a good way to keep a history of who was doing what since they have associated dates. Suggestions are welcome!

**Comment by dustymc** [comment]
I think I like the general idea, but dates in a text field can't do date-things and adding two-sided terms to https://arctos.database.museum/info/ctDocumentation.cfm?table=CTAGENT_STATUS (a one-sided structure) seems a little weird. Perhaps some combination could work - AgentA has {relationship} to AgentB AND some status (which comes with a date and remark) clarifying. When the relationship is dissolved, another status entry could clarify that as well.

That's probably overkill for this use case - just delete the relationship when the person leaves the AWG - but might be useful in eg, figuring out if a person was collecting as part of some agency (which might have more data) or on their own.

(Just a new name as AKA or something might work for this use case - searching for "AWG" would find "AWG Member" and "AWG Chair" and .... IF we're consistent in formatting.)

I'm not opposed to adding more data (dates, remarks, whatever) to relationships either, but it seems like something that would be very easy to use interchangeably with status, and if we do that the data won't be discoverable. If we do, we should try to minimize any overlap between "relationship events" and status so that there's one clear path to searching those data. I don't see much conflict in the current data, so I think this would just be something to keep in mind going forward.

And I'd probably just use "employee of" (and maybe even merge that into "associate of" - https://arctos.database.museum/info/ctDocumentation.cfm?table=CTAGENT_RELATIONSHIP) - it seems unnecessary to add another term which carries about the same idea.

**Comment by dustymc** [comment]
merge>https://github.com/ArctosDB/arctos/issues/1873
