### ISSUE TITLE
Manually creating subsamples

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#1574]
Is it possible to manually create a subsample from a part without using the loan form? I have ectoparasite lots that were loaned out to be sorted by taxa and then returned. I'd like to keep the original part and barcode, as at least some had only one taxon and did not need to be divided into child containers. But others were divided into two or more children that were then returned to the collection.  So the issue is 1) can we have a tool to create subsamples = children, both via the specimen record parts edit and also via bulkload, and 2) can we track these parent child relationships in the same way we track parent/child for tissue subsamples. 
It seems like an easy way would be to add the ID of the parent part to the parts bulkloader?

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/1367

<img width="198" alt="screen shot 2018-06-19 at 7 18 29 am" src="https://user-images.githubusercontent.com/5720791/41603039-fd1b5aa8-7390-11e8-8af3-69118490f73e.png">

>parts bulkloader

We could do that by barcode, but not key.

**Comment by dustymc** [comment]
So add a "this part should be created as a subsample of the barcode you provide in this field" to the parts bulkloader, correct?

That said, I think what you're trying to do finally sunk in, and I think it's the wrong approach based on our (sound!) "catalog the item of scientific interest" advice. This is a great use case for lots (and it's what normally happens in entomology collections, AFAIK). You've got a jar of 50 "things that crawl around on dead rats" and don't have the resources to sort it - that's a "natural" lot. It goes out on loan, someone sorts it into "fleas," "the species of flea I'm working on," "ticks," and "IDK," then returns it (what happened here, I think). They should also sort "the species of flea I'm working on" into individuals, and those should be recataloged so that they have a citatable ID. (I think some collections would send them a bunch of barcodes and provide catalog numbers for them as they sort.) All of those things should get a "same lot as" relationship back to the original (probably the "IDK" lot). The original will eventually have no parts (as "IDK" gets sorted out into individuals with better IDs), but it's still useful to glue everything together. The original lot may end up with hundreds of relationships (which should all be reciprocated).

If you skip the "catalog individuals individually" step you end up with uncitable data - not so different than what fish "traditionally" do, where "ABC:XYZ:1" refers to a bunch of individuals (which eventually turn out to be cryptospecies or something fun) and you end up flailing around in part remarks or something looking for some distinguishing feature that may not exist.

https://en.wikipedia.org/wiki/Replication_crisis

When one of the former lot-members, now cataloged as an individual, is hacked up (genitalia preparation, tissue sample, etc.) THEN you need "this part came from that part" functionality.

**Comment by campmlc** [comment]
Yes, I agree that ultimately the goal is to catalog all separately. But we
need the option of creating the subsample in the short term. In this case,
the "lots" of parasites are still parts of the host, and are being loaned
out by the host collection to students for initial sorting to phylum. Once
the initial sorting is done, they will be loaned out again to experts in
each major group for further identification, and then will be returned to
be cataloged in the parasite collection. Tracking all this is a nightmare
without parent/child relationships between parts; these will ultimately
become new cataloged items. I'm hoping this new tool, as you've described,
will help bridge the transition.

**Comment by dustymc** [comment]
rebuild bulk part subsample tool in component loader format
