### ISSUE TITLE
WIDE media column in search results

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#1579]
All of a sudden this afternoon my search results column with Media is resizing to be very wide:
![media_searchss](https://user-images.githubusercontent.com/17605945/41752284-12f6f808-7573-11e8-90af-4a6ca5e65235.jpeg)

Did I do something to make this happen? Can you help me figure out how to resize? Grabbing the column header and dragging does not seem to do it. Prior to today I'd get a scroll bar and the images would stack vertically, which I greatly prefer!

**Comment by dustymc** [comment]
URL?

**Comment by AJLinn** [comment]
> URL?

Of my search results? Here's my full window. Notice sometimes I get an error relating to the JSON. That happened more noticeably when I'd sort results by a different column (e.g., specific locality).

![media_searchss2](https://user-images.githubusercontent.com/17605945/41756916-6b853878-758b-11e8-9558-6c244c21393b.jpeg)

**Comment by dustymc** [comment]
Yes - just click show/hide search terms then requery, or make an archive or saved search. It's almost certainly something related to specific Media, I need to see what you're seeing to have much hope of finding it.

**Comment by AJLinn** [comment]
https://arctos.database.museum/saved/Cameras

![media_searchss3](https://user-images.githubusercontent.com/17605945/41757194-f6fd063c-758c-11e8-8625-d73e8fa2c953.jpeg)

**Comment by dustymc** [comment]
Thanks, that's what I needed.

String objects in Oracle are limited to 4000 characters. There's a workaround (CLOBS instead of strings), but I'm a little hesitant to push >4000 characters (usually with some sort of multiplier - like number of specimen records in a result set) to users/browsers. CLOBs can carry 128TB or something crazy - they're capable of doing evil things to browsers (and networks and internet bills). Maybe I'm just being paranoid - I could certainly be convinced to try a "bigger" datatype. (And some other stuff - localities, parts, etc. - has a similar limitation.)

The JSON representation of the Media for http://arctos.database.museum/guid/UAM:EH:UA77-029-0003AF (http://arctos.database.museum/MediaSearch.cfm?action=search&specimen_id=23832251) is >4K characters, so the converter just returns...

```
[{"STATUS":"Error Creating JSON"},{"MEDIA_ACCESS_URL" : https://arctos.database.museum/MediaSearch.cfm?collection_object
_id=23832251"}]
```

which displays as text and downloads as a link to the media detail page. It's a long string and my browser (and probably yours) doesn't like to wrap it, so it's forcing that column to be wide. I added a space which should help a bit (and adds to the character count...).

https://github.com/ArctosDB/arctos/issues/1519#issuecomment-388151201 is a request by @ccicero to add more stuff to the JSON and is likely to have the same problem, depending on the contents of "more stuff."

Wat do?

**Comment by AJLinn** [comment]
> The JSON representation of the Media for http://arctos.database.museum/guid/UAM:EH:UA77-029-0003AF (http://arctos.database.museum/MediaSearch.cfm?action=search&specimen_id=23832251) is >4K characters, so the converter just returns...

What is causing that to be so long? Is it because there are 18 media files associated with that one item?

**Comment by dustymc** [comment]
>18 media files

That's a multiplier so yea, but mostly that's just sort of how cross-platform communication tends to work.

Here's the data for whatever was in the top of my last download:


```
[
  {
    "MEDIA_ID": "10566392",
    "MEDIA_TYPE": "image",
    "PREVIEW_URI": "https://web.corral.tacc.utexas.edu/UAF/arctos/mediaUploads/20170607/tn_UA2001_014_0013_0014_0023.jpg",
    "MEDIA_URI": "https://web.corral.tacc.utexas.edu/UAF/arctos/mediaUploads/20170607/UA2001_014_0013_0014_0023.jpg",
    "MIME_TYPE": "image/jpeg",
    "MIMECAT": "image"
  }
]
```

It's around 300 characters, about 200 of them in the two URLs.

There are a bunch of flavors of JSON, I'm using the most verbose (it's also the most human-readable, which turns out to be useful/critical for this). MEDIA_ID etc. would be repeated for every media record - about 70 unnecessary (for machines, not humans!) characters per Media.

That's the absolute minimum information I need to do something with the Media and get folks to where they want to be. It's not enough to do that in the downloads - they have to know what to put in front of media_id to get metadata.

I guess I'm sort of leaning towards something that'll support more data for more Media. 18 doesn't seem like a lot, we should certainly stuff one more URL in there for the downloads to be at all useful, and the idea of adding a bunch of metadata directly to the downloads doesn't seem unreasonable. 

???

**Comment by dustymc** [comment]
It seems I was wrong: I don't think it's possible to mix a CLOB in with strings. I could do that in the application server, but there will be performance issues. 

Currently: Query the DB (one call), it compiles some stuff, returns it, then CF unwinds the JSON and turns strings into images and all that jazz. Download just converts the "compiles some stuff" to text/csv.

Possible: Query the DB (one call), it compiles some stuff, returns it, then **CF makes another DB call for every row to fetch Media stuff. Download makes another fetch of every row to get the media stuff again.**

I __think__ we can support that for the most part. Large queries with lots of Media are likely to break something (or just never get around to completing), but I think those are relatively rare. It's some code changes, rather than just the new back-end plugin that I was hoping could work.

Needs AWG discussion?

**Comment by AJLinn** [comment]
It happened again. What were we supposed to do to fix this? Sorry, I got lost in the tech talk of it all...
For this search it was the output of the objects associated with Loan 2017-11.EH.

![ss_widemedia1](https://user-images.githubusercontent.com/17605945/42775592-365a93dc-88e1-11e8-8f2e-6a39e9576c3e.jpeg)
![ss_widemedia2](https://user-images.githubusercontent.com/17605945/42775593-36723d70-88e1-11e8-877e-0902b3e42e6a.jpeg)

**Comment by dustymc** [comment]
I think this needs AWG discussion in conjunction with https://github.com/ArctosDB/arctos/issues/1519#issuecomment-388151201.

This is essentially a request to put less information in the specimen-media column (so it can be packaged as JSON and displayed as images).  #1519 is a request to put more information in the specimen-media column (so users can download media-data with specimen records). A workaround would be to get rid of that pre-packaged column altogether and build it on the fly, but there are two potential problems:

1. that's computationally-expensive, and
2. the result may be very large, which may break something else.

**Comment by AJLinn** [comment]
@dustymc I had another group of records messing with my column width with my media previews on search results screen:
![screen shot 2018-12-03 at 1 14 43 pm](https://user-images.githubusercontent.com/17605945/49404996-a1696d80-f6fd-11e8-8fb5-4927de794843.png)

This is a group of records resulting from an Accession search for agent: Rasmuson and then I clicked on [View 61 Specimens].
The offending records were these guys at the bottom (It is actually probably just this one: http://arctos.database.museum/guid/UAM:EH:UA2015-018-0001AU because it has 42 images attached as media). Is this something we can discuss as part of the Media Committee and then bring a recommendation to the AWG? I guess I'm too unsophisticated in terms of what the problem is and what your ideas are for solving it.

**Comment by dustymc** [comment]
<img width="645" alt="screen shot 2018-12-03 at 2 27 42 pm" src="https://user-images.githubusercontent.com/5720791/49405564-a3d0c500-f707-11e8-8b78-ea0601addfa4.png">

if I click that, remove checked rows, it comes back as text and then after a little grinding...

<img width="704" alt="screen shot 2018-12-03 at 2 28 59 pm" src="https://user-images.githubusercontent.com/5720791/49405623-cb279200-f707-11e8-88c8-d5ca117f3370.png">

That error occurs when I have >4KB in the JSON. Oracle 12 has higher limits (32KB I think), so I'm tagging this infrastructure-limited. In the meantime anything that results in fewer characters (just ignore the whole thing?? Seems a bit evil...) should fix the display problem, and I'm very up for clever ideas.

**Comment by AJLinn** [comment]
Is there any way for us to manually select one image for the preview on search results? Maybe make it a checkbox in the media details ("check this box to show on search results")? It could be on by default and we uncheck it when we have LOTS of media to attach?

**Comment by dustymc** [comment]
>manually select one image for the preview 

Anything's possible, but that doesn't seem very friendly to me. Among other things, the point at which "LOTS" starts is variable - it depends on the length of URLs (including filenames), the existence of previews, the current Oracle environment, what we include in the JSON (which is always evolving - see https://github.com/ArctosDB/arctos/issues/1519#issuecomment-388151201), etc. etc. etc. 

A "too long" record looks like this

```

UAM@ARCTOS> select getJsonMediaUriBySpecimen(collection_object_id) from flat where guid='UAM:EH:UA2015-018-0001AU';

GETJSONMEDIAURIBYSPECIMEN(COLLECTION_OBJECT_ID)
------------------------------------------------------------------------------------------------------------------------
[{"STATUS":"Error Creating JSON"},{"MEDIA_ACCESS_URL" : https://arctos.database.museum/MediaSearch.cfm?collection_object
_id=25756821"}]
```

A "normal" record like this:

```
UAM@ARCTOS> select getJsonMediaUriBySpecimen(collection_object_id) from flat where guid='UAM:Herb:190896';

GETJSONMEDIAURIBYSPECIMEN(COLLECTION_OBJECT_ID)
------------------------------------------------------------------------------------------------------------------------
[{"MEDIA_ID":"10106171","MEDIA_TYPE":"image","PREVIEW_URI":"https://web.corral.tacc.utexas.edu/UAF/ala/2010_03_19/jpegs/
tn_H1005544.jpg","MEDIA_URI":"https://web.corral.tacc.utexas.edu/UAF/ala/2010_03_19/H1005544.dng","MIME_TYPE":"image/dng
","MIMECAT":"image"},{"MEDIA_ID":"10121589","MEDIA_TYPE":"image","PREVIEW_URI":"https://web.corral.tacc.utexas.edu/UAF/a
la/2010_03_19/jpegs/tn_H1005544.jpg","MEDIA_URI":"https://web.corral.tacc.utexas.edu/UAF/ala/2010_03_19/jpegs/H1005544.j
pg","MIME_TYPE":"image/jpeg","MIMECAT":"image"}]

```

The expected components to process in specimendetail are...
```
{
    "MEDIA_ID":"10106171",
    "MEDIA_TYPE":"image",
    "PREVIEW_URI":"https://web.corral.tacc.utexas.edu/UAF/ala/2010_03_19/jpegs/tn_H1005544.jpg",
    "MEDIA_URI":"https://web.corral.tacc.utexas.edu/UAF/ala/2010_03_19/H1005544.dng",
    "MIME_TYPE":"image/dng",
    "MIMECAT":"image"
}
```


what if as the "too big" error handler we...

* create a default "it doesn't fit" thumbnail, similar to the defaults - http://arctos.database.museum/images/noThumb.jpg (images) or http://arctos.database.museum/images/audioNoThumb.png (audio)
* use that for preview_URI
* use the search results page (from the current error) as the media_uri (https://arctos.database.museum/MediaSearch.cfm?collection_object_id=25756821)
* find a way to fake or ignore the rest

So the error handler would essentially be a visually-distinct pointer to a group of Media, structured identically to any other "found some Media" option, rather than the current thing that points to the same place but isn't processed or structured the same way as everything else and just generally isn't nice to pass around.

???

**Comment by dustymc** [comment]
tentatively tabling....
