### ISSUE TITLE
Help with error message

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1583]
When attempting to bulk edit labels I get this message:

An error occurred while processing this page!
Error Executing Database Query.
[Macromedia][Oracle JDBC Driver][Oracle]ORA-00001: unique constraint (UAM.IU_CF_TEMP_LBL2CONTR_BC) violated

Attaching Excel file (which is converted to .csv before upload)
[Label upload Cryo 01A.xlsx](https://github.com/ArctosDB/arctos/files/2137801/Label.upload.Cryo.01A.xlsx)

**Comment by dustymc** [comment]
>IU_..

You've already got one.

http://handbook.arctosdb.org/documentation/understanding-errors.html#unique-constraint-iu_table_and_column-violated

There's a unique constraint on barcode in that file - eg, you're trying to move a container somewhere, then move it somewhere else a few milliseconds later. That's commonly an indication that Something Very Bad is going on. (I think a scanner doing something weird lead to this.)

**Comment by dustymc** [comment]
The problem is this:

<img width="493" alt="screen shot 2018-06-26 at 8 50 50 am" src="https://user-images.githubusercontent.com/5720791/41924141-16adafec-791e-11e8-9aee-c8e107ea5ba4.png">

SOMETHING about whatever created these data is broken, perhaps dangerously so. (Eg duplicate physical barcodes - one thing that's caused this before - can very quickly eat a LOT of scans.)

**Comment by Jegelewicz** [comment]
Ha! Interestingly enough we just discovered the typo in the label that caused the duplicate. Will fix and re-try.
