### ISSUE TITLE
Track who creates taxa

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1592]
I think it would be a good idea to know who creates taxa - it would help if there are questions about spelling, etc.

**Comment by sharpphyl** [comment]
I agree.  I can sometimes tell by the Source Authority, but knowing what individual to contact would be helpful and I'd appreciate know of any errors or issues with what I create.

**Comment by campmlc** [comment]
I agree.

**Comment by dperriguey** [comment]
Agreed. I am creating taxa all the time because almost none of them are in Arctos. But I am no taxonomist and the sources we have for verifying data is somewhat limited. I sometimes have taxa that are found in only a few papers that are not in any of our data verification sources. I am always looking for synonyms, but again the data is limited sometimes. 

The questions of spelling and actual legitimacy is really important to me. Although, I have so many new taxa that I'm uploading that I can only verify them to the extent that my time permits. If others are able to see my or other's mistakes, we can have the necessary conversations and keep Arctos' biological taxonomy clean.

**Comment by sharpphyl** [comment]
Will the delete feature alert me (and refuse to delete the taxon) if it is in use, or do we need to check that no other collection is using it before we delete it?

**Comment by Jegelewicz** [comment]
Also #1591

**Comment by Jegelewicz** [comment]
Also #1601

**Comment by Jegelewicz** [comment]
Also #1602

**Comment by dustymc** [comment]
done
