### ISSUE TITLE
Prospective Collections Link text

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#1596]
On the link to the new Prospective Collections Form, change the language from:

You must log in to use this form. You may log in or create an account in the header, or here. 

to 

Thank you for your interest in Arctos! Please create a preliminary account by clicking HERE to access our online form for prospective collections.

Dusty has to fix this.

**Comment by dustymc** [comment]
>Please create a preliminary account by clicking HERE

What is HERE? If they're seeing that they're already in the right place, they just need to log in or create an account.

**Comment by Jegelewicz** [comment]
> Thank you for your interest in Arctos! Please create a preliminary account by clicking HERE to access our online form for prospective collections.

How about this:

Thank you for your interest in Arctos! If you have not done so already, please create an Arctos user account [here](http://arctos.database.museum/login.cfm). Once your account has been created and you are logged in, you will be able to access this form.

The problem here is, how do we get them back to the form after they have created their account and logged in? Is it possible to make this happen automatically? They see the message, create an account and then are automatically returned to the form?

**Comment by dustymc** [comment]
Login always tries to send you back to wherever you came from. The form (still in test maybe) lets them create accounts.

<img width="1312" alt="screen shot 2018-07-16 at 9 19 12 am" src="https://user-images.githubusercontent.com/5720791/42770293-67121674-88d9-11e8-8a48-90db800f66e6.png">

**Comment by Jegelewicz** [comment]
Can you send the link to the form in test?

**Comment by dustymc** [comment]
http://arctos-test.tacc.utexas.edu/new_collection.cfm

**Comment by Jegelewicz** [comment]
Yep, when I created an account I was then sent to the correct page.

Here is my revised suggestion:

> Thank you for your interest in Arctos! If you have not done so already, please create an Arctos user account here. If you have an account please use it to log in. Once your account has been created and you are logged in, you will be able to access the prospective collection form.
