### ISSUE TITLE
bat attributes

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#1616]
Can we add "thumb length" and "calcar length" as attributes for mammals? We've been doing a lot of bats recently and these have been going in as "unformatted measurements". Format as 'value' and 'units'.

**Comment by Jegelewicz** [comment]
Dusty will want definitions for thumb length and calcar length.

**Comment by dustymc** [comment]
Yes, definitions please. (I'm just arbitrating - they're for the folks entering data and the folks using data!)

**Comment by campmlc** [comment]
Done 8-6-18.
Added "calcar length" and "thumb length with claw".

**Comment by dustymc** [comment]
OK, one more: are there conflicting standards for measuring thumb length? "hind foot..." includes with and without because Europeans and Americans have conflicting standards. If that's true here as well then this is correct, if not this should be shortened to "thumb length" and the "claw.." bits moved to the definition.

**Comment by campmlc** [comment]
Thumb length with claw would be relevant for bats and most mammals. Thumb length without claw is relevant for higher primates.  Depends on the taxonomic group being measured and whether or not they have claws as well as whether it is being measured by a European or an American.

Calcar length is a standard term in mammalogy. It is a linear piece of cartilage - measured from base to apex. I added a link to an image.  For a link to a specific publication describing how it is measured, you'd need to ask the mammalogists.
@jldunnum
