### ISSUE TITLE
cf_temp_attributes validator is cryptic

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#1629]
**Describe the bug**
cf_temp_attributes validator is cryptic

**To Reproduce**
try to validate an orphaned GUID, get undefined variables message

**Expected behavior**
get an understandable error

https://github.com/ArctosDB/arctos/issues/1628#issuecomment-409703050

**Comment by acdoll** [comment]
When we create an 'extra' attribute (or anything else extra) can we tag it with the associated catalog number? Or will that not work because the catalog record has not been created when the extra attribute is entered? If there was a field in the 'Add more...' pop-up, we could manually enter the catalog number if necessary.

**Comment by dustymc** [comment]
Catalog number seems overly fragile to me at that stage, and most records are entered without them so it would be a fair bit of what seems like unnecessary complexity in dealing with both situations (and weird combos thereof - a record gets a UUID then a catalog number before being loaded so users are expecting one thing, or the catalog number is changed, or the catalog number originally assigned is removed, or ...). 

There will never be a reason to change a UUID, and I can magic them at will so they're always available when needed. I think that consistency and stability make them the best choice here.

All that said, I'm happy to try something else if ya'll have better ideas. I just need SOMETHING that exists both when the record is entered and after it's loaded.
