### ISSUE TITLE
Media tagged to collecting event

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1635]
I [tagged a field catalog](http://arctos.database.museum/TAG.cfm?media_id=10584557) to a collecting event, but the link provided in the tag takes me to the [find localities search page](http://arctos.database.museum/showLocality.cfm?action=srch&collecting_event_id=11031875). Only if I scroll down, do I see something, and that is the [locality for this event](http://arctos.database.museum/showLocality.cfm?action=srch&collecting_event_id=11031875), not the event itself, so it includes a bunch of stuff not related to the tag AND there isn't a hint of media anywhere.

If I go to the [record for a specimen I know uses the event](http://arctos.database.museum/guid/UTEP:ES:23-107), I don't see a link to the media anywhere.

When media is tagged to a specimen event, I'd like to see it in the event section of the specimen record and I'd like to have the link on the tag take me to the event with only the specimens related to the event listed.

Possible? Is this related to #1608 ?

**Comment by dustymc** [comment]
Yea that public locality page isn't very linkable. It all fits on my little laptop screen - if you're seeing a big search, it's because you've been there and set cookies to expand the options before. I'm up for ideas, but that needs it's own issue.

Nope, TAGs aren't terribly integrated. https://github.com/ArctosDB/arctos/issues/1537#issuecomment-390045477 

>1608

It's related only in that Media is integrated and TAGs sorta aren't.
