### ISSUE TITLE
make it easier to add new names from hierarchical tool

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#1697]
allow adding (cloning??) of nomenclatural code and such when creating a term in the hierarchical tool, rather than forcing the user to edit the new record after it's been created.

**Comment by sharpphyl** [comment]
Just want to be sure this would not only create the name in the hierarchical tool but in Arctos as well.  I always forget to add it to Arctos and get an error (scientific name not found) when I try to do the bulk upload.

**Comment by sharpphyl** [comment]
You may want to make this a new issue, but if you want a series of suggestions to make the hierarchical tool more user friendly, here are a few.

When you edit a taxon, if you make changes to the top part of the form, you must save the form, then reopen it to change the parent.  In this example, I just wanted to change the parent but I had to make corrections on the top half of the form for the bulkloader to accept it.

![screen shot 2018-09-22 at 11 48 59 am](https://user-images.githubusercontent.com/15368365/45920265-f0be3280-be5e-11e8-97e1-d85aa7d15d92.png)


That required closing then reopening the form.


![screen shot 2018-09-22 at 11 49 21 am](https://user-images.githubusercontent.com/15368365/45920269-f3b92300-be5e-11e8-9022-51cc3cc6aeee.png)

Also note that everything in "clams" (could we call it Mollusca?) still contains the warning that the Term-type valid_catalog_term_fg will be deleted  

![screen shot 2018-09-22 at 12 02 43 pm](https://user-images.githubusercontent.com/15368365/45920315-72ae5b80-be5f-11e8-969c-88720d9958bf.png)

Fixing this would require opening every record and adding Taxon Status as valid...or asking Dusty to fix that or reload the clams  to fix it.  Can you do that Dusty?  

Also note that "scientific name" and "display name" are autogenerated when you add a taxon in Arctos.  Yet we have to create them in the bulkloader for a successful upload.  Can they be autogenerated in the bulkloader from the hierarchy without having them show up as a metadata term?  (This relates to the above issue where creating a "child" taxon pushes the scientific name to Arctos.)  

Next, I think this what Derek was describing, but it would be very helpful if, when I pull a taxon from one genus or family or whatever to another, Arctos would search for every one who is using that taxon and send them a notice that it will be moved from e.g. Hydrobiidae to Cochliopidae on a specific date if they don't speak up.  Now that puts the onus on me to return to the hierarchical tool on that date (send me a reminder email?), and upload the bulkload and clean up any other problems that are in there.  That's still a whole lot better than having to open Arctos in another server (so I get all museum records) and figure out who I need to contact.  Right now I'm sitting on a complete redo of Truncatelloidea - especially Hydrobiidae and Cochliopidae - and I just don't want to spend the time contacting everyone when I only have a few specimens.  (And I know I'll lose all the work I've done if Dusty reuploads Mollusca.)  But in the meantime, we have the same genus in multiple families - which is precisely why Dusty doesn't want us to have single-taxon edit capability.  It could also have happened when a new taxon was added if WoRMS was the source.  When ITIS populated Arctos, Cochliopinae was a subfamily of Hydrobiidae; now it's a separate family. 


![screen shot 2018-09-22 at 12 11 03 pm](https://user-images.githubusercontent.com/15368365/45920533-8c9d6d80-be62-11e8-8f11-f83c5fe6d76e.png)


Another approach would be to alter the heading when I open a taxon.  Currently it shows the use of that taxon by everyone in Arctos, but it doesn't allow me to trace who they are.  Here's the header for Hydrobiidae.  DMNS has 21 specimens in Hydrobiidae but it's being used as a family 433 times across all of Arctos.  

![screen shot 2018-09-22 at 12 33 38 pm](https://user-images.githubusercontent.com/15368365/45920611-eb171b80-be63-11e8-9d0f-7c84fa071d9c.png)

If I follow the links to "Arctos Record" it shows the classification with a map of all specimens that have been geolocated but if I click to open them, I get no results because I'm logged in to just DMNS.  I don't recommend that we allow access to other museums' records, but it reinforces the idea of the tool generating some type of communication to every collection using that taxon that a change has been proposed.  

And just a reminder that if we all agree to update our taxonomy (just mollusca or all marine species) with WoRMS, all these changes will happen to everyone without specific warning unless Dusty is able to generate a list of the taxa where the family or genus or whatever we chose is going to change.  But it also means we'd be starting fresh with the most up-to-date taxonomic tables available today.

**Comment by dustymc** [comment]
>change the parent.

Can you elaborate? Changing the parent should generally be a drag operation, or at least that's how I envisioned it. When you drag, it's visually-obvious that you're moving a bunch of stuff - it works just like moving files around on your computer. When you change from a single record, it looks more like you're doing something to one THING, which isn't really possible in a hierarchy. That's the initial reasoning, anyway. (And I'm not actually sure why the "change parent" thing exists - someone must have asked for it??)

I think the multiple buttons and auto-close on save just exist for consistency - it's possible to change the entire nature of the term in the top, and then do something which contradicts that in the bottom before the top is saved. 

In any case, shuffling the buttons around is possible, I just want to better understand what's going on.

>"clams" (could we call it Mollusca?) 

I think this comes back to a fundamental divergence on how the form is used (by everyone except me, I think!) vs. how I'd use it.

I would generally grab the stuff I want to work on NOW (a genus, family, etc.), do my thing, export, and DELETE the local data - the stuff I've just changed changes the big picture in Arctos, possibly in unpredictable ways, it's super-easy to import, I see no reason to chance the inconsistency.

I think everybody else imports everything they might ever want to work on and exports small batches back to Arctos. I also think they generally do this while simultaneously using the single-record form to eg, add new names and probably create inconsistent data.

>valid_catalog_term_fg

See above. That's been removed from the Arctos data, but you're working on a very old snapshot. The form just knows you fed it some data of a type which isn't supported by the code tables.

>opening every record and adding Taxon Status as valid

That's one of the reasons this form pushes through the bulkloader - you can interact with these data in the hierarchical editor, in a spreadsheet, or in the DB after they're loaded to the temp table and before they're pushed to taxonomy records. You can make mass changes in Excel (or whatever you use to manipulate tabular data).

>"scientific name" and "display name"

I'll do something about that ASAP.

**Comment by sharpphyl** [comment]
> change the parent.

> Can you elaborate? Changing the parent should generally be a drag operation, or at least that's how I envisioned it. 

Sometimes I need to move a taxon to a parent that isn't visible on the screen and I can't get my screen to scroll to where I can drag and drop.  So I open the taxon and there are two SAVE buttons.  For example, I need to move the taxa in the genus Hadoceras from Lithoglyphidae to Cochliopidae.  (Yes, in this case, I can see the new parent, but let's assume that I can't.)  

![screen shot 2018-09-24 at 10 29 53 am](https://user-images.githubusercontent.com/15368365/45965633-3d804580-bfe6-11e8-90cf-57f5a7c7b3ce.png)

I also want to move the unaccepted genus Hadoceras to Cochliopidae based on this WoRMS entry.

![screen shot 2018-09-24 at 10 30 16 am](https://user-images.githubusercontent.com/15368365/45965676-5d176e00-bfe6-11e8-8c91-d376001414ab.png)




First, when I open Hadoceras, I can't see the entire screen unless I pull on the edges to open it further.  Can you adjust the size of that screen so you can see all the fields that are available? 
 
![screen shot 2018-09-24 at 10 31 22 am](https://user-images.githubusercontent.com/15368365/45965811-b41d4300-bfe6-11e8-9b37-3cfcd6d486fd.png)

Here's the screen opened to show everything.

![screen shot 2018-09-24 at 10 31 51 am](https://user-images.githubusercontent.com/15368365/45965841-ca2b0380-bfe6-11e8-8620-1d7261146614.png)

I need to add Taxon Status as invalid to this record AND change the family to Cochliopidae.  I usually add the author as well, but forgot to do it here.  If I enter both I have two SAVE buttons.  

![screen shot 2018-09-24 at 10 32 57 am](https://user-images.githubusercontent.com/15368365/45965944-15451680-bfe7-11e8-9afc-562cbcb8c926.png)

If I use the one at the top - Save Rank/Term Metadata Edit - the Taxon status is changed but not the Family.

![screen shot 2018-09-24 at 10 47 53 am](https://user-images.githubusercontent.com/15368365/45966066-63f2b080-bfe7-11e8-9ea4-d4d22e7576bc.png)

I have to reopen the record to change the family.  Doing it this way does move all the children to the new family which is great.  BTW, the drop-down menu for TAXON STATUS (which is really helpful) only appears AFTER I enter invalid and populate that field.  Can the dropdown menu be available initially?  Also, having the Pick Term fields right there speeds the process of adding additional information - similar to what I've asked for as an enhancement to single-taxon entry. 

![screen shot 2018-09-24 at 10 55 07 am](https://user-images.githubusercontent.com/15368365/45966454-6bff2000-bfe8-11e8-8c2b-24b8dd2ab092.png)

> "clams"

> (could we call it Mollusca?)

> I  think this comes back to a fundamental divergence on how the form is used (by everyone except me, I think!) vs. how I'd use it.  I would generally grab the stuff I want to work on NOW (a genus, family, etc.), do my thing, export, and DELETE the local data - the stuff I've just changed changes the big picture in Arctos, possibly in unpredictable ways, it's super-easy to import, I see no reason to chance the inconsistency.

So I tried a new import of Littorinimorpha just to test how this works.  It loaded them but it didn't bring over the existing data in Arctos which should have taken care of my "valid_catalog_term_fg" question.  I've read through the handbook and instructions on the screen and don't see a reason for this problem.  Can you advise?  

BTW you can't copy anything in the hierarchy tool which would be helpful. 

![screen shot 2018-09-24 at 11 45 36 am](https://user-images.githubusercontent.com/15368365/45968903-7670e800-bfef-11e8-90b4-66dbbf81fa70.png)

_________
![screen shot 2018-09-24 at 11 45 46 am](https://user-images.githubusercontent.com/15368365/45968916-7cff5f80-bfef-11e8-84e1-3a4d4e49614e.png)



> "scientific name" and "display name"
> I'll do something about that ASAP.

Thanks.

**Comment by dustymc** [comment]
also: http://arctos.database.museum/tools/taxonomyTree.cfm?action=seedMIA&dataset_name=Littorinimorpha (from "seeded taxa not in your dataset") are inconsistent in Arctos. All of the errors need investigating.

**Comment by sharpphyl** [comment]
There are a TON of errors which will take a long time to work through - and this is just one superfamily.  But I'm still not seeing any data when I open individual names.  How long will it take to populate the various non-classification fields?

Also, I don't quite understand the list of terms with the error "missed taxon name error".  Here's an example.  What exactly is wrong??

![screen shot 2018-09-24 at 12 39 31 pm](https://user-images.githubusercontent.com/15368365/45971778-2d249680-bff7-11e8-98bb-c66640bd6f33.png)

Here's the Arctos entry.


![screen shot 2018-09-24 at 12 40 02 pm](https://user-images.githubusercontent.com/15368365/45971780-301f8700-bff7-11e8-9ab7-5fbd98c21043.png)

**Comment by dustymc** [comment]
>There are a TON of errors which will take a long time to work through

That's precisely why I want to deprecate the single-record editor. All of those errors are hiding specimens, and making importing to this tool which makes data which doesn't hide specimens difficult.

>"missed taxon name error"

For that one, nothing - it just "inserted_term".

Scroll down a bit and you'll see things like...

<img width="679" alt="screen shot 2018-09-24 at 11 59 49 am" src="https://user-images.githubusercontent.com/5720791/45972742-6528db00-bff1-11e8-8e4f-0aebd15c658e.png">

which goes to http://arctos.database.museum/name/Bistolida%20kieneri%20depriesteri which makes the hierarchical editor angry because the scientific name is not the lowest classification term (eg, it's got the wrong classification).

>populate the various non-classification fields

Ah - gotcha. There's a problem somewhere, I'll find it and get back to you.

**Comment by sharpphyl** [comment]
OK, I fixed _Bistolida kieneri depriesteri_ and I appreciate knowing about it as the label with the specimen doesn't have the full species name.

Do I ignore all the "inserted term" taxa?  Can we eliminate them from the list in the future since they are the vast majority and only 13 actually need work.  Whew!

Today I marked a few taxa with a status DELETE.  What's the procedure for them being deleted?  Does that just send a notice to you?  I don't see anything in the handbook yet but DELETE is in the code table.

**Comment by dustymc** [comment]
>Bistolida kieneri depriesteri 

It now has two classifications. That cannot be represented hierarchically and will continue to cause problems.

> eliminate them from the list 

That's the normal behavior - these are still processing==not the "everything happy" status==appear in that table. Some name had 2 nomenclatural code values - I think I know what to do there, it's running now.

**Comment by sharpphyl** [comment]
Sorry.  I forgot to delete the wrong classification.  Is there a way to search for these directly in Arctos?  I seem to find them by error rather than seeking them out and correcting them.

**Comment by dustymc** [comment]
Not really easy to find them - the core model is designed to accommodate that sort of thing. (It has to be - a huge % of the data from GN contains that.) If we're in some sort of agreement that we don't want that in the data we use to identify specimens, my recommendation remains to manage those data in a model which can't allow them to exist.

**Comment by dustymc** [comment]
The nonclassification terms should be coming across now.

**Comment by sharpphyl** [comment]
Actually the nonclassification terms are in each name twice.  I guess I can just eliminate the second set when I edit the csv but is there a way to just get one set?

![screen shot 2018-09-26 at 7 20 00 am](https://user-images.githubusercontent.com/15368365/46082641-c91be280-c15c-11e8-9ba2-5229f8604be1.png)

**Comment by dustymc** [comment]
Woops, knew I'd missed something...

**Comment by dustymc** [comment]
For next release:

- changing parent is moved to the top of the form (with metadata)
- Creating a name auto-opens edit for the new name; should be about the same functionality as requested, but in the context of the new name (eg, you can see how it's placed in the background)
- controlled terms trigger controlled vocab when selected
- clicking a label copies the text to the status box, where it can be copied like any other text - I don't think it's possible to copy directly, perhaps that's somehow useful

**Comment by dustymc** [comment]
- classification bulkloader will now build CSV of names not in Arctos
- the taxon name bulkloader has been reconstituted
