### ISSUE TITLE
Enhancements to the Add Taxon Screen

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#1707]
**Is your feature request related to a problem? Please describe.**

These are not problems - just enhancements - but would be helpful and might make our taxonomy module look more user friendly for prospective members.  

When adding a new taxon, under the non-classification terms, only one line appears which is mandatory - "nomenclatural_code."  This always has to be added and, in my case, it is always ICZN.  Is there a way to auto insert ICZN if the Kingdom is Animalia, and ICBN if it's Plantae.  Alternatively, let users set up a profile where they choose which to insert.  We shouldn't be using "unknown" for new taxa and we could overwrite "noncompliant" if needed.

![screen shot 2018-09-22 at 3 55 11 pm](https://user-images.githubusercontent.com/15368365/45922119-d2692e80-be80-11e8-9f7b-3bea0c1efd30.png)

It would be helpful if there were more than one line in the form.  It's trivial but I have to add three more lines every time to add the author, source and taxon status and I can't figure out a way to do this with keystrokes.  I'd prefer to have those already listed and, if I don't want to use one of them, I delete them.  Is it possible to set up a profile that would always bring up the non-classification fields that you want?  We don't, for example, use Infraspecific_author, so I'd omit that but others would want it always there.  (Maybe even pull the synonym fields into this non-classification table.)

![screen shot 2018-09-22 at 3 55 42 pm](https://user-images.githubusercontent.com/15368365/45922123-e4e36800-be80-11e8-913f-c9cbc166c803.png)

There are two "term types" that are automatically generated.  As the instructions say, anything you write in "scientific_name" and "display_name" will be overwritten, so why include them as options?  Alternatively, fill in the field with "Autogenerated" so users won't think it's been omitted.

![screen shot 2018-09-22 at 3 55 51 pm](https://user-images.githubusercontent.com/15368365/45922122-df861d80-be80-11e8-8088-a983852a8a85.png)

**Describe the solution you'd like**
The changes as suggested above.

**Describe alternatives you've considered**
We can continue just as we are today.  These changes would just make the process of adding individual taxa go faster and unless we upload WoRMS, we'll continue to add new taxa every day.

**Priority**
I would like to have this resolved by date: Whenever.  There's a lot going on right now and this is not high priority.

**Comment by campmlc** [comment]
I agree with these suggestions. This would reduce unnecessary complexity
and effort in the form of multiple clicks and make fields more obvious.

I also support: pull the synonym fields into this non-classification table.
Can we add all the options for non-classification data here, including
publications? I'm  still very confused by all the different form options
for taxonomy. Integrating them would make sense.

Also agree :for scientific name and display name,  fill in the field with
"Autogenerated" so users won't think it's been omitted

Another critical issue that has been raised earlier related to this form is
to change the autogenerated genus suggestion to require opt-in rather than
opt-out. We should not have to think about deleting autosuggested
information every time we open the classification editor to do something
unrelated.
E.g. don't make users have to delete "Aves" = genus when taxon rank is
"Class".

sugInfUnkRnk:
Drag HandleOriginalTermTypeTerm TypeTermDeleteSource
(drag row here) genus     superkingdom  kingdom  subkingdom  infrakingdom
superphylum  phylum  subphylum  subdivision  infraphylum  superclass  class
subclass  infraclass  hyperorder  superorder  order  suborder  infraorder
hyporder  subhyporder  superfamily  epifamily  family  subfamily  supertribe
tribe  subtribe  genus  subgenus  species  subspecies  forma  variety  [
Delete this row ] DUPVAL_flaky_autosuggest
(drag row here) kingdom     superkingdom  kingdom  subkingdom  infrakingdom
superphylum  phylum  subphylum  subdivision  infraphylum  superclass  class
subclass  infraclass  hyperorder  superorder  order  suborder  infraorder
hyporder  subhyporder  superfamily  epifamily  family  subfamily  supertribe
tribe  subtribe  genus  subgenus  species  subspecies  forma  variety  [
Delete this row ] original
(drag row here) phylum     superkingdom  kingdom  subkingdom  infrakingdom
superphylum  phylum  subphylum  subdivision  infraphylum  superclass  class
subclass  infraclass  hyperorder  superorder  order  suborder  infraorder
hyporder  subhyporder  superfamily  epifamily  family  subfamily  supertribe
tribe  subtribe  genus  subgenus  species  subspecies  forma  variety  [
Delete this row ] original
(drag row here) class     superkingdom  kingdom  subkingdom  infrakingdom
superphylum  phylum  subphylum  subdivision  infraphylum  superclass  class
subclass  infraclass  hyperorder  superorder  order  suborder  infraorder
hyporder  subhyporder  superfamily  epifamily  family  subfamily  supertribe
tribe  subtribe  genus  subgenus  species  subspecies  forma  variety  [
Delete this row ] DUPVAL_flaky_autosuggest[ add a row ]
Possibly missing:

**Comment by dustymc** [comment]
Flagging this low-priority for now; I'm still hopeful that we can do this through the hierarchical tool.

> Is there a way to auto insert ICZN if the Kingdom is Animalia, and ICBN if it's Plantae.

No. There are important names (eg, those on types) which are not Code compliant. (If I could make that leap I'd drop the redundancy!) We could probably make it a suggest (eg, something to change in the relatively rare case of it not being predictable), but that leads to something similar to the "monomials are genera" suggestions - the ~5% outliers get ignored and cause problems.

>more than one line in the form

Not overly difficult. Please bring this back up if we don't find a way to deprecate this form soon-ish.

>"scientific_name" and "display_name" 

I'll try to get that as part of removing them from the bulkloader.

>upload WoRMS

I haven't heard back on the request I submitted - if you know anyone there and would like to follow up on that....

> pull the synonym fields into this non-classification table. Can we add all the options for non-classification data here, including publications? I'm still very confused by all the different form options for taxonomy. 

This is a very different kind of data. These terms are all strings; relationships and publications (and projects etc.) are keys. I agree that this is "correct" but it's its own issue (I think one exists).

> require opt-in rather than opt-out.

Been there, done that, it makes inconsistent data in large volumes, which makes the tools that provides consistent data difficult to access. I'm up for better ideas, but I don't like a "solution" that moves the problem from ~5% of the data to ~95% of the data.

**Comment by campmlc** [comment]
How about a confirmation popup on save that requires operators to confirm
they want to accept the autoinserted genus name, or any autoinserted, for
that matter?

**Comment by Jegelewicz** [comment]
> How about a confirmation popup on save that requires operators to confirm they want to accept the autoinserted genus name, or any autoinserted, for that matter?

At least this. As it is WE are "doing something indefensible" by inserting errors into our taxonomy table. Scripts that make decisions about what I or any other human are thinking are not always the answer. I very much dislike the "DUPVAL_flaky_autosuggest". At the very least, we should have to accept the suggestion - it should NEVER auto-populate a part of a classification created by a human being. The Taxonomy Committee should be notified of classifications with missing levels and resolve them through review.

**Comment by dustymc** [comment]
Insert errors and 'fail to insert' errors seem equally bad to me - they break different things, but they both break stuff.

There's nothing auto about the insert - there's a big red suggestion which you can accept or reject. I think I'm not quite understanding something??

> The Taxonomy Committee should be notified of classifications with missing levels and resolve them through review.

In the current model, those are not a problem - it explicitly allows inconsistent data because that was a requirement when we were building the model. If ya'll want to set our rules for local classifications (or whatever) I'm happy to talk about how we can accomplish that.

I'd also need to know what you mean by "missing levels" - AFAIK that's currently 100% of local classifications by the obvious definition of "doesn't include something in http://arctos.database.museum/info/ctDocumentation.cfm?table=CTTAXON_TERM."

**Comment by sharpphyl** [comment]
Dusty, I haven't had any contact with WoRMS about uploading their taxonomy.  The only conversations I've had have been about Global Names and I filed those comments through their general information email which is probably answered by a variety of staff.

**Comment by dustymc** [comment]
related: #1816

**Comment by sharpphyl** [comment]
The original request for enhancements to the Add Taxon screen are covered in #2695. 

 The issue then wandered into new territory with the request to add synonyms to the metadata and to not insert an autosuggested classification name.  I recommend that @Jegelewicz  or @campmlc initiate a new issue if this is important to you after Teresa/Dusty implement all the recommendations in #2695.

I'm closing this and recommend we delete this from the Committee list or move it to the Propose to Close or Implemented or No Action Recommended column.
