### ISSUE TITLE
Taxon rank improvements caused aggregator mix ups?

### ISSUE THREAD

**Issue by anna-chinn** [ArctosDB/arctos#1737]
**Describe the bug**
I think the improvements to the way taxon rank is communicated to the aggregators may have caused all Arctos identifications to get funky.

![capture2](https://user-images.githubusercontent.com/40321380/46822754-ebfbe880-cd51-11e8-961f-a4bb0d2e7dda.PNG)

I checked the most recent CHAS:Fish Darwin Core Archive and it looks like some classification fields may be getting switched around on the back end. Older Darwin Core Archives look fine.

CHAS:Fish DwC-A 13.17 (Oct 2018):
![capture](https://user-images.githubusercontent.com/40321380/46822777-fae29b00-cd51-11e8-9973-e615ae7663d5.PNG)

CHAS:Fish DwC-A 13.12 (May 2018):
![capture3](https://user-images.githubusercontent.com/40321380/46822782-fd44f500-cd51-11e8-9514-4f1e03d59490.PNG)

**To Reproduce**
It looks as though all Arctos datasets are affected.
e.g. MSB Mammals: https://www.gbif.org/occurrence/search?dataset_key=b15d4952-7d20-46f1-8a3e-556a512b04c5

**Priority**
I would like to have this resolved by date: probably ASAP

**Comment by dustymc** [comment]
@dbloom ??

**Comment by Jegelewicz** [comment]
It appears that taxon rank is not pulling the correct information.

**Comment by dustymc** [comment]
IPT is position-mapped, so altering the view melted everything, everywhere. They are in the process of moving to new servers, so have limited capacity to deal with this now. I've dropped taxon_rank; re-adding it (and any future remappings of the digir_query.ipt_view view) need coordinated with the folks who handle IPT.

**Comment by dbloom** [comment]
This issue has been addressed. It took 1.5 days to remap and republish each of the 77 Arctos resources manually, including the provision of a complete re-connection to the Arctosdb for several resources that were completely FUBAR (as Dusty would say). Taxon_rank is included in this new set of mappings.

I will notify GBIF and iDigBio who have been on a hold with the Arctos datasets for about two weeks while we fixed the issue. After all of the portals have reharvested these newly refreshed resources, all should, once again, be good in the world. This could take between several hours and several days depending upon how quickly various portals are able to harvest and process the new data.

Thanks @dustymc for being available to for testing and experimenting and you guys should all thank the Field Museum because in the middle of all of this we moved the VertNet IPT to a server at that fine institution. Thus, now the VN IPT is much more stable and easily accessible should anything like this happen again.

Now I will have a glass of wine and await all of the new messages from data users telling me that I forgot some critical piece of this puzzle.  ;-)

**Comment by Jegelewicz** [comment]
Thanks @dbloom and @dustymc for handling this. We who count on your behind the scenes magic really appreciate the things you do that we can not!

BTW - The Field is my favorite museum and while they are by no means perfect, it seems they are taking data seriously which makes me like them even more.

Enjoy that well-deserved wine! We'll get back to you....
