### ISSUE TITLE
Arctos Error Message Log

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#1769]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
I would like to create a log of Arctos error messages in Github. 

**Describe the solution you'd like**
Please post when you receive interesting messages and, if you know it, the reason for the error and the problem fix. 

**Additional context**
To keep an operator log of these kinds of messages and their translations that we can use for future user interface upgrades

**Comment by campmlc** [comment]
screen shot 2018-10-29 at 4 05 35 pm
#1768

**Comment by campmlc** [comment]
#1768 try again to copy image
<img width="1040" alt="screen shot 2018-10-29 at 4 05 35 pm" src="https://user-images.githubusercontent.com/28404497/47687305-818dd980-db94-11e8-8b52-379ccdb37eb6.png">

**Comment by dustymc** [comment]
This is a useful project, but I think it's better done in http://handbook.arctosdb.org/documentation/understanding-errors.html.

I added the "Needs Documentation" Milestone (https://github.com/ArctosDB/arctos/milestones) recently - it (in conjunction with the Error Messages label that just appeared) should be sufficient to flag things; I don't think we need to replicate to another Issue.

If you're looking for specifics, the report is looking for a a variable named "identification" but it's just being fed the number 1. That should all be in http://handbook.arctosdb.org/how_to/How-to-Create-Labels.html.

**Comment by Jegelewicz** [comment]
> This is a useful project, but I think it's better done in http://handbook.arctosdb.org/documentation/understanding-errors.html.

Agree, but we can use GitHub issues to compile the errors to be added to documentation. I added the "Error Message" tag and we can use it to search for messages that need to be added to documentation. Now we just need someone to take on the job of http://handbook.arctosdb.org/documentation/understanding-errors.html editor.....

**Comment by dustymc** [comment]
Yes, that's what I was suggesting, and I think your label is a good addition to the process. I generally filter by milestone - eg, I don't have enough info to do anything about "needs discussion" Issues so I ignore them. When I've done my thing with Issues having the tag I'll switch them to the "Needs Documentation" Milestone (which I'll also generally filter out) rather than closing them. People writing docs can filter by the label (but the error might change if the milestone is still some flavor of "in progress") or the milestone, and for those documentation should be all that's needed and the Issue can be closed when that's done.
