### ISSUE TITLE
Bug repeat - coordinates from locality don't get to the collecting event

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#1770]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
After geolocating locality 10479707, it shows the map in the two catalogued item records (DMNS:Inv:10216 and 24570), but the coordinates don't show in DMNS:Inv:10216 - only in 24570.  This is the second time, this has happened, but I can't recall doing anything differently while geolocating the locality.

**Expected behavior**
Last time you added the coordinates to flat, so can you do that again.

**Screenshots**

![screen shot 2018-10-30 at 7 27 20 am](https://user-images.githubusercontent.com/15368365/47721563-ff45f980-dc15-11e8-9819-c56abee0d493.png)
_____________
No coordinates appear here with the locality record on this specimen record

![screen shot 2018-10-30 at 7 27 35 am](https://user-images.githubusercontent.com/15368365/47721578-079e3480-dc16-11e8-84d9-3dcbea66370a.png)

_____________

But there are coordinates with the locality record.

![screen shot 2018-10-30 at 7 28 31 am](https://user-images.githubusercontent.com/15368365/47721587-0d941580-dc16-11e8-95de-ffd88a2877e3.png)

_____________

The coordinates only show on one of the collecting events/specimen records.

![screen shot 2018-10-30 at 7 28 51 am](https://user-images.githubusercontent.com/15368365/47721592-11279c80-dc16-11e8-8d70-2e6348e5f69d.png)

**Desktop (please complete the following information):**
Mac from home with Chrome.

**Priority**
I would like to have this resolved by date: Whenever.

**Comment by dustymc** [comment]
Looks like the locality was georeffed at 2018-10-29 08:36:04.0 - http://arctos.database.museum/info/localityArchive.cfm?locality_id=10479707

Then the formerly-coordinateless event was pushed to that locality at 2018-10-29 10:09:13.0 - http://arctos.database.museum/info/collectingEventArchive.cfm?collecting_event_id=11120901

That should have triggered TR_COLLEVENT_AU_FLAT, which updates flat by collecting_event_id. That looks right now, but perhaps it somehow wasn't at some point??

```
UAM@ARCTOS> select stale_flag,dec_lat from flat where locality_id=10479707;

STALE_FLAG    DEC_LAT
---------- ----------
	 2
	 2   5.871928
```

There were a couple dozen of these, all recent.

I can't break it or find any stale triggers or etc. 

My intuition is that this is related to cache_anygeog and happens when locality-stuff is busy, but that should just cause hangs. I rebuilt that too.

I'm flagging this infrastructure-limited. Minimally, this would be easier to diagnose if we didn't have to clutter up the DB with the complexity of maintaining caches to support our limited resources.

@lkvoong can you kick the tires and see if anything falls off?
