### ISSUE TITLE
Broken Link on Prospective Collection form

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1777]
The link for creating a user account is broken.
![image](https://user-images.githubusercontent.com/5725767/47929507-dda37700-de8e-11e8-95e6-51f839c535d1.png)
The middle "How To" should link to http://handbook.arctosdb.org/how_to/How-to-Create-your-Arctos-Team-Users-and-Operators.html#1-have-each-team-member-create-an-arctos-user-account

**Comment by dustymc** [comment]
The link is broken because https://github.com/ArctosDB/documentation-wiki/commit/5fb665ce2faf60a5e722d45de1dc959cacba9258#diff-32e4fb474bccb794fc6cc9554ce52312 and the link below it because https://github.com/ArctosDB/documentation-wiki/commit/c00f4122c9445d270c29e146c2364f89ecfde5d7#diff-32e4fb474bccb794fc6cc9554ce52312.

This is documented at http://handbook.arctosdb.org/how_to/How-to-Contribute-Content-to-Arctos-Handbook.html#edit-existing-content

This is a common occurrence, and I have no way of monitoring broken links coming in to the handbook so I doubt we're very good at detection.

How do we make this better?

I'll change the one link and remove the other for next release.

**Comment by Jegelewicz** [comment]
It will always be a problem which we will fix as we find them. One thing we could do is document the links IN ARCTOS that go to the Documentation/Handbook. A list of these on the documentation wiki and instructions in the documentation to review these if a change is made to a title might help a bit.

**Comment by dustymc** [comment]
A few weird things - like this one - I hard-code in. Everything else is available in the documentation menu.

**Comment by Jegelewicz** [comment]
Check! Maybe we should assign someone the task of checking the links occasionally?
