### ISSUE TITLE
Add dagger to fossil taxa

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#1810]
In working with the hierarchical classification tool, I run into many fossil taxa that were added from UCMP.  Many are a single species and the genus was not added which adds them to the "taxon needing names" list after the upload.  They are not added to the csv for upload if I don't add the nomenclatural code which creates another error message.  Some are misspelled.   Some are valid.  

I have no expertise in fossil taxa so I rather laboriously figure out if they're fossils, add that as a remark sometimes, sometimes update them and sometimes delete them from the tool, but of course they come back if I upload that group again.  Here's an example of a group identified only as Gastropoda and every one of the genera from Tapfius to Urosyca is empty and placed there because there's a fossil species from UCMP that needs a genus taxon name in the classification.  Yes, these are all on our list of taxa needing a family.

![screen shot 2018-11-24 at 3 32 02 pm](https://user-images.githubusercontent.com/15368365/48973574-52d21a00-efff-11e8-9093-916b37564649.png)

![screen shot 2018-11-24 at 4 20 49 pm](https://user-images.githubusercontent.com/15368365/48973784-0558ab80-f005-11e8-9ce5-2e13e2331a40.png)

And by the way, _Tapfius peregrinus_ doesn't seem to pass the Google test.

I would upload a smaller section of Mollusca such as a superfamily, but the one I'm working on now, Tonnoidea, had families in three different orders so I needed to upload all the Gastropoda to find them.

Ideas:

I see that FossilWorks and WoRMs both use the dagger † to indicate a fossil (not extant) species.  Is it possible to add that to our taxa as an additional or modified descriptor that would be visible with the taxon name.  I know there's probably a lot of discussion around what is a fossil, but if WoRMS or some other acceptable authority identifies it with the dagger, that's good enough for me.  I would reduce the hours I spend checking taxa that are purely an irritation when trying to use the HC tool to manage mollusca taxonomy.  

![screen shot 2018-11-24 at 3 20 07 pm](https://user-images.githubusercontent.com/15368365/48973595-dbe95100-efff-11e8-9462-808673f852e7.png)

![screen shot 2018-11-24 at 3 22 48 pm](https://user-images.githubusercontent.com/15368365/48973596-ed325d80-efff-11e8-8fe5-1d144624917f.png)

If we did have a way to identify fossil taxa, could I choose whether or not to upload them to the Hierarchical Classification tool?  That way I wouldn't have to deal with them at all and the tool would be much more attractive to use.  Yes, I know we need to eventually get them into a family, but I'm probably not the expert to do that.

I don't think it's a good idea to ask to be able to leave out UCMP taxa when I upload though I've thought seriously about it.  There are more than 10,000 taxa from UCMP and some are valid, needed and used by our collection.  Perhaps if we upload the WoRMS mollusca taxa and overwrite the valid UCMP taxa with the WoRMS classification, we could consider this. 

Dusty, can you add ICZN to all these genera when they are autogenerated as placeholders?  Alternatively, can you include these taxa in the csv created for upload to Arctos whether or not the nomenclatural code has been added?  It's laborious to have to open every taxon in the HC tool, choose ICZN, save, close and repeat, but if I don't they aren't added to the csv.  In the csv, I can add ICZN quickly to every taxon (and it's mandatory anyway so the taxon won't upload without it.)

If there were an easier way to create the taxon name and classification, this probably wouldn't be as big an issue.  It looks like I can now create the SCIENTIFIC_NAME with a csv, then upload the classification, but it's not quick and easy.  Am I missing anything new?

I'm open to any other ideas, but I'm wearing out.

**Comment by campmlc** [comment]
If we can do this now in taxon term, and that would help deal with the
original request, then I recommend doing that while we sort out the overall
model.

**Comment by sharpphyl** [comment]
Ok, the dagger is out.  It would be fine to have some type of taxon status (although it's really a taxon descriptor that is "fossil only."  We'd still need "valid" and the other taxon descriptors so that's why I'd rather put it in a different category.  Do we have enough paleo specimens to warrant identifying fossil only taxa?

I don't think we need to add author or other descriptors to the scientific name (mostly because we need to be compatible with idigbio etc.), but I like Derek's idea of adding author and perhaps taxon status (as you've done already) and perhaps "fossil only" whenever a taxon is called up - such as in data entry, taxon search, and even in the hierarchy classification tool.  You indicated that it's never been done because no one asked for it, so let's consider this a request.  Would that work?

**Comment by dustymc** [comment]
>We'd still need "valid" and the other taxon descriptors

This isn't an either/or situation - you can add as many terms as you want to a record (but not through the hierarchical tool which relies on pre-known CSV format - we could deal with that too, somehow).

Adding something functionally equivalent to taxon_status (another term at the top of http://arctos.database.museum/info/ctDocumentation.cfm?table=CTTAXON_TERM) is possible as well, and probably easier to deal with. I'm not sure it's exactly "correct" from a DB design perspective, but I don't think it'll break anything and it should be easy enough to shuffle around if we find a reason to. I'd say work out the term-type vocabulary, add to the code table, and let me know if you want any term-level vocabulary control. (And maybe we should talk about making a code-table-code-table for taxon term values, should that part of the model still exist when some of these issues are resolved.)

>I don't think we need to add author or other descriptors to the scientific name

I wholeheartedly agree and have no desire to take us back to 1999! Not my decision, but not something I can be very enthusiastic about either. That doesn't mean we can't/shouldn't do more internally. The taxa pick is easy to change. Tossing display_name (which could be formatted to include whatever) around is "only" a social problem (eg, convince everyone to show it wherever you want to see it, or find a way to filter by collection, or something). Rebuilding the model to allow picking specific classifications from IDs is possible (I think, somehow) and shouldn't isolate us from the world, although it probably comes with some significant usability problems (but we have a big group of users who might be able to find a solution). I think we can find ways to make things better without also making anything worse.

**Comment by campmlc** [comment]
If we could do this:
"Rebuilding the model to allow picking specific classifications from IDs is
possible "
So that we can simultaneously choose a classification with authority/date
to associate with a name on name creation, that would be ideal. Or have a
script that searches based on the authority and date info provided to
autopopulate classification data into new names. Right now the process is
far to complex and cumbersome, and people are creating names without
classifications without realizing they are doing so. If we allow users the
option of choosing/specifying an authority/date on name creation, would
that allow us to immediately embed within the appropriate classification?
We need to allow different classifications for the same name to deal with
homonyms, and need to be able to search on a particular name+author+date
combination to avoid homonym issues. How these data are stored internally
is not an issue if these usability and searchability issues can be resolved.

**Comment by dustymc** [comment]
>people are creating names without classifications without realizing they are doing so

Perhaps, but people are also creating names because that's all the information they have.

If we keep the current model, perhaps we need to split the manage_taxonomy role into "create, delete, modify name" (very restricted) and "do classification stuff" (less restricted), which would ~halve the amount of documentation needed to do the most common "taxonomy stuff."

>We need to allow different classifications for the same name to deal with homonyms, 

You only need that in the current schema if you're cataloging homonyms in a single collection. That gap in coverage was widely publicized as we were looking for taxonomy models (which may have been before many current users became active).

>need to be able to search on a particular name+author+date combination to avoid homonym issues

That is just "tossing display_name around."

And I'm back to being completely lost. I thought the desire was to explicitly attach this:

<img width="932" alt="screen shot 2018-11-26 at 11 23 45 am" src="https://user-images.githubusercontent.com/5720791/49036930-cb56e900-f16d-11e8-9a77-d77419b91a7a.png">

(the third classification within http://arctos.database.museum/name/Echidna#GBIFBackboneTaxonomy) to a specimen. That's what "allow picking specific classifications from IDs" would allow. Your comments make me think this is something else - limiting how classifications and/or names are created or something.

I think we really need https://github.com/ArctosDB/arctos/issues/1817.

**Comment by Jegelewicz** [comment]
I added extinct and extant to the TAXON_STATUS code table so for an organism that is valid and extinct, you would need two TAXON_STATUS values, but hopefully that will help for now. @sharpphyl let me know if that works.

**Comment by sharpphyl** [comment]
That should work. I'll give it a try.  Thanks.
