### ISSUE TITLE
×Bayerara and how to handle in taxonomy

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1827]
![image](https://user-images.githubusercontent.com/5725767/49196728-3f99b400-f349-11e8-8030-c0956336dd3b.png)

I feel like it is part of this: hybridparent of:Aloaceae × Bayerara D.M.Cumming Haworthiad 13(1): 20. 1999 but I don't understand how I should be handling it in taxonomy. It seems to me that it should just be Bayerara...

**Comment by dustymc** [comment]
I don't know about that specific example, but the x-thing is real and in use.

>H.1.1. Hybridity is indicated by the use of the multiplication sign × or by the addition of the prefix "notho-" 1 to the term denoting the rank of the taxon.

http://www.ipni.org/ipni/idPlantNameSearch.do;jsessionid=662DFF97774A725C76C55797D591974D?id=1017026-1&back_page=

guess IPNI hasn't figured more out since we pulled their data.

**Comment by Jegelewicz** [comment]
OK - now I see what it is. Anything with the multiplication sign is a hybrid, but they aren't easily searchable in Arctos. The names are entered with a multiplication sign (not an "x") and if I search xBayerara or just Bayerara I get nothing. I have to put the % in front to find it. Any way we can make that easier?

**Comment by dustymc** [comment]
>is a hybrid

Well, something that some botanist who likes symbols once thought was a hybrid, anyway...

Arctos is bitwise indexes - until we change some infrastructure-things (which is not trivial) x and × are just different characters. xBayerara is just wrong, although it's fairly common (because ASCII databases). I don't think botanists have much trouble coming up with the correct character, but who knows. There are also botanical names with dashes and umlauts and such which present similar discoverability issues.

**Comment by dustymc** [comment]
>back burner..

It's been there since Oracle introduced linguistic indexes (ca. 2000). Not much of a technical issue, but it does require rewriting a significant amount of code and probably an Oracle consultant.
