### ISSUE TITLE
"Deadlock detected" error

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#1831]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
My student was just trying to save a new specimen event after cloning and when she tried to save she got this error.
![screen shot 2018-11-29 at 10 18 34 am](https://user-images.githubusercontent.com/17605945/49246091-91315580-f3c0-11e8-8e34-b88f7bde7030.png)

She was still able to find the new specimen event by the Collecting Event ID, but we were hesitant to close the window with the error. Just wanted to alert you. The saves were taking a long time prior to this.

**Comment by dustymc** [comment]
Thanks. This is caused by the expense of updating locality data - it takes a while, and things get confused and run into each other. It usually only surfaces when there are lots of data - tens of thousands of specimens or similar - involved, but repeated saves to the same thing or just the DB being busy with other stuff at the moment or similar could lead here too.
