### ISSUE TITLE
data entry problems with taxon name

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#1833]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
When I tab to select taxon name in data entry, the popup window times out without entering a name. 

**To Reproduce**
1. Go to '...' data entry, tried MSB Host and MSB Para
2. Click on '....' Scientific name, enter "Physa acuta" in host, Echinostoma in Para, hit TAB
3.  Get popup box that looks for name, but box remains blank and nothing happens.

**Expected behavior**
A clear and concise description of what you expected to happen.  To be able to enter these attributes during data entry.
Name would be found and entered into scientific name field
**Screenshots**

**Desktop (please complete the following information):**
Windows 10
Chrome

**Additional context**

**Priority**
I would like to have this resolved by date: _asap  - have a demo coming up in an hour______

**Comment by dustymc** [comment]
<img width="356" alt="screen shot 2018-11-30 at 11 08 29 am" src="https://user-images.githubusercontent.com/5720791/49309533-64e50a00-f490-11e8-8a4d-dd545b27ed36.png">


<img width="334" alt="screen shot 2018-11-30 at 11 08 57 am" src="https://user-images.githubusercontent.com/5720791/49309525-60205600-f490-11e8-8478-3a7bb9c45d78.png">

**Comment by campmlc** [comment]
So, it did load eventually. It took several minutes. A problem on my end?

**Comment by campmlc** [comment]
Still having this issue, with both Firefox and Chrome. 
![screenshot 2018-12-03 09 54 22](https://user-images.githubusercontent.com/14808196/49388614-8be64a80-f6e1-11e8-8937-c7db9c8b7bc3.png)

![screenshot 2018-12-03 09 55 58](https://user-images.githubusercontent.com/14808196/49388673-b2a48100-f6e1-11e8-995a-0b4122c4c968.png)

**Comment by dustymc** [comment]
That's trying to filter ~3 million names and ~800 million terms ~130 times. I'm not sure there's anything I can do except add the "need more power" label. 

For a cruddy baseline..

<img width="393" alt="screen shot 2018-12-03 at 8 59 52 am" src="https://user-images.githubusercontent.com/5720791/49388877-d5cb3280-f6d9-11e8-9d48-ba8d39862d44.png">

takes 2 seconds

<img width="409" alt="screen shot 2018-12-03 at 9 00 43 am" src="https://user-images.githubusercontent.com/5720791/49388932-f4c9c480-f6d9-11e8-9268-d43a979b7f8e.png">

takes 1.5 (probably because Oracle "learns" but this is the best comparison I have)

<img width="398" alt="screen shot 2018-12-03 at 9 01 41 am" src="https://user-images.githubusercontent.com/5720791/49388975-12972980-f6da-11e8-89b7-f5e3e8803a95.png">

still takes 1.5....

<img width="369" alt="screen shot 2018-12-03 at 9 02 25 am" src="https://user-images.githubusercontent.com/5720791/49389020-322e5200-f6da-11e8-8800-ac0bf2a849ff.png">

takes almost 15

Andinomys performs almost exactly the same for me - this it data-dependent, but doesn't seem THAT sensitive.
