### ISSUE TITLE
WoRMS homonyms

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#1840]
These are accepted homonyms in WoRMS. Lacking better ideas, I'll pick a random aphiaID from among them and use that.

[temp_worms_accepted_homonym.csv.zip](https://github.com/ArctosDB/arctos/files/2654551/temp_worms_accepted_homonym.csv.zip)

**Comment by sharpphyl** [comment]
Makes sense.  If it turns out that we need the other aphiaID, I can modify the original record and substitute the the alphiaID that we want.  I'll look these over in the next few days, but don't let it stop you from going forward as we can always make modifications after the upload.  Thanks for all you're doing to make this happen.

**Comment by campmlc** [comment]
Can we get the author/date authority info that is associated with the aphia
Id? seems like that is the solution here as well.

**Comment by dustymc** [comment]
Yea, I can get that, or you can use the ID to do. 

What problem would that information solve?

**Comment by campmlc** [comment]
We could choose the Cepolidae mollusc instead of the Cepolidae fish.

**Comment by dustymc** [comment]
You can do that by changing the aphiaid. Or I can add whatever to the CSV if you want to deal with that before I push it to Arctos - I'll probably be ready to load these early next week, after the easy stuff has gone in.

I've got another ~15K homonyms that point to one "accepted" if you want to go through those too.

**Comment by sharpphyl** [comment]
If they point to one "accepted" can you just load that one?  ~15k would take a long time to work through.

**Comment by dustymc** [comment]
Yes my plan was to use the accepted homonym when there is one - you can change those later if you need as well. The multiple accepted will be a little more random.

Here's what's used.

```
select distinct scientificname from temp_worms_accepted_homonym,taxon_name, identification_taxonomy where temp_worms_accepted_homonym.scientificName=taxon_name.scientific_name and 
taxon_name.taxon_name_id=identification_taxonomy.taxon_name_id
  3  ;

SCIENTIFICNAME
------------------------------------------------------------------------------------------------------------------------
Heterothops
Kenella
Nassarius cinctellus
Polystoma
Stellaria
Avenella
Corbicula
Leucon
Vesicularia
Arenaria
Calophyllum
Diloma
Ficus
Liparis
Oenanthe
Pontoporeia
Retusa sulcata
Sabatia
Strombus
Trichia
Argonauta
Didymocystis
Digenea
Gonostomatidae
Linckia
Pontogeneia
Turbinella
Urospora
Acanthina
Ctenophora
Martensia
Amicula
Congeria
Perrinia
Vertebrata
Alvania fenestrata
Calliostoma canaliculatum
Planaria
Porella
Proboscidea
Trichocera
Tuba

42 rows selected.
```

**Comment by sharpphyl** [comment]
Dusty, I can't tell which taxon you chose in the above post.  But I did go through your list of homonyms and where I was able to trace the term to something we use, I indicated "Use this one" for the correct taxon to enter.  Hope you can still make those adjustments.  BTW, our friend Cepolidae wasn't among the suspects, so you must have already taken care of that one.

[temp_worms_accepted_homonym with PMS edits.xlsx](https://github.com/ArctosDB/arctos/files/2658086/temp_worms_accepted_homonym.with.PMS.edits.xlsx)

Some but not all of the homonyms are across kingdoms.  Since WoRMS will come in with complete classifications for each taxon (and a unique AphiaID), have you considered splitting the WoRMS taxa into separate kingdoms (like you did the Arctos and Arctos Plants) which would reduce the number of homonyms within a selected source (e.g. WoRMS Animalia or WoRMS Chromista).  Ideally, an institution could choose from a menu of kingdoms which ones they need for their collections.    And, it would be great, if someone tried to add a taxon without a kingdom, it would be refused.  (At least, now we can figure out who adds unacceptable taxon classifications and try to get them corrected.) 

Anything else you need from us at this point?

**Comment by campmlc** [comment]
I support this to encourage users to add Kingdom and whatever other
classification info they have. We need to make it easy for them to find out
whether a classification already exists for that taxon in Arctos (red flag
if they try to create a duplicate) and easy for them to create the new
classification.

 "strongly suggesting" whatever - making it required in the classification
loader or throwing up big red boxes on the single-record editor or
similar.

**Comment by sharpphyl** [comment]
I'm not sure who all will use the WoRMS source, so it should probably stay as you plan to upload it - with everything included.  I'll just use Animalia but the next collection might like Chromista, so I'm reluctant to eliminate anything especially since we're hoping this will make Arctos more attractive to new collections.

We are trying to update all the various taxonomy files in the Handbook  - if possible before the Webinar next week and that one is part of the review.  I'll include a link if anything serious is changed, but we can always correct and amend them later to capture all the enhancements going on.  

And I agree with Mariel - it would be a good idea to see the big red box around Kingdom when we're using the single-taxon editor tool if it's not filled in.  Sometimes what we clone isn't complete and we don't notice it, so reminders are always appropriate.   But it's true that you don't see the classification when the bare name is added, so we'll need to think of other approaches.  Do we know who adds bare names so we could remind them after an appropriate amount of time that they're still without a classification?

**Comment by dustymc** [comment]
>big red box 

It's always been there.

<img width="831" alt="screen shot 2018-12-07 at 10 12 16 am" src="https://user-images.githubusercontent.com/5720791/49665088-9f0e5880-fa08-11e8-85be-30227c9dec17.png">


>who adds bare names so we could remind them

For recent stuff, yes. Issue please....


>enhancements going on

Completely unrelated to this, but we need something like a blog for that.

**Comment by dustymc** [comment]
We can do whatever, but...

You can easily convince me that the red box is overused (and we now have a less-red counterpart - let me know if you thing something should not be "important" and I'll swap them).

I don't think you'll convince me that someone who ignores a giant red box with a big blank where important data should be stored will notice a giant red box with a big blank where important data should be stored and a little bit of text.

My solution, as always, would be route such updates though something which structurally cannot be inconsistent, rather than trying to guess what "inconsistent" means outside of any context and maybe making some suggestions from those guesses. https://github.com/ArctosDB/arctos/issues/1698

**Comment by campmlc** [comment]
If people have an explanatory prompt, they are much more likely to use it.
When we buy airline tickets and forgot to add our date of birth, we get a
prompt to please fill in the following fields or some such. A box with a
red border with no text is scary, and the response is not to touch it.
