### ISSUE TITLE
Specimen Event Bulkloader question

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1898]
When loading specimen events using the event bulkload tool, if I supply a locality ID, why am I also required to supply higher geography and specific locality? Aren't those already included in the locality?

I am loading events to record the georeferencing of specimens and want to retain the original event.

**Comment by dustymc** [comment]
Why do you think those are required?

**Comment by anna-chinn** [comment]
I just tried to load specimen events with existing Locality_IDs (and therefore no higher geography and specific locality) and the bulkloader threw these errors upon validation:

![Capture2](https://user-images.githubusercontent.com/40321380/54390361-4c2fe700-4670-11e9-8e61-aa77d35ebc5c.PNG)

**Comment by dustymc** [comment]
Data? I don't see that in the table

UAM@ARCTOS> select distinct status from cf_temp_specevent;

STATUS
------------------------------------------------------------------------------------------------------------------------
FAIL: Error Executing Database Query. [Macromedia][Oracle JDBC Driver][Oracle]ORA-02290: check constraint (UAM.CK_VERBAT
IM_DATE_NOPRINT) violated

FAIL: Error Executing Database Query. [Macromedia][Oracle JDBC Driver][Oracle]ORA-02290: check constraint (UAM.CK_SPEC_E
VNT_REMARK_NOPRINT) violated


2 rows selected.

**Comment by anna-chinn** [comment]
Oh, I deleted the data from the table. I have more in there now, but haven't tried validating anything. Here's table I downloaded from the staging table before deleting everything.
[BulkloadSpecimenEventData.xlsx](https://github.com/ArctosDB/arctos/files/2968494/BulkloadSpecimenEventData.xlsx)

**Comment by dustymc** [comment]
Thanks. That tool won't handle locality_id - I think it was removed semi-recently, probably something about auto-merged localities causing confusion but I can't find the Issue.

All of the IDs in your file do seem to exist. I could name them, update your data, then un-name them after you're done - does that work?

**Comment by Jegelewicz** [comment]
So we aren't able to use locality IDs? That isn't very helpful! We cannot always name localities - see recently where I did so to facilitate bulkloading and it was removed by someone who didn't like the name. Maybe we need a community discussion about this?

**Comment by dustymc** [comment]
Neither is preparing a file using IDs that all get deleted while you were preparing your file!

Can you link to the other thread? I seem to have missed that. I can't really imagine how a name could be a problem, and if it is it's not hard to split a locality (and https://github.com/ArctosDB/arctos/issues/1357 could make it easier).

Yep, we can discuss, I don't mind bringing ID back in as long as we all understand how it works.

**Comment by anna-chinn** [comment]
> All of the IDs in your file do seem to exist. I could name them, update your data, then un-name them after you're done - does that work?

Yes that works for now. Thanks Dusty!
That is a lot of localities to name. Could there be a tool for users to temporarily name a batch of localities/events (e.g. give all CHAS:Inv localities a temporary name for 1 week)?

**Comment by Jegelewicz** [comment]
> Can you link to the other thread? I seem to have missed that. I can't really imagine how a name could be a problem, and if it is it's not hard to split a locality (and #1357 could make it easier).

It wasn't a thread - it was via an email directly to me telling me that the name had been removed because they didn't want it. I could have created an exact duplicate locality and given it a name and moved all of my specimens to it, but why do that? It seems like that defeats the purpose of shared data.... I want everything from that place to be in that locality. So I just try to make sure that I enter everything EXACTLY as it is for the locality when creating my bulkload file.  For this one case, not too large of an issue and probably no one else cares, they would just create the locality they want and name it.

**Comment by dustymc** [comment]
@anna-chinn 134 of your records in the loader do not have a locality_id - do you want to change that before I proceed or should I just ignore those?

```
UAM@ARCTOS> select count(*) from cf_temp_specevent where username='ACHINN' and LOCALITY_ID is null;

  COUNT(*)
----------
       134

```

Temporary names is an interesting idea - maybe a new Issue? Auto-expiring something like that makes me a little nervous, but I'm sure we could find a way. Maybe that's just another bulk loader/unloader pair? Of if this is a rare/legacy/whatever thing then I can just SQL them in/out. Knowing more about what you're doing would be useful if this heads towards creating tools.

**Comment by campmlc** [comment]
I am concerned about using names, precisely because of what Teresa is
describing. Why not make the locality ID the permanent name? They are
clear, trackable, and won't cause community issues. Names can be
duplicated, or misunderstood. If I want to call "Cleveland Zoo" one
locality where we get our wolves from, but someone at a different
institution wants to use a more specific locality (e.g. georeferenced
precisely at the garbage dump where they trapped a raccoon), and also call
it "Cleveland Zoo", how do we track that?

There are over 100 localities for "Boone's Draw" in New Mexico. Many differ
just by elevation or a slight difference in the georeferencing error
radius. What names are we going to give to all those, or even to a subset
if we clean some of them up and consolidate them somehow?

**Comment by dustymc** [comment]
If we're OK with duplicates then that's possible. If there's any desire to update one thing instead of maybe-thousands when we get more/better information, then that would be a huge step backwards. 

>Names can be duplicated

They cannot.

> If I want to call "Cleveland Zoo" one locality where we get our wolves from, but someone at a different institution wants to use a more specific locality (e.g. georeferenced precisely at the garbage dump where they trapped a raccoon), and also call it "Cleveland Zoo", how do we track that?

Whoever got there first owns the name.

>What names are we going to give to all those,

I'd recommend none. If I had to name them for some unimaginable reason, I'd use UUIDs (which can be generated from the forms on request).

>clean some of them up and consolidate them somehow?

Names actively prevent that. They're intended to preserve and identify localities which have already been cleaned up and consolidated.

http://handbook.arctosdb.org/documentation/locality.html#locality-nickname

**Comment by anna-chinn** [comment]
> @anna-chinn 134 of your records in the loader do not have a locality_id - do you want to change that before I proceed or should I just ignore those?

That's intentional. Those are specific locality names that I'm trying to update during this event bulkload.

> Knowing more about what you're doing would be useful if this heads towards creating tools.

Right now I'm trying to update some of our date ranges. For most specimens, I'd like any new collecting events to be related to the same the localities as the events currently in Arctos. I thought about relying on the locality merging scripts to make sure that specimens with new events stuck together, but I'm worried that locality data might become disparate between when I pull them for the event bulkloader and when localities would be set to merge automatically.

**Comment by dustymc** [comment]
@anna-chinn of course it can't be simple - there's a locality used by locked Events involved, 10140249. Can I just remove it from the bulkloader?

**Comment by anna-chinn** [comment]
@dustymc Sure!

**Comment by dustymc** [comment]
Your data in the bulkloader should now all contain locality_name. Let me know if you have any problems - I may need to flush locality_id to get things going. And let me know when/if you want those localities un-named.

**Comment by anna-chinn** [comment]
I just finished with the events. Feel free to un-name the localities! Thanks so much for you help, Dusty.

It would be great to be able to do this at will for a given list of locality_ids when we are working with particular localities that we don't want merged or changed during that process.

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/1990

The temp names are coming off now, hopefully will be done by the time you read this....
