### ISSUE TITLE
Move location of media on object detail page

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#1918]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
My problem is that the media for our objects is often "hidden" at the bottom right corner of my screen. The layout on the object detail page is quite off-balance with the left column vs. the right column.

**Describe the solution you'd like**
I would like to propose that we move the object media frame directly below the Identifications frame, above the Locations.

This would allow users to immediately identify if this is in fact the item we're looking for, without having to scroll to the hidden corners of the record. It would also prioritize the object photos over the sometimes-random media that is associated with locality data, which can create a great deal of confusion for expert and novice users alike, as well as the sometimes less-important media associated with the accession. Lastly, it would help get the two columns more "in balance" visually, which for users of small screens, is increasingly important.

**Priority**
I would like to have this resolved by date: 2019-02-28.

Photos for an example:
Hmmm, where are my object photos?
![screen shot 2019-02-12 at 9 53 43 am](https://user-images.githubusercontent.com/17605945/52660485-3c27ba80-2eac-11e9-8837-a3322f00dff2.png)

Oh yeah... way down here!
![screen shot 2019-02-12 at 9 54 05 am](https://user-images.githubusercontent.com/17605945/52660522-506bb780-2eac-11e9-9c26-ec74126bd3c4.png)

**Comment by dustymc** [comment]
Unassigning me for now; this isn't much of a technical problem, I'm happy to shuffle things around however ya'll want.

Is anyone opposed to moving specimen media between identification and location?

**Comment by Jegelewicz** [comment]
Maybe, because when there is a lot of media, it could obscure the locality, which for us nat hist people is potentially more important.

I suggest instead that each of the main boxes be expandable such that you can see what is available generally, but perhaps not all the detail unless you expand a given area. Make sense?

**Comment by AJLinn** [comment]
The media box will only show 4 images at a time regardless of how many you have posted, so this is the largest it could ever be. (see http://arctos.database.museum/guid/UAM:EH:UA2015-018-0001AU for an example where there are 42 images but only 4 show on the detail page)

I agree we should always have the [expand] option available.

**Comment by dustymc** [comment]
> always have the [expand] option available.

Media is "collapsed" by default - I'm not sure I could collapse it any more and still have it make sense??

**Comment by AJLinn** [comment]
I think the size it is now works fine for most collections. Clicking on the "view details" is better for seeing all the media together anyway.

**Comment by Jegelewicz** [comment]
Not just media - the other stuff too, so that you could see all of the major "boxes" on a single screen.

**Comment by dustymc** [comment]
@AJLinn I can easily adjust the page size of Media displayed. Showing everything isn't an option - looks like there's currently a specimen with 244 images, could be more....

@Jegelewicz screenshots and specifics would be very useful - I do not understand what you're talking about.

**Comment by marecaguthrie** [comment]
I would be absolutely thrilled if the media box could move directly below identifications.

**Comment by Jegelewicz** [comment]
Sorry I don't have time to mock up a page, I'm going to try to explain.

**Identifications** would just show the accepted or most recent Id with an "expand" button to expand the section.

**Location** would just show the most recent or accepted event with an "expand" button to expand the section (this is already there, but the Location box still seems huge and shows almost all of the events for the record used as an example above...)

**Parts** already seems to have what I'm talking about and work as I would expect (I can see there are more parts, but the section is not huge).

**Attributes** would just show the first attribute with an "expand" button to expand the section (this is already there, but the Attribute section still seems huge...)

And so on. If we have page that shows you the stuff you can check out (but not everything at once) then there will be less scrolling to find out what might be there.

As long as it will never (can we guarantee that?) make Location fall off the page as viewed WITHOUT scrolling, then media could follow identification, but location is the second most important bit of info for biological specimens after identification so we don't want it falling off the page when there is a lot of media. In the case of the record above, I think that is a possibility, especially on smaller screens.

I'd like to see the major sections fit on a page

Identifications
Location
Agents
Parts
Attributes
Media
Links
Remarks

Make sense? If not and no one else comments - just move on!

**Comment by AJLinn** [comment]
> **Location** would just show the most recent or accepted event with an "expand" button to expand the section (this is already there, but the Location box still seems huge and shows almost all of the events for the record used as an example above...)

Cultural collections often have three distinct locations and it's important that this is not hidden for "casual" users who won't necessarily see the [Expand] box. I actually like the size of that particular frame as it stands... but that's just me.

> **Attributes** would just show the first attribute with an "expand" button to expand the section (this is already there, but the Attribute section still seems huge...)

Most of the data about cultural objects is held in the attributes field and I'd hesitate to make that any smaller than it already is. 
I would like to see an [expand] button for the remarks frame, as we often have long renderings of stories or other historical backgrounds that are transcribed in that field.

**Comment by dustymc** [comment]
"Most recent" is dangerous ground - all of these data are highly variable - eg, the first ID might have 20000 authors (current record is 15: http://arctos.database.museum/guid/MVZ:Mamm:185202) and a book in ID remarks. I think sizing by pixels makes more sense than by "record" but I'm always up for better ideas....

Here's a record with 23 IDs:

http://arctos.database.museum/guid/MSB:Mamm:55245

<img width="653" alt="screen shot 2019-02-14 at 2 45 20 pm" src="https://user-images.githubusercontent.com/5720791/52822667-31655500-3067-11e9-9c98-eb54a0f644b8.png">

the pane does collapse. 

The size of the locality pane depends somewhat on the size of the map you've chosen.

Attributes has some collection-type-specific formatting, so again showing a record would be weird. http://arctos.database.museum/guid/MSB:Mamm:312468 has 93 attributes and looks like this for me:

<img width="699" alt="screen shot 2019-02-14 at 2 51 18 pm" src="https://user-images.githubusercontent.com/5720791/52822921-029bae80-3068-11e9-941e-b45608062331.png">

http://arctos.database.museum/guid/MSB:Mamm:312468 is a good example of a "lop-sided" record - there's not much in the left pane and lots in the right. Identifiers takes up a fair bit of room, and I think very few people will care about those. I'm hesitant to shrink that because doing so would hide things like Genbank links, which many people DO care about. Maybe we could shrink the "links" pane to a line or two - _I_ certainly don't care about those data, but I think ya'll may?? Parts seems reasonable somehow - it's pretty dense, even if ~80% of it's hidden on my screen. Maybe half that many attributes would be useful - but I'm not sure how that would look on other records.

An (evil...) alternative would be to let the data flow across columns, which would even out things on lop-sided records, but then you can never predict where you're going to find things - collectors might be anywhere, for example. We briefly played with that way back when and everyone hated it - I'm just mentioning it because it comes up every now and then.

@AJLinn give me a guid for something that needs an "expand" option and I'll add it.

**Comment by Jegelewicz** [comment]
> sizing by pixels makes more sense than by "record"

Totally fine by me, but not for Angie as she stated above.

This is probably part of what the Israel people were asking. We need other ways of presenting "Arctos" such that it doesn't appear to be "Arctos" (think MCZBase). This seems like a grant opportunity in the making to create a more appropriate interface for cultural collections, like this: https://collections.si.edu/search/detail/edanmdm:nmafa_90-1-1?hlterm=pottery

**Comment by campmlc** [comment]
I'm coming late to this discussion, but this looks like another good use
case scenario for why we need an API and/or customizable interfaces.

**Comment by campmlc** [comment]
Grant proposal, anyone?

**Comment by AJLinn** [comment]
> @AJLinn give me a guid for something that needs an "expand" option and I'll add it.

A couple of good examples that could use an expand option for remarks. I'm sure I could find more if you need them.
http://arctos.database.museum/guid/UAM:EH:UA64-007-0022
http://arctos.database.museum/guid/UAM:EH:UA64-007-0028

> it's important that this is not hidden for "casual" users who won't necessarily see the [Expand] box.

I retract this statement. The size of the box is perfect for me, the scrolling is not that big of a deal. Compared to the scrolling length of other collections, (esp. parts!) whew, we've got it easy. Thank goodness for the expand button.

**Comment by dustymc** [comment]
I'm not sure 'other ways of presenting "Arctos" such that it doesn't appear to be "Arctos"' would be "we." We could definitely expose more API (or for some users access to the DB - that offer has been on the table since Day One). Consumers of that API would need to work out development, hosting, authentication, etc. Or maybe it could be "part of Arctos" under a different fee structure or something.

If we had a magical API that was fully capable of doing everything anyone might ever want, would anyone use it? I think we'd have to have a solid answer to that before we could get funded to build such a thing, but ????????

Arctos data tend to be scattered around to various other things with APIs. Any question that can be answered with the data we provide GBIF can be answered with GBIF's API, for example.

The current Arctos API should be fully capable of supporting a "pretty picture and some text" UI.

**Comment by dustymc** [comment]
@AJLinn those are about the same size as collapsed expandoboxes on my screen.

<img width="694" alt="screen shot 2019-02-14 at 3 45 31 pm" src="https://user-images.githubusercontent.com/5720791/52824952-a63c8d00-306f-11e9-9e47-af6e595aa574.png">

Is it different from your viewpoint? Do we need a more-collapsed option??

**Comment by AJLinn** [comment]
> Is it different from your viewpoint? Do we need a more-collapsed option??

Nope, that's the same for me. If you're cool with it, I'm cool with it. I don't have a problem with scrolling thru long bits of interesting text, so this is fine especially if we'll be moving media to top left.

**Comment by Jegelewicz** [comment]
Collapsing those would certainly help, but are we then going to run into the large media and locality sections falling under what can often also be a large identifications section requiring scrolling just to get to the localities?

**Comment by dustymc** [comment]
>large...sections

I think all sections have a fixed max size (until someone clicks expand). It's super-easy to change that value, and it shouldn't be THAT difficult to introduce multiple max-height values (eg, if we want to give locality more room than remarks or something).

**Comment by Jegelewicz** [comment]
Could we also have an "expand all" on the specimen page? For those who like to see everything,e ven if it means scrolling for days?

**Comment by dustymc** [comment]
Media just moved.

@Jegelewicz where would you want the expandall link?

**Comment by marecaguthrie** [comment]
This new layout makes me incredibly happy.

**Comment by dustymc** [comment]
I put some little links here for lack of better ideas.

<img width="304" alt="screen shot 2019-02-15 at 1 50 34 pm" src="https://user-images.githubusercontent.com/5720791/52886302-be241780-3128-11e9-8b57-56637713c1bc.png">

**Comment by AJLinn** [comment]
This looks so good! Thank you @dustymc - I agree with Mareca. It's wonderful and will make such a difference for our users. I hope it doesn't create too many hardships for nat hist folks - maybe they'll learn to love it as much as us?

**Comment by Jegelewicz** [comment]
@campmlc see http://arctos.database.museum/guid/MSB:Mamm:1318 - can live with this?

**Comment by Jegelewicz** [comment]
I feel like a change to the specimen view deserves an AWG discussion. Leave as is, but I will add to next AWG Agenda.

**Comment by dustymc** [comment]
Done, closing
