### ISSUE TITLE
Ichnotaxa

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1964]
I just add classification info for an ichnotaxon [Brontozoum](http://arctos.database.museum/name/Brontozoum) and it brought up a few questions:

1. I'd like to know if it makes sense to have "Repichnia" as the kingdom taxon rank.

2. Do we need to use the ichnotaxa ranks (Ichnoclass, Ichnomagorder, Ichnoorder, Ichnofamily, Ichnogenus, etc.) or can we just substitute equivalent (are they?) Linnaean ranks?

3. I think we should label ichnotaxa as such, but I'm not sure what would be the best way to do this. For [Brontozoum](http://arctos.database.museum/name/Brontozoum) I just put "ichnotaxon" in remarks, but I'd rather have a more formal way to treat these. We can use taxon status, but there may also be valid and invalid ichnotaxa (I think?) so I'd rather not use that field. Or does using the appropriate "kingdom" - see https://en.wikipedia.org/wiki/Trace_fossil_classification or set of taxonomic ranks do this for us (see 1 and 2)?

**Comment by dustymc** [comment]
1) Is there some sort of publication suggesting that's a thing? I'd rather _we_ not be the ones to make stuff up! Terms can be unranked.

2) I don't think so - I think those are just a "customary" way to separate these things out. We can add them to http://arctos.database.museum/info/ctDocumentation.cfm?table=CTTAXON_TERM as well, but that seems like a lot of overhead for a fringe use case - maybe because I underestimate how much material exists?

3)  I suspect using a "kingdom" to designate these things will find a way to be problematic. Big picture, I'm not sure I see the necessity of the "this is ichnotaxomony" distinction - like all other taxa, anyone using it probably knows what they mean. Any classification can have any number of labels of any type - status=valid + status=ichnitaxon fits just fine. http://arctos.database.museum/info/ctDocumentation.cfm?table=CTTAXON_STATUS has become a trashcan so should probably be split up anyway, but that's another Issue.

**Comment by Jegelewicz** [comment]
1. https://en.wikipedia.org/wiki/Trace_fossil_classification

2.
> maybe because I underestimate how much material exists?

Probably - I was just at NMMNH last week and they have a room full of ichnotaxa.....

3. 
> "this is ichnotaxomony" distinction - like all other taxa, anyone using it probably knows what they mean.
 Except they don't call the ranks Kindom, Phylum, Class....etc.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I'll talk to our fossil trackway curator next week to get clarification, however my understanding is that higher ichnotaxonomy has been attempted, but may not be used consistently or frequently. I would not use wikipedia as a reference here - for example the article on brontozoum is based on a book produced for a lay audience written by a person who is not a professional paleontologist. A cursory google scholar search shows it may actually be an invalid name.

I do think it would be good if there was something indicating taxa that are ichnotaxa. People who are entering these specimens and researcher will know, but a curious visitor stumbling through the database might want that information too.

**Comment by Jegelewicz** [comment]
Closing as covered by #2394
