### ISSUE TITLE
Add position to Container Locations results

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1968]
How difficult would it be to add the position number for each item in the Container Locations results?

![image](https://user-images.githubusercontent.com/5725767/54321952-cc931100-45b8-11e9-960a-65e49838c581.png)

Maybe like this:

![image](https://user-images.githubusercontent.com/5725767/54322060-4f1bd080-45b9-11e9-9366-985bf2f97377.png)

I'd like to know where in the box each of these cryovials are without having to compare this to the position map.

**Comment by dustymc** [comment]
I don't like that - it's one of very many use cases. I could add "parentage" - http://handbook.arctosdb.org/documentation/container.html#display-format

**Comment by campmlc** [comment]
What does "parentage" look like?

**Comment by dustymc** [comment]
[ MSB ] Museum of Southwestern Biology (institution):[ DGR ] MSB Division of Genomic Resources, DGR (room):[ DGR12648 ] DGR-13 (freezer):[ DGR12574 ] Rack 8 (position):[ DGR16202 ] DGR16202 (freezer rack):[ DGR16219 ] Box position 12 (position):[ DGR16341 ] DGR16341 (freezer box):[ ] 8 (position):[ A44TT ] A44TT (cryovial)

**Comment by campmlc** [comment]
That is way more info than we need and wouldn't fit on the form. Can we
just do the immediate 2 parents, e.g. the A44TT barcode of the container
(already there) and 8 (position) ? We know the DGR16341 freezer box because
that is what we are searching in when we click "show all collection objects
in this container".

**Comment by dustymc** [comment]
We can do WHATEVER but again that is but one of very many use cases. If we add everything in our standard format (and like you point out, screen real estate may complicate that) then it should work for any situation from any "parent." If we add bits-n-pieces we'll likely rebuild the form about 50 times until it includes everything and then can work for any situation from any "parent"....

**Comment by campmlc** [comment]
Maybe this is an interface issue? We can choose how much of the parentage
to see and download?

**Comment by Jegelewicz** [comment]
Because I am looking at stuff in the freezer box, I am not concerned with anything in the tree "above" that, so if the entire parentage is "there", could I then have the option of seeing only the "most immediate parent"?

**Comment by dustymc** [comment]
Lots more discussion of that in https://github.com/ArctosDB/arctos/issues/1585, https://github.com/ArctosDB/arctos/issues/1183, etc.

I think this is related to my constant confusion surrounding "obvious" containers (institutions, buildings, etc.). If you (=Arctos operators with access to your collection and manage_container rights) don't need everything, why is it in the container stack? That exists to help you find specimens; if it's in there, it should be because someone found it useful in finding specimens. Parentage is wildly variable (because it exists for a specific reason which is also wildly variable) so I don't really see any sort of "ignore if...." logic inherent to the data. You can choose to see what you view and download by including the stuff that matters in the data.

I added parentage starting from the "containing container" (so it doesn't include the collection object). All the above aside, that form is fairly limited-scope, so if that's overwhelming this is a good place to play with "bottom 3 containers" or something.

@Jegelewicz the form is not limited to freezer boxes and freezer boxes do not have a set structure, and the barcode field (before I removed it a couple minutes ago...) _IS_ the immediate parent.

**Comment by campmlc** [comment]
We need to know that a freezer box is at MSB in a particular freezer, and
not in Alaska in their "freezer 1"  or in "the Universe" . So we need to
embed in the hierarchy. But if we are looking in one of our own freezer
boxes, we already know all the parentage at the level of the box and above,
and we don't need to see that in the display or download.

**Comment by dustymc** [comment]
I'm not suggesting you need to do anything in particular, other than including the stuff that might need included for some reason. That form should work fine for you with UAM's boxes - containers are shared - which I'll take as evidence that including everything is the best solution (when it fits...). 

You might be able to rename "Genomic Resources" to "MSB Genomic Resources" or  "324 Cryo Room" to "MSB 324 Cryo Room" or even CRYO-01 to "MSB 324 Cryo-1" and get rid of the parents, for example. That'd leave you with


[ DGR-C01 ] SomethingWeCanUseToFindABigMetalThing (freezer):[ DGRC1D ] CRYO1-D (bay):[ DGRC1D68 ] CRYO1-D68 (freezer rack):[ DGR13507 ] 1-1-9 : DGR13507 (freezer box):[ ] 1 (position):[ A7YXF ] NK 561 K (cryovial) 

which won't fit just anywhere, but is still a bit more digestible.

**Comment by Jegelewicz** [comment]
Is it really so hard to say I want the barcode (position) of *This* in *That* to go *Here*, no matter what *This* and *That* are?

![image](https://user-images.githubusercontent.com/5725767/54455401-53fb9400-4721-11e9-8d09-8eb965922013.png)

And please, let's just have the barcode in the "in barcode" field. While the whole tree may be useful, it takes up way too much screen space and it gives me a headache.

**Comment by dustymc** [comment]
> the barcode (position) of 

Maybe I'm just not understanding something - positions by definition cannot have barcodes.

<img width="432" alt="Screen Shot 2019-03-15 at 12 02 41 PM" src="https://user-images.githubusercontent.com/5720791/54455999-4ee71680-471a-11e9-8d9b-9c2b46d6e044.png">


???

**Comment by Jegelewicz** [comment]
Sorry, I thought they essentially WERE a special kind of barcode.

So, how about the POSITION of This in That?

**Comment by dustymc** [comment]
>POSITION of This in That?

That works only for certain things. That form is used by things that do not have a predictable arrangement.

**Comment by campmlc** [comment]
This really should just be an interface issue. Keep the whole tree
somewhere if necessary. But we only want to SEE a column with Position as a
header and a number value..
That's all we need - the barcode of the immediate parent container and the
position number that holds the immediate parent container, one in each
column.

**Comment by dustymc** [comment]
That will result in a blank column for most uses of the form. There's no technical problem with that, but I suspect everyone else want to see something useful in the limited space rather than a column that only works for a certain arrangement.

**Comment by Jegelewicz** [comment]
Can we try it and see who complains?

**Comment by dustymc** [comment]
Not my preferred way to develop, but maybe. Does what's there now not do what you need?

**Comment by Jegelewicz** [comment]
Not perfect, but it will help me get the job done! Thanks!
