### ISSUE TITLE
Missing event and locality change notifications

### ISSUE THREAD

**Issue by anna-chinn** [ArctosDB/arctos#1969]
**Describe the bug**
Dawn and I just realized that we haven't been receiving the nightly locality and event change notification emails for two weeks or so. I'm fairly certain that it's not just CHAS internal junk mail filters because we are still receiving authority table change notifications. Anyone else having this same problem?

**Comment by Jegelewicz** [comment]
I just got this one today:
 You are receiving this report because you are a collection "data quality" contact, or because you are receiving forwarded email from arctos.database@gmail.com. Before attempting to view the report via the link below, sign in to Arctos. You must be logged in to view the report.

This report is available at https://arctos.database.museum/ScheduledTasks/authority_change.cfm?start=2019-03-13&stop=2019-03-14

Code tables changed between 2019-03-13 and 2019-03-14. These data may reflect discarded changes, changes that have not been used in data, or changes that your user cannot access. Contact any Arctos Advisory Group member for more information.
Rows with only N_xxx (new) values are INSERTS.
Rows with only O_xxx (old) values are DELETES.
Rows with N_xxx and O_xxx values are UPDATES.

Table GEOG_AUTH_REC:

ACTION_TYPE | GEOG_AUTH_REC_ID | N_CONTINENT_OCEAN | N_COUNTRY | N_COUNTY | N_DRAINAGE | N_FEATURE | N_GEOG_REMARK | N_ISLAND | N_ISLAND_GROUP | N_QUAD | N_SEA | N_SOURCE_AUTHORITY | N_STATE_PROV | O_CONTINENT_OCEAN | O_COUNTRY | O_COUNTY | O_DRAINAGE | O_FEATURE | O_GEOG_REMARK | O_ISLAND | O_ISLAND_GROUP | O_QUAD | O_SEA | O_SOURCE_AUTHORITY | O_STATE_PROV | USERNAME | WHEN
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
inserting | 10009624 | Asia | Myanmar |   |   |   |   |   |   |   |   | https://en.wikipedia.org/wiki/Kayin_State | Kayin State |   |   |   |   |   |   |   |   |   |   |   |   | SHARPPHYL | 2019-03-13 09:16:57.0
inserting | 10009625 | Asia | Korea |   |   |   |   |   |   |   |   | https://en.wikipedia.org/wiki/Busan | Busan |   |   |   |   |   |   |   |   |   |   |   |   | SHARPPHYL | 2019-03-13 15:08:10.0
deleting | 10009625 |   |

**Comment by anna-chinn** [comment]
I received that one! It's these guys that I haven't been getting:

![Capture](https://user-images.githubusercontent.com/40321380/54369794-8a171600-4644-11e9-8eca-c50319020974.PNG)

**Comment by Jegelewicz** [comment]
I haven't received any of those either. In fact, I can't remember when or if I ever have...

**Comment by dustymc** [comment]
Thanks! I gave them both a kick, you should have email inbound and I think they're both happy now.

**Comment by anna-chinn** [comment]
Email received! Thanks Dusty!

**Comment by anna-chinn** [comment]
I think the locality change notifications have stopped running, again.

**Comment by dustymc** [comment]
Looks like it was timing out - I ran it and bumped that up.

**Comment by sharpphyl** [comment]
I'm getting this report (Arctos Locality Change Notification) but instead of changes to existing localities, I'm getting all the new localities that were created by everyone who did data entry in DMNS:Inv in the past day or so.  Instead of my name (I'm the only one who routinely edits localities) the UserID is "unknown".  Is this what the report is supposed to be?

**Comment by dustymc** [comment]
Let's keep this issue limited to the emails.

I think the request to track who creates localities is from an AWG-ish meeting, summarized (under "accepted solution") in https://github.com/ArctosDB/arctos/issues/1705#issuecomment-463786889. Feel free to start a new Issue for that - that thread has wandered far and wide...

**Comment by sharpphyl** [comment]
But I am talking about the emails - the same one that Anna copied into the thread from February 27.  Here's the one I got this morning:

![Screen Shot 2019-04-03 at 7 34 22 PM](https://user-images.githubusercontent.com/15368365/55523709-8e34c300-5647-11e9-8939-3c911cd27657.png)

These aren't changes. (Nothing is outlined in red.)  They're just all the localities created by new specimen records over the past day or so.  In the past, what I got was changes to localities that I had made.

**Comment by sharpphyl** [comment]
In the email **Arctos Locality Change Notification** received this morning, I'm still getting a list of every locality CREATED by new specimen records - not CHANGES to existing localities.  

If that's what we want, it's OK, but it's not what we used to get.  And the email title would more appropriately be **Arctos New Localities and Locality Change Notification**.

In the email **Arctos Collecting Event Change Notification** (also received this morning), I am only getting changes to existing Collecting Events, so that one is still working as always.

**Comment by campmlc** [comment]
I agree we should only get changes.

**Comment by dustymc** [comment]
The notifications reflect what the trigger captures.

https://github.com/ArctosDB/arctos/issues/1969#issuecomment-479715003

**Comment by campmlc** [comment]
We have the View Locality Edits history to see who has created or edited
localities, which is very useful.  However, we don't need to see all new
localities in the emails. For the emails to serve any useful function,they
should just let us know who has made changes to localities used by our
collection. I realize edit and create Locality are now the same trigger -
no way to parse these out? If not, the emails don't really help.

**Comment by dustymc** [comment]
Oh I see, finally, I think...

I could remove notifications involving 'unknown' (or DBA or whatever we're calling that). I can't really distinguish between event types.

That would also remove the notifications when eg, I mangle a million of your localities - I use the same account to do cross-collection stuff. I PROBABLY won't mangle a million of your localities....

Correct and acceptable?

**Comment by campmlc** [comment]
Yes, that will certainly help.

**Comment by sharpphyl** [comment]
Yes, it sounds like that will remove what we don't really need.  Thanks!

**Comment by sharpphyl** [comment]
Not sure you've taken any action yet, but the locality change report I received this morning was all new localities added through single item data entry.


DMNS:Inv | 16 | 16 | unknown | click
-- | -- | -- | -- | --


https://arctos.database.museum/info/localityArchive.cfm?locality_id=10996130,10996131,10996132,10996133,10996134,10996135,10996136,10996137,10996168,10996169,10996170,10996171,10996172,10996173,10996174,10996175

**Comment by dustymc** [comment]
done
