### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#2003]
Dead Link:  https://arctosdb.org/join-arctos/costs/

The link is on page: http://arctos.database.museum/new_collection.cfm

It should probably be: https://arctosdb.org/join-arctos/financial-contributions/ 

Priority - next time someone wants to join Arctos and reads our website to learn more.

**Comment by dustymc** [comment]
Unless someone has a compelling reason to do otherwise and a way to get there, I intend to: 

1) Redirect all arctosdb.org/stuff to arctosdb.org/. I just can't keep up with the ever-shifting structure.
2) Replace alll how-to links with documentation links. Compare and contrast the catalog number format descriptions (a critical decision not easily changed) in http://handbook.arctosdb.org/how_to/How-to-Manage-a-Collection-in-Arctos.html and http://handbook.arctosdb.org/documentation/catalog.html, for example.

**Comment by dustymc** [comment]
I did this:

>See ArctosDB.org for current pricing structure, webinars, etc.

There are documentation links with the relevant fields, and the how-to IS useful. Users should be able to distinguish between documentation (which should be authoritative, if not particularly helpful in figuring out which button to click next) and  how-tos, which are occasionally incomplete (and probably worse) but extremely useful in figuring out which button to push next.

@mkoo can you control header-or-something based on "folder" to somehow differentiate?
