### ISSUE TITLE
How to document river as higher geography?

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#2025]
I hope some of the wise users of Arctos can help me figure out this location-based issue I'm having.

I have five items that I'm trying to update the records for. These are pieces of two separate sternwheeler riverboats that ran (I think) primarily on the Yukon River, and likely also the Tanana River. For the "use" events, I have the dates that they ran on the rivers, and have added  a verbatim locality as "Nenana" (where the boat was often docked) and "Tanana and Yukon Rivers" (the rivers on which the boat transported people & goods). I don't know what to list for higher geography, however...

It seems this is related to issue #1273 for fish collections. As I do more with our boat collection, I will likely need to have a better handle on how to describe waterways. Boat usage needs to be tied to a body of water and I'd like to understand this issue. 

Priority: Normal for now, but I just got grant funding to start working on my boat collection so will become a higher priority starting 2019-05-01.

Here are two of my example records from the same boat:
https://arctos.database.museum/guid/UAM:EH:0656-0001
https://arctos.database.museum/guid/UAM:EH:0658-0003

**Comment by dustymc** [comment]
The best you can do with geography is to use the most precise thing that covers all of the bits - which isn't very precise in this case. "Alaska" or even "North America" is still better than "I have no idea" - https://arctos.database.museum/guid/UAM:EH:0656-0001?seid=2411095 could be tightened up.

I don't think "watershed" is entirely what you're looking for, although "Yukon River Basin, Alaska" is a heck of a lot smaller than either "Yukon River Basin" or "Alaska." (Only about half again the size of California!) The drainage/basin/watershed still covers a LOT of country that's never seen a riverboat.

"Water Body" gets rid of the dirt, but I'm not sure it will fix this either - "Yukon, Tanana, and Koyukuk rivers" may not be something we want in geography, and the boats probably weren't on all of that area anyway. You could just have three use-events that occurred simultaneously, but that's a lot of data to maintain (and understand).

My suggestion (for which I don't yet have a practical solution) is to record the data spatially and use services to pull geography as needed (which also lets users pull the geography THEY care about instead of hoping some Curator happened to record the things they're interested in). Arctos allows WKT polygons in locality, so it's not much trouble to spatially define a locality that is "Yukon R between Kaltag and Tanana, Tanana R below Delta, and Koyukuk below Huslia" (or whatever). Linking that up to some service that provides standardized text-based descriptive data is "just" a matter of waiting for the right service to materialize.

The spatial approach also works for tagged seals that cross oceans, tagged birds that cross continents, whatever.

@mkoo know of anything that can take a polygon and return overlapping/enclosed/etc. "shape names"?

**Comment by Jegelewicz** [comment]
> "Water Body" gets rid of the dirt, but I'm not sure it will fix this either - "Yukon, Tanana, and Koyukuk rivers" may not be something we want in geography, and the boats probably weren't on all of that area anyway. You could just have three use-events that occurred simultaneously, but that's a lot of data to maintain (and understand).

I like the idea of an appropriate polygon, but I also like the idea of the three use events, even if they have overlapping dates, because when maps aren't working the textual descriptions can be interpreted. Also, each event could have the appropriate polygon for the applicable Waterbody, making it easy to determine WHICH SECTION of THAT river the boat traversed.

**Comment by dustymc** [comment]
Also: The precision of your data are going to determine the questions you can answer. If you have a '800 miles of river' event that covers 40 years, you can get at things with a precision of 800 miles and 40 years. If you know the boat was at {place} on {date} and anyone might ever have interest in {place} on {date} (they do!) then that should be an event, events being our only mechanism for recording those data. My answer above was based on some hopefully-unjustified assumptions; if you have precise data, we can and should find a place for them. (The model is fine, but I assume enough events on a specimen would eventually melt the IU.)

**Comment by AJLinn** [comment]
>  If you know the boat was at {place} on {date} and anyone might ever have interest in {place} on {date} (they do!) then that should be an event

I'm sure I could find some historical photos that might place the boat at a particular section of the river on a particular time (if we're lucky enough to have a dated photo) so I'll keep that in mind. As of right now, without going down a massive rabbit hole of researching this boat, I know it was based in Nenana (https://www.alaskarails.org/historical/Strong/index4.html, note in photo 111) and operated by the Alaska Railroad, but besides that, I don't have a lot of specific info.

So, sounds like I'll have a use event as Nenana, with the dates of operation and a note indicating this was the home port, with higher geography as Yukon-Koyukuk Census Area. 
What's my higher geography for the Yukon River, Alaska? Or Tanana River (with a note being between Nenana and Tanana)?

**Comment by dustymc** [comment]
>massive rabbit hole

That's what I suspected!

Adding specific events as you discover them even though there's an overlying event should not be a problem.

I just made

North America, United States, Alaska, Yukon River
North America, United States, Alaska, Yukon-Koyukuk Census Area, Yukon River
North America, United States, Alaska, Tanana River

We can make more if necessary - the intersection of one of those and quad or something could be a useful way to get at Nenana, for example.

The note is probably most appropriate in locality remarks.

**Comment by AJLinn** [comment]
Updated with multiple use events reflecting differing geographies of Nenana, Tanana River and Yukon River, Alaska.

One question, and maybe this is a new issue ? When we have multiple events of the same type (for instance, 1 manufacture, 2 uses, 1 collection) can you make it so the multiples display sequentially together? Right now, my events go made, use, collection, use. Is there a prescribed order on the object detail page?

**Comment by campmlc** [comment]
I would like the option of ordering them. Will mark/recapture data, it
would be preferable to have them in chronological order, not  in the order
of data entry.
Also, there is a problem in that currently, my understanding is that search
results will not return data for all events. Dusty?

**Comment by dustymc** [comment]
I can order them on specimendetail, just let me know how. 

The ordering is currently by verificationstatus "priority"
```
	case
		       when specimen_event.verificationstatus = 'verified and locked' then 1
		       when specimen_event.verificationstatus = 'checked by collector' then 2
		       when specimen_event.verificationstatus = 'accepted' then 3
		       when specimen_event.verificationstatus = 'unverified' then 4
		       when specimen_event.verificationstatus = 'unaccepted' then 5
		       else 6
		    end order_by_vs
```

I'm hesitant to mess with that, but we can order within that - shall I add event type and some sort of date field??

>will not return data for all events

The data are available, but there are practical limitations in stuffing nontabular data into a tabular format.

<img width="354" alt="Screen Shot 2019-04-05 at 8 41 54 AM" src="https://user-images.githubusercontent.com/5720791/55639641-b70ba400-577e-11e9-9c9b-fc5190248f8e.png">

**Comment by AJLinn** [comment]
> I'm hesitant to mess with that, but we can order within that - shall I add event type and some sort of date field??

That sounds perfect and totally logical.

Also... (sorry to keep adding tasks) when you go into the Edit screen for events, the order they display is not the same as how they show in the object detail page. I think the Collection event always shows up first, but on the detail page, it's manufacture. I have to pay very close attention when I go in to edit events and often go too fast and end up editing the wrong one. I don't suppose it's possible to have the events in the editing pane display in the same order as the detail page?

**Comment by dustymc** [comment]
I'll have to look at the code, but I think it's not a problem to get the order the same. (If it is I'll do it anyway, but maybe not immediately).

@campmlc what date should I use for ordering?

**Comment by campmlc** [comment]
For the mark/recapture material, event date in ascending order? That way
the order of the events matches the order of the parts they are associated
with, for those records with multiple consolidated events. And I agree with
Angie about the order of the events in edit mode - I've made the same
mistake of editing the wrong event.

**Comment by dustymc** [comment]
>mark/recapture

That should be in specimen_event_type.

>event date

WHICH event date?

**Comment by dustymc** [comment]
Merging with https://github.com/ArctosDB/arctos/issues/2374
