### ISSUE TITLE
Inputting stratigraphic measurements and data

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#2031]
As we prepare to upload our paleo locality data, I've noticed that there is not a good field to enter stratigraphy descriptions, observations, and measurements.

An example of this type of data would be:

15 feet above base of Pierre Shale

I would like to see this type of data associated with locality as a text field, however I could also see an argument for it being associated with collecting event (observations taken by different researchers could conflict)

**Comment by dustymc** [comment]
I'll assume Pierre Shale is more than 15 feet thick in your example; if not this is a very different conversation.

In general, I think lots of people records lots of data in lots of ways that just aren't very useful in discovery and analysis, often as tradition demands. Arctos was built largely to facilitate discovery and analysis.

Those sort of data ARE useful - someone finding the specimen might find a use for them - and Arctos has lots of remarks-like fields so hopefully digging relevant information out of them won't be too bad. (This one describes the place - I agree it's related to locality, ether as specific locality or locality remarks.) 

What question could you answer with those data as their own thing rather than in a hopefully-not-quite-arbitrary free-text field?

**Comment by Jegelewicz** [comment]
I would record this in geology remark

So you would have:

GEOLOGY_ATTRIBUTE_2 = formation
GEO_ATT_VALUE_2 = Pierre Shale
GEO_ATT_DETERMINER_2 = Nicole Ridgwell
GEO_ATT_DETERMINED_DATE_2 = 2019-04-04
GEO_ATT_DETERMINED_METHOD_2 = Collector's notes
GEO_ATT_REMARK_2 = 15 feet above base of Pierre Shale

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
@Jegelewicz ok, that works for me.
