### ISSUE TITLE
Automation of Georeferencing Statistics 

### ISSUE THREAD

**Issue by dperriguey** [ArctosDB/arctos#2039]
I'm having to request @dustymc to refresh/update the georeferencing statistics regularly to help me with reporting our group's status. 

http://arctos.database.museum/Reports/georef.cfm

Dusty proposed setting up automation for frequent users. He's trying to limit the automation to reduce the drain on Arctos. 

Is there anyone else that needs their georeference stats to be updated regularly?

**Comment by dustymc** [comment]
This is tied to https://github.com/ArctosDB/arctos/issues/2058 - there is no automation happening at the moment.

What is of value in the report? Is whatever that is better done as https://github.com/ArctosDB/arctos/issues/2040?

FYI that "report" started out as an experiment in automation, but it turns out our data is pretty flaky and the data from automation is pretty flaky and I wasn't very successful in telling good georefs from bad. I would not use any of the data involving automation for much of anything.

**Comment by dustymc** [comment]
Map/spatial issues are fixed, this is now on a weekly schedule, closing but suggest we consider merging with https://github.com/ArctosDB/arctos/issues/2040
