### ISSUE TITLE
Do data loans count as specimen usage?

### ISSUE THREAD

**Issue by amgunderson** [ArctosDB/arctos#2049]
I have a project, https://arctos.database.museum/project/10003107, using 26,963 specimens' data for niche modeling. A data loan with 26,963 items is linked to this project as are 2 publications with 26,963 citations. But this usage does not show up in the projects that contributed those 26,963 specimens. See the UAM Denali NP project, https://arctos.database.museum/project/10002123, or the Beringian Coevolution project, https://arctos.database.museum/project/51. This specimen usage and the niche modeling publications should show up in those projects under "Projects using contributed specimens", but they do not appear there.

**Comment by dustymc** [comment]
I think the general the answer is "sometimes"....

Some data loans are like this - data supported by specimens was used to do science, and I'd say that's clearly "real usage" and should be counted.

Other data loans are convenient places to link specimens to random administrative things for random reasons, and you may or may not want to count those as "real usage."

For projects, I don't really see a problem with integrating data loans - I'll go ahead with that if nobody objects.

/remind me in 5 days

For other stuff, ????????

Maybe we need a new type of loan ("administrative"?) that works like data loans (specimens, not parts) so we can make that distinction? Maybe there's no such distinction?

I have no real opinions, but we should probably be consistent in whatever we do.

Thoughts/opinions?

**Comment by dustymc** [comment]
Data loans are now in "Projects using contributed specimens".  

"Looked at this particular specimen in detail" and "one of thousands of records hurled at software" are now in the same container; I don't think that's WRONG, but it seems a little weird to me. Should we try to do something (include loan type somewhere in projects???) to better differentiate?

And while we're here, can we do more with project data? https://arctos.database.museum/project/10002176 popped up while I was clicking around, it's one of 1166 projects that used specimens and didn't produce publications.

<img width="278" alt="Screen Shot 2019-04-22 at 8 33 17 AM" src="https://user-images.githubusercontent.com/5720791/56508527-6663ad00-64d9-11e9-817b-42e649b63815.png">

That seems like something ya'll might want to know about the next time you're eg, considering a loan to involved people. Of course maybe the project did exactly whatever was promised and the ball is in the collection's court, but maybe there's some trend that could help us get better usage statistics in there.

**Comment by dustymc** [comment]
"Projects contributing specimens" should be playing nice with data loans now as well.

**Comment by Jegelewicz** [comment]
> Maybe we need a new type of loan ("administrative"?) that works like data loans (specimens, not parts) so we can make that distinction? Maybe there's no such distinction?

Personally, I don't think there is a distinction. The information was used somehow and that is usage! If someone created a project, then the usage is important for some reason (in the case of UTEP, it is useful for reporting data contributed under a grant).

**Comment by Jegelewicz** [comment]
> And while we're here, can we do more with project data? https://arctos.database.museum/project/10002176 popped up while I was clicking around, it's one of 1166 projects that used specimens and didn't produce publications.

And some of them probably won't. They may be student projects that never get published (hey - that's contributing to education) or projects to provide information for grant reporting (see above).

**Comment by campmlc** [comment]
I make a project for every loan from the create loan form, because I
frequently get multiple loan requests for the same project over time, and I
have all the information and project description in front of me at the time
of the loan request. If I waited until publications came out, I'd have to
dig back and find all that documentation. And really, loans imply projects,
as do many but not all accessions. Since projects are shared across
collections, the important thing is to search on a project agent first to
make sure another collection with a similar loan request has not already
created the project.

**Comment by dustymc** [comment]
>published

Loans are usage; projects bring in results. We have the peer reviewed flag so "publications" can be whatever they need to be in order to demonstrate the value of collections.  Direct evidence of supporting student projects seems a very useful thing to have. (Maybe we need some sort of K-12; ... ;postdoc user-categorization somewhere in here??)

>I make a project for every loan from the create loan form

Seems reasonable to me; projects are in part 'public loans.'

>If I waited until publications came out, I'd have to dig back and find all that documentation

I'm definitely not suggesting you should wait to create projects, projects just make it easy to find usage that hasn't produced results. (https://github.com/ArctosDB/arctos/issues/1257 means that's not so trivial with only loans and citations.)

> over time

I think that's somewhat subjective - is each student a short-term project, or does the advisor run one long-term project? Doesn't much matter from my end, whatever better lets you (and your users) track whatever's important should lead to about the same place as far as tracking results goes.

Shared projects are great, but I'm not sure that's a factor here either.

We have 2765 projects
```
UAM@ARCTOS> select count(*) from project;

  COUNT(*)
----------
      2765
```
1766 of them used specimens
```

UAM@ARCTOS> select count(*) from project where project_id in (select project_id from project_trans,loan where project_trans.transaction_id=loan.transaction_id);

  COUNT(*)
----------
      1766

```
174 of them used specimens and have publications
```
select count(*) from project where project_id in (select project_id from project_trans,loan where project_trans.transaction_id=loan.transaction_id) and project_id in (select project_id from project_publication);

  COUNT(*)
----------
       174
```
97 of those include citations
```
 select count(*) from project where project_id in (select project_id from project_trans,loan where project_trans.transaction_id=loan.transaction_id) and project_id in (select project_id from project_publication,citation where project_publication.publication_id=citation.publication_id);
```

I find it hard to believe that fewer than 100 of almost two thousand usage-projects eventually linked specimens to results. I'm not sure why that is - 95% of loans really don't result in citations, they do but we don't follow through and record that, ??????????

I'm just offering to try to help find a way to use the data we're already accumulating to somehow better document the importance of your collections, if it's something we can control or influence. Maybe we need more information in projects (could be the loan was renewed, never shipped because of various reasons, the collection has a huge backlog of publications for some reason I might be able to help with, etc., etc.), we need new reports that draw on project data, we need an 'add this to publication to {project}' button on the manage citations form, or WHATEVER. I have no idea, can't see any of that detail from here, I can just see somewhat terrifying statistics. So how can I help?

**Comment by campmlc** [comment]
"95% of loans really don't result in citations, they do but we don't follow
through and record that, ?????????? "

Yes, at least for my collection, because we get information back from the
author on only handful of loans, and the rest have to searched based
GenBank and Google Scholar and then tortuously data managed for upload -
not enough time or staffing. We need resources to make this easier. Hence
the request for auto-reminders to loan recipients - in my court, I believe,
as soon as I can get the time to tackle it . . .

**Comment by dustymc** [comment]
That seems like something you could partially mitigate in your loan agreements, and knowing how the person requesting a loan has handled citations in the past seems like a critical piece of information to have when deciding whether to send them another loan or not.

**Comment by campmlc** [comment]
Again, it can take severy years before we know whether a researcher has or
had not published and has or has not notified us. In the meantime, multiple
loans are issued. At 50+ loans per year, tracking this becomes unmanageable
very quickly.

**Comment by Jegelewicz** [comment]
> Again, it can take severy years before we know whether a researcher has or had not published and has or has not notified us. In the meantime, multiple loans are issued. At 50+ loans per year, tracking this becomes unmanageable very quickly.

#2035 now that we have that - can we work on #1448 ? Maybe that would help with the management end....

**Comment by dustymc** [comment]
>add this to publication to {project}' button on the manage citations form

Done.
