### ISSUE TITLE
Tissue Loan Process Improvement

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2060]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
When we get a request for a tissue loan, we end up downloading information about the required tissue samples from Arctos and manipulating it to create a form for students to track the process of pulling, cutting, and replacing tissues in storage.

![IMG_6309](https://user-images.githubusercontent.com/5725767/56929168-2c287b80-6a96-11e9-816b-8c657f22f609.JPG)

**Describe the solution you'd like**
It would be so much more helpful if these steps could be documented within Arctos. Perhaps adding some new [collection object disposition](http://arctos.database.museum/info/ctDocumentation.cfm?table=CTCOLL_OBJ_DISP) terms?

requested - object has been requested for a loan and needs to be pulled (Collection manager would set this status when parts are added to the loan.)

pulled - object has been pulled from its standard storage location to be subsampled (Would it be possible for this status to automagically update when vials are scanned into a "loan" box as students doing the work do not have access to the loan transaction in Arctos? Other ideas for allowing students to change the status?)

replace - object has been sub-sampled and is ready to be replaced in storage (How can we allow students to change this status when they have completed a sub-sample?)

We also need a handy way to allow students to return the vials to their original storage locations and change the status for those tissues back to "in collection" when they do so. At that time, the parts would be removed from the loan, leaving only the sub-samples.

**Describe alternatives you've considered**
We can continue to download and manipulate, but this eventually leads to errors and omissions.

**Additional context**
This is a first stab at what the process might look like. Ideas for making it work smoothly are appreciated!

**Priority**
Please assign a priority-label.

**Comment by KyndallH** [comment]
I think we talked about doing a loan request form via Arctos which would be awesome because the researcher could select which tissues they are interested in (the requested). Granted, we'd still need to go through them and help them but it would be nice to have the list in Arctos so I can easily download the tissue locations. 

Another note is that we don't process tissue loans in a similar fashion to MSB. We do not pull tissues as a step and put them in a loan box. I download the freezer location list from Arctos and sort by location. I had it to a student. They remove one freezer box (students know only one box at a time) from the cryovats and put them in a desktop freezer/LN2 box. The tube is removed, scanned into the loan (make sure it is what we think it is), subsampled, then immediately returned to the box/freezer. My students do have access to loan transactions because I want them to scan a sample in, make sure it is the correct tissue (it really is a bat or salmon) before subsampling.  

What are the barcodes for?

**Comment by Jegelewicz** [comment]
We find that when processing a loan for 150 tissues, it is more efficient to have students to pull all the vials so that they can be cut in one sitting. (Plus it is likely that two different students will pull and cut....)

**Comment by Jegelewicz** [comment]
>  I download the freezer location list from Arctos and sort by location.

More downloading...it would be nice to be able to sort the parts in the loan request by location rather than download stuff...

**Comment by dustymc** [comment]
I've always had the vague idea that disposition is just a lightweight and not very accurate way of recording stuff when better data don't exist.

If you KNOW exactly where the thing is because you're using an object tracking system, "in collection" doesn't really add anything of value, even if someone actually did remember to do the extra work to set it.

If that isn't somehow heretical, maybe we can do more with CONTAINER.PRINT_FG. (It's currently a boolean, but that's easy enough to change.)

Loan approved--> find everything, set print_fg to 'pending loan' (or maybe free-text, which would let you search??)
pulled--->pulled
....
replaced-->NULL

If that is heresy, I certainly have no problem with more values in disposition (as long as they're discrete).

**Comment by Jegelewicz** [comment]
> I think we talked about doing a loan request form via Arctos which would be awesome because the researcher could select which tissues they are interested in (the requested).

#2006

**Comment by dustymc** [comment]
>sort the part

<img width="253" alt="Screen Shot 2019-04-29 at 4 06 55 PM" src="https://user-images.githubusercontent.com/5720791/56932492-e7521400-6a98-11e9-8a2d-db468345218f.png">

<img width="112" alt="Screen Shot 2019-04-29 at 4 07 04 PM" src="https://user-images.githubusercontent.com/5720791/56932496-eb7e3180-6a98-11e9-87c5-e62470f1de41.png">

**Comment by campmlc** [comment]
All this requires download and serious data manipulation to get the form in
the shape of the photo Teresa attached. This takes a lot of time. Plus, I
end up with a paper version of what the locations were, what tissues were
actually pulled and cut for the loan, based on what was actually found,
what had sufficient tissue to loan, etc - I file this in a filing cabinet,
but it would be better to have the students manage this in a form in Arctos.

**Comment by Jegelewicz** [comment]
> I've always had the vague idea that disposition is just a lightweight and not very accurate way of recording stuff when better data don't exist.

I think that it is an IMPORTANT way of recording stuff for anyone not using barcodes (you can'y borrow that because someone else has it...)

> If you KNOW exactly where the thing is because you're using an object tracking system, "in collection" doesn't really add anything of value, even if someone actually did remember to do the extra work to set it.

Fair enough, but just because it has been moved to a "loan" box, that doesn't tell the students (or Mariel) whether it has been sub-sampled or not. Mariel needs a way to track the progress of loan preparation (remember, we are talking about loans of over 100 tissues here!).

> Loan approved--> find everything, set print_fg to 'pending loan' (or maybe free-text, which would let you search??)
> pulled--->pulled
> ....
> replaced-->NULL

The problem is, this doesn't all happen at once. It may take students a week or more to actually pull everything. Also, we need the middle step of sub-sampling.

**Comment by KyndallH** [comment]
> We find that when processing a loan for 150 tissues, it is more efficient to have students to pull all the vials so that they can be cut in one sitting. (Plus it is likely that two different students will pull and cut....)

We also have multiple people pulling and subsampling a loan of 100+ samples. I find having fewer steps more efficient and I don't have to spend a ton of time making a spreadsheet or transferring to a new box or then putting them back. 

> More downloading...it would be nice to be able to sort the parts in the loan request by location rather than download stuff...

And yes, more downloading BUT the paper copy is super nice so when you are standing next to a cryovat, you know what rack you want without having to go back to the paper. Even with a non-paper system, I'll still be downloading and printing off a paper copy. 

I'd be interested in hearing how other places process loan requests and if these proposed changes would help them. I know they aren't needed here.

**Comment by dustymc** [comment]
>for anyone not using barcodes
>when better data don't exist.

Same thing....

>moved to a "loan" box

That's from container.parent_container_id

>has been sub-sampled or not

That's from "print_fg" (or something like it).

>doesn't all happen at once

Exactly! Stuff gets moved into some sampling box, you do something on some sticknote then get run over by a bus (plz don't), it may take a decade to find it. Stuff gets SCANNED to some sampling box, you get run over by a bus, everyone still knows where it is and what's going on with it.

>middle step

That's in the "...." I don't think there's any limit to the 'status' values - if you have 50 steps in your process, we could add 50 values.

**Comment by AJLinn** [comment]
> I'd be interested in hearing how other places process loan requests and if these proposed changes would help them. I know they aren't needed here.

For those of us who don't do tissue loans, how is this going to impact our "standard" loan processing / documentation? (For all the other types of loans we have) I've just been noting all of these stages in the Remarks field using a date and a description of what's been done, and how long it took. Seems like the more collection object disposition types there are, the more chances there are to not remember to update the disposition each time you do something. 

> maybe we can do more with CONTAINER.PRINT_FG

Um, what's that? Should I be using it? What's it do?

**Comment by dustymc** [comment]
>how is this going to impact our "standard" loan processing / documentation?

Worst case, no change - I don't think any approach to this would change anything existing or be required for anything. Best case, maybe it gets a bit easier to stay organized.

> what's that

<img width="271" alt="Screen Shot 2019-04-29 at 5 21 24 PM" src="https://user-images.githubusercontent.com/5720791/56934988-503e8980-6aa3-11e9-932f-6931eed0a86d.png"> 

is it AFAIK. (And it's not a boolean after all...) I'm just suggesting we could expand it to more than 'need to print.' That could be done instead of or along with adding more disposition values, or the disposition approach could work too.

**Comment by campmlc** [comment]
Reviewing this - I'm not sure that at MSB we need the change in disposition because we do use barcodes and object tracking. The challenge is that a loan of 100+ samples may actually end up being only one sample needing to cut in each box - we have lots of boxes - so assigning a box at a time to a student doesn't work. I now use Parts Table download from Search Results rather than Flatten Part Locations to generate the list of part locations, which is much easier to manipulate to get a summary to hand off to a student.  Students do not add items to a loan - I do, from the barcode list on the page. This is necessary because we have over 500,000 legacy containers with no barcodes, and they are given new barcodes during loan handling and processing. I have the paper copy of the Parts Location download for students to stick the second copy of the newly assigned barcode, which can then be added to the part using scary red box prior to loan bulkload.
So we all have different loan protocols.
Generally I have my students pull up to 20 vials at a time, cut them, and return them immediately, recording what was pulled, cut, and returned on the paper Locations spreadsheet I give them.  But this does not involve changing the status of a container in object tracking. That is problematic if samples are not able to be returned immediately, because they have been removed from their positions without any digital record of the move having occurred.  We stick things in a Loans in Process rack, which is the obvious place to look if something is missing. But ideally we'd pull the tubes, scan them into a Loan Box, add all items to loan with subsample option from object tracking. We would still also have to have a paper copy of the part locations, because if they are scanned into a loan box, we need to know where they need to be returned to and rescanned back into position- a lot of extra work with computer and scanners that we currently don't do. 
Is there a way to download a report from object tracking of an object previous location - like the parts table download, but with an extra set of columns for the location history one step back?

**Comment by Jegelewicz** [comment]
I think that the Parts Table download has solved the original issue here - I am going to close this.
