### ISSUE TITLE
How can we map everything without encouraging people to dump locality data (eg, for zoos)?

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#2068]
ref https://github.com/ArctosDB/arctos/issues/1942 - what should be excluded from in-Arctos maps?

**Comment by Jegelewicz** [comment]
My take - nothing. We have to remember that there may be people interested in "captive" things.

**Comment by amgunderson** [comment]
I agree, anything with coordinates should map, which I think is how it works now.

**Comment by campmlc** [comment]
Agree.

**Comment by dustymc** [comment]
OK - how about this then:

How can we map everything without encouraging people to dump locality data (eg, for zoos)?

(And FWIW this is essentially what I'm trying to get at in #1942. Some - most maybe! - collections have thrown out data because they don't see value, or see negative value, in coordinates to eg zoos. Others of us are horrified by this, esp. as we're trying to push Arctos for education. There's no single viewpoint to what's useful locality data.)

**Comment by Jegelewicz** [comment]
> How can we map everything without encouraging people to dump locality data (eg, for zoos)? (And 
> 
> FWIW this is essentially what I'm trying to get at in #1942.  Some - most maybe! - collections have thrown out data because they  don't see value, or see negative value, in coordinates to eg zoos.  Others of us are horrified by this, esp. as we're trying to push Arctos for education. There's no single viewpoint to what's useful locality  data.)

I am one of the horrified ones. I really hope that we will all start to see our data as useful to more than a single audience.

I have been turning this over since our meeting and I think we already have an appropriate model, we just need to make it more understandable/useful and perhaps develop some warning language on search results.

In a way, I don't understand how removing coordinates does anything good. Those camels in Alaska will show up in anyone's search for "camels" or everything in "Alaska". Lack of coordinates just means they won't show up as points on a map. Download data from the above-mentioned searches and the camels will be there, potentially muddying up someone's data unless they do a little work on it.

The use of "captive" in collection source makes it easy to remove those camels if you are only interested in things actually running around wild in Alaska or camels in their native habitat. The whole discussion in #1942 started because "wild caught" (and even "wild") are not really useful terms to paleo collections. Changing "wild caught" to "wild" is a good step, but I think we should add "in situ" and "ex situ" for paleo who also might use "float" along with malacology collections. However, this sort of brings us back to @dustymc  [comment](https://github.com/ArctosDB/arctos/issues/1942#issuecomment-466111669). We don't want to make eliminating items from search results too difficult and I personally believe (with education and other things in mind) that we don't want to automatically eliminate stuff for people when we have no idea what they are looking for.

All that said, different disciplines have their traditions and ways of referring to what is essentially the same concept. If I search for camels with no other filters, perhaps Arctos should warn me if there is anything other than "wild" or "in situ" in the results so that I could then decide to remove them from the search (or get results that ONLY include them).

**Comment by campmlc** [comment]
I think this could be address though changes in the search interface with
the use of flags or pop ups that ask the user whether they want to display
or download captive or cultivated records, etc. We could even have
different interfaces for different user types. Ask at the beginning - is
this search for research use? educational use? range mapping? other?

**Comment by dustymc** [comment]
From https://github.com/ArctosDB/arctos/issues/1942#issuecomment-489277052

>I also like the idea of "colorcode maps by collecting source" - but that conflicts with Berkeley Mapper's current color coding. However, people are confused by the current BM colors - it would be good to have a map with a legend/key.

I think "how ... map" is fair game here too.

I believe BM has a mechanism to request changes. (And I think they're planning a major revision, so this might be a good time to get involved.)  "Color by {pick a column}" (we send them data as a "spreadsheet") seems ideal - anything we pre-package is likely to not be what *someone* wants.

I can do stuff inside Arctos as well, but there aren't very many maps where I'd show multiple collecting sources and as always screen real estate is at a premium. Very few users have maps turned on in SpecimenResults, and most of them show the small map for example - I'm not sure they'd appreciate a legend taking up space.

**Comment by campmlc** [comment]
Hopefully in their revision they will make it possible to print the actual
map image without all the circles replaced by boxes.

**Comment by dustymc** [comment]
>print

I believe that's part of Google's TOS, so if they go to an open-source solution better printing seems likely.

**Comment by dustymc** [comment]
Edited title to reflect the direction this has gone.

**Comment by diannakrejsa** [comment]
I like the idea of some kind of flag or warning of these captive data during a search. Having the field of COLLECTING_SOURCE is good, but then people have to include that in their data fields that pop up during a search, or during an export of those data. 

Maybe a color code for the records that are non-wild caught; on the map the waypoints/error circles are blue instead of red for example, or the lines of record results in a search are highlighted in some way (with a justification popping up below the cursor when hovering over the record).

**Comment by dustymc** [comment]
The SpecimenResults table (and therefore the download) is usually incomplete when there's any complexity to the locality stack. (The solution is to turn JSON Locality on, and the people who've done that probably don't need more help.) The data they're seeing isn't necessarily the data they should be cautious of; what's squished into the table may be from a pre-capture event.

We're trying to warn people of that with...

<img width="160" alt="Screen Shot 2019-08-23 at 8 55 04 AM" src="https://user-images.githubusercontent.com/5720791/63606010-ff87fa80-c583-11e9-903c-93f653a9df36.png">

which might be a useful place to somehow get at "this specimen contains something you might not expect."

There's more discussion in https://github.com/ArctosDB/arctos/issues/1942.

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/3765 provides a solution to multiple locality assertions, https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcollecting_source exists and is documented, not sure what else can be done, tentatively closing.
