### ISSUE TITLE
adding citations

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#2087]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
When adding citations and choosing the "use an existing identification" option, neither the new identification or the citation appear on the specimen record. I've waited 15 minutes so far and nothing has appeared. However, I see the citations on the manage citation page. I need to confirm that this process is working - I can't afford to wait around and see if something shows up in 24 hours. Help?
I tried this process first by creating a new identification based on the publication, and that identification and citation did show up reasonably quickly, within a couple of minutes.
This is a process that we really need to make as streamlined and simple as possible, and so far it has not been.

**To Reproduce**

**Expected behavior**

**Screenshots**

** Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**

**Priority**
Please assign a priority-label.

**Comment by campmlc** [comment]
https://arctos.database.museum/Citation.cfm?publication_id=10008818

**Comment by campmlc** [comment]
OK, IDs just came through. I've spent 45 min adding three citations, and only now have confirmation that the process worked. Is this normal delay or related to an Arctos slowdown?

**Comment by dustymc** [comment]
I am doing stuff, other people are doing stuff, background processes are doing stuff, ....

24 hours is "normal."

I don't think there's a solution to this which does not involve massive amounts of hardware.

**Comment by campmlc** [comment]
Will this improve with Oracle upgrade?
Perhaps we can add a message to the interface to the effect that if the citations are visible at the bottom of the citations page, then the citations should be visible on the specimen record within 24 hours?

**Comment by campmlc** [comment]
@Dusty - adding you back in for the interface message. I think we need to let people know that just because there is extreme variability in the response rate (<30 sec to 24 hrs), it does not mean their changes have not taken effect

**Comment by dustymc** [comment]
If you mean upgrading to Oracle12, probably not.

If you mean with a tuneup, sometimes and perhaps if there's some sort of drastic performance increase (which wouldn't much surprise me). That can't fix our need to aggressively cache, but we might be able to process more stuff through the cache faster. We're constantly adding more stuff, and more complex(=expensive) stuff, to various caches, so that's sort of a never-ending cycle.

> interface message.

I can (more or less) get the status of the cache for a record and could display it somewhere??

**Comment by campmlc** [comment]
Hmm, maybe a progress bar with estimated time to completion?

**Comment by campmlc** [comment]
@Dusty are you doing something with citations code? I'm getting strange error messages when I search on publications and try to view citations.
[Database Access.pdf](https://github.com/ArctosDB/arctos/files/3192514/Database.Access.pdf)

**Comment by campmlc** [comment]
Actually - the problem is Actos-wide, both operator and public access.

**Comment by dustymc** [comment]
>progress bar

You can sort of get the scope of that from...

<img width="443" alt="Screen Shot 2019-05-17 at 11 21 42 AM" src="https://user-images.githubusercontent.com/5720791/57948242-f9ec8b80-7895-11e9-9b21-f336d8857e00.png">

Just the count is a sorta-expensive query (and not something that could be cached) - adding that to specimendetail or something would significantly slow the page and somewhat increase the load on the DB, which would further slow the page....

The status of a single record - for "us", not so much for public users - is cheap; I'm hitting the table anyway, it's just a tiny bit more data to move.

>estimated time 

"estimate" is kind of a strong word as well. Refreshing FLAT hits most everything so eg, loading taxonomy can slow it just due to stale indexes, I often shut it down to do other stuff, etc.
