### ISSUE TITLE
Locality + Event Type searches

### ISSUE THREAD

**Issue by krgomez** [ArctosDB/arctos#2097]
From comments: https://github.com/ArctosDB/arctos/issues/2044#issuecomment-495725604

**Is your feature request related to a problem? Please describe.**
We would really like to be able to search locality along with event type to get search results that are more precise. Now that we are using depiction events (https://github.com/ArctosDB/arctos/issues/2044), we have realized that we cannot easily search the collection for depicted localities.

**Describe the solution you'd like**
I would like to be able to search for locality + event type together. For example, I want to be able to do separate searches for: artworks made in Denali National Park and Preserve that depict whatever; artworks made in the park that depict Denali; and artworks made elsewhere that depict Denali. Right now I don't even see a way to search for the depicted localities at all without going to the locality page for what I'm looking for and seeing the objects using it (Denali example: https://arctos.database.museum/editLocality.cfm?locality_id=10998105).

It seems like it would be nice to be able to choose what event type information we want to see in the search results. In a search for a certain classification (paintings, photographs, etc.) or even just the whole collection, I think users would be just as interested in seeing a map of all the places depicted in the artworks as they would be in a map of where they were all made.

**Describe alternatives you've considered**
I have considered using whatever I want to be able to search for in the verbatim locality field for depiction events, but this would be an inaccurate use of verbatim locality. Often the verbatim and specific locality are not the same.

Is there something here I'm not thinking of or don't understand that will allow me to do the searches I want to do?

**Priority**
?

**Comment by Jegelewicz** [comment]
So this search wouldn't work?

![image](https://user-images.githubusercontent.com/5725767/58448134-17a2c780-80c4-11e9-86f5-aed0abcc4ac0.png)

**Comment by dustymc** [comment]
From https://github.com/ArctosDB/arctos/issues/2044#issuecomment-495732138

>I think this is a new issue. #755 is perhaps most-relevant. If we search by data from any locality, users get back results that may (from the table, unless they have "json locality" turned on) make no sense to them. If we don't, users can't find what they're looking for. Given a useful replacement, I'd get rid of the tabular results altogether - it's obviously not capable of representing our data. I don't have a useful replacement, and people would start getting out pitchforks if I tried to take their tables away so....

>I'm up for better ideas. Whatever we ultimately do should at least be consistent and documented. It's currently neither.

@krgomez are you wanting to search multiple events - eg, find specimens where (event_1_thing_1=bla and event_1_thing_2=blah and event_2_thing_1=blaugh and event_2_thing_2=blaw) or do you want the existing form (one event-thing, which doesn't necessarily limit itself to one event) to behave differently?

>It seems like it would be nice to be able to choose what event type information we want to see in the search results.

You can, as JSON. Otherwise you might have have 30 columns called "dec_lat" (or we do something horrid that prevents merging downloads with the column names, or ... - there's just no good way to represent complex data in a table). I am completely open to better ideas, but I think they would all necessarily involve radical changes in how we see and present our data.

>I think users would be just as interested in...

We can adjust the default by tweaking https://github.com/ArctosDB/DDL/blob/master/functions/getPrioritySpecimenEvent.sql, but that still involves some way of selecting a single event and stuffing it into a table.

>considered using whatever I want to be able to search for in the verbatim locality field

Please do not try to game the system; you'll just ensure that NOBODY can find what they want. That would make this a data problem, instead of "just" an interface problem.

Here's how to see - not search, that still needs addressed - what's there.

https://arctos.database.museum/SpecimenResults.cfm?locality_id=10998105&collection_id=39&specimen_event_type=depiction

<img width="362" alt="Screen Shot 2019-05-28 at 8 43 32 AM" src="https://user-images.githubusercontent.com/5720791/58491957-cf67c180-8124-11e9-8e7f-88d937bac340.png">

<img width="214" alt="Screen Shot 2019-05-28 at 8 43 42 AM" src="https://user-images.githubusercontent.com/5720791/58491969-d55da280-8124-11e9-9791-c9ce33120ee4.png">

<img width="319" alt="Screen Shot 2019-05-28 at 8 43 53 AM" src="https://user-images.githubusercontent.com/5720791/58491977-da225680-8124-11e9-8f2f-d1f55048ffae.png">

<img width="183" alt="Screen Shot 2019-05-28 at 8 44 04 AM" src="https://user-images.githubusercontent.com/5720791/58491983-de4e7400-8124-11e9-8518-013201ad341b.png">

<img width="296" alt="Screen Shot 2019-05-28 at 8 44 10 AM" src="https://user-images.githubusercontent.com/5720791/58491989-e0b0ce00-8124-11e9-8a94-3e06262d2d52.png">

And FWIW unless "date unknown" is truly verbatim from some involved agent, some variation of "1865-1940" would make those data a bit more approachable.

**Comment by krgomez** [comment]
@Jegelewicz No, unfortunately that doesn't work. That's exactly what I was trying to do and expected to work, but it doesn't. I believe what's happening is it finds me objects that have both the "I want stuff that shows this place" in the specific locality of any event (I think any event, maybe just manufacture, not sure) and also happen to have depiction events, but it does not give me objects that have depiction events for that specific locality.

**Comment by krgomez** [comment]
Thank you for pointing out that JSON Locality option in the search view - that is good to know about.

> @krgomez are you wanting to search multiple events - eg, find specimens where (event_1_thing_1=bla and event_1_thing_2=blah and event_2_thing_1=blaugh and event_2_thing_2=blaw) or do you want the existing form (one event-thing, which doesn't necessarily limit itself to one event) to behave differently?

In my example, I suggested that I might want to be able to search both manufacture and depiction events simultaneously. However, that it not really something we need to be able to do, I don't think. What I am really asking about is the latter -- I would like the one-event thing to behave differently. Otherwise we/users are not going to be able to search the collection by localities depicted.

> Please do not try to game the system; you'll just ensure that NOBODY can find what they want. That would make this a data problem, instead of "just" an interface problem.

Okay, we will not use verbatim locality in this way! I knew it was not a good idea, but was grasping for one.

> And FWIW unless "date unknown" is truly verbatim from some involved agent, some variation of "1865-1940" would make those data a bit more approachable.

Well, this is something that maybe has veered a little from the intended use of verbatim date, but EH does the same thing with unknown dates. EH uses "unknown" whereas we use "date unknown". I guess it's akin to "not recorded" but more useful to us. It's the way unknown date information is presented in other art collections so it's important to have it there and that text field is the best/only place for it. And really, you could say that "date unknown" is legacy verbatim from the cataloger.

**Comment by dustymc** [comment]
>I would like the one-event thing to behave differently.

Thanks - we can work with that.

I think you want to search all events, not just the "priority" - correct?

My reservation there is in finding things people can't see in the table - you search "bla" and get a bunch of stuff back that says "blah" and it's not clear why (until you turn the JSON Locality option on or click through to the detail page). I think that's just where we have to go (and some stuff is already there), but if anyone has any ideas for mitigating the confusion I'd love to hear them.

I think you want the "locality stack" data - events, locality, geography - to match ONE stack, correct? So given a specimen with two events...

```
Thing1: A
Thing2: B
```
```
Thing1: C
Thing2: D
```
a search for..

* Thing1=A+Thing2=D -->finds nothing - the specimen has both of those attributes, but not on the same event
* Thing1=A-->finds the specimen because of the first event
* Thing1=C-->finds the specimen because of the second event
* Thing1=C+Thing2=D--> finds the specimen because both of those are true for **one** of the attached events.

Is that correct?

Is that reasonable/does it break anything else?

>verbatim date

http://handbook.arctosdb.org/documentation/collecting-event.html#verbatim-locality. If I were downloading your data I'd rather find something useful, if vague, in that field. And it might help find the problem if eg one of the bracketing date fields seems improbable.

**Comment by krgomez** [comment]
> I think you want to search all events, not just the "priority" - correct?

I think so. I want to be able to search the collection by events other than just manufacture. Where if I select an event type and other event/locality information the search results will give only objects that have that particular combination.

>  Thing1=A+Thing2=D -->finds nothing - the specimen has both of those attributes, but not on the same event
    Thing1=A-->finds the specimen because of the first event
    Thing1=C-->finds the specimen because of the second event
    Thing1=C+Thing2=D--> finds the specimen because both of those are true for one of the attached events.

Yes, this seems to be what I mean. What I think is happening right now in my searches involving depiction events is Thing1=A+Thing2=D -->finds nothing, if I'm understanding it correctly. 

If I search a specific locality (or any other field that relates to locality or events) and also select an event type I would expect to get search results for only objects where there is an event that is the type I selected that also has that specific locality (or whatever). In my search for event type: depiction + specific locality: =Denali, I expect to get only the objects that use this locality: https://arctos.database.museum/editLocality.cfm?locality_id=10998105 If we could get that to work that would be excellent.

> My reservation there is in finding things people can't see in the table - you search "bla" and get a bunch of stuff back that says "blah" and it's not clear why (until you turn the JSON Locality option on or click through to the detail page). I think that's just where we have to go (and some stuff is already there), but if anyone has any ideas for mitigating the confusion I'd love to hear them.

So you mean that you don't like the idea of getting results related to one event type (depiction) but having the information that displays be related to another (manufacture)? I can see how it could be confusing. What about an option to select which event info you want prioritized that would then display and map. Not possible and maybe even more confusing? I don't understand how that would even work. I'm imagining a drop-down or something where the default is always manufacture (and however events are prioritized for other collections), but then you could choose from the drop-down a different event you would like prioritized for the given search results. Maybe if you do a search involving a different event type other than the default priority type, you could get results displaying the selected event type, but then have the dropdown or whatever option to choose to go back to displaying priority event information but keeping those results you were looking for. I imagine it's not possible or doesn't make any sense to do.

**Comment by dustymc** [comment]
OK, I think I can write code and documentation to that if nobody else has a problem with it. 

>So you mean that you don't like the idea of getting results related to one event type (depiction) but having the information that displays be related to another (manufacture)? 

Yes, but not just event type. Many specimens have many events of the same type - ANYTHING where results don't obviously match search criteria is potentially confusing. Let's call it a documentation problem....

**Comment by dustymc** [comment]
done
