### ISSUE TITLE
Error message when attempting to access Data entry & Data management

### ISSUE THREAD

**Issue by ndisotell** [ArctosDB/arctos#2119]
@dustymc @campmlc 
New to using Arctos for collections management and I'm attempting to enter the data entry page and manage data page and this is the error that is appearing when I do so. The page will not allow me to click anything else without the message reappearing.

Priority: High

OS: High Sierra
Chrome
Version 74

![Screen Shot 2019-06-11 at 2 56 18 PM](https://user-images.githubusercontent.com/51721760/59302594-ed234380-8c59-11e9-874b-b030d915ff62.png)

**Comment by Jegelewicz** [comment]
Do you have access to another browser? I suggest trying to use Firefox to see if you get the same error, then we can troubleshoot from there.

**Comment by campmlc** [comment]
Also try from off-campus.

**Comment by mkoo** [comment]
This looks like a cross-origin problem -- Could be something dusty can fix
checking (eg HTTP or HTTPS) references? I got the same error in the early
days of us applying ssl and now not so much if at all.

What other pages are you getting that error from?

What happens if you just hit ok ? Can you just move on? It also doesnt look
like a fatal error, just a notification. Are you saying it just keeps
popping up?

Trying in Firefox would be interesting...

**Comment by dustymc** [comment]
This looks like your organization manipulating traffic. Using https://arctos.database.museum is usually enough to stop that.

**Comment by Jegelewicz** [comment]
@ndisotell is this resolved?
