### ISSUE TITLE
Adding single specimens to Projects rather than the entire Accession

### ISSUE THREAD

**Issue by acoconis** [ArctosDB/arctos#2127]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

I have set up a project that is based on a particular species occurrence. I want to add specimens to the project that may be in a larger accession (with multiple species), but can only see a way to add an entire accession to a project. Is there currently a way to add just one specimen to a project rather than the whole accession? Or could I request a way to do so?

**Comment by AJLinn** [comment]
I think the current way to add single objects/specimens is to create a loan, add your one item to that loan (maybe it's a data loan?), then add the loan to the project. Then the single item associated with that loan will show up.

**Comment by acoconis** [comment]
Interesting. But creating a loan doesn't really make sense to me. Why would I want to create a loan add specimens to a project? Thanks.

**Comment by dustymc** [comment]
Projects currently document usage or activity. Anything that moves away from that would reduce the value of all projects. What are you trying to do?

**Comment by acoconis** [comment]
We have incoming salvaged specimens and observational data that we want to group together to document an invasive species.

**Comment by dustymc** [comment]
That definitely sounds like usage (=loan) to me - you've used the collection, presumably examined (identified) specimens, etc.

**Comment by Jegelewicz** [comment]
FROM UMNH student Ally Coconis:

> To be honest, all we really need fixed is to delete any un-related (in our case, non- Fox squirrel) specimens from the project. Can that be done?
> 
> We don’t necessarily want to create loans as we have not used the specimens in any way. We have identified them as we have prepared them, but have not used the specimens in any way.
> 
> Thanks for your help!

Ally,

Per the [Arctos documentation](http://handbook.arctosdb.org/documentation/projects.html):

> Projects are primarily endeavors that **contribute specimens, use specimens, or both**

If no specimens were contributed or used then there is no project! The only way to associate specimens with projects is via a transaction (a loan or an accession). Because not ALL of the specimens in an accession are part of your project, effort was required to determine which ones should be part of the project. That effort is USE. Setting up a loan is the appropriate way to do this OR you can move the items you want in the project to their own accession.

It may be true that the specimens were not physically examined, BUT their data has been! Someone looked at the data and determined that certain taxa are invasive. In order to properly document that EFFORT, I would create a data loan, put the specimens determined to be invasive in the loan, then add the loan to the project.

I hope that makes sense!

**Comment by acoconis** [comment]
Thanks everyone. This all makes perfect sense.

**Comment by mkoo** [comment]
Sorry to be late to the thread: just want to endorse Data Loans for this
purpose which is how I often use them. A typical case is where an accession
has a lot of unrelated specimens to my Project (or only a few specimens
from several accessions). A Data loan lets me specify the exact specimens
that need to be linked to a Project which can be something conceptual
(historic transect) or actual data usage (eg., modeling species
distribution). The project is a great way to archive your curated list of
specimens for a specific purpose.

Hope that helps and let us know what your solution is! (feel free to close
this issue too!)

**Comment by acoconis** [comment]
Yes. We will add our specimens to the project as data loans. Thank you!
