### ISSUE TITLE
Locality Changes

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2133]
Why is Gordon Lau making changes to UTEP localities? It looks like a georeferencing event, but there are no remarks and the reason for the change is not super clear. Would it be possible for us to require some documentation of WHY the change was made?

Collection | Change# | Locality# | User(s) | Link
-- | -- | -- | -- | --
all below | 142 | 104 | Diane R. Hunt,Gordon Lau,Jessica Mailhot,Jonathan L. Dunnum,Karinna Gomez,Phyllis Sharp,Zachary Mills | click
CHAS:Inv | 2 | 1 | Zachary Mills | click
DMNS:Inv | 5 | 3 | Phyllis Sharp | click
MSB:Mamm | 1 | 1 | Jonathan L. Dunnum | click
MVZ:Herp | 84 | 79 | Gordon Lau | click
UAM:Art | 5 | 3 | Karinna Gomez | click
UAM:Bird | 2 | 2 | Gordon Lau | click
UAM:Herb | 32 | 16 | Diane R. Hunt | click
UAMb:Herb | 1 | 1 | Gordon Lau | click
UCM:Herp | 1 | 1 | Jessica Mailhot | click
UMNH:Herp | 2 | 2 | Gordon Lau | click
UNR:Fish | 2 | 2 | Gordon Lau | click
UNR:Herp | 1 | 1 | Gordon Lau | click
UTEP:Bird | 1 | 1 | Gordon Lau | click
UTEP:Ento | 1 | 1 | Gordon Lau | click
UTEP:Herb | 1 | 1 | Gordon Lau | click
UTEP:Herp | 1 | 1 | Gordon Lau | click

**Comment by dustymc** [comment]
>Why is Gordon Lau making changes to UTEP localities?

I'm gonna say because both he and shared locality models are awesome!

> the reason for the change is not super clear.

Without coordinates, we can maybe sorta match some strings up sometimes and maybe sorta guess that some stuff might have some sort of relationship with some other stuff.

With coordinates, we can DO STUFF with the data - see if higher geography is appropriate, map it, find it spatially, integrate it with other georeferenced datasets, etc, etc,etc. 

I'd say the reasons for georeferencing are self-evident.

>require [something]

That would serve as a denormalizer; it would negate much of what I consider to be awesomeness.

@gordonhlau

**Comment by Jegelewicz** [comment]
I'm not saying that auto-georeferencing is bad - and it this case it is easy to see what happened, but suppose the coordinates had merely been changed? It would really be nice to know why.

**Comment by Jegelewicz** [comment]
Also - how is a remark a denormalizer? - The field is there, it is just blank.

**Comment by dustymc** [comment]
All of the automation is still behind the scenes; a person - presumably a well-trained person that understands locality data and the locality model (because https://github.com/ArctosDB/arctos/issues/745) - looked at this and decided that whatever they did better represented the data.

>denormalizer

ref: https://arctos.database.museum/info/localityArchive.cfm?locality_id=10460854

There's a very good chance that we'll get a "Texas, that's all we know" in the future. If the spatial data lines up (and if people followed the ["No specific locality recorded." guidelines](http://handbook.arctosdb.org/documentation/locality.html#specific-locality)), this would have fixed 86 localities linked to 1305 specimens, and would be easy to merge in the future so that collections which haven't even found Arctos yet could benefit from Gordon's work. If this one was "Texas, that's all we know" plus unique remarks, the benefits of Gordon's work would end here - this would almost certainly never get merged with anything else, future "just TX" records would remain unavailable for any spatial purposes, and georeferencing "just Texas" would require finding all of the perhaps hundreds of records that don't share localities because the localities don't share remarks.

Locality Remarks should be used for things that help define the place - things that make the locality unique even if they can't be structured - not administrative information.



```
select count(*) ns, count(distinct(locality.locality_id)) nl from  specimen_event, collecting_event, locality where 
specimen_event.collecting_event_id=collecting_event.collecting_event_id and
collecting_event.locality_id=locality.locality_id and
locality.geog_auth_rec_id=1103  and 
(spec_locality is null or 
spec_locality in (
  'unknown',
  'specific locality unknown',
  'no specific locality recorded',
  'no specific locality given',
  'no data',
  'not recorded',
  'captive',
  'blank',
  'Texas',
  'TEXAS',
  'Specific Locality Unknown',
  'SPECIFIC LOCALITY UNKNOWN',
  'Possibly Texas',
  'None given',
  'No specific locality recorded.',
  'No specific locality recorded',
  'No specific locality',
  'No data',
  'No Data',
  'NO SPECIFIC LOCALITYNDE ZOO, IN CAPTIVITY',
  'NO DATA',
  '.'
 29  ));

	NS	   NL
---------- ----------
      1305	   86


```

**Comment by Jegelewicz** [comment]
Direct changes to locality are not specifically recorded as Georeferences. To do that with all the proper information, you have to create a new Specimen Event. I know we have gone around and around with this (#1705), but it bothers me in a way that I am unable to fully articulate. Apparently no one else cares, so I'll just drop it.

**Comment by ewommack** [comment]
Are you thinking of a something back to trying preserve the history of the locality change info as mentioned in #1705 ?

**Comment by Jegelewicz** [comment]
We already decided to preserve the history (the notification we received today was also part of that decision, I believe). So we are doing that, it just feels wrong to me somehow that georeferencing isn't a task that would show up on an Agent's page. (Which brings up a whole other issue - why don't the number of identifications and event determinations show up on an Agent's page?) Creating a whole new event just to add coordinates to "El Paso" seems like overkill. I really think there is a better way to do this, I'm just not sure what it is....

**Comment by dustymc** [comment]
>georeferencing isn't a task that would show up on an Agent's page. 

<img width="178" alt="Screen Shot 2019-06-27 at 4 55 12 PM" src="https://user-images.githubusercontent.com/5720791/60308141-5cf12980-98fc-11e9-8328-d4ae06bec815.png">


>number of identifications and event determinations
<img width="317" alt="Screen Shot 2019-06-27 at 4 45 45 PM" src="https://user-images.githubusercontent.com/5720791/60307824-0800e380-98fb-11e9-9616-5418a1b34c9c.png">

<img width="301" alt="Screen Shot 2019-06-27 at 4 44 57 PM" src="https://user-images.githubusercontent.com/5720791/60307795-ee5f9c00-98fa-11e9-85a6-f12b7f9058c0.png">

If you mean the public agent page, Issue please - I don't think anyone will care (I certainly don't, and it's an easy change), but I think that should be something that happens in the open.

>Creating a whole new event just to add coordinates to "El Paso" seems like overkill.

I agree - coordinates are just **more complete** data, not **different** data, the locality edit archive is enough. You're of course free to disagree by creating more specimen-events, and as long as we're not planning on scrapping the locality model or anything I can probably make it easy/ier to do so. (Maybe I just did - have you tried https://github.com/ArctosDB/arctos/issues/1357?)

>better

I don't think there's a "better," but there's plenty of "different." Toss everything and record much more verbose data in a much less normalized model, toss everything and find a way to normalize/share more, whatever - it's hard to imagine any locality model (that we let people use, anyway...) that doesn't have some sort of trade-off.

**Comment by Jegelewicz** [comment]
> If you mean the public agent page, Issue please - I don't think anyone will care (I certainly don't, and it's an easy change), but I think that should be something that happens in the open

Yes, I would like this. I did my looking while not signed in. If we have students doing georeferencing, they can't use their Agent page to "show" their work.

**Comment by sharpphyl** [comment]
I noticed a different locality edit by Gordon Lau that impacted our collection made on Tue, Jun 25, 9:21 AM.  That one geolocated "Mexico" with an error of 1,715,023 m.  My two specimens are marine so Mexico isn't a very valuable locality (could be an Atlantic or Pacific specimen) which is why we probably would never geolocate something that big.  

There's nothing terribly wrong with the geolocation, but I thought we were supposed to contact the other collections using the locality before making changes that impact their collections. Is that true or not? 

I try to only modify localities that are "used only by" our collection, although a few used by other collections have slipped through and I have contacted them to see if it's ok or I returned the locality to its original condition and created a new one for our collection.  My geolocation is often offshore since it's a marine specimen and wouldn't necessarily be appropriate for other collections even if it sounds the same.

**Comment by Jegelewicz** [comment]
>georeferencing isn't a task that would show up on an Agent's page. 

<img width="178" alt="Screen Shot 2019-06-27 at 4 55 12 PM" src="https://user-images.githubusercontent.com/5720791/60308141-5cf12980-98fc-11e9-8328-d4ae06bec815.png">

This has been on mind overnight. "locality edits" do not equal "georeferenced" and I guess that is what bothers me about this. I am all for improving localities with coordinates, but the same steps are involved in just changing a word or the case of letters in the specific locality. So I found this locality:

![image](https://user-images.githubusercontent.com/5725767/60354291-244b6180-9989-11e9-9667-12ec210acd77.png)

And I really hate the all caps yelling at me, so I made it more appealing:
![image](https://user-images.githubusercontent.com/5725767/60354409-65dc0c80-9989-11e9-9013-4e03e4a0b6fe.png)

Here is my count before the change:
![image](https://user-images.githubusercontent.com/5725767/60354753-2b26a400-998a-11e9-997e-d0accda9dcc0.png)

And After:
![image](https://user-images.githubusercontent.com/5725767/60354772-41ccfb00-998a-11e9-84fd-ab5fa743b488.png)

 I didn't georeference anything, so the big basket of "locality edits" doesn't really tell anyone much about what the person was doing...

Also, sorry to be jumping around, but this one just caught my eye... Why haven't these two localities merged? What is different that I am missing?
![image](https://user-images.githubusercontent.com/5725767/60354699-0cc0a880-998a-11e9-9f5e-e85047437f79.png)

**Comment by dustymc** [comment]
>Mexico

http://handbook.arctosdb.org/documentation/higher-geography.html#guidelines-for-assigning-geography-to-specimens

https://github.com/ArctosDB/arctos/issues/1107 esp. https://github.com/ArctosDB/arctos/issues/1107#issuecomment-435602111

Our documentation still needs some help, but I think it's clear from the community (eg, DWC) and from the behavior of Arctos tools that the locality should be WITHIN the assigned geography, not just reference it. 

>supposed to contact the other collections using the locality before making changes that impact their collections.

That's essentially what the notification does. The model and supporting documentation is designed to facilitate full sharing.

**Comment by dustymc** [comment]
>georeference

I can pull stuff out of the archive, but I'd hate to try to generalize it to vague terms. E.g., is adding coordinates georeferencing? I think @mkoo might justifiably argue that it's not (and it's not particularly useful - you should just assume a "one planet" error with bare coordinates!). I don't know (or really care) what "georeferenced" is, and I don't have to - I can see that UserX added coordinates, then UserY added an error, then UserZ .....

You (presumably) looked over the locality data while you were there and didn't find anything terribly wrong - whatever you did, you added some value/certainty to everything using the locality. You might have even made it more palatable to geolocate, so the automated services work better and we can plug in to more stuff which adds even more certainty to the data. I'm not sure that's necessarily less useful than adding coordinates.

Still, if 'came in without coordinates, left with coordinates' (or whatever) is a useful action I can (in theory - it'll be computationally expensive) find that and label it however you want.


If you'd move that drainage info to geography, we could (potentially, if someone can dig up spatial data) DO_STUFF() with it. In remarks, it can never be more than just a string.


>Why haven't these two localities merged? 

Thanks - I needed a great example of how uncontrolled text fields are denormalizers!
```
UAM@ARCTOS> select ':'|| LOCALITY_REMARKS  ||':' from locality where locality_id in (10888541,10888544);

':'||LOCALITY_REMARKS||':'
------------------------------------------------------------------------------------------------------------------------
:Error accounts for locality placement.  Ends up in El Paso County Texas.:
:Error accounts for locality placement.  Ends up in El Paso County, Texas.:

2 rows selected.
```

**Comment by Jegelewicz** [comment]
> If you'd move that drainage info to geography, we could (potentially, if someone can dig up spatial data) DO_STUFF() with it. In remarks, it can never be more than just a string.

There are thousands of records uploaded prior to the addition of drainage to geography. Any cahnce we could magic those into geography and get rid of the remark?

 

>    Why haven't these two localities merged?
> 
> Thanks - I needed a great example of how uncontrolled text fields are denormalizers!

Don't rub it in....

> Still, if 'came in without coordinates, left with coordinates' (or whatever) is a useful action I can (in theory - it'll be computationally expensive) find that and label it however you want.

Probably a larger discussion of how we are recording effort in Arctos. Collectors and preparators get recognized, but everything else is in various degrees of opaqueness. If we can make Arctos such that it records what people are doing with their time, it can help collection managers better allocate resources and estimate how long it will take to get stuff done. Not easy, but probably useful...

**Comment by dustymc** [comment]
>magic

Maybe - https://github.com/ArctosDB/arctos/issues/2136

>effort...managers

"Made {count} localities suck less" seems a useful metric to me....
