### ISSUE TITLE
New part "trace"

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2137]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Table**
http://arctos.database.museum/info/ctDocumentation.cfm?table=CTSPECIMEN_PART_NAME

**Value**
trace evidence

**Definition**
The imprint of a track, trail, footprint, burrow, etc, of an organism

**Collection type**
Mamm

**Attribute data type**
N/A

**Attribute value**
N/A

**Attribute units**
N/A

**Part tissue flag**
no

**Other ID BaseURL**
N/A

**Context**
trace fossil does not work for trace evidence of extant species (the definition of fossil = the remains or impression of a **prehistoric** organism preserved in petrified form or as a mold or cast in rock.)

Alternatively, we could change trace fossil to trace evidence and use a new definition = The imprint of a track, trail, footprint, burrow, etc, of an organism preserved in petrified form or as a mold or cast in rock.

@ArctosDB/paleontology people should weigh in.

**Priority**
Please assign a priority-label.

**Comment by dustymc** [comment]
I don't like "evidence" - is that a cast, description (no-part observation event), photo (part=media), ??? ALL part are evidence - that's why we keep them!

This is closely related to my "objections" (confusion? Lack of better ideas?) surrounding things like "fossil" in part name. ( https://github.com/ArctosDB/arctos/issues/991, https://github.com/ArctosDB/arctos/issues/1020) "Fossilized" is a preservation method (one that we may not be able to usefully define, but still); it says nothing about what's fossilized. Parts are structurally defined as physical things; this (and fossils, and anything else that's a description of a part instead of just a part) are, at best, awkward. https://github.com/ArctosDB/arctos/issues/1460

Speaking of awkward... how about part "trace" == "a mark, object, or other indication of the existence or passing of something." with preservation (cast, fossil, etc.) in CTPART_PRESERVATION.

**Comment by Jegelewicz** [comment]
I'm down with using trace - it sounds awkward, but makes perfect sense. I added the "evidence" because of that...

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I'm fine with Dusty's solution, although I have a suggestion for the definition of trace. In the ichnology literature, trace is defined as "morphologically recurrent structure resulting from the life activity of an individual organism (or homotypic organisms) modifying the substrate" Bertling et al.(2006). Names for trace fossils: a uniform approach. Lethaia, 39(3), 265-286. I don't know if those studying modern traces would use a similar definition.

**Comment by Jegelewicz** [comment]
I love a definition with a citation and it seems like that would apply to the beaver print that started this, but let me check in with Diana to make sure.

**Comment by Jegelewicz** [comment]
Summary:

1. new part in code table: trace = a mark, object, or other indication of the existence or passing of an organism; in ichnology, a morphologically recurrent structure resulting from the life activity of an individual organism (or homotypic organisms) modifying the substrate

2. all "trace fossil" parts should be migrated to "trace" with the part preservation "fossil".

3. "trace fossil" should be removed from the parts code table

**Comment by campmlc** [comment]
This makes sense.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Sounds good to me.

**Comment by campmlc** [comment]
ACTC meeting 5-21-20 waiting on larger discussion with paleo folks, wait on PG

**Comment by Jegelewicz** [comment]
closing as now covered in https://github.com/ArctosDB/arctos/issues/2546#issuecomment-657692417
