### ISSUE TITLE
Freezer rack positions/racks/box positions floating in the Universe

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2143]
Apparently there are a bunch of MSB freezer rack positions (that include racks and box positions) floating about in the ether of the Universe. We have a new system where rack positions are not given DGR barcodes so I need to get a list of all of these floating objects then decide how best to get them into the new format. I can't just double-click "Universe" to find them. @dustymc can you help me out?

**Comment by dustymc** [comment]
I need an example. There are no rack positions in THE universe as I see it. There may be some your universe. Long live the multiverse....

**Comment by Jegelewicz** [comment]
DGR16303

**Comment by dustymc** [comment]
Oh - right universe, wrong type.

```
create table temp_posnin0 as select * from container where container_type='position' and parent_container_id=0;
```
[temp_posnin0.csv.zip](https://github.com/ArctosDB/arctos/files/3351838/temp_posnin0.csv.zip)

**Comment by Jegelewicz** [comment]
OK, here is a crazy request.

I would like all of these barcodes PLUS any barcodes they contain returned to "container label". Possible?

**Comment by dustymc** [comment]
Labels can't hold anything, so that's not readily possible - I can probably lock things down and do it, but then you couldn't move them. 

There are 129 parts in there, in these.

select container_type,barcode from container where parent_container_id in (select container_id from container where parent_container_id in (select container_id from container where parent_container_id in (select container_id from temp_posnin0))) ;

CONTAINER_TYPE
------------------------------------------------------------------------------------------
BARCODE
------------------------------------------------------------------------------------------------------------------------
cryovial
A6ESF

cryovial
A6F95

cryovial
A70BR

cryovial
A70BG

cryovial
A6EQH

cryovial
A6EQY

cryovial
A6ERF

cryovial
A6ES9

cryovial
A6ERY

cryovial
A6ES2

cryovial
A4WX1

cryovial
A4WX7

cryovial
A6F8O

cryovial
A5YM0

cryovial
A703C

cryovial
A702S

cryovial
A702E

cryovial
A703L

cryovial
A702U

cryovial
A70BD

cryovial
A70CA

cryovial
A6ERD

cryovial
A6EQQ

cryovial
A6ERG

cryovial
A6EQN

cryovial
A6YZU

cryovial
A5VMT

cryovial
A6ESI

cryovial
A6ESH

cryovial
A703E

cryovial
A703O

cryovial
A702Q

cryovial
A702C

cryovial
A702H

cryovial
A703A

cryovial
A70CF

cryovial
A6YZR

cryovial
A6ESA

cryovial
A6E41

cryovial
A6ES0

cryovial
A6ES3

cryovial
A6ERO

cryovial
A4WX4

cryovial
A4WX5

cryovial
A4WXP

cryovial
A4WX2

cryovial
A6F98

cryovial
A6F7U

cryovial
A6F7Y

cryovial
A6FA7

cryovial
A6F9G

cryovial
A6F9H

cryovial
A6FA6

cryovial
A5YL4

cryovial
A5VMZ

cryovial
A6EQX

cryovial
A702B

cryovial
A70BU

cryovial
A70C7

cryovial
A6EQU

cryovial
A6ERE

cryovial
A6YZN

cryovial
A6ES6

cryovial
A6ERX

cryovial
A6ES4

cryovial
A6ES7

cryovial
A6ERV

cryovial
A6F9L

cryovial
A6F7W

cryovial
A703N

cryovial
A7025

cryovial
A70BL

cryovial
A7039

cryovial
A70C5

cryovial
A706C

cryovial
A6EQI

cryovial
A6ESC

cryovial
A6ESE

cryovial
A6ES1

cryovial
A6ERT

cryovial
A4WXB

cryovial
A6F9C

cryovial
A6F9A

cryovial
A6F99

cryovial
A5YM1

cryovial
A702X

cryovial
A7022

cryovial
A6ERH

cryovial
A6EQM

cryovial
A70CE

cryovial
A70CG

cryovial
A7023

cryovial
A702Z

cryovial
A70BF

cryovial
A6WCH

cryovial
A6ESD

cryovial
A6ERZ

cryovial
A6ERW

cryovial
A6ERU

cryovial
A6F97

cryovial
A5YL6

cryovial
A6EQR

cryovial
A703H

cryovial
A7028

cryovial
A7024

cryovial
A702L

cryovial
A70BY

cryovial
A70BC

cryovial
A6EQP

cryovial
A6YZP

cryovial
A6ESG

cryovial
A6ESB

cryovial
A6ES8

cryovial
A6ES5

cryovial
A6ERQ

cryovial
A6ERR

cryovial
A6ERP

cryovial
A4WWZ

cryovial
A6F7V

cryovial
A6F7X

cryovial
A6F96

cryovial
A6F8P

cryovial
A6F7Z

cryovial
A5YLZ

cryovial
A7026

cryovial
A7031

cryovial
A70BE

cryovial
A6YZQ

cryovial
A6YZS


129 rows selected.

**Comment by Jegelewicz** [comment]
OK then, I'll just click click away and fix this stuff.
