### ISSUE TITLE
Edit Collecting Event error because of Verification Lock; need better UI feedback

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#2149]
Troubleshooting with a curator: When trying to update the verbatim coordinates to corrected coordinates in collecting event, we got this error:

An error occurred while processing this page! Error Executing Database Query. [Macromedia][Oracle JDBC Driver][Oracle]ORA-20001: This collecting event is used in verified specimen/events and may not be changed or deleted. ORA-06512: at "UAM.TR_COLLECTINGEVENT_BUID", line 25 ORA-04088: error during execution of trigger 'UAM.TR_COLLECTINGEVENT_BUID'

I realize now that the error was because of the Verification Status of involved specimens.
--

**To Reproduce**
1. Go to https://arctos.database.museum/Locality.cfm?action=editCollEvnt&collecting_event_id=10202309
2. Click on Use Locality Coordinates for this Event
3. Click on Save
4. See error above! I realize now that the error is because of the Verification status of the specimens. After changing from Verified and Locked to Unaccepted (and presumably Free) it worked.

**Expected behavior**
We need to send useful feedback to user to correct. In this case, simple error message like "Check your Verification Status before you can proceed!" Right now Users see the above error message and freeze up so not helpful!

**Comment by dustymc** [comment]
That's easy to change, but "This collecting event is used in verified specimen/events and may not be changed or deleted." seems more useful (informative) than "Check your Verification Status before you can proceed!" to me....

**Comment by mkoo** [comment]
Works for me. The main point is something that starts in friendly English, not Oracle-ese, since that is what causes users' brains to freeze (witnessed just now!)

**Comment by dustymc** [comment]
>starts in friendly English

OH!!! I'll see what I can do, while we're all thinking about things that shouldn't really be done in a production DB....

**Comment by campmlc** [comment]
I agree that users should always see friendly English instead of Oracle
errors. A new committee to translate messages?

**Comment by dustymc** [comment]
OK, somebody go break something and see how it looks.

<img width="1323" alt="Screen Shot 2019-07-08 at 1 38 44 PM" src="https://user-images.githubusercontent.com/5720791/60841088-cdfad180-a185-11e9-97bc-8202d668cd1b.png">

**Comment by dustymc** [comment]
>translate messages

http://handbook.arctosdb.org/documentation/understanding-errors.html

**Comment by campmlc** [comment]
Yes, but maybe we could have these kind of translations appear live
instead, without having to know to go look them up somewhere, which many
(most) people don't know how to do. For example, instead of:
"integrity constraint (*schema.table.column*) violated"

We would see:
"integrity constraint (*schema.table.column*) violated"
Problem

You’re trying to delete something that’s been used elsewhere.

Solution

Delete “child” data.

More Information

These errors are most commonly encountered when attempting to delete
specimen parts which have been on loan. Arctos (usually) links specimens to
loans via parts. Deleting loaned parts therefore removes any record of the
specimen having been loaned, and so is prevented. In the unusual situation
where it is desirable to delete loaned specimens, first remove them from
any loans then proceed with the delete.

**Comment by dustymc** [comment]
> translations appear live

Yes, that's possible - it's why Oracle error messages have codes. This should be a new Issue - eg it should probably come after https://github.com/ArctosDB/internal/issues/27 if that's a real possibility. 

>many (most) people don't know how to

EVERYONE who uses Arctos should know how to use GitHub, where to find help, at least that the how-tos and tutorials exist, etc. That's definitely not the case; how do we better direct people to those resources?

**Comment by dustymc** [comment]
done
