### ISSUE TITLE
Show event ID when picking new event

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2237]
I am trying to correct a bunch of parasite records that have an incorrect collecting event. I cannot select the correct event using the event ID, but have to use the locality. The problem with this is that for some localities, there are multiple, very similar events and I still may end up with the parasite in a different event from the host. Can we show the event ID on the pick list so that I can be sure to select the correct event?

![image](https://user-images.githubusercontent.com/5725767/63708569-09169a00-c7f2-11e9-9b4b-8d3d29fc4f36.png)

**Comment by campmlc** [comment]
We need to have a collecting event ID that is stable and that can be
distinguished by a human being from other event ids in order to be able to
match host and parasite collecting events. This is why 7 years ago we added
collecting event ID to the manage dropdown options to download with
specimen data - so that we can grab the host collecting event and load it
to the parasite. If this is not a stable identifier, how are we going to do
this?
