### ISSUE TITLE
Encumbrances not working!

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#2268]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
Encumbered records  = mask record= are showing up on public view.
**To Reproduce**
Search on Pitta anerythra at MSB Birds
One encumbrance was created by Michael Andersen on 2019-02-14 
One I just created to see if it was some sort of user issue.
The records are visible.

**Comment by campmlc** [comment]
All 6 records are showing up on GBIF but only the two non-encumbered records show up on iDigBio.

**Comment by Jegelewicz** [comment]
These are already published at GBIF and a couple at iDigBio. Were the entire records encumbered or just parts? Either way, I can see everything even when I am not logged in.

**Comment by campmlc** [comment]
Even more interesting - the GBIF record says "Information withheld = mask record", but then proceeds to provide all the data.

**Comment by campmlc** [comment]
![Screenshot 2019-09-19 08 13 41](https://user-images.githubusercontent.com/14808196/65254147-11908680-dab9-11e9-95b2-206cab6cb882.png)
![Screenshot 2019-09-19 08 28 48](https://user-images.githubusercontent.com/14808196/65254148-11908680-dab9-11e9-9efd-472baeb4b90f.png)
![Screenshot 2019-09-19 08 39 44](https://user-images.githubusercontent.com/14808196/65254149-11908680-dab9-11e9-8e7f-f593d56278f3.png)

**Comment by campmlc** [comment]
The encumbrance action was "Mask record".

**Comment by dustymc** [comment]
It's "interesting" all right!

I've plugged the hole in Arctos; it'll take a couple hours to rebuild everything. When that's done and confirmed I'll force-rebuild the DWC stuff and see if I can get @tucotuco to help flush this from aggregators.

**Comment by campmlc** [comment]
@Jegelewicz  @Dusty is it possible to expedite the removal of the records from GBIF? Anyone there we can contact directly?

**Comment by Jegelewicz** [comment]
John is probably the best contact we have for that kind of thing.

**Comment by campmlc** [comment]
We should make sure that all Arctos encumbered records are flushed - I imagine this affected everything?

**Comment by tucotuco** [comment]
I have initiated a request with GBIF to flush everything of Arctos from the
index. Once that is done, I can republish all resources again.

Are the encumbered records in the VertNet index?

**Comment by dustymc** [comment]
Thanks!

Yes at least some of them are probably in VN. They should be purged from the Arctos cache in the next few minutes, then I'll rebuild digir_query.occurrence (generally takes about an hour) and let you know when we're ready for a new pull.

**Comment by tucotuco** [comment]
If there is a way to say which collections are not affected, that would be
very useful for VertNet, where the effort is volunteer and the indexing
costs real money.

**Comment by dustymc** [comment]
collections info sent via chat

filtered_flat is cleaned and rebuilt

digir_query.occurrence is cleaned and rebuilt

**Comment by tucotuco** [comment]
GBIF has turned of indexing for the weekend. I will republish the affected data sets and on Monday when indexing starts again, the data sets will be refreshed without the encumbered records. Following are the data sets that are not affected. All others will be republished:

These SHOULD not be affected - they have no mask record encumbrances
GUID_PREFIX
------------------------------------------------------------
ALMNH:ES
APSU:Bird
APSU:Fish
APSU:Herp
APSU:Mamm
ASNHC:Herb
ASNHC:Mamm
ASUMZ:Bird
ASUMZ:Bivalve
ASUMZ:Ento
ASUMZ:Fish
ASUMZ:Herp
ASUMZ:Invert
ASUMZ:Mamm
BYU:Herp
CHAS:Bird
CHAS:EH
CHAS:ES
CHAS:Egg
CHAS:Ento
CHAS:Fish
CHAS:Herb
CHAS:Herp
CHAS:Inv
COA:Bird
COA:Egg
COA:Ento
COA:Herp
COA:Mamm
COA:Rept
DGR:Ento
DMNS:Egg
DMNS:Herp
DMNS:Para
HWML:Para
KNWR:Inv
KNWRObs:Fish
KNWRObs:Herb
KNWRObs:Mamm
MLZ:Bird
MLZ:Egg
MLZ:Herb
MLZ:Mamm
MSB:Herp
MSBObs:Mamm
MVZ:Egg
MVZ:Fish
MVZ:Hild
MVZObs:Bird
MVZObs:Fish
MVZObs:Herp
MVZObs:Mamm
NBSB:Bird
NMMNH:Bird
NMMNH:Ento
NMMNH:Fish
NMMNH:Geol
NMMNH:Herb
NMMNH:Herp
NMMNH:Inv
NMMNH:Mamm
NMMNH:Paleo
NMU:Bird
NMU:Ento
NMU:Fish
NMU:Herb
NMU:Herp
NMU:Mamm
NMU:Para
OWU:Amph
OWU:Bird
OWU:EH
OWU:ES
OWU:Ento
OWU:Fish
OWU:Geol
OWU:Herb
OWU:Inv
OWU:Mamm
OWU:Para
OWU:Rept
PSU:Mamm
STAR:Alg
STAR:Herb
UAM:Alg
UAM:EH
UAM:Ento
UAM:Env
UAM:Fish
UAM:Herb
UAM:Herp
UAMObs:Bird
UAMObs:EH
UAMObs:Fish
UAMObs:Mamm
UAMb:Herb
UC-SCFS:Bird
UC-SCFS:Mamm
UCM:Bird
UCM:Egg
UCM:Fish
UCM:Herp
UCM:Obs
UCSC:Bird
UCSC:Fish
UCSC:Herp
UCSC:Mamm
UMNH:Bird
UMNH:Ento
UMNH:Herp
UMNH:Mala
UMNH:Mamm
UMNH:Teach
UMNHObs:Mamm
UMZM:Bird
UMZM:Mamm
UNM:ES
UNR:Bird
UNR:Egg
UNR:Fish
UNR:Herp
UNR:Mamm
USNPC:Para
UTEP:Arc
UTEP:Bird
UTEP:Ento
UTEP:Fish
UTEP:Herb
UTEP:Inv
UTEP:Teach
UTEP:Zoo
UTEPObs:Ento
UTEPObs:Herp
UWBM:Herp
UWBM:Mamm
UWYMV:Bird
UWYMV:Egg
UWYMV:Fish
UWYMV:Herp
UWYMV:Mamm
WNMU:Bird
WNMU:Fish
WNMU:Mamm

**Comment by tucotuco** [comment]
The following were republished just now with encumbered records removed. Indexing by GBIF should happen on Monday. Removing relevant data sets from VertNet and reharvesting them...

Arctos:GGBN
MSB:Mamm GGBN
CHAS:Mamm
DMNS:Bird
DMNS:Mamm
DMNS:MarInv
KWP:Ento
MSB:Bird
MSB:Fish
MSB:Host
MSB:Mamm
MSB:Para
MVZ:Bird
MVZ:Herp
MVZ:Mamm
UAM:Bird
UAM:Inv
UAM:Mamm
UAMObs:Ento
UCM:Mamm
UTEP:Herp
UTEP:Herp Ost
UTEP:Mamm

**Comment by tucotuco** [comment]
Finished harvesting and aggregating updated resources to VertNet with encumbered records removed.

**Comment by campmlc** [comment]
Given the importance of this, is there a way we can install some failsafe procedures or immediate notification system if the encumbrance system fails again?

**Comment by campmlc** [comment]
see discussion at #1727
We could change the timing on the notifications for encumbrances? Send emails to agents that have created the encumbrance and also manage collection contact. Include encumbrance type and name, so users/collections can review their encumbrances weekly
Dusty will send out as a distinct email so it can be filtered by those not interested.
Get TACC advice on security issues. Problem with use of Postgres vs Oracle.
Let's bring up with TACC.

**Comment by dustymc** [comment]
todo: 
* send weekly email summary to encumbance and collection contacts
* include expired encumbrances
* send with distinct subject to allow filtering

**Comment by campmlc** [comment]
Consult with TACC

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
One instance of why this is important:
[Paleontological Resource Protection Act](http://vertpaleo.org/The-Society/Advocacy/Paleontological-Resources-Preservation-Act.aspx)
SEC. 6304c3 permit specifications

> specific locality data will not be released by the permittee or repository without the written permission of the Secretary.

The Bureau of Land Management is still developing their regulations, but per our regional BLM paleontologist, we should not make public any locality information below the level of county.

**Comment by dustymc** [comment]
There's a tentative report, which you'll need to be logged in to access, here: http://arctos.database.museum/ScheduledTasks/encumbrance_report.cfm

Please have a look, I'll start sending it out on Mondays if there are no change requests.

It's currently set to go to all collections whether they have encumbered specimens or not. Let me know if I can dial that back.

**Comment by campmlc** [comment]
Dusty, is it possible to only send a report for collections that have
encumbrances and only send collection-specific data? E.g. if a collection
has no encumbrance, don't include it in the report? What I'd really like to
see is just a single table with a list of the encumbrances created by
agents in collections I have access to. Possible?

**Comment by dustymc** [comment]
Yes, that's possible, but it's not very paranoid....

The purpose of this is to detect broken code. The potentially-broken code and the potentially-broken potentially-broken-code-detector are all part of the same thing here. It's currently built so that YOU can detect the most obvious breakage, a lack of reports, by noticing that you didn't get anything from Arctos. With what you're suggesting, you can't know if you didn't get anything because there's nothing relevant, or if you didn't get anything because something is broken. Not getting a million "nothing to see here!" emails definitely has some appeal, but I think it's also capable of masking the most fragile part of this.

Technically it's not much problem to adjust this in most any way. Tell me how paranoid you want to be, and how much you're willing to pay, and make everyone else pay (in the form of potentially-useless emails) to support that and I'll figure out a way to make it happen.

Note that the report currently just prints everything, but will be implemented as one email per collection. You won't get all of that, just one email for every collection in which you're an encumbrance owner or data quality contact (unless you tell me something different here).

**Comment by campmlc** [comment]
OK, I can understand the need for paranoid. However, I don't want to see
encumbrances for collections that I do not have access to. Can we send a
report to the data quality contacts for only the collections they are
responsible for?
I also don't think we should publish the encumbrance remarks, which contain
explicit info as to why an encumbrance exists which may have sensitive
info.
It would be helpful to simplify the report and make it more coherent
visually - e.g. get rid of all the extraneous and repetitive computer
language. How about just a list of collections managed by each contact with
a link to the corresponding encumbrances?
Or simply as follows. We also need a statement that data quality contacts
are responsible for verifying and managing encumbrances.
[image: image.png]

**Comment by dustymc** [comment]
You are looking at something that needs discussed, not a final product. Once someone says "go"....


* going to that URL will just fire off a lot of emails, so please don't (applies to all scheduled tasks)
* the report will send ~130 emails every time it's run, one to every collection (with an active contact or encumberer)
* each report will contain data relevant to that single collection only

All of the "computer language" (Subject etc.) is just to send the emails, but I do need ya'll to confirm I'm sending the right things to the right people before I make this live. The body of the emails will all be...

> You are receiving this message because you have encumbered COA:Rept specimens, or because you are a COA:Rept data quality contact. Note that this report includes expired encumbrances. 

> [ a table with zero or more rows ]

> This report was generated by /ScheduledTasks/encumbrance_report.cfm. 


You personally will get a bunch of these because you have those roles in a bunch of collections - one for msb:mamm, one for dgr:bird, etc. You won't get one from any collection you don't have those roles in.

Anyone who's getting these reports can probably access the data; I don't think this adds any significant risk, but I'm also willing to be as paranoid as ya'll want me to be. Remarks is there because I think it will save folks a lot of clicking; confirm if you want it gone.

If we really want to be paranoid, this email (which is fairly complicated due to performance issues) might be best as just be a 'click here to review your encumbrances on Arctos' link. That's easier for me, but doesn't provide a method for you to quickly review without leaving your inbox. Maybe that's not what you're asking for anyway??

**Comment by campmlc** [comment]
Actually, this might be best:
'click here to review your encumbrances on Arctos' link
That way we end up in Arctos and don't disseminate our confidential info
via email.

**Comment by campmlc** [comment]
Another test of whether or not an encumbrance is working is whether there
is a GBIF and iDigBio and Globi linkout on the specimen record? If there
isn't a linkout, can we assume the record is not being published externally?

**Comment by dustymc** [comment]
In that case, the "[ a table with zero or more rows ]" bit of the email would be replaced with a link (to a new form which probably looks a lot like the table). Everything else would remain the same.

Objections?

The linkouts are generated dynamically on demand. I don't have any sane way to pre-check them, and they're a bit dodgy for this sort of thing anyway.

**Comment by campmlc** [comment]
Any way to reduce the clutter and consolidate all collections links (for
which an operator has access) into a single table would be very helpful.

**Comment by dustymc** [comment]
Encumbrances work, there's a report available, closing
