### ISSUE TITLE
Locality Discoverer

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#2272]
In our locality database we record the name of the person who discovered a locality. I cannot find a good place for this in the locality model. Collectors are connected to specimens through Specimen Event. 99.9% of the time, that 'discoverer' will also be a collector, however if we only record the name in specimen event, we lose the information that they discovered the site. This is particularly relevant if multiple people collected at the locality on the date it was discovered. Or in the rare case that the discoverer didn't actually collect anything.

The best place I can think of to record this information would be in collecting event. I could put it in remarks, but then we lose that relational link to the agent.

Would putting an agent field in Collecting Event mess up the model? I can see how that might end up being confusing for other users. Any suggestions on the best way to record this data?

**Comment by dustymc** [comment]
> person who discovered a locality

What precisely does that mean; what is the significance?

> Collectors are connected to specimens through Specimen Event

No, collectors are linked to cataloged items.

Hard to say without understanding why this is important, but on the surface an agent in collecting event looks like a very large step away from "events as spationtemporal facts" and towards something less-normalized.

@tucotuco

**Comment by tucotuco** [comment]
I see this. What does it mean to discover a location? Is its discoverer an attribute of the location itself?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> No, collectors are linked to cataloged items.

Ok, thanks for clarifying, it was not at all clear from the [cataloging documentation](http://handbook.arctosdb.org/documentation/catalog.html) and I had assumed that collector might be ASSIGNED_BY_AGENT_ID under specimen event.

> What precisely does that mean; what is the significance?

All the paleo collections I have worked have some version of 'discoverer' in their locality files, the discoverer being the person out in the field who first observed 'hey there are fossils coming out of the ground in this specific spot'. There are a couple of reasons for keeping track of this information. 

- Scientifically and historically it is important because then you know that person (or their field notebooks) might have information about the original state of the site or they might have a story about how the fossil site was found.

- People like to have credit for their discoveries.

The challenge is fitting this data into the Arctos locality model. At this point I have no idea where the best place to put it would be.

**Comment by dustymc** [comment]
Whoa - we don't have collector documentation?! We should! "Collectors" are Agents who act on cataloged_items in one of these roles: http://arctos.database.museum/info/ctDocumentation.cfm?table=CTCOLLECTOR_ROLE

ASSIGNED_BY_AGENT_ID is the person who asserts that the locality stack pertains to the specimen in one of these roles: http://arctos.database.museum/info/ctDocumentation.cfm?table=CTSPECIMEN_EVENT_TYPE. http://handbook.arctosdb.org/documentation/specimen-event.html#event-determiner

As long as we're modeling localities as spatial data, I don't think that has a place in the locality model. I think it would also be very denormalized there, given how we model localities; you'd end up needing to maintain essentially the same information perhaps thousands of times should someone show up with a decent GPS. (Perhaps not for "legacy" data which tends to be very coarse, but certainly for anything that's remotely capable of supporting things like spatial analyses.) This seems very much like primarily data about an agent, rather than the place (or place-at-time?).

I think that's usually handled via publications - things like http://arctos.database.museum/publication/10005404. Those are linked to agents who presumably collect from the sites they "discover," citations can link them to specimens collected from the site, and projects can make looser links if there are no citations. We could probably add finer-scaled links via Media if that's necessary.

A copy of your "locality data" (eg, everything that might be relevant to localities) would be exceptionally useful. I don't think it's possible to effectively deal with these specific questions in isolation as we've been trying to do; we need to start with a comprehensive large-scale map.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> A copy of your "locality data" (eg, everything that might be relevant to localities) would be exceptionally useful. I don't think it's possible to effectively deal with these specific questions in isolation as we've been trying to do; we need to start with a comprehensive large-scale map.

How would you like to proceed with that? I can do this in one of our data migration threads if that makes the most sense?

**Comment by dustymc** [comment]
Attaching it to some issue is great if that works for you.

**Comment by Jegelewicz** [comment]
We have a temporary solution. Documentation request already added in https://github.com/ArctosDB/documentation-wiki/issues/133

Closing
