### ISSUE TITLE
Agent Mergers

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2319]
From @ccicero 

> I don't agree with these agent mergers where "Mr. " or "Mrs." someone are merged to unknown (there was another similar one recently) . Last name is better than nothing.
> 
> Thoughts from the AWG.

**Comment by ccicero** [comment]
Thanks for making an issue of this!

**Comment by dustymc** [comment]
I think I flagged this one. It was old, not used, didn't follow the [guidelines](http://handbook.arctosdb.org/documentation/agent.html#abbreviation-exemptions), and wasn't structured correctly. It almost certainly came in during some migration, and the lack of use suggests the scripts somehow mangled it and specimens never found it.

Well-formed "Mrs. Whatever" format agents are not a problem.

The possibilities are not limited to low-data agents or nothing - [verbatim collector](http://arctos.database.museum/info/ctDocumentation.cfm?table=CTATTRIBUTE_TYPE&field=verbatim%20collector) also exists (and merged agent are automatically stashed there).

I think choosing the "proper" approach is a case-by-case thing, although perhaps this is a good opportunity to develop some guidance. I'd probably make an agent for "Mrs. Whatever" (which realistically might be refined at some point), but perhaps not for "Smith" (which is probably always going to be "one of these thousand people, maybe"). I'd almost certainly make an attribute for a single occurrence of "ABC," but I'd make an Agent if the cryptic initials are used for multiple records.

**Comment by mbprondzinski** [comment]
I  know I will have a number of Agents with just a Mr. or Mrs.  and a last name.

**Comment by Jegelewicz** [comment]
@mbprondzinski Those should be OK - especially if they are tied to specimens/publications/accessions.

**Comment by Jegelewicz** [comment]
I do think it would be good for us all to have an understanding of what the scripts that look for these things is looking for. Documentation somewhere would be great! (Maybe it already exists, but we don't know where it is?)

**Comment by dustymc** [comment]
>scripts

If you mean the scripts that likely helped create that, they just turn strings into other strings, and I believe all come with 'not magic, review carefully' warnings. (Those live in the Data Services tab, mostly.)

The "script" that flagged this for deletion lives in my head - I think I spotted this one by searching on first name and seeing something that shouldn't be there. That sort of thing does occasionally get turned into scripts, but they're always 'this needs a closer look' and never 'actually do something to data.'

**Comment by Jegelewicz** [comment]
I agree with this:

> Last name is better than nothing.

I don't know what script is running for Agent clean-up, but I think we need to discuss as a community how Agent clean-up should occur. It would be really great if someone would volunteer to take on the [Agents Committee](https://github.com/ArctosDB/arctos/projects/11)! I think we might be doing more to integrate our Agents with already existing platforms like ORCID and Wikidata. There are opportunities for creating a larger Agents community.

**Comment by ccicero** [comment]
I agree that this is a larger community issue and that more integration would be great.

Meanwhile, maybe something could be added to the message to indicate which marked agents are not used by anything or have some other 'flaw' in terms of structure, not just that it's a bad duplicate?

**Comment by dustymc** [comment]
>script is running for Agent clean-up

I think the only thing actively running in the background attempts to "enforce" (if it was actually enforceable it'd be rules, not suggestions....) http://handbook.arctosdb.org/documentation/agent.html#creating--maintaining-agents - they put the 'are you sure....' warnings on top of the agent record, and send emails when something obvious is detected (agents without ASCII variants of preferred names and etc.).

There are some scripts that users can run on demand, I think they all need revised and rebuild. I haven't worried much about that because our agent data are pretty good; it used to take me minutes to find a duplicate when I needed an example, I can't do that anymore. I think our procedures and guidelines work well.

From my perspective, "the community" could immediately do a few things:

1. Include all available information in the proper place in agent records. I think sometimes we don't include available data, probably just due to not having the time it takes to do so. I know that a lot of relationship, address, etc. data gets stuffed into remarks, from where it's not accessible to scripts in any useful way. As addresses or relationships I can potentially DO STUFF with that information.
2. Review the merger emails, and update the involved agent records when possible.

Tighter integration with external sources MIGHT make it a bit easier to detect duplicates, but I doubt it will be significant - agents with that much information can probably be de-duplicated locally. Those services will potentially allow us to pull in data (and maybe that will lead to the discovery of duplicates), and in the case of ORCID allow pulling more information (and being much more certain of what we're getting) when eg, the ORCID is found in publication metadata from CrossRef. There are some really cool and powerful possibilities, but I'm not sure it'll help much with 'basic housekeeping.'

@ccicero https://github.com/ArctosDB/arctos/issues/1873 will provide a place for that, and I hope will be one of the first new developments when we get to PG.

**Comment by Jegelewicz** [comment]
> not having the time it takes

Story of our lives

> a lot of relationship, address, etc. data gets stuffed into remarks, from where it's not accessible to scripts in any useful way.

This is something an Agents committee could tackle (or a student). A report that provided agent name and agent remarks could set someone a goal of remarks to move to more appropriate fields.

**Comment by dustymc** [comment]
That's an easy report to get - it's all in one table. Reports/WriteSQL

```
select PREFERRED_AGENT_NAME,AGENT_REMARKS from agent where AGENT_REMARKS is not null and AGENT_REMARKS not in (select AGENT_REMARKS from agent where AGENT_REMARKS is not null having count(*) > 200 group by AGENT_REMARKS)

```
That filters out remarks replicated across lots of agents - you can remove the not in clause, adjust the number, whatever. Those are currently:

```
UAM@ARCTOS> select AGENT_REMARKS from agent where AGENT_REMARKS is not null having count(*) > 200 group by AGENT_REMARKS;

AGENT_REMARKS
------------------------------------------------------------------------------------------------------------------------
ALMNH agent bulkload
Bulkloaded MSB Mammal agent.
Bird collection agent.
Invertebrate bulkload agent.
MSB:Herp USGS bulkload
UNLV herpetology collector
NMMNHS bulkload agent
Artist
ALMNH ES agent bulkload
MSB Fish bulkloaded agent
UAM ethnology
Migrated from ALA database.
UAM Ethnology & History
MSB Fish bulkloaded record

```

**Comment by Jegelewicz** [comment]
Closing as duplicate of #2928
