### ISSUE TITLE
UMNH new barcode series request

### ISSUE THREAD

**Issue by srobson4** [ArctosDB/arctos#2320]
@dustymc 

UMNH needs 50K alphanumeric barcodes for object tracking the UMNH wet collection.  I would like all barcodes to have 11 places, start with UMNH followed by a random series all beginning with the letter W (designating a container in the 'wet' collection'), and the remaining 6 places can be any combination of capital letters A-Z or numbers 0-9).  Barcodes will visually read as: UMNHW[xxxxxx]

We want to have the barcodes printed by EIM, so can you generate a file with the 50k barcode series that I can send to them to print the sticky labels? 

Thanks for your help creating this series and staking the claim in Arctos.  And thank you @Jegelewicz for also helping us figure this out!

**Comment by dustymc** [comment]
>random series

That is going to be VERY hard to track.

base36 numbers would provide some extra space (and probably look random to most). If you don't need that, just autoincrementing in Excel is probably as good as anything.

@campmlc can you help with this?

**Comment by srobson4** [comment]
Autoincrementing in excel works too.  I was just cut-and-pasting the lingo in the issue request form.  Random isn't necessary but alphanumeric is to avoid confusion with catalog number series.

**Comment by Jegelewicz** [comment]
@srobson4 do you need any help or have we answered your questions?

**Comment by campmlc** [comment]
@Shannen Robson <srobson@eou.edu> I can help with this too. Have you
already created your file? If so, happy to take a look, or help with the
creation.

**Comment by srobson4** [comment]
@Jegelewicz and @campmlc   Thank you!  I still need help.  I haven't created a file as I'm not sure how to make an alphanumeric series.

**Comment by Jegelewicz** [comment]
@campmlc has done this - I have not. As you guys are doing this, could you write a how-to? I'd owe you big time!

**Comment by campmlc** [comment]
Here you go. Short documentation to follow shortly. As I will explain in
the documentation, I strongly advise against using your institution code as
part of your barcode because 1) it is unnecessary and makes the barcode too
long and unwieldy and 2) it can be confused with your catalog number, which
you absolutely don't want to do (you need people to cite the catalog
number, not the barcode).
So this file just has base36 numbers starting with W. There are no barcodes
yet reserved starting with W. I would advise reserving however many you
might ever want to use - 500,000? 1,000,000? - if the letter W is important
to you. Using Base36 means that your 50,000 series starts and ends with a
W0.
One issue with base36 is that you can make a much smaller label but you
need a scanner that will read 2D. We buy Zebra (formerly Symbol) scanners
with this capability that cost about $200 but they are very durable and
functional. Looking to see if there is a phone app . . .

**Comment by dustymc** [comment]
>too long and unwieldy and 2) it can be confused with your catalog number, which
you absolutely don't want to do (you need people to cite the catalog
number, not the barcode).

If long and unwieldy (eg, https://n2t.net/ark:/87299/x67h1gmh) aren't a problem I could get ARKS which can easily serve as citable barcodes. I doubt that'll work here, but there it is anyway!

>scanner that will read 2D

You shouldn't need that - the scanner doesn't know it's base36, it's just reading the string. Base36 strings are A-Z+0-9 which should work with the most basic formats (eg, code39). Even base64 can be encoded as C128B, which can be read with 1D scanners. You should only need a 2D scanner if you're printing 2D (eg, data matrix) labels (or maybe if you really want hieroglyphics or kanji in your barcodes...).

**Comment by acdoll** [comment]
If they are including UMNHW in the barcode, shouldn't they just claim the entire ~2.17 billion combinations with: regexp_like(barcode,'^UMNHW[A-Z0-9]{6}$')

**Comment by campmlc** [comment]
I'm arguing that they should not include any institutional acronym in the
barcode as that is too easily confused with a catalog number. Best to have
a short base 36 sequence that allows millions of combinations but is a
random human readable value of letters and numbers.

**Comment by acdoll** [comment]
Ah, I see that now. That does make sense. The way I did ours was that I forced a letter in the middle so I can't randomly get all numbers - but I see that it could still be confusing.

**Comment by Jegelewicz** [comment]
@srobson4 are you getting anywhere with this? Let me know if you need help!
