### ISSUE TITLE
Paleo part associations

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2327]
Fossil collections often have the situation where several parts are needed to properly describe what is in the collection. An example is http://arctos.database.museum/guid/UTEP:ES:1-1070

In this case, the object is a dentary with two teeth in it. These teeth might be firmly implanted in the dentary, or they could be loose enough to fall out in the drawer. It would be beneficial to any researcher as well as to collections personnel, to understand the exact status of these connected parts. (If someone is interested in the molar, @mvzhuang  might have to loan them all three parts). But it is also important to clearly describe all three parts as each might have separate interest to researchers. @Nicole-Ridgwell-NMMNHS and I are thinking about this for the future and would love to hear ideas about how this could best be accomplished. We'll put any we have here too.

**Comment by dustymc** [comment]
Sounds like condition to me - are you trying to solve some problem that won't work for?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Brainstorming about this. Here is a list of example situations showing how parts could be related to each other in different ways. 

For all of the situations the specimen contains tibia and partial foot (astragalus, calcaneum, and metatarsals 1&2)

**Situation 1** All bones are articulated and are all attached to each other so they are functionally 1 object.

**Situation 2** The foot is articulated and all the foot bones are attached to each other. The tibia was not articulated with the foot, but it is attached to it by rock. The tibia and foot were found beside each other and probably came from the same individual animal.

**Situation 3** The foot is articulated, but all the individual foot bones were prepared so that they are not attached to each other. The tibia was not articulated with the foot and is not attached to any of the foot bones. All were found near each other and probably came from the same individual animal.

**Situation 4** none of the bones were articulated. The astragalus and metatarsal 1 are attached to the tibia by rock and the calcaneum and metatarsal 2 are individual pieces. All were found near each other and probably came from the same individual animal.

**Situation 5** none of the bones were articulated and none are attached to each other. They're all from the same species but their sizes and other context clues indicate they are not from the same individual.

It would be great to be able to make relationships between parts (a is physically attached to b, but not c) and/or (a is articulated with b, but not c). Same/different individual is a more ambiguous relationship that might be best in a remarks field?

**Comment by Jegelewicz** [comment]
> Sounds like condition to me - are you trying to solve some problem that won't work for?

These things might also separately be "good condition", "poor condition", "fragment" and so on. Mashing up the condition of the individual parts with the "condition" of them being articulated or not (see all of the examples above) makes it more difficult to find the "good dentaries with teeth in them" which might be written "dentary w/ teeth, good", "dentary, teeth attached, good", "good dentary, w tooth fragments in" and so on....

**Comment by campmlc** [comment]
If the relationship is ambiguous, could you catalog separately and use
relationships?

**Comment by dustymc** [comment]
Some of this looks like "catalog the item of scientific interest" territory. "Probably ... same individual" doesn't particularly sounds like something that should share a primary identifier; the component parts aren't all equally capable of doing things like serving as physical vouchers to citations in publications. Cataloging (or recataloging) separately would provide a clear place for relationship data.

That won't fix the "articulated with" thing, obviously. Figuring out "foreign key" as a datatype in attributes would, and would be really handy in locality as well. Post-postgres....

**Comment by dustymc** [comment]
Tentatively tabling - this looks like it can all be handled by part parentage ('this toe is from that foot') and entities ('these 12 bones are from that rock-entity, you decide how they might be further related').

**Comment by dustymc** [comment]
>part bulkload 

parent_part_barcode

> after the parts have been created

You can find some convoluted path via the (poorly labeled!) 'subsample' button, but essentially "no" - Issue, doesn't seem impractical.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> essentially "no" - Issue, doesn't seem impractical

Thanks, I will create an issue.
