### ISSUE TITLE
Show Datum/Coordinates in Locality results

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2382]
Neither datum nor coordinates appear in the results of a locality search:

![image](https://user-images.githubusercontent.com/5725767/69373414-faa91480-0c60-11ea-84d6-3950586d066f.png)

they are only visible when editing the locality

![image](https://user-images.githubusercontent.com/5725767/69373255-a9008a00-0c60-11ea-8467-9f69b4782c11.png)

or on the specimen page

![image](https://user-images.githubusercontent.com/5725767/69373293-bb7ac380-0c60-11ea-9cb1-593a04643d3c.png)

I think both should also be visible on the locality search results, otherwise the error, georef source and georef protocol are meaningless.

**Comment by dustymc** [comment]
We can discuss more in PG (locality attributes might be useful too), but

1) localities are not intended to have variable datum, it's just hanging around because we've never had decent tools to convert, and
2) The maximum error that can be introduced by datum shift is something like 20 meters, most semi-normal-map datum shift in CONUS is on the order of a couple meters. It's certainly something that needs accounted for, but I don't think a 400KM+ error is rendered meaningless by anything that could possibly relate to datum.

All Arctos maps use WGS84, so everything should be accurate in your example.
