### ISSUE TITLE
Ichnotaxa

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2394]
- [ ] Needs Best Practice documentation when resolved

It would be good to have a copy of [The Study of Trace Fossils: A Synthesis of Principles, Problems, and Procedures in Ichnoloy](https://books.google.com/books?id=Am3tCAAAQBAJ&pg=PA47&lpg=PA47&dq=epichnion&source=bl&ots=9ziLUMTFk_&sig=ACfU3U2IL7TvUaIzFWx8sEB4fJxgpZn-Fw&hl=en&ppis=_c&sa=X&ved=2ahUKEwit1Jb2lJjmAhUNCawKHZMQCmIQ6AEwDXoECAoQAQ#v=onepage&q&f=false) but, I went to dinner with Andrew Rindsberg, an ichnologist, when I was in Alabama. Here is what he told me about the ways ichnofossils are classified:

1. Taxonomic - name of thing that made the trace. He said this is especially used for vertebrate trace fossils. **Theropoda** from our Grallator example.

2. Ichnotaxonomic -  a name that reflects the morphology of the trace. An ichnogenus or ichnospecies name which may include ichnofamily, ichnosubgenus, ichnosubspecies and so on. **Grallator** from our Grallator example.

> Check out the classification of Grallator on [Wikipedia](https://en.wikipedia.org/wiki/Grallator)....

3. Ethologic - classification according to behavior represented. These seem to be part names but instead of "**trace fossil, crawling**" I think we should be using the defined terms (see Wikipedia link below and book link above). **repichnia** for our Grallator example.

>Also see [Wikipedia](https://en.wikipedia.org/wiki/Trace_fossil#Classification)

4. Toponomic - how the trace was preserved. For example - "epichinion" = bioturbation structure preserved at the upper surface of the main body of the casting medium, may appear as a ridge or groove. This would also encompass epirelief and hyporelief which should be part attributes from the "preservation" code table. Not sure which one applies to our Grallator right now.

5. General trace morphology - burrow, trail, trackway, and so on. This one seems like a "common name" and perhaps should be the common name for the associated ichnotaxon. **track** would be the common name for Grallator.

_Originally posted by @Jegelewicz in https://github.com/ArctosDB/data-migration/issues/53#issuecomment-560941969_

**Comment by dustymc** [comment]
Ichnotaxonomy and "Linnean" taxonomy are separate and should not be confounded. I certainly don't see a problem with mixing them up however best reflects the situation in identifications.

The ethologic and toponomic terms might make decent specimen attributes, but I'm not sure I've got my head wrapped around that yet either.

I can't dispute "track" as a common name of Grallator, but that also necessitates at least two ways of finding tracks - one for taxa that are defined as tracks, and one for taxa that aren't. Ideally I'd be just be able to find all tracks, however they (and/or the thing that allegedly made them) might be classified. That's making me think those data also belong in some kind of attributes, perhaps of parts.

**Comment by Jegelewicz** [comment]
> I can't dispute "track" as a common name of Grallator, but that also necessitates at least two ways of finding tracks - one for taxa that are defined as tracks, and one for taxa that aren't. Ideally I'd be just be able to find all tracks, however they (and/or the thing that allegedly made them) might be classified. That's making me think those data also belong in some kind of attributes, perhaps of parts.

"Repichnia" as a part name would include all tracks, but I have been thinking about your statement along with my notes in #2363. As with people names, parts can have multiple terms which mean the same thing. This would be a big shift, but could we treat the part name table the way we do agents in that part names could include a list of synonymous terms? Mariel and I recently had a discussion with Jorrit from GloBi and I think he makes the best argument for not trying to decide on "the vocabulary to rule them all" but instead to create the appropriate relationships among vocabulary terms so that stuff can be found. This is definitely a post PG idea to tackle, but I think we should tackle it.

**Comment by Jegelewicz** [comment]
> Ichnotaxonomy and "Linnean" taxonomy are separate and should not be confounded. I certainly don't see a problem with mixing them up however best reflects the situation in identifications.

I agree, so how should we handle ichnotaxonomy? I propose that we just add to the ichnotaxa types to the CTTAXON_TERM code table which would separate ichnotaxa from Linnean taxa. Other ideas?

**Comment by Jegelewicz** [comment]
> The ethologic and toponomic terms might make decent specimen attributes, but I'm not sure I've got my head wrapped around that yet either.

I will stick with my assessment: ethologic terms are part names and toponomic terms are part preservation attributes.

**Comment by dustymc** [comment]
>parts can have multiple terms 

Quick, find all the hearts in Arctos. You can't - they're 'heart' but also contained in 'whole organism' (sometimes) and 'tissue' (sometimes) and .... We've played with that a bit over the years, mostly just finding stuff that doesn't work. I'm not sure I see any silver bullets in linking parts, but anything that gets us closer seems deserving of consideration. I think this needs a dedicated issue.

Somewhat like paleo, the distinction between parts and identifications gets fuzzy with cultural items. This could turn into one of those neat "community" things where finding a robust solution involves getting an ethnologist and a ichnologist in the same room. That might be an easier conversation to have after https://github.com/ArctosDB/arctos/issues/2057.

>add to the ichnotaxa types to the CTTAXON_TERM code table

That will cascade down to CSV-based tools, but the idea of CSV-ing (and un-CSV-ing) complex data has always been a little tenuous. I think this is correct, but I'm not sure how usable it will turn out to be, at least in the context of some current tools.

We could also just declare that taxon_status=ichnotaxon term ranks are implicitly prepended with 'ichno' or something - not (explicitly) correct, but I don't think it would have any usability fallout either.

**Comment by Jegelewicz** [comment]
> We could also just declare that taxon_status=ichnotaxon term ranks are implicitly prepended with 'ichno' or something - not (explicitly) correct, but I don't think it would have any usability fallout either.

The only issue I see with that are ranks like "Ichnocohort" which have no equivalent in Linnean ranks.

**Comment by Jegelewicz** [comment]
Useful resource: http://www.ichnology.ku.edu/poi/poi/glossary.html
Also, for names/descriptions: http://www.ichnology.ku.edu/tracefossils.html

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
The attached pdf article is the best, most recent summary of trace fossil taxonomy that I can find.

[Chapter2.pdf](https://github.com/ArctosDB/data-migration/files/3924185/Chapter2.pdf)

Based on this, I propose the following:

1.  The categories of trace fossils listed on table two be added as parts. These are not taxonomy, however they are formal terms used to describe kinds of trace fossils. They are not common names.

track - a single imprint made by the appendages of an animal on the surface of the substrate

trail - a continuous trace made on the surface of a substrate

burrow - a continuous trace made within a substrate

boring - an excavation produced by an organism in a hardground

coprolite - (already added)

gastrolith - (already added)

regurgitalith - the fossilized remains of stomach contents that have been regurgitated by an animal

nest - (already added)

web - a thin, silken material spun by spiders and the larvae of some insects

cocoon - the silky envelope spun by the larvae of many insects, as silkworms, serving as a covering while they are in the pupal stage

case - a protective covering made by caddisfly larvae from organic or inorganic detritus

predation mark - a mark on an organism created by the predation of another organism. Includes bite and gnaw marks.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
2. Systematic classifications, ichnogenus, ichnospecies, and ichnofamily if one has been designated, be added without any higher classification.

3. Phylogenetic classification (the taxon of the animal that created the trace) be added as a second identification using the A and B string (perhaps with a remark). (@Jegelewicz for our stuff, for now, we would just add what is currently in the taxonomy field and fix later.)

4. Perhaps we could add ethological classification into the taxonomy as unranked terms and put them as a 3rd ID. Not ideal, since it would not be an 'accepted' ID. Another option is putting it as a unranked clade above the systematic classification. I don't like this option because we're mixing two classification systems. A third option is to add it as a part attribute. Any other ideas? It is good to figure this out ahead of time, but honestly our database doesn't include a lot of ethological classifications.

5. Any others types of trace fossil classifications would probably fit best under part attributes.

**Comment by Jegelewicz** [comment]
> Systematic classifications, including ichnogenus, ichnospecies, and ichnofamily if one has been designated, be added to the taxonomy without any higher classification.

@Nicole-Ridgwell-NMMNHS should these be given the rank ichnogenus and ichnospecies or can we just use the standard genus and species?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
If we can add the ranks ichnogenus, ichnospecies, and ichnofamily that would be ideal. It would also make it really obvious when the ichnotaxonomy and the zoological taxonomy have been mixed.

**Comment by aklompma** [comment]
For ichnotaxonomy, only genera and species names are used, not higher level classifications (family and up).

**Comment by dustymc** [comment]
>For ichnotaxonomy, only genera and species names are used, not higher level classifications (family and up).

Suggest these are moved to a new Source (if they must be managed locally, if not https://github.com/ArctosDB/arctos/issues/3311)

**Comment by Jegelewicz** [comment]
Great minds! I was just thinking this last week. Arctos Ichnotaxa?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Agreed, I've been wanting to do this for awhile. I think grabbing everything in order Ichnites + everything that has ichnogenus/ichnospecies should get most things, not counting the many that don't have any classifications.

I don't think #3311 will work for these, no one does ichnotaxa very well.

**Comment by Jegelewicz** [comment]
Just put it on my to do list.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
One thing we need to consider when we move ichnotaxonomy to a new source is where do we include the non-ichno part of the classification? Take Batrachichnus as an example, which is an Amphibian track. Here is it's current classification:
![image](https://user-images.githubusercontent.com/47402809/117506746-55acf500-af43-11eb-9715-0b5ec5914ee1.png)
with the Batrachichnus ichnogenus subset under Amphibia.

I think we should continue to subset the ichnotaxonomy under the non-ichno taxonomy rather than using an A and B formula for several reasons.
1) Using an A and B formula requires the data entry user to go look up every time "what type of animal made this track"
2) The A and B formula doesn't translate well to GBIF, GBIF can only read A. For example:
![image](https://user-images.githubusercontent.com/47402809/117507876-e7693200-af44-11eb-97f8-1640f338e79e.png)
3) A lot of our track specimens already have 2+ IDs because there are multiple track types on a single slab. That's pretty common for track collections. Sure, that could be fixed by giving each track its own catalog number, but they are already published in journals that way and I'm not going back and re-cataloging everything because I don't have time or curator support.

**Comment by dustymc** [comment]
From my viewpoint: I don't/can't care, classifications are yours, do with them what you will. It's probably worth noting "...with assumed higher taxonomy..." or similar in the source description (someone else might want to avoid that), otherwise, this seems fine/useful to me. (And if everyone except you thought it was evil, you could still do it - its easy enough for everyone else to just not use whatever they don't like.)

**Comment by Jegelewicz** [comment]
I have no problem with non-ichno higher classifications for ichno stuff. No need for A and B.

**Comment by aklompma** [comment]
Thank for reminding me about this one @Jegelewicz!

Having described some new ichnotaxa, my ideal would be to get rid of the higher classification altogether because this is an interpretation (and can be wrong sometimes) and is essentially mixing of two classification systems (organisms and traces they leave behind/create). Accurate (so nearly all) scientific literature on this will not report Chordata as a phylum for the track _Cincosaurus_. The scientific literature will just list: 
ichnogenus _Cincosaurus_
ichnospecies _Cincosaurus cobbi_

**Comment by Jegelewicz** [comment]
Well, this means that we have a bit of a stalemate. @Nicole-Ridgwell-NMMNHS says leave higher classifications and @aklompma says don't. Do we need a meet-up?

**Comment by dustymc** [comment]
>stalemate

We are not limited to one Source - https://github.com/ArctosDB/arctos/issues/2394#issuecomment-834792952

**Comment by Jegelewicz** [comment]
Yep - but before we make more, let's make sure we need to!

**Comment by dustymc** [comment]
>need to

Yes! This does seem like something where we should require some commitment before adding code table values, lest we end up with 564 mostly-empty Sources serving only to make setting up collections unnecessarily difficult.

**Comment by aklompma** [comment]
Yeah, let's discuss it more whenever works. This statement by Rindsberg (2012) in the chapter cited above may also be useful: "it is far preferable to maintain a higher classification of vertebrate trace fossils than to shoehorn them into the classification of tracemakers."

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I'm definitely open to discussion on whether or not to include the higher taxonomy, and I definitely know there are others in the paleo community that share your opinion. My concern is that if it is a separate classification every single time someone enters a new specimen, that data entry person (be it curator or undergrad) will have to interpret who made this trace. Or they just won't enter the separate higher classification and then nobody will be able to find, for example, all the the arthropod traces. 

@aklompma you might be interested in attending the August 26 Paleo Digitization Happy Hour which will be a discussion of trace fossil issues. I think we should wait to make any decisions until after this discussion as I really want to get more than just our opinions on issues like this.

**Comment by dustymc** [comment]
> interpret who made this trace

That sounds like an identification problem rather than a taxonomy problem (but I'd not be terribly surprised to find I just don't understand something, either).

* According to some agent(s), it's {some trace taxon}, and
* According to some (other, perhaps) agent(s), it's {some organism taxon}.

or 

* According to some agent(s), it's {some trace taxon}, and
* that's it
 
 or

* According to some agent(s), it's {some organism taxon}, and
* that's it

That might also be a nudge towards the idea that identification "acceptedness" is nonbinary - we might want to accept (or not reject, or something) both of the identifications. (I think there's an issue somewhere but I can't find it...)

**Comment by Jegelewicz** [comment]
Cool - you guys get back to me after the happy hour!

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I guess I shouldn't have used infer rather than interpret. I think in most cases a trace fossil gets ID'd as trace fossil taxon and then based on previous research it is inferred to be in a certain higher classification. For example, if I'm given a box ID'd as Ophiomorpha, I will assume based on the literature that they're crustacean burrows. That might not always be the case though. Maybe I find a shrimp fossil in one of the burrows and so I know based on that that these burrows were made by this species of shrimp. Then it would make sense to add a separate classification.

**Comment by Jegelewicz** [comment]
I am going to close this as a duplicate of #3579
