### ISSUE TITLE
Part quantity qualifiers (exact, calculated, estimated)?

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#2466]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**

In entomology collections there are vials and jars of specimens that when databased the quantity of specimens inside are often estimated. In UAM Insects we try to indicated 'estimated count' in the remarks of the part. However, in some cases we calculate the count using a subsampling method (eg spread contents evenly over a gridded petri dish & count everything in 10% of the grids, get an average per grid & multiply to estimate the total), and in other cases we do an exact count. 

**Describe the solution you'd like**

It would nice to have a field associated with the part lot quantity field that indicates how the count was obtained: exact, calculated, or estimated. Also, it would be best if during data entry that if a quantity is entered (which is required I believe) then the method of estimation is also required - that is, one can't enter a record with a null value for how the quantity was obtained.

**Describe alternatives you've considered**

Using the remarks field. 

**Additional context**

**Priority**
Please assign a priority-label. Medium

**Comment by Jegelewicz** [comment]
I've started to think that each of the fields we associate with parts (condition, disposition, count) just need to be attributes.

**Comment by campmlc** [comment]
Yes, I agree - part attributes. But we need to re-think the way that part
attributes display. I don't want to change the way we see the existing
parts, except to add a preservation field before condition. These
fields,however, would pull data from part attributes.

**Comment by campmlc** [comment]
And we should have the option to expand each part to see the entirety of
part attributes, or have a pop up window with that info, so the specimen
record does not become even more impossibly cluttered.

**Comment by dustymc** [comment]
>attributes

I don't wholly disagree, but that would have significant impacts on the model.

>a preservation field

The assumption that there's _***A***_ *anything* in a parent-child relationship is the core of the change; that model allows zero or more of any of these.

* Are we OK with having NULL part lot count (condition, whatever), and how would a user interpret that?
* Are we OK with having 784 counts on the same part, all the same or not, and how would a user interpret that?
* Are we OK with NULL method on part lot count(s), or some of them?
* Etc.

I'm not sure any of that's a showstopper, but it's worth thinking about before we let it in.

The idea that one attribute controls what a part's useful for also needs dispelled. Given

* great
* perfect
* soaked in bleach
* lovely
* very tissue-like

you're going to be eg, getting tissue loan requests for things that aren't suitable for DNA (because "the preservation" just says "great"). I'm not really suggesting we display all of that all the time, but if we're going to record complex data in a complex way we're also going to have to SOMEHOW find a way to convey that complexity to users.

>display

What you're asking for directly conflicts with previous requests (which may or may not be up for discussion - I think it was the former UAM:Mamm collection manager??). It's an easy change, but I don't think it's an acceptable one for some users, and I don't even know how to discuss that anymore. There's an easy solution - robust APIs and roll-yer-own UIs on top of them....

**Comment by dustymc** [comment]
An alternative to "attributes for everything" would be a single "estimated count" or "lot count qualification" or whatever attribute. 

Tabling; reopen as a CT request if any of that is satisfactory, or for discussion if more is needed.
