### ISSUE TITLE
Access to UAM:Art collection?

### ISSUE THREAD

**Issue by marecaguthrie** [ArctosDB/arctos#2484]
Can you help me with why @Jegelewicz isn't able to see the UAM:Art collection?
I have invited her and have removed all of the previous encumbrances that I know of. 
My preference is to wait to make UAM:Art publicly accessible until we have our ducks a little more in a row (See issue #2478 Planning for Art Collections in Arctos) but it would be great to be able to invite people to view it in the meantime. I'm not sure I understand why it isn't visible for people I give access to.

**Comment by marecaguthrie** [comment]
Oops- to clarify- I want to keep the encumbrances that @krgomez created on Value, Specimen/catalog remarks, and Part attribute location.

**Comment by dustymc** [comment]
@Jegelewicz where are you trying to go and what's it look like?

**Comment by Jegelewicz** [comment]
See #2362 I wanted to play with the options for them so they can visualize how the information might look as both taxonomy and attributes so that they can make a more informed decision about how it should be structured. I would set up one term as taxonomy and as an attribute. Nothing crazy - just an example.

**Comment by dustymc** [comment]
I need URLs and screenshots. In general, you'll see collections you have access to when you're logged in, and records which aren't encumbered when you're not.

**Comment by Jegelewicz** [comment]
I'm thinking this is no longer an issue. Closing.
