### ISSUE TITLE
Sorting on Part Attribute Type

### ISSUE THREAD

**Issue by mbprondzinski** [ArctosDB/arctos#2490]
I need to sort on the part attribute type "location" value.  Right now, the field contains both the part and the storage location, so it sorts on the part name, not the location value.  Can the two be in separate fields?  Thanks!

![image](https://user-images.githubusercontent.com/43214224/74164033-d4a06a00-4be8-11ea-8b97-0323b18a248c.png)

Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**

** Describe what you're trying to accomplish** 
An clear and concise overview of the goals; why are you asking for this?

**Describe the solution you'd like**
How might we accomplish your goals?

**Describe alternatives you've considered**

**Additional context**

**Priority**
Please assign a priority-label.

**Comment by dustymc** [comment]
The issue template - https://github.com/ArctosDB/arctos/issues/new?assignees=&labels=&template=feature_request.md&title= - contains the questions to which I need answers in order to help.

What I think I'm seeing in your screenshot is an attempt to extract a bit of data from a bunch of "fields" and I think it would lose any meaning if it was further reduced to just the attribute 'location' (of some arbitrary part, I suppose??). Technically it's easy enough to change if the community can reach some consensus, but I'm no longer sure how we do that.

https://github.com/ArctosDB/arctos/issues/2346

**Comment by mbprondzinski** [comment]
The problem is that I need to go through these cited specimens by drawer to check on the number of parts per record, which is proving to be highly inaccurate.   I then can change the number while we are going through the drawer directly in Arctos.  It saves me time and aggravation.

**Comment by dustymc** [comment]
Is it practical to slap a barcode on and scan it into the part while you're counting? That would HUGELY simplify this sort of thing (and a bunch of other stuff) going forward. Part attributes can, at absolute best, serve as "object tracking lite." 

One of the "other stuff" is that with barcodes you could easily bulkload the counts back into the catalog records.

I can probably help you with SQL to pull out whatever you want, particularly if I can anchor off of citations, but I'd need details to know for sure.
