### ISSUE TITLE
Clone Locality WITH Geology Attributes

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2496]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
When I clone a locality, the clone contains NONE of the geology attributes from the original and I have to re-enter all of the geology attributes if I want them in the clone.

** Describe what you're trying to accomplish** 
I would like to be able to clone a locality along with its geology attributes to create a new locality. Currently I have a "public" locality with geology attributes that I clone to set up "private" locality. The new locality will have additional attributes, but will also include all of the public geology attributes.

**Describe the solution you'd like**
An option to "clone with geology attributes"

**Describe alternatives you've considered**
Enter all the geology attributes twice.

**Additional context**

**Priority**
Please assign a priority-label.

**Comment by dustymc** [comment]
Done in PG

**Comment by Jegelewicz** [comment]
That probably isn't going to help me as I am doing this right now and expect it to be ongoing for the next several months...

**Comment by dustymc** [comment]
Would you like to suggest procedures then? This is "I know how to do it," "high priority," and doesn't require any structural changes, which is what I'm looking for lately, but there's nothing else I can do so it's just annoying. I more or less get the idea that you don't want to accept things you can't test (or even if you'd want to wait for 'tested in production' to fully close), but I need SOMETHING I can use to filter this thing into another pile, and then perhaps something so that pile doesn't just hang around until it's impossible to deal with.

https://github.com/ArctosDB/arctos/issues/2346

Help!

**Comment by Jegelewicz** [comment]
Maybe we aren't speaking the same language? I just mean that it is awesome to have this working in PG, but I could really use it NOW in actual, functioning Arctos. See [pending documetnation](https://github.com/ArctosDB/data-migration/blob/master/NMMNH/NMMNH_New_Locality.markdown). If this is not at all possible, then close the issue and I will just have to enter all of these geology attributes twice until PG.
