### ISSUE TITLE
New media relationship - documents locality

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2522]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Goal**
I just added [this media](http://arctos.database.museum/media/10607236) and it brings up a paleo issue. Paleontologists carefully track and document localities which are cited by identifiers in publications. I would like to be able to associate descriptive publications with the named locality.

**Context**
The referenced publications do not "show" the locality, but they do often describe it in detail and give a history as on page 85 of [this publication](https://play.google.com/books/reader?id=9bch7CTEzaoC&hl=en&pg=GBS.PA85). As this pub also demonstrates, specimens are not cited directly, just [the locality UTEP 32](http://arctos.database.museum/SpecimenResults.cfm?locality_id=10749931)!

I have considered associating this media with collecting events, but it is a bit uncertain which event(s) would be appropriate. In this case, all events took place before the publication, so I could associate the media with all of those events... @mvzhuang what are your thoughts? It could also be used to develop a loan based upon species cited in the pub - but it would be guessing.

**Table**
http://arctos.database.museum/info/ctDocumentation.cfm?table=CTMEDIA_RELATIONSHIP

**Value**
documents locality

**Definition**
Media which documents a named locality or all/most specimens from a named locality.

**Priority**
Please assign a priority-label.

**Comment by dustymc** [comment]
I hate it for all the reasons in https://github.com/ArctosDB/arctos/issues/1608 - it's not documenting the locality tomorrow, and there's no way to deal with that if the Media is attached to a timeless data object. Best case, you're tossing out information. Worst case, specimens collected tomorrow look like they're something they're not.

I want to suggest you just make a new "super event" that spans the necessary time and we'll do magic from that, but the tiny little experiments in that (displaying media with some temporal flexibility) mostly seem to confuse and anger people.

**Comment by Jegelewicz** [comment]
Yeah, I hear you. Let me cogitate and we can experiment.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I'd like to get something worked out for this. I have a long list of locality citations in publications that our volunteers have helped put together, plus a few in this latest batch of locality data I'm entering, and I need a way to enter them.

I'm concerned that attaching the citations to some super collecting event will make them difficult to find. If I pull up the record for a particular locality, I won't be able to see those citations (and if a particular locality has a lot of collecting events, it will be difficult to sort through those and find just the ones with linked publications). Maybe that is just a UI fix?

**Comment by Jegelewicz** [comment]
OK, so I took a little time to think about this. Not that I found an answer, but I did start to wonder about what constitutes an event and where we need them.

Isn't any publication or image an event? They describe what someone did to something and where IF the metadata is there.

A publication has a date and an author(s), so why create another event to repeat that documentation? If a publication cites this locality: https://arctos.database.museum/place.cfm?action=detail&locality_id=11031877

Then the date of publication is the timestamp and the author(s) is the determiner.

And even though we are [trying to get rid of it](https://github.com/ArctosDB/arctos/issues/1608), aren't images the same way?

In the media metadata there is date created and created by. Those two are the date and determiner.

> Maybe that is just a UI fix?
Maybe this is correct and instead of just plopping media or citations into a locality, we should make use of the dates and determiners already available to list them as citation and imaging events.

**Comment by dustymc** [comment]
>super collecting event 

I was suggesting that only as a proxy for a locality - if you know more then you should use more appropriate Events.

Yes I think it's a "just UI" problem. I don't see how adding Media with a time component (wasn't published tomorrow!) to an object without can be correct. It certainly can't be the only possibility, and we've thoroughly explored that flavor of denormalization in the other issue. I think all of the "why's this here?" complaints involve the intersection of low-precision data, which you don't have. Maybe someone will tell me what I'm missing....

Lacking objections, suggest linking Media to the most appropriate collecting event, retrieving them for display with the locality/other Events under the locality (as we do now, just needs spread around).

@Jegelewicz those data don't necessarily have anything to do with each other - it's a publication pulled from 100 year old field notes, an image created from a 100 year old image, etc., etc., etc.

**Comment by Jegelewicz** [comment]
> those data don't necessarily have anything to do with each other - it's a publication pulled from 100 year old field notes, an image created from a 100 year old image, etc., etc., etc.

In Nicole's case, these are publications that cite the site (say that 10 times real fast) number. They are talking about THAT place at the time of the publication. If she wants to find all pubs citing that site number - how best to do that?

**Comment by dustymc** [comment]
>find all pubs citing that site number - how best to do that?

Define "citing."

**Comment by Jegelewicz** [comment]
The publication says Site NMMNH:Paleo:L-3

**Comment by dustymc** [comment]
Thx.

The "correct" answer is to crawl over the publication-->media-->collecting_event-->locality relationship and pull various things from various nodes into - something. Pulling all Media into the locality detail page is easy enough for now, but I'm not sure that 100% gets at your needs. Developing that further would require some discussion, I don't really foresee any problems but I'd expect it to take some time too.

The "cheat" would be to add that locality name to the media via https://arctos.database.museum/info/ctDocumentation.cfm?table=ctmedia_label&field=media%20identifier or something like it. It's denormalization and therefore evil, but it might make things easier anyway....

**Comment by Jegelewicz** [comment]
/remind me to think on this tomorrow

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> Pulling all Media into the locality detail page is easy enough for now, but I'm not sure that 100% gets at your needs.

Definitely a step in the right direction I think. Now it seems like the next step is to be able to link a publication directly to a collecting event? I realize I can chain publication -->media-->event, but creating media for a publication with a DOI seems redundant.

I also think @Jegelewicz 's idea

> citation and imaging events

deserves some thought

**Comment by Jegelewicz** [comment]
> I realize I can chain publication -->media-->event, but creating media for a publication with a DOI seems redundant.

It is.

Suggest that we create a citation for locality in the same we have them for identifications.

**Comment by dustymc** [comment]
>seems redundant

So is driving around the block instead of cutting through a yard, but that's where the roads are!

I'm certainly willing to consider whatever comes along, but I'm not yet understanding the use case for building a new road here.

**Comment by Jegelewicz** [comment]
This publication:

![image](https://user-images.githubusercontent.com/5725767/100906357-56b69380-3486-11eb-9533-b17a1aaa811b.png)

Would include a citation:
[1 cited locality](https://arctos.database.museum/place.cfm?action=detail&locality_id=10749931)

And this locality

![image](https://user-images.githubusercontent.com/5725767/100906850-dcd2da00-3486-11eb-921a-4c0721d6ea06.png)

Would include a link to the publication:
referred to in [Van Devender and Worthington 1977](https://arctos.database.museum/publication/10007992), page 85

**Comment by dustymc** [comment]
I need to understand WHY, not WHAT. Citations are complex data objects because citations are complex linkages between publications and physical material. I am not seeing that sort of relationship between localities and publications. That might mean it's not there, or it might mean I'm just not yet seeing it.

**Comment by Jegelewicz** [comment]
Why?

![image](https://user-images.githubusercontent.com/5725767/100909273-b95d5e80-3489-11eb-94a3-71238d2713ad.png)

**Comment by Jegelewicz** [comment]
Note that there are several identifiers applied to this locality....

**Comment by dustymc** [comment]
That still looks like the sort of information Media are designed to carry; "these things are linked."

>several identifiers applied

Same as always, no problem (yay locality attributes).

>to this locality

That's part of what I'm not quite understanding. In a specimen citation, you'd (ideally) find "we looked at ABC:XYZ:123's skull and found 2 eyeballs" and you can go find that exact THING and count the eyeballs - you KNOW you're talking about the same THING, unless someone's completely failed to do their job. In this case we say "within 675 m of 31.8873680000 / -108.4524610000 between 1660=1660 m" (I fixed the = typo) while they say "....

<img width="650" alt="Screen Shot 2020-12-02 at 9 39 49 AM" src="https://user-images.githubusercontent.com/5720791/100910107-5d430c00-3482-11eb-9de2-28c4f95196f0.png">

... as we found it sometime before 18 October 1974" and I'm 100% sure I'm understanding the relationship between those things. Are we attempting to say something beyond "these are related" and if so, what is it and why does it matter?

**Comment by Jegelewicz** [comment]
> "we looked at ABC:XYZ:123's skull and found 2 eyeballs" and you can go find that exact THING and count the eyeballs - you KNOW you're talking about the same THING

Assuming that thing is still found in the collection, or someone hasn't written the catalog number incorrectly, or any number of other reasons you cannot KNOW.

> why does it matter?

Archaeological and Paleontological sites are important to those that work with them. People return to them over and over again and give them identifiers so that they can cite them in publications. Sometimes, it isn't what is collected from the site, but information about the site itself that is of interest. The publication has a date and authors and so, for me, constitutes an event related to the cited locality.  I would think this could come into play for research plots as well. 

I still don't see how creating fake media (sure this pub is available as a url, but not all of them are) in order to link a publication with a place makes a lot of sense. I also don't see how linking this pub with an existing event would work. The publication doesn't include "collecting" and if an event is not tied to some object record, won't it eventually be deleted?

**Comment by dustymc** [comment]
>Assuming

Yes, and we have a bunch of complexity to describe those things when we do know. Do we need that here, or is a simple link (and some semi-structured metadata) enough?

I was aiming more at "sites" - they seem much more abstract than the things that normally get cited, and that might be important in organizing data.

>event related to the cited locality.

Yes but kinda no, for the same reasons as above. It's certainly an event, but Events have a bunch more complexity behind them because it's necessary. Do we need that here - is there something that demands more than the universal link mechanism provides?

>fake media 

Hu?

>event is not tied to some object record,

Same "Hu?" as above. Does the top of https://handbook.arctosdb.org/documentation/media.html clarify anything? Media exists for the sole purpose of tying things, including but not limited to data objects in Arctos, to data objects in Arctos.

>publication doesn't include "collecting"

Yea neither do many other things that use the table - naming things is hard, but the functionality remains.

**Comment by dustymc** [comment]
Here's another angle; maybe I'm starting to understand what you're saying. (Or not!)

This (and a bunch of other stuff in Arctos) is about linking two data objects. For specialized links that need predictable data of their own, we create dedicated linking data objects. Identifications (including Citations, sorta) are the link between cataloged items and taxonomy, and exist because there's a complex relationship between cataloged items and taxonomy, and because Arctos users want to demand some minimal and predictable metadata in there (which is easy with NOT NULL columns, but not with additional data objects which may or may not exist). 

The link itself is precisely the same data object relationship that Media would establish, but Media would have difficulty in things like ordering identifiers or referencing multiple taxa. We could probably figure it out, but it would be a lot of work and likely require some nonstandard (=fragile) code. We might end up with "17th identified by agent" or something equally horrid as a media relationship, and making sure that one gets used only after "16th" and only once per identification would rely on that probably-fragile code.

Identifications do nothing that Media cannot do, but they do it more elegantly.

For "these objects are related (and maybe we'll provide some details, but no promises)" type situations, Media is a completely sufficient - along with very flexible and future-proof - mechanism. Designing and building a dedicated link table, and then rebuilding the UI around it, gains nothing.

If this requires the structure of something like Identification, then I'm going to have to understand those requirements before I can build a model capable of expressing them.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Dusty, I don't think I understand what you are saying.

Here is what a locality citation does:
There is a rocky hillside that produces a lot of fossils. Paleontologists/geologist dig the fossils out, but they also take observations and measurements of the rock and rock layers. 1 foot of shale, 5 feet of sandstone, etc. Those rock layers are physical things that don't change. Even if someone comes and bulldozes the site, they were still there and they still mean something. From that rock data the paleontologists/geologists draw conclusions like "these layers correlate with this other section we measured that dates to about 80 million years ago" and "the size of the rock grains and the ripple patterns indicate this used to be a beach (and the fossil critters we collected here died on the beach)" Others may dispute those observations, they come to us, get information about the site, and go back to site, retake measurements (maybe the others measured incorrectly) and draw their own conclusions. These sites are scientific data just like the specimens we collect from them.

**Comment by Jegelewicz** [comment]
Thanks @Nicole-Ridgwell-NMMNHS 

@dustymc I just caught on to the way you are suggesting we use "media" - I think. I would create media with the url of the publication, then add the relationship to the locality in that media?

Also, for my UTEP example, I added the relationship to the cited locality and I have a few comments.

1. What am I seeing here? This is what popped up when I selected "shows locality". I assume these are all the exact same locality, and that this is because there are this many events associated with the locality, but the duplication is confusing. Am I really creating a relationship to the locality or am I creating a relationship to one of the events?

2. When I go to the media details, I see the link to the locality
![image](https://user-images.githubusercontent.com/5725767/100929849-7c06ca00-34a5-11eb-849c-9ca5b0a9bdd1.png)

but when I select it, I get:
![image](https://user-images.githubusercontent.com/5725767/100929939-9c368900-34a5-11eb-88ac-33f5155f4a62.png)

 Nothing...I assume because the default search is by event and the media IS actually associated with the locality.

3. When I visit the locality detail page, there is no indication that any media (and therefore a link to the publication) exists.
![image](https://user-images.githubusercontent.com/5725767/100930197-f9cad580-34a5-11eb-8167-7b0060ebfd41.png)

**Comment by dustymc** [comment]
>understand

Ditto, but I think maybe we're getting there!

Those folks planning a trip might want to know what the place is like now. Locality is incapable of doing that; "there was a walmart parking lot but it's all gone and now this cool stuff is exposed" and "this cool stuff was there but now it's under the walmart and they get all excited when you start digging" are not distinguishable. (OK, they probably are - to humans, IF a bunch of secondary data exists and can be interpreted. We should aim higher than that!)

Events do have a time component and so are capable of ordering those states.

Nothing can be lost by linking to events. Not everything can be saved if linking to locality.

You'll always know something of the time component - minimally, that publication you're linking today wasn't published tomorrow.

I understand that the primary object of interest is the place, but I can see nothing lost, and potentially much gained, by going through events.

All that said, I don't think this part of the conversation is completely critical. If we hook these directly to the localities and then decide to un-do that in a few years, just those few years of precision would be lost (eg, by making events which stop at NOW() and linking to them then). I still don't think that's correct, but it's easy enough to get in and out of. That would require maintaining two paths to locality, which isn't ideal but (sorta) still exists because https://github.com/ArctosDB/arctos/issues/1608 is stuck.

**Comment by dustymc** [comment]
>What am I seeing here? 

Needed work: https://github.com/ArctosDB/arctos/issues/3099

>Am I really creating a relationship to the locality or am I creating a relationship to one of the events?

https://handbook.arctosdb.org/documentation/media.html#media-relationship

>when I select it, I get:

https://github.com/ArctosDB/arctos/issues/3260

>visit the locality detail page, there is no indication that any media 

 #1608 - it's not in the UI because I can see no reason for the relationships to exist!

Media linked to events are now in that view.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I'm ok with adding publications to collecting events, what I'm still confused on is why I have to double my workload by adding a redundant media record to every publication record to create that link.

**Comment by dustymc** [comment]
I may have just somehow popped out of the tunnel I think I've been looking through...

I've been fixated on Media because that's in the title and what's used in the examples. Now I'm thinking maybe I'm looking at this from the wrong place; media (if they exist) are attributes of the (table) Publication, which you want to link to the Collecting_Event. So without going into details

1. https://arctos.database.museum/publication/10007992 links to eg https://arctos.database.museum/place.cfm?action=detail&collecting_event_id=10924512 (not THAT Event, but AN Event) and 
2. https://arctos.database.museum/media/10607236 is just a convenient way to get to the content represented by the Publication record, if someone happens to have a PDF laying around and feels like uploading it. Media are irrelevant to the core of this issue.

Am I close?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> media (if they exist) are attributes of the (table) Publication, which you want to link to the Collecting_Event

Yes, exactly. And I want to be able to see collecting event publications when I view a locality record.

**Comment by dustymc** [comment]
Awesomeness.

The elegant solution is to allow FKEY as a "datatype" in event attributes, but I don't know how to do that. If I don't have any immediate revelations, which doesn't seem overly likely, suggest we add a simple link table

```
collecting_event_publication_id PKEY
collecting_event_id FKEY-->collecting_event
publication_id FKEY-->publication
```
and then we can figure out the best way(s) to get it to the interface(s).

Objections?

**Comment by Jegelewicz** [comment]
> The elegant solution is to allow FKEY as a "datatype" in event attributes

YAAAAASSSSSS

>  simple link table

Not exactly sure I get that set-up, but your definition "simple link table" sounds good....

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Sound good to me.

**Comment by dustymc** [comment]
In next release, example at http://test.arctos.database.museum/place.cfm?action=detail&collecting_event_id=11139008

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Thanks Dusty!
