### ISSUE TITLE
New Media label type - citation

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2529]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Goal**
I would like users of my media to be able to easily cite it.

**Context**
I can add the citation as a remark, but I think a labeled field would be more effective. See http://arctos.database.museum/media/10607321

**Table**
http://arctos.database.museum/info/ctDocumentation.cfm?table=CTMEDIA_LABEL

**Value**
citation

**Definition**
When referring to this media, or information within it, use this text.

**Priority**
Please assign a priority-label.

**Comment by dustymc** [comment]
Other than the introduction of one more label that all sort of look the same from here, I don't think theres a technical reason not to do this.

I would recommend just using "description" - that's what's most prominently displayed with the Media.

For a citation that can DO STUFF, you can click this:

<img width="188" alt="Screen Shot 2020-02-27 at 8 02 45 AM" src="https://user-images.githubusercontent.com/5720791/75461436-a4223500-5937-11ea-98c9-3e1f688422af.png">

**Comment by krgomez** [comment]
Is there a way to make it so that we can predict what will display below the media thumbnail? I’m pretty sure I have noticed that comment labels will sometimes display if there is not a description label. The description label is where we have recorded the copyright notice (© artist or artist's estate) so that it displays below the image for clarity to users. We also record the notice as a remark in the copyright status attribute.

I was recently thinking along the same lines as Teresa is here and pondering how it might be nice having such a designated media field for copyright/information aggregated for users to cite. If that were the case we would prefer that be the “tombstone” or label that's displayed (artist, title, year created, medium, dimensions, catalog number, repository, credit line, copyright notice). I personally like what the Brooklyn Museum does to aggregate a work's tombstone information for display with the media:

![Screen Shot 2020-02-27 at 8 04 00 AM](https://user-images.githubusercontent.com/40579515/75492540-76071a00-5964-11ea-97ae-66ee341de8a3.png)

**Comment by Jegelewicz** [comment]
Can we use html in the description label to format the "tombstone"? (I love that term!)

**Comment by dustymc** [comment]
>predict what will display 

Add a single 'description' label - otherwise Arctos will try to round something up.

This may be something for which we need API guidelines or requirements - https://github.com/ArctosDB/internal/issues/51

>designated media field for copyright/information aggregated 

That's https://github.com/ArctosDB/arctos/issues/2450, no?

>use html 

That's used for ALT tags, where I suspect it'd melt something. The forms won't stop you though...

**Comment by krgomez** [comment]
How long does it take for a new description (updated or newly added) to display on the catalog record? I added a new description for an image on 2/24 and it is still displaying the old one.

**Comment by Jegelewicz** [comment]
Mine have updated almost immediately. Can you give me a link to the image?

**Comment by krgomez** [comment]
![Screen Shot 2020-03-04 at 9 20 51 AM](https://user-images.githubusercontent.com/40579515/75910020-9cf89c80-5df9-11ea-8e35-a5f2c6971456.png)

![Screen Shot 2020-03-04 at 9 21 07 AM](https://user-images.githubusercontent.com/40579515/75910036-a2ee7d80-5df9-11ea-87d4-9a2c2008a996.png)

I was testing what it would look like to have the tombstone text display below media.

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/2813
