### ISSUE TITLE
How to enter an EH object in the single record data entry?

### ISSUE THREAD

**Issue by mbprondzinski** [ArctosDB/arctos#2532]
I can't find any information on this.  Can someone please help?  Thanks.

**Comment by Jegelewicz** [comment]
@mbprondzinski it is no different than entering a biological record except in the identification where the A {string} formula will be used. If you would like, we can set up a call and go through one of y'all's records together.

**Comment by mbprondzinski** [comment]
That might help.  I tried using the A {string} but it wouldn’t accept it.  I figure I must be doing something wrong when it comes to artifacts!

**Comment by Jegelewicz** [comment]
What were you trying to enter using the A {string}?

**Comment by mbprondzinski** [comment]
It was a Mask, Washkuk, from the indigenous people of the Sepik River, New Guinea.

**Comment by Jegelewicz** [comment]
In the ID section select "build"
![image](https://user-images.githubusercontent.com/5725767/75717818-1c1d9180-5c8f-11ea-8cc1-88b39249ef50.png)

In the pop-up, select "A {string}" and complete the form like this

![image](https://user-images.githubusercontent.com/5725767/75718108-9cdc8d80-5c8f-11ea-800f-ebc4eeb25326.png)

Then select "Save To Form"

you will now have this:

![image](https://user-images.githubusercontent.com/5725767/75718184-bc73b600-5c8f-11ea-9b34-dba38995edaf.png)

Note: you may want to add the culture of origin and perhaps the culture of use as attributes using https://arctos.database.museum/info/ctDocumentation.cfm?table=CTATTRIBUTE_TYPE

but that will also require adding the appropriate culture to the code table https://arctos.database.museum/info/ctDocumentation.cfm?table=CTCULTURE

Let me know if this helps or if we need to chat.

**Comment by mbprondzinski** [comment]
Okay, I will try that.  I didn’t know I needed to add “unidentifiable.”  Can I add cultures to the code table or does that require special permissions?

**Comment by Jegelewicz** [comment]
> Can I add cultures to the code table or does that require special permissions?

Code table access requires special permissions. If you send me the term you want and a link to wikipedia, I can add them for you. You can browse the cultures already there in the [Culture Code Table](ttps://arctos.database.museum/info/ctDocumentation.cfm?table=CTCULTURE)

The example you have might be difficult because it could include a bunch of cultures - see https://en.wikipedia.org/wiki/Sepik#Peoples_and_languages

In this case maybe just use what is already in the code table:

> Papuan - Indigenous people of New Guinea and neighboring islands; see also http://en.wikipedia.org/wiki/Papuan_people

**Comment by mbprondzinski** [comment]
So this worked fine, but for some reason, I got this:
![image](https://user-images.githubusercontent.com/43214224/75819972-27d98880-5d61-11ea-9eb0-1917cf0d33d0.png)

I don't know how to get rid of the ES: or the full description.  I tried renaming it, "Mask, Waskuk", but the entire phrase is still there.  Any ideas on how to fix this?  Thanks!

**Comment by Jegelewicz** [comment]
ALMNH:ES: is your default search ID. This is set in your profile:

![image](https://user-images.githubusercontent.com/5725767/75827354-aab11200-5d66-11ea-9079-65118f3bd06e.png)

It only looks that way for you! For me it looks like

![image](https://user-images.githubusercontent.com/5725767/75827384-c5838680-5d66-11ea-8b6d-f106011f06a0.png)

because my default is collector number.

**Comment by Jegelewicz** [comment]
> or the full description. I tried renaming it, "Mask, Waskuk", but the entire phrase is still there.

It appears as "Mask, Waskuk" now - IDs take a little bit to change in the interface. Ususally if you check back an hour later the change is complete.

**Comment by Jegelewicz** [comment]
Nice!

**Comment by mbprondzinski** [comment]
Okay, I see now!  Thank you, Teresa!  I'll change my default to something more generic.
