### ISSUE TITLE
Common names - link to language

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2536]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**

** Describe what you're trying to accomplish** 
Common names are associated with languages. It would be good to let users know which language a common name is associated with.

**Describe the solution you'd like**
Use https://glottolog.org and associate the language ID with the common name.

**Describe alternatives you've considered**

**Additional context**

**Priority**
Please assign a priority-label.

**Comment by dustymc** [comment]
This would be a paradigm shift; common names currently exist in Arctos as finding aids. http://handbook.arctosdb.org/documentation/taxonomy.html#common-names

>Common Names are added to the taxon record as classification metadata.

That is just wrong. 

What precisely are we trying to ACCOMPLISH with this; what's the point, and who's the audience? (It's hard to tell if it's capable of doing whatever's needed without some knowledge of what that is.)

There are currently 301241 common names. Nobody's realistically going to add a language to them. That complicates things a bit.

What precisely does "associate the language ID" mean? Are we trying to link to https://glottolog.org/resource/languoid/id/amer1254 instead of spelling "American Spanish," or as a reference or reinforcement, or do we also want to find the Spanish name by searching Latin (eg, by traversing the language hierarchy).

Glottolog doesn't seem to include the language my family speaks. What's the workflow around that?

All real questions, but I think my initial response to yesterday's conversation would be

1. Media-link eg http://arctos.database.museum/name/Canna%20tuerckheimii to http://demca.sites.gettysburg.edu/taxa/index.php?taxon=Canna+tuerckheimii&formsubmit=Search+Terms
2. Snarf this

<img width="135" alt="Screen Shot 2020-03-05 at 7 06 12 AM" src="https://user-images.githubusercontent.com/5720791/75994435-d4c21b80-5eaf-11ea-96a6-350369f75c6d.png">

into common name.

From there, 

1. users can find stuff by searching "li:ma'hchí:n" 
2. doing more stuff with the pretty UI (or the data behind it, if that's accessible) from anywhere the name gets used is technically trivial

That also includes some pretty huge assumptions of course; I'm not the audience and can't really speak for whomever they might be.

**Comment by Jegelewicz** [comment]
closing for lack of interest

**Comment by mkoo** [comment]
Not really for lack of interest but lack of current bandwidth. this is important stuff but not currently something we're built to handle-- like Dusty said it requires a paradigm shift. And I would expand on this concept of common names to regional taxonomy. Can we transfer to internal repo as it will probably require new partners and extramural funding?
