### ISSUE TITLE
Calcareous Algae

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#2538]
**Goal**
We have fossil specimens, not yet entered into Arctos, identified as calcareous algae. I'm trying to figure out the best way to enter this so that someone could search somewhere for calcareous algae and come up with a result. The taxonomic ID is just phylum Chlorophyta.

**Context**
The simplest thing would be to put calcareous in remarks, but since calcareous algae is such a big group, spanning both modern and fossil taxa, I'd prefer not to just drop this info in an open text field. I'm thinking an attribute could maybe be used, but I'm not sure what that attribute would be. Maybe biomineralization?

**Collection type**
ES, Paleo, Herb

Does anyone else have calcareous algae in Arctos? I couldn't find any. I'm hoping someone familiar with modern calcareous algae groups could weigh in.

**Comment by Jegelewicz** [comment]
I found this https://www.sciencedirect.com/science/article/pii/B9780444826725500076 which says:

> The calcareous algae comprise an artificial group that cuts across both taxonomic and disciplinary boundaries.

This is strangely akin to @mbprondzinski 's sharks but adding the common name "calcareous algae" to every possible taxon in the group is much more difficult (IMO). 

See also: https://www.majordifferences.com/2013/02/difference-between-natural-and.html#.XmGVfkplCUk

How about a new attribute:

artificial classification =  group to which the organism belongs based upon non-evolutionary features (e.g. the grouping together of plants according to the number and situation of their stamens, styles, and stigmas rather than their evolutionary relationships)

**Comment by dustymc** [comment]
>identified as calcareous algae

The "A {string}" identification formula was made for that.

**Comment by Jegelewicz** [comment]
> 
>     identified as calcareous algae
> 
> The "A {string}" identification formula was made for that.

That's all fine and dandy for this case, but if the algae is identified to species, no one will want to do that!

**Comment by dustymc** [comment]
``Somesorta algae {Somesorta algae (calcareous)}``

A {string} can deal with any level of specificity; it's capable of conveying all of the precision in any taxon, plus whatever's in the identification, with any form of "identified as *something that's not quite taxonomy*."

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I'm ok using A{string}, but my concern is that it is an uncontrolled data field and calcareous algae are a pretty common group of organisms. So at some point when there are a lot of calcareous algae in Arctos, it will be difficult to find them because one person will enter "calcareous algae", another "calcaraous algae", another "calcareous green algae".

I'm not sure I have a good solution though, because even if we introduce a new attribute will it even be used for things that are already identified to genus/species level?

**Comment by dustymc** [comment]
If those are identifications, then they're all potentially "correct." As long as they tie into taxonomy they can still be found.

This was presented as though "calcareous" is part of the identification. If that's not the case - if it's just a part attribute - then an A identification to whatever the most precise taxa is might be better.

Also https://arctos.database.museum/name/Algae exists but I'm not sure it should - looks like all modern classifications avoid it, but I can't immediately determine if it was considered "taxonomy" at some point or not.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
The issue is that calcareous algae isn't a cohesive group. We have fossil specimens of calcareous algae that can't be identified to a precise taxon. The most precise taxon is phylum Chlorophyta, which includes everything from unicellular algae to seaweed to pond scum. The calcareous part is an important part of the identification. Functionally, they are a group that people study and thus important to be able to search by.

**Comment by Jegelewicz** [comment]
AKA an unranked clade

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
not even a clade really since calcareous algae are polyphyletic.

**Comment by dustymc** [comment]
>unranked clade

I'm not 100% sure, but I don't think it's that - "word informally used for barely-related sorta-planty stuff" maybe!

**Comment by Jegelewicz** [comment]
Nicole has a very valid point about the A string and the potential for people to misspell and thus make discoverability poor.

For me, if identifications are meant to represent taxonomy (at least in the biological world), this term just isn't identification except as a remark, which leads to the same lack of discoverability but seems the best place for it. For taxa that are actually ALL calcareous algae, this could be a common name and work great. I just don't have an answer......maybe an attribute?

**Comment by dustymc** [comment]
>A string and the potential for people to misspell

Yes, that's why the other formulae exist. Unfortunately for this it looks like its informal enough to be pushed towards A {string}.

It's far from ideal, but some sort of 'A String IDs created in in the last {timespan}' report is possible.

>identifications are meant to represent taxonomy

Only loosely; the formal separation exists for just this case, there there is no formal (and useful) representation of the best identification, Arctos can accommodate.

(Or https://github.com/ArctosDB/arctos/issues/2499 might make it possible to introduce some sort of formalized "paleotaxonomy" if such a thing exists....)

The "calcareous" bit certainly came from a part - it's a physical description. In very general terms, does "Algae" in/near identification and "calcareous" somewhere in part-land solve this, or are you looking for the term "Calcareous Algae" somewhere?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> "Algae" in/near identification and "calcareous" somewhere in part-land solve this

Yes, I think it would.

**Comment by Jegelewicz** [comment]
So, I have added the common names "algae" and "green algae" to Chlorophyta, then what would the part name be? Would "calcareous" be part of the part name or a part name modification (condition or preservation?)

Then, how do we get people to understand that finding "calcareous algae" means a search for common name "algae", part name "whatever we pick" and part condition "calcareous"?

**Comment by Jegelewicz** [comment]
@Nicole-Ridgwell-NMMNHS what are your thoughts on this?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I'm still concerned about discoverability, but I'm not convinced anymore that an attribute is the solution to that. I'll just use A string for now.

**Comment by mbprondzinski** [comment]
Are you still looking for someone to "weigh in" on this thread?  We have an algae expert here at the U of A.  Don't know if he would be useful or not!

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Yes, it would be very helpful!

**Comment by mbprondzinski** [comment]
I'm sorry to report that we have been given the brush.  The algae "expert" said he did not understand what was wanted, and did not bother to look at the GitHub thread.  Judging from his Facebook posts, I believe he aspires to the arts these days rather than to algae (!)  I have to admit, I was rather surprised by his disinterest.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Ah well, it was worth a shot!
