### ISSUE TITLE
isGeoreferenced=false is looking for "has an ungeoreferenced locality" NOT "has at least one georeferenced locality."

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2571]
I suggest that "is Georeferenced" = false should look for a georeferenced locality in the event stack. The way it is now forces loss of information if we have to merge events to get a locality off the "needs georeferencing" list.

**Comment by Jegelewicz** [comment]
Actually, I've been thinking about this and what we really need are more nuanced ways to find what needs georeferencing. For example, in the NMMNH Paleo collection, there are two events for each specimen, one public and one private. The public events all have locality only to county and they are georeferenced, but the private events have all of the locality components included and most of these are NOT georeferenced, but of course, we would like them to be. In our case, we would be looking for all localities with geology attribute access=private that don't have coordinates.

**Comment by anna-chinn** [comment]
I've thinking about this a little bit recently, as well. Having greater locality-facing search capabilities would be really useful at CHAS. Being able to [search for localities](http://arctos.database.museum/Locality.cfm?action=findLO) given particular collection, specimen, or specimen event data would allow us coordinate our georeferencing projects at the locality level, which is something I feel is important for interdisciplinary collections management (e.g. return all localities without coordinates related to CHAS specimens where specimen event verification status !=unaccepted; return all localities related to NMMNH specimens where access = private).

Because all of our localities have been migrated/georeferenced/modified so sporadically over the last 5 years, we have a ton of duplication that could probably be rectified. Having the ability to return localities with more specificity would help us find and merge duplicates, as well.

**Comment by dustymc** [comment]
>more nuanced

Yea I was intending to have a close look before giving up, but that's my initial impression as well.

>CHAS

Are those comments strictly in relationship to localities, or localities-via-specimens? Eg http://test.arctos.database.museum/Locality.cfm?action=findLO or http://test.arctos.database.museum/SpecimenSearch.cfm (or both)?

**Comment by anna-chinn** [comment]
Maybe both? Whether it's from the specimen search page or from the locality search page, I'd like to get at a list of localities based on specimen event data _and_ locality data. The current tools available from the search search results page aren't quite precise enough. Tools in this menu return events/localities related to ALL specimen events for specimens in the query, when what I'd like is a list of events/localities related to a specific kind of specimen event: <img width="977" alt="Screen Shot 2020-04-01 at 12 25 51 PM" src="https://user-images.githubusercontent.com/40321380/78161784-fd3c2780-7413-11ea-8f23-bf24d26a9e2e.png">
