### ISSUE TITLE
Dinosauria

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2589]
Currently in Arctos the classification for Dinosauria places the term as an order, I am not sure this is correct and want to start a discussion about the term and how we should be using it in Arctos.

PBDB places Dinosauria in an unranked clade between class Reptilia and various unranked clades and families such as family Dictyoolithidae.

@Nicole-Ridgwell-NMMNHS and I discussed this briefly and my initial thought was that Dinosauria should be changed to a rank of superorder and that term added to all classifications that belong in "Dinosauria" to facilitate the use of that term in searching. But I am hesitant to change the rank of a term that is in use by others without some documentation or community agreement and I am not qualified to determine the list of taxa that will need to have their classifications modified.

Thoughts, ideas and suggestions are welcome.

@aklompma @dperriguey @mbprondzinski @acdoll

**Comment by dustymc** [comment]
>added to all classifications that belong in "Dinosauria" 

Are you intending to include Aves?

PBDB also places eg Mammalia in Osteichthyes - https://github.com/ArctosDB/arctos/issues/1641#issuecomment-477822649 - I suppose it's correct, but it's not very useful for people trying to find fish either.

If this is as far-reaching as I think you're suggesting, it should probably go through the newsletter pathway. I suspect attempts to embrace cladistics are going to require a new Source, but who knows.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I don't think we are considering Aves right now. We would just be re-ranking Dinosauria as a superorder and placing the two orders Saurischia and Ornithischia within Dinosauria.

See [Dinosaur classification - Benton classification](https://en.wikipedia.org/wiki/Dinosaur_classification#Benton_classification)

**Comment by Jegelewicz** [comment]
No matter what - inconsistencies will inevitably creep in and newly added classifications will be missing the super order. I don't really see a good way to handle this as someone may disagree with the Benton Classification (if it is like any other taxonomic tree in the world...).

**Comment by dustymc** [comment]
>inconsistencies will inevitably creep in

Not if you manage classifications in a tool where they're not possible!

>someone may disagree

That's why Arctos provides for multiple classifications.

**Comment by Jegelewicz** [comment]
> PBDB also places eg Mammalia in Osteichthyes

If it has a backbone - it's a fish.

> Not if you manage classifications in a tool where they're not possible!

That tool isn't Arctos. Don't propose the hierarchical tool - inconsistencies can be created there too unless you manage the entire tree (see "mammals are fish" and "birds are dinosaurs").

For consideration: https://www.wikidata.org/wiki/Q430

**Comment by Jegelewicz** [comment]
Also, who knew that the Getty AAT puts taxa in the "Agents" facet?

https://www.getty.edu/vow/AATFullDisplay?find=&logic=AND&note=&subjectid=300250126

**Comment by dustymc** [comment]
>If it has a backbone - it's a fish.

I want a t-shirt.

>inconsistencies can be created there too unless you manage the entire tree

That's just a matter of perception. A hierarchy can't possible be anything except "the entire tree" - if you're not managing that then you're managing multiple hierarchies, and there's no reason to expect consistency across resources.

I'm not recommending any tools - I keep hoping taxonworks or something like it will meet some need and we can simplify/eliminate Arctos tools, which exist ONLY because I couldn't find anything better.

>Getty AAT puts taxa in the "Agents" facet

Oh my!

**Comment by mbprondzinski** [comment]
Lions, and tigers and bears?!

**Comment by Jegelewicz** [comment]
> 
> 
>     If it has a backbone - it's a fish.
> 
> I want a t-shirt.

I'm on it.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
What is the status of this? Can we get Dinosauria changed to superorder? Can someone tag whoever else we need feedback from?

**Comment by Jegelewicz** [comment]
@aklompma

**Comment by acdoll** [comment]
I have no current objection to assigning Dinosauria as a superorder. I'm with @dustymc that hopefully we can shift this burden onto an external authority sometime in the near future. I'd really love to see the paleo and modern bio trees more appropriately integrated.

**Comment by aklompma** [comment]
Dinosaur paleontologists have refrained from using any Linnean taxonomy in pretty much any of their recent papers. Making Dinosauria a superorder in Arctos would be rather strange and confusing to some. Is there a way to avoid using Linnean taxonomy for this specific case or alternatively just call it clade?

**Comment by dustymc** [comment]
>avoid using Linnean taxonomy

Yes and no. The Arctos model is built in anticipation of this and NULL "rank" is fine.

BUT there are a bunch of tools that flatten taxonomy out to spreadsheet-like formats, and having a column (or 50!) named NULL isn't so fine in that environment.

None of that matters if we're just pulling from external sources....

**Comment by aklompma** [comment]
Ok, I am not in favor of making Dinosauria a superorder because an alternative may work in Arctos, it is incorrect scientifically, and scientists who use Arctos would not get a good impression.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
From the handbook "unranked terms may make it difficult for users to find your specimens."

My main concern with finding specimens is this: if Dinosauria is entered as an unranked clade and someone searches for Dinosauria, will the search come back with the ranked orders Ornithischia and Saurischia.

Honestly I still don't fully grasp how taxonomy works in Arctos.

**Comment by dustymc** [comment]
> if Dinosauria is entered as an unranked clade and someone searches for Dinosauria, will the search come back with specimens under the ranked orders Ornithischia and Saurischia?

http://test.arctos.database.museum/name/Ornithischia#Arctos

<img width="415" alt="Screen Shot 2020-05-19 at 1 32 32 PM" src="https://user-images.githubusercontent.com/5720791/82375302-3c7b0380-99d5-11ea-9b19-8ef83b094919.png">

<img width="325" alt="Screen Shot 2020-05-19 at 1 32 58 PM" src="https://user-images.githubusercontent.com/5720791/82375329-469d0200-99d5-11ea-9cdf-daa81806a3eb.png">


Note the lack of "various unranked terms scattered around in various places" option(s) here:

<img width="645" alt="Screen Shot 2020-05-19 at 1 34 06 PM" src="https://user-images.githubusercontent.com/5720791/82375470-7e0bae80-99d5-11ea-9f19-27054027c3bb.png">

which I believe is where the "unranked terms may make it difficult for users to find your specimens." thing came from. That's "just" a UI problem, but it's one for which I don't have a great solution.

>don't fully grasp how taxonomy works in Arctos.

The important thing to understand here is that the Arctos model is built to deal with anything that anyone ever thought was taxonomy, which is very much NOT hierarchical. Adding Dinosauria to http://test.arctos.database.museum/name/Ornithischia affects that "name" and nothing else - it doesn't propagate to children and such.

The hierarchical tool DOES deal with children, but also includes an export/import as text step so doesn't deal with things that won't fit in a spreadsheet; it can't handle unranked clades.

Webservices don't have that problem, so the easy solution here is to just pull from https://paleobiodb.org/classic/checkTaxonInfo?taxon_no=91973&is_real_user=1 or something like it - which leads to things like https://github.com/ArctosDB/arctos/issues/1641#issuecomment-477822649

That's only a problem because that request was to dump those data into an existing (huge and bloated) classification, which would make things very inconsistent. Importing it into a new classification would not be a problem.

That one's actually already in Arctos via GlobalNames - http://test.arctos.database.museum/name/Ornithischia#ThePaleobiologyDatabase - even if the "null, but let's say something anyway" "ranks" are a little weird.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> Adding Dinosauria to http://test.arctos.database.museum/name/Ornithischia affects that "name" and nothing else - it doesn't propagate to children and such.

So just changing Dinosauria to unranked doesn't do much because we'd have to go through every dinosaur taxon and change the classification to include Dinosauria?

> Webservices don't have that problem, so the easy solution here is to just pull from https://paleobiodb.org/classic/checkTaxonInfo?taxon_no=91973&is_real_user=1 or something like it 

So are you talking about cloning this into the Arctos source?

>That one's actually already in Arctos via GlobalNames - http://test.arctos.database.museum/name/Ornithischia#ThePaleobiologyDatabase - even if the "null, but let's say something anyway" "ranks" are a little weird.

But wouldn't we have to either switch our taxonomy source or clone that into the Arctos source to use it? There is some part of this here I am not understanding.

**Comment by Jegelewicz** [comment]
> So just changing Dinosauria to unranked doesn't do much because we'd have to go through every dinosaur taxon and change the classification to include Dinosauria?

Yes, but we would have to do that even if it was ranked. We have ways of doing this in bulk, but someone would need to build the file. And as soon as we are done, there is nothing stopping anyone from adding a new genus without the unranked or Superorder term.

> But wouldn't we have to either switch our taxonomy source or clone that into the Arctos source to use it? There is some part of this here I am not understanding.

Yes - you could create a new taxonomy source - PBDB (via Arctos) and you could switch to it. This means you would need to maintain the source yourself (unless someone decides to use it too). Also, unlike WoRMS, I don't think there is a direct way for us to update from PBDB on a schedule. So very quickly, the taxonomy source would be out of step with PBDB.

@dustymc can correct me if any of this is wrong.

**Comment by dustymc** [comment]
>cloning this into the Arctos source?

That'd do it, but it wouldn't be my first choice; that thing is becoming about as bloated as it was the last time we were forced to do something radical.

>create a new taxonomy source - PBDB (via Arctos) 

* Best (for me!) - just use http://test.arctos.database.museum/name/Ornithischia#ThePaleobiologyDatabase (via globalnames)
* Close second: yes, new source, pull data from them to populate it (would take some development) They do have an API - https://paleobiodb.org/data1.2/ - so we could (maybe/probably, depending on the details) keep things current.

>have to go through every dinosaur taxon 

That's one reason I'd be looking for a less-bloated Source - that's one click in a hierarchy, and I would not want to try to pull Arctos into a hierarchy, even if you had tools that could deal with it.

The problem then would be getting it back to Arctos - we currently only have flat file tools, all of those "unranked clade" (properly NULL, I believe) terms don't make good CSV headers. We could easily build a loader for something other than a flat file, or services to talk to some taxonomy tools, or ....

**Comment by dustymc** [comment]
I think this can be closed, or pushed off to https://github.com/ArctosDB/arctos/issues/3311? @Nicole-Ridgwell-NMMNHS ?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> pushed off

Yes, I think it can. On piece I wasn't understanding when we were originally discussing this was that you can use the "any taxon, ID, common name" to search on unranked terms like this and it will use the global names sources, including PBDB, to find results. Knowing that allays many of my concerns about finding specimens in our collection by searching on unranked groups. Order Dinosauria is still incorrect, but it is not something that many people will see. And in fact, it seems to be used only by 8 taxon, so I could just go and change those 8 to unranked. If no one has a concern with that I will.

**Comment by Jegelewicz** [comment]
@Nicole-Ridgwell-NMMNHS I say go ahead.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Done
