### ISSUE TITLE
Classification Bulkloader - load more than one metadata term type

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2592]
When bulkloading classifications, it would be helpful if we could load multiple metadata types for any given classification. The most use I would have for this is in paleo where many of our classifications have TAXON_STATUS = valid and TAXON_STATUS = extinct, however I have also added more than one SOURCE_AUTHORITY to a classification. As we are able to add multiple instances of a given metadata type when creating a classification manually, it seems like we should be able to do the same in the bulkloader.

**Comment by dustymc** [comment]
>it seems like we should be able to do the same in the bulkloader.

Bulkloaders use CSV, which by user preference is flat. That's not a suitable data model for most anything in Arctos, so there are limitations or some flavor of weirdness. Two "columns" named taxon_status isn't possible. taxon_status_1 and taxon_status_2 is, but then things get wide and people complain about that (and what about taxon_status_54?!?). Structured data instead of strings would work, but that also causes complaints. Shifting the loader to vertical would work, but that causes yet more complaints.

This might be evidence that one of those things isn't "taxon status" (but I'm not so sure of that).

The bulkloader also fails to deal with unranked classification terms.

A general solution that we could apply to various loaders - an Arctos Standard of sorts - would be very useful.

**Comment by Jegelewicz** [comment]
>  taxon_status_1 and taxon_status_2

Would work just fine for me - I'm used to it in a lot of other bulkloaders.

**Comment by sharpphyl** [comment]
It seems odd to me that the species status (extinct or extant) is mixed in with the taxon status of valid or invalid.  Maybe we should have a separate field for whether it's extinct or not.

**Comment by dustymc** [comment]
>extinct or extant

It seems weird to me that this is a thing. Does someone really run out and flip the flag when we decide chronospecies are way cooler than paleospecies, or vice-versa, again? How's ANY of that work without taxon concepts? Has anyone used these data in some useful way?

**Comment by sharpphyl** [comment]
In our case, we're often documenting when the collector/dealer label says "fossil" and/or WoRMS applies their fossil flag † to the species.  WoRMS definition: "Anything before 10,000 BC is considered fossil."   Also, there are usually geological terms in a fossil locality and we distinguish between the date of collection and the date of deposition.  

I don't know how researchers may use this data but I'd like to continue to capture it in our records.

**Comment by Jegelewicz** [comment]
> we distinguish between the date of collection and the date of deposition

Oh man - this blows my mind and makes me wonder about how we are handling chronostratigraphy. Maybe instead of the geology attribute what we really should be doing is adding an event type = "deposition" where verbatim date is stuff like "Norian" and began and ended dates are 227 Ma and 208.5 Ma (of course it would be even better to have those dates auto populate from a chronostratigraphy table so they could be updated when the terms get a tweak from the ICS.

**Comment by sharpphyl** [comment]
I'm totally out of my league on your question.  We probably have only a hundred or so fossils in or waiting to get into our database so our experience is limited.

We just fill in the collection date - like September 1963 - and then make a comment that it is the date of collection and not deposition.  Of course, that should be obvious with the geologic information and the "extinct" status, but sometimes the aggregators don't capture all the data in their summary tables so the comment is a bit of insurance.

**Comment by campmlc** [comment]
This comment from an external user may be relevant:

  Since I am mostly looking at NM records, my problems are mostly stemming
from the UTEP collection.  I tried searching for all collections except the
UTEP Arch collection but that does not seem to cull out many arch records
for modern mammals.  I will try using the “wild caught” option, but this
would also exclude modern animals found dead.  It would be nice if there
were a way to easily click  radiobutton for Modern Records (e.g.,  since
1482 or something like that).  Another problem I have noticed is that many
users of  ARCTOS are not realizing they are getting archaeological
records.  This is causing some wild distributions to be reported.  I have
not seen any published yet but have caught some in draft form.

**Comment by Jegelewicz** [comment]
> but this would also exclude modern animals found dead

That is an incorrect assumption and highlights the issues with the term "wild caught" no matter what definition we assign, people will have their own!

**Comment by dustymc** [comment]
>In our case, we're often documenting when the collector/dealer label says "fossil" and/or WoRMS applies their fossil flag † to the species. WoRMS definition: "Anything before 10,000 BC is considered fossil." Also, there are usually geological terms in a fossil locality and we distinguish between the date of collection and the date of deposition.

I still can't wrap my head around what this has to do with taxonomy. You are saying the clams in Site1 (dated 10.1KY) and the 100% identical in all aspects clams in Site2 (dated 9.9KY) by definition can't be the same species?!?!

>event type = "deposition"

"Death" probably makes more sense - and would work for "verbatim preservation date" as well - but yea, there's a lot of data all confounded up in various events.

**Comment by Jegelewicz** [comment]
> I still can't wrap my head around what this has to do with taxonomy. You are saying the clams in Site1 (dated 10.1KY) and the 100% identical in all aspects clams in Site2 (dated 9.9KY) by definition can't be the same species?!?!

Oh there are a few that can, but yeah - for the most part the identification probably gives it away. However, some people looking at the higher level classification may want to exclude "fossils" or the other way around, so there's that...

**Comment by sharpphyl** [comment]
Again, not high priority vs. getting the testing done.  Can delay discuss until then.

**Comment by dustymc** [comment]
Current loader does this.
