### ISSUE TITLE
Re-label "Collector" section of catalog record page

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2602]
The section of the catalog record page that displays agent roles associated with the object appears as follows:

![image](https://user-images.githubusercontent.com/5725767/79775907-27d21f80-82f2-11ea-8c16-930bb8e2610e.png)

The heading "Collector(s)" seems inappropriate given that there are collectors, preparators, makers, etc. listed here.

Potential headers:

**People**
**Agents**

others?

**Comment by dustymc** [comment]
This is vaguely related to https://github.com/ArctosDB/arctos/issues/1492

Those are definitely not people - they include agencies, groups, etc. They are also not some arbitrary list of Agents that had something or another to do with something, probably. They are collectors acting in various collector roles, which are listed; the structure doesn't allow any other interpretation.

I'm definitely up for a better term for that node (and the [definition of collector](http://test.arctos.database.museum/info/ctDocumentation.cfm?table=ctcollector_role&field=collector) leaves much to be desired), but just ignoring the structure seems like a fatal loss.

**Comment by ewommack** [comment]
I definitely would like to have a discussion on this. 
I can see the point that Collector(s) seems redundant or not helpful if you're looking for preparators and not sure where to look.

At the same time, what to replace it with is a big puzzle. Synonyms found online seem unhelpful:
archivist
aggregator
packrat

**Comment by Jegelewicz** [comment]
I vote for packrat!

**Comment by dustymc** [comment]
>Synonyms

It's "agent-acting-on-specimen-in-role" that we need a name for. "Collectors" now include things like copyrights holders and creators; I don't think there's any reason to retain any part of what increasingly looks like the legacy term "collector" in naming that.

Alternatively, for ~a few months (????) of development we could use this as an opportunity to get a little more event-based/@tucotuco -ish and change the relationship from 

```agent-in-role-->cataloged_item```

to

```agent-->specimen_event (which includes type)-->cataloged_item```

Which I think would effectively merge http://test.arctos.database.museum/info/ctDocumentation.cfm?table=ctcollector_role into http://test.arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_event_type. That is, the assertion would move from "agent acting in role on specimen" to "agent contributing to specimen_event of type."

That would much more clearly express things like "this was created by {agent} at {place}  on {date}" and "{agent} {whatever'd} this particular part of the cataloged item at {place}  on {date}", but it'd be a lot more complexity in things like adding a georeference, or perhaps even recording a preparator for initial data entry, which makes me think that's not quite the right model even if the idea turns out to be useful. (Maybe keeping the role so we can say "agent who prepared at event-type=collect" mitigates some of that??)
