### ISSUE TITLE
Create procedure - Arctos Operator no longer at institution

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2635]
Thanks Katie! Hopefully you can help change that....

And there's another procedure that needs formalized - what exactly should happen when an Arctos operator gets a new job in a different collection, and how's that interact with things like edit history? There's a tiny bit of info at http://handbook.arctosdb.org/documentation/users.html#maintenance-and-deletion

_Originally posted by @dustymc in https://github.com/ArctosDB/arctos/issues/2326#issuecomment-623611853_

**Comment by Jegelewicz** [comment]
See addition to How To - https://handbook.arctosdb.org/how_to/How-to-Create-your-Arctos-Team-Users-and-Operators.html#2-managing-operator-roles-and-permissions-for-exiting-team-members

**Comment by Jegelewicz** [comment]
@campmlc @dustymc @mkoo anything else to add/edits ?

**Comment by mkoo** [comment]
I would add after the first sentence:
```
When a member of your Arctos team leaves, DO NOT delete or alter the account or the user’s agent login name. 
Deleting agents will destroy their edit history and may have other unintended consequences. Instead,....
```
Thx!

**Comment by Jegelewicz** [comment]
Done

**Comment by Jegelewicz** [comment]
I think we are done here - no further comments about the documentation were made.

**Comment by campmlc** [comment]
Sorry, I missed this earlier, and I do have a question.
What is the procedure for a former operator who is subsequently hired at a different institution in Arctos? If we go the route described here, their former account would be unlocked, and they would then have access to all of the collections they had access to from their previous status as an operator in a different collection. Who is responsible for removing that access? How will the personnel at the previous institution know that a former operator now has restored access to their collection, in order to remove the access if necessary? 
Keeping the old account without removing the access seems to lead to potentially scary unauthorized access. I've certainly had this happen already with former graduate students who moved on to different collections in Arctos. They should no longer have access to MSB collections, but there is no procedure in place for notification or removal.

**Comment by Jegelewicz** [comment]
> What is the procedure for a former operator who is subsequently hired at a different institution in Arctos? If we go the route described here, their former account would be unlocked, and they would then have access to all of the collections they had access to from their previous status as an operator in a different collection. Who is responsible for removing that access? How will the personnel at the previous institution know that a former operator now has restored access to their collection, in order to remove the access if necessary?

I just did this with Katie (formerly UAM:ES, now at Burke). I emailed the contact I could find and informed them of the consequences of allowing Katie to have continued access to the UAM:ES collection. They failed to remove her access and she understands what is going on. I don't worry that she will edit things she shouldn't. See https://github.com/ArctosDB/new-collections/issues/583#issuecomment-1430292764

Unfortunately, this can happen to any person - ideally, the exit procedure should include instructions to remove access to the collections and if they are followed there wouldn't be a need to worry about reinstating anyone. They would still have access permissions, just not to any collections.

Is that an appropriate action @dustymc ?

**Comment by dustymc** [comment]
>exit procedure should include instructions to remove access to the collections 

Yes, there's a log (as of a couple years ago), it addresses all technical concerns. I don't think this is or can be an "Arctos problem," it's something the collections will need to sort out. (Arctos could of course provide guidance, and we should make sure any guidance does not include any pre-log concerns.)

**Comment by campmlc** [comment]
For collections that have lost a staff member, there may not be anyone at
the previous institution who understands or has the capability to remove
access once that person has left, and that may be why there is no response.
I think that there should be some way to flag that an individual no longer
should have curatorial access at a collection, and this should be part of
the decommissioning process when someone leaves Arctos.
We also don't have a good way to know whether to unlock someone's account -
a flag on their account that says they no longer have curatorial access to
certain collections would help with that.

**Comment by ewommack** [comment]
I agree with @Jegelewicz and @dustymc - the decision on whether a person does not have curatorial access is really up to the collection. We can provide guidance and instructions on how to take someone off a collection, but I don't think we should dictate if and when collections should remove people.

**Comment by dustymc** [comment]
>We also don't have a good way to know whether to unlock someone's account

That's easy: don't. If you have any question at all, do not. If they don't work for you, do not. Very nearly EVERY "hack" starts with this. If I wanted to make a big mess of Arctos, I would 100% start by asking a few folks to "unlock my account." (And on that note - maybe we're being way too liberal with access to the unlock button; perhaps that should involve 2 people or something??)

>the decision on whether a person does not have curatorial access is really up to the collection

Yes.

**Comment by campmlc** [comment]
What exactly breaks when operator access is removed? Because I have done
that for former students who have gone elsewhere. Locking their accounts
doesn't work when they are at other Arctos institutions. I have to remove
their MSB access.

**Comment by Jegelewicz** [comment]
> remove their MSB access.

is different from changing their role permissions

![image](https://user-images.githubusercontent.com/5725767/228086075-f521128e-7788-4558-90ef-a5cb182cef69.png)

Leave the "role"s alone, revoke access to your collections

Correct?

**Comment by Jegelewicz** [comment]
I do not have access to UAM:ES (and I don't know anyone but Patrick who does) so I cannot do this for Katie. She can do it herself if she wishes, but I am not going to tell her what to do at this point.

If people aren't monitoring who has access to their collections, I don't think it is up to us to do it for them unless it becomes a security issue for the community.

**Comment by campmlc** [comment]
The requirement that we never ever delete roles is what is most problematic
to me. If we have logs, surely we can see who did what when even if they no
longer have the role currently? Can't we have a log file showing when they
did have access, and when it was revoked?

Related to this is the ability to change an operators roles depending on
which collection they have access to. Maybe I'm the only one who has
students working with permissions across multiple collections in Arctos -
perhaps that will change as we bring in more tissue collections. But I have
students who work as a GA in the bird division one semester, where they are
given advanced permissions to manage and bulkload specimens in a single
collection.Then they come work for me, where they only need manage records
role, but they need that role for multiple collections. If I don't change
their previous permissions, they could end up with advanced permissions in
multiple divisions, because I can't separate the role from the collection
access.
I feel there must be a better way that would solve the problem I just
described plus the problem of operators leaving Arctos for other
institutions, where they would have different roles in different
collections.

**Comment by Jegelewicz** [comment]
This has been documented and there is no actionable request - other than a duplicate of #2636 so I am closing this.
