### ISSUE TITLE
Allow multiple users per Agent

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2636]
>KatherineLAnderson account is locked. Should I unlock and revoke access? @dustymc

Not unless you are her supervisor and are limiting her access to "your" collections.

That's probably another procedure we need to formalize. Unlocking accounts should be a very transparent process with absolutely no possibility of unlocking that user who was just very purposefully locked by a panicking Curator.

_Originally posted by @dustymc in https://github.com/ArctosDB/arctos/issues/2326#issuecomment-623597110_

**Comment by Jegelewicz** [comment]
See #2756

**Comment by dustymc** [comment]
http://handbook.arctosdb.org/documentation/users.html

**Comment by campmlc** [comment]
This should be at the top, not buried three pages down.
*DO NOT UNDER ANY CIRCUMSTANCES CREATE A NEW OPERATOR ACCOUNT FOR USERS WHO
HAVE EVER HAD AN OPERATOR ACCOUNT IN ARCTOS!*
*Also add*
*Do Not convert an operator account to a public account by removing
permissions.*

*But what about removing some but not all permissions on the same account
when an operator changes roles?*

**Comment by Jegelewicz** [comment]
> *But what about removing some but not all permissions on the same account when an operator changes roles?*

This - we have had several people switch institutions, we need to be able to keep up with all of what they do and where they were when they did it.

**Comment by campmlc** [comment]
I have students who work in DGR one semester and need Mammal and Bird
access, but later move to be Bird GA, and no longer need mammal access, so
I've removed their mammal access but let them keep their operator account
and their existing bird access. How should this be handled?

**Comment by dustymc** [comment]
>How should this be handled?

I don't think it's a problem altering roles as someone comes and goes, but having a non-Operator logged as having made updates would confuse me (and maybe the system).

Some of this can be pushed off to https://github.com/ArctosDB/arctos/issues/2550 - I'm not 100% sure HOW yet, but I'd like to do more with eg sending a user's error logs to the person who invited them, which might turn into a natural place to keep track of history - grabbing "personA [granted|revoked] {role} to/from personB" would do what I need, and a much better job of tracking previous access as well.

**Comment by dustymc** [comment]
Related: https://github.com/ArctosDB/arctos/issues/3509 - do we need to allow multiple users per Agent? We currently can't because https://github.com/ArctosDB/arctos/issues/579#issuecomment-134426534 assumes a 1:1 ratio.

I'll add a log of Operator changes - I don't think that's a complete solution but it's a start and should be useful for various reasons.

**Comment by dustymc** [comment]
log in next release - going back to needs discussion

**Comment by campmlc** [comment]
We could definitely use multiple users per agent, if this is possible.
Without it, people are already creating dummy accounts that can't be
tracked back to a single human. With it, we could track people's changing
roles and permissions.

**Comment by dustymc** [comment]
>creating dummy accounts that can't be tracked back to a single human

That's clearly contrary to the documentation - https://handbook.arctosdb.org/documentation/users.html - and my emphatic vote would be to delete those when they're discovered. (Which is of course a bunch of extra work, because it should have never happened in the first place.)

> track people's changing roles and permissions.

That's what I just added, and I'm not sure what it has to do with a person having multiple accounts. (It is structured to deal with that, should we decide to allow it for some reason.)

**Comment by campmlc** [comment]
it should have never happened in the first place
So my vote is to remove the incentive for people to do so by giving them
the tools they need to have different profiles/accounts attached to one
agent name. It is possible for a student to need only good student
access to a herp collection while needing full access to mammals. If they
had different accounts, they could be the same agent with different
permissions in different collections. Is that what you added?

**Comment by campmlc** [comment]
Here are two actual examples of the problem we need a solution for -
requiring different accounts for the same agent.
1) In DGR, students must have data entry, manage specimen and object
tracking access to all collections whose tissues are archived in the
division. This is MSB:Mamm, MSB:Bird, MSB:Herp, MSB:Fish, and MSB:Para. If
any of these students also works in a different division, e.g. MSB:Bird,
they may have been given additional permissions beyond this basic access -
e.g perhaps they bulkload specimens or help with loans in that division. If
so, then in the current scenario, they will have these advanced permissions
across all the collections they have access to in DGR. This is not
acceptable. They should be able to be given basic permissions for an
account that has access to multiple divisions, but advanced permissions
under a different login associated with the same agent name for a single
division.

2) MSB and NMMNHS have a collaboration where students and staff assist with
different curatorial projects across institutions. In order to give an
NMMNHS staff member access to an MSB division, e.g. for object tracking, we
currently have to allow them the same access privileges they have in their
home institution, e.g transactions and/or manage collection. Again,
unacceptable. We have managed a work-around by creating a "staff" agent
with limited permissions to work across institutions. However, that means
the actual agent doing the work does not get credit for the work they do,
and it functionally means that a single agent has multiple login accounts
with different permissions.

**Comment by dustymc** [comment]
@campmlc that's going to get buried here, it should be in another issue. It is (or may turn out to be) relevant to this - we might want different procedures under that model (or not, I don't know).

I don't think there are any technical problem with that, but it would require a fair bit of development, starting with un-doing the preferred name bits of https://github.com/ArctosDB/arctos/issues/579#issuecomment-134426534. (I don't think there are any non-technical problems either, but that's the The Community to decide.)

**Comment by campmlc** [comment]
OK, created issue #3586 .

**Comment by dustymc** [comment]
Procedure needs to include revoking access to collections (https://github.com/ArctosDB/arctos/issues/2767)

**Comment by dustymc** [comment]
>very difficult to know what actual things you are allowing someone to do
<img width="354" alt="Screen Shot 2021-10-07 at 9 50 56 AM" src="https://user-images.githubusercontent.com/5720791/136429405-66afb808-2010-496e-bbae-48d3b9fb7bd6.png">

<img width="663" alt="Screen Shot 2021-10-07 at 9 51 10 AM" src="https://user-images.githubusercontent.com/5720791/136429419-c2457eac-c980-4627-b0c6-a82adeed3e11.png">

> some collections managers would take offense!

The ones who were around for Versata and have seen that in action won't!

>that never seems to happen as expected.

I don't believe adding complexity will much help with that, although it may be necessary anyway.

**Comment by Jegelewicz** [comment]
I am pretty sure that collection managers do not peruse that before assigning roles. it is multiple clicks away and not visible as roles are being assigned unless you have a couple of tabs open.

In any case, I think this needs a real dedicated discussion group.

**Comment by campmlc** [comment]
Maybe we partition permissions into different roles? e.g. "good student role" automatically is assigned data entry,public, etc. and these are automatically checked once "good student" is selected. Or "Manage collection" role automatically assigns manage collection, data entry, transactions, etc etc.

**Comment by campmlc** [comment]
Then you could click one time per collection - "good student" role for Birds, "manage collection" for mammals, and there could be an "advanced" button to allow individual management of roles if something beyond standard needs to be added or removed.

**Comment by campmlc** [comment]
Reviving this - we have an associate curator with full curatorial access at one institution who wants to be able to view transaction info at our institution. The problem is that we don't have a "view only" option - can we make this possible? 
Also, this same person was formerly a student at MSB and is now an Arctos curator at NMMNHS, and has multiple logins but only one operator account. Allowing a second operator account to MSB with different permissions, including view only, would solve this problem.

**Comment by campmlc** [comment]
@jldunnum

**Comment by campmlc** [comment]
Just checking in on status of this one? The situations in which this is needed are multiplying, and in our current state we are giving full access to operators who only need view or student level editing access in some collections.

**Comment by mkoo** [comment]
I'm closing this issue as it has become stale and fragmented. If there is a need and use case, please separate out into a new feature request.
