### ISSUE TITLE
Higher Geography -  Indo-Pacific Ocean

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2642]
Does anyone have thoughts on an Indo-Pacific Ocean locality?

_Originally posted by @lin-fred in https://github.com/ArctosDB/data-migration/issues/80#issuecomment-624745110_

**Comment by dustymc** [comment]
http://arctos.database.museum/geography.cfm?geog_auth_rec_id=10003404

I can't see how anything else will do anything other than introduce inconsistencies. That could be mitigated by adding WKT and changing the ocean component of everything "in" that, but that's probably more than we want to bite off at the moment (and might introduce its own flavor of inconsistency).

**Comment by Jegelewicz** [comment]
I pretty much agree. Until we have a better way of dividing marine geography, I say go with Pacific Ocean and put "Indo-Pacific" in specific locality.

**Comment by lin-fred** [comment]
That's what I was figuring, thanks!

**Comment by mkoo** [comment]
agreed. and unless it has an authority we can point to then it's a Feature
like a Sea
we should discuss if we want to divide into  North Pacific and South
Pacific since the Equator nicely does that for us and wikipedia supports it

**Comment by mkoo** [comment]
exactly. belongs in specific locality for now

**Comment by dustymc** [comment]
>then it's a Feature like a Sea

And that's in Major Surgery territory - there's almost certainly reason to need "sub-feature" somewhere in there, and maybe "sub-sub-feature." We should back WAY up and talk about what we're trying to accomplish before getting that weird.

>divide into  North Pacific and South

http://arctos.database.museum/geography.cfm?geog_auth_rec_id=1147
http://arctos.database.museum/geography.cfm?geog_auth_rec_id=10006464

**Comment by mkoo** [comment]
as we've discussed before, Features dont belong in Higher Geography so my
point is that it doesnt need to sub-anything!

**Comment by sharpphyl** [comment]
There is a URL:  https://en.wikipedia.org/wiki/Indo-Pacific

It may depend on what specimens have the "Indo-Pacific" locality and how it may have been used.  There is a group of Malacological Provinces that include Indo-Pacific.  Most lists I see divide the oceans into 20 provinces but not necessarily the ones in this map.  We infrequently see these and other provinces used as locality in older labels.  Usually we just record it as the verbatim and specific locality and use "no higher geography."

![Malacological Provinces Map URL](https://user-images.githubusercontent.com/15368365/81298934-b8b73380-9032-11ea-9b40-0665b999e766.png)

Here's a slightly different list:

![Malacological Provinces list](https://user-images.githubusercontent.com/15368365/81301238-04b7a780-9036-11ea-8aaf-92a87720e7d8.jpeg)

We have a lot of specimens with nothing better than Indo-Pacific, and, while it's data, it's of limited value.  We could use Indo-Pacific Region (or Province) as a feature to have a consistent way to find them since it's a combination of the Indian Ocean and Pacific Ocean.  I would not divide it into North and South but the Wikipedia article gives three ways to divide the region.  I have never seen a specimen that used any of them.    

> I say go with Pacific Ocean and put "Indo-Pacific" in specific locality.

I'm sure we've done this too, but it's wrong.  Indo-Pacific is a region that combines both the Indian Ocean and the Pacific Ocean through the temperate zones.

Yes, we need to discuss marine geography and develop (or adopt) consistent structures to describe localities.

**Comment by dustymc** [comment]
>Features dont belong in Higher Geography 

@mkoo where's that document? I think that may have briefly made sense to me at one point....

>but it's wrong

For very personal reasons, I refuse to recognize the Indian Ocean. (OK fine I'll share: I just made that up. And I am 100% sure there are specimens in Arctos backed by crazier geographic ideas.) Without spatial data, it's difficult to call anything but the most ridiculous outliers "wrong."

>group of Malacological Provinces 

I'm not sure I could get into taxon-specific geographic descriptors, but some sort of organization backed up by spatial data would be most welcome. Gordon used to have some big blue marine descriptors book, possibly published by some navy, which would have been about perfect if there was a spatial component - surely something like that exists in digital form?

**Comment by sharpphyl** [comment]
> Gordon used to have some big blue marine descriptors book, possibly published by some navy, which would have been about perfect if there was a spatial component - surely something like that exists in digital form?

Any of these?
https://www.marineregions.org/
http://www.globalgisdata.com/10923.html
http://www.getty.edu/research/tools/vocabularies/tgn/index.html
