### ISSUE TITLE
Media Relationship=spatially defines geog_auth_rec

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#2664]
I LIKE this new one and will definitely fit into my future Arctos work, but Arctos seems quite unsure of itself:
```Something is broken. I have no idea what to do with a relationship to geog_auth_rec```

Please let Arctos figure out what to do with this so we can use it! Putting Priority since I assume it wont be time-consuming to fix... but change the label if wrong

**Comment by dustymc** [comment]
It's a little time consuming but manageable. The intended functionality works, there's just no "summary" of geography on the media record. Adding that as a map would also serve as a way to visualize the polygon.

Recommend considering this with https://github.com/ArctosDB/arctos/issues/2660 - I'm not 100% sure WKT will survive that process.

**Comment by mkoo** [comment]
doesnt matter if WKT survives, but it will make the move to a spatial database easier if we can find organized bits and pieces to plug into that postGIS space. if it's manageable but time consuming, can we prioritize for the PG Arctos? we've lived without it in production so really not a priority but I would suggest removing it (no need to tease!) 
let us know what you're going to do

**Comment by dustymc** [comment]
We started with WTK as CLOB. EVERYTHING struggles with properly handling CLOBs; they're a pain to work with. I moved all WKT to Media because it's really just text files, everyone knows how to work with those, and we already have a mechanism for handling them. BUT, since they're Media, they're discoverable as Media, and there's no "handler" to turn the ultra-normalized media relations into something visible on the page. I don't see this as any sort of problem; it's not clear what we're living without.

I can find the WKTs, just not from the media side of things. There are no organizational issues here, just an inability to go from media to geography, and I'm having a hard time seeing a use case in which that's needed.

The media relationship exists only to provide some clue as to why the Media exists.

I think I'm not understanding something fundamental about your concerns. Help?

**Comment by mkoo** [comment]
you're forgetting the non-Dusty user; we (ok, I am) have trouble finding these media/Geography relationships. Look, I do not love (at all) dealing with spatial info (wkt's or any format) in media. Right now, we are in the phase of adding to the pot but I will want to replace, delete, update these CLOBs so if I cant find/ understand why it's there then harder to do. Anyway, to the issue here. If this relationship is not functional, probably should be removed in production, eh?

**Comment by dustymc** [comment]
We can revisit the relationships post-Postgres; it's not changed recently.

Replace, update, delete work like all other Media relationships - remove the pointer to the media, or create a new media object and update the geography (and/or locality) to use it.

As part of https://github.com/ArctosDB/arctos/issues/2660 we should consider other ways of handling spatial data.
