### ISSUE TITLE
Consolidate edits to single-record taxon name/classification forms

### ISSUE THREAD

**Issue by anna-chinn** [ArctosDB/arctos#2695]
per #2682:

> Would you be willing to round all the single-record taxonomy form issues up in one place?

Taxonomy committee 2020-05-20: We'll start by mocking up our wish lists starting with the classification editing page.

**Comment by anna-chinn** [comment]
https://docs.google.com/document/d/1iUqEHZyPRtLvfbFBMXTQp554yYtSKJd1h995I4ehWR0/edit#

**Comment by sharpphyl** [comment]
Four documents with suggested revisions to some of the taxonomy pages have been uploaded to https://drive.google.com/drive/folders/1gQdI-qWCDFAe6yJSkWkUKlXLAX5KYwLp?usp=sharing

The pages address are the main Taxon Page, the Edit Taxonomy Page and the Edit Name + Related Data page.

We need the Taxonomy Committee to review, edit, and approve these before we move on to similar recommended changes to the remaining Taxonomy module.

**Comment by sharpphyl** [comment]
There are now six documents.  Teresa, the issues you raised #2682 isn't on any of these pages, so we probably need to add them next.

**Comment by sharpphyl** [comment]
We're up to 10 documents: https://drive.google.com/drive/folders/1gQdI-qWCDFAe6yJSkWkUKlXLAX5KYwLp?ths=true

**Comment by Jegelewicz** [comment]
@dustymc I got really crazy this afternoon with the taxonomy search results page. Please review before you pull to test. If it's OK, let me know once you have pulled because I want the taxonomy committee to review before we pull any triggers.

Let me know if I have done anything nuts-o.

**Comment by dustymc** [comment]
>before

I'm pretty much pulling constantly - it's there, and throwing errors

variable [TAXON_NAME_ID] doesn't exist

probably a scope problem - you might need ``#somequery.taxon_name_id#`` or similar.

**Comment by Jegelewicz** [comment]
UGH

Can I just revert back to the previous commit? I was pretty sure I hadn't touched anything that would affect the search screen, but apparently I was wrong. I should probably just do one thing at a time....

Sorry to be learning as I go  - I'm gonna screw up a lot.

**Comment by dustymc** [comment]
>revert

I think you figured that out?

>do one thing at a time

That's what I do. If I had a full "local" dev environment I might commit weekly or something, but I don't so I commit constantly.

>learning

yea me too!

**Comment by Jegelewicz** [comment]
Committee recommends

- [ ] Can we populate metadata for new classifications or cleaned classifications with the term types appropriate for the name type?
- [ ] After creating a new taxon name (without cloning), instead of going to top of taxon page, go to classification section and prompt to either clone or create a classification. Include a force refresh of Global names so that external sources are available to clone.
- [ ] Use the "Define" widget whenever possible remove code table links elsewhere
- [ ] Write a newsletter article and create a short tutorial for "Define" widget
- [ ] Make the "define" widget consistent throughout Arctos
- [ ] Ensure all taxonomy pages have a working page help link
- [ ] Stay on the same page - create a new name opens a new tab
- [ ] Field labels link to documentation

**Comment by Jegelewicz** [comment]
@dustymc I really would like an answer for this:

The last column in the classification says "original."  I tested what this is by adding a row (then deleting it) and it says "original" again.  Is there a reason for this column?  

<img width="953" alt="Screen Shot 2021-08-12 at 7 00 39 AM" src="https://user-images.githubusercontent.com/15368365/129201122-9e18e7a7-2946-4e9b-a548-93de15e001d8.png">

**Comment by dustymc** [comment]
It's a leftover from when we were trying to find consistency and can be removed.

**Comment by dustymc** [comment]
Form and rules have changed, I think this is no longer relevant.
