### ISSUE TITLE
abdomen - new part name for ento/ES collections

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#2714]
**Goal**
Catalog fossil material

**Context**
Fossil insects are not always preserved as whole organisms, often only one or two body section are preserved. See also [thorax](https://github.com/ArctosDB/arctos/issues/2437)

**Table**
http://arctos.database.museum/info/ctDocumentation.cfm?table=CTSPECIMEN_PART_NAME

**Value**
abdomen

**Definition**
the posterior part of the body of an arthropod, especially the segments of an insect's body behind the thorax.

**Collection type**
Ento, ES, Teach

**Part tissue flag**
No

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
@Jegelewicz

**Comment by campmlc** [comment]
I really think we need to have a discussion about body parts. If we are
going to add every possible anatomical term from every taxonomic group to
the part table, we are going to need a different interface for choosing
parts from the table, otherwise it will become astronomically more
unmanageable than it is now. We've already attempted this with attributes:
see "location in host" for parasites. We need to brainstorm some solutions
outside of the current box.

**Comment by campmlc** [comment]
In this case parasites, the part is "partial organism". The specific body
part could be a part attribute - but only if we can make these searchable
and downloadable into something other than a JSON string.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> We need to brainstorm some solutions outside of the current box.

I agree, but that is a large discussion encompassing all parts. In the meantime, we need to continue uploading specimens. Since there are already a lot of very specific parts in the parts table, couldn't we continue adding as appropriate, and if we reorganize the table at a later date, then they will be included in that reorganization.

**Comment by campmlc** [comment]
That is a lot of code table changes. Wouldn't it be possible to just add
"organism, partial" as the part, add the specific part as an attribute or
remarks, and Dusty can magic that in later?

**Comment by Jegelewicz** [comment]
See #2713 

If we are going to accommodate the huge variety of collections and the materials they hold, I think we need to expect people will want 

> every possible anatomical term from every taxonomic group

in the part table.

I see two possible options:

1. We just add all of the anatomical terms, but make sure they are properly defined and associated with the collections that NEED them. (I would argue that mammals do not need "arm" but inverts do...but probably others would argue differently.) I also think we should start relying on Wikipedia links for further explanation of parts just as we do with higher geography. [Phalanx](https://en.wikipedia.org/wiki/Phalanx_bone)

2. We simplify the part table, but then include a whole bunch of descriptive attributes (that put the real information a step further from the part and cause all kinds of search timeouts and download issues - 

> but only if we can make these searchable and downloadable into something other than a JSON string

When it comes to this, I struggle:

> That is a lot of code table changes. Wouldn't it be possible to just add "organism, partial" as the part, add the specific part as an attribute or remarks, and Dusty can magic that in later?

Why was it OK to add "phalanx", but it's not OK to add "abdomen"? New types of collections should not be held back because older ones don't want to see a bunch of part names.

And finally - why is it such a big deal if we have a lot of parts? There ARE a lot of potential parts! (Just like there ARE a lot of potential taxa). As long as the parts have clear definitions and are useful to the communities that request them, why should we start saying NO?

**Comment by dustymc** [comment]
>every possible anatomical term from every taxonomic group

That's a start - Arctos also holds cultural collections and I see no reason to leave them out of this discussion.

>I would argue that mammals do not need "arm" but inverts do...

This is critical if we go in this direction. Mammals will need "arm" if someone's cataloged a starfish in a mammal collection (it happens....) - using "arm" for a mouse is just wrong, and that should be clear from the documentation. That is, "arm" need to mean one THING ('starfish appendage') and NOT "whatever anyone's ever called 'arm'" (eg, car part). Any other approach will mean these data aren't usefully searchable, and if we're going to end up with garbage data anyway let's just make this free-text and avoid the hassle.

>Why was it OK to add "phalanx", but it's not OK to add "abdomen"? New types of collections should not be held back because older ones don't want to see a bunch of part names.

Agree - whatever we do should be consistent and predictable.

>why is it such a big deal if we have a lot of parts?

More values makes a thing harder to find for data entry, and harder to find for search. "Just" a usability problem! (But everyone with access to data entry has been instructed to carefully read the documentation so that part's not a problem - right?!)

>Just like there ARE a lot of potential taxa

Not a perfect comparison - taxonomy is a lot more formalized, and the existence of type specimens means we can't ignore the inconvenient bits - but still, I'd expect having 3 million parts to pick from to cause similar issues to picking from three million names.

**Comment by campmlc** [comment]
The problem with a lot of parts is 1)knowing a priori what part to search,
2) not having a part ontology so that if you search on "manus" you also are
finding "phalanx", and 3) the utter impossibility of the current parts
display during single record data entry. It goes on for miles already.

**Comment by dustymc** [comment]
>a part ontology

I want to just say "yay, not our problem!!" and be done with this, but I'm not sure that would line up with reality. Who'd maintain this? If "not us" then what happens when we really need some weird jellyfish part and it's not in the ontology, or if we disagree with the ontology? If "us" then is an ontology really the most appropriate tool - can we do simpler, or do we need something more complex? I do think we need to have some big-picture conversations about parts, but I don't think we should go into that with an outcome in mind.

**Comment by Jegelewicz** [comment]
@ArctosDB/arctos-code-table-administrators approved addition of body part names - plans to look at ways to do this better, but does not want to impede progress for incoming collections.

Done.
