### ISSUE TITLE
carapace - add to part definition

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#2725]
**Goal**
In order to catalog fossil arthropod parts, expand carapace definition to include arthropods.

**Context**
The definition of carapace currently limits the term to "dorsal part of turtle shell". Shell or exoskeleton is not sufficient for arthropod carapace, the carapace is a particular section of the exoskeleton.

**Table**
http://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name

**Value**
carapace

**Definition**
dorsal part of the turtle shell or the exoskeleton over the cephalothorax of an arthropod.

**Collection type**

Currently this part is available for ES, Herp, Hild, Rept, Teach, if we expand the definition Inv should be added.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
@Jegelewicz

**Comment by dustymc** [comment]
Suggest we reject this and find a replacement term; this denormalization would preclude searching for turtle-bits.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I don't think there is a replacement term that wouldn't be non-specific?

![image](https://user-images.githubusercontent.com/47402809/83576743-a88a5b00-a4ef-11ea-8d4a-4b42d7b77e3e.png)

Certain terms are going to be homynyms defining different bits in different groups of organisms. How do we deal with that? It seems to me that people may just have to enter some taxonomy when doing searches.

**Comment by dustymc** [comment]
This is a bit like taxonomy in that smallish groups of people use one word to mean different things, but it's very unlike taxonomy in that there are no types - we're not forced to use any particular vocabulary.

"exoskeleton, dorsal" (with dorsal eventually moved to part attributes) seems like it could work, as could eg "carapace, invertebrate" (but that doesn't fit so nicely into the idea of part attributes). I'm not sure I have useful suggestions. Any well-defined UTF string that's not already used for something else probably suits me; as long as we don't mix it up with other stuff, we can always change that.

**Comment by campmlc** [comment]
Is it really a problem to use a common term across taxa? If I want turtles,
I would search for Testudines and carapace. If I want crayfish,
Malacostraca and carapace.

**Comment by aklompma** [comment]
Agree with Nicole. Carapace should be used for decapod crustaceans.

**Comment by dustymc** [comment]
Taxonomy-based searches seem to always find a way to rot, and are not predictable across collections.

If we don't mix them, "find carapaces, but not from crabs" is an easy task no matter what happens in some unrelated corner of Arctos (eg, taxonomy) or what administrative decisions have been made (herp collection cataloged a shrimp). If we do mix them, they'd have to be un-mixed, probably by the individual collections, before that question can be answered (and the chances of that happening are low). It's impossible to say if anyone will ever care, but given that scenario I'll always advocate for the reversible approach.

**Comment by Jegelewicz** [comment]
I see no problem with this at all. People who search "carapace" and end up with turtles and crayfish can then refine their search depending on what they are interested in. Pretty sure peeps are smart enough to figure that one out.

**Comment by campmlc** [comment]
I agree.

**Comment by lin-fred** [comment]
Does anyone have an opinion on Armadillo carapace? What do collections use currently?

We already use "skin" for a stuffed armadillo that we have, so I don't want to use skin for just the carapace, or is that appropriate?

**Comment by campmlc** [comment]
You can use skin, study or skin, mounted for the stuffed armadillo.

**Comment by lin-fred** [comment]
Yes it will be skin, study for the stuffed armadillo

But we have two specimens with just the carapace

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I think we could incorporate armadillos into the definition. What we said earlier still applies - if someone is searching for carapaces, they can sort by taxonomy to get whichever critter they are looking for.

**Comment by campmlc** [comment]
Agree. Is carapace created now?

**Comment by dustymc** [comment]
I don't have a use case clearly suggesting that there's a need to find spider-bits and not turtle-bits so I won't oppose this very aggressively, but I do not think the data are supportive of "they can sort by taxonomy to get whichever critter." If we do this, we should do so with a realistic view of the effects.

**Comment by campmlc** [comment]
This would also be the same solution needed for "foot" for mollusc. Keep a
part which can be used for multiple taxa.

**Comment by dustymc** [comment]
Yes, that is the big-picture question. Do we...

1. Continue as before, where if the clam-people get there first then "foot" can by definition apply only to clams. If we do this, then 
    * a search for "foot" will find very specific material, and
    * a new term will have to be created for non-clam material that's been called 'foot'
2. Alter our trajectory to allow "foot" to mean whatever anyone wants it to mean. If we do this then
    * we'll end up with fewer overall terms (I'm struggling to find a positive slant!)
    * people looking for "foot" should expect to find lizards and bathtubs, along with clams

There's been a lot of development in favor of (1), if we're now going towards (2) perhaps we should revisit that - eg, requiring a definition and also allowing terms to be defined by local or traditional use doesn't really make sense to me. ``foot==whatever's been called 'foot'`` isn't informative. From there, if we can no longer usefully define terms then do we really need a controlled vocabulary; what precisely could that DO that other arbitrary strings (which require much less structure) cannot?

**Comment by campmlc** [comment]
I support 2. Reduction of terms will mean people can find what they want
for either data entry or search. We have the ability to easily refine
searches by taxon. Foot is legitimate for molluscs - and most public users
looking for vertebrates will also expect to search on foot and not pes.
And to be honest, our taxon searches already work this way. I search on
cestodes and find all kinds of things that aren't cestodes. This wouldn't
be any different.

**Comment by lin-fred** [comment]
I am still unsure about the carapace for the armadillo. Could also put it under skin, with carapace in the remarks?

Otherwise when someone searches for armadillo carapaces, possibly wanting to take a piece of it for destructive sampling, they'd have to know to look up skin and carapace. Now that I've thought about it a bit more, I'm leaning towards not having carapace for mammals.

**Comment by dustymc** [comment]
> Reduction of terms will mean people can find what they want
for either data entry or search.

Yes, that is a very good point. False positives are much easier to deal with than false negatives. Getting bathtubs out of your download might be a pain, but it's possible. Never getting any indication that Arctos has anything you're interested in because you never found the right overly-specific search term isn't so straightforward to deal with.

>taxon searches already work 

Taxonomy is a known mess; along with finding all kinds of things that aren't cestodes, you may very well be NOT finding all kinds of things that ARE cestodes, and short of going through everything (which isn't remotely realistic) you can't possibly know. 

I'm more or less OK with intentionally giving up functionality here, but we really need to all be comfortable with the idea that **we are losing functionality**, because we are.

If we do this, I suggest we are very explicit in our "undefinitions." ``carapace==>Any of several generally shell-like structures.`` or something equally vague.

**Comment by Jegelewicz** [comment]
> if we can no longer usefully define terms then do we really need a controlled vocabulary; what precisely could that DO that other arbitrary strings (which require much less structure) cannot?

It can stop people from entering "fooot"

I am not convinced that any functionality is lost. Right now, we have two ways of saying "foot" and depending on who is searching they might end up right here: 

> Never getting any indication that Arctos has anything you're interested in because you never found the right overly-specific search term isn't so straightforward to deal with.

If foot means three different things, then maybe we should just warn people.

> The part name you selected includes multiple definitions that may be related to a variety of taxa, you may want to add a taxon name to your search to ensure that you limit your results to the taxa in which you are interested.

Maybe we need a "this term has more than one definition" check box in the code table so that the message above or something like it is displayed when the term is selected for searching.

**Comment by dustymc** [comment]
>"fooot"

I've proposed a "dictionary" model which would, but without all the complexity of the current model, at various times.

>not convinced that any functionality is lost

It is; with this change it is no longer possible to do something that's possible now.

>might end up right here

And some functionality is gained. I don't think I'm even willing to argue it's not a good trade, but it's still one we should make fully aware of the implications.

>maybe we should just warn people.

That's essentially where I ended up. I don't really like the idea of rating our documentation; I'd rather (somehow) do a better job of getting all documentation in front of all users. I think there are three classes of users we need to address:

* data entry - when should I use this?
* search - what will this do?
* admin - why shouldn't I tighten this definition up?

**Comment by campmlc** [comment]
"False positives are much easier to deal with than false negatives. Getting
bathtubs out of your download might be a pain, but it's possible. Never
getting any indication that Arctos has anything you're interested in
because you never found the right overly-specific search term isn't so
straightforward to deal with. "
This supports option 2 above. Better to have fewer, more generally
recognizable and searchable terms that may yield things you don't want. I
don't think it is reasonable to force students doing data entry ( or CMs
for that matter) and public users to scroll through long code tables full
of precise definitions for each term that must be read to decide on the
appropriate term for data entry or the appropriate term for search.

**Comment by lin-fred** [comment]
After discussion at our digitization meeting, do not add carapace to the mammals. The armadillos will have skin, with partial in the condition and carapace in the remarks

**Comment by Jegelewicz** [comment]
OOPS, my bad! Will do!

**Comment by Jegelewicz** [comment]
Now it's done.
