### ISSUE TITLE
Trouble bulkloading more than 5 identifiers?

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#2794]
Anyone else having this problem? Also, does PG require they be in order in the csv? That was not the case for Oracle. But I'm getting strange errors that I can't find the source of. I deleted identifiers 6-8 and it loaded . . . 
![Screenshot 2020-06-15 14 53 52](https://user-images.githubusercontent.com/14808196/84707538-1a18cf00-af1c-11ea-8a41-235c0a59826d.png)

**Comment by campmlc** [comment]
Well, that makes sense, I guess, although I thought we were allowed 10 of
everything, to be consistent with parts and attributes.

**Comment by campmlc** [comment]
This might need to be revisited now in the age of GenBank and IsoBank
identifiers.

**Comment by Jegelewicz** [comment]
I have started using the Identifier bulkload tool.

**Comment by campmlc** [comment]
Minimally need to add this to our list of errors to add explanatory language to.

**Comment by dustymc** [comment]
No, there's no consistency - 8 collectors, 12 parts, 10 attributes, 6 geology determinations....

That's why there's a builder!

>revisited

https://github.com/ArctosDB/arctos/issues/2178, although I do worry that we're adding complexity for fringe cases and would be better off overall with a less-capable but simpler model.

>GenBank and IsoBank

That would only(ish) be a factor if you're loaning uncataloged material. 

>add explanatory language

Better errors are always better, but 

<img width="278" alt="Screen Shot 2020-06-15 at 3 26 07 PM" src="https://user-images.githubusercontent.com/5720791/84712061-91e6f980-af1c-11ea-805c-5854875f1648.png">

seems fairly clear to me.

**Comment by campmlc** [comment]
"That would only(ish) be a factor if you're loaning uncataloged material."
How about: trying to finally resolve 2 decades of loans of uncataloged
material. Anything to make this easier would be appreciated. The data are
still recoverable, barely - hence the need to avoid adding unnecessary
complexity in the form of multiple bulkloads for the same data.

**Comment by campmlc** [comment]
I disagree that that error message is clear. In Arctos, such a message
could mean all kinds of things, from "you typed the header or controlled
vocabulary in wrong, and so it doesn't exist" to "there is no such field
allowed". Trying to rule out the former wastes a lot of time and leads down
rat holes.

**Comment by campmlc** [comment]
And the uncataloged material is legacy parasite material that had no place
to go in Arctos; can't trust host biologists to track parasites if there is
no clear place to put them (Remarks, if we are lucky). But now, we have
fantastic Arctos parasite collections and data fields! Just have to have
dedicated personnel to try to recover the data and put it where it belongs
and is trackable.

**Comment by Jegelewicz** [comment]
People are the answer.
