### ISSUE TITLE
Expand permission to refresh in taxonomy module to all Arctos users

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#2808]
Arctos users without taxonomy permission are not able to Refresh Global Names or Refresh the WoRMS (via Arctos) entry.  
________________

![Screen Shot 2020-06-18 at 7 07 42 AM](https://user-images.githubusercontent.com/15368365/85023839-7d7c4a00-b132-11ea-8b01-e4da740caf70.png)
__________________
![Screen Shot 2020-06-18 at 7 08 01 AM](https://user-images.githubusercontent.com/15368365/85023852-8240fe00-b132-11ea-9c95-f1a0972d9cae.png)

The Taxonomy Committee identified no issues but some benefits to allowing all Arctos users (including the general public) ability to Refresh.  This often brings in additional sources from Global Names.  Also, the WoRMS (via Arctos) refresh brings up the Preferred Name which is helpful if the name is invalid and a link to the preferred name is not already established.
__________________

![Screen Shot 2020-06-18 at 7 13 21 AM](https://user-images.githubusercontent.com/15368365/85025778-10b67f00-b135-11ea-9f3b-f9c1f511bfa4.png)

___________________

![Refresh WoRMS (via Arctos)](https://user-images.githubusercontent.com/15368365/85025531-bf0df480-b134-11ea-869a-8bb2bf9617e0.png)
___________________

WoRMS (via Arctos) entry after refresh showing preferred name (no change in this example because it is a valid name).

![Screen Shot 2020-06-18 at 7 28 17 AM](https://user-images.githubusercontent.com/15368365/85026191-9cc8a680-b135-11ea-8649-6a5700277726.png)

Refresh is the only command we are requesting be available to the general public as editing, cloning, creation and deletion of taxon names and classifications should be limited to those with taxonomy permissions.

**Priority**
Medium priority.  This will be included in the Taxonomy Committee consolidation of requests for modifications to the taxonomy module.

**Comment by sharpphyl** [comment]
This issue is included in #2695.  See https://drive.google.com/drive/u/0/folders/1gQdI-qWCDFAe6yJSkWkUKlXLAX5KYwLp

<img width="737" alt="Screen Shot 2020-10-21 at 4 25 43 PM" src="https://user-images.githubusercontent.com/15368365/96793717-1f01f980-13ba-11eb-8057-25b46d3e0d17.png">


@Jegelewicz   I'll leave this open in case you want to discuss this in the committee.  It will be months before we have volunteers doing data entry again, but I would like to have this feature in place when they return to the Museum.

**Comment by dustymc** [comment]
Let's please reserve the critical label for things which are breaking existing functionality.

**Comment by Jegelewicz** [comment]
Trying to get it on the AWG radar and the critical label is the only way to do it....

**Comment by dustymc** [comment]
This is not supported by our security model, our processing capability, or our arrangements with providers.

**Comment by sharpphyl** [comment]
@dustymc  Are you saying that you can't separate out both the **Pull/Refresh Global Names** and **Refresh WoRMS (via Arctos)** from the rest of the taxonomic permissions?

**Comment by Jegelewicz** [comment]
Allow for data entry to avoid public changes to taxonomy.

**Comment by sharpphyl** [comment]
> This is not supported by our security model, our processing capability, or our arrangements with providers.

@dustymc  Are you saying that we can't expand refresh capability beyond those with taxonomic authority?  If that's true, can we refresh everything at some frequency - even once a year - so that the most current information always comes up?  

All this may be moot and we can close this down if #3311 moves forward.  There has been no comment in that issue for over a month.  Is it moving forward and will it eliminate any concern about what classifications appear on the Arctos taxon page?

**Comment by dustymc** [comment]
Yes #3311 is a much better mechanism for this (from my perspective). I don't see any objections over there, so I believe it's just a matter of prioritization. Go make some noise!

If that fails for some reason we can revisit this. I can - if I have to! - find a way to make refresh available to Operators without manage_taxonomy.

**Comment by sharpphyl** [comment]
> Go make some noise!

@Jegelewicz Let's put this on the agenda for today's taxonomic committee meeting.

**Comment by Jegelewicz** [comment]
Discussed during @ArctosDB/taxonomy meeting this week.

> If that fails for some reason we can revisit this. I can - if I have to! - find a way to make refresh available to Operators without manage_taxonomy.

@dustymc we walked through one of these during the meeting and it brought up a question. What is the difference between this refresh

![Screen Shot 2020-06-18 at 7 13 21 AM](https://user-images.githubusercontent.com/15368365/85025778-10b67f00-b135-11ea-9f3b-f9c1f511bfa4.png)

and this one?

![Refresh WoRMS (via Arctos)](https://user-images.githubusercontent.com/15368365/85025531-bf0df480-b134-11ea-869a-8bb2bf9617e0.png)

The second one adds the preferred name 

![Screen Shot 2020-06-18 at 7 28 17 AM](https://user-images.githubusercontent.com/15368365/85026191-9cc8a680-b135-11ea-8649-6a5700277726.png)

which is important when trying to choose a currently accepted name. This is very useful to @sharpphyl and her team. We wondered if there is some way to ensure that the preferred name is available for all WoRMS (via Arctos) classifications with some sort of periodic update in the background. This would eliminate (I think) the need to allow non-operators to refresh.

**Comment by sharpphyl** [comment]
This may belong in [#3512](https://github.com/ArctosDB/arctos/issues/3512) but the two are related.  @Jegelewicz just this week I learned that there has been a major revision of the superfamily Buccinoidea.  There are five new families and many other changes.  

My question @dustymc is when would you expect these changes to show up in WoRMS (via Arctos)?   It will be at least another month before our volunteers return and start databasing.

The new families and other changes showed up in WoRMS between 7/18 to 7/21.  Theoretically, Global Names won't pick them up for up to 6 months.  I've already started to refresh species used as ID's and other users can do the same, but it can introduce inconsistency into the classifications.  We could use the hierarchical tool, but we promote using WoRMS (via Arctos) because it is externally managed.  

Is it possible to refresh one superfamily in WoRMS (via Arctos) or, as Teresa has suggested, refresh all of WoRMS into WoRMS (via Arctos) semi-annually or annually to pick up both the preferred name and these major taxonomic changes?

**Comment by dustymc** [comment]
>difference between

One pulls from GlobalNames, the other directly from WoRMS

>preferred name

Those data are in the GlobalNames pull, but structured a bit differently - they become classifications, rather than metadata of a single classification. See the second (for me, anyway) classification in https://arctos.database.museum/name/Conus%20maculatus#WorldRegisterofMarineSpecies

<img width="1053" alt="Screen Shot 2021-07-26 at 8 57 34 AM" src="https://user-images.githubusercontent.com/5720791/127020632-5bd6fda4-72a3-4756-85ce-1e3cd71fa9c2.png">

I'm not sure we could successfully change that to the "Arctos view" (maybe we could), but we could somehow display it (screen real estate might be the limiting factor).

>expect these changes to show up in WoRMS 

I think WoRMS updates occasionally just overwhelm our scripts, and that's going to be hugely compounded by the Arctos services being spotty (at best) for the last week or so.

We really need to back up and come up with a sustainable plan for this. The webservices don't get the attention they need, and I'm not sure where we might realistically divert that from. I don't think we have the processors to just periodically recheck everything, and I doubt WoRMS terms would allow that anyway. We're not USING most of what's in WoRMS, so there's little reason to push that (that I can see). My preference remains piping everything through GN, but that doesn't seem to be progressing for whatever reason. Perhaps a more manual approach could work; that would look something like...

* shut down the automated services (which as above don't seem to be very predictable anyway)
* manually add aphiaid to things that need managed via worms (it's automated for names that are created from worms now, so that may not be a noticeable difference. The classification bulkloader should serve this purpose.)
* Provide a mechanism to refresh on demand. This could be the existing "click to pull one", plus some app that calls https://github.com/ArctosDB/arctos/issues/3512#issuecomment-796880271 (eg refresh for all name-at-rank).

That's still a lot more connected than any sort of download-->upload mechanism, but it also avoids the most fragile and problematic of the services, and doesn't burn all of our resources on things that nobody is using (eg seaweed taxonomy). Workable?

**Comment by sharpphyl** [comment]
>Those data are in the GlobalNames pull, but structured a bit differently - they become classifications, rather than metadata of a single 

If I understand you correctly, the "preferred name" is in GlobalNames but doesn't get into WoRMS (via Arctos) without you taking some action (such as a refresh) on the WoRMS (via Arctos) entry.  Correct?

In the future, I would agree that we need to come up with a sustainable plan, but right now only a few collections are using WoRMS (via Arctos) and it seems they mostly use the molluscan taxonomy which is about 25% of all the WoRMS taxon names.  Is it possible to at least annually refresh all the Mollusca?

Your manual approach also sounds doable.  First, I'm not aware of many names in WoRMS (via Arctos) that do not have an aphiaID.  I tried to run your SQL from [#2196](https://github.com/ArctosDB/arctos/issues/2196#issuecomment-701434280) and got an internal error perhaps because of limited service right now.

> Provide a mechanism to refresh on demand.

This is a very attractive option.  It would be helpful if it were at least at the Superfamily level or higher.  I think that would solve a lot of problems.  

Would it be able to add taxon names that are new to WoRMS or just update the classification and metadata?  Of course, it would be ideal if it could do both, even if it were at the family level.
