### ISSUE TITLE
Reorder Part/Part Subsamples in Part Edit

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#2848]
In Catalog Record-> Edit Parts, the subsamples used to display immediately under the part from which they were subsampled.
In current PG view, the subsamples are at the bottom of the display.
Request that subsamples be reordered so that they are immediately below the part which they were subsampled from.

See https://arctos.database.museum/guid/MSB:Mamm:224225
Go to Edit Parts
Scroll to bottom

**Comment by dustymc** [comment]
>The part table display in Catalog Object Record is sorting by barcode rather than by part name. Can we get the sort by part name first and then by barcode?

This is a place where PG's relatively primitive nature is problematic.

That's actually sorting by PG-hierarchy-magic. We need a multi-level sort that includes https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_list_order (https://github.com/ArctosDB/arctos/issues/2862), part name, level of hierarchy, and all of that for siblings at every level, with attributes sorted and injected in the proper place.

Certainly possible in some way, but I don't think trivial, and should be done in a reusable way to allow consistency and limit the proliferation of overly-complex code.

I'd guess it's going to take a full rebuild of the UI-guts as well, so if there's anything you don't like about that now's a good time to sort it out.

Probably an uninterrupted week??

Needs prioritized.

**Comment by campmlc** [comment]
Ok, if we are rebuilding UI then also on this wish list is ability to
display/show part attributes and add part attribute preservation to
concatenated display with part name, to deal with when we split part from
preservation.

**Comment by dustymc** [comment]
New Issue I think - that's come up a couple times, keeps getting buried.

**Comment by ccicero** [comment]
Related to this is how Arctos displays subsamples on the specimen detail page. They are indented under the part, but that is not clear that those are subsamples. @ewommack was asking me about that because she was confused about this. If a AWG officer is confused, then we can't expect the general public to understand. This has come up before, but I can't find another issue for it.

I'm open to suggestions on how best to display this. One idea: rather than repeat the part name, replace it with 'subsample' if subsample = 'yes'

**Comment by campmlc** [comment]
Agree this is a serious problem and I agree with using "subsample" or
"part_name (subsample)" in the display.

**Comment by dustymc** [comment]
I think there are two issues here. First, there's no limit to the depth so we might end up with...

* part
    * subsample part
        * subsample subsample part (??)
             * subsample subsample subsample part (??)
                  * .....

... which seems overly confusing.


Second, "subsamples" aren't defined or homogenous- they're everything from a tiny bit of tissue that we'll never see again to a rib pulled from a skeleton. I'm not convinced that the general public understanding that a part is a "subsample" is useful in understanding what the part is. 

Maybe 'subsample' is "curator stuff" and the general public doesn't need that information at all?

**Comment by campmlc** [comment]
I'd agree that subsamples could be displayed only for curator's view, or
perhaps, they could be hidden by default and displayed at curatorial
discretion.

**Comment by ccicero** [comment]
I agree that this is not something the general public needs to have, it's more curatorial.

**Comment by ccicero** [comment]
Can we discuss briefly at this weeks issue meeting? Seems like the simplest solution is to limit to curatorial access.

**Comment by ewommack** [comment]
Absolutely! The [agenda](https://docs.google.com/document/d/1aKAT2U7ET5aFc8t2Mjw0uxNdl2yFrIYrqWvY7SetVMw/edit?usp=sharing) is waiting to go, so feel free to add what ever you like to it for the discussion.

**Comment by campmlc** [comment]
Public vs curatorial view
![Screenshot 2020-09-03 12 22 56](https://user-images.githubusercontent.com/14808196/92152947-c1512800-ede0-11ea-8ebb-87f8a5d2670d.png)
![Screenshot 2020-09-03 12 25 31](https://user-images.githubusercontent.com/14808196/92152957-c4e4af00-ede0-11ea-96c7-1f5e2e2cc1ad.png)

**Comment by campmlc** [comment]
And Edits part view:
![Screenshot 2020-09-03 12 28 23](https://user-images.githubusercontent.com/14808196/92153128-01180f80-ede1-11ea-8afc-663dfeda9676.png)

**Comment by campmlc** [comment]
And public view Details
![Screenshot 2020-09-03 12 34 41](https://user-images.githubusercontent.com/14808196/92153701-ed20dd80-ede1-11ea-8950-5e7ec3d57203.png)

**Comment by dustymc** [comment]
AWG likes "subsample" in one of the parts views, but "subsample" isn't quite the right term and banishing it from our vocabulary may make this all easier to understand. Perhaps "child of" or "derived from" (which matches the model) would be better.

There are two kinds of things that get "subsampled" (hard to avoid that term!); anything we do in the UI needs to be capable of handling both use cases.

1. A "muscle" gets split into a muscle and a smaller sample of still-muscle.
2. A jaw is removed from a skull, a dentary is separated from the jaw, a tooth is extracted from the dentary, and a dentine sample is removed from the tooth., resulting in....

* skull
    * jaw (derived from skull)
        * dentary (derived from jaw)
        * dentary (derived from jaw)
            * tooth (derived from THAT dentary)
                * dentine (derived from tooth)

(1) works reasonably well in the loan UI; (2) does not. It was suggested that "subsample" could be expanded to "subsample as {new part}", which would allow a feather pulled from a wing to be created as "feather" instead of "wing subsample" (there's that word again). This would probably further complicate https://github.com/ArctosDB/arctos/issues/2741, which everyone seems to think is over-complicated (at least the parts that they don't use).

I believe the AWG consensus is that the public UI should have enough information for a user to evaluate suitability for their use. That is probably incompatible with removing ancestry from the public UI; knowing that a tooth is already extracted, or that it was extracted from the left dentary, will be important for some users. (Adding anatomical direction to the tooth would somewhat compensate, but is also denormalization; "original" data are available from the linked part.)

**Comment by Jegelewicz** [comment]
You know, it seems like we are kinda confounding two things.

As @acdoll said - subsampling should mean that the stuff you took is essentially equivalent to the stuff you took it from (when you subsample some muscle, both the original sample and the subsample are muscle)

When you take a tooth out of a jaw, it is more like separating something into new component parts. https://www.macmillandictionary.com/us/thesaurus-category/american/to-separate-an-object-or-area-into-parts

I am failing to come up with a term for this. Maybe splitting?

When taking something from a part, could we have the choice between subsampling (see definition above) and splitting (creating a new part that was once included in the old part, but is not equivalent to it).

Both of these could be treated as "derived from" (which is my preferred term).

**Comment by dustymc** [comment]
I don't see much difference nor a reason to attempt pigeonholing. It's all just parts with a parent-child link to another part.

**Comment by campmlc** [comment]
The main difference would be the option of changing the part name during
subsampling, while still keeping the parent/child relationship.
E.g.
Parent part:
skin, study
      Derived part 1: feather
            Derived part 2: DNA (frozen)

**Comment by dustymc** [comment]
>option of changing the part name

https://github.com/ArctosDB/arctos/issues/2848#issuecomment-686758408 - I'm not sure I could predict when you might want to do that, I think such a tool would just always be available.

**Comment by Jegelewicz** [comment]
> I think such a tool would just always be available.

I guess that's what I was getting at. Just an option when "subsampling" to either use the part name of the part being sampled or use a new part name.
