### ISSUE TITLE
Taxon names without a classification in a single collection

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2888]
Can we get a list of all taxon names used in identifications in NMMNH:Paleo that do not have an associated classification in the Arctos source?

**Comment by acdoll** [comment]
I just was looking at that for our collections - here's some SQL that Dusty provided previously:

Select
 taxon_name.scientific_name
from
  identification_taxonomy,
  identification,
  cataloged_item,
  collection,
  taxon_name
where
  identification_taxonomy.identification_id=identification.identification_id and
  identification.collection_object_id=cataloged_item.collection_object_id and 
  cataloged_item.collection_id=collection.collection_id and
  identification_taxonomy.taxon_name_id=taxon_name.taxon_name_id and
  collection.guid_prefix='NMMNH:Paleo' and
  taxon_name.taxon_name_id not in 
  (select taxon_name_id from taxon_term where 
    taxon_term.taxon_name_id = taxon_name.taxon_name_id and
    taxon_term.source=collection.PREFERRED_TAXONOMY_SOURCE
    )

It doesn't show any results for me, but maybe that's because I don't have access to that collection?

**Comment by Jegelewicz** [comment]
Works like a charm! Added to [SQL Cheat Sheet.](https://docs.google.com/document/d/15e3b8WNErFPqg1SW-QNq0nI_RjiEEZjWQDznxIJNFHE/edit#heading=h.b20evqfj43mk)
