### ISSUE TITLE
locality attributes: identifiers

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#2898]
Can we merge

  Site Field Number
 Site Identifier
 Site Collector Number

and perhaps use remarks to semi-differentiate?

Suggest free-text "site identifier" if we can.

@Jegelewicz @Nicole-Ridgwell-NMMNHS

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
This: https://github.com/ArctosDB/arctos/issues/2847 is relevant.

These ought to have the same sort of structure as specimen identifiers.

**Comment by Jegelewicz** [comment]
The cool thing with this is that unlike other IDs, we have a determiner to associate with the number. So I actually thing we could merge these into a single thing "site identifier". The values will be free text because the number format depends upon the agent who created it. The determiner will be the agent who assigned the identifier to the site.

However, how hard will it be to find all identifiers assigned by "Spencer G. Lucas"? This might be something people will want to do....

**Comment by dustymc** [comment]
Yes these are already agent-including - and date, method, ... 

> how hard will it be to find all identifiers assigned by "Spencer G. Lucas"

Trivial.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Ok, I'm on board with merging then.

**Comment by dustymc** [comment]
done
