### ISSUE TITLE
New locality attribute - Mindat location identifier

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2922]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Goal**
I am cataloging mineral specimens and many of them come from mines with locality information stored at https://www.mindat.org I would like to have a locality identifier that links to mindat using a base URI of https://www.mindat.org/loc-

**Context**
A locality ID that can DO something!

**Table**
http://test.arctos.database.museum/info/ctDocumentation.cfm?table=ctlocality_attribute_type

**Value**
Mindat location identifier

**Definition**
Enter the identification number only of the Mindat location
![image](https://user-images.githubusercontent.com/5725767/87565782-57898d00-c67f-11ea-9320-d3f0988d4adf.png)

**Collection type**
N/A

**Attribute data type**
free text, but can we limit to numbers only?

**Attribute value**
N/A

**Attribute units**
N/A

**Part tissue flag**
N/A

**Other ID BaseURL**
https://www.mindat.org/loc-

**Priority**
Please assign a priority-label.

NOTE:
I am creating named localities for a lot of mines using the Mindat information and placing the URL to the Mindat location in either the locality remark (if Mindat provides no coordinates) or the georeference source (if Mindat provides coordinates)

See [Valenciana Mine](https://arctos.database.museum/showLocality.cfm?action=srch&showDetail=locality&higher_geog=&any_geog=&continent_ocean=&country=&state_prov=&county=&quad=&feature=&drainage=&island_group=&island=&sea=&geog_auth_rec_id=&hasGeoWKT=&locality_name=&spec_locality=Valenciana+Mine&collnOper=&collection_id=&MinElevOper=%3D&minimum_elevation=&MaxElevOper=%3D&maximum_elevation=&orig_elev_units=&MinDepOper=%3D&minimum_depth=&MaxDepOper=%3D&maximum_depth=&depth_units=&locality_remarks=&locality_id=&datum=&max_err_m=&coord_serv_diff=&dec_lat=0&dec_long=0&search_precision=2&lat_deg=&lat_min=&lat_sec=&dms_latdir=N&long_deg=&long_min=&long_sec=&dms_longdir=E&dec_lat_deg=&dec_lat_min=&dm_latdir=N&dec_long_deg=&dec_long_min=&dm_longdir=E&geology_attribute=&geo_att_value=&geology_attribute_hier=0&verbatim_locality=&begDateOper=%3D&began_date=&endDateOper=%3D&ended_date=&verbatim_date=&collecting_event_name=&coll_event_remarks=&collecting_event_id=#results)

**Comment by Jegelewicz** [comment]
Makes sense, but I just found this too. This USGS thingee has all kinds of cool stuff.....

https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10013310

Could we use these with a base URI? 

Here is the Arctos locality

https://arctos.database.museum/editLocality.cfm?locality_id=11168466

**Comment by dustymc** [comment]
Those are formed where a base_url could work, but I'm still not seeing any compelling reasons to add the complexity - the full URL does the same thing, you're never very likely to have "10013310" by itself (or know what it is if you do), it's easy to copy-paste, .....

These seem a very different kind of data than OtherIDs was developed to accommodate. Those are intended to integrate resources that are directly related to individual specimens, where these seem to be information about something related to something related to a specimen and not directly to specimens themselves - right? 

I think I'm leaning more towards dumping these all into site identifier (and html-wrapping it when possible) instead of firing up a new concept for every possible vaguely-related thing, but I also can't identify any compelling technical reason to go one way or the other.

**Comment by Jegelewicz** [comment]
Using Mindat urls as site identifier attribute. Added to documentation.

**Comment by Jegelewicz** [comment]
Added Mindat identifiers to NMMNHS localities.
