### ISSUE TITLE
Name validation results presentation

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2940]
When I look at this newly minted name, it looks like there is a problem.

![image](https://user-images.githubusercontent.com/5725767/87993103-f14da180-caa6-11ea-9d95-242a8246f8b8.png)

Rather than asserting that the name is "probably_not_valid", how about we just say "name not present in GlobalNames"?

**Comment by Jegelewicz** [comment]
Note: the name was just published, so has not had time to propagate through the systems. No need to make it look "invalid".

**Comment by dustymc** [comment]
>Rather than asserting that the name is "probably_not_valid", 

Good so far....

>"name not present in GlobalNames"

...but that's not what it's checking - it's hitting a half-dozen services, and they come and go fairly often, and all of them occasionally do weird things.

Somewhere (my imagination??!!) there's a request for a table rather than a summary, which is fine there. Elsewhere (eg, name checker) I need some sort of text string that I can shove into a varchar "cell" and that'll make sense in whatever ya'll view CSV in - some sort of string summary.

I think that's all pretty clear from the [documentation](http://handbook.arctosdb.org/documentation/taxonomy.html#validation-service), and everyone with taxonomy permissions is intimately familiar with the documentation - right?

**Comment by Jegelewicz** [comment]
> everyone with taxonomy permissions is intimately familiar with the documentation - right?

HAHAHAHAHA!!!! You are SOOOOOO funny!!!

Anyway, it isn't just people with access to taxonomy who see this - it is anyone who has some kind of operator access, right? That includes the Curator who recently minted the name. Just want to be a little less judgemental and more informative. Whatever would do that best and isn't overly difficult would be an improvement I think.

**Comment by dustymc** [comment]
Yea I occasionally & briefly amuse me too....

The service call is eg https://arctos.database.museum/component/taxonomy.cfc?method=validateName&returnformat=json&taxon_name=Eye%20madeitup

Piping that to table probably makes the most sense, where a table can work.

**Comment by dustymc** [comment]
done
