### ISSUE TITLE
New part preservation - Riker mount

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2942]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Goal**
Accurately describe the preservation of mineral samples

**Context**
Riker mounts are a very specific method of preservation

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctpart_preservation

**Value**
Riker mount

**Definition**
a flat container used for mounting a specimen (typically plant or insect) on cotton wool or other backing material, often with transparent glass or plastic cover as protection https://en.wikipedia.org/wiki/Riker_mount

**Collection type**
N/A

**Attribute data type**
N/A

**Attribute value**
N/A

**Attribute units**
N/A

**Part tissue flag**
no influence

**Other ID BaseURL**
N/A

**Priority**
Please assign a priority-label.

**Comment by campmlc** [comment]
Agree.

**Comment by lin-fred** [comment]
Agree! We have some bats in Riker Mounts

**Comment by dustymc** [comment]
Better as container type? Does it do anything to the specimen, eg somehow influence fitness for use?

**Comment by Jegelewicz** [comment]
> Better as container type?
Probably, but we aren't going to barcode them anytime soon....we can't even go in to take photos.

> Does it do anything to the specimen, eg somehow influence fitness for use?
I don;t think so, but it is nice to know that something can be easily moved around because it is already in a neat container.

**Comment by lin-fred** [comment]
A specimen mounted in a riker mount will most likely have to say in that mount - in the sense that they are prepped differently to fit in there. I'm sure there are some cases where something could be taken out of the mount and put into a drawer, but our insects/bats are mounted in such a way to be meant for a riker mount.

**Comment by ebraker** [comment]
Agree. Insects and plants are prepared specifically for riker mounts instead of in the usual fashion (pinned, taped), so it does encompass prep/preservation method as well as a container type. We have riker mounts for our bats. There are two categories: the kind with cotton can be easily opened and the specimen removed for exhibit, or the fully clear riker boxes where the specimen appears free floating and would be very difficult for a non-conservator to safely disassemble. Generally a bat in a riker mount indicates that it is prepared with its wings spread (not always), so it can signal a variant study skin. Even if fully reversible (e.g., shells sitting on cotton in a riker box with no adhesives), the riker mount is still an intentional prep method.

**Comment by Jegelewicz** [comment]
OK, it seems like this is a valid part preservation as well as a container type. While we are looking at it, should we just add both? @ebraker @campmlc @lin-fred

**Comment by lin-fred** [comment]
Sure

**Comment by ebraker** [comment]
Sounds good to me.

**Comment by dustymc** [comment]
If you denormalize by allowing two ways to provide the same data, then there won't be a clear path to finding all of them. I emphatically suggest not doing that. It sounds like there are valid reasons to see this as part-data rather than container-data, and assuming each Riker-container would contain about one part then there are no or few efficiencies to being able to update "upstream" of parts anyway.

**Comment by Jegelewicz** [comment]
Cool - I'll leave the discussion about container for a day when someone actually requests it and just add the preservation for now.

**Comment by Jegelewicz** [comment]
Added
