### ISSUE TITLE
Accession Detail Page Changes

### ISSUE THREAD

**Issue by lin-fred** [ArctosDB/arctos#2948]
**Is your feature request related to a problem? Please describe.**
It's frustrating to have to save and click no permit every time to add an Agent on the Accession Detail page. Also, have to go to Manage Data --> Transactions --> Create New Accession each time to create new accession. What's the difference between In-house contact, outside contact, contact agent and why can't I have multiples of each? Why is Est. Cnt. abbreviated?

**Describe the solution you'd like**
Agents: Be able to add more than one agent at a time
Create New Accession: Have a button on the Accession Detail page to "Create New Accession"
Contacts: Can we be able to have multiples of each?
Est. Cnt. - Can it read Estimated Count

**Comment by dustymc** [comment]
>frustrating to have to save and click no permit every time

That was a Community decision - it should be in some GGNB issue

>Have a button 

Not much problem, other than screen real estate, but I think whatever you're doing is probably a fairly unique use case. I usually just build my own button in my browser's toolbar when I need something like that.

>What's the difference between 

https://arctos.database.museum/info/ctDocumentation.cfm?table=cttrans_agent_role

>have multiples

That'd:

* break a bunch of loan forms, and
* leave you without a single point of contact in various roles

>abbreviated

Screen real estate - someone didn't like it spelled out, or it made something weird at some point, or something like that.

**Comment by Jegelewicz** [comment]
> >frustrating to have to save and click no permit every time
> 
> That was a Community decision - it should be in some GGNB issue
 
No, we get that, but if you need to add multiple agents as contacts, you have to select it every time. This would be resolved if you could add all of your contacts and just save once.

**Comment by Jegelewicz** [comment]
>     Have a button
> 
> Not much problem, other than screen real estate, but I think whatever you're doing is probably a fairly unique use case. I usually just build my own button in my browser's toolbar when I need something like that.

C'mon man - we are struggling to get a registrar to actually use Arctos. A button [Save and Create Another Accession] right next to save that saves whatever you are doing then takes you to Manage Data > Transactions > Create Accession would really make their life easier.

**Comment by Jegelewicz** [comment]
> leave you without a single point of contact in various roles

And when that person is ill or out for some reason, no one gets the messages! First - we need better definitions of the roles and an understanding of how they are used by Arctos, then we need a way to add back-ups. Having a single point of contact will probably fail eventually.

BTW - we are talking about accessions, not loans. Very often there is more than one contact person for a given accession.

My questions in **bold**


TRANS_AGENT_ROLE | Documentation
-- | --
associated with agency | Agency which has provided support for a transaction. Useful to distinguish Accessions provided by people as part of their capacity at an Agency from those provided by agency personnel without agency  support, for example.
authorized by | Person or persons within the Institution who authorized a transaction. Multiple authorizers are allowed.
contact agent |  **What's this for? only one allowed? we need to say so if it is so**
entered by | Automatically populated with login information.
in-house contact | Single person within the institution to contact about the transaction. **only one allowed? we need to say so if it is so**
notification contact | Agent to which notifications are sent when a loan is approaching its due date. **only one allowed? we need to say so if it is so**
outside contact | Single person from outside the institution to contact about the transaction. **only one allowed? we need to say so if it is so**
received by | Person or list of people receiving a Loan.
received from | Person of list of people who provided an Accession.
unknown | DO NOT USE FOR NEW DATA - placeholder until legacy data can be sorted out

**Comment by Jegelewicz** [comment]
> Est. Cnt. 

Can we please just spell this out? The field is plenty long to accommodate "Estimated Count". Again, trying to get someone whose only brush with Arctos will be entering accessions and loans. We need it to be user friendly.

**Comment by lin-fred** [comment]
> > frustrating to have to save and click no permit every time
> 
> That was a Community decision - it should be in some GGNB issue

To clarify, I meant only being able to add one agent at a time, not the permit thing!

Otherwise Teresa helped broaden the explanations better, thanks Teresa!

**Comment by dustymc** [comment]
Thanks, all useful.

Things involving screen real estate probably didn't come from me, I'm just trying to advocate for the folks who've complained about that in the past!

The form could be rebuilt to handle more agents.

Yes code tables kinda always need better documentation.

The three one-only terms are `` ('entered by','in-house contact','outside contact') ``

There's no distinction between various trans_agent roles; any can be used for any type of transaction, and the rules attached to any role apply anywhere. Changing that isn't practical. Adding roles is just data.

**Comment by Jegelewicz** [comment]
Cool,

So - can you do this pretty easily?

> The form could be rebuilt to handle more agents.

And I'd like to update the definitions for these terms:


TRANS_AGENT_ROLE | Documentation
-- | --
contact agent |  Any person who may be contacted about the transaction. Use this to supplement in-house and outside contacts, not instead of those. Multiple contact agents are allowed.
in-house contact | Person within the institution to contact about the transaction. Only one in-house contact is allowed. If you want to add contacts, please use the "contact agent" role.
notification contact | Agent to which notifications are sent when a loan is approaching its due date. Multiple notification agents are allowed, but be advised that notification contacts all will receive notifications.
outside contact | Person from outside the institution to contact about the transaction. Only one outside contact is allowed. If you want to add contacts, please use the "contact agent" role.

Are those statements true?

**Comment by dustymc** [comment]
>easily

There's nothing overly difficult about it, but it's still a couple days of work. MAYBE I could add a set number of static agents without too much revamping, I'd have to look at the code to tell, but your comments re registrars make me think that's not the right approach here. I'll go next task, needs prioritized.

Loan notifications are sent to  ('collection contact agent','in-house contact','authorized by','notification contact')

but Arctos only emails active operators.

**Comment by Jegelewicz** [comment]
It really would be nice to just "add a row", but if that's overly-complicated, then having a place to add five agents would be an improvement and I think would eliminate a lot of clicking for anyone entering an accession.

**Comment by ewommack** [comment]
Does the new definition of:

notification contact | Agent to which notifications are sent when a loan is approaching its due date. Multiple notification agents are allowed, but be advised that notification contacts all will receive notifications.
-- | --


mean that we have to put agents in multiple times in order for them to get the notifications? Would an agent in the field Contact Agent get the same notifications?

**Comment by Jegelewicz** [comment]
TRANS_AGENT_ROLE | Documentation
-- | --
contact agent |  Any person who may be contacted about the transaction. Use this to supplement in-house and outside contacts, not instead of those. Agents in this role will not receive any automated notifications from Arctos. Multiple contact agents are allowed.
in-house contact | Person within the institution to contact about the transaction. Only one in-house contact is allowed. If you want to include additional contacts, please use the "contact agent" role.
notification contact | Agent to which notifications are sent when a loan is approaching its due date. Multiple notification agents are allowed, but be advised that notification contacts all will receive notifications.
outside contact | Person from outside the institution to contact about the transaction. Only one outside contact is allowed. If you want to add contacts, please use the "contact agent" role.

> mean that we have to put agents in multiple times in order for them to get the notifications? Would an agent in the field Contact Agent get the same notifications?

I changed the definition of contact agent a bit - however, I still do not know if that definition is true. @dustymc will have to weigh in there. I am also not sure what, if any, automated notifications in-house or outside contacts receive from Arctos.

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/2948#issuecomment-662468198

**Comment by Jegelewicz** [comment]
> Loan notifications are sent to ('collection contact agent','in-house contact','authorized by','notification contact')

Is "collection contact agent" = "contact agent" in the code table? Because there is no "collection contact agent" in the code table.

**Comment by dustymc** [comment]
Ah sorry no that's from digging around in the collection's contacts for overdue loans. ONly

,'in-house contact','authorized by','notification contact'

come from the transaction

**Comment by Jegelewicz** [comment]
> ,'in-house contact','authorized by','notification contact'
> 
> come from the transaction

do those roles DO anything in Arctos?

**Comment by dustymc** [comment]
They're the only roles that DO anything - they direct email!

**Comment by lin-fred** [comment]
Is there anyway to link to the definition table for those agent types from the Accession Detail page? Maybe next to role? Have a "define" hyperlink?

**Comment by campmlc** [comment]
Agree on the hyperlinks. Did I miss the discussion of adding more
notification contacts? Will the other contacts also receive emails if they
are Arctos operators?
This relates to a previous discussion about loan notifications as well.
I'll try to track that down.

**Comment by Jegelewicz** [comment]
So based on that - do these role definitions make sense?

TRANS_AGENT_ROLE | Documentation
-- | --
contact agent |  Any person who may be contacted about the transaction. Use this to supplement in-house and outside contacts, not instead of those. Agents in this role will not receive any automated notifications from Arctos. Multiple contact agents are allowed.
in-house contact | Person within the institution who will receive email notifications from Arctos about the transaction. Only one in-house contact is allowed. If you want to include additional contacts, please use the "contact agent" role.
notification contact | Agent to which notifications are sent when a loan is approaching its due date. Multiple notification agents are allowed, but be advised that notification contacts all will receive notifications.
outside contact | Person from outside the institution who will receive email notifications from Arctos about the transaction. Only one outside contact is allowed. If you want to add contacts, please use the "contact agent" role.

**Comment by campmlc** [comment]
Can we add a way to choose whether or not the additional contacts should be
added to email notifications? Is there a reason to restrict the number of
people who can receive these notifications?

**Comment by dustymc** [comment]
>outside contact ... who will receive email  notifications 

no

>choose whether or not the additional contacts should be added to email notifications? 

That's why we have contact agent and notification contact.

>restrict the number of people who can receive

no

**Comment by campmlc** [comment]
Then I don't understand Teresa's definition for contact agent, which
says " Agents
in this role will not receive any automated notifications from Arctos".
I would like to have the option of more than one Arctos contact,
notification or otherwise, designated to receive automated notifications.

**Comment by Jegelewicz** [comment]
TRANS_AGENT_ROLE | Documentation
-- | --
contact agent |  Any person who may be contacted about the transaction. Use this to supplement in-house and outside contacts, not instead of those. Agents in this role will not receive any automated notifications from Arctos. Multiple contact agents are allowed.
in-house contact | Person within the institution who will receive email notifications from Arctos about the transaction. Only one in-house contact is allowed. If you want to include additional contacts, please use the "contact agent" role.
notification contact | Agent to which notifications are sent when a loan is approaching its due date. Multiple notification agents are allowed, but be advised that notification contacts all will receive notifications.
outside contact | Person from outside the institution to contact about the transaction. Only one outside contact is allowed. If you want to add contacts, please use the "contact agent" role.

**Comment by Jegelewicz** [comment]
> Then I don't understand Teresa's definition for contact agent, which
> says " Agents in this role will not receive any automated notifications from Arctos".

per https://github.com/ArctosDB/arctos/issues/2948#issuecomment-663092943

> 'in-house contact','authorized by','notification contact' - They're the only roles that DO anything - they direct email!

So I assume that "contact agent" does nothing....

**Comment by lin-fred** [comment]
Contact agent seems to be there for when you want to have someone associated with the transaction, but not get sent notifications  of the loan/accession.

**Comment by ewommack** [comment]
Would a Contact Agent by a professor who is associated with the project, but isn't involved directly with the loan?

**Comment by Jegelewicz** [comment]
> Would a Contact Agent by a professor who is associated with the project, but isn't involved directly with the loan?

Seems like this is confounding project roles with transaction roles? Seems like that professor should be added to the project, but not to the loan?

**Comment by ewommack** [comment]
> Seems like this is confounding project roles with transaction roles? Seems like that professor should be added to the project, but not to the loan?

I was thinking of the professor as in someone you had contacted and discussed the loan with, but not someone directly involved. 

So what would be an example of a Contact Agent? I'm trying to figure out where we would use that. The term kind of sounds like the one I would first pick by the name (Contact Agent -> the Agent I contact), but it seems like it is more specialized than the person to contact for the transaction.

**Comment by lin-fred** [comment]
> So what would be an example of a Contact Agent? I'm trying to figure out where we would use that. The term kind of sounds like the one I would first pick by the name (Contact Agent -> the Agent I contact), but it seems like it is more specialized than the person to contact for the transaction.

I think I see where this was going, as the Notification agent would be the one that receives Arctos notifications, but the Contact Agent would be the one that you could physically contact about loan details, but I think this meaning gets lost as they are synonymous with each other (in the sense of the words contact and notify).

I think Contact Agent should be named something else. As what? I don't know, I've been thinking on it. Contact Agent is someone that you want involved with the loan, but to not get notifications. This could be students/professors, but as Teresa said, why not just have them in the project? So why have a contact agent at all?

I think having the student/professor in the loan instead the project is important though, as many people could be in the project, and there could be many loans for one project, but each person could only be actually associated with specific loans.

But at that point do you make more projects instead? And then nestle small individual projects under the larger project? Or do we just leave it, and call Contact Agent something else and let people have the flexibility of having many projects or have agents involved in the loans.

**Comment by campmlc** [comment]
I still am not clear on what we are doing here with the contact vs
notification agents. I already find the limitation on the number of
contacts problematic in dealing with loans, in order to document
students, professors, and even external sources such as the person in the
genome lab who will actually be receiving the samples. This info needs to
be in the loan form, not in the project page. And I need to be able to have
more than one person receive automated notifications. Is that going to be
fixed here?

**Comment by Jegelewicz** [comment]
> So what would be an example of a Contact Agent? I'm trying to figure out where we would use that. 

Anyone associated with the transaction (in the case of this issue we are looking at Accessions) who isn't THE in-house, or outside contact. So that professor would have that role (IMO).

**Comment by Jegelewicz** [comment]
> I think Contact Agent should be named something else. As what? 

associated contact - Anyone associated with the transaction who isn't the in-house, outside, or notification contact.

**Comment by Jegelewicz** [comment]
> But at that point do you make more projects instead? 

YES - every loan should be associated with its own project (IMO) to better track what happens to stuff. Projects can be nested OR loans can be associated with multiple projects.

**Comment by Jegelewicz** [comment]
> And I need to be able to have more than one person receive automated notifications. Is that going to be fixed here?

Nope - I think that needs it's own issue. This issue is about clarifying the definitions for Accession details, including definitions of the code table terms for transaction agents.

**Comment by dustymc** [comment]
Loans are basic curatorial stuff, projects DO STUFF with transaction data including loans. I shouldn't have to go to projects to figure out where your specimens are or who might be able to send them back, and loans can't do cross-transaction magic. If that distinction looks fuzzy, then we probably need better documentation!

There's no real "this is a project" cutoff. One for each loan works, but is a extra work for cluttered data. One per grad student or funded project (particularly those that collect) is less work, more natural to share across collections, and probably just closer to what everyone wants.

There's no limitation on the number of agent-in-role except for the two "primary" contacts which are designed around loan forms, and there never has been.

**Comment by campmlc** [comment]
"One per grad student or funded project (particularly those that collect)
is less work, more natural to share across collections, and probably just
closer to what everyone wants."
This is how I use projects associated with loans and find it an extremely
useful approach. It sometimes requires asking the grad student which of
their funded projects a particular loan will be used for.

**Comment by dustymc** [comment]
merged/rebuilt form in test
