### ISSUE TITLE
Saved Search Link Broken(ish)

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#2957]
Saved search link is funky.

When I save a search and paste the link (https://arctos.database.museum/saved/oMesoPubs) in my browser, a very brief screen flashes that redirects the link to bring up the correct records:

![image](https://user-images.githubusercontent.com/11336485/88319817-ea5aa500-ccd9-11ea-9b74-e20ace36e366.png)

However, when I paste the full URL or hyperlink my saved search in a document, this redirect process does not happen and I instead receive this message:

![image](https://user-images.githubusercontent.com/11336485/88319251-22151d00-ccd9-11ea-89cc-a7e1a41b2e10.png)

I'm not sure if there is anything to be done on Arctos side (?) but wanted to bring up the issue just in case. I'm not sure if this is a new PG issue or the way things have always been.

**Comment by dustymc** [comment]
This is best dealt with as part of https://github.com/ArctosDB/internal/issues/64; I'm not sure why tomcat is pushing headers directly to the client instead of just returning them to lucee's handler.

**Comment by AJLinn** [comment]
Something else is going wrong with saved searches... just created this one: 
https://arctos.database.museum/saved/MtMcKinleyPlaceSettings

Normally I can go immediately and open it. Now I get this:
<img width="1574" alt="Screen Shot 2020-07-29 at 2 04 09 PM" src="https://user-images.githubusercontent.com/17605945/88858474-7ec67b00-d1a4-11ea-9f5a-ee7900bc3b6f.png">

HELP! I reaaaaalllly need to be able to do these searches and send them to users! What did I do wrong? "Invalid call of the function... Invalid string list" ?

**Comment by dustymc** [comment]
@AJLinn that's fixed thx

**Comment by AJLinn** [comment]
thanks!

**Comment by AJLinn** [comment]
Another one not working - getting another 404.
https://arctos.database.museum/saved/Loan202020EH
What is happening with my saved searches?

**Comment by dustymc** [comment]
That search joins to loan, which is an internal table not visible to public users. You could archive those records and share that, use a project to share, or we could talk about public having select on "internal" tables. (I'm not 100% sure it's always worked that way, I don't think it could actually expose loan data, but this setup still makes the most sense to me from a security standpoint.)

**Comment by Jegelewicz** [comment]
> public having select on "internal" tables

Possible for access to loan records (the search results) but not loan details (loan metadata or whatever we want to call it)?

Or a way to convert this to just a list of stuff so it is no longer associated with the loan (even though that's how you created the list). My first thought here was to just do a new search with comma separated list of all the stuff in the loan, but that is a bunch of steps to take....

**Comment by dustymc** [comment]
> access to loan records (the search results) but not loan details 

Possible, yes. Also more risk than what we're doing now.

>convert this to just a list 

That's what Archives are.

**Comment by AJLinn** [comment]
For now, I'll convert this to an archive. I wonder why it's only now happening - I have, for several years now, been doing this exact same process and have never had anyone have a problem accessing the list. Do you think it makes a difference if I create the list from the loan environment vs creating the list from the results of a search using the loan number as the search criteria?

I certainly don't want to open us up to security but I also don't want to have to do a bunch more steps in order to share a list of records that I find on behalf of a research request. If making a Project is the recommended way to do this, I can also start adjusting my workflow, given that doesn't add a huge amount of work and has some other potential benefits (one of them being a public way to see how much our collection is being used for research. Is that how others are using Projects?

**Comment by dustymc** [comment]
>why it's only now happening

I'd guess because we built the entire VP for postgres - not much was "importable" from Oracle - and I think we probably have slightly tighter control on this now. Looks a bit like an improvement to me, but I'm still completely open to the idea that public users need to search by loan numbers (and associated data).

>how others are using Projects

Projects get stretched in all sorts of strange ways, but "public transactions" is the core of the design.

**Comment by Jegelewicz** [comment]
> (one of them being a public way to see how much our collection is being used for research). Is that how others are using Projects?

That's definitely one of the reasons I use projects!

**Comment by dustymc** [comment]
I figured out how to deal with this in CF - /saved/... should be responding with a 200 in next release.
