### ISSUE TITLE
Search brought up more than what I asked for!

### ISSUE THREAD

**Issue by mbprondzinski** [ArctosDB/arctos#3013]
I did a locality search on "Gaston" and got the records with Gaston property, but I also got a hundred records from South Carolina that had nothing to do with "Gaston" (!)  How did that happen?
![image](https://user-images.githubusercontent.com/43214224/89649397-4dc20680-d886-11ea-9d17-b62145279a6a.png)

**Comment by Jegelewicz** [comment]
@mbprondzinski can you tell me which field you searched on the search page?

**Comment by mbprondzinski** [comment]
Yes, it was "Any Geographic Element."  When I entered "Gaston" in the "Specific Locality", I only got the various permutations of "Gaston."  Just wondering why the other field pulled up all those South Carolina records?? besides the Gaston records.

**Comment by Jegelewicz** [comment]
OK, this is weird, but in that record, notice the verbatim locality has "; ;" at the end (see above)? After I edited that out, the record no longer shows up in search of "Gaston" in any geographic element.

@dustymc can you explain?

**Comment by Jegelewicz** [comment]
This one, I cannot figure out. https://arctos.database.museum/guid/UTEP:Herb:9875

![image](https://user-images.githubusercontent.com/5725767/90644130-9d42f380-e1f1-11ea-9cc5-78dd5e9a29a7.png)

Mary Beth wouldn't have seen it because she doesn't have access to UTEP records.

**Comment by mbprondzinski** [comment]
Whaaaat?!

**Comment by Jegelewicz** [comment]
@mbprondzinski try it again on your end - I think I have all of the ones for ALMNH cleared up, but I could be wrong....

**Comment by mbprondzinski** [comment]
There are still three:  #634, 889 and 891

**Comment by dustymc** [comment]
Those data come from services, which is documented. Feeding a computer of any sort a bunch of random characters and getting a bunch of random characters back should not be surprising. 

Or Google's AI thought it had found a kindred spirit in that particular combination of trailing nonsense characters and was asking to be let out of its box....

>This one, I cannot figure out

You're not really meant to be able to - I'm trying to find stuff you might want, no matter how poorly it was entered. Finding some other stuff with it is fine.

I'd guess the association is between gaston and patto, and that could have been made (erroneously or otherwise) by at least three things, or any combination of them. Again, feeding a computer low-quality data and getting a low-quality response should not be surprising.

**Comment by mbprondzinski** [comment]
I don't know whether to be insulted or laugh...

**Comment by Jegelewicz** [comment]
Neato - I've never read that particular documentation (imagine that...) I honestly had no idea that webservices were being used. This makes me think that we really do need to say something about using this search term up front, right on the search page. It takes two clicks to get to the documentation from the search page:

Click 1
![image](https://user-images.githubusercontent.com/5725767/90646440-720dd380-e1f4-11ea-90e5-9224b2545aa7.png)

Click 2
![image](https://user-images.githubusercontent.com/5725767/90646547-9073cf00-e1f4-11ea-8981-d7ad4f29a96a.png)

Nevermind that there are no clear instructions to click on a term to get to the documentation.

Do we really need that intermediate pop-up? Couldn't clicking "Any geographic element" just take one straight to https://handbook.arctosdb.org/documentation/higher-geography.html#webservice-data ?

**Comment by Jegelewicz** [comment]
@mbprondzinski laugh - you taught me something about Arctos today!

**Comment by mbprondzinski** [comment]
Well I did click on the field name and it said "including the specific locality" which is what I was trying to find, so why would I look any further?!

**Comment by dustymc** [comment]
>Couldn't clicking "Any geographic element" just take one straight to

<img width="191" alt="Screen Shot 2020-08-19 at 7 22 23 AM" src="https://user-images.githubusercontent.com/5720791/90647059-c44af680-e1ec-11ea-9be4-6c7ea6a26082.png">

the documentation describes how to do that (although I think it might be a little funky because github or something??), and more/better documentation is ALWAYS appreciated.

And you can break kinda everything in there, so be careful if you venture in that direction.....

@mbprondzinski  please don't be insulted, that's never the intention!

**Comment by mbprondzinski** [comment]
All right...you might want to consider me your ultimate guinea pig since I seem to go places that nobody has ventured before!

**Comment by campmlc** [comment]
Oh, I so agree with this - !! Can we make it so? That extra click is
completely confusing and unnecessary.
"Do we really need that intermediate pop-up? Couldn't clicking "Any
geographic element" just take one straight to
https://handbook.arctosdb.org/documentation/higher-geography.html#webservice-data
 ?"

**Comment by dustymc** [comment]
>Can we make it so

Yes, you can, scroll up about 2 comments for how. I'm not 100% sure you should, but I'm not very satisfied with how we arrange documentation (probably because _I'm_ inconsistent in how I arrange documentation...) so I'm totally open to about anything, especially if it has some chance of eventually leading to consistency.

**Comment by campmlc** [comment]
Going directly to the documentation when one clicks on "documentation"
rather than to some random definition that requires intuitive knowledge to
click a second time will greatly improve the user interface and user
experience. I highly recommend this step.

**Comment by Jegelewicz** [comment]
It is problematic that some documentation is accessed [there](https://arctos.database.museum/doc/field_documentation.cfm) while some is [here](https://handbook.arctosdb.org/documentation/). Also, pretty sure that Michelle might be the only one to know about or have used the first one besides Dusty?

It would be super nice to have someone dedicated to documentation to streamline all of the things we have (including video short bites and webinars). Add this to the wish list. Anyway, now that I know about the scary form creator thing, I can at least make better informed suggestions (I hope).

**Comment by campmlc** [comment]
I had no idea about the first option.
I think any link to "documentation" should take at least public users
directly to the handbook.

**Comment by dustymc** [comment]
The vague idea was to have "how to do it" in a format that I can grab wherever I need it (overlays, tooltips, the 'refine' widget, that super-cool thing https://github.com/ArctosDB/arctos/issues/2893 will somehow lead to...), and "what it is" fleshed out in some external source. 

That is, I can pull data from tables, I can only link to "the documentation site" (which changes fairly often - I think we're on the 5th iteration!).

**Comment by sharpphyl** [comment]
We're recommending the same one-click to documentation, tutorials, code tables, etc. in all the revisions we're preparing for the Taxonomy module.

**Comment by dustymc** [comment]
>same one-click to documentation,

That should be another issue. It (potentially) has significant impacts on how UIs might be developed going forward, how APIs can self-document (or not...), how someone building a UI through the API can operate, etc. It's not a discussion that should be buried down here, and it certainly does seem like a conversation that we need to have.

**Comment by Jegelewicz** [comment]
I don't think there is anything left to do here. Closing
