### ISSUE TITLE
Select by collection type

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#3027]
You know what would be cool? If we could search on all Herp collections or all Art and Cultural Collections in the main search page. Right now we can select all the collections from an institution but it's harder to go through all the institutions and select all similar collections. 

Might require an alternative search page for records so please consider if anyone is building one!

**Comment by campmlc** [comment]
Yes, I like this idea. Especially for herps - since you can't just pick a
single taxonomic class!

**Comment by dustymc** [comment]
Blocked by https://github.com/ArctosDB/arctos/issues/1662

**Comment by ewommack** [comment]
Ah standardizing collections types (or collection types names). I can see how that would make searching even more difficult until we get that together. Should I put it on the next AWG Agenda?

**Comment by dustymc** [comment]
>Agenda

Sure - and we should identify or add whatever's meant by "collection type" if it's not that while we're in there.

>herps

Those are found in at least herp, reptile, amphibian, teaching, and paleo collections (and probably a bunch more). This could lead to less discoverability rather than more unless it's approached very carefully. (And maybe then too!)

**Comment by ewommack** [comment]
Maybe we also need a conversation about what types of searches we are thinking we want to tackle with this new potential feature? 

`Those are found in at least herp, reptile, amphibian, teaching, and paleo collections (and probably a bunch more). This could lead to less discoverability rather than more unless it's approached very carefully. (And maybe then too!)`
That's a really good point, and the same could be of birds, mammals, insects, etc. And what about the pieces found in cultural collections that use specific types of material?

Maybe in addition to clarifying the types of collections, and we should also constructing a collection tree that shows all of the different connections between them to understand what a straight up search across all collections that have certain types of material would look like.

**Comment by Jegelewicz** [comment]
Maybe we need to eliminate "and" collection types and instead allow selection of multiple types from a standardized list. And maybe we are just trying to hard to standardize EVERYTHING.

**Comment by dustymc** [comment]
>trying to hard to standardize EVERYTHING.

Maybe. We're definitely trying too hard to stuff everything into pigeonholes; "collection type" almost certainly does not mean what users think it means. If I limit my search to "herp" collections as @campmlc suggests above, then I'll never find https://arctos.database.museum/guid/MSB:Mamm:283723 (or the paleo dna in cultural collections, worked Hydrodamalis bone in mammal collections, art in bird collections, etc., etc., etc.). I can't think of a single reason - other that some weirdly ingrained idea that I want snakes so I need to only search herp collections - that I'd want to avoid that material. I can think of lots of reasons I'd want to discover unexpected but relevant material, even if it's cataloged in the "wrong" collection due to some arbitrary and administrative historical event. (So maybe the arbitrary and administrative data shouldn't be the first thing users encounter on the search page?)

**Comment by Jegelewicz** [comment]
Wouldn't it be better for these kinds of broad searches to create some saved searches and just present them on a separate page:

Find all Reptiles (class=Reptilia)
Find all Mammals (class=Mammalia)
Find all Herps (class =Amphibia, Reptilia)

and so on. I could see something like this being useful for K-12 and maybe even as a first pass for researchers. Of course, there is the issue of names without classifications, but I don't think we can fix that by saying that everything in MSB:Mamm is a mammal.

**Comment by campmlc** [comment]
Agree that if we want users to find hero's, maybe we should simplify the
public search to taxon and geography, with other fields showing up on
advanced search, including collection type related info.Also,but would be
good to be able to add multiple collection types as code tables to a
collection. Maybe the code tables show be controlled by the taxon entered,
and not by a predetermined collection type?

**Comment by Jegelewicz** [comment]
> Maybe the code tables show be controlled by the taxon entered, and not by a predetermined collection type?

What happens here?
https://arctos.database.museum/guid/MSB:Mamm:283723

**Comment by campmlc** [comment]
That's what I mean. If the sci name entered in data entry is a herp, then
the attributes that should show up in data entry should be herp attributes,
regardless of what collection type it is being entered in. That is what all
this is for, correct? To determine what code tables are associated with the
attributes etc for a given collection? Do we really even need all that
distinction?

**Comment by dustymc** [comment]
>Find all Reptiles (class=Reptilia)

https://arctos.database.museum/guid/UTEP:Herp:738 has no class (and it's not a reptile, but it was on top of the pile...); our taxonomy isn't more predictable than our arbitrary admin data.

>and geography,

That's even worse!

>controlled by the taxon entered

That'd be pretty cool if we had the data to support it. We'd need a whole bunch more processors to deal with the "you can't change this, it's linked to some code tables through taxonomy" errors, and probably some more people to get/keep the data in a state capable of supporting that sort of thing. Neat, but I don't think realistic.

>multiple collection types as code tables

I've been tossing around the idea of going essentially the other way for a while, but haven't quite worked out the kinks enough to propose anything. We'd have "thing" in the CT once (rather than once per collection type, plus a bunch of complicated nonsense to keep the documentation synced), and an individual collection could "subscribe" to use it, or something of the sort. That would make setting up collections a bit more complex, but also allow "Herp and Fish" collections to exist without any code-table compromises (including not having to see marlin attributes if they only deal in pupfish), and would mean we could entirely eliminate collection_cde.

>That is what all this is for, correct? 

Yea probably subconsciously, but the only thing we've really discussed is "I'm cataloging mammals so don't show me turtle-stuff."

**Comment by Jegelewicz** [comment]
> 
> 
>     That is what all this is for, correct?
> 
> Yea probably subconsciously, but the only thing we've really discussed is "I'm cataloging mammals so don't show me turtle-stuff."

Is that what "this" is for? We have two ways of saying this which creates confusion. I select something from this table https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcollection_cde then I also have to select something from this new table we are discussing in #1662. Which one does what and why?

**Comment by dustymc** [comment]
>Which one does what a

https://handbook.arctosdb.org/documentation/catalog.html#collection-code

1662 runs the 'filter by collection' search widget

**Comment by Jegelewicz** [comment]
Right. So it seems important for THAT to be standardized, but the other not so much.

As for

> If the sci name entered in data entry is a herp, then the attributes that should show up in data entry should be herp attributes,
> regardless of what collection type it is being entered in.

That seems a lot more complicated than the system we have now.

> but haven't quite worked out the kinks enough to propose anything. We'd have "thing" in the CT once (rather than once per collection type, plus a bunch of complicated nonsense to keep the documentation synced), and an individual collection could "subscribe" to use it, or something of the sort. That would make setting up collections a bit more complex, but also allow "Herp and Fish" collections to exist without any code-table compromises (including not having to see marlin attributes if they only deal in pupfish), and would mean we could entirely eliminate collection_cde.

Could allowing multiple collection_cde for any given collection be a thing? Of course that means adding the collection code for herps to MSB:Mamm just to facilitate a single herp and all of those attributes and parts will be available to all of the students entering data for mammals. Maybe something like the dynamic taxonomy? Order your collection_cde choices and you can only access the ones after the first in data entry by some sort of acknowledgement that you know what you are doing or you have manage collection or something like that?

**Comment by dustymc** [comment]
>Could allowing multiple collection_cde for any given collection be a thing? 

Yes, but it wouldn't deal with some low-level chronic problems (like the complexity in synchronizing denormalized authorities), and it would be about the opposite of the potential "fish, but not those kinds of fish" functionality.

>only access the ones after the first in data entry by some sort of acknowledgement 

Relatively few records go through an interactive UI, and I see anything that requires an interactive UI as completely fatal.
