### ISSUE TITLE
Advice - Agent "Living Trust"

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#3030]
I'm looking for advice regarding an agent which is a "Living Trust" (https://arctos.database.museum/agents.cfm?agent_id=21330438) set up to manage the estate of agent Robin Morris (https://arctos.database.museum/agents.cfm?agent_id=21330439) who died last year and had herself inherited a collection of items formerly owned by her step-mother, Jean Bunnell Kennedy (https://arctos.database.museum/agents.cfm?agent_id=21279829) daughter of the first president of the University of Alaska. (WHEW!)

I'm wondering what people think about making the Trust an organization, then creating relationships between Robin Morris and Jean Bunnell Kennedy. The only relationship that seemed appropriate was "associate of". 

Wondering what others might have done in my place given the same situation... or do you think this is a reasonable way to express the relationships between the various agents? I also made the "parent of" relationship for Kennedy to Morris, and indicated it was a step-parent in the remarks.

**Comment by AJLinn** [comment]
Or should this be a group with those various people listed as members of the group?

**Comment by dustymc** [comment]
>making the Trust an organization

Seems correct.

>The only relationship that seemed appropriate 

I think there's some constant friction (here and many other places) between a few general terms and potentially very many specific terms. Can you imagine a semi-realistic situation where you NEED "third cousin twice removed on mother's side" and can't get it by performing a more general search ("associate" maybe) and digging through the results (or something similar)? If so, maybe we need that as vocabulary. If not, having fewer terms (probably!) generally makes things easier to deal with and more discoverable.

>group

I think it's had some evolutionary pressure, but the origins of group agents are mostly in expanding cryptic things that get scribbled and printed on labels into Agents, and so that a search for "That Agent" will find things collected by "ABCD" where That Agent is "C" for some cryptic reason. I would not use groups for your use case, particularly now that relationships have a time component (so you can effectively say "managed the trust from Monday to Wednesday").

**Comment by AJLinn** [comment]
Coolio. Thanks. Just wanted to talk out my rationale - I don't know that I've ever used the group agent so wanted to be sure I was using organization in an appropriate way. I love the time component and remarks for the relationships - will really help clarify our corporate agents to better document the ownership and name changes over time.

**Comment by mkoo** [comment]
Good use case. thanks for sharing and this makes sense.
