### ISSUE TITLE
Search Taxonomy Changes required to accomodate non-Linnean terms

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3036]
Currently our "Search Taxonomy" page is written for Linnean taxonomy.

![image](https://user-images.githubusercontent.com/5725767/90785787-fe38fd00-e2bf-11ea-9404-4f4e67ac89d9.png)

I see two possible ways to make this form useful for other types of collections:

1. De-taxon the form to make it more generic

2. Customize the form for other collection types (Have separate search pages for Linnean, mineral and cultural collections).

Personally, I prefer the first, but am not sure how to generalize and still make sure everyone knows what is going on. What terms would best replace "Taxonomy" and "Taxon"?

**Comment by Jegelewicz** [comment]
Note, this will also have implications on the main search page.

**Comment by dustymc** [comment]
>replace "Taxonomy"

Mineral (or whatever else we might end up with) taxonomy is still taxonomy, no?

**Comment by Jegelewicz** [comment]
> taxonomy is still taxonomy, no?

For you and me - yeah, but I expect that art and cultural public searchers might find the terms confusing? Would an art historian looking for paintings really search for a taxon name?

**Comment by sharpphyl** [comment]
According to Wikipedia "Taxonomy (general) is the practice and science of classification of things or concepts, including the principles that underlie such classification." https://en.wikipedia.org/wiki/Taxonomy

It goes on to list many different types of taxonomy.  Linnean taxonomy is one biological system. 

So I think we could appropriately leave in the word Taxonomy as the general descriptor at the highest level and add a field for Name Type (or, preferably, Taxonomy Type).  This would add mineral and cultural to biological/Linnean as taxonomy types.

I do question having quarantine as a name (taxonomy) type since it applies to all types of taxonomy.  It seems to be a name (formerly taxon) status, not a type.  It's a historic name not used in identifications.  Can we rethink that one?   

We might want to add a general descriptor of taxonomy at the very top of this screen to describe how it is inclusive of all three types. (Yes, I'm happy to draft something.)

At lower levels, I agree that Taxon Name would be more inclusive if it said just Name.  That's what we're proposing for the primary name description page in issue #2695 . 

Instead of Taxon Term, we might say Name Classification and Metadata which is what's in the description.  

Term Type(s) may be ok as is though it's a bit vague.  Source and Common Name are fine.

Should we develop a draft, @Jegelewicz and add it to the others in our UI google docs?

**Comment by dustymc** [comment]
>It seems to be a name (formerly taxon) status, not a type. 

It's neither. Anything that's actually taxonomy should almost certainly never be quarantined. "We don't like it this week" is an opinion/hypothesis, not a reason to quarantine - somewhere out there should be a type, we can't declare it with a quarantined name. "Someone can't spell, that caught on and got used a lot, still ain't actually taxonomy, should never be used in identifications, but is useful for finding stuff" is reason to isolate. 

"Quarantine" is appropriate in the sense that it's an enforced isolation, but maybe not so much in the sense that it should be permanent (unless someone creates a new taxa using a formerly-not-taxon name, which seems more or less inevitable, I suppose...). If we're going to come up with a new term we should do so now; it's a functional term, changing it requires updating some code, it'll probably require more tomorrow than it does today.

**Comment by Jegelewicz** [comment]
@sharpphyl a draft would be AMAZING.

**Comment by sharpphyl** [comment]
Just to confirm with both of you:

@dustymc and @Jegelewicz    A name in "quarantine" is one that has been misspelled (or a similar error) in publications (not just in Arctos) and should not be used for identifications.  There must be a link to a synonym so that a search will lead the correct spelling.  Setting its type to "quarantine" makes it unuseable in identifications.  The type can be changed by anyone with taxonomic authority who wants to use the name in an identification.

Names that have been misspelled in Arctos should be deleted, unless they pass the Google test (and we're not breathing our own exhaust).

**Comment by sharpphyl** [comment]
@Jegelewicz  and @dustymc 

Here's a link to draft ideas for the Taxonomy Search Page and the Taxonomy Type Code Table.

https://drive.google.com/drive/folders/1gQdI-qWCDFAe6yJSkWkUKlXLAX5KYwLp

**Comment by Jegelewicz** [comment]
I think this is good to go now. Closing.
