### ISSUE TITLE
postgrestification of containerization

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3066]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
Previous Oracle restrictions on permissions in object tracking to prevent one collection from moving another collections object appear to have failed in PG. My student just scanned two NK numbers on cryovials in as barcodes into an MSB freezer box; since the MSB NK series overlaps with the UAM barcode series, this has scanned two UAM barcodes into MSB positions.
Furthermore, the "history" function does not show that these barcodes were ever UAM - they only show that these are now MSB. Perhaps the UAM barcode series is not appropriately claimed for UAM in PG?

**To Reproduce**
1. Go to Find container
2. Enter freezer box barcode DGR10434
3. go to positions
4.  see barcodes 295329 and 295311  incorrectly scanned in positions 40 and 50.

**Expected behavior**
Students or anyone without permissions should not be able to alter the object tracking positions of other collections.

Priority: High

![Screenshot 2020-08-31 17 55 01](https://user-images.githubusercontent.com/14808196/91780331-7d79db00-ebb4-11ea-8a66-770efbb56bc6.png)
![Screenshot 2020-08-31 17 55 06](https://user-images.githubusercontent.com/14808196/91780336-82d72580-ebb4-11ea-83a0-208568b550cc.png)

**Comment by dustymc** [comment]
Thanks, UAM parts are back where they came from, I'll drop everything and rebuild the controls ASAP.

**Comment by dustymc** [comment]
There's a different approach to this in test. Everything should look and work the same as always, but the rules are more integrated, closer to the data, and hopefully easier to manage. It needs testing.

/remind me to push this to production in a week, if nobody manages to break it.

**Comment by campmlc** [comment]
@campmlc test  /remind for Sep 5 2020

**Comment by dustymc** [comment]
This is in production, but running parallel with the old code.

/remind me to check back in a week

**Comment by dustymc** [comment]
Currently we have:

* PCID=0 (doesn't exist) as the default no-parent parent
* container_id cannot equal parent_container_id constraint (prevents the most obvious cases of infinite recursion)
* procedures holding everything together, because this setup prevents direct DB control

This issue has moved us towards a more procedureless model, which seems to work in PG and would be a lot easier to deal with if it continues to do so, BUT we can't get there without a container.parent_container_id fkey-->container.container_id relationship. Need to:

* alter parent_container_id to NULL
* set up the key
* deal with whatever code a possible NULL parent breaks, which is probably lots of things.

**Comment by dustymc** [comment]
added coalesce to barcode change to prevent nulls from coming and going
added additional check on position editing

**Comment by Jegelewicz** [comment]
Can this be closed?
