### ISSUE TITLE
locality access forms: part two

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#3099]
Ref: https://github.com/ArctosDB/arctos/issues/2916

This is Phase Two of the locality form rebuild. This should include

* things that were not implemented in the linked issue, and
* general changes to /place.cfm

---------------------

Add customization

Allow users to turn columns on and off. This should be fairly straightforward, can perhaps be integrated with customizing the search form. (Sections can be turned on/off, that probably needs finer-scaled control.)

---------------------
Do something clever with child data, locality and event attributes.

I have no idea what we could do, but users seem to a) want a tabular view, and b) struggle when complex data are smooshed into a tabular view.

---------------
Use this form for picks

Picks are still using one-off forms. This should be able to work there, but "add customization" is almost certainly a prerequisite - the "full" form can be very wide, especially in Events mode.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I'm ok if, for example, two formation determinations are smooshed into one cell, but the individual attribute types need to be separated.

**Comment by Jegelewicz** [comment]
Comment on the current datatable - scrolling includes the headers, so they get lost. Can we make the datatable it's own sub-window so that those column headers can remain in view when scrolling through results?

Also - NMMNH will really need https://github.com/ArctosDB/arctos/issues/2820#issuecomment-692827484

**Comment by Jegelewicz** [comment]
> Do something clever with child data, locality and event attributes.
> 
> I have no idea what we could do, but users seem to a) want a tabular view, and b) struggle when complex data are smooshed into a tabular view.

The "Expand Attributes" button doesn't do what I think most everyone will expect (put all of them into new columns). I realize this will make for an unwieldy table and that as you point out, multiple attributes of the same type are problematic. Not sure about smooshing attributes of the same "type" together - it seems like columnizing them with _1, _2, etc. would be a workable way to put them into a downloadable table. Not sure that would be helpful for anything else.


locality_name_1 | attribute_type_1 | attribute_value_1 | attribute_units_1 | attribute_determiner_1 | attribute_remark_1 | determination_method_1 | determined_date_1
-- | -- | -- | -- | -- | -- | -- | --

**Comment by Jegelewicz** [comment]
Alternatively, expand could just create a second "attribute" table with one extra column:

locality_ID | attribute_type_ | attribute_value_ | attribute_units_ | attribute_determiner_ | attribute_remark_ | determination_method_ | determined_date_
-- | -- | -- | -- | -- | -- | -- | --

This would allow sorting by any given attribute value and finding all of the localities that have it. BUT this means the locality ID will need to be in the first datatable as well so that things can be matched up.

**Comment by dustymc** [comment]
>_1, _2, etc.

That is "workable" in that it would produce theoretically-valid CSV, but it's not scalable - I doubt I have the processors to pull our current <=20 attributes out into ~140 columns, and attribute_remark_1286 (which would be one of about 10K columns) is just going to break everything it touches.

Keeping the normalization seems much more realistic from here, but that's how I natively see the world so I know I have a huge bias. In any case that seems much more technically feasible, if some form of it should turn out to be usable.

**Comment by acdoll** [comment]
Can a similar "starts with/is/contains/ends with" option be built into the specific locality? We often have just a city name for spec_locality and want to see what's already in Arctos to avoid creating duplicates. For example, searching for Tucson in specific locality, with county =  Pima County and state = Arizona, you get 760 results. But we only want to look at the ones where specific locality = "Tuscon", and nothing else. I'd hoped you could just use and equal sign like on the main search page, but that doesn't do it.

**Comment by dustymc** [comment]
> "starts with/is/contains/ends with" 

Not much technical problem, but that takes a fair bit of screen space. Would 

<img width="322" alt="Screen Shot 2020-09-15 at 2 56 25 PM" src="https://user-images.githubusercontent.com/5720791/93269355-a9c05a80-f763-11ea-824c-187576c2aff2.png">

do what you need in specloc?

**Comment by Jegelewicz** [comment]
That would do what I need in Locality Name!

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> Not sure about smooshing attributes of the same "type" together

Was mostly just offering that in case it was a more workable solution

> columnizing them with _1, _2

would be ideal

> I doubt I have the processors to pull our current <=20 attributes out

What makes the locality attributes more processor heavy than the many more specimen attributes that are available individually in the main catalog record search?

**Comment by Jegelewicz** [comment]
> What makes the locality attributes more processor heavy than the many more specimen attributes that are available individually in the main catalog record search?

True - and I assume that we are only talking about this level of detail when searching localities, not catalog records?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> True - and I assume that we are only talking about this level of detail when searching localities, not catalog records?

For now.

**Comment by Jegelewicz** [comment]
He he he....

**Comment by dustymc** [comment]
> locality attributes more processor heavy than the many more specimen attributes

We can't effectively support those either - there's an issue somewhere.

That would make a "column" ``formation`` (with perhaps 23574 formation determinations somehow stuffed inside), rather than having 23574 columns with attribute_n==>formation. I think I heard somewhere that's not what you want - you need to sort by individual determinations - but maybe I'm confused on that point.

When (not if... - "for now" is always right!) someone wants that in specimenresults, it would be multiplied by the number of localities.

I've been hearing from above that I should not do things that don't perform, and that's definitely a solid development strategy. I could slap some duct tape on this thing, and at some point it will probably stop performing adequately even if it does initially. I'd much rather find a more general/sustainable solution to wanting complex data, and also wanting it in a simple table. I don't think we're on a sustainable pathway right now, and at the very least I'd like to stop digging at this hole we're in.

This obviously needs focused discussion - perhaps it should be added to the top of every semi-appropriate agenda, and stay there until we as a community can come up with a workable solution. I obviously don't have any great ideas. I'm not even completely opposed to an attribute-like approach, but we should all understand what we're getting into.

**Comment by acdoll** [comment]
> do what you need in specloc?

Absolutely!

**Comment by sharpphyl** [comment]
The field that limits the search to localities used by a specific collection is not working as before.

This is a search for the specific locality Bacochibampo.  If I search for localities with the specific locality "used only by" DMNS:Inv (which is what I prefer to use so I don't mess with another collection's terrestrial localities), I get no results.

<img width="425" alt="Screen Shot 2020-09-19 at 8 53 02 AM" src="https://user-images.githubusercontent.com/15368365/93670065-93611a00-fa55-11ea-80ec-ac9c17f25cc3.png">

<img width="311" alt="Screen Shot 2020-09-19 at 8 54 55 AM" src="https://user-images.githubusercontent.com/15368365/93670100-cdcab700-fa55-11ea-8ca6-4206ecc6a878.png">

If I search for it "used by" DMNS:Inv, I get 29 entries

<img width="298" alt="Screen Shot 2020-09-19 at 8 57 12 AM" src="https://user-images.githubusercontent.com/15368365/93670134-226e3200-fa56-11ea-88eb-c3448284e2cc.png">

I know that DMNS:Inv has 29 catalog records with Bacochibampo in the specific locality.  What I'm getting is every one of those records, not the localities used by those 29 records.   

If I don't choose a collection, I get 7 records.  These are actually the 7 localities used only by DMNS:Inv, since no one else is using that specific locality, although it does appear in "locality remarks" of other collections.  In the past, this is what I would have gotten if I limited the search to "used only by" DMNS:Inv.

<img width="412" alt="Screen Shot 2020-09-19 at 9 04 55 AM" src="https://user-images.githubusercontent.com/15368365/93670241-3c5c4480-fa57-11ea-8541-27aa0b3b5138.png">

If, during data entry, I select "pick locality" with the identical request, I get the seven localities we use.

<img width="313" alt="Screen Shot 2020-09-19 at 9 08 09 AM" src="https://user-images.githubusercontent.com/15368365/93670319-d02e1080-fa57-11ea-92fc-913a1290348e.png">

<img width="418" alt="Screen Shot 2020-09-19 at 9 08 47 AM" src="https://user-images.githubusercontent.com/15368365/93670320-d2906a80-fa57-11ea-82e9-9bebf1eca215.png">

Note: 
The same series of searches for Island: Sanibel, Specific Locality: Lighthouse, return
"used only by DMNS" - 0
"used by DMNS" - 309 (which is the catalog records)
"not used by DMNS" = 0
no selection = 3 (which is the number of localities)

Can we make the new system work this way or is there a reason for the change?  
______________

Also, can you put the count of the responses right under the "show number of entries per page" so I don't have to scroll down to find out how many responses there are, then back up to change the number on the page.


<img width="173" alt="Screen Shot 2020-09-19 at 9 13 21 AM" src="https://user-images.githubusercontent.com/15368365/93670415-7548e900-fa58-11ea-8796-9026877540b2.png">


<img width="282" alt="Screen Shot 2020-09-19 at 9 13 15 AM" src="https://user-images.githubusercontent.com/15368365/93670411-737f2580-fa58-11ea-804a-7cdc6294ffe7.png">

______________________________________________________

A Typo

<img width="488" alt="Screen Shot 2020-09-18 at 12 59 38 PM" src="https://user-images.githubusercontent.com/15368365/93638203-20539700-f9b4-11ea-838c-4d36fc3deeb2.png">

____________________________________________

And is it possible to have the same option to "hide empty columns" as on the data entry bulkloader?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> I think I heard somewhere that's not what you want - you need to sort by individual determinations - but maybe I'm confused on that point.

Separate columns would be perfect, but putting all determinations of one attribute in a column would be more functional than what we have now.

Would leaving out the determination information make this more workable? Obviously that will create some problems (site found, matching multiple TRS, outdated determinations coming up without a remark) but again it would be better than what we have.

A results table that has:

**Formation**
Formation 1, Formation 2

may not be perfect, but is infinitely more functional than a JSON blob.

**Comment by Jegelewicz** [comment]
Messing around with some searches and here is something that would be useful.

I searched for:

Locality Nickname = NMMNH:Paleo:L-%
Site Found = Gary S. Morgan
landholder = US Bureau of Land Management

And get results = 423 localities

I can look at the catalog records for any ONE of those localities, but actually I am interested in ALL of the records from them. Possible to have a "See All Catalog Records" option?

**Comment by dustymc** [comment]
Remaining request could be addressed via https://github.com/ArctosDB/arctos/issues/3272#issuecomment-819691228, closing.
