### ISSUE TITLE
MSB Host Report Handlers needed

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3118]
Please provide updated handlers for the following reports:
MSB_Host_4dram_label (msb_host_4dram_label.cfr)            
msb_host_4dram_origID (msb_host_4dram_label_origID.cfr)  
@msbparasites

**Comment by dustymc** [comment]
Hu?

**Comment by campmlc** [comment]
Neither of these are working? We need to be able to pull in collector
number, original ID, and either NK  AF, IF, etc. with the conditional
language I requested earlier. I need help getting one of these forms
working so I can see an example of how to fix others in the same way. I
don't understand how the SQL fixes from the other github issues must be
inserted into the handler. Please provide a functional example.

**Comment by campmlc** [comment]
OK, looks like the first one is working only for MSB Host specimens. The
second one, the one we really need that has the identifier info, is not
working.

**Comment by campmlc** [comment]
Why do both of these handlers have
"concatsingleotherid(flat.collection_object_id,'UIMNH: University of
Illinois Museum of Natural History')"?
We don't need that. Is it necessary? What about NK, IF, AF, collector
number, and original identifier, which we do need?

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/3057#issuecomment-682168815

I added a comma and pasted that in to msb_host_4dram_origID, changed cataloged_item.... to flat... because you're not joining to cataloged_item, used the recipe in https://github.com/ArctosDB/arctos/issues/2729 to change the decode to case, search, print any, 

<img width="457" alt="Screen Shot 2020-09-18 at 10 13 14 AM" src="https://user-images.githubusercontent.com/5720791/93626245-0310cf80-f998-11ea-8b58-68128811f159.png">

<img width="141" alt="Screen Shot 2020-09-18 at 10 13 19 AM" src="https://user-images.githubusercontent.com/5720791/93626261-0c01a100-f998-11ea-81c3-d309af127cde.png">

<img width="264" alt="Screen Shot 2020-09-18 at 10 17 04 AM" src="https://user-images.githubusercontent.com/5720791/93626317-2176cb00-f998-11ea-9545-a9cd28e61756.png">

I also pulled 

 concatsingleotherid(flat.collection_object_id,'UIMNH: University of Illinois Museum of Natural History') user_id_num,
    'UIMNH' user_id_type,

out, if you don't need something you can just remove it.

**Comment by campmlc** [comment]
Yay! Thanks!!
