### ISSUE TITLE
Informal chronostratigraphy fail

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3134]
I have run across localities that should have informal chronostratigraphy but instead have Stage/Age = "informal chronostratigraphy", which is not an option in the Stage/Age code table so ends up blank when one of the localities is edited.

When I search localities with Stage/Age =  informal chronostratigraphy there are 412 results - we need to figure out what went awry in the process of migrating locality attributes in order to fix these. I can probably figure out all of the ALMNH and NMMNH issues, but the Alaska ones are a different story.

@dustymc any suggestions?

Note, there may also be issues in Series/Epoch and Eon/Eonothem

**Comment by dustymc** [comment]
I knew that went way too smooth...

Here's what the insert should have been, I think. I can re-do it properly then delete the value=informal chronostratigraphy stuff, but it's 444 rows so that might be un-doing some un-doing.

[temp_informal_geo_shouldbe.csv.zip](https://github.com/ArctosDB/arctos/files/5295446/temp_informal_geo_shouldbe.csv.zip)

**Comment by Jegelewicz** [comment]
Nice - be aware that there are a few of these that I have messed with already so when you go to undo them, they won't be there.

I say let the undoing commence...

**Comment by dustymc** [comment]
/remind me to check back tomorrow, before my brain gets all mushy

**Comment by dustymc** [comment]
done
