### ISSUE TITLE
part names and part attributes for media and observations

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#3164]
The Code Table subcommittee has been discussing how to deal with part names and part attributes for media and observations. This issue is related to several other issues linked in this [Google doc](https://drive.google.com/file/d/10gvsABpVGRlNCUEDA4oeqP2kPO3A-1iH/view?usp=sharing). The Google doc has:

1) recommendations for updated definitions in the [specimen_event_type code table](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_event_type)

2) recommendations for how to enter part name, part attribute (of type preservation), and specimen_event_type for unvouchered media, vouchered media, and observations with no media

3) recommendations for changes to the Search Cataloged Records interface.

We plan to discuss this at the next Arctos Issues meeting on November 5th, so please review and comment before then (add comments here or to the Google doc).

**Comment by dustymc** [comment]
I dislike mixing "handled" in with "biopsied. We currently have three very clearly distinct event types, and I oppose intentionally blurring the lines between them. We now have

* removed
* still out there, we have biology-bits
* still out there, we don't have biology-bits

and the proposed definitions mix up the second and third. I can see lots of reasons not to do that, and no reasons it's necessary or desirable.

The example parts in the linked document contain not-parts, such as "fossil" (which is, or should be, a preservation method, or something like it, not a part).

There is no event type that cannot result in photos. You can take a picture, shoot it, then take more pictures. (Perhaps that's more correct as three events milliseconds apart, but nobody's going to do that.) There's little linkage between parts and event type, and none when the parts are media.

>If there is a media object related to a physical specimen, there is no need to add media
as a part name.

Parts are things that can have barcodes. Some Media have barcodes, which is the origin of media as a part. If you're tracking a critter-bit and a picture of the critter (thumb drive containing the digital picture, etc.) then you need two parts.

>Observation only, no media (e.g., point-count survey):

Same as above; if there's a physical thing to track then there's potentially a reason to create a part.

**Comment by ccicero** [comment]
The Code Table Working Group met again before Christmas and revisited this [document](https://drive.google.com/file/d/10gvsABpVGRlNCUEDA4oeqP2kPO3A-1iH/view?usp=sharing) in the context of @dustymc comments. Suggested changes are tracked. After much discussion, the group concluded that "Encounter" is confusing and that if a physical sample is collected, the specimen_event_type should be "collection" even if the organism can be resampled.

@dustymc @Jegelewicz @campmlc @ebraker @mkoo - Can we accept these changes and finalize the document?

**Comment by campmlc** [comment]
I accept this.

**Comment by dustymc** [comment]
I don't see what's fundamentally changed in the doc, and I still don't understand the goals at all. This is a proposal to irrevocably reduce the information associated with any bot garden, zoo, captive program, mark-recapture, etc. specimen, and to add ambiguity to most records in Arctos by doing so.

There are no structural changes. If the collections are OK with losing data then I suppose I have to be as well.

@jldunnum 
@amgunderson

```
arctosprod@arctos>> select guid_prefix,count(*) from collection
arctos-> inner join cataloged_item on collection.collection_id=cataloged_item.collection_id
arctos-> inner join specimen_event on cataloged_item.collection_object_id=specimen_event.collection_object_id
arctos-> where specimen_event_type='encounter' group by guid_prefix;
 guid_prefix | count 
-------------+-------
 MSB:Herp    |     1
 MSB:Mamm    | 30966
 UAM:Ento    |     1
 UAM:Mamm    |  1200
 UAMObs:Fish |     1

```

**Comment by ccicero** [comment]
The goal is to get some consistency in how we deal with media that are physical but not digital (e.g., 35 mm slide of a karyotype, when we don't have a digital media so can't link to the record but want people to know that there is a karytope). Likewise, how to deal with records where the only representation is by media (no physical voucher or sample), or observations where there may or may not be media. Currently, there is no consistency in how people are doing that with parts. 

The only recommended changes are to (1) remove specimen_event_type of 'encounter' which we found confusing after a lot of back and forth, (2) add part name of 'whole organism (living)' which would be needed for bot gardens but also could be used if someone wants to put that as the part for a media of an animal observed but not collected, and (3) add values for part attribute type of 'preservation' that reflect the type of media. 

I'm not sure where you think data are being lost. These changes should make it easier to find things, not harder. 

This came up initially because Patton wants me to update a bunch of MVZ mammal records to show that there are karyotype representations in media that are not digital but are physical. He wants people to know that they exist, so how best to do that...brought us down this rabbit hole.

**Comment by dustymc** [comment]
Thank you, that helps tremendously.

>consistency in how we deal with media 

This I enthusiastically support.

>I'm not sure where you think data are being lost

We currently have "we killed it, it won't be wandering around any more" and "we didn't kill it, you might bump into it again." You've proposed to get rid of that distinction. It's valuable; it's a hint that two samples might be __really__ similar because they're the same animal, etc., etc., etc., could be useful for someone looking at hormones, aging, capture stress, etc., etc., etc.; completely critical data for any number of use cases. I can see zero reason to lose it and many many reasons to keep it.

>part name of 'whole organism (living)'

I object to confounding parts with "living." We may need to better get at that information, but it's a determination of some sort (probably part attributes), not a description - certainly not a static description! - of the THING that parts represent. Things like seeds and cryptogams have strange ideas of "dead," metadata would be important with such an assertion.

I think "encounter" does what you're trying to do here as well.

>add values for part attribute type of 'preservation' that reflect the type of media.

I think we need to back up more than that and identify what's important. I think it's this:

* It's a 35MM slide. This is a part - it's a physical thing, it might have a barcode, etc. I'm less certain on what we should call it, but we should normalize this as much as we can.

* It's a picture of a spleen. People who want spleens to look at some enzyme should be able to readily avoid this, people who want spleens for anatomy-things may want to include it. https://arctos.database.museum/info/ctDocumentation.cfm?table=ctpart_attribute_part may serve that purpose, but I'm certainly up for better ideas.

* The media itself may be "preserved" by some technique/media/environment/whatever; this is what https://arctos.database.museum/info/ctDocumentation.cfm?table=ctpart_preservation would apply to. (The cultural folks may have an interest here.)

Is that all you care about, and do my suggestions handle that information?

I think maybe you're trying to get at "picture of a _[preserved in some way]_ spleen"????

Or you may be trying to invert that, treat the spleen as the part and the fact that it's not a spleen, but a picture of a spleen, as metadata?? That doesn't completely strike me as "wrong," but we'd need to find something to do with the data pertaining to the media object (eg slide) itself.

One way to handle that would be to catalog the media separately (your Archives collection). That would allow you to focus the data on what's relevant to the collection (part=spleen in the mammal collection, part=35mm slide in the archives), and would likely make the Media more useful to a wider audience, but of course it would be a lot more stuff to keep up with as well.

**Comment by dustymc** [comment]
I think some semi-recent TDWG-ish discussion (that I don't have time to look for right now) has been useful in framing this - essentially, the idea is to treat "MaterialSample" as **evidence** for "Occurrences." We don't quite have either of those things, but the idea works, and the thought process removes us from the arbitrary and pointless cycle of trying to figure out what "observational data" is and isn't (It's currently ear snips in some collections and "literature sightings" in others and who knows what elsewhere; entirely arbitrary things that vary across time/institutions/collections/whatever). We simply tell users that we have (or claim to have had - this approach also considers things like disposition and condition) some thing, or some representation or description of a thing, and users can decide if that's worthy of inclusion in whatever they're doing or not.

I think our primary evidence is (or should be) parts, and there is an inconsistency with the current documentation. 

* A 35MM slide of a karyotype should be entered as part=media (according to the current documentation) - I think that's all correct, the 'media' (=some physical thing to which you might stick a barcode) is in fact (part of) the evidence for the Occurrence. (Patton saying "this is a Pero" is more evidence, so maybe we should document that we're never going to get all of our evidence into one basket.)
* A digital image of a karyotype on a USB thumb drive would (per docs) be treated in exactly the same way - there's something to which a barcode could be stuck.
* A digital image of a karyotype on a drive at TACC would be treated differently - there's no physical bit, so there's no part. I think this is our outlier. I believe UAM:EH / @AJLinn has been purposefully ignoring that bit of documentation and may have this figured out. I'm pretty OK with the exception here - our "definition" of parts has always been something less than an actual definition.

So there's a wrinkle, but I believe the "media" (image, sound recording, video, whatever) part is appropriately the evidence.

What's obviously missing is doing something better with the "secondary evidence". My current take is that this is the same situation as [combo parts](https://github.com/ArctosDB/arctos/issues/3654), and both would be solved by 

1. (re)firing up a "sub-part" code table, and 
2. doing something with it in the UI (so people who are just looking for karyotypes or liver can search both, and people who only want liver that's not mixed in with feet can use some 'advanced' search)

That would also provide a mechanism by which to better categorize things like the audio in part=media - the "subparts" could include

* kayrotype (eg diagnostic image)
* teeth (different kind of diagnostic image)
* fuzzy camera-trap image of mouse scurrying into the bushes ("less-good" evidence)
* field notes ("evidenceness" would require individual examination - is this an expert talking about their subject, or are they trying to describe the mites in the nest of their subject?)
* liver (it's still a liver, but maybe it's been soaking in really cold stomach juices for a few decades)
* call (a way to be more specific about what's on audio tapes without making it difficult to find audio tapes)
* song (ditto)
* etc etc

Essentially this would be a controlled but less-limited place for the not-quite-part things that come in as parts with every new collection, and which comprise a fair number of our part requests. It would not pollute our 'things to which one might stick barcodes' list nor prevent any current searches from working. It would provide a normalized mechanism, so we're not doing one crazy thing for one kind of evidence (eg mixed tissues) and something else for another (photos-n-such); any development would serve a wide audience.

**Comment by dustymc** [comment]
Done?
