### ISSUE TITLE
bulkload cryovials into freezerbox positions?

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#3181]
Can you bulkload cryovial barcodes into freezerbox positions? It seems like if you create positions in the the freezer box, you then can't use the 'Upload CSV file' on the Batch Scan page:
_call moveContainerByBarcode('#barcode#','#parent_barcode#',NULL,NULL)
An error occurred while processing this page!Message: ERROR: movecontainerbybarcode(unknown, unknown, unknown, unknown) is not a procedure Hint: To call a function, use SELECT. Position: 6_
 

Would you have to create a separate loader to put them into positions, or could we just add the position number to that CSV? What are the third and fourth arguments in the moveContainerByBarcode function?

**Comment by campmlc** [comment]
We physically scan new cryovials into position to minimize error, but our
old legacy system was autoconverted by Dusty. I am not aware of a way to
bulkload objects into positions that have scannable forms.

**Comment by dustymc** [comment]
Technically: Sure, I could come up with something, if I had to....

Practically: I don't think this is a good idea. You're going to have to handle the vials to get them in the box anyway, if you scan them then it's pretty hard to end up with something wrong. Someone trying to remember 2 sets of tiny little random numbers (presumably about 100 at a time) would lead to a very different quality of data.

If this is legacy data then I could SQL in from CSV of box/tube/position.

**Comment by acdoll** [comment]
We scanned a bunch of them already (into excel) so that I could do some quality control as I set up our system. Now I'd like to just dump that in without pulling the boxes out again, or doing some major copy-pasting. I would imagine this would be a useful function for any new collections that has an existing tracking system.

**Comment by acdoll** [comment]
Is this like what you mean by legacy?

**Comment by dustymc** [comment]
Legacy enough; send it along and I'll make it happen. 

I have yet to meet a non-Arctos collection with a functional part-based, actually-unique object tracking system. If one shows up, it should be trivial to SQL them in.

**Comment by dustymc** [comment]
>QC step between scanning barcodes and entering into Arctos.

Much of that's built into Arctos, and would be difficult to replicate outside of Arctos. You can't scan a freezer into itself, you can't scan big things into small things, etc. - all things that have caused problems before.

Much more can be built into the barcode system itself. I think most of us use fairly simple systems, but various encodings make available various checks.

Much more is in procedures. If you're allowing entry folks to type things then they will, and they'll do it wrong from time to time. If they're scanning, that's not really possible - as far as I know every encoding has at least primitive checks that don't allow the scanner to read anything that's not intended.

>lag between the specimen preparation (tissue sampling and barcode application) and the entry of the prep data (particularly the parts)

That is a fundamental design consideration of the system. Enter the data when you get them, scan the "part barcode" (2-piece codes are handy for this) when you enter the specimen information, and everything automagically comes together.

>create a container for all 12M barcodes I've claimed 

I'd like to just say yes, but I think that would create performance problems.

> just the 50,000 we had printed

Yes. That's why the various "... label" container types exist.

>the barcode sticker get lost/destroyed

There's value in knowing that - that smudged sticker you get back from a loan can't be THAT, because it was destroyed and that was noted in the remarks.

> loading cryovials into freezer boxes without positions 

That's perfectly acceptable. Positions should be used if they make things easier for you, if they don't (eg, because you have some other organization system) then there's no reason to use them.

>move those back into The Universe?

That's purposefully difficult, perhaps impossible - "The Universe" is not actually part of the hierarchy, things get weird out there. 

If you do want to move them, I'd probably just scan them into another box which will leave the original empty and ready for positions, if you want them.

You could scan them into a room or similar, which is better than nothing. UAM has/had a "junk shelf" that worked well for that sort of thing.

Some collections/institutions also have a "ABC:XYZ never-never land" "container" (which exist only virtually) with a barcode for "un-scanning" things, like this:

<img width="747" alt="Screen Shot 2020-10-30 at 10 59 12 AM" src="https://user-images.githubusercontent.com/5720791/97740794-028f4c80-1a9f-11eb-9341-16ce38be0695.png">

**Comment by campmlc** [comment]
Yes, I would recommend creating a new box with positions and rescanning
them there, although you can do this virtually (albeit with some
difficulty) if you understandably don't want to take this freezer box out
of the freezer again.   Create a new virtual box with positions. Copy paste
the barcodes into the form. Then physically attach this barcode to the old
box.
We do have a tool that allows you to move all children of this container to
a different container, but this doesn't work with positions. It would be
fantastic if it would, and I have requested that feature several times.
E.g. move all cryovials from one box to identical positions in second box.

**Comment by acdoll** [comment]
By QC I mean finding and fixing, for example, when a prep volunteer collects and freezes heart, kidney, liver and muscle but then writes only "heart, kidney, liver" on the data sheet and then the data entry volunteer enters "heart, kidney, liver (ethanol)". No matter how many times we stress accuracy in recording data, things like this still happens. Our volunteer preparators don't touch Arctos (if they did, we'd have computers covered in blood and feces); for many of them it's not in their skill set or they just want nothing to do with it. They've got plenty of work to do in the lab, so we find other volunteers that like sitting at computers. 
Going forward, I plan to have our one staff preparator scan thing into place as they go, but for now I'm cleaning up the last thirteen years of tissue collection. I will move those cryovials into a safe place and then send you a .csv or two with the appropriate parent-child-position relations.

**Comment by dustymc** [comment]
>writes ... on the data sheet 

If you're doing anything very standard you could encode the common parts as barcodes on the data sheets and stick half of the two-piece cryovial labels beside the appropriate part. The tube gets scanned into a freezer, eventually the record gets entered which involves scanning the part name, scanning the associated barcode, and waiting for the magic to rejoin the part-container with the tracked container stack.

**Comment by acdoll** [comment]
That's essentially what I'm going for, but I hadn't thought about scanning part names. So, I'd just need to add a translated  part name (into barcode font) on the data sheets...we're kind of space limited already, but it is worth a shot. Thanks

**Comment by dustymc** [comment]
If you're using a smart enough scanner, you can use a 2D code of some sort on the sheet - not sure how small you can make those, at least quite a bit smaller than a nunc cap.

**Comment by acdoll** [comment]
Okay, all the freezer boxes are emptied and they've been assigned the correct position layout (9x9 or 10x10). Can you upload this file to put the cyrovials in their positions?

[MR1_cryovials-freezer_box_positions.zip](https://github.com/ArctosDB/arctos/files/5467584/MR1_cryovials-freezer_box_positions.zip)

**Comment by dustymc** [comment]
Do you want to make the positions in the boxes? I can do it as well, but I'll just accept the defaults and won't know if they're inappropriate....

**Comment by acdoll** [comment]
I forgot about that step. I went ahead and created them. Out of curiosity, why doesn't it create them automatically when you select the position layout?

**Comment by dustymc** [comment]
Thanks, done.

I think there's an issue somewhere, not much technical problem with that, but I think it would result in a lot of angry fixing of "oopsies."

**Comment by acdoll** [comment]
Awesome, thanks! I'll have a few more of these to do. Should I just put them up on here for you to do or is there some way I can take care of it?(you probably have bigger fish to fry?)

**Comment by dustymc** [comment]
I don't mind and it's pretty quick if everything's clean like this one, or I'm happy to help figure out SQL access if you're comfortable on the command line and want to do this sort of thing.

Here's the code I used.

```
create table temp_dmns_pos as select * from  temp_cache.temp_dlm_uptbl ;
alter table temp_dmns_pos add tubeid bigint;
alter table temp_dmns_pos add boxid bigint;
alter table temp_dmns_pos add posid bigint;
update temp_dmns_pos set tubeid=(select container_id from container where barcode=tube);
select count(*) from temp_dmns_pos where tubeid is null;
update temp_dmns_pos set boxid=(select container_id from container where barcode=box);
select count(*) from temp_dmns_pos where boxid is null;
update temp_dmns_pos set posid=(select container_id from container where label=position and parent_container_id=boxid);
select count(*) from temp_dmns_pos where posid is null;
CREATE OR REPLACE function temp_test() returns void AS $body$
DECLARE
  r RECORD;
BEGIN
  for r in (select * from temp_dmns_pos) loop
    update container set parent_container_id=r.posid where container_id=r.tubeid;
  end loop;
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
select temp_test();
drop function temp_test();
```

**Comment by campmlc** [comment]
Happy to share the Bartender file we use to preprint cryovial labels with
scannable field number and tissue codes. We use EIM label paper that will
stick to cold tubes.

**Comment by acdoll** [comment]
Thanks @dustymc, for now I think I'll have you upload them. Once we get the backlog entered I shouldn't need to do this again. I'll make sure everything is clean and ready before I send you more.

@campmlc I'd love to take a look at that Bartender file - I was just getting comfortable with that software when the shutdown happened and haven't touched it since.

**Comment by dustymc** [comment]
Tentatively closing, I think we're done here?

**Comment by acdoll** [comment]
I will have more for you to load, but can start a new issue and reference this at that time. Thanks.
