### ISSUE TITLE
Linnean suggestions in taxonomic classifications make managing mineral and cultural classifications difficult

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3196]
Currently if you edit a taxonomic classification that does not include a kingdom or a genus, Arctos suggests a genus for you and creates a blank kingdom field. This is OK for Linnean taxa, but for minerals and cultural classifications it can easily add junk unless you delete all of the unnecessary suggestions. Can we somehow exclude mineral and cultural taxa from these suggestions?

In addition, Arctos tells you that you are missing nomenclatural code and adds a blank field. Could we use this to facilitate the above? Currently we have one set of mineral classifications (Hey's CIM) and we could create a new nomenclatural code = Heys, then anything with that code doesn't get the "helpful" Linnean suggestions?

**Comment by dustymc** [comment]
Why are you using the "make everything inconsistent" form for this? Can you manage those elsewhere - Excel, hierarchical editor, just download them from wherever the come from and upload them to Arctos, etc. - and just not use that?

I suppose I'm resigned to the idea that we can't get rid of that form, but it shouldn't be used to manage anything that anyone hopes to be consistent either. Those suggestions were aimed at consistency, and they demonstrably did not serve that purpose. Can we just simplify the form so it can manage anything but suggests nothing?

nomenclatural code exists because display name is autogenerated, and that generation varies between ICZN and ICBN (mostly in how infraspecific information is handled). I see no reason to add it if it's not doing anything, and I certainly see not reason to make something up! As above, let's remove it as a "requirement," perhaps beef up the documentation, and I'll redo the function to generate display name for "bare" classifications.

**Comment by Jegelewicz** [comment]
> Why are you using the "make everything inconsistent" form for this? 

When I got the data from Mindat, the links to the webpages were not included. As I work with stuff, I add it as the source authority.

**Comment by dustymc** [comment]
The form is simplified, closing, new issue for flat packaging is https://github.com/ArctosDB/arctos/issues/3231
