### ISSUE TITLE
error feedback - Higher Geography

### ISSUE THREAD

**Issue by cefilipek** [ArctosDB/arctos#3280]
The locality my fossil is from is not in our system (Europe, Germany, North Rhine-Westphalia, Minden-Lubbecke). I attempted to add it and I recieved this error.

> An error occurred while processing this page!
Message: ERROR: permission denied for table geog_auth_rec
Detail:
Check the Arctos Handbook for more information on errors.
This message has been logged as D74DA47B-435E-413B-87DE9638334C890B Please contact us with any information that might help us to resolve this problem. For best results, include the error and a detail description of how it came to occur in the Issue.

I thought I had the authority to create localities, so I am unsure what this issue is. I added the relevant information, the source authority, and the information on why it is unique (it is not in Arctos yet) then selected create.

**Comment by Jegelewicz** [comment]
Higher geography is different from locality. Send me the wikipedia link to this geography and I will create it for you.

**Comment by cefilipek** [comment]
Ah! I must have gotten confused.

https://en.wikipedia.org/wiki/Minden-L%C3%BCbbecke

Thanks!

**Comment by Jegelewicz** [comment]
Editing higher geography is a different set of permissions.

Currently we are using Nordrhein-Westfalen instead of North Rhine-Westphalia

![image](https://user-images.githubusercontent.com/5725767/101390518-2ef96e00-3880-11eb-98a1-ec2b0feeca45.png)

So your geography will be:
Europe, Germany, Nordrhein-Westfalen, Minden-Lubbecke

**Comment by cefilipek** [comment]
Great! Thank you very much!
