### ISSUE TITLE
Bulkloader error message: triggercaught:::You cannot put anything in a label.

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3284]
I don't remember ever seeing this error message previously with Oracle. This error is preventing bulkloading of specimen records with parts in cryovials that have not yet been scanned into a freezer box position, and consequently have not been converted from cryovial labels to cryovials. We need to be able to load the specimen records and their associated parts even if those parts are in holding pending transfer to DGR.  Can "cryovial label" autoconvert to "cryovial" during bulkload if someone is associating the barcode with a tissue part type?

**Comment by dustymc** [comment]
The ability for the bulkloader to manipulate containers was removed primarily in response to people (from different collections) typing in incorrect barcodes.

The direct answer to "Can "cryovial label" autoconvert to "cryovial" during bulkload" is "yes, but doing so has far-reaching implications."

The answer to "if someone is associating the barcode with a tissue part type" isn't exactly "no" but it's close enough to be treated that way. That limitation has never been implemented or attempted, and I doubt if the data support it.

In the old model, partially due to Oracle's security model, everything that happened to containers went through functions, which are complex code with limited functionality, and each is a potential security hole. We're moving towards a model in which rules are closer to the DB (because PG's security model allows it), and under which containers can be addressed more natively. I am hesitant to revert and give up the increased security or functionality, but there will never be a better time than now if we absolutely must.

I think the core of this issue revolves around procedures. "Change some labels to an appropriate usable container type (one not containing “label”)" is the first step in https://handbook.arctosdb.org/documentation/container.html#using; if you're not doing something like that well before the labels get anywhere near a physical container then container type isn't serving its purpose. If that's not important you could just change them all to something generic immediately after creation, and set up containing containers to deal with that.

**Comment by campmlc** [comment]
This trigger is continuing to cause problems in that the collections adding barcodes to tissues cannot catalog the records until the parts are scanned into position in DGR and autoconverted to cryovials. The records get hung up in the bulkloader, causing the barcodes to be deleted from the bulkload file and ultimately never associated with their voucher records.  We had just developed a workflow which would allow capture of barcodes with records at time of cataloging, and this is derailing that effort.
Solution:
We could autoconvert all the MSB:Bird cryovial labels to cryovials proactively to deal with this -but that doesn't fix problems with the wrong label being typed or assigned etc. 
Or we could provide a optional field in the bulkloader of "new_container_type_1" which would convert a label to a cryovial during bulkload. I prefer this latter option, as it will work going forward. I'd like to request that this field NOT require the operator to know the old container type - just the new one that the barcode is being converted to.

**Comment by campmlc** [comment]
Some observations on the inconsistent use of triggers/not triggers in object tracking:
To add a barcode to a legacy container, options for doing so without using the scary red box include:
1) adding a barcode via Catalog Record: Edit Parts: this tool can be used to add a part to a barcode which is a cryovial label;  it autoconverts a label to a cryovial on insert. This is a good tool - please do not change.
2) adding the same barcode to the same part via Object Tracking Edit Container : Move to Barcode fails, with the error: you can't put anything into a container. So, no autoconvert of cryovial label to cryovial in this case. I never use this tool - it's been so long I couldn't remember why -so this is why. But very hard to explain to students.
