### ISSUE TITLE
Media loading somewhat largeish image files into Arctos

### ISSUE THREAD

**Issue by mvzhuang** [ArctosDB/arctos#3336]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
Jpegs produced from DSLRs and exported at 300 dpi are approximately 5-12 mb each and are somewhat large - could cause problems for users of lower quality connectivity.

**Describe what you're trying to accomplish** 
Create solution for viewing high resolution images uploaded to Arctos or at separate allocation

**Describe the solution you'd like**
Find solution for large size images on Arctos or transformation of images uploaded to arctos

**Describe alternatives you've considered**
Reexport files at a lower dpi
Set up guidelines for image size being uploaded to Arctos
Create medium size image option in addition to high resolution image option (This is what TORCH TCN is doing with all images (thumbnail, medium, high))

**Additional context**
Preparing TACC allocations for uploading a large amount (~34,000) images 

Zhuang, Mingna
Thu 1/7/2021 2:09 PM
To:	Dusty <dustymc@gmail.com>;
​​I could export them at a lower res. I accidentally did that a little while ago and they ended up being 1.5-2 mb each. They seemed ok, but can't get a ton of detail when zoomed in. will file issue though describing the size. 

So should I go ahead with Chris in the meantime for a separate allocation? or still need discussion?
From: Dusty <dustymc@gmail.com>
Sent: Thursday, January 7, 2021 2:01 PM
To: Zhuang, Mingna
Subject: Re: inquiry about TACC allocations for an Arctos-member project at UTEP
 
Hmm, that sorta seems "huge." Definitely won't break anything, but wouldn't be much fun for someone on a dicey connection either. Maybe an Issue if you don't mind - this sort of thing is going to become routine if we transition to the s3 loader, now's a good time to start looking for a solution.

On Thu, Jan 7, 2021 at 12:56 PM Zhuang, Mingna <mzhuang@utep.edu> wrote:
​On average, they're 5-12 MB, although mostly 7-8 mb for jpegs and then about 25-27 mb for the RAWs
From: Dusty <dustymc@gmail.com>
Sent: Thursday, January 7, 2021 1:53 PM
To: Zhuang, Mingna
Cc: Christopher Jordan
Subject: Re: inquiry about TACC allocations for an Arctos-member project at UTEP
 
How big are the JPGs? If they're not huge (whatever that means...) then they're probably OK as-is. 

On Thu, Jan 7, 2021 at 12:46 PM Zhuang, Mingna <mzhuang@utep.edu> wrote:
​Hi Chris,

Sorry about the delay in response. Thanks for the information. I don't think we need image conversion and will just be uploading images to link to Arctos (unless there is something else I should consider Dusty?). If we do get a separate allocation, would we have to renew the allocation every year? 

Thanks,
Vicky

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.

**Comment by dustymc** [comment]
When/if https://github.com/ArctosDB/arctos/issues/3224 happens, creating derivatives will become the user's problem. Guidelines, tool suggestions, etc. see very useful.

https://handbook.arctosdb.org/documentation/media.html#binary-object-creation-guidelines exists, but the internet has come a long way (at least in the US) since it was developed.

I believe that https://github.com/ArctosDB/arctos/issues/2863#issuecomment-755355131 works because they're using IIIF to generate derivatives. If we had IIIF (and if it actually works like I imagine) then perhaps generating web-friendly versions (or whatever) could be part of Arctos. 

Disk space and associated costs probably needs somehow balanced with usability as well - eg it might be nice to have huge/medium/small/thumb JPG (or similar) in addition to the originals, but then we'd have to store them.

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/internal/issues/119
