### ISSUE TITLE
unreciprocated relationships

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#3370]
There are relationships in https://arctos.database.museum/info/ctDocumentation.cfm?table=ctid_references which are not handled by https://github.com/ArctosDB/PG_DDL/blob/master/function/pg_cron/gatherReciprocalRelations.sql. These will not receive notices.

```
  'ate|eaten by',
    'collected with|collected with',
    'host of|parasite of',
    'in amplexus with|in amplexus with',
    'littermate or nestmate of|littermate or nestmate of',
    'mate of|mate of',
    'parent of|offspring of',
    'same individual as|same individual as',
    'sibling of|sibling of'
```
1. Do any existing relationships need added to the notification
2. Any additions to this code table need made reciprocal (or perhaps not, but let's be explicit if we go there). How do we better handle that?
3. Documentation in this table should end with "Reciprocal relationship is ..." - how do we do better with that?

**Comment by Jegelewicz** [comment]
> Documentation in this table should end with "Reciprocal relationship is ..." - how do we do better with that?

To me the simplest solution is to add a field to the table that is required but also allows for "NONE".

**Comment by campmlc** [comment]
Any reason not to include all the relationships in
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctid_references?
It would be good if we could link these tables so that additions to the
above would automatically add to the notification list.
I would like to request including "same lot as", minimally.

**Comment by dustymc** [comment]
>add a field

That complicates both our tools and sharing our authorities. That may well be a cost worth paying, but I'm not yet convinced. It's important to keep in mind that I'm only generating suggestions - these are potential data, not data, as might be implied by a column.

>Any reason not to include all 

Nobody asked to - please, do!

>same lot as

Self-reciprocating, correct?

**Comment by campmlc** [comment]
Yes, self reciprocating. And I would like to request notifications for all relationships, except self, unless the cultural folks prefer otherwise.  @AJLinn @krgomez

**Comment by dustymc** [comment]
>same lot as

done

> like to request notifications for all relationships

That's what I'm doing here, I need the reciprocals of anything that's no in my list.

**Comment by krgomez** [comment]
Notifications sounds fine to me! I have a question: For all the catalog records where I have added relationships that were not automatically reciprocated, but where I added the reciprocal relationships myself to the necessary catalog records, will anything be changing with those relationships that already exist?

**Comment by dustymc** [comment]
>Notifications

There have always been notifications, but just for those relationships of which I'm aware. (And now they're in a format that's a lot easier to manage, yay postgres.)

>added relationships that were not automatically reciprocated

There is no automated reciprocity. 

>will anything be changing with those relationships that already exist?

No, this is just a suggestion (in a format that can be downloaded, reviewed, then fed into the bulkloader).

**Comment by acdoll** [comment]
> These will not receive notices.

I would be in favor of adding the listed relationships to the notifications

**Comment by Jegelewicz** [comment]
> Hi Teresa,
> 
> I received this email this morning concerning the records below.  Am I supposed to do something with these? Not sure…  But this brings to mind a conversation Adiel and I had yesterday concerning trace fossils with counterparts.  So far as when Dana was paleontologist, we had been assigning separate catalogue numbers to each of the two parts.  Adiel now wants to create a single record/catalogue number for both parts, and list them as such.  It seems we had a long conversation about this back in the day, so I wanted to run this by you and ask for your opinion:  which of these works best and why?  Should we proceed from now on the way Adiel would like to see it done?  He has a new specimen he wants me to enter into the database, but I remember going over this awhile back and can’t remember why we didn’t combine the two parts in the first place?!
> 
> Thanks!
> 
> > Mary Beth
> > 
> > You are receiving this message because you are a data quality contact for collection ALMNH:ES.
> > 
> > There are specimens with unreciprocated relationships to your collection.
> > 
> > After logging in to Arctos, you may download a prepared Identifiers/Relationships bulkloader file at https://arctos.database.museum/info/unreciprocated_relationships.cfm, or by navigating to Reports/Services-->Find Low-Quality Data-->Unreciprocated Relationships.
> > 
> > Summary:
> > 
> >     same individual as ==> ALMNH:ES (1 relationships)
> >     same lot as ==> ALMNH:ES (9 relationships)
> > 
> > Specimens in collections to which you do not have access may not be visible while you're logged in; encumbered specimens may not be visible at all. Contact the appropriate Curators (contact information is under the Portals tab) with questions or concerns.

> Am I supposed to do something with these?

Yep. The one "same individual as" is telling you that https://arctos.database.museum/guid/ALMNH:ES:6190 shows a relationship of same individual as https://arctos.database.museum/guid/ALMNH:ES:6207 but that 6207 does not have the other half of the relationship.
HOWEVER, when I look at these, the relationships are both there!

![image](https://user-images.githubusercontent.com/5725767/105530631-457b4d80-5ca5-11eb-91e4-d407f0689d01.png)

![image](https://user-images.githubusercontent.com/5725767/105530664-51ffa600-5ca5-11eb-801b-c8b203c1fd10.png)

@dustymc ?

**Comment by Jegelewicz** [comment]
> which of these works best and why?  Should we proceed from now on the way Adiel would like to see it done?  He has a new specimen he wants me to enter into the database, but I remember going over this awhile back and can’t remember why we didn’t combine the two parts in the first place?!

@mbprondzinski I don't have a preference, but here are some pros and cons.

Catalog as two parts under the same catalog number:
Pro - they are the same taxon, collected at the same time and place; so one number reduces duplication
Con - Unless you barcode them or otherwise definitively mark and track them, you may have difficulty knowing which "half" is out on loan or was cited in some publication.

Catalog separately and assign "same individual as" relationship:
Pro - can more fully describe the object and track its individual use
Con - you have two records where you could have just one and if the relationship isn't made correctly or gets removed, you may confuse researchers as to the duplication the two catalog numbers represent.

Ideally, you would treat these consistently within a collection, so if you decide to go with @aklompma system of one number for both, you might want to change the way you have handled this situation for ALL of your records. But it is really up to you. If you carefully document what is being done, it should be OK.

**Comment by dustymc** [comment]
> the relationships are both there!

This isn't a 2-part problem. 6190-->6207 is there, 6190-->6271 (what's in the download) is not.

From a research perspective, the real answer is always "catalog the item of scientific interest," and that's almost always biological individuals (when such things exist). Anything else is going to lead to studies independently examining A and B when they're really parts of the same critter, wonky citation statistics for your collection, etc., etc., etc. Giving citable identifiers to bits-n-pieces of the whole just doesn't readily support good science.

From an administrative perspective, you're not going to be able to faithfully maintain twice (or more) as many records. Someone will reidentify (measure, cite, whatever) a chunk of the individual, you'll update that record but not the other 47 pieces of the same critter, and now it looks even more like multiple individuals. If you ever decide to fix that, it'll be an incredibly painful process to merge those data in some way that makes sense.

I can't overstress how important cataloging the item of scientific interest is.

**Comment by Jegelewicz** [comment]
> I can't overstress how important cataloging the item of scientific interest is.

I sort-of agree, but the item of scientific interest might not be a one-size-fits-all thing. Let's look at the three way "same individual as" above.

Parts of the same fossil organism were collected on 3 different dates, not unusual for paleo stuff. Now, we could do the band-aid link event to part thing that MSB does with wolves, but I prefer a more solid event to part match that cataloging each separately provides (which includes the fact that different collectors were involved, and any other collection-specifics). We have the same individual as relationship for a reason and I think this is a good one to use it for. For a slab and counter-slab collected at the same time and place by the same collector, it seems unnecessary, but it is still OK in my book as long as the relationship between the objects is clear.

**Comment by campmlc** [comment]
Agree.

**Comment by mbprondzinski** [comment]
So what needs to be done with this?  I see there are three that are the same. Does 6271 needs to be linked to 6207?

**Comment by dustymc** [comment]
>wolves

If the dinosaur might have acquired parasites, had pups, or put some more wear on their teeth, then maybe...

You MIGHT convince me that "a wolf pup" and "same wolf 10 years later" are different THINGS for certain specific use cases. I don't think you'll convince me that "the part we dug up first" and "the part that we dug up later" are analogous.

There's no bandaid in linking parts to events, it's part of the core model.  

>needs to be done

Nothing, really - this is a notification service, nothing more. You might WANT to link everything to everything else, but that's not really a need. Your users might have a different perspective.

**Comment by Jegelewicz** [comment]
> So what needs to be done with this? I see there are three that are the same. Does 6271 needs to be linked to 6207?

@mbprondzinski if created all the relationships, so give it a day and they should all be OK.

**Comment by Jegelewicz** [comment]
> I don't think you'll convince me that "the part we dug up first" and "the part that we dug up later" are analogous.

But it might - ARE they the same individual? there could easily be differences of opinion.

> There's no bandaid in linking parts to events, it's part of the core model.

I wholeheartedly disagree with this statement. Adding "this part goes with this event" to a single record that documents ten or more samplings from a wolf over as many years is not as stable as one record per sample. That link is SOOOOOO easy to undo or mismanage and just ask @campmlc how that system works for her when she needs the blood sample collected on June 12. Also, what happens when there is a new interpretation of an event (so now there are two events associated with a single part) that cannot be addressed unless the sample has it's own record.

Also - the collectors are all lumped together without any way to determine who collected what when.

**Comment by campmlc** [comment]
Re linking parts to events:
The critical problems with the current model include:
1) accessions cannot be linked to events, so the different accessions for
different samples from the same organism must be added to remarks fields
and are not linked to and searchable by the actual accession
2) different collectors and preparators for each set of samples cannot be
tracked
3) It is an opaque process to search and view on eg localities and dates
for all events for a single record since only one event of many displays in
the flat search results
4) It is impossible to download records with data for multiple events for a
single record, unless we go to JSON, which is not a solution as it cannot
be parsed into a flat file for download and subsequent data manipulation
and search functions.

**Comment by campmlc** [comment]
And re part: event model:
5) the current model has proved virtually impossible to manage in terms of
data entry - can only be done by highly trained collections personnel who
dedicate hours of dedicated focus to avoid making mistakes, which get made
anyway, because the process is too complex.  Currently I have a museum
studies/biology MS postgrad doing this, and she is the only one I can trust
after many months of training, but still requires curatorial review. I'm
afraid we are going to need to discuss a way to undo this model and revert
to splitting these records back into single events linked by same
individual as relationships.

**Comment by campmlc** [comment]
@jldunnum

**Comment by AJLinn** [comment]
I've been getting a report about "unreciprocated relationships" between items in UAM:EH and UAM:Art. I downloaded the list, checked the relationships and all 6 records seem to have the mutually reciprocated relationship. What needs to happen so I stop receiving these notifications? Have @krgomez and I done the relationship incorrectly? Please advise.

> You are receiving this message because you are a data quality contact for collection UAM:EH.
> There are specimens with unreciprocated relationships to your collection.
> 
> After logging in to Arctos, you may download a prepared Identifiers/Relationships bulkloader file at https://arctos.database.museum/info/unreciprocated_relationships.cfm, or by navigating to Reports/Services-->Find Low-Quality Data-->Unreciprocated Relationships.
> 
> Summary:
> 
> same individual as ==> UAM:EH (6 relationships)

**Comment by dustymc** [comment]
I checked one, there's a trailing space

```
 select ':'||display_value||':' from coll_obj_other_id_num where collection_object_id in (select collection_object_id from flat where guid='UAM:EH:UA83-003-0034');
     ?column?      
-------------------
 :UA1983-003-034 :
```

I can't prevent or globally fix that as those can be used purposefully (eg to format prefixed space-containing collector numbers).

**Comment by AJLinn** [comment]
> I checked one, there's a trailing space

No worries - easy enough for me to go thru and check each one. Is that on the EH designation side (i.e., in my record where I designated the reciprocal relationship to the UAM:Art piece?

**Comment by dustymc** [comment]
>Is that on the EH designation side 

Yes, whatever it's suggesting - the GUID - is what the scripts think are missing, and the stuff being suggested (NEW_...) is from as existing relationship.

**Comment by AJLinn** [comment]
Thanks! That fixed my problem. :-) TGIF!

**Comment by dustymc** [comment]
Remaining values added to gatherer, issue template updated
