### ISSUE TITLE
agent rank

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#3448]
needs documentation, maybe scattered around more

**Comment by Jegelewicz** [comment]
Would like it in loan form as in "what is this agent's borrower rating?" and when loans are closed "rate this borrower".

**Comment by campmlc** [comment]
I like this idea.

**Comment by acdoll** [comment]
> agent's borrower rating

Not sure how I feel about this. A simple-to-implement 5 star rating system would surely miss lots of important details about the rating that was given. A more informative system with quantifiable measures and options for comment would take a lot of development which I don't believe should be a priority. Unless it's done _very_ carefully I would worry that this leads to unintentional or undeserved black-balling. Can you contest a rating? Is there a rating monitor or committee? Is it public or for internal ratings? Lots to discuss here before any action takes place.

**Comment by dustymc** [comment]
This has been around for maybe 15 years, someone just noticed it (again). It's implemented (in a somewhat limited fashion) but little used.

>quantifiable measures 

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctagent_rank, but I'm not sure that's quite quantifiable.

>options for comment

Comments are required.

>unintentional or undeserved black-balling

It's possible, I suppose, but see below.

>Can you contest a rating?

You could contact the rater. I'd like to think it won't every be controversial, but I'm sure more details would be handy from time to time. You could/should contest/reinforce by leaving your own ranking.

>public or for internal

Strictly internal with no desire to change. The intention is just to share experiences across Arctos collections - "we loaned this person some stuff, they [did what we asked of them | required some prompting before doing what we asked of them | ignored us ]." What you do with that information is of course entirely up to you.

**Comment by ccicero** [comment]
Revisiting this issue. @atrox10 @mkoo and I added an unsatisfactory ranking for an agent re: loans/borrows. Can we have that ranking show in the pop up next to the agent's name when you go to select an agent for a (loan) transaction? Otherwise, you don't know that the agent has a ranking unless you search on the agent name in the Agents interface.

**Comment by jldunnum** [comment]
An unsatisfactory rating of a potential borrower would be useful for other CMs to see as well when evaluating loan requests.

______________________________________________________________

Jonathan L. Dunnum Ph.D.
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by campmlc** [comment]
Agree that making this obvious on agent selection would be useful.

**Comment by dustymc** [comment]
The current agent pick doesn't have any way of knowing where it's being called from or by whom, and I doubt we want that being in front of students picking collectors and such (and processors might be an issue if we do).

Ranks are available on transaction forms after the agent is selected:

<img width="373" alt="Screen Shot 2021-09-24 at 2 01 05 PM" src="https://user-images.githubusercontent.com/5720791/134739283-564b5af9-a96c-41e6-8cb9-0ec3add1601f.png">

**Comment by ccicero** [comment]
@dustymc - This is a bit confusing. There are three possible ranks:

neutral
satisfactory
unsatisfactory

But how do those translate to the numbers 1-3, which are not in the rankings that you select.

Rather than having numbers, can we just display the descriptive ranking which also will be more obvious than just a number?

**Comment by dustymc** [comment]
[2]==>this agent has been ranked twice

**Comment by ccicero** [comment]
@dustymc  @atrox10 

First, I don't see a way of editing the agent record once the ranking has been assigned. How do you get rid of the ranks, or change it from 'accn' to 'loan' ? We just want one rank of 'unsatisfactory' for 'loan'

Second, can we display the term "unsatisfactory" instead of a number which (a) is not very visible, and (b) is unclear what it means.

Thanks.

**Comment by dustymc** [comment]
Don't think there's anything to do here, closing.
