### ISSUE TITLE
ALMNH API concerns

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#3477]
See https://github.com/gmfaircloth/UA-Museums-Capstone-2021/issues/5

I'm hesitant to allow use of a production server for testing.

https://github.com/ArctosDB/internal/issues/65 prevents us from just refreshing test.

Help!

**Comment by Jegelewicz** [comment]
But I thought they would be accessing the api - granted I know nothing about how that works, but I thought that was the whole idea behind allowing creation of "your own" UI - what am I missing?

**Comment by Jegelewicz** [comment]
That GitHub link 404's for me.

**Comment by dustymc** [comment]
There's copy-paste in https://github.com/ArctosDB/internal/issues/65

They are accessing the API. They're fundamentally asking for an API key which lets them point their developing application at a production server. I'm confident that I could use the API to melt the current production server, and I have no way of knowing how anything on their end works - one infinite loop (because that sort of thing happens in untested code), or some security issue that lets a malicious actor insert that infinite loop, or etc., etc., etc. could affect the production environment. I suppose they same will be true after they're finalized the app, but presumably/hopefully by then everything will have been tested and looked over by their security folks and such and the risks will have been reduced.

**Comment by Jegelewicz** [comment]
Well then, this is going to be true for anyone and it seems like we are unprepared to offer the solution of "build your own UI"? How are we supposed to monitor security for everyone who requests an API key? What expectations are we setting for such use? I feel like there needs to be a Working Group emergency meeting about this because we have been telling everyone this is an option, but now it seems that it isn't.

**Comment by dustymc** [comment]
General administrative concerns should be discussed in https://github.com/ArctosDB/internal/issues/51

The rest of your comments do not make sense to me. Using the API is an option.

**Comment by dustymc** [comment]
@ArctosDB/arctos-working-group-officers and @jcabbott13 can we schedule a meeting to talk about this soon?

**Comment by jcabbott13** [comment]
I'm happy to talk. I am going to be out of town Tuesday through Thursday, but depending on when folks can meet, I might be able to join. Generally, this afternoon or Friday morning are probably best for me.

**Comment by campmlc** [comment]
Friday am would be better, as I am traveling today, but I may be able to do
2pm MST from the road.

**Comment by dustymc** [comment]
I could make after about 1:30PST today or any time Friday.

**Comment by ewommack** [comment]
I could maybe do today, but not Friday. There is also the Arctos webinar today from 1300-1400 MST

**Comment by Jegelewicz** [comment]
Meeting notes

@mkoo says we need a completely public API as a long term goal.

@jcabbott13 questions as provided by @dustymc 

There is an API, but it is cobbly, may not be robust enough, runs in test too. Production API is not public because we don't have great security and the ALMNH app could take down the production version of Arctos. Are we OK with that? Can we start with test?

John says we need to fix security issues before we can make use of API and dusty agrees, but we don't have the appropriate security review as of now.

Michelle asks about resources available at ALMNH to ensure the app is performing as expected and within security parameters.

Faculty supervisor would be the stopgap - can we place the expectations on them? UA IT support? Probably not. Time is an issue, as it is a semester-long project. What are our expectations?

Mariel - interface is for only cultural collection? John says no - it is for all ALMNH. Can we port over ALMNH data - Dusty says not it would not be possible because we have an outdated version of Test. MIchelle - We should be applying pressure to TACC for a true test environment and we could use this as the prime reason for getting a fix. John can help. But TACC will need to bill us - we need to ask for a bill. This would solve so many problems!!!

But this probably still will not solve our problem, because ti will take too much time. What is the backup plan so that the students can finish the project? Get faculty member on the call? can TACC evaluate the student project for security issues?

Only five weeks of the semester left.

App will not be public right now, which would eliminate to some degree hacking. Would this work for now? Dusty would be comfortable with that for now. Available only to authenticated users. OK for the short run, until we have public API. Maybe run tests in off hours to avoid taking down Arctos during "prime time", but probably would need Dusty there.

What is the plan in the worst-case scenario? We don't want to repeat last summer.

Writing in authentication may not be feasible for the current group. Not making it public is an option for this group though. 

Who needs to approve? Working group officers, one day to respond and send an announcement to the community, then open up the API for the group. Dusty will mint a key once we give approval.

John's questions for Dusty

About section is missing a lot of fields (time scales - locality attributes)
Higher taxonomy refresh is complete
Search fields like collector and scientific name with author are missing - Dusty asks for examples to help out with.
Mapping works now

Where is the code and how do communications happen? Somewhere public and available to us? Share repository with Dusty and who else? GitHub working group team.

**Comment by Jegelewicz** [comment]
- [ ] send an announcement to the community @mkoo @campmlc @Jegelewicz 
 - [ ] open up the API for the group @dustymc

**Comment by dustymc** [comment]
Where are we on this? Should I issue a production API key?

**Comment by Jegelewicz** [comment]
Has anyone sent an announcement? @mkoo can we do this today?

**Comment by jcabbott13** [comment]
I hate to be pushy, but the students are running out of time, so the sooner we can move forward the better. Thanks!

**Comment by mkoo** [comment]
Yes, I think with the assurance it will be on a private page for now, we
should move forward with access to the prod API.

There will be follow up for secondary test arctos based on the TACC email
and @Lam VOONG ***@***.***> follow-up with the BNHM sys admin (and
maybe other resources) but none of that prevents the students moving
forward.

Sound right?

**Comment by dustymc** [comment]
Sounds like "go" from here....

@jcabbott13 what Arctos username should I issue the key to?

**Comment by jcabbott13** [comment]
@dustymc Please use gmfaircloth. Thanks!

**Comment by dustymc** [comment]
I need an Arctos user with some rights - I can you use or @mbprondzinski ?

**Comment by jcabbott13** [comment]
Oh, I guess use mine, jabbott, then since Mary Beth is retiring. Will this mean though that I need to provide the team testing, my credentials to Arctos or just the username?

**Comment by dustymc** [comment]
Neither, just the key - I'm just looking for a point of contact. 

Your account is locked - you'll need it to retrieve the key. I unlocked, you should have email from Arctos.

I also need the IP address (or range) of your testing box - sorry I forgot to mention that earlier.

We really need to get https://github.com/ArctosDB/internal/issues/51 fleshed out, @ArctosDB/arctos-working-group-officers .

**Comment by dustymc** [comment]
Nevermind, I dug the IP out of test logs (I hope...), you should have a key on your Arctos profile - might take an hour for the cache to clear.

**Comment by jcabbott13** [comment]
Got it. Thanks
