### ISSUE TITLE
Feature Request - Indigenous Place Names into Arctos?

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#3527]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
We've discussed over the years a desire to add local Indigenous place names to Arctos. I just came across [this list at the Alaska Native Language Center](https://www.uaf.edu/anla/collections/map/names/) and I'm wondering if there's a way for us to add these to Arctos in some way that could standardize the names as an alternative to geographic place names currently used (in Alaska). 

I have a lot to learn about how to "properly" use localities in Arctos and I'm sure i"m not doing it right. I just wish there was some sort of code table that we could use for geographic place names like we do with higher geography. Or does that exist already and I just don't know how to properly use it?

**Describe the solution you'd like**
Create a controlled vocabulary for geopolitical place names that includes lndigenous place names as "other ID" or "alternative name" or something similar.

**Priority**
Normal priority - it would super cool but maybe a can-of-worms? Looking for some input. I'm tagging this as a cultural collection issue because it is part of the idea of expanding our ideas of what constitutes knowledge authority and using local Indigenous names for places would go a long way in demonstrating that value.

**Comment by AJLinn** [comment]
Maybe this is tied somehow to https://github.com/ArctosDB/arctos/issues/3272?

**Comment by dustymc** [comment]
If they correspond to geography, they can be added to search_terms, https://handbook.arctosdb.org/documentation/higher-geography#guidelines-for-geographic-terms-in-arctos.

<img width="416" alt="Screen Shot 2021-03-17 at 12 30 07 PM" src="https://user-images.githubusercontent.com/5720791/111527000-9dba5300-871c-11eb-8fe1-2396ec7e7393.png">

finds

https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=10000319

because 

<img width="304" alt="Screen Shot 2021-03-17 at 12 47 03 PM" src="https://user-images.githubusercontent.com/5720791/111529033-f1c63700-871e-11eb-8d3a-95b2022d09a0.png">


is one example. That's displayed in a few places (including catalog record detail), it could be more prominent. (I added it as a way to automate lookup, it turned out to be kinda cool by itself....)


If they're locality rather than geography then you can just add them to specific locality. Do be aware that I use specific locality for automating georeferences, my sources of that information aren't great with less-than-official (whatever that means...) terms so automation isn't likely to work very well. I'd recommend just georeferencing anything like this, from which point the automation becomes much less important.

**Comment by Jegelewicz** [comment]
From looking at the list - these represent a language difference and what you want is for people to be able to find the same place using both languages?

This seems like a great example of a project that requires funding. A translator table might work? So that searches in specific locality for 'Atna' would return everything from Copper River. Probably a lot of work.

Adding a locality attribute might also work.

Ahtna translation = 'Atna'

**Comment by dustymc** [comment]
>Atna would return everything from Copper River

I'd guess it's not that clearcut -  ’Atna’ probably refers to the general area of the old village (now Chitina, I believe), not the drainage or waterbody or region or .... (And I think perhaps that's actually an uncommon transliteration of what the people call themselves, not what they'd use for a place, but ??????)

>A translator table 

A translator **polygon** would probably be more appropriate.

>funding

Yes, really figuring out what precisely ’Atna’ means, and then figuring out how to store and what to DO with that knowledge, would be (very cool) new development. It would also incidentally fix things like https://github.com/ArctosDB/arctos/issues/3108 - very much not "just a cultural thing," but useful for many purposes across all of Arctos.

**Comment by AJLinn** [comment]
> I'd guess it's not that clearcut 

In terms of this list from the ANLC it's a one-to-one correlation / alternative name for places with names assigned by white people. And more often-than-not these are names that are included in the Wikipedia pages for these locations. Yes, there is a degree of "translation" because of course the names listed as the Native name is what the local people call a particular site that is known by a different English name. Sometimes those English names are transliterations of the Indigenous word for a place (you can clearly see the connection between "Mentasta" (English) and "Mendaesde" (Ahtna Athabascan). Others are not connected (Seward, named for William Henry Seward who negotiated the sale of Alaska vs. Qutalleq, which is an Alutiiq name for the place used by the Alutiiq people who occupied Resurrection Bay prior to the colonization of Alaska). 

As another referenece, there is the _Alaska Placename Dictionary_ (AKA "Orth") that provides a great deal of historical information as well as coordinates of (nearly) every city, stream, glacier, ghost town, and mountain in Alaska that has every been recorded anywhere. Perhaps excerpts of that could be used in these geography references... ooo yes, big funded project! (NatGeo anyone? American Geographical Society?)

I guess partially I need to better understand exactly the geography vs. locality tools to figure out what I want to see happen. Suppose I should watch some webinars and do more reading of the handbook...

One thing that is important is the orthography of how things are written. Special characters are key to referencing these terms appropriately. (E.g., Danzhit Khànląįį  is not necessarily the same as Danzhit Khanlaii).

Anyhoo, maybe this is something that goes on a back-burner somewhere if someone wants to write a grant and have a student do a big project??? Not sure where to take it at this point.

**Comment by dustymc** [comment]
>understand exactly the geography vs. locality

Let us know if you figure it out! There are currently lots of blurry lines in there. #3272 might provide some clarity, or make it so that we don't _need_ clarity, but as of right now what's in table geog_auth_rec is less predictable than an authority should be. That could be a good thing for this....

>Orth

Yep, I'm sure I could find interesting things to do with those data. (Seems impossible that someone hasn't digitized that, but I can't find it.)

>NatGeo

Or USGS? Seems like it could be interesting to someone like that, but I certainly don't know how to talk to any of them. Perhaps even some of the Native groups would like to be involved in some capacity (funders, partners, ????).


>Special characters 

That should be no problem anywhere. ("Formal geography" is by decree ASCII, but that's just an attempt to prevent duplicates and provide predictability.)

>back-burner

For anything that needs funding, probably. You can use milestone 'wish list' to keep this on the radar.

Search terms seems a step in the right direction, is available now, and might be handy to have something to show off as a baseline if we do go asking for funding. I'm happy to help bulkload data or facilitate WHATEVER you'd need to make that happen.

**Comment by Jegelewicz** [comment]
> Search terms seems a step in the right direction

Unfortunately, I don't think most of these terms are "geography" as we define it. They are specific localities and it is hard for me to see how we could facilitate search terms there when any given specific locality might include the place, but not be just the place that has an indigenous name. That's why I suggested a locality attribute and maybe a better attribute would be "search_term" = other names for the same place.

**Comment by AJLinn** [comment]
> Search terms seems a step in the right direction, is available now, and might be handy to have something to show off as a baseline if we do go asking for funding. I'm happy to help bulkload data or facilitate WHATEVER you'd need to make that happen.

I like that idea of loading them as search term - is that visible at the catalog record level?

**Comment by dustymc** [comment]
**are** "geography" isn't really critical (but it does make automagic cleanup work better).

I generally see them as "people might want to find geography by searching....".

We should have better documentation, and perhaps more structure (some sort of "search term relation to geog" value or something), but for now I'm not seeing much evil in pretending they don't do anything except facilitate search.

You can get to catalog records from my example above - https://arctos.database.museum/guid/BYU:Herp:20940 contains

<img width="617" alt="Screen Shot 2021-03-18 at 11 41 20 AM" src="https://user-images.githubusercontent.com/5720791/111679907-e20e2780-87de-11eb-8456-06a53c6b08e7.png">

Or it's trivial to fire up a new locality attribute if that's better - and it may be, AK is a big place without very good "natural" subdivisions.

**Comment by Jegelewicz** [comment]
> is that visible at the catalog record level?

Dusty says yes in higher geography above and locality attributes are visible as well - see https://arctos.database.museum/guid/NMMNH:Paleo:1

![image](https://user-images.githubusercontent.com/5725767/111704378-a71eea80-8804-11eb-8c94-10b4a896b664.png)

> AK is a big place without very good "natural" subdivisions.

 'Atna' would be associated with a quad map. How many other indigenous names would be associated with the same quad? Maybe that would be good enough though!
