### ISSUE TITLE
LastPartLocation not encumbered in search results

### ISSUE THREAD

**Issue by krgomez** [ArctosDB/arctos#3535]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
I just happened to notice that the LastPartLocation, a search results field, displays data when logged out. This is a security issue as this field displays the current physical location of an object.

**To Reproduce**
1. Be logged out
2. Open some catalog record results
3. Have LastPartLocation checked as a data field option
4. See that this is not encumbered to the public

**Expected behavior**
This should show something like "not available" which we see for things like partdetail or "masked" like we do for encumbered attributes. 

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.2.3
 - Browser: Firefox
 - Version: 86.0.1

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.
High

**Comment by dustymc** [comment]
I removed it as an option and left a note in https://github.com/ArctosDB/PG_DDL/blob/master/function/getLatestPartLocation.sql

If there's some compelling reason to add that (or something like it) back in, it will need built in to the cache (or similar).

**Comment by AJLinn** [comment]
I'd like to discuss what our options are for getting the same function of "last part location" in the search results without downloading the part info and manipulating a spreadsheet while also avoiding causing the issues that other collections apparently have. 
I don't even know how to start this conversation so please provide advice. I don't understand how an encumbered field is visible in a public search. I don't understand the other options that might be available. I have barcoded probably less than 10% of my collection so this was really a saving grace in working efficiently in my collections space.

**Comment by dustymc** [comment]
>understand how an encumbered field is visible in a public search

It's not a "field" - it's any number of fields, all of which are children of parts. I generally use functions to squish that kind of thing into something that'll fit in a spreadsheet - a "field." Functions don't perform great, but they're super-easy to use and only use resources on demand, so that's what we'd done here. When performance is an issue, the function runs asynchronously and the results get cached in a field, which requires CPU and storage. It also provides a mechanism to filter the "field" - certainly not the only possibility, but it's the one that fits in the current setup.

The long version of all that is https://github.com/ArctosDB/arctos/issues/2938 - just using functions seems to always find a way to cause a problem (generally performance, now security), and that additional CPU and storage adds up. I'd really like The Community to be more involved in deciding how to respond to these kinds of requests; my vote would be to find more resources when we need them (which is more realistic under the current architecture than it was under Oracle, at least), but I'm not sure how that lines up with reality.

Lacking better ideas, I'll assume that discussion isn't going to happen any time soon and just add this to the internal cache.

**Comment by AJLinn** [comment]
> Lacking better ideas, I'll assume that discussion isn't going to happen any time soon and just add this to the internal cache.

I don't want to be the single-handed result for causing searches in all of Arctos to stall out... I would just like to learn how to get the same functionality without breaking things. Thank you for explaining how those data create problems for the rest of the operations of Arctos. If it's going to break everyone else's results, please don't worry about adding it to the cache - it might just be a matter of sitting down with someone to walk me thru the other options.

**Comment by campmlc** [comment]
Angie, I'd be happy to discuss potential tools in object tracking that
might be useful, but I'd need to know more about your system. I also have a
significant chunk of our collection without barcodes, but we migrated
legacy data into a functional tool to bridge the gap with Dusty's help. I
now barcode samples as I handle them, but can still use object tracking to
locate unbarcoded samples. Not sure if this would be an option in your
case, but happy to do a call and talk it over.

**Comment by dustymc** [comment]
A single new "field" - especially this one, which doesn't hold much data - isn't going to do much, it's a cumulative effect. And I don't think anyone else uses this, so I don't need to refresh everything, which makes the immediate bits easier. I don't think there's much reason to not do this, but I'd still like The Community to be more involved in making these strategic decisions that do have long-term costs. Our Oracle install went from incredibly fast to barely functional over the course of several years, I'd very much like to never find myself painted into that corner again.

>use object tracking to locate unbarcoded samples

That should be a how-to/webinar/something. Containers get you into a much more powerful system, and...

>barcode samples as I handle them

... seems exactly the right approach to me. If there's a way to get into the container ecosystem with a similar amount of work as part attribute "location," we should be highlighting it.

**Comment by dustymc** [comment]
This is available again, UAM:EH is set to refresh, please close if testing is satisfactory.

**Comment by AJLinn** [comment]
Sweet - LPL no longer shows up in public view even if you try to add it as a column. Closing.
