### ISSUE TITLE
 Provide option to exclude webservice Standardized Place Name (SPN) in public view of catalog records

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#3562]
This is partially a bug and partially a feature request.

Catalog records now automatically show the "Standardized Place Name" (SPN) associated with the locality coordinates.  See GitHub [#3272](https://github.com/ArctosDB/arctos/issues/3272).  This is a very helpful service for curators and collection volunteers to verify and standardize locality records.  However, not all SPNs are accurate or meaningful and many distort the verbatim locality.

**Proposed Solution:**  Do not include the Standardized Place Name in the public view of the catalog record.  Whether or not to show the SPN could be a selection for that collection in the Manage Collection tab.  The SPN would be included just as it is now for all Arctos users with data entry or other general authority for that collection.  

An additional enhancement would be for collection managers to toggle back on the public view of the Standardized Place Name for an individual locality once it is reviewed.  This would not remove the details for the SPN from the locality detail page if a public user wanted to see that data.

**Examples** of current issues:

1.  The SPN adds greater specificity than in the verbatim locality.   

The [locality](https://arctos.database.museum/place.cfm?action=detail&locality_id=10903491) for [DMNS 27813](https://arctos.database.museum/guid/DMNS:Inv:27813) adds a specific area (Ampang/Empang) and a town (Moyohulu) to the place name when the catalog record only specifies the island province Sumbawa.  

<img width="599" alt="Screen Shot 2021-04-10 at 8 49 02 AM" src="https://user-images.githubusercontent.com/15368365/114273985-a4fe1500-99d9-11eb-9e56-18b5bcb17b1a.png">

<img width="641" alt="Empang, Moyohulu, Indonesia" src="https://user-images.githubusercontent.com/15368365/114274149-60bf4480-99da-11eb-8e7b-7c13716b11ee.png">

Similarly, other records add a specific county or city when the verbatim locality is only the state.  [DMNS: Inv 10304](https://arctos.database.museum/guid/DMNS:Inv:10304) has only the state of Florida as the verbatim locality.  But the locality (with coordinates) [1121738](https://arctos.database.museum/editLocality.cfm?locality_id=1121738) used by DMNS and MSB includes Polk County and Highlands County. 

<img width="658" alt="Screen Shot 2021-04-10 at 9 26 08 AM" src="https://user-images.githubusercontent.com/15368365/114275192-d0cfc980-99de-11eb-8c82-494d87e3b1aa.png">

More concerningly, the same SPN shows up on Florida records that have no coordinates.  This includes 960 records from multiple collections.  See [locality 11153495](https://arctos.database.museum/place.cfm?action=detail&locality_id=11153495) and an example of a record from UTEP Herp:

<img width="788" alt="UTEP:Herp" src="https://user-images.githubusercontent.com/15368365/114274888-ac272200-99dd-11eb-807f-c286df4baf0f.png">

2.  Some SPNs are wrong. 

[Locality 10904124](https://arctos.database.museum/place.cfm?action=detail&locality_id=10904124) for the Dampier Archipelago in Australia shows an SPN of Leonora Shire in the middle of the desert.  

<img width="1239" alt="Screen Shot 2021-04-10 at 9 07 35 AM" src="https://user-images.githubusercontent.com/15368365/114274554-37071d00-99dc-11eb-9112-e716d8135009.png">

We may be able to resolve all of these over time and the SPN service is helpful.  But having the SPN be part of our public record while we're still working out the details leads to a lot of misrepresentation of the verbatim locality in the catalog record.   

**Priority**  High

**Comment by ebraker** [comment]
Just encountered this issue with UCM records. Is there a way to simply exclude standard place names when specific_locality = "no specific locality recorded" or "no specific locality data recorded" or "no data"? I know records will be missed given all the various flavors of 'no data' transcribed in the field, but this might capture a solid swath of records and eliminate confusion. 

![image](https://user-images.githubusercontent.com/11336485/119561372-51197680-bd62-11eb-942d-9bee093008e9.png) from https://arctos.database.museum/guid/UCM:Mamm:3157.

If this is too complex, I don't feel super strongly about masking SPNs since it does not appear to affect search functionality (e.g., querying a long-tailed weasel in Summit County does NOT return my coarse-resolution Colorado record that has the random Summit County SPN applied). But it would be nice!

**Comment by dustymc** [comment]
https://handbook.arctosdb.org/documentation/locality.html#specific-locality

``No specific locality recorded.`` is handled better than the variations.

>does NOT return

The webservice data are only used via the documented (poorly, probably) search options - county (and such) consider only asserted data.

And from there back to the original request, I think the service-derived data are critical for all the reasons discussed in https://github.com/ArctosDB/arctos/issues/3272, and landing on a record with no indication of how you might have got there isn't great design. Somehow doing a better job of communicating what's derived (vs asserted) and what it does seems much more useful to me, and I'm very receptive to clever ideas on that front.

**Comment by dustymc** [comment]
I can't think of how a pick would work, but I could add a button to various forms if that might help.

**Comment by campmlc** [comment]
Maybe when any flavor of "no specific locality" is entered, a popup or
dropdown appears with the "valid" version, e.g. as we do with taxon names?

**Comment by dustymc** [comment]
>as we do with taxon names?

All possible valid taxon names are in an authority. There's no limit on the things that are valid, even good, specific localities.

https://github.com/ArctosDB/arctos/issues/2353#issuecomment-548542728

**Comment by dustymc** [comment]
See also https://github.com/ArctosDB/arctos/issues/3272#issuecomment-819691228

"Category" (needs a better name) could also be used to tell the services to stop at state/county/whatever.

**Comment by sharpphyl** [comment]
I've tried to clean up a lot of locality records with the "No specific locality recorded." variants.  Many of them are shared localities and I really don't want to generate a ton of change records for other collections.  Could a mass update to the correct version be approved by the AWG and done as a group?

**Comment by campmlc** [comment]
Great idea.

**Comment by dustymc** [comment]
Is some Arctos user conceivably invested in some alternate way of saying "we have nothing useful here" to such an extent that this needs approval?

**Comment by campmlc** [comment]
I would say no. Otherwise, they'd be participating in this discussion.

**Comment by sharpphyl** [comment]
Being able to mask SPNs would be extremely helpful for our collection.  Almost daily, we find SPNs that are erroneous or misleading or confusing.

**Comment by dustymc** [comment]
>SPNs

See https://github.com/ArctosDB/arctos/issues/3272#issuecomment-850523922, there's new terminology/data/appearance, it may or may not help resolve this issue.

>mask

"We don't care, don't try to make this better" could be a "category" (https://github.com/ArctosDB/arctos/issues/3272#issuecomment-819691228, which isn't quite current from a couple comments down, linked above). I'm still not a fan, just pointing out a plausible path to where I think you're asking to go.

>erroneous or misleading or confusing

One source of that is bad assertion data - in your case that commonly takes the form of "some reference to, but not included in, some terrestrial place." 

I don't think I understand something fundamental about this. It looks to me like we're on a path likely to result in better assertion data, expose problems in assertions, etc., etc., etc., - just make things **better** for everyone, despite some imperfections in the current implementation. I don't understand the apparent desire to undo that.

**Comment by sharpphyl** [comment]
> See #3272 (comment), there's new terminology/data/appearance, it may or may not help resolve this issue.

Let's see how these records look after you take this into production.  It sounds like a helpful step.

**Comment by KyndallH** [comment]
I'm not sure if I should post this here or on #3272 but Associated Names is horrible (understatement). Point Hope is not even remotely close to SE AK or British Columbia. Shishmaref --> Exclusive Economic Zone? Why is this data added to our specimens records? It isn't data that we entered or was provided by the collector. What is the point except to confuse those that are not familiar with the geography of a location? Can we opt out completely of SPN/Associated place names?  @amgunderson @AJLinn 

<img width="1041" alt="Screen Shot 2021-07-02 at 3 31 20 PM" src="https://user-images.githubusercontent.com/16887896/124336803-fc7cce80-db4b-11eb-93d9-b3ee43ab55e3.png">

<img width="1023" alt="Screen Shot 2021-07-03 at 9 50 13 AM" src="https://user-images.githubusercontent.com/16887896/124362873-529d5080-dbe4-11eb-8bac-58020c5b2828.png">

Valdez is not even remotely near Quartz Lake.

<img width="1066" alt="Screen Shot 2021-07-02 at 3 44 24 PM" src="https://user-images.githubusercontent.com/16887896/124362890-6648b700-dbe4-11eb-8df2-26e59efa2a29.png">

<img width="921" alt="Screen Shot 2021-07-03 at 9 57 36 AM" src="https://user-images.githubusercontent.com/16887896/124363034-58476600-dbe5-11eb-8de0-e896e0821259.png">

<img width="905" alt="Screen Shot 2021-07-03 at 9 58 55 AM" src="https://user-images.githubusercontent.com/16887896/124363036-5a112980-dbe5-11eb-8c10-96a1aa4144e1.png">

**Comment by AJLinn** [comment]
> Associated Names is horrible (understatement).

I agree 100% - we have countless number of items with "unknown" as the locality and the Associated Names brings up North Carolina? I'm not clear where the associated names come from.

**Comment by dustymc** [comment]
I (obviously) think that these data are important because of our internal inconsistencies, but display is just CSS - there will be some hopefully-obvious new CSS options in next release, you can set them in manage collection.

CSS has been an option for a very long time, maybe we need to somehow make that more obvious/accessible/whatever's missing.

Links are incredibly useful, and the 'more' links will provide more information on the source of those data. I think the things @KyndallH  dislikes are just about exactly the things that @sharpphyl  is hoping to accomplish, and that's basically the problem as it's laid out in the other issue - we WANT to say "there" in multiple ways based on things like what was collected, so nobody can find anything through our "authority" data. I'd still like to look for a palatable solution, but there's an option to just hide these.

@AJLinn I'm guessing without links, but that sounds a lot like https://github.com/ArctosDB/arctos/issues/3562#issuecomment-848243609 / https://handbook.arctosdb.org/documentation/locality.html#specific-locality / https://github.com/ArctosDB/arctos/issues/2662

The origin is https://handbook.arctosdb.org/documentation/locality.html#service-derived-data.

**Comment by sharpphyl** [comment]
@dustymc  What's CSS and how do we manage it?  

I'm not so sure @KyndallH and I see this issue that differently.  Having a service-derived suggestion on a locality is fine. It could be similar to the the service-derived taxon status on each taxon name.  But having it in the public record when so many of them are way off target is misleading and confusing.  If we can control what's public and what's for internal use, that should be adequate as we continue to look for other solutions to improving locality data.

**Comment by dustymc** [comment]
>What's CSS

A "language" to control layout (in this case by hiding an element).

>how do we manage it?

Depends, and there are two components. To do this (and similar simple things) you can tell me what you want to do and I can edit your CSS file. For more complex things you'll probably want to figure out CSS and GitHub (or maybe change how the collection-specific CSS is created or WHATEVER - we can talk if there's a directed interest). 

Once there's a sheet in the repository, you can just select it under manage collection to use it.

> If we can control what's public and what's for internal use, 

That's basically the problem. You want to call the place at coordinates (x,y) "there" because of whatever random reason, some other collection (or the same collection for some other taxon, or ...) wants to call it "something else" for different reasons (which is exactly what we've always done). Some poor user shows up, searches "something else," finds some of what they want, and leaves with it and no way of knowing they missed some records. Sucks to be them, end of story.

The webservice data provides a consistent relationship between spatial and descriptive data. Everything at (x,y) gets the same textual data, no exceptions. Users can find all of what they want without guessing at our arbitrary decisions, yay everybody.

You're trying to claim the data which exists for the user as "yours," which puts us back where we started. I'm offering a compromise, where the users can still discover your data via the webservice data, but nobody can see it. I don't think that's great design, but users finding what they want for mysterious reasons is better than not finding it at all so here we are.

**Comment by KyndallH** [comment]
@mkoo  Here is the issue I was referring to!

**Comment by mkoo** [comment]
Yes we were just talking about Associated Names as sometimes being wrong
and misleading like many for Alaska. At the least let CSS hide it from a
record detail page.
Here's the one I plucked from Kyndall's stuff that is hilariously wrong
(site is not in Kansas!) I dont know how GM services got it so wrong
(unless there's a bad cache somewhere?)
[image: Firefox_Screenshot_2021-08-19T22-33-12.199Z.png]

So maybe until they can be useful to the curator, Assoc.Name should be
hidden from the detail view as default? If I am editing the locality then I
it makes sense to see some Google Maps services reference, right?

**Comment by dustymc** [comment]
Your screenshot didn't come through - a link would be better.

Please scroll up, this isn't for "us"....

**Comment by Cynthia-Carr** [comment]
https://arctos.database.museum/guid/UAM:Mamm:60952


________________________________

**Comment by dustymc** [comment]
<img width="551" alt="Screen Shot 2021-08-19 at 5 17 33 PM" src="https://user-images.githubusercontent.com/5720791/130160028-af6816fe-523d-4ef2-b604-90af60a70899.png">

https://handbook.arctosdb.org/documentation/locality.html

<img width="522" alt="Screen Shot 2021-08-19 at 5 19 41 PM" src="https://user-images.githubusercontent.com/5720791/130160098-eea25107-656c-46ea-a4be-14ac10c0c9ce.png">

**Comment by Jegelewicz** [comment]
One thing I can see here is that the Specific Locality IS known, but entered as unknown in an incorrect format. I'd be curious to see what happens if Specific Locality was changed to "Sheep Creek Valley". I think I'll go do that in test....

**Comment by dustymc** [comment]
> IS known, but entered as unknown in an incorrect format.

I don't think that's always something you can infer from strings - there might be a few (or zero) things that share a name, and any of them may or may not be on any given map. If that's the reasoning it should be in remarks, but..... 

Maybe we should do something about https://github.com/ArctosDB/arctos/issues/2662 - I'm not thrilled with the idea of changing even that, specific locality exists as an already-interpreted assertion, but that's obviously not being implemented according to the docs and surely SOME of https://github.com/ArctosDB/arctos/issues/2353#issuecomment-548542728 can be safely "translated"??

I think all of these complaints have come back to some sort of data problem, and many of those have involved providing variations of "nothing" that look like "something" to the services. Maybe we should somehow better convey the likely causes of wildly wrong service data?

**Comment by Jegelewicz** [comment]
> Maybe we should do something about #2662 - I'm not thrilled with the idea of changing even that, specific locality exists as an already-interpreted assertion, but that's obviously not being implemented according to the docs

It would be great if there was a way to check a box when there really is "No specific locality recorded." so that we don't get a million variations of that. Honestly, it might work the way we do things now if it was just "none" or NULL instead of a sentence that no one can remember the structure for and no one looks up.

> many of those have involved providing variations of "nothing" that look like "something" to the services.

What looks like "nothing" to the services? I would assume it is NULL to be safe because there probably is a None, Texas. If that is the case, could we start by sending NULL to the service whenever "No specific locality recorded." is there?

**Comment by dustymc** [comment]
>check a box 

There are many ways to create a locality, and anyone could build another at any time. I'll add something to edit locality, but I just don't think it's ever going to be a replacement for reading documentation.

>NULL

Yes, that (the value, not the string) would be ideal, but people don't like it (for reasons that I don't quite understand). That's what I "translate" “No specific locality recorded.” to before passing it off to the services.

(And I played with just ignoring specloc altogether, but there are a ton of "Continent or something equally inappropriate, specific thing that the services can understand" data.)

>What looks like "nothing" to the services?

https://handbook.arctosdb.org/documentation/locality.html

<img width="678" alt="Screen Shot 2021-08-20 at 8 04 58 AM" src="https://user-images.githubusercontent.com/5720791/130253814-a01f96d2-3376-4c05-a82e-f84fe7411943.png">

>probably is a None, Texas

There's something a lot like that in KS and NC....

**Comment by sharpphyl** [comment]
> @sharpphyl there's a spreadsheet in #2662 (comment)

For our collection, all your suggestions in the spreadsheet would be fine.

I'm leery of correcting any shared locality.  I seem to trigger a locality change report even when I just look at a shared locality, e.g., https://arctos.database.museum/info/localityArchive.cfm?locality_id=11420794

**Comment by sharpphyl** [comment]
Have you considered adding the option "none" by the Specific Locality field on the data entry screen that would auto fill correctly if you click it?

<img width="683" alt="Screen Shot 2021-08-31 at 10 26 41 AM" src="https://user-images.githubusercontent.com/15368365/131547023-58e4dca4-d0f1-43dd-bfc8-6de57f30b771.png">

**Comment by dustymc** [comment]
>data entry screen

https://github.com/ArctosDB/arctos/issues/2662#issuecomment-902826360

<img width="685" alt="Screen Shot 2021-08-31 at 10 24 49 AM" src="https://user-images.githubusercontent.com/5720791/131548234-a8902b41-f543-4efe-8f01-179b4974419b.png">
