### ISSUE TITLE
Component Loader: v3

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#3582]
The problem is that anyone looking at the data in the following form has no means of going back and finding the collection object that it was supposed to append to if there is a problem with the cataloged item or the linking of the uuid to it. I don't know how to say this more clearly:
![image](https://user-images.githubusercontent.com/14808196/116448475-67d9b580-a816-11eb-9956-62396d575ae7.png)

_Originally posted by @campmlc in https://github.com/ArctosDB/arctos/issues/2240#issuecomment-828647443_

**Comment by dustymc** [comment]
URLs of the following format will be functional in next release:

```
/Bulkloader/browseBulk.cfm?uuid={UUID}
```

Component loaders could build links to that.

@campmlc does that do what you're asking?

**Comment by campmlc** [comment]
Yes, I think so? So there wouldn't be any broken links, unless someone
deletes the uuid from an already cataloged record?
If the record is cataloged, can the link in the component record go to the
catalog record prior to load? That way we can tell which of multiple uuids
are associated with which data in a given catalog record.

**Comment by dustymc** [comment]
>unless

Don't underestimate users' creativity! Anyone messing with the UUID from any angle in any way will break links. (There are at least three opportunities - component loader, bulkloader, catalog record - for all of these.) EVERYTHING in Arctos is ultimately reliant on procedures and documentation being followed.

>If the record is cataloged

I won't know what until the procedure runs, but I could add a second link to eg https://arctos.database.museum/SpecimenResults.cfm?oidtype=UUID&oidnum=fec50edd-78ea-4c8e-8180-a0ebfde95479&oidoper=IS

Alternatively, we now have the tools to just create these "components" with status=autoload. If we were to do that, I don't think you'd ever see these problems (but see above), and the rare time you do copy-pasting the UUID in one of the search fields (catalog record or next release browse-and-edit) might be sufficient to resolve them.

**Comment by campmlc** [comment]
I think creating components with status autoload has a lot of advantages,
especially since, right now, reviewing the data without the url link to the
bulkloader is essentially pointless. But even with the added link to the
bulkloader it woudl be a hugely difficult task to review and verify between
the two tools. One thing that would be more helpful is to provide a way to
review and edit "extras" added from the single record data entry page -
because if a student enters something wrong, in the current scenario the
data vanish from view on entry, cannot be reviewed without leaving data
entry and having permissions to view the component loaders, which don't tie
back to the data entry record. Can we keep the extras table associated with
a single record data entry page as a popup that can be reopened and viewed
during data entry, for verification?

**Comment by dustymc** [comment]
<img width="217" alt="Screen Shot 2021-04-28 at 11 15 42 AM" src="https://user-images.githubusercontent.com/5720791/116452990-301d3e80-a813-11eb-935b-d3bd1e300e7e.png">

<img width="339" alt="Screen Shot 2021-04-28 at 11 16 57 AM" src="https://user-images.githubusercontent.com/5720791/116453128-57740b80-a813-11eb-8c17-43caeeaa3788.png">

**Comment by campmlc** [comment]
And this is visible to and editable by students with data entry permissions?

**Comment by campmlc** [comment]
Question about the component loader interface: When I go to Review and Load, and I check "Check All and Set Status to Autoload", the check all happens, but the status doesn't change. In order to actually get records to set to autoload, I have to additionally click "Change Status for Checked Records". This seems to be a glitch, since options already exist to do each of these steps independently. In my understanding, the check all AND change status option should do both of those things.

**Comment by dustymc** [comment]
<img width="814" alt="Screen Shot 2021-05-03 at 8 07 50 AM" src="https://user-images.githubusercontent.com/5720791/116894243-aee4f380-abe6-11eb-84c7-e3975cea1431.png">

**Comment by Jegelewicz** [comment]
@campmlc 

"Check All and Set Status to Autoload"

checks them all and sets the status

"Change Status for Checked Records"

saves the status.

**Comment by campmlc** [comment]
That isn't intuitive to me, and likely not to others. If that is the way it
will be,then don't we need to add that final step to the documentation as
published in the newsletter?

**Comment by Jegelewicz** [comment]
Feel free to add it!
