### ISSUE TITLE
How to find and use polygon data to create marine localities and WKTs

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#3595]
This is a follow-up to #3272 and #3562 

Current shapefiles/WKTs are primarily terrestrial and result in localities/geolocation for marine specimens that are considered in error because they fall outside the WKT or that generate a confusing and misleading Standardized Place Name (SPN).  

Per @dustymc suggestion in #3272 I looked for a sources of appropriate coordinates for most frequently used marine localities.  We have over 500 specimens from the Great Barrier Reef.  The SPN for that locality places it in the middle of Queensland, so it seemed like a good candidate for clean-up.

One source of coordinates (not listed on the locality 10905237) is https://www.ngdc.noaa.gov/gazetteer/ or GEBCO

<img width="1351" alt="Screen Shot 2021-05-01 at 10 01 12 AM" src="https://user-images.githubusercontent.com/15368365/116787929-35bd9300-aa64-11eb-9cca-190e8c289419.png">

A download of the polygon coordinates returns this: POLYGON ((143.33445046 -12.23103787, 143.52171039 -12.52184726, 143.66120078 -13.08407595, 143.72142937 -13.45529873, 143.77609298 -13.78117963, 144.04990237 -14.0630847, 144.61122123 -14.12963397, 144.76348765 -14.3561338, 145.06881702 -14.59118474, 145.3725956 -14.83577868, 145.42278577 -15.48625777, 145.57503281 -15.87760062, 145.70159974 -16.38990503, 145.90967659 -16.67272055, 146.39881523 -17.71387437, 146.53452536 -18.081982, 146.67873752 -18.37231954, 147.05883908 -18.68035144, 147.97186912 -19.39145128, 148.66665052 -19.51515337, 149.9112762 -20.55147562, 150.37107598 -21.13739814, 151.36288823 -21.59889204, 151.93064418 -21.92052911, 152.39192759 -22.32361817, 152.63827776 -22.44325529, 152.82378634 -21.99407604, 152.64612335 -21.45508853, 152.81813221 -21.08654217, 152.07105814 -20.95715027, 151.27206135 -20.74549798, 150.77348966 -20.05916432, 149.78355884 -19.47371632, 148.55236099 -18.90095998, 147.52069447 -18.32969189, 146.8151126 -17.65977693, 146.62659835 -16.98405846, 146.20667102 -16.43146238, 146.00623092 -15.83430614, 145.85899524 -15.1145813, 145.77889015 -14.75322897, 145.57409719 -14.45001464, 144.90771615 -14.10137374, 144.70443746 -13.9172679, 144.4209867 -13.82045933, 144.16782516 -13.53888954, 144.05146251 -13.27980631, 143.97180529 -12.86503151, 144.03799452 -12.24853254, 144.12105762 -11.74161131, 144.12231523 -10.99803925, 143.99533742 -10.37466099, 144.10761205 -9.98029298, 144.19363561 -9.54885987, 143.85268391 -9.31028865, 143.46175598 -9.23314794, 143.23450345 -9.54783357, 143.03909617 -10.10493172, 142.98357993 -10.77774372, 142.93001957 -11.37608197, 143.06614289 -11.76228089, 143.30363327 -11.92185684, 143.33445046 -12.23103787))

Exporting the results as a shapefile returns these files which I can't read:

<img width="242" alt="Screen Shot 2021-05-01 at 10 05 01 AM" src="https://user-images.githubusercontent.com/15368365/116788041-b8465280-aa64-11eb-9c4b-8f969543827a.png">

Can we do anything with this data to create a useable WKT for the Great Barrier Reef?  It is administratively controlled by Australia.  It is in the Coral Sea which in our current higher geography has no reference to Australia.

Is this data of any value?  Are there other collections with marine localities who can participate in selecting and confirming appropriate coordinates for these marine areas?  There are other websites with similar data for EEZs but this looked like the best feature to start with.

**Comment by dustymc** [comment]
I think perhaps you're mixing up some components, but maybe I'm just not understanding too. I'm certainly not understanding if you're wanting to create geography or locality data.

There are 2 places for WKT in Arctos - both need better documentation.

https://handbook.arctosdb.org/documentation/locality.html#wkt-polygon is "fancy coordinates" - its your assertion. I don't think it DOES anything at all, other than make some not-necessarily-circular splotches on some maps. You can make this by clicking the button from GeoLocate, or by creating a Media containing WKT and saving it in the locality, and there could be other ways - it's just data.

https://handbook.arctosdb.org/documentation/higher-geography.html (geography WKT, there's not even anything to link to!) is essentially a quantification of the geography assertion. It is functional; it results in annotations and such. You can create WKT here by creating Media and editing the geography, but that's "authority data" and should be discussed beforehand.

"Standardized Place Name" comes primarily from the point of point-radius assertion data via webservices - it doesn't much use any of the above.

https://arctos.database.museum/guid/DMNS:Inv:10072

says

Australia, Australia, Queensland, Great Barrier Reef 

I don't think there is any such place - Queensland looks like...

<img width="239" alt="Screen Shot 2021-05-03 at 7 33 13 AM" src="https://user-images.githubusercontent.com/5720791/116889804-d84f5080-abe1-11eb-850e-c6b1d1f92b68.png">

and the reef is someplace else. If that's not causing problems, it's only because we don't have enough sophistication in the checkers (yet, I hope). 

We need marine geography (speaking of self-conflicting terminology....). "Standardized Place Name" is an attempt to get something like that without figuring it out for ourselves, but here you're giving it conflicting data so it's giving you something that may not make a lot of sense. https://github.com/ArctosDB/arctos/issues/3272#issuecomment-819691228 ("is marine" flag) would provide a bit more information, and I could assemble what we're doing now into any/combinations/whaever of:

* Australian Exclusive Economic Zone (via EEZ)
* Coral Sea (via IHO)
* CORAL SEA (via SeaVoX)

and maybe treat them as geography in some way (eg to bootstrap better data).

(You can see those in the Locality section of eg https://arctos.database.museum/place.cfm?action=detail&locality_id=10905237)


>administratively controlled by

That's a major problem - it results in https://handbook.arctosdb.org/documentation/higher-geography.html#country and sometimes GBIF throwing up "that ain't France!" errors and other times moving bits of Antarctica to Europe. Probably a separate Issue, but I wonder if just ignoring administration that wouldn't be better? 

>Coral Sea

That seems correct to me - any "parent" is just going to be confusing, there are no "children" that I can find, dirt-things are mostly irrelevant, why aren't we just using this for geography?

Given unlimited resources, what would you like to have for "spatial authority data" for this example? ("Nothing" is always a perfectly valid answer, and one I would seriously consider from your position.)

I think https://www.ngdc.noaa.gov/gazetteer/ is "IHO" in GBIF so we're already using those data - but if they - or anyone else - has a webservice that can turn something we have into something better than what we have, I'm up for exploration.

**Comment by sharpphyl** [comment]
I followed your link ( https://www.ngdc.noaa.gov/gazetteer/) to this data on the Great Barrier Reef but have no idea what to do with it now.  


<img width="1582" alt="Screen Shot 2021-05-18 at 2 32 37 PM" src="https://user-images.githubusercontent.com/15368365/118720265-a562aa80-b7e6-11eb-9863-565edb262d13.png">

> "Nothing" is always a perfectly valid answer, and one I would seriously consider from your position.

Yes, I think that's the best thing to do at this point.  We can revisit this at a later time.
