### ISSUE TITLE
Bulk edit localities?

### ISSUE THREAD

**Issue by mlbowser** [ArctosDB/arctos#3599]
Is there a way to update localities in bulk? I need to update core locality data of > 200 locations from a project where coordinates, specific locality, etc. should be updated to reflect additional plot numbers (for easier cross-referencing among datasets) and legally comply with data sharing agreements. 

I do not see an easy way to bulk download locality ids from all specimens in a project/accession, but I could get these data from <https://arctos.database.museum/tools/userSQL.cfm>. I did not see locality id among the add or remove data fields (columns) in search results.

I would like to retain all relationships between localities, collecting events, and catalog records from this project (currently 5346 catalog records), so it seems to make sense to keep the locality ids and update the values rather than creating new localities-events-catalog record relationships. This could be done manually, but it would be error-prone and it would take a long time.

**Comment by dustymc** [comment]
There is no way to bulk-edit localities, and I'm not sure there could be a safe one - someone could use one of "your" localities milliseconds before you change it, etc.

Locality_id is not a stable identifier - they are constantly changed by scripts. You can name localities, and https://arctos.database.museum/place.cfm?sch=locality-->search-->
<img width="173" alt="Screen Shot 2021-05-04 at 9 46 27 AM" src="https://user-images.githubusercontent.com/5720791/117039430-9f84a980-acbd-11eb-8292-af870aaad73b.png"> will let you do that in bulk (and then download the named localities).

You can also download localities from a couple places in the Manage widget on specimenresults.

You can bulkload specimen-events.

The scripts that make locality_id unstable will eventually merge any duplicates you manage to create along the way.

We generally recommend adding rather than replacing. Setting https://arctos.database.museum/info/ctDocumentation.cfm?table=ctverificationstatus#unaccepted is functionally identical to replacement from most views, but has no chance of losing history/data.

You can probably put that all together to replace localities, but I can't point you to a step-by-step approach at the moment, and there may well be a missing tool somewhere along the way. That seems like something we should have, and have documentation for. If you want to provide more details (and I'm sure answer a bunch of questions along the way) I can figure out what we need to do this and document the process.

**Comment by mlbowser** [comment]
Thank you, Dusty, I will explore those options you listed.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
This is relevant to https://github.com/ArctosDB/data-migration/issues/130#issuecomment-1022383485.

**Comment by dustymc** [comment]
>I'd like to take UTM and biota remarks out of locality remark. Will you be able to batch edit the localities if I create a csv with locality name, utm_ew, utm_ns, utm_zone, datum, locality remark (to replace current locality remark), georeference source (to be appended to current georeference source), and biota remarks? These will only be named NMMNH localities, and shouldn't be anything that is shared with anyone (but of course we can check before editing).

How about something like https://arctos.database.museum/tools/bulkloadLocality.cfm?action=ld, minus locality_id, which would essentially do...

```
update locality set {everything}={stuff from file} where locality.locality_name=uploaded.locality_name
```

That would not deal with "append" in any way, but that should be easy enough to manage in the CSV. It would only work with named localities, but there are tools to do that (and un-do it after the update if necessary/desirable).

That would leave open the possibility of naming some shared locality and then mangling it, but we're all making sure we don't grant manage_locality to anyone who would do that (right?!) so I'm happy to call that a matter of documentation if ya'll are....

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
That sounds good. Could we make something to go with it that would allow a pre-check of which collections are using the localities you are about to batch update. In case some other institution has decided to use one of my named localities, it might be a good idea to contact them first.
