### ISSUE TITLE
Code Table Request - mg is in units of volume code table, but should be in units of weight?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3648]
**Goal**
Make our "units of" code tables consistent

**Context**
request for new unit value units = ng/uL see https://github.com/ArctosDB/arctos/issues/3624#issue-904730629 made me take a look at our current "units" code tables. While adding definitions, I noticed this inconsistency.

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctweight_units

**Value**
mg

**Definition**
milligram = 10<sup>−3</sup> g. <a href="https://en.wikipedia.org/wiki/Kilogram#SI_multiples" class="external">Wikipedia</a>

**Priority**
Setting as high because messes are being made?

Then correct unit dependencies and remove this from https://arctos.database.museum/info/ctDocumentation.cfm?table=cttissue_volume_units

**Comment by dustymc** [comment]
I think you may be bumping into the structure of the model. 

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspec_part_att_att#remaining_volume requires that all "remaining volume" determinations use units from https://arctos.database.museum/info/ctDocumentation.cfm?table=CTTISSUE_VOLUME_UNITS, and those reasonably might include...

* weighs xx [milligram]
* volume is xx [millilitre,microlitre]
* volume is xx [percent] occupied

I think occasionally we're just going to have mixed units and code tables that only do one thing because they require mixed units, although I'd obviously much prefer to reuse CTs when we can (and so avoid another opportunity to spell "meters" 37 different ways).

The alternative is to have "remaining weight" and "remaining volume" and "remaining whatever" all using separate CTs, which seems somehow slightly worse than the current approach.

That said, 

```
arctosprod@arctos>> select attribute_units,count(*)  from specimen_part_attribute where attribute_type='remaining volume' group by attribute_units;
 attribute_units | count 
-----------------+-------
 mg              |  4951
 mL              |    39
 µL              |    63
```

things get added for overly-theoretical reasons, nobody's used percent, maybe it's not necessary, it's easy to delete right now, it's not difficult to add back with justification and definition if necessary. I'd say delete it if nobody comments here in the near future.

**Comment by Jegelewicz** [comment]
Tried to delete - got this

![image](https://user-images.githubusercontent.com/5725767/121385993-daa27a00-c906-11eb-8ec1-fc05e3fd21b8.png)

I'd like to get rid of it here....

**Comment by dustymc** [comment]
```
arctosprod@arctos>> select guid,attribute_units,attribute_value from specimen_part_attribute inner join specimen_part on specimen_part_attribute.collection_object_id=specimen_part.collection_object_id inner join flat on specimen_part.derived_from_cat_item=flat.collection_object_id  where attribute_type='remaining volume' and attribute_units='percent';
      guid       | attribute_units | attribute_value 
-----------------+-----------------+-----------------
 MSB:Mamm:40797  | percent         | 10
 MSB:Mamm:43526  | percent         | 10
 MSB:Mamm:43531  | percent         | 10
 MSB:Mamm:311832 | percent         | 5
(4 rows)
```
@campmlc those yours?

I checked one, it's in a cryovial of unknown size, "10 % of something" isn't terribly informative....

**Comment by Jegelewicz** [comment]
@campmlc can we clean up these percent things?

**Comment by mkoo** [comment]
do we have 10% accomplished here? just nudging @campmlc

**Comment by Jegelewicz** [comment]
Nobody seems to care about this - closing

**Comment by dustymc** [comment]
I care! (But not about the original issue nor enough to reopen, I suppose....) "10% of something" is still nonsense, we shouldn't perpetuate that. @campmlc any interest?

**Comment by Jegelewicz** [comment]
I agree - but I don't feel empowered to just do something about these.

**Comment by campmlc** [comment]
How about changing to remaining quantity?

**Comment by campmlc** [comment]
I have tissues where there is 25 mg sample left in tube. Other tissues would be 0.5 ml blood left in tube. Single attribute for both is necessary.

**Comment by Jegelewicz** [comment]
So just change "remaining volume" to "remaining quantity"? With the same definition: Amount of tissue or extract remaining in a vial. Used to help assess whether sampling will use up the material.

I don't think that fixes anything? 10% of what is still my response since there was no "original quantity". But my brain is hurting right now so maybe I'm missing something.

**Comment by dustymc** [comment]
Agreed, 10% of something isn't useful whatever the structure/units/whatever, and we don't need multiple ways of saying the same thing - surely whoever's making the determination knows what they're looking at and can do the math?

**Comment by campmlc** [comment]
If the container is a jar, then 10% remaining volume is fairly
straightforward -it means you need to initiate conservation measures.
Doesn't matter what size jar.

**Comment by Jegelewicz** [comment]
This has nothing to do with containers as far as I can tell. The only usage revolves around the amount of tissue left in a vial.

**Comment by ewommack** [comment]
What do you do if the vial didn't start out full? Does the initial condition state 10% of volume?
