### ISSUE TITLE
Code Table Request - new herp parts

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3650]
**Goal**
Add new herp tissue combinations for new curator's legacy research samples

**Context**
existing values don't exist

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name

**Value**
1) heart, liver, lung, muscle, toe
2) liver, muscle, tail tip
3) heart, liver, tail tip
4) liver, muscle, toe
5) heart, liver muscle, toe
6) blood, tail tip
7) liver, tail tip
8) liver, toe

**Definition**
1) heart, liver, lung, muscle, toe tissue in combination 
2) liver, muscle, tail tip tissue in combination
3) heart, liver, tail tip tissue in combination
4) liver, muscle, toe tissue in combination
5) heart, liver muscle, toe tissue in combination
6) blood, tail tip tissue in combination
7) liver, tail tip tissue in combination
8) liver, toe tissue in combination

**Collection type**
Herp

**Part tissue flag**
yes

**Priority**
High - bulkload pending this week

**Comment by campmlc** [comment]
This has some urgency - bulkload planned in next couple of days. Please let me know if any objections or OK to move forward.

**Comment by dustymc** [comment]
I'd recommend "[tissue](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#tissue)" and remarks if multiple parts in a container isn't practical, but that's not exactly an objection given the state of the rest of the data. Maybe we _*can*_ dig our way out of this hole!

I'll up priority a bit more in case that solicits less-waffly feedback.

**Comment by campmlc** [comment]
I thought about that, but we are getting more and more specific tissue type
requests, so it is useful to be able to search explicitly. I did suggest to
the researcher that going forward it would be better to split these up, but
there is cost in effort and archival space and supplies to do so.

**Comment by Jegelewicz** [comment]
sigh - I'm too tired to fight it.

**Comment by campmlc** [comment]
If we create each part separately, but they share a barcode - and I add only one of them to a loan, that means I cannot use barcode to add items to a loan.  But theoretically I could still add an individual part, e.g. tail tip, to loan without adding all the others, correct? It also inflates the number of parts, but not the number of containers . . . and could possibly but maybe not affect my ability to get an inventory of objects in the collection. Any other considerations to doing this?

**Comment by Jegelewicz** [comment]
> I cannot use barcode to add items to a loan [...] But theoretically I could still add an individual part, e.g. tail tip, to loan without adding all the others, correct? 

Ideally, you would subsample, but I'm not exactly sure how that would work:
 - add all stuff to loan, but then subsample only whatever thing is being subsampled and wa-la?

> inflates the number of parts

I disagree with this statement. "heart, liver, lung, muscle, toe" is 5 different parts. The method of mashing them together UNDERSTATES the number of parts you are managing!

> possibly but maybe not affect my ability to get an inventory of objects in the collection

Nope. # parts in # of containers seems pretty doable. What do you consider to be your "inventory" parts? containers? I think it is both and you should give yourself credit for both.

**Comment by dustymc** [comment]
> subsample, but I'm not exactly sure how that would work:

The current bulkloader handles it, if I know more about what's going on I might be able to develop other paths. That said, these sorts of things have real impacts on usability - data representing a single item will be able to do different things than data representing some sort of conglomerate, whether that's mixed parts in a tube, a bucket of guppies in a fish collection, or parasites cataloged as parts of a bird.

>UNDERSTATES the number of parts you are managing!

And the alternative probably overstates what you can recover - are you SURE you can dig a toe out of the blender scrapings? Does being mixed in with the pâté for the last decade change the usefulness of the toe? Are you somehow communicating that history to researchers? Etc., etc. I'm not certain that the 'many parts in a tube' approach is quite correct either (but at least it doesn't require us to sort through ~20% more parts than we really have).

I believe MVZ calls these "tissue" and uses remarks to delineate the alleged parts, and AFAIK it works fairly well for them - maybe @ccicero can chime in with details.

We played around with "part attribute parts" at one point, but I think that got removed due to lack of use - it could be revived if it would be used.

**Comment by ewommack** [comment]
> I believe MVZ calls these "tissue" and uses remarks to delineate the alleged parts, and AFAIK it works fairly well for them - maybe @ccicero can chime in with details.

That's what we do that the UWYMV. I get one tube of heart kidney muscle liver -> part = tissue -> remarks = saved 1 vial of HKML, tissue B-#.
I try and be specific about the order the parts went into the tube, so I know which parts to go through if I need a specific one. Liver and muscle are on top since those are the most commonly requested ones. I try and put tissues next to each other that have different appearance and structure.

**Comment by mkoo** [comment]
I'd ping @ccicero and @atrox10 again but this:
"I believe MVZ calls these "tissue" and uses remarks to delineate the alleged parts, and AFAIK it works fairly well for them "
@campmlc was this resolved for you?
