### ISSUE TITLE
GitHub Discussions

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3666]
Maybe we need this?

![image](https://user-images.githubusercontent.com/5725767/122070420-2fd10680-cdb3-11eb-8fac-5b6d3fd56a66.png)

**Comment by dustymc** [comment]
Yea maybe. I hate the idea of more opportunities to lose track of communications, but I also hate trying to find anything in GitHub's horrid little accordion-thing, and I suspect most people don't participate in Issues because there's too much minutia/background/wandering/etc. I'm at least willing to explore the idea that Issues should be concise and focused and all the rest should happen somewhere else.

Only one of (discussions, discord) seems useful if that's somehow possible....

**Comment by Jegelewicz** [comment]
I only brought it up because of the Slack thing. I already have too many communication channels to monitor. I am not sure of the many reasons that people have for not participating (or circumventing by emailing people) and I would actually prefer that we just stick with one thing (really we already have many - GitHub Issues, Google mailing lists, email, Slack). Maybe I'll just drop this and power on with issues - it is the best way to make sure that you see the discussion.
