### ISSUE TITLE
Feature Request - Mask parts from public with dispositions of deaccessioned, discarded, missing, transfer of custody, and used up.

### ISSUE THREAD

**Issue by KyndallH** [ArctosDB/arctos#3667]
Not sure if this is possible but I'm going to ask.

I have a tissue sample with the disposition of "missing". Is there any way to mask parts with the disposition of "missing" so J.Q. Researcher cannot view that sample (and then request it) - mask it in the part list? Also, when I click the flag "require tissues" and search, specimens with missing tissues (and no non-missing tissues) also show up. 

Part dispositions I'd think to mask are deaccessioned, discarded, missing, transfer of custody, and used up.

<img width="232" alt="Screen Shot 2021-06-15 at 12 52 50 PM" src="https://user-images.githubusercontent.com/16887896/122122609-7d606a00-cdd9-11eb-9638-716a5d215f57.png">

**Priority**
Moderate. Slightly above the hole of despair. Not sure if this is even possible.

**Comment by campmlc** [comment]
This would be useful - agree.

**Comment by dustymc** [comment]
Not displaying publicly is possible, but we did this at some point and someone complained (I can't find that now, might have been pre-GitHub). I don't care or have too much opinion (until/unless we implement PartIDs, then it would be evil) but I'd like to get this sorted out before we do anything; un-doing isn't great fun.

Avoiding those parts in the search is much trickier (takes CPU that we may or may not have to give), and that can be confusing to users.

"Tissueness" is https://github.com/ArctosDB/arctos/issues/1875 - that needs implemented soonish, would be good to get it thoroughly sorted out in the next couple weeks. (I don't foresee any objections there, but I don't foresee lots of things....)

**Comment by dustymc** [comment]
Or: how about a "partNotInCollection" CSS class? The details are easy to change, but some indication (tiny gray font maybe) that's not cryptic by way of exclusion but still obviously different. (And CSS can hide stuff, so it's easy - but still cryptic - if we do decide to go there.)

**Comment by KyndallH** [comment]
I think I'd like them gone from view completely but I'll let others weigh in.

The hiding from the flagged got tissue search would be key though. I honestly think people just click that, download a list of specimens, and forward it on to me without checking the tissue dispositions.

**Comment by amgunderson** [comment]
I support masking parts with disposition=missing. Removing those specimens from a search sounds complicated. Go for it, if it can be done only when the require tissues box is checked so as not to limit other searches.

**Comment by campmlc** [comment]
This is a concern, if it is affected:  implement PartIDs

**Comment by AJLinn** [comment]
Would this be an encumbrance that we could apply individually? Or would this be an automatic hiding? 

We have objects that have not been found recently either because they weren't found by someone who may not have been diligent about searching for them, or they were stolen, or they were deaccessioned, etc. 
Would the entire record get masked or just parts? For our collection where the whole record represents the whole object (part) it's not super useful... we already mask our part attribute - location.

It's useful for us to have those records for the institutional knowledge and past publications of objects:
https://arctos.database.museum/guid/UAM:EH:0771-0009
https://arctos.database.museum/guid/UAM:EH:UA74-005-0001

**Comment by KyndallH** [comment]
@AJLinn The record would show up but the part line item would be masked/hidden since you could be missing.
However, I'd love for the record not to show up if the person is searching for a part that is "missing" or "used up". They just assume if the record showed up when they searched for a heart sample that I have the heart sample to loan without checking the disposition of the part.

**Comment by dustymc** [comment]
No I think it would be UI, at least without significant work.

> past publications

Agreed. Rat says there was a liver used, rat has no liver (because it's hidden), users get confused and assume the data is all garbage.

Hiding would also get really weird when a parent part makes the list - it would look like the child (eg subsample) is a parent, or something equally weird.

**Comment by KyndallH** [comment]
@dustymc If it is a pipe dream, I can continue to suffer. Been sucking it up for 8 years so can continue to deal.

**Comment by Jegelewicz** [comment]
> I'd love for the record not to show up if the person is searching for a part that is "missing" or "used up". 

This is problematic when there are two parts with the same part name. Two vials of liver, one gets used up, no one ever gets the other one because the record doesn't show up in searches.

**Comment by sjshirar** [comment]
This would be problematic for us as we've had things go missing over the years for a variety of reasons, but also our disposition info is a mess. We have objects that are here and marked as missing and things marked as missing that are actually here. But even if something is missing there's still catalog information associated with that object that should remain publicly accessible. Would it be possible to set it up so that each collection can choose which disposition categories to mask (or not)?

**Comment by KyndallH** [comment]
> > I'd love for the record not to show up if the person is searching for a part that is "missing" or "used up".
> 
> This is problematic when there are two parts with the same part name. Two vials of liver, one gets used up, no one ever gets the other one because the record doesn't show up in searches.

In this case, the record should show up if the one vial doesn't have a disposition of "missing". 

For example (in my ideal world), with this record: if they just search for Sorex Oregon, they'd pull up this record. BUT when they looked at the record, they couldn't view the missing part- it would be masked. If they searched for Sorex Oregon with tissue, this record wouldn't show up. If it had a tissue that wasn't marked as "missing", this record would show up in their search for tissue. I basically just want the missing part to be masked, not the record. 

<img width="554" alt="Screen Shot 2021-06-16 at 8 51 49 AM" src="https://user-images.githubusercontent.com/16887896/122260776-1e096500-ce80-11eb-96f8-717da993d2bb.png">

**Comment by dustymc** [comment]
>gone from view completely 

<img width="617" alt="Screen Shot 2021-06-17 at 7 26 11 AM" src="https://user-images.githubusercontent.com/5720791/122416125-58850780-cf3d-11eb-826b-b05f93911fff.png">

Hiding loaned items doesn't seem optimal.

Next release will look like this:

<img width="534" alt="Screen Shot 2021-06-17 at 7 47 41 AM" src="https://user-images.githubusercontent.com/5720791/122420248-62f4d080-cf40-11eb-899c-df750fa28769.png">

**Comment by Jegelewicz** [comment]
Add this in search results too?

**Comment by dustymc** [comment]
Gonna need some more direction on that - one of the available parts "fields" is a concatenated string, the other's a JSON object, I'm not sure how I could style either of them there.

**Comment by Jegelewicz** [comment]
Maybe if any of the parts have the disposition above, grey out those fields? Just thinking it would be good to somehow flag these in the results (which is about as far as a researcher requesting stuff for a loan probably gets)...
