### ISSUE TITLE
Specimen event flagged by automation inappropriately

### ISSUE THREAD

**Issue by gradyjt** [ArctosDB/arctos#3679]
Hello, one of my APSU Herp records (APSU 20069) keeps getting flagged for the specimen event not matching the higher geography, but this shouldn't be the case. It is very close to a county border but I have moved the marker further away from the county line repeatedly and this doesn't seem to fix the issue. The automatic checks are also inundating me with notices that the specimen event and higher geog do not match like it's overreacting maybe? Do I just need to move the lat/long further away from the county border?

Thanks!

Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.

**Comment by dustymc** [comment]
I'd recommend not worrying about it for now.

https://github.com/ArctosDB/arctos/issues/2660 should provide access to more precise spatial data (the WKT cuts a corner on the river), plus tools to query/report on spatial problems rather than running it through the UI (the only access to spatial tools I have at the moment). With that, I think we can delete/archive a bunch of the automated annotations - I'll open a discussion when that becomes possible. I'm just waiting on some infrastructure adjustments to make all of this happen - I thought we'd have those a couple months back, I'm not sure what's going on, @mkoo ??

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/3530
