### ISSUE TITLE
Code Table Request - Mound Valley Limestone

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#3681]
**Goal**
Add the Mound Valley Limestone to the Lithostratigraphic Formation code table

**Context**
Mound Valley Limestone is not in the code table. It exists and is used by a locality I need to enter ([https://ngmdb.usgs.gov/Geolex/Units/MoundValley_9406.html](https://ngmdb.usgs.gov/Geolex/Units/MoundValley_9406.html) and [https://macrostrat.org/sift/#/strat_name_concept/9406](https://macrostrat.org/sift/#/strat_name_concept/9406))

**Table**
[https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlithostratigraphic_formation](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlithostratigraphic_formation)

**Value**
Mound Valley Limestone Formation

**Definition**
[Geolex](https://ngmdb.usgs.gov/Geolex/Units/MoundValley_9406.html)

If there are no objections I will add it to the code table.

**Comment by Jegelewicz** [comment]
Looks good to me.

**Comment by dustymc** [comment]
I halfheartedly want text in the definition (eg something that splat-f might help me find), but I think others haven't had that so whatever.

Otherwise no objections from me - pretty safe to assume that for all your geology issues....

Also you may know but

<img width="447" alt="Screen Shot 2021-06-24 at 4 31 02 PM" src="https://user-images.githubusercontent.com/5720791/123344886-aa172e80-d509-11eb-9106-53a76676844b.png">

will make links for you - or just add ``class="external"`` to get the arrow-thingee and a new window.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Thanks! Last one I did I just copied what the code for the link in another term and replaced the url, but it is good to know that is there!

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> I halfheartedly want text in the definition . . . but I think others haven't had that

Never too late to start.

Definition: Late Pennsylvanian limestone in the Cherokee basin of Kansas and Oklahoma

**Comment by Jegelewicz** [comment]
Need to start a "code table admins how to" so that everyone with the access knows this stuff.

**Comment by dustymc** [comment]
>"code table admins how to" 

https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html

**Comment by Jegelewicz** [comment]
OK - it needs some updates probably - will read later. Thanks!

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Added
