### ISSUE TITLE
catalog number format bug?

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#3702]
@cefilipek @Jegelewicz JSNM:Paleo is set up as integer catalog numbers, there's at least one which isn't (0011379) that's somehow snuck through (and is somehow breaking the cache updater). Did you perhaps change catalog number format somewhere along the way, or ??? - SOMETHING is broken and needs fixed, any information you can provide would be most helpful.

Do you want/need the padding zeroes? If so, you'll need a different value for https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcatalog_number_format

If the catalog numbers change somehow in this process, I can help create redirects to keep all of the links/GUIDs working.

**Comment by Jegelewicz** [comment]
I didn't change anything, but it seems like this was never really finalized - https://github.com/ArctosDB/data-migration/issues/162

Probably my bad.

**Comment by cefilipek** [comment]
Sorry for my delayed response, I am only at Benedictine on Tuesday and Wednesday and work a different job on Fridays, so I have only just seen the emails.

I have not changed my catalog numbers, so I don't know why it would be causing an issue. I did notice that the catalog number was different at the top than it was in identifiers, which I fixed. Perhaps that was the issue. The extra 0s at the front are due to the fact that we use barcodes and that is how the number looks on our barcodes. We want them to appear the same as they do on the barcodes, minus the JSNM at the end because I was told that would not work here. This format was chosen before I started working at the museum so I don't know the reasoning behind it, but I cannot change it at this point. I thought I had been told to use integer for the way I have it, but I must have misunderstood.  I don't know what value I would change it to for the number format, I honestly find the documentation a little confusing in this case.

**Comment by Jegelewicz** [comment]
@cefilipek integer catalog numbers cannot include leading zeros. If you want those in your catalog number, you cannot use the integer format and will need to switch over to either string or prefix-integer-suffix.

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcatalog_number_format

We can discuss on a call if you want.

**Comment by cefilipek** [comment]
@Jegelewicz I have switched it to prefix-integer-suffix. I had assumed that meant text before the number and wouldn't apply to other numbers, so thank you for the clarification.

**Comment by Jegelewicz** [comment]
It think that is the best choice you can make given the circumstances. Just put the leading zeros in the prefix. Do you need any help correcting any that are missing them?

**Comment by cefilipek** [comment]
I haven't noticed any missing the zeros at the front, so I think I'm good. Thank you!

**Comment by dustymc** [comment]
Thanks! I've updated the trigger to handle leading zeroes correctly and updated the documentation, I think this is done.
