### ISSUE TITLE
Quad Maps as  new Locality Attribute

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3724]
See also https://github.com/ArctosDB/PG/issues/1

Quad maps have traditionally been included in Higher geography. @dustymc suggests we move them to Locality Attributes.

New Locality Attribute Type = Quad Map
Definition = A topographic map produced by the United States Geological Survey (USGS) covering the United States. The maps are usually named after local physiographic features. <a href="https://en.wikipedia.org/wiki/Quadrangle_(geography)" class="external">Wikipedia</a>

New Code Table for Quad Map values

ctquadmap

QUAD_MAP_NAME | DOCUMENTATION
 -- | -- 
Cerro De La Campana SE 7.5 minute | <a href="https://ngmdb.usgs.gov/topoview/viewer/#12/33.8126/-106.5628" class="external">USGS</a>

**Comment by dustymc** [comment]
Clarification: I think just the not-1:250K should be moved. (And AFAIK those are "quads" so maybe "map name" is a better attribute.)

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
What is the purpose of moving the quads to locality attribute?

**Comment by Jegelewicz** [comment]
@dustymc please explain!

**Comment by dustymc** [comment]
Well as long as we're refusing to say what we're trying to do with geography, it just *feels* right....

Geography to me is finite (ish) and authoritative (ish). 1:250K maps are there, I suppose, smaller-scale feel less geog-ish.

https://github.com/ArctosDB/arctos/issues/3272 contains (ish) "geography is whatever some Curator wants it to be (and users can find stuff via services)" so if we're still headed in that direction my waffly arguments are slightly wafflier.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
My concern is that I use the quad data a lot and anything that goes into locality attributes is so much harder to work with when I download locality data because it takes so long to parse out the attributes. I can do it now, but it takes forever.

I would argue that the 7.5' topo maps are finite and authoritative. The boundaries are finite, set by a governmental authority, and don't move. We could get WKTs for them if we had the time, which is another reason to leave them in geography because if we move them to locality attributes we no longer have the option to treat them as spatial data.

**Comment by dustymc** [comment]
I'm convinced....

>parse out the attributes.

Maybe open an Issue - might be something I could help with.
