### ISSUE TITLE
Bulkloading Parts

### ISSUE THREAD

**Issue by SerinaBrady** [ArctosDB/arctos#3750]
Hi, 

Is there some way to change the Parts Bulkloader to load parts horizontally instead of vertically? I have a file where each GUID has multiple parts in the same row. Transferring those cells from horizontal to vertical will take me a very long time and errors could occur. Is there any way to convert this file? Thanks! 

![Parts_Bulk](https://user-images.githubusercontent.com/86243942/126392172-4b767d86-a5b5-4f8b-aa74-db77fa4f12aa.JPG)
[Tissues_2500-2750_EDITING.xlsx](https://github.com/ArctosDB/arctos/files/6851097/Tissues_2500-2750_EDITING.xlsx)

**Comment by Jegelewicz** [comment]
@SerinaBrady this is not possible. The reason parts with more than one attribute cannot be loaded in the main bulkloader is that Arctos wouldn't know which part each attribute was meant to go with.

BUT, I've been looking for this opportunity. Give me a day or so and I'll see if I can create a solution that others could use too.

**Comment by Jegelewicz** [comment]
FYI - I changed three of the part attribute type headers because they were all part_attribute_type_1 and I also changed all of the "Tissue" headers to "part_name_n". Recommendation for this process will be that column headers match the Arctos part and part attribute bulkload templates.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
This would be helpful. I had the same issue when I did my first big specimen bulkload and it was a very time intensive task to rebuild the parts upload. Keeping separate sheets for specimens and parts is a pain.

**Comment by campmlc** [comment]
Absolutely agree we need a tool to deal with this problem.

**Comment by SerinaBrady** [comment]
@Jegelewicz Hi there! I was just wondering if there were any updates on the file? I was going to be working on the part file today, hopefully in preparation to have the parts loaded by Friday. Just curious if I could save myself some time in any way!
Thanks!

**Comment by Jegelewicz** [comment]
@SerinaBrady I actually have it done. It took me less than 3 minutes in Excel, but I have been trying to write an R script to do the same thing and one day later, I am still working on it!

I made a video of the Excel transform: https://youtu.be/oHDXdaydXzk

Here is the file. The last sheet is your part bulkload - but you are going to need to add some information because disposition and condition are required for parts.
[part_bulkload.xlsx](https://github.com/ArctosDB/arctos/files/6862986/part_bulkload.xlsx)


I am going to keep working on the R script using this file. Pretty sure it will be faster than 3 minutes (but not by much) and will offer an option for those who can use R. Still, doing this in Excel is a breeze....

**Comment by Jegelewicz** [comment]
Also, sorry about having to watch my face the whole time...what a hoot!

**Comment by SerinaBrady** [comment]
Three minutes! You saved me so much time today, thank you, thank you!

**Comment by Jegelewicz** [comment]
@SerinaBrady also, Arctos is not loading anything from the bulkload tools today and probably tomorrow. You can upload, but the processing to add stuff to the records is not running right now. I expect there will be an announcement about it later today. Maintenance at TACC...

**Comment by dustymc** [comment]
Merge-->https://github.com/ArctosDB/arctos/issues/3748
