### ISSUE TITLE
Part Preservation in Bulkload template is confusing

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3755]
While I get that we were trying to make the addition of preservation easier under the new system, I think we are confusing people. 

See
#3750 
https://github.com/ArctosDB/arctos/issues/3708#issuecomment-883001643
https://github.com/ArctosDB/arctos/issues/3708#issuecomment-883853005

I think it would be much more appropriate to call these what they really are Part_1_Attribute_1 or something of the sort. Because we are basically telling people this isn't a part attribute, it is something SPECIAL. I also sorta dislike that we are telling everyone - go ahead and create a preservation attribute with no determiner, method or date (it isn't even obvious from the main bulkloader that those would be an option).

**Comment by lingnancollection** [comment]
If preservation is an attribute why is there a column in the bulkloader called [part_preservation with its own code table](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctpart_preservation)? and even if it is an attribute it does not solve the problem of bulkloading multiple preservation methods to the same specimen, because you can not assign two preservation modes to the same part. Especially when you have multiple parts like other tissues. Then to bulkload we would still the need to use the bulkload part tool which is getting complicated on its own. Can we please reconsider going back and add as an option formalin-fixed, 70% ethanol?

**Comment by Jegelewicz** [comment]
Closing as duplicate of #3748
