### ISSUE TITLE
70% ethanol: tissue?

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#3763]
Alternatively I could use fixed in formalin as my preservation (thus killing tissueness) and stored in ethanol as my remark. 
Curious why 70% ethanol is denied as tissueness. It is separated from any fixation step. Tissues in lower percentage of isopropynol are no influence. 

-- | -- | --

_Originally posted by @cjconroy in https://github.com/ArctosDB/arctos/issues/3759#issuecomment-885862132_

**Comment by dustymc** [comment]
It's trivial to flip the flag if there's a consensus on whether 70% ethanol is a tissue or not.

Note also that there are two ways to use this information:

1. You can search using the "tissue" flag to locate things **we** think are tissues, or
2. You can search using preservation to locate things **you** think are tissues.

**Comment by Jegelewicz** [comment]
@jtgiermakowski @mvzhuang @atrox10 thoughts?

**Comment by campmlc** [comment]
@jldunnum

**Comment by jldunnum** [comment]
70% EtOH is tissue, just not all that great of tissue. Thats one of the issues isn't it? Just depends on what your question is and what methods you plan on employing to answer the question.
At the moment we are trying to be all inclusive with anything that remotely has a chance of being useful for molecular, or pathogen, or whatever, research. We end up getting requests for specimens that really aren't viable for what the researchers are trying to do.
Because tissueness is such a critical aspect for a large majority of users now, it might be worth thinking about how to make that filter a larger field with some options to play with. Such as selecting for specimens with actual tissues as parts, then various quality filters like frozen (n2, -80. -20), EtOH filters.
A more encompassing filter could allow for whole organisms that could be subsampled for molecular work (never touched formalin).
______________________________________________________________

Jonathan L. Dunnum Ph.D.
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by dustymc** [comment]
>options to play with

That's my (2) above - like all UI I'm sure it could be better, but there is a mechanism for users to ignore whatever arbitrary flag we've used (and I don't think it can be anything else) and directly interrogate the data.

**Comment by Jegelewicz** [comment]
> selecting for specimens with actual tissues as parts

not so easy when some of them are "tissue" and some of them are "heart".

> We end up getting requests for specimens that really aren't viable for what the researchers are trying to do.
> Because tissueness is such a critical aspect for a large majority of users now, it might be worth thinking about how to make that filter a larger field with some options to play with.

Now that part and preservation are separate, this should be something anyone could do, but we probably need some instructions for that.

Looking for tissue for molecular work....do x or use "this" search page.

**Comment by dustymc** [comment]
resolved?

**Comment by campmlc** [comment]
Just a note that 70% ethanol only preserves DNA in the short term, not really more than a year or two at most at room temperature (recent study showed not more than 4 months). The problem is that below 80% ethanol the water concentration becomes problematic for DNA stability.
