### ISSUE TITLE
Arctos taxonomoy relationships taking precedence over correct classification

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#3767]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**

This beetle has a higher classification of a fish

https://arctos.database.museum/guid/UAM:Ento:70250

The name has an Arctos classification of a beetle

https://arctos.database.museum/name/Ischnosoma

but also has 2 classifications from "Data from source Arctos Relationships" that are fishes.

Why is the classification from 'relationships' showing on the catalog record page instead of the correct, beetle classification?

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.
high

**Comment by dustymc** [comment]
I think that probably just stopped processing at an inconvenient time. I manually ran the refresh...

```
 select update_flat_row(collection_object_id) from flat where guid='UAM:Ento:70250';
```

... and it looks right to me now.

Your taxonomy preferences are...

<img width="410" alt="Screen Shot 2021-07-26 at 12 57 40 PM" src="https://user-images.githubusercontent.com/5720791/127050856-f62f263c-85ce-4bdd-af25-d55d14ef8064.png">

so that data was probably from https://arctos.database.museum/name/Ischnosoma#WoRMSviaArctos, not https://arctos.database.museum/name/Ischnosoma#ArctosRelationships
