### ISSUE TITLE
Feature Request - announcements

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#3777]
**Is your feature request related to a problem? Please describe.**

I can never find the announcements that get sent out when I need to share them with a user. (https://github.com/ArctosDB/arctos/issues/3775 for example.)

**Describe what you're trying to accomplish** 

One place to find current (functional-only, maybe) happenings.

**Describe the solution you'd like**

Maybe we have this and I just don't know where it is? If not, can https://arctosdb.org/status (or /announcements or /current or ????????) be magicked into existence and used?

**Describe alternatives you've considered**

Don't communicate as effectively as we should!

@Jegelewicz @ewommack @mkoo

**Comment by Jegelewicz** [comment]
Agree this is a problem and we need a more coordinated effort. Unfortunately we have multiple methods for doing this:

- Arctos Banner (as far as I know there is no history for this...)
- email to Arctos Google Group (and Arctos Working Group) (should be able to find the announcement in the group site outgoing mail, but....)
- Newsletter (for less urgent stuff) (should be able to find issues for newsletter articles - at least for the past year or so, before that not so much)
- Often, no announcement is made - "we" have discussed something here or in an email thread and think that is enough.

I think we either need an announcement repo or we need an announcement label in this repo and we need a point person for making announcements. This has generally been @ewommack but I think she has been out this week, so we need to also designate a backup (aka we need a Communication Co-Chair) All announcements (including those sent by email or the banner) should be recorded for posterity here in Github so that we can point people to them when necessary.

Other ideas?

**Comment by Jegelewicz** [comment]
> can https://arctosdb.org/status (or /announcements or /current or ????????) be magicked into existence and used?

This is a great idea.

**Comment by dustymc** [comment]
>announcement label in this repo

There's a [milestone](https://github.com/ArctosDB/arctos/issues?q=is%3Aopen+is%3Aissue+milestone%3AAnnouncement), I'm fine with using it as primary or an archive, as long as there's one place to send users I don't think I care too much. 

I don't think I'm crazy about the idea of yet another repo, but whatever.

A single announcement point would also serve as a nice check against the 'we discussed' thing, which I'm certainly susceptible to.

**Comment by dustymc** [comment]
Bumping this up, I'm still getting inquiries and still can't find our official announcement....

**Comment by Jegelewicz** [comment]
I think that's because there has never been one.

**Comment by ewommack** [comment]
I've been out and not tracking my email, and trying to find the thread to find info about what is going on. Can I just copy the announcement Dusty sends out? How much explanation do I need to track down for the outages announcements? Do we need to send it out for editing?

I'd fully support a co-chair or announcement point. I feel like I left and things blew up, sorry!

**Comment by Jegelewicz** [comment]
@ewommack yes - not your fault by any means! We do need a backup and we also need a better path for this kind of information. Right now there are some emails among the working group officers or something randomly posted in one of the many Github repos and I'm not sure anyone feels empowered to just make an announcement.

I've placed this near the top of the agenda for the 8/12 working group meeting because we are not communicating with everyone well enough or in a systematic manner.

**Comment by Jegelewicz** [comment]
I created a new issue template to help with this (I hope). See https://github.com/ArctosDB/arctos/blob/master/.github/ISSUE_TEMPLATE/arctos-down.md

**Comment by Jegelewicz** [comment]
I DO think this is an excellent idea:

https://arctosdb.org/status

@mkoo

**Comment by mkoo** [comment]
that's solid! I'll make that page real but lets talk about the workflow to
populate it at the meeting

**Comment by campmlc** [comment]
I like Arctos status page and also the label idea.

**Comment by ewommack** [comment]
Yes please! Anything to help if I'm out and gone again unexpectedly. I thought I'd have more brain power during the move, but hahaha....

**Comment by mkoo** [comment]
We have a status page now for Arctos announcements:
https://arctosdb.org/status/ (I posted the last two that I received)
Should we also link to this? https://portal.tacc.utexas.edu/system-monitor

I'll look around for where to link the status page on the home page next.
feedback? Is this how we want to use it?
MK

**Comment by Jegelewicz** [comment]
> 

Somewhere in the https://arctos.database.museum header would be good too - so it is available no matter where you happen to be in Arctos?

**Comment by Jegelewicz** [comment]
Also, perhaps a permanent link to the ["Arctos Down" issue template](https://github.com/ArctosDB/arctos/issues/new?assignees=&labels=Priority-Critical+%28Arctos+is+broken%29%2C+Arctos+Down&template=arctos-down.md&title=Arctos+Down+-+) on the status page to make it easy for people to report outages?

**Comment by mkoo** [comment]
Also, a link on our default "Down for Maintenance" sign to "Status" when
Arctos is down for maintenance...
