### ISSUE TITLE
Feature Request - Change the Name of the New Collections Orientation monthly meeting

### ISSUE THREAD

**Issue by ewommack** [ArctosDB/arctos#3791]
As suggested by @mbprondzinski in her newsletter feature article (https://github.com/ArctosDB/newsletter/issues/55), it would be great to have a forum where Arctos users can ask questions once a month. 
We have the monthly meeting New Collections Orientation, which is open for all Arctos users to come ask questions, but perhaps the name is keeping older collections away. 

Suggested name changes:
Monthly Arctos Users Forum
Arctos office hours

Needs discussion.

**Comment by campmlc** [comment]
I like "Arctos Office Hours" or "Arctos Open Office Hours". Clear, everyone understands what that means, open to all.

**Comment by Jegelewicz** [comment]
Changed in the Calendar to Arctos Office Hour

**Comment by dustymc** [comment]
Unless someone has reason not to, I'm going to remove my office hour from the calendar and attend this instead.

**Comment by campmlc** [comment]
Just to clarify, yours has been weekly for internal stuff; this one is
monthly for general users. Can we keep your Monday slot as an optional when
necessary and by prior arrangement?

**Comment by dustymc** [comment]
I thought mine was general stuff, but maybe that didn't get communicated. If monthly isn't enough I'd vote to make the general chat weekly (or whatever's needed) rather than having multiple apparently-mostly-identical 'hang out with Arctos' slots, even if that means it's just me on some weeks.

I'm always happy to chat with whoever about whatever (and I suspect the rest of "us" are too), maybe that should somehow be made more clear. I can usually be pretty flexible on the time.
