### ISSUE TITLE
Request for change of GUID Prefix - UNM:ES to UNM:Paleo

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3795]
Please see https://github.com/ArctosDB/new-collections/issues/115#issuecomment-886998404

I would really like to get this resolved so that we can move on. I am making every effort to stop this from happening in the future, but adding the choice of GUID Prefix to the MOU is not going to happen until we complete an MOU overhaul.

**Comment by lkvoong** [comment]
We need clarification/confirmation on:

1. Change guid from UNM:ES to UNM:Paleo [ArctosDB/new-collections#115 (comment) mentions other versions).
2. Do you intend to re-use UNM:ES in the future?

Because there are cataloged items associated with the guid_prefix UNM:ES, it complicates matters. 

If you expect to re-use UNM:ES, then we will have to create a new collection and transfer the cataloged_items to the new collection, but we will not be able to reuse existing UNM:ES guids (i.e. if we create another UNM:ES collection in the future, that collection cannot use any existing UNM:ES catnums).

1. Request a new collection for an existing institution.
2. Create new role unm_paleo.
3. Assign role unm_paleo to all members of unm_es role.
3. Create new collection using guid_prefix UNM:Paleo and collection_cde ES.
3. Reassign collection_id and catnums for UNM:ES cataloged_items.
4. Redirect old guids to new guids (e.g. UNM:ES:14807 to UNM:Paleo:14807).
5. Archive old guids for UNM:ES (old UNM:ES catnums can not be re-used due to redirect).

If you do NOT expect to re-use UNM:ES, we can update the guid_prefix for the collection, but it means you can never create a collection with guid_prefix UNM:ES.

1. Create new role unm_paleo.
2. Assign new role to all members of unm_es role.
3. Update vpd_collection_access.role to unm_paleo for collection_id = 147
4. Update guid_prefix to UNM:Paleo for collection_id = 147
5. Redirect /unm_es to /unm_paleo (redirect all UNM:ES records to UNM:Paleo).
6. Archive UNM:ES prefix.

**Comment by lkvoong** [comment]
@Jegelewicz @cemyers42 

I forgot to ask about catnums for UNM:Paleo.  Are we keeping catnums for the cataloged item records and just changing the guid prefix?

e.g. UNM:ES:14807 becomes UNM:Paleo:14807


> @cemyers42 Please indicate that you agree with the information below.
> 
> 1. Do you intend to re-use UNM:ES in the future? **NO**
> 
> UNM does NOT expect to re-use UNM:ES, an update to the guid_prefix for the collection means you can never create a collection with guid_prefix UNM:ES.
> 
> 1. Create new role unm_paleo.
> 2. Assign new role to all members of unm_es role.
> 3. Update vpd_collection_access.role to unm_paleo for collection_id = 147
> 4. Update guid_prefix to UNM:Paleo for collection_id = 147
> 5. Redirect /unm_es to /unm_paleo (redirect all UNM:ES records to UNM:Paleo).
> 6. Archive UNM:ES prefix.
> 
> NONE of this should affect UNM:MIN.

**Comment by Jegelewicz** [comment]
From @cemyers42  I am out of the office through 8/8/21 and will be delayed in responding to emails.

**Comment by cemyers42** [comment]
Hi All, apologies for the delayed reply I was out of town.

Yes, I would like to change "UNM:ES" to "UNM:Paleo"

NO, I do not need to re-use "UNM:ES" in the future

What else can i help with?

**Comment by Jegelewicz** [comment]
> Are we keeping catnums for the cataloged item records and just changing the guid prefix?

Yes

**Comment by Jegelewicz** [comment]
@lkvoong What else is needed from our end?

**Comment by lkvoong** [comment]
@Jegelewicz  @cemyers42 

Sorry for the delay; I have the information I need and will make the changes after hours today.

**Comment by Jegelewicz** [comment]
Thank you!

**Comment by lkvoong** [comment]
@Jegelewicz  @cemyers42 

I've updated the database to move UNM:ES to UNM:Paleo; please review and let me know if anything doesn't look right.

https://arctos.database.museum/unm_paleo

All pre-existing UNM:ES guids should redirect to UNM:Paleo with the same catnum:
e.g. https://arctos.database.museum/guid/UNM:ES:15454
will automatically redirect to:
https://arctos.database.museum/guid/UNM:Paleo:15454

I did the following:

  1. Rename role unm_es to unm_paleo; Recreate role unm_es for archival.
  2. Verify all members of unm_es are now members of unm_paleo.
  3. Update vpd_collection_access.role from unm_es to unm_paleo for collection_id = 147
  4. Update collection.guid_prefix from UNM:ES to UNM:Paleo for collection_id = 147
  5. Update cf_collection.portal_guids from {{UNM:ES}} to {{UNM:Paleo}} for collection_id = 147
  6. Verify no records in coll_obj_other_id_num with other_id_type 'UNM:ES'
  7. Insert into ctcoll_other_id_type for other_id_type 'UNM:Paleo'; Retaining 'UNM:ES' for archival.
  8. Insert into redirect to redirect UNM:ES records to UNM:Paleo
  9. Set flat.stale_flag = 1 where collection_id = 147 and guid_prefix = 'UNM:ES'
 10. Call is_flat_stale to update flat from UNM:ES to UNM:Paleo

**Comment by Jegelewicz** [comment]
Thanks @lkvoong !

@cemyers42 once you have reviewed the new portal, please close this issue.

**Comment by cemyers42** [comment]
looks good!
