### ISSUE TITLE
Feature Request - link to identification

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#3812]
**Is your feature request related to a problem? Please describe.**
 Would be neat to to link to (eg scroll to and highlight) individual IDs

**Describe what you're trying to accomplish** 
Make @tucotuco happy

**Describe the solution you'd like**
expose identification_id; make it do stuff

**Describe alternatives you've considered**
don't

**Additional context**
What the heck is "identificationID in DwC"?

**Priority**
Help...

**Comment by tucotuco** [comment]
The background for this is that we are reviewing the Darwin Core documentation for changes prior to a major release that includes all the recently ratified term additions and changes. In the RDF Guide there is a hypothetical example for an identification, with an identifier in the form of a resolvable IRI (see [this issue comment](https://github.com/tdwg/dwc/issues/240#issuecomment-893729456)). I thought Arctos might be the most likely to actually have a real example, hence the question. It certainly isn't necessary, and it would actually have no bearing on my happiness, but it might be interesting to be able to refer to distinct determination acts, since Darwin Core supports that.

**Comment by Jegelewicz** [comment]
interestingly this also applies to parts (and probably #3630 ) because when I am [here](https://www.ggbn.org/ggbn_portal/search/record?unitID=MSB%3AMamm%3A284885&collectioncode=Mamm&institutioncode=MSB&guid=http%3A%2F%2Farctos.database.museum%2Fguid%2FMSB%3AMamm%3A284885%3Fpid%3D21740876)

This link

![image](https://user-images.githubusercontent.com/5725767/128422883-2115b950-a797-416b-9a39-9b4fcee20fb3.png)

 just takes me to the catalog record rather than the specific part....sorry to jump in!

**Comment by Jegelewicz** [comment]
and FWIW, I think linking to individual ids will be useful for more than making @tucotuco happy....
