### ISSUE TITLE
Bulkloading error "Error and units, datum, and georeference source and protocol must be accompanied by coordinates."

### ISSUE THREAD

**Issue by aklompma** [ArctosDB/arctos#3817]
For ALMNH:Paleo records in Arctos, numerous were uploaded recently, but some show the following error message when clicking on Enter Data > Bulkloader > Browse and Edit:
"Error and units, datum, and georeference source and protocol must be accompanied by coordinates."

It applies to collection_object_id: 97590129 to 97590136

Any idea?

**Comment by campmlc** [comment]
Check to see if you have any of those fields populated with a value? If
there is a value in those fields, you need coordinates and vice versa.

**Comment by aklompma** [comment]
The Coordinates (events and locality) field does not have any values in it.

**Comment by campmlc** [comment]
Same issue as #3379 - @dustymc

**Comment by campmlc** [comment]
Can you download the records from the bulkloader and post here as zipped csv?

**Comment by Jegelewicz** [comment]
All of these records have an error, datum, source and protocol, but no coordinates. The error, datum, source and protocol need to be deleted or coordinates added.

**Comment by Jegelewicz** [comment]
![image](https://user-images.githubusercontent.com/5725767/128531392-036a2a4f-ca1a-4810-a4ae-34965dfcd95b.png)

**Comment by aklompma** [comment]
I just saw it too now....It is odd because I never filled out datum, georeference_source, max_error_distance for this locality myself and I would not like to have it in there either.  I have not figured out how to delete it yet.

**Comment by Jegelewicz** [comment]
Looks like you figured it out?

I am curious, was this information in your original bulkload file? If not, then something crazy has happened.

**Comment by campmlc** [comment]
I'm wondering if this is somehow getting autoinserted on some files . . . .

**Comment by aklompma** [comment]
I have figured out how to delete it.
@campmlc Yes, it may have been autopopulated yet now show up when entering the data.

**Comment by Jegelewicz** [comment]
I see, if these came through data entry, then yes, those things may have stuck in there from a previously entered record. @aklompma the next time you are entering stuff if you can look for it that will help us figure out how to stop it.

**Comment by aklompma** [comment]
I'll try to see what happens a next time for these localities. Thanks for the help!

**Comment by Jegelewicz** [comment]
THANK YOU for being patient and helping make Arctos better!!!

**Comment by campmlc** [comment]
I'm just come across the same error for some records that have been in the bulkloader since prior to the PG move. I get this error even though the record was entered with no coordinates.
![Screenshot 2021-09-23 17 18 57](https://user-images.githubusercontent.com/14808196/134596431-48e3120f-9cfe-466e-8161-e053e4003c09.png)

When I go in to edit the record from the Browse and Edit pane by clicking on the key at left, I see the first screenshot below - e.g. nothing recorded for coordinates. 
![Screenshot 2021-09-23 17 19 16](https://user-images.githubusercontent.com/14808196/134596518-01a13dd0-1902-4d05-b013-24ce4adf0edf.png)

But these two values are misteriously present in the browse and edit table - triggering the error. How are they getting added by default, and can we globally remove them from legacy browse and edit table entries, or do we have to do this manually?
![Screenshot 2021-09-23 17 19 41](https://user-images.githubusercontent.com/14808196/134596574-67bbefb2-8dbf-4c3c-9cae-6e602665c23a.png)

**Comment by campmlc** [comment]
@dusty

**Comment by dustymc** [comment]
> in the bulkloader since prior to the PG 

!!!!

There are lots of tools capable of fixing this.

There are lots of ways those data could have gotten like that - something important has gone missing, for example. I can't and won't just disappear random bits of data, but I can help if you have some specific mass update request.

**Comment by campmlc** [comment]
These records had their locality data pulled from host records. I'm just
wondering whether there is some reason "unknown" is being autoinserted into
georeference source and protocol for records that were not georeferenced in
data entry. This seems to be happening for lots of different people in
different collections, with the commonality that the fields are being
populated during single record data entry. The  volunteer who entered the
records in my example entered data from single record data entry, and there
were no coordinates to enter, so I'm sure she did not open the georeference
tool and add these values.
