### ISSUE TITLE
component loaders should act as username

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#3861]
Currently, when we load data through the Component Loaders (aka. batch tools), the Edit History attributes those changes to either DBA or arctosprod: 
![image](https://user-images.githubusercontent.com/12507297/129955624-ddaa612f-6e70-48df-b3b4-45953387a4e4.png)

Can we get that tied to the user that performed the upload using these tools?

**Comment by dustymc** [comment]
That's a hard one.

The scheduler runs as an admin user whose credentials are handled by the application server. A "normal" user's credentials are just kept for their session, and flushed when they log out in some way. So, the options seem to be

1. Store user passwords somewhere that the scheduler can access, allow the loaders to run as the user. This is ideal from the perspective of letting the database deal with things like permissions, but storing passwords is a huge security risk.
2. Somehow override the triggers that keep FLAT up to date (and provide the 'last edit' functionality), which seems somewhere between magical and evil.

There may be some other option that I can't see at the moment, and I am going to be talking to TACC about authentication (for the API) sometime in the next couple years, so the answer isn't "no" but I don't have a "yes" handy at the moment either.

**Comment by Jegelewicz** [comment]
Something new - user can be DBA but "uploader" is whoever put the stuff in the tool?

**Comment by dustymc** [comment]
I think that's probably (2) but I really don't understand what you're asking.

**Comment by Jegelewicz** [comment]
Maybe, but I'm not exactly sure what @ really maens...so there we are.

Any way we can do a modified version of 1? Something more like the main Bulkloader (which accomplishes this somehow?)

I guess I am not clear as to what really happens here.

1. I load some stuff in a component loader and the tool knows it is me because I have to mark it to autoload and I can easily find my stuff.
2. I mark stuff to autoload then (Magically?) DBA becomes the owner. Because that is the only way Arctos will let stuff load since at the time, I may or may not be logged in?

Why isn't this the case for the main Bulkloader?

**Comment by dustymc** [comment]
>exactly sure what 2 really means

We're letting the RDBMS do the things it was designed to do, and I'm incredibly hesitant to do anything else because nothing - even the very expensive middleware we had at one point - has proven capable of replicating that functionality.

>Why isn't this the case for the main Bulkloader?

Its inserting data values in coll_object.

>DBA becomes the owner

DBA owns your account as well, not much magic involved.

>may or may not be logged in?

Yes, but that doesn't make your password available to other users!

**Comment by acdoll** [comment]
I imagine this may not be possible based on how Edit History works, but if the loaders had a entered_by column (as in the main bulkloader) could we get that to feed into the Edit History?

**Comment by dustymc** [comment]
All component loaders carry username. Inserting that as data somehow is technically possible, but I don't think it's practical.

Somehow authenticating the users has significant benefits aside from the history, I think that's probably the only realistic approach to this, I just don't (yet, I hope) know how to safely do that.

**Comment by Jegelewicz** [comment]
That is what I was trying to say.

**Comment by dustymc** [comment]
I think I know how to do this under the current tech stack, the ask is clearly additive, serves only to clarify, changes nothing a user would notice, going direct.

**Comment by mkoo** [comment]
I dont like 1 or 2 frankly. Howabout 3: new field for user login in the loading table (append when it's sitting in the review table since it is attributed to the user there so no real change in bulkloading template at all), then add that new field "user_uploader" (or whatever) to the history. (this may be 2ish...)

But otherwise, the sample Andy shared just shows which parts were bulkloaded

**Comment by dustymc** [comment]
My idea (using set role and reset role in a transaction) isn't working reliably with security definer triggers, I think this is going to have to take one of two paths:

1. Some way of authenticating on behalf of a user. (@mkoo and I have been talking to TACC about this, but I don't know that such authentication could safely be available to 'the system.')
2. Some more direct approach, 'inserted_by_username' in the table or something, maybe part of https://github.com/ArctosDB/arctos/discussions/6742. 

I am closing this as inactionable, but won't lose sight of the need.
