### ISSUE TITLE
Nesting containers of the same type

### ISSUE THREAD

**Issue by keg34** [ArctosDB/arctos#3873]
**Goal**
Maybe create a new container type (but see below).  

**Context**
We are trying to get a pile of skin patches organized in the collection.  These are in 2"x2" paper coin envelopes.  We are repurposing a small plastic tray (of which we have a stack) to hold these envelopes.  This small tray will live on a larger specimen tray in a cabinet.  We need an appropriate container type for these plastic trays.  "Unit tray" appears to be the closest thing to this in the Code Table, but its description is very specific (paper and foam; for insects) and does not match our need.  "Vial unit tray" is limited to vials as described in the code table.  Does the AWG recommend creating a whole new container type or should we simply hold our nose and use the unit tray type?  

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcontainer_type

**Value**
Envelope Unit Tray 

**Definition**
A small tray used to organize a large series of small envelopes containing specimens (e.g., skin patches).  These are generally stored permanently on a larger tray in a specimen cabinet and facilitate moving and locating specimens.

**Comment by campmlc** [comment]
This sounds reasonable, unless we want to get rid of tray types and just go
with "tray" with the option of making whatever positions are needed, which
might be simpler in the long run but which would require changing existing
values.

**Comment by dustymc** [comment]
I think a new container type ("small tray" maybe??) is reasonable.

**Comment by keg34** [comment]
Yeah - small tray would be fine.  We will not have set positions in these, so keeping it a little flexible would be good.

**Comment by Jegelewicz** [comment]
"small" is bothering me because the "nested" tray may not actually be "small"

I'm trying to come up with something better and getting nowhere!

**Comment by Jegelewicz** [comment]
Why not just use "unit tray" and we can update the definition?

**Comment by Jegelewicz** [comment]
> Well we have "big box" - it's all relative....

UGH

**Comment by campmlc** [comment]
Why not just "tray" - and we use dimensions and positions to specify small,
large, unit or not? We can keep unit tray for the specific function it is
fulfilling now.

**Comment by campmlc** [comment]
But then we should be able to put a tray within a tray.

**Comment by keg34** [comment]
I'm resurrecting this discussion as we will soon be needing a solution.  Mariel's suggestion of simply having "tray" be a container that can be of user-defined dimensions seems reasonable as long as there is no problem with having multiple trays in another tray.  On the other hand, I am guessing that for most museum folks the word "tray" immediately brings to mind a cabinet tray - i.e., the shelf that slides into a cabinet.  So this could be confusing.  "unit tray" gets around this a bit by being non-intuitive (to me at least) enough that it sends the user to the definition.  Could we use "unit tray", the definition that Teresa proposed, AND have user-defined dimensions?  Would that be disruptive?  Is it non-trivial to add dimensions to a container type that is already in use (i.e., would it be okay to use the container type without providing dimensions if a user wished to do so; I'm thinking of folks who have already used this container type and wouldn't want to go back and add the dimensions)?

**Comment by dustymc** [comment]
>no problem with having multiple trays in another tray

You cannot put a container into a like type  - eg freezer box into freezer box, or tray into tray.

> word "tray" immediately brings to mind a cabinet tray

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcontainer_type#tray agrees.

>Could we use "unit tray"

Yes

>the definition that Teresa proposed,

Would be good to get some feedback from users - @DerekSikes ?? (Note that definitions won't stop any usage, but it's probably not great to do something that your successor will never figure out either.)

>AND have user-defined dimensions?

Yes.

>dd dimensions to a container type 

Dimensions are applied to individual containers. There are some 'for X you probably want Y' buttons-n-such, but they're just suggestions/tools.

>would it be okay to use the container type without providing dimensions

Yes - just don't be surprised if you find your dimensionless freezer in a dimensionless nunc tube....

**Comment by keg34** [comment]
Ah - so dimensions are really just a way to try to avoid weird hierarchies?

**Comment by Jegelewicz** [comment]
@keg34 there is nothing stopping you from using unit tray right now.....

**Comment by keg34** [comment]
I suppose that's true... other than a definition that's all about insects.

**Comment by Jegelewicz** [comment]
I am actually in favor of your original request. How many versions of "small tray" can we have? When you decide to put a tray in the "small tray", do we call it "tiny tray"? Naming containers by purpose seems more intuitive. Since we already have "unit tray" and "vial unit tray", why not "envelope unit tray"?

**Comment by campmlc** [comment]
Sounds good to me.

**Comment by dustymc** [comment]
>How many versions of "small tray" can we have?

Fewer than if we named by purpose....

I believe we're currently (mostly) naming by the design of the container itself - "unit trays" aren't just trays, they're manufactured for a purpose - same as eg freezer boxes aren't quite just "box." Of course there's some huge blurry gradient, but I think "random generic tray on which we want to pile {thing}" probably doesn't count as a "{thing} tray" (unless there's some compelling reason for it to - container type ultimately exists to help curators sort things, I'll support whatever that takes).

https://bioquipinc.com/product-category/cabinets-drawers/unit-trays/ - I'm not sure it's reasonable to expect @DerekSikes to support relaxing the definition after all, for the same reasons 'freezer box' makes sense (it's what user expect, even if it's just another box).

I think I'm still a halfhearted fan of "small tray" - seems the safest option (eg easier to do something different with in the future).

**Comment by ebraker** [comment]
To chime in...unit trays are used for other groups besides insects, especially for storing shells and small fossils. We use unit trays to break up taxonomic series' that share the same drawer (preferable to handling the specimens themselves or pulling out a full drawer). I think we can make the unit tray definition a bit more generic - mostly that it is a modular system of chipboard trays for storing specimens/objects that generally have dimensions representing a subdivision of the containing shelf/drawer. 

I sort of think we should rename the existing 'tray' code table value to 'shelving tray' to be more accurate in describing a drawer-like thing rather than a box-like thing, and then create a new 'tray' value (storage container without a lid) so we can rely on user-defined dimensions rather than getting into multiple "small" "medium" "large" modifiers.

**Comment by keg34** [comment]
Thanks, Emily.  I like the idea of drawing a distinction between shelving trays and open-lidded box-like things.

**Comment by Jegelewicz** [comment]
From Object Tracking Planning Group:

We see the need for some types of container to allow nesting and some not. We propose that rather than creating an endless number of “small, tiny and miniscule” boxes we provide for this option in the code table with something like “nestable” Y or N. This would allow a box inside a box and a room inside a room, but not a freezer inside a freezer.  Suggest the following for what is already in the code table.

CONTAINER_TYPE | nestable | CONTAINER_TYPE | nestable2 | CONTAINER_TYPE2 | nestable3
-- | -- | -- | -- | -- | --
Falcon   tube | 0 | exhibit | 0 | range   case | 0
Nalgene | 0 | exhibit case | 0 | range case position | 0
Whirl-Pak   bag | 1 | folder | 1 | room | 1
bag | 1 | freezer | 0 | row | 0
bay | 0 | freezer   box | 0 | shelf | 0
big box |   | freezer position | 0 | shelf position | 0
box | 1 | freezer   rack | 0 | shelving   unit | 0
bucket | 1 | freezer rack position | 0 | slide | 0
building | 0 | gallery | 1 | slide   box | 0
cabinet | 0 | glassine envelope | 1 | slide drawer | 0
cabinet   position | 1 | herbarium   folder | 1 | specimen   label | 0
case | 0 | herbarium sheet | 0 | tag | 0
collection | 0 | institution | 0 | trap | 0
collection object | 0 | jar | 1 | tray | 1
column | 0 | microplate | 0 | unit   tray | 1
container label | 0 | microplate position | 0 | unknown | 0
cryotank | 0 | microwell | 0 | vial | 1
cryovial | 0 | paper envelope | 1 | vial unit tray | 0
cryovial   label | 0 | pin | 0 | virtual | 1
dewar | 0 | plastic envelope | 1 | wood case | 0
drawer | 0 | position | 0 |   |  
envelope | 1 | range | 1 |   |

**Comment by dustymc** [comment]
I don't think allowing some types to be nested is tenable - types are mostly arbitrary, I don't see that stopping the constant "student scanned a freezer box into a freezer box" issues that lead to the current rules.

https://github.com/ArctosDB/arctos/issues/4335 provides a much better solution, but only if dimensions are given - and we refuse to do so.

Maybe there's some hybrid of those things, but I'm not sure I can see it yet.
