### ISSUE TITLE
Geography with no catalog records

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3889]
Browsing this morning for good demonstration records has led me down many rabbit holes. I have yet to open a specific locality where there isn't at least one set of coordinates that doesn't fall within the specified geography, and I don't mean just the error falling out side - I mean this:

![image](https://user-images.githubusercontent.com/5725767/131358600-6d6a8f9d-4c6d-4f6a-864f-b53017a99b02.png)

But I also came across this one. When I click that outlier, I get "no catalog records found". So why is this showing up on the map?

![image](https://user-images.githubusercontent.com/5725767/131358533-0f370a21-a027-4614-b524-914ba440bec5.png)

**Comment by dustymc** [comment]
A link would be awful handy, but generally that happens when there are no cataloged records involved....

That looks like its probably https://arctos.database.museum/place.cfm?action=detail&locality_id=10111295, which has two Media records. 

It's also why https://handbook.arctosdb.org/documentation/media.html#media-creation-guidelines says

>Create only necessary relationships; allow the relational nature of Arctos to work for you.

The extra data just gets twisted up and causes confusion over time.
