### ISSUE TITLE
when I am logged in as arctostester I can access the page   http://test.arctos.database.museum/Admin/user_roles.cfm  but I cannot access the page  http://arctos.database.museum/Admin/user_roles.cfm  When I am logged in as myself I cannot access the page  http://arctos.database.museum/Admin/user_roles.cfmAn error occurred while processing this page! Check the Arctos Handbook for more information on errors. This message has been logged as 38E27325-36C3-4116-937AADFCE5667DCF error feedback

### ISSUE THREAD

**Issue by sginzbar** [ArctosDB/arctos#3935]
** Please use the "Report Bad Data" link where available to ensure the correct Curator receives your message. **

** Outages should be reported to the contacts listed at https://arctosdb.org/arctos-down/ **

** Arctos Documentation is http://handbook.arctosdb.org/ **

** Learn more about Arctos at https://arctosdb.org/ **

** Please include enough information to re-create the problem if this request involves Arctos forms. Links and screenshots are helpful. **

**Comment by Jegelewicz** [comment]
@sginzbar that is expected behavior. Only those logged in and with appropriate permissions can see http://arctos.database.museum/Admin/user_roles.cfmAn and when you are logged into http://test.arctos.database.museum as arctostester, you can see http://test.arctos.database.museum/Admin/user_roles.cfm because that user has appropriate permissions, but your personal account does not.
