### ISSUE TITLE
Institution Collection Staff Departure

### ISSUE THREAD

**Issue by lin-fred** [ArctosDB/arctos#3993]
In reference to ArctosDB/internal#126 

Adding to main arctos repository so it can be discussed in the Agents Committee, and if anyone else has comments.

**Comment by campmlc** [comment]
My original request was based on the need to remove operator permissions from an agent who has left Arctos, and wanted to do so without ever unlocking the account. No need. So for that I would need editing access. @dustymc argued that we should never remove permissions - but that makes me incredibly nervous. It would be better if we could edit permissions on locked accounts, including removing all operator priviledges, with no requirement to unlock - and have a log of that agent's operator history. Perhaps they come back later and get granted new operator access. But in the meantime, all it would take would be for some long lost operator to request unlocking an account and someone down the line who doesn't know the history granting access, and I could easily see that happening.
Alternately, we allow agents to have multiple operator accounts for different collections with different levels of permissions, some of which may be active or inactive at given times. T
I need to be able to  have students with object tracking access to several collections, data entry and manage specimens for one or two only; and when they leave, I remove all permissions. But later when they get a job as a CM at an Arctos institution, they can be granted new operator access to their new collection - and we track all this?

**Comment by Jegelewicz** [comment]
So I now have a concrete example that I need help with.

Arctos operator ssullivan (Steve Sullivan) was previously employed at CHAS, but his account is locked as he has been gone for a while so I have no idea what permissions he had been granted there. Unlocking his account will immediately reinstate them.

Steve is now Director at Hefner Museum of Natural History and will be bringing their collections into Arctos, so I will need to assign him permissions (as ssullivan) in Arctos to be able to manage those collections once they are created.

My main concern is what happens when I unlock his account and revoke permission to the CHAS collections?

**Comment by dustymc** [comment]
There's now a log, so we can track who's clicking all the wrong buttons; "if open" logic removed for next release.

Maybe consider adding something about "none of this really matters if the account is locked so check that" to the documentation somewhere @Jegelewicz
