### ISSUE TITLE
Is <creator> required?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3994]
Who is listed as <creator> for your collection? This might need a second look!

<creator> is part of the citation created at GBIF. See https://discourse.gbif.org/t/is-creator-required/3060 for further discussion.

**Comment by Jegelewicz** [comment]
> How is this connected to or complicated by our collector_role: creator ("Agent responsible for the creation of an object or work."

Not at all. - this is something add from contacts in manage_collection - or manually in the eml.

**Comment by mkoo** [comment]
What if we dont have anyone listed specifically as <creator>? From the linked GBIF discussion thread, I dont see an answer to Ken-ichi's question about leaving <creator> blank and their best practice for that field.

**Comment by Jegelewicz** [comment]
This might be a question for @dbloom

**Comment by mkoo** [comment]
Wrap up from GBIF:
You would still need to have a <individualName> for the creator but it can be “iNaturalist”. Basically use your institution or other administrator name.
"This is the person or institution to contact with questions about the use, interpretation of a dataset."

Closing since we need a new issue for collections to review all their metadata.
