### ISSUE TITLE
Feature Request - bulk collecting event

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4033]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**

SpecimenResults-->manage-->collecting events needs rebuilt

**Describe what you're trying to accomplish** 

Logs suggest this form gets very little or no use. I don't think the form is usable/useful as-is. I can't implement https://github.com/ArctosDB/arctos/issues/732 on it without significant changes, and I don't want to put more work into a form that doesn't get used.

**Describe the solution you'd like**

Figure out what, if anything, people would like to do with a search result set of collecting events; rebuild the form to accommodate that.

**Comment by campmlc** [comment]
I don't use this because it's broken. I have to use update specimen events instead.  
I need to be able to bulk update events for groups of records that should share events, but don't, such as hosts and parasites cataloged separately.

**Comment by dustymc** [comment]
The form isn't broken, it's disabled, and that sounds a bit like magic (finding data where there is none) from here. I'd need some sort of better explanation or annotated example or something.

**Comment by campmlc** [comment]
This goes back to matching parasite and host records based on shared
identifiers, collectors, and collection data. It is a core feature of
Arctos parasite / host management. Once we can identify linked records, we
need to be able to update to shared georeferenced  collecting events.
Ideally, we'd add this as new specimen event using the Manage tool.

**Comment by dustymc** [comment]
>add this as new specimen event

Just adding events to one based on the other is circular - everybody ends up wearing all the bad data and nobody can figure out what's correct. Both don't necessarily participate in all events - a host might have parasites pulled any number of times. Etc., etc., etc. There's plenty of room for development (and/or procedures - much/most this is all easily avoided by simple behavioral changes) but I'm still not at all seeing how any of this is compatible with a bulk-update form.

Maybe downloading - sorting the above out in a spreadsheet - uploading could lead somewhere productive, but those tools exist.

**Comment by campmlc** [comment]
Example:
The following specimens are associated with a mis-transcribed locality.
https://arctos.database.museum/saved/S%20side%20dettaki%20cr
I have confirmed the mistranscription from original field catalogs. Note
the associated records contain types - and the incorrect locality has been
published. We obviously need to keep the verbatim locality and potentially
the original specimen event assigned by "unknown". I'd like to use the
Manage Events tools to be able to move all of these records to a new
specimen event  with the correct locality with my name and date as
determined by. But there is no way to do that with the current tools. And
yes, I could bulkload specimen events. But I usually come across things
like this when I am deeply involved in managing a different project - and
having the ability to make an assertion that these should be in a different
locality/event stack using specimen events from the Manage tool would allow
me to do that without disrupting the workflow of the project I'm involved
with. If we don't do these things as we find them, they never get done.
Note that I fixed a number of records from this same verbatim locality
previously - but didn't get all of them, and I had to do so by moving them
to a new collecting event, rather than adding a specimen event, because
that is the only tool available in the Manage dropdown.

https://arctos.database.museum/saved/S%20side%20dettaki%20cr

The correct transcription is "S side Deltaic creek" which is in Arctos as
two localities: "S side Deltaic creek" and also " Stewart-Cassiar Highway,
British Columbia Highway 37, Dease Lake Highway, S side Deltaic Creek".

**Comment by dustymc** [comment]
Thank you, adding a specimen-event is actionable. 

Unless there's some compelling reason for instant gratification I'll still route it through the bulkloader, which should avoid the almost-inevitable problems involving raw CPU and locality locks this would otherwise cause - let me know if that seems problematic.

>in Arctos as two localities

Unrelated to the current issue: that's the 'simple behavioral' things I mentioned earlier. Pre-create named events and 1) this just never happens, and 2) a huge number of data entry fields - the things that lead here - are no longer needed or used.

If the only difference is in the specloc, you can just change one and they'll auto-merge. (Or you can name one or both to prevent that, if that's the intention.)

>incorrect locality has been published.

This has come up in various contexts before, there's also a trivial solution (and some very nice tools which exist for precisely this reason): Require (eg loan agreements) whatever data is used for publications to get stashed on Dryad. Its neat that Arctos has the capacity to keep incorrect data hanging around, and it's awesome that Arctos users are willing to entertain such ideas, but even that only goes so far. Dump whatever you used for analysis on Dryad and mention it in the publication and it doesn't matter what we do to the data, a future user can still understand the publication, and maybe even why it makes no sense in light of current data.

**Comment by Jegelewicz** [comment]
@campmlc please add a priority label to this.

**Comment by campmlc** [comment]
Priority high, because without this tool, every time I come across these situations I have to either ignore them or do something that doesn't solve the whole problem, making things worse.
I'm not sure what routing through the bulkloader would mean - if it means I can still use the Manage tools to do so, then probably OK. If it means I need to drop everything I'm doing and spend several hours searching for all other related records and creating a bulkload file, or wait for an hour before the bulkload finally goes through and remember to come back and load, then no.
And yes, in an ideal world, we'd precreate localities for everything. But in this case, these are legacy data from 15 years ago hand entered by a variety of students, and what I'm hoping to accomplish here is to have the tools I need to fix these problems as I come across them during my daily activities. We have this same tool for Edit Collecting Events - I see no difference in making the tool available for specimen events.

**Comment by dustymc** [comment]
See also https://github.com/ArctosDB/arctos/discussions/8014
