### ISSUE TITLE
Add subsample barcode or part ID to Loan bulkload tool

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#4124]
Related to #4119
I would like to request that we add a field for subsample barcode to the loan bulkload tool.
This would actually save me an entire step when I try to subsample parts, barcode them, and add these subsamples to a loan.
Currently I am having to create the subsamples and add their barcodes using bulkload parts, and then separately bulkload these parts to a loan using the loan bulkloader. 
The loan bulkloader provides the tools to create subsamples, but no field to add a barcode to these newly created subsamples. I am asking for this functionality to be added to the loan bulkload tool.
Also, relevantly, the loan bulkload tool does not require a priori knowledge of the part condition in order to create subsamples: "NULL (empty) does nothing, leaving existing values as-is; a value updates the part."

**Comment by campmlc** [comment]
Also relevant: can we add the ability to create a permanent PID to these subsamples with this tool? I understand that if we do this, the part can no longer be deleted. But this would not affect legacy samples, only newly created parts/subsamples. Perhaps with a 24 hr lag before the permanent identifer goes into effect?

**Comment by dustymc** [comment]
> add a field for subsample barcode to the loan bulkload tool.

I'm instinctively hesitant to add any complexity to those forms at this point, but I can't quite put my finger on how that might spiral out of control; as you say, it's already creating parts. I'd like more input, but I think this seems reasonable??

> create a permanent PID

That's for https://github.com/ArctosDB/arctos/issues/3630

**Comment by Jegelewicz** [comment]
Add a single field here - subsample_barcode

![image](https://user-images.githubusercontent.com/5725767/142699430-a6a1fdb8-80c6-4cc1-9949-ceb38d4a56bd.png)

**Comment by Jegelewicz** [comment]
Otherwise @campmlc has to bulkload subsamples using part bulkload tool with a container barcode (two bulkloads for a single loan)

**Comment by KyndallH** [comment]
Would this be too complex to add: subsample barcode, condition, remark, and new part name for the subsample?

This also on the other ways to add parts to a loan (add by part barcode and add part). I have the pickled frog in my hand and I'm subsampling the frog for a muscle sample. So either I have to create a whole new part or I put "whole organism" on loan. I'd also like to update the condition while I'm looking at it and update the loan remarks.

**Comment by dustymc** [comment]
For the loan-thing in specimenresults: No, I don't think making that crazy is going to bother anyone, but let's not undo anything that happened in https://github.com/ArctosDB/arctos/issues/2741 either.

For the add-by-barcode thing: I'm hesitant to mess with that at all, at least outside a focused discussion, it serves a purpose and subsampling seems beyond that. MAYBE it makes more sense to have another similar form for more complex stuff, maybe not, IDK, belongs in the same conversation, I think.

For the loan item bulkloader: I still don't know, but if we're creating parts then it still seems fairly reasonable to add some part-stuff (or that's the first step towards building up to something that's so complex that nobody can use it and there's already a loader to do that and just using the existing tools is like three clicks.....).

Maybe this is already to the point where it deserves a focused issue instead of the many scattered that are open now; there's an issue for that, somewhere.....

**Comment by Jegelewicz** [comment]
This is a request to make adding parts to loans easier when subsampling is involved. Something like this could be added to the bulkload file.

field | required | documentation 
-- | -- | -- 
create_subsample_part_name | no | If NULL, subsample part will have the same name as part_name, if complete subsample part name will be what is entered here 
create_subsample_barcode | no | The barcode assigned to the container holding the subsample being created in create_subsample 
create_subsample_condition | no | if NULL subsample part condition will be the same as part_name condition
create_subsample_remark | no | if NULL subsample part remark will be the same as part_name remark 

Possible?

**Comment by dustymc** [comment]
All related issues need rounded up and summarized, maybe in https://github.com/ArctosDB/arctos/issues/3987

**Comment by Jegelewicz** [comment]
They are rounded up and summarized in the project - https://github.com/ArctosDB/arctos/projects/35

**Comment by Jegelewicz** [comment]
@campmlc @KyndallH is this still an open request?
