### ISSUE TITLE
help with bulkloading additional specimen identifications

### ISSUE THREAD

**Issue by droberts49** [ArctosDB/arctos#4165]
I've got historic identifications that I want to add to existing Arctos records; they already have an accepted taxonomic identification and these will not replace it, just add to the history. The bulkload identification (https://arctos.database.museum/tools/BulkloadIdentification.cfm?action=ld) doesn't give an option for using the ID Formula of A {string} and I want to keep these as they are listed. Some have the genus only as a first letter, some are so old I can't find them. Is there a way to keep them as is?

**Comment by dustymc** [comment]
>any valid identification; uses same formula as catalog record bulkloader

That is in reference to https://handbook.arctosdb.org/documentation/bulkloader.html#taxonomy

The loader should accept ``any valid taxon {any identification string}`` as scientific_name.

I'm not sure how tested that is, so perhaps try it with a small batch first. Let me know if you have any problems.

**Comment by droberts49** [comment]
Ok, will do. Thanks, @dustymc

**Comment by droberts49** [comment]
@dustymc  the loader appears to only accept A names, not strings.
https://arctos.database.museum/tools/BulkloadIdentification.cfm

![image](https://user-images.githubusercontent.com/16580148/144920866-135d1949-ecfa-4acd-b495-a94e1cde5b1d.png)

**Comment by droberts49** [comment]
So perhaps the issue is that these aren't "valid" but they are historic and are part of the specimen's data history, so I want to keep them as they are.

**Comment by dustymc** [comment]
@droberts49 you need a taxon name that Arctos knows about, and the string formatted as above

So instead of eg ``A. Eupatoria``

you need something like

``Alces {A. Eupatoria}``

which will link that to https://arctos.database.museum/name/Alces (probably not what you actually want, just the formula), or 


``Animalia {A. Eupatoria}``

which uses https://arctos.database.museum/name/Animalia if you know less than genus, or 

``unidentifiable {A. Eupatoria}``

to use https://arctos.database.museum/name/unidentifiable if you really don't know anything and aren't willing to guess (which is perfectly fine).

All of those will display "A. Eupatoria." 

Let me know if that works for you.

**Comment by droberts49** [comment]
Ah! Thank you for the help. I'll try that out.
