### ISSUE TITLE
Error on Log out

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4194]
Every time I log out I am greeted with this error

> An error occurred while processing this page!
> Check the Arctos Handbook for more information on errors.
> 
> This message has been logged as 28511C5B-4BA8-443E-A6CD1EB4C6EF0226 Please contact us with any information that might help us to resolve this problem. For best results, include the error and a detail description of how it came to occur in the Issue. 

Why? And what does it mean?

**Comment by dustymc** [comment]
https://arctos.database.museum/Admin/errorLogViewer.cfm?request_id=28511C5B-4BA8-443E-A6CD1EB4C6EF0226

<img width="1718" alt="Screen Shot 2021-12-14 at 6 59 00 PM" src="https://user-images.githubusercontent.com/5720791/146115033-9e451ca9-1bd5-4712-83ab-14073caa0d38.png">


https://github.com/ArctosDB/arctos/issues/4173

https://github.com/ArctosDB/arctos/issues/4107#issuecomment-974474810

**Comment by Jegelewicz** [comment]
But why does this happen after I log out - I shouldn't be accessing that form anymore...

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/4107#issuecomment-974474810

Current behavior reloads as the new you, which saves me a fair number of clicks every day. The offer to do something else is still open, but I still can't identify anything that seems like it would be less annoying.

**Comment by Jegelewicz** [comment]
This has been bothering me lately. Nearly anything I am doing in Arctos is somewhere that I cannot be when logged out so almost every time I log out I end up with the error. Could the process of logging out just send me to the main search page? Do people really want to stay where they are when they log out or they are going to close Arctos anyway so ending up at the search page wouldn't bother anybody where the weird error makes it seem like Arctos is broken.

**Comment by dustymc** [comment]
>Do people really want to stay where they are when they log out 

I do, I think, but I'm not a typical user and I'm pretty handy with tabs. It would be good to somehow solicit more input, I'm OK with about anything.

**Comment by Jegelewicz** [comment]
@campmlc @ewommack @ebraker @mvzhuang does this happen to/bother you? If it is just me, then I can live with it. I'm just concerned that regular users are ignoring it but irregular users might find it troublesome.

**Comment by mvzhuang** [comment]
Doesn't bother me because I kind of rarely log out (it usually times out before that happens) unless I'm switching with a student. I do prefer that it keep on the page that I was working on, so that I can get back to it faster and the students spend less time clicking. But, I think when I log in from my working page, it sends me to the search page or profile page instead of the original page, so I have to click back twice, or log in from another tab and refresh my working tab.

**Comment by campmlc** [comment]
I do think that minimizing obscure errors is a good thing - and conversely,
having error messages pop up randomly when folks are doing nothing wrong is
an annoyance at best and a  deterrence at worst. Let's come up with an
alternative - at the very least, maybe just a message that says "You have
been logged out of Arctos. To continue working, please log in at xxxxxx".

**Comment by ebraker** [comment]
It may be safe to say I have never logged out of Arctos(!)....but I agree with Mariel that some sort of more legible error message is a good approach.

**Comment by ewommack** [comment]
I'm like @mvzhuang and @ebraker - I'm more likely to be timed out then to actually log out. 
I'm not sure it would bother me too much, mostly because I feel I run into the error anyways when I click on a link someone sent for some curatorial aspect of Arctos in a Github issue or something. I remember that I need to log in, then click the link again and it takes me where it should. So not a totally unfamiliar error for me.

**Comment by mkoo** [comment]
> I do think that minimizing obscure errors is a good thing - and conversely, having error messages pop up randomly when folks are doing nothing wrong is an annoyance at best and a deterrence at worst. Let's come up with an alternative - at the very least, maybe just a message that says "You have been logged out of Arctos. To continue working, please log in at xxxxxx".

Absolutely, currently it looks like something went wrong when you log off. If form stability is the issue here, I think logging off is a clear signal that the user doesnt care that they remain on the same page.

Personally I'm in the 'what's logging off?' boat-- first time I've ever done it was to see what Teresa was talking about!

this is major UI thing that does not instill confidence and needs to be addressed

**Comment by Jegelewicz** [comment]
UGH people who do not log out of applications make cyber security nuts.

**Comment by mkoo** [comment]
> UGH people who do not log out of applications make cyber security nuts.

that's why Arctos does it for you!

**Comment by Jegelewicz** [comment]
No it does not - not immediately and it leaves us open to hacks. Someone walks up to your computer, opens a browser, and is logged in to Arctos as you - a person with superpowers who can really make a big mess. Not saying this is likely, but it IS possible.

**Comment by mkoo** [comment]
Update on fixing?

**Comment by Jegelewicz** [comment]
I still get the error.

**Comment by dustymc** [comment]
>not immediately and it leaves us open to hacks

Every web developer ever would log you out the second your eyes leave your screen if they could. There are usability tradeoffs. I'd be thrilled to reduce the timeout, but that's another issue.

>Update on fixing?

If a solution has been suggested I'm not aware of it. It's pretty easy to do something different, but I don't know what that might be.

**Comment by Jegelewicz** [comment]
> If a solution has been suggested

https://github.com/ArctosDB/arctos/issues/4194#issuecomment-1019004409
