### ISSUE TITLE
Code Table Request - new media type "3D model" and new MIME types "application/.stl" and "application/.ply"

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#4206]
I'd like to request a new code table value "3D model" (or some similar variant, e.g. "surface model," "surface mesh," "mesh") for [ct_media_type](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctmedia_type). Currently the CT Scan media value includes derivatives in the definition, however, a new value will be more inclusive for 3D models generated by other methods (laser surface scanning, photogrammetry, etc.). Plus, a "3D model" label will better communicate to users that a model is available, as currently the a CT scan and 3D model display the same: 

![image](https://user-images.githubusercontent.com/11336485/146613451-2f0889bf-5df2-4d4c-bd85-3d4a640f993b.png)

Proposed definition: A mathematical coordinate-based representation of the surface of an object. Applicable to models created using methods such as photogrammetry, CT scanning, and laser surface scanning.

We also need the following common file types for [ct_MIME_type](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctmime_type):

application/.stl Standard Tesselation Language
application/.ply Polygon File Format

**Comment by dustymc** [comment]
Should we merge this value with CT scan or is this something different? "3D image" maybe?

I don't have any strong feelings either way, but it seems like fewer values are probably more useful to users unless there's some reason to do otherwise. @jldunnum @ewommack ??

https://www.digipres.org/formats/mime-types/ suggests ``application/sla`` and https://www.iana.org/assignments/media-types/media-types.xhtml#application ``model/stl``, I have no idea how to resolve that.

I can't find anything at all for .ply and I'm not sure what the implications of making something up are - maybe nothing as long as it start with ``application/`` ??

**Comment by ebraker** [comment]
I think we should keep them separate to be specific (also, my problem in the screenshot would be replicated if we merge values). The jump from a CT scan to a surface model is much more loss in data than say, from a  TIFF to jpeg, which are represented as separate media types. Also, in general (not always!), CT scans and 3D models often have different audiences (e.g., scans more often used for research, whereas 3D models often use for education/art/figures/general public), so I think it is important to distinguish for users.

**Comment by ebraker** [comment]
approved to add at 2022-01-20 meeting
