### ISSUE TITLE
Feature Request - Begin and end dates for preservations?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4231]
**Is your feature request related to a problem? Please describe.**

@KyndallH  says
I wonder if there needs to be a "removed" date for the attributes. Right now, you add the preservation, and it keeps adding to it, but no way to state if that method ended. The example below is not ending because it is archived in DESS in the freezer. But there is an end date/time for things fixed in formalin. Or if I decant the ethanol or DESS off. 

![unnamed](https://user-images.githubusercontent.com/5725767/148471199-05583f23-2957-46f9-93f2-65f28bb709b9.png)

Also see @cjconroy comment in https://github.com/ArctosDB/arctos/issues/4223#issuecomment-1006896440

**Describe what you're trying to accomplish** 
Better recording of what really happens to an object and/or ease in recording what you know

**Describe the solution you'd like**
Unsure as these seem like conflicting goals

**Describe alternatives you've considered**
In AWG today we discussed adding some "simplified" preservation but also how that will probably lead to a big mess in preservation just like we had in part names.

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.

**Comment by dustymc** [comment]
>conflicting goals

Agreed.

The only viable solution (that doesn't require Major Surgery, anyway) I see is another Attribute, maybe "decant" (or something more specific, whatever). Among other things, those data will need their own methods - did you sorta hope the formalin fell off between jars, or was there some rinse cycle or etc., maybe as described in some publication?

>simplified" preservation 

Yes, I don't think I'm completely opposed to eg "frozen in DESS" if:

1. There are significant curatorial usability implications, and
2. There are not significant "potential borrower" usability implications

>lead to a big mess

Yes, introducing combo-terms would unavoidably lead to messy data.

>just like we had in part names.

Not exactly - whatever we might do here won't be multiplied by part-count (as authority - it would be as assertions). I'm not suggesting combos would lead to usable data - that's a question only the users can answer - but the mess would be slightly more contained due to the normalization of concepts, even if the terms are not normalized.

**Comment by KyndallH** [comment]
Another valid but what-if scenario:
I receive samples that have been stored in -20C for 10 years (true story). Now, they are moved into LN2.

Knowing both of those will greatly impact the quality of the tissue and what they can be used for. I need to know that they were in -20C for 10 years - the timeframe is critical. If they were only in -20 for 1 year versus 10 years make a huge difference on the quality of the tissue. And in this case, decant would not work.

**Comment by dustymc** [comment]
>decant would not work.

Why not? And maybe there's something important there - did you "decant" after the freezer started stinking in a 95F room, or while everything was still happy in a cold room, or ??? Method still seems handy/necessary, and a "decant" (transfer, whatever) event still seems like the least-confusing place to put it.

Or maybe this is "just UI" - you couldn't have had the thing at -20 and -80 at the same time (unlike frozen-in-goo), the first -80 date can be inferred to also be the last -20 date. (But that can't get at those details.)

If that's all wrong and we somehow really need a timespan:

1. ISO8601 (but not as implemented in Arctos) provides two potential formats:

* 2020-01-12/2022-01-12 means "from date to date" (and the dates can bear any year-or-better precision)
* 2022-01-12/P3Y means "for 3 years after date" and P3Y/22022-01-12 means "for three eyars ending on date"

2. Or we could change ``specimen_part_attribute.determined_date`` to some "normal" ISO8601 pair.

I think both of those probably qualify as Major Surgery, and both probably provide interesting ways to mangle things like [tooth abbreviation](http://test.arctos.database.museum/info/ctDocumentation.cfm?table=ctspecpart_attribute_type#tooth_abbreviation).

**Comment by Jegelewicz** [comment]
> Or we could change specimen_part_attribute.determined_date to some "normal" ISO8601 pair.

that is the original request
