### ISSUE TITLE
Feature Request - create spatial data

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4263]
**Is your feature request related to a problem? Please describe.**

https://github.com/ArctosDB/arctos/issues/4183 Part Two: Arctos now (soon...) deals in spatial data, but there's limited UI.

There's no way at all to create/import such data for geography.

For Localities, the GeoLocate not-quite-WKT return can be saved as spatial data, but there is no way to edit nor to provide/upload more complex data.

**Describe what you're trying to accomplish** 

We probably need some sort of a UI; I'd like to get ahead of that before it becomes a problem if possible.

**Describe the solution you'd like**

Tell me how you'd like to manage spatial data.

**Describe alternatives you've considered**

I can SQL WKT in.

**Additional context**

https://github.com/ArctosDB/arctos/issues/4259

**Priority**

??

**Comment by mkoo** [comment]
is this for localities or higher geography or something else? 
i havent had a chance to address #4259 but one way we could view spatial data is it's all "footprints" with point localities just having a really small (or large) radii. We may have to take this in baby steps since we want to integrate Geolocate and Berkeleymapper still. 

if by creating spatial data, you mean assign points or sets of coordinates then not a large ui change, is that? seems like it's still GL. but let me know what you mean or maybe we need to have a geography-focused meeting tomorrow or soonish

**Comment by dustymc** [comment]
> localities or higher geography

Both, but the number of people who might update geography is much lower - maybe enough so that a UI isn't an imminent issue at all.

>it's all "footprints" 

Well it is!

>integrate Geolocate and Berkeleymapper still.

Right, lots of reasons to keep text (or something that can easily be made into text) around, hence the 'calculate whatever's not given from whatever is' idea in #4259. 

>not a large ui change, is that

No, I don't think anything I'm bumping into is. (Until we want it to be, anyway.) I'm mostly just trying to not paint myself into any awkward corners at this point.

>geography-focused meeting

I'm in, say when.

**Comment by dustymc** [comment]
Closing - can reopen when someone has data to load.
