### ISSUE TITLE
Question on the new Browse/Edit Bulkloaded Data

### ISSUE THREAD

**Issue by ewommack** [ArctosDB/arctos#4265]
Playing around to get a feel for all the different ways the new system can work and I had a question @dustymc. If I entered the text "autoload_core" in the status column for an entry by hand (without going through any of the control buttons), will that then set it to load?
![loading documents question](https://user-images.githubusercontent.com/18562884/149575486-d4261c4a-576c-4d8d-8908-7624aeda11bf.jpg)

**Comment by dustymc** [comment]
Yep - there are any number of ways to change status (and other fields), the only thing the loader scripts care about is the value.

**Comment by ewommack** [comment]
Thanks @dustymc! I'm going to close this issue, but may open it again if I had more questions as I poke around. I'm trying to get a feel before I record a tutorial and write up the newsletter article.

**Comment by sharpphyl** [comment]
Is the status a free form field or is there a code table?  I was able to write in "seed record - do not delete?" so it must be free-form.  If I want to keep records in the bulkloader for further review and load others, do I keep the status as "waiting approval" or just something besides "autoload"? In other words, I could put in that field what the problem is for review and it wouldn't upload the record?

**Comment by dustymc** [comment]
Status is uncontrolled text - the loader returns errors in there, and users may use it for various things - "note to self," describing "seeds," whatever.

>something besides "autoload"

https://handbook.arctosdb.org/documentation/bulkloader.html#processing - ``autoload_core`` and ``autoload_extras`` are the functional values, all other values result in nothing happening.

**Comment by sharpphyl** [comment]
Thanks.  But will DELETE delete that one specific entry?

**Comment by dustymc** [comment]
>DELETE

Oh yea, that too - should be added to documentation.

**Comment by sharpphyl** [comment]
Thanks!
