### ISSUE TITLE
Help on Small Batch Media Upload

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#4267]
**Describe the bug**
I'm trying to do a small batch media upload for the first time (per [https://handbook.arctosdb.org/how_to/How-to-Upload-Media-to-TACC.html#small-batch-uploads](https://handbook.arctosdb.org/how_to/How-to-Upload-Media-to-TACC.html#small-batch-uploads)) I uploaded my zip file with27 images over a week ago and have not received an email with the file to upload my metadata.

Batch name is JohnFinkGarScales

**To Reproduce**
1. Create zip folder of (small) JPGs
2. Go to upload images
3. load file
4. nothing
5. I tried regenerating download file from existing jobs, but it doesn't contain a URI

**Data**
I've got the zip file on a different computer, I will attach if needed on Tuesday.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Retaining some sort of small batch upload would be preferable to going through the normal media upload path, which seems exceptionally complicated. 

There are two roadblocks I see right away 1) It could take up to a month for our IT to install cyberduck for me (that's how long it took for them to install coldfusion for me)(it seems like the kind of program they might push back on????) and 2) I try to not use my personal phone for work stuff (and I'm not supposed to), but since I have no work cell, I would have to use it for TACC authentication.

Probably in the long run, yes it is worth it to get this set up, but for moment when I'm just trying to get a measly 27 low resolution condition photos uploaded for a loan (and I don't currently need to bulkload photos very often), it seems excessive. I might as well upload these one by one.

If the small batch upload does not work anymore, we should probably update the documentation . . .

**Comment by dustymc** [comment]
>exceptionally complicated

It shouldn't be! It's not! But I'm not terribly surprised to see that it comes across as such.

>install cyberduck

That's just a client. I personally think it's just unnecessary complication but some folks like UIs. In any case, firing up any sort of terminal and

```
scp dailyfolder me@data.tacc:/my/existing/path/dailyfolder

```

is how I upload stuff. I'd add that to the docs, but I suspect that anyone who would use scp already knows how to use scp??

>phone

That might be a question for TACC, I sorta guess they can accommodate but IDK.

Anyway, thanks, that's helpful, I'll see if I can figure out what's going on and patch the thing up for now. If I can't (or if I can) I could upload for you, just get the data somewhere I can find them - maybe that could even be a suitable long-term replacement for the twitchy little tool??

I'll hijack this issue once your problem is addressed, yes we should somehow end up with functional tools or better documentation or ??

**Comment by dustymc** [comment]
I adjusted some permissions (and added a cool new header), I'm not sure if that's the new server setup or just the test environment. Otherwise it worked for me, so I'm not sure what happened. Calling this in next release, I'll start a new issue for the general discussion.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Thank you!

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Still haven't gotten an email for my latest attempt (I've checked junkmail as well). Job name GarScales_attempt3.

**Comment by dustymc** [comment]
Can you send me the zip please?

**Comment by dustymc** [comment]
Nevermind, I think I found the clog (not yours) - let me know if it doesn't do anything in interesting in the next few hours.
