### ISSUE TITLE
Feature Request - Add UTMs to locality loader

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#4271]
**Is your feature request related to a problem? Please describe.**
I need a way to bulk create localities with UTM data.

**Describe what you're trying to accomplish** 
The easiest way to this would be to pre-create the localities and then use the collecting event loader to load the original coordinates provided by the collector.

**Describe the solution you'd like**
Add UTM data fields to the collecting event loader.

**Describe alternatives you've considered**
#4255 will allow me to add UTMs when I'm individually entering localities, but using it to individually add coordinates to localities I've just bulkloaded will be a lot of extra time and more chance for error.

**Comment by dustymc** [comment]
>pre-create the localities and then use the collecting event loader to load the original coordinates provided by the collector.

Clarification request: Do you want to load events under existing/pre-created localities, or create locality+event at once? (Or something else...)

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> create locality+event at once

Would be easiest, but per this comment in the collecting event bulkloader:
![image](https://user-images.githubusercontent.com/47402809/150023684-80d96fbe-7149-45b6-80b4-568af8c473f1.png)

I had planned to just pre-create the localties.

**Comment by dustymc** [comment]
So the locality loader would accept UTM? That's possible, but there'd be no place for the "as-entered" coordinates.

Conversely I can just create locality+event, which provides a place for as-entered but can't result in named localities. Does that work?

"As-entered" is part of the stuff that gets ignored when loading events against preexisting localities. (And I think that's correct if we're reserving "as-entered" for "inputs which might have been mangled by some script" rather than "the collector said," and I think we must do that.)

>provided by the collector

Maybe this should involve the "verbatim coordinate-like stuff" issue that we've been mostly avoiding forever? That would also provide the ability to get at 'the collector said N but we think they meant "North" rather than "UTM Zone N" which is around Venezuela'. (But I suspect that would result in your UTM data in two places and therefore unable to do what you do.)

ANYWAY, I can certainly convert UTM to DD.d, but I haven't (yet, I hope) wrapped my head around how to do so while keeping all of the bits-n-pieces that I think you want to keep.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
>So the locality loader would accept UTM? That's possible, but there'd be no place for the "as-entered" coordinates.

That would work too. My plan was to put something like "collector provided utm coordinates from GPS (zone XXXXXXX,XXXXXX datum) in Georeference soure anyway. Not sure if that is the correct place. Maybe we need a Georeference History locality attribute?

> can't result in named localities

No, I have to have named localities.

**Comment by dustymc** [comment]
>Georeference soure

Seems reasonable to me, but that does seem like something that would benefit from focused discussion.

Can we change the title of this to "Add UTMs to locality loader" and go next task?

**Comment by dustymc** [comment]
Next release will convert UTM and reproject datum (for UTM or DD.d) if necessary.

**Comment by Jegelewicz** [comment]
Now can we dig UTM out of verbatim/remarks for all the stuff already in Arctos and update stuff?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Thanks!
