### ISSUE TITLE
Batch Scan Upload CSV file option should be in the component loader environment

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4290]
# Error Text
An error occurred while processing this page!
Message: ERROR: query returned no rows Where: PL/pgSQL function movecontainerbybarcode(character varying,character varying,character varying,character varying) line 69 at SQL statement
Detail: Parameter types passed (4): CF_SQL_VARCHAR, CF_SQL_VARCHAR, CF_SQL_VARCHAR, CF_SQL_VARCHAR
Check the Arctos Handbook for more information on errors.

This message has been logged as F1DC9B7A-D3D1-4EC6-872FE598EA77EB04 Please contact us with any information that might help us to resolve this problem. For best results, include the error and a detail description of how it came to occur in the Issue. 

# Where it happened
[**Provide a link to or a description of the page where the error occurred.**](https://arctos.database.museum/batchScan.cfm?action=saveCSV)

# Steps to get there

1. Load the file
2. Get Loaded - proceed to save
3. Click proceed to save
4. Get error

[ALMNH_containers.csv](https://github.com/ArctosDB/arctos/files/7929456/ALMNH_containers.csv)

# Problem

# Solution
**Community response with directions for how to correct the problem**

**Comment by dustymc** [comment]
"query returned no rows" is generally "there's no such thing."

You can check here:

<img width="443" alt="Screen Shot 2022-01-24 at 3 11 11 PM" src="https://user-images.githubusercontent.com/5720791/150880432-4a43b02a-c8d8-4e2b-93f0-b752c1ac8f71.png">

or start with these:

<img width="80" alt="Screen Shot 2022-01-24 at 3 14 09 PM" src="https://user-images.githubusercontent.com/5720791/150880771-543683c9-bf99-4e52-81b9-7078519a666c.png">

**Comment by Jegelewicz** [comment]
Any way we can make this more functional? Maybe get a report of the bad rows and load the rest (like the component loaders)?

**Comment by dustymc** [comment]
Yes the CSV option should be moved to the component loader ecosystem, ideally before it melts the environment it's currently in.

And the rest of that form can probably be deprecated  - surely nobody's still working on a network that can't support /moveContainer.cfm?!

**Comment by Jegelewicz** [comment]
>  ideally before it melts the environment it's currently in.

Adding a priority commensurate with that statement.

**Comment by dustymc** [comment]
Can the CSV component of this issue be solved by adding move_to_barcode (eg choose new parent or leave NULL to ignore) to BulkloadContainer Edit? 

If not, I need actionable specifications for the needed loader.

This is greatly complicating https://github.com/ArctosDB/arctos/issues/5815 and it looks like there's a simple solution available: both altering the existing loader or creating a new would be much, much simpler - and so less likely to find a way to mangle containers - than dealing with this antique mess, so I'm upping priority. It would be great if I can move on this so I can finish this project before next ~Tuesday (so I might do something random if I can't get feedback here).

@DerekSikes @KyndallH @campmlc @Jegelewicz HELP!

**Comment by Jegelewicz** [comment]
I don't really have skin in this game.

> adding move_to_barcode (eg choose new parent or leave NULL to ignore) to BulkloadContainer Edit?

If it accomplished the same task, then seems OK to me.

**Comment by dustymc** [comment]
>solve the issue that with BulkloadEditContaineryou have to know the old container type

That's only an "issue" because "single-factor identification" has caused problems. Perhaps the finer-grained container access has fixed that, I'm happy to drop the constrain if there's some agreement that the check isn't necessary.

> get a list of container

Get Container from Barcode

> The alternative would be to have the Bulk EditContainer tool allow for loading of all the correct matches, and csv download of the incorrect matches with the actual container type values so that the problems could be isolated and fixed.

I am incredibly hesitant to make another form cryptically and overly complex. I think we ALWAYS come to regret that, it makes things way more complicated than they could be, that prevents progress. https://github.com/ArctosDB/arctos/issues/1689 is one example.

And on that note - why do we have this anyway? Do we REALLY need to mass move containers that aren't in our hands? That seems to be the cause of this issue, and was only noticed because the non-scanned input wasn't a container at all - not-scanning the wrong thing but with valid containers would have silently and happily made "interesting" and potentially unresolvable messes. Can we reserve movement for scanners? (We can't, but "scanner-centric forms" might be a decent approximation.)

**Comment by campmlc** [comment]
> > solve the issue that with BulkloadEditContaineryou have to know the old container type
> 
> That's only an "issue" because "single-factor identification" has caused problems. Perhaps the finer-grained container access has fixed that, I'm happy to drop the constrain if there's some agreement that the check isn't necessary.
> 
Any way to have the tool run a precheck on old container type, and flag any discrepancy prior to load? With csv download to fix and reload?

**Comment by Jegelewicz** [comment]
I like the idea of adding the move functionality to the bulk edit tool (just add a column for parent_container?). To be honest, it would be nice to have that same ability when creating containers (create them and put them where they belong all in one fell swoop). Then we can re-name [this](https://arctos.database.museum/batchScan.cfm) Container: Batch Scan in the directory.

Probably need to add something on the tool page to let people know the csv option is now completed via bulk edit

**Comment by Jegelewicz** [comment]
Do we know who has used the csv option in the last 6 months?

**Comment by DerekSikes** [comment]
Are you talking about the Container: Bulk Move -> CSV Paste mode ?

I use this all the time. I've asked a while ago to have the link to CSV Paste mode less squished between the button above it and the link below it - there should be at least 1 blank line of space separating these so it's harder to accidentally click the wrong thing.

I hope whatever you are planning doesn't: change the name or the basic functionality of this.

Improvements discussed included the ability to not need to delete the comma my scanner sends after scanning the parent barcode (so the whole form is more comma-friendly).

And the ability to hit 'enter' to 'save' rather than being forced to use the mouse to click the button.

**Comment by Jegelewicz** [comment]
> Are you talking about the Container: Bulk Move -> CSV Paste mode ?

Nope, I am asking about [Upload CSV file](https://arctos.database.museum/batchScan.cfm?action=loadCSV)

**Comment by campmlc** [comment]
Request for meeting if necessary to discuss this. I currently have no other means to move a list of batcodes to a new parent.

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/7464
