### ISSUE TITLE
Help Please: How to select the right scientific name

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#4312]
I'm trying to pick the Taxon named "Bola" from the source Nomenclature 4.0.
<img width="976" alt="Screen Shot 2022-02-06 at 6 36 26 PM" src="https://user-images.githubusercontent.com/17605945/152720594-abc836ec-5db0-4bd9-8f99-e3cf19f92323.png">

When I go to the edit determination screen in my catalog record to add to the associated taxa, only the Linnean term shows up:
<img width="672" alt="Screen Shot 2022-02-06 at 6 35 29 PM" src="https://user-images.githubusercontent.com/17605945/152720461-150f8c02-2e16-49a1-90c4-e64b07d0a79c.png">
https://arctos.database.museum/name/Bola

Does it matter? Nothing shows up when I use the Filter "Include only terms used by my collections".

Any ideas from the experts who use taxonomy? I'm such a total newbie...

**Comment by sharpphyl** [comment]
Add the source to your search.  It looks like this name as been entered as a Linnean rather than a cultural name.  @Jegelewicz is this a homonym that needs some additional work?  Can we change the Name Type without disrupting other collections?

<img width="756" alt="Screen Shot 2022-02-07 at 9 04 23 AM" src="https://user-images.githubusercontent.com/15368365/152825460-80a1735c-e3d2-4472-866a-e0038e06e3a5.png">

**Comment by Jegelewicz** [comment]
This is a name used in both Linnean and Cultural circles. It carried the Nomenclature 4.0 classification:

![image](https://user-images.githubusercontent.com/5725767/152827491-e1b05caa-0eaf-49cc-8f3a-065831a21aa9.png)

@AJLinn if you select this as an identification, the above classification will show up on your catalog records.

**Comment by dustymc** [comment]
https://handbook.arctosdb.org/documentation/taxonomy.html#name-type

Name type controls how a name may be created, not how it's used.

**Comment by dustymc** [comment]
See https://arctos.database.museum/name/Bola

This bit:

<img width="242" alt="Screen Shot 2022-02-07 at 9 35 32 AM" src="https://user-images.githubusercontent.com/5720791/152841541-f73fc3b1-59d1-4144-bf8e-a53f355d8a9d.png">

controls how the **name** may be *created*. That's it.

I suppose it's in the UI because we figured it would be useful, and it probably is for those names which aren't hemihomonyms and such, but it's obviously just confusing for those where there's some complexity involved.

https://arctos.database.museum/name/Bola#NomenclatureviaArctos

<img width="981" alt="Screen Shot 2022-02-07 at 9 37 41 AM" src="https://user-images.githubusercontent.com/5720791/152841872-40b07034-6108-4634-a9f3-388ffeb91c3e.png">

Is a possible classification - not name - for how the ID will be interpreted for collections most preferring that classification.

https://arctos.database.museum/collection/uam:eh says that's first in your list, so if you pick the **name** Bola you'll get the **classification** https://arctos.database.museum/name/Bola#NomenclatureviaArctos.

(Collections who prefer Arctos earlier in their sources will get fish classification.)

The pick could almost certainly use a full rebuild, that's probably another issue - it will need to somehow deal with the "we're a fish collection, we just need a simple list" and "it's complicated, we need to see the whole shebang" and probably about 500 things in the middle and somehow run on the processors we have and.....

**Comment by Jegelewicz** [comment]
@AJLinn it will automatically show up when you select Bola because your preferred taxonomy source is Nomenclature 4.0 (via Arctos)
