### ISSUE TITLE
Replace commas separating classification terms with pipes on catalog record page

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4333]
For the object record, I think the way we present it is fine EXCEPT instead of separating terms with commas I think we need something that isn't used within some of the terms. I suggest |

> FLAT columns (or DWC)

> might be a bit more informative to people (but also might be a little overwhelming with ~a dozen insect ranks embedded), or could be complete and unambiguous as JSON (certainly my preference, but I suspect everyone else hates it).

DwC suggests that what you call "full_taxon_name" is actually two things:

[higherClassification](https://dwc.tdwg.org/terms/#dwc:higherClassification) + [scientificName](https://dwc.tdwg.org/terms/#dwc:scientificName)

Interestingly, it does not call for the addition of "ranks" to the higherClassification, which seems like it would cause issues anywhere it is used. I would be on board with JSON for "flat" taxonomy in a download of object records if it is structured in a way that makes it fairly easy to parse. Maybe we could play around with it to see what people can work with?

_Originally posted by @Jegelewicz in https://github.com/ArctosDB/arctos/issues/3498#issuecomment-802101079_

**Comment by Jegelewicz** [comment]
> Hi, Teresa.
> 
> "... JSON (certainly my preference, but I suspect everyone else hates it)."
> https://github.com/ArctosDB/arctos/issues/4333
> 
> ...hates it with good reason, but by "everyone else" do you mean people at the data admin level?
> 
> I loathe and detest JSON myself, although JSON-Lines is fairly tractable in my shell. Recently I discovered "gron" and wrote a blog post about it (draft attached - the blog will appear on 23 March). I can *process* gron-flattened JSON easily with shell tools. Very friendly developer, too.
> 
> Keep well,

Dr Robert Mesibov

**Comment by Jegelewicz** [comment]
I think this is important and needs to remain open. Nobody has even read or discussed it.

**Comment by AJLinn** [comment]
I don't quite understand what is at stake here but if it involves the cultural collection Nomenclature, I'm interested.

**Comment by dustymc** [comment]
@AJLinn no, this would just replace an arbitrary character with a different arbitrary character. https://github.com/ArctosDB/arctos/issues/3498 would provide the possibility of doing something clever with terms which don't fit in the pre-defined pigeonholes (so most everything cultural, plus lots more).

**Comment by Jegelewicz** [comment]
This definitely has implications for cultural collections.

Consider any classification that includes [Glass, Plastics & Clayworking T&E](https://arctos.database.museum/name/Glass,%20Plastics%20&%20Clayworking%20T&E)

If something was identified as "Mold Press" the classification underneath the ID would be

> Tools & Equipment for Materials, Glass, Plastics & Clayworking T&E, Mold Press

See how the comma in the classification term Glass, Plastics & Clayworking T&E gets confused in with the whole string? If we replaced with |, you would get this instead:

> Tools & Equipment for Materials | Glass, Plastics & Clayworking T&E | Mold Press

For biological collections, this isn't an issue, BUT the "|" is what is expected in [dwc:higherClassification ](https://dwc.tdwg.org/terms/#dwc:higherClassification)

higherClassification Property | explanation 
-- | --
Identifier | http://rs.tdwg.org/dwc/terms/higherClassification
Definition | A list  (concatenated and separated) of taxa names terminating at the rank  immediately superior to the taxon referenced in the taxon record.
Comments | Recommended best practice is to separate the values in a list with space vertical bar space ( \| ), with terms in order from the highest taxonomic rank to the lowest.
Examples | Plantae \| Tracheophyta \| Magnoliopsida \| Ranunculales \| Ranunculaceae \| Ranunculus, Animalia, Animalia  \| Chordata \| Vertebrata \| Mammalia \| Theria \| Eutheria \| Rodentia \|  Hystricognatha \| Hystricognathi \| Ctenomyidae \| Ctenomyini \| Ctenomys

**Comment by AJLinn** [comment]
So will this process know the difference between the hierarchical levels of commas (to convert to |) vs. commas within in the category word strings?

> See how the comma in the classification term Glass, Plastics & Clayworking T&E gets confused in with the whole string? If we replaced with |, you would get this instead:
> 
> Tools & Equipment for Materials | Glass, Plastics & Clayworking T&E | Mold Press

So that does not become: Tools & Equipment for Materials | **Glass | Plastics** & Clayworking T&E | Mold Press

(Real world case here)
<img width="834" alt="Screen Shot 2022-05-03 at 3 00 33 PM" src="https://user-images.githubusercontent.com/17605945/166586575-e23a59b4-579f-43e0-82d4-30c6b8f61d70.png">

If it can know the difference, then yes, I support this change as it does seem to make the distinctions much more visible. I want our users to know that string means this:
<img width="492" alt="Screen Shot 2022-05-03 at 3 07 32 PM" src="https://user-images.githubusercontent.com/17605945/166587284-77b9697d-409e-44ec-b4d7-a1fc5dd79e81.png">

**Comment by Jegelewicz** [comment]
> So will this process know the difference between the hierarchical levels of commas (to convert to |) vs. commas within in the category word strings?

Yes, the process right now inserts commas between taxon levels, the commas within them would not be affected and instead pipes would be inserted between the levels.

**Comment by AJLinn** [comment]
Thanks for clarifying.
Sounds like an improvement on the current display. I am in support of this change.

**Comment by dustymc** [comment]
>improvement

Perhaps, but it's going to be a minimal improvement - it's still going to be a string, anything with any complexity is going to be some sort of mess. For example, https://arctos.database.museum/guid/UAM:EH:UA67-133-0001 will be something like

"Animalia, Chordata, Mammalia, Carnivora, Caniformia, Mustelidae, Mustelinae, Neovison, Neovison vison; Animalia, Chordata, Mammalia, Artiodactyla, Ruminantia, Cervidae, Rangifer, Rangifer tarandus; Animalia, Chordata, Mammalia, Carnivora, Caniformia, Phocidae; Animalia, Chordata, Mammalia, Carnivora, Caniformia, Canidae, Canis, Canis lupus; Animalia, Chordata, Mammalia, Carnivora, Caniformia, Mustelidae, Mustelinae, Gulo, Gulo gulo"

and https://arctos.database.museum/guid/UAM:Art:UAP2006-005-001 (which pulls from two Sources) is currently returning nothing at all. Both could be something other than what they are, but I don't think anything very satisfactory could be balled up into that string - and certainly not anything that can answer questions (What's term-at-rank? What's the source?). I'd rather figure out a real solution, instead of burning a week or so of full CPU on something with inherent limitations.

**Comment by Jegelewicz** [comment]
This issue is getting nowhere and I am not sure that I completely understand the opposition. Closing for now.
