### ISSUE TITLE
Create Geography - admins only?

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#4375]
@ehalverson26 needs some new Higher Geog values ( [Higher Geography to add (2).xlsx](https://github.com/ArctosDB/arctos/files/8134644/Higher.Geography.to.add.2.xlsx) ). Neither she nor I am able to Create Geography (ERROR: permission denied for table geog_auth_rec). Can we request that the values in the csv get added (confirmed they are not yet reflected in the authority table and are in consistent format as nearby regions/provinces with source authority links)? Or, happy to be granted admin privileges so we can do it ourselves.

Also, Emily noticed some inconsistencies:

Current Higher_Geog | Should be added for consistency? | Notes
-- | -- | --
Europe, Germany, Nordrhein-Westfalen | Europe, Germany, North Rhine-Westphalia | inconsistancy in states, some in german and some in english
Europe, Germany, Rheinland-Pfalz | Europe, Germany, Rhineland-Palatinate | inconsistancy in states, some in german and some in english

- There are several Korean provinces that have "Korea" for country but could be resolved further to North or South Korea

**Comment by dustymc** [comment]
Korea is https://github.com/ArctosDB/arctos/issues/3135

Yes geography should be treated as an authority (maybe..). I think more users can probably have access, but it should be close to code table access. (Or we can decide to give up on formality in asserted geography and go with https://github.com/ArctosDB/arctos/issues/3272, I don't know!)

Some (all?) of the data in the spreadsheet doesn't match rules. Source https://en.wikipedia.org/wiki/Districts_of_Botswana and...

DO Link to the Wikipedia page which directly describes the resource.
    DO NOT link to anchors in general articles, lists, maps, images, vaguely-related entities, “parent” entities (except in cases described under [source documentation](https://handbook.arctosdb.org/documentation/higher-geography.html#source)) or anything other than the specific relevant article in Wikipedia.

for example.

Oh - nevermind, I scrolled right, the proper thing does seem to be there, whoever does this should make sure to use the correct column!

Translating probably has to be on a case-by-case basis, but yes we should be consistent. (Maybe "someone willing to fix stuff" is compelling reason to be more open with access??)

The Iceland entry follows what's in Arctos, but we should (probably?) be using https://en.wikipedia.org/wiki/Administrative_divisions_of_Iceland instead of https://en.wikipedia.org/wiki/Regions_of_Iceland (changelog says that's my fault....)

I suppose I'm up for anything, @mkoo can you chime in here?

**Comment by mkoo** [comment]
We need to have regular Geography committee meetings again-- my fault for shoving Arctos grant activities on my plate and ignoring that. Let's discuss today and get Korea, Germany and Palau cleaned up-- it makes the most sense to me to tackle country by country in the clean-up, since it usually involves more than one institution (and MVZ is often in the mix/ to be blamed!)
But then we should also have committed committee members with expanded permissions if needed. 
Somewhere in all these, we can start making recommendations regarding integrating any spatial tools to help....
GADM has been useful in the past but has its limits.....

**Comment by ebraker** [comment]
Ok. Will someone please load the requested values? @Jegelewicz @mkoo
[Higher Geography to add (updated).xlsx](https://github.com/ArctosDB/arctos/files/8136470/Higher.Geography.to.add.updated.xlsx)

Decided at AWG meeting: dedicated cleanup projects by country (this will resolve the two German localities. For now, @ehalverson26 will use the Germanic names to reduce mess in the table.

>
 <html>
<body>


Current Higher_Geog | Should be added for consistency? | Notes
-- | -- | --
Europe, Germany, Nordrhein-Westfalen | Europe, Germany, North Rhine-Westphalia | inconsistancy in states, some in german and some in english
Europe, Germany, Rheinland-Pfalz | Europe, Germany, Rhineland-Palatinate | inconsistancy in states, some in german and some in english


</body>
</html>

**Comment by Jegelewicz** [comment]
I'm on it - I'll let you know when they are in.

**Comment by Jegelewicz** [comment]
OK all in except:

Asia, Uzbekistan, Sirdaryo Region is in as Asia, Uzbekistan, Sirdaryo

this is for consistency with other Uzbekistan regions which do not include "Region"

and


Europe, Iceland, Southern Peninsula

This is a smaller administrative district than "state" it appears to me to be in the "state" of [South Constituency](https://en.wikipedia.org/wiki/South_(Icelandic_constituency) so you would instead have

Europe, Iceland, South Constituency, Southern Peninsula

of course this highlights the fact that the rest of Iceland is a bit of a mess using Regions instead of the Constituencies.....

**Comment by ebraker** [comment]
@ehalverson26 all values have been added (see above for some slight tweaks). Thanks @Jegelewicz !

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/4493
