### ISSUE TITLE
Subspecific names with questionable spelling of specific epithet

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4410]
See https://github.com/ArctosDB/data-migration/issues/663#issuecomment-1061336683

[Rhinopoma hardwickei](https://arctos.database.museum/name/Rhinopoma%20hardwickei) is a synonym of [Rhinopoma hardwickii](https://arctos.database.museum/name/Rhinopoma%20hardwickii) according to the [GBIF taxonomic backbone](https://www.gbif.org/species/5218750).

I have created the appropriate relationship between the names and provided the preferred name in the classification metadata for [Rhinopoma hardwickei](https://arctos.database.museum/name/Rhinopoma%20hardwickei)

However, there are three subspecies using this species name that I can find no appropriate names for:

[Rhinopoma hardwickei arabium](https://arctos.database.museum/name/Rhinopoma%20hardwickei%20arabium)
[Rhinopoma hardwickei cystops](https://arctos.database.museum/name/Rhinopoma%20hardwickei%20cystops)
[Rhinopoma hardwickei hardwickei](https://arctos.database.museum/name/Rhinopoma%20hardwickei%20hardwickei)

The above are in use by MVZ:Mamm. @cjconroy how should these be handled?

Also, [Rhinopoma hardwickei](https://arctos.database.museum/name/Rhinopoma%20hardwickei) is in use by WNMU:Mamm @jldunnum and MVZ:Mamm @cjconroy this is OK as people should find your records because of the synonym relationship, but depending on the answer above, you may want to re-identify them?

**Comment by cjconroy** [comment]
I tentatively agree, the proper spelling should be -ii, not -ei. The last Mammal Species of the World sides with -ii, as does the 1986 Mammalian Species account and the relatively recent Mammals of Africa. Apparently the original spelling is -ii (from 1831), but Oldfield Thomas in 1903 suggested using -ei since the name is after Major General Hardwicke. I haven't found an argument to keep using -ei, but I would still like to read Thomas' argument since it was used for many years. The older version of Mammal Species of the World, 1992 uses -ei with no explanation.
The Mammals of Africa notes that a 2007 paper elevates R. h. cystops to species level. I need to review that paper. 
So, if I were to upgrade, would I make 3 new names in Arctos and then update my 3 specimens with those new names? Is the reason Revised Taxonomy?

**Comment by Jegelewicz** [comment]
> So, if I were to upgrade, would I make 3 new names in Arctos and then update my 3 specimens with those new names? 

Yep. When the new names are created, also please add the synonym relationships.If it were me, I would probably just add a new identification and leave the one under the "ei" spelling as an historical identification.

> Is the reason Revised Taxonomy?

That's what I would use!

**Comment by Jegelewicz** [comment]
@cjconroy any progress here?

**Comment by Jegelewicz** [comment]
I have created the names with the appropriate spellings (and synonomized them with the currently accepted names). I'm not going to request quarantine. Closing
