### ISSUE TITLE
Quarantine Taxon Name - Incorrect spelling of Crassula marnierana

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#4414]
Name suggested for quarantine: [Crassula marnierana](https://arctos.database.museum/name/Crassula%20marnierana)

Reason for quarantine: Appears to be misspelled (missing an "i"); correct spelling is Crassula marnieriana.
Sources: https://powo.science.kew.org/taxon/273280-1

This taxonomy is a synonym for Crassula rupestris subsp. marnieriana
https://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:878790-1

Which also appears to be misspelled in Arctos (missing an "i"): [Crassula rupestris subsp. marnierana](https://arctos.database.museum/name/Crassula%20rupestris%20subsp.%20marnierana)

Update spelling from "marnierana" to "marnieriana" for both classifications.

Collections currently using this name in identifications: none for either; I noticed the spelling error while searching for another name.

**Comment by dustymc** [comment]
@wellerjes if it's not used you can just create a relationship and quarantine it. Un-doing that is worlds easier than cleaning up after someone's inadvertently used something other than what they really intended, so this is my recommendation.

Filing the issue seems moderately useful, but maybe that's asking too much; I'd not want to recommend anything that would result in users just ignoring problems.

@Jegelewicz if that sounds reasonable suggest the template gets updated accordingly.

**Comment by Jegelewicz** [comment]
And create the correct ones...

**Comment by dustymc** [comment]
>delete it.

Please don't, it's useful - users coming from https://en.wikipedia.org/wiki/Crassula_marnieriana would need it to get anywhere, for example.

**Comment by Jegelewicz** [comment]
Why would they need [Crassula marnierana](https://arctos.database.museum/name/Crassula%20marnierana) to get to Crassula marnieriana?

**Comment by dustymc** [comment]
That's what relationships do?!

**Comment by Jegelewicz** [comment]
NOBODY should be searching for [Crassula marnierana](https://arctos.database.museum/name/Crassula%20marnierana). It is not a thing.

**Comment by dustymc** [comment]
>not a thing.

It is according to 5,350 things that google knows about, including wikipedia. Getting a user coming from one of those places where they want to be, or preventing an operator coming from one of those places from starting this cycle again, is is well worth the minuscule cost of maintaining a relationship.

**Comment by wellerjes** [comment]
Those results could be a case of a misspelling being perpetuated from an incorrect source, such as this. Also, there isn't a relationship in Arctos that alerts a user of an issue.

The incorrect version is not associated with the correct nomenclature in Arctos (such as "synonym of"), which would alert anyone using the incorrect spelling to the error, which would continue to perpetuate the issue. If I look for a taxonomic name on a trusted source and don't find it, then I know something is up. When I searched the International Plant Name Index to find a source to back up my claim for quarantine, "Crassula marnierana" did not yield any valid results.

**Comment by dustymc** [comment]
>alerts a user of an issue.

The name type does that see eg https://arctos.database.museum/name/Buteo%20jamaicensis%20abeiticola


<img width="391" alt="Screen Shot 2022-03-10 at 1 00 32 PM" src="https://user-images.githubusercontent.com/5720791/157753819-aa7b24bb-ec2a-4c14-943b-20414cff3785.png">

>isn't a relationship

Quarantined names without relationships trigger notifications; they'll get relationships. (But see https://arctos.database.museum/info/ctDocumentation.cfm?table=cttaxon_relation, an inappropriate relationship gets used way too often, I don't know what to do about that.

>continue to perpetuate

Quarantined names may be used for relationships, nothing more. Someone could ignore the warnings and copy/paste something, but that's about the only way a quarantined name can find its way out of Arctos (and as above, there are strict rules within Arctos).

>searched the International Plant Name Index 

EVERY source has something that looks like an issue to someone!

If the name is deleted, then

* users coming from eg wikipedia will hit a dead end
* the potential for someone to re-create the name and start this cycle over exists
* there's no way we can propagate anything, unless ^^ that happens.

If the name is quarantined instead of being deleted, then

* users coming from eg wikipedia will get a link to the good name
* the potential for someone to re-create the name and start this cycle over does not exist
* there's some (very minimal, I think) chance that someone will ignore all the warnings, copy-paste the bad name somewhere, and confuse themselves

I think the latter scenario is better in every way.

**Comment by Jegelewicz** [comment]
@dustymc I will concede to the quarantine vs.delete argument, but I think we need a better relationship for quarantined names and their correct spellings because "potential alternate spelling" isn't strong enough and "synonym" is only correct some of the time.

**Comment by dustymc** [comment]
>better relationship

Yes please! These get significant consideration, even if not by taxonomists, they deserve a better term.

"potential alternate spelling" is just wrong unless you're scripting something.

The definition of "synonym" goes against what we decided in some old very long discussion a while back - the intent was "these have something to do with each other, I ain't no taxonomist so I can't do better." Some term - I don't care how we spell it - should be reserved for that usage. (We'll need to update about everything if we do change the term.) I'd have no objections whatsoever to someone who is a taxonomist introducing Code-compliant terms, but we mere mortals will seldom/never have enough information to use them. (And they should probably be things like "whateverterm (ICBN)" because the terms change meanings across Codes.)

**Comment by Jegelewicz** [comment]
Name has been quarantined.
