### ISSUE TITLE
We need better terms for the relationships between taxon names

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4417]
>better relationship

Yes please! These get significant consideration, even if not by taxonomists, they deserve a better term.

"potential alternate spelling" is just wrong unless you're scripting something.

The definition of "synonym" goes against what we decided in some old very long discussion a while back - the intent was "these have something to do with each other, I ain't no taxonomist so I can't do better." Some term - I don't care how we spell it - should be reserved for that usage. (We'll need to update about everything if we do change the term.) I'd have no objections whatsoever to someone who is a taxonomist introducing Code-compliant terms, but we mere mortals will seldom/never have enough information to use them. (And they should probably be things like "whateverterm (ICBN)" because the terms change meanings across Codes.)

_Originally posted by @dustymc in https://github.com/ArctosDB/arctos/issues/4414#issuecomment-1064528787_

**Comment by sharpphyl** [comment]
Could we at least add "misspelling" as a choice.  "potential alternate spelling" implies that it's a creative, but accurate, term.  

I'm no taxonomist, but what's wrong with "synonym"?  [WoRMS statuses](https://www.marinespecies.org/aphia.php?p=manual#topic16) include that term as the most common relationship.  The reasons (such as Junior homonym) are all listed as "taxon status."

**Comment by dustymc** [comment]
>misspelling

No objections if it can be disambiguated from other terms.  (I was going to suggest something like "orthographical variant" because I've seen it used, but turns out that's a Code term so let's reserve it for the folks who live and die by the ICBN.)

>"potential alternate spelling" implies...

Nothing, there's documentation! ["Possible spelling variation detected by automation."](https://arctos.database.museum/info/ctDocumentation.cfm?table=cttaxon_relation#potential_alternate_spelling)

>what's wrong with "synonym"?

Nothing, but the definition has been changed (something about Codes) to disagree with the origins ("means exactly or nearly the same ...").

**Comment by sharpphyl** [comment]
Ok.  I'll leave this issue to the taxonomists...

**Comment by Jegelewicz** [comment]
Let's change "potential alternate spelling" to misspelling and add taxon status to anything with relationship so that people can make better choices.

Get a list of everything using "potential alternate spelling" and evaluate. Anything with this should have one term quarantined.

**Comment by Jegelewicz** [comment]
@dustymc can we get a list of all names with the "potential alternate spelling" relationship. Would it be possible to also include any taxon status associated with the name? So

taxon name | related name | taxonomy_source | taxon status
 -- | -- | -- | -- 
[Sceloporus olivaceus](https://arctos.database.museum/name/Sceloporus%20olivaceus | Sceloporus olivaceous | Arctos | valid 
[Sceloporus olivaceus](https://arctos.database.museum/name/Sceloporus%20olivaceus | Sceloporus olivaceous | Current Reptile Classification | valid
Sceloporus olivaceous | [Sceloporus olivaceus](https://arctos.database.museum/name/Sceloporus%20olivaceus) | Arctos |

**Comment by Jegelewicz** [comment]
Doing the little exercise above made me think that quarantined names should not have any local classifications?

**Comment by Jegelewicz** [comment]
We are concerned that we are still potentially creating backward relationships or relationships that can't easily be interpreted. Which name is the misspelling? I don't know that we have an answer right now, but the taxonomy committee did agree that "potential alternate spelling" is misleading. There should only be one correct spelling for a taxonomic name, so "misspelling" makes more sense. However, it becomes ambiguous when applied to the names - what is a misspelling of what?

**Comment by dustymc** [comment]
>change "potential alternate spelling" to misspelling

No, two reasons.

1. Tracking down my scripts wouldn't be too much fun, but mostly
2. There are two very different things in play here.
    * some [script](https://arctos.database.museum/info/ctDocumentation.cfm?table=cttaxon_relation#potential_alternate_spelling) makes some waffly assertion based on potential patterns in strings
    * some person makes some hopefully-not-so-waffly assertion based on - we hope - something beyond potential patterns in strings

>Get a list of everything using "potential alternate spelling" and evaluate. 

That's basically a view of the above. "potential alternate spelling"=="hey people, maybe look at this" ---> [ yup, those are the same, here's a real relationship | nope, just similar strings, nothing to see here ]. (But I still like the automated assertion on the latter - it lets people know that there's something of a similar form which they might want to consider.)

>Anything with this should have one term quarantined.

Would be nice, but not supported by reality. I can think of one name which has literally decades of discussion involving how many ``i``s it needs (the author used various forms), there's legitimate disagreement over how we should spell red-backed vole and woodfrog, etc., etc., etc.

>quarantined names should not have any local classifications?

why not? I don't think discoverability is ever a bad thing, and I'm particularly twitchy here because many of the fundamental problems in taxonomy involve some Committee trying to pretend things never happened.

>ambiguous

Relationships have a direction, my scripts go both ways so it doesn't matter, feel free to propose more linear terms.

>list

```
select a.scientific_name,taxon_relationship,b.scientific_name from
taxon_relations
inner join taxon_name a on taxon_relations.taxon_name_id=a.taxon_name_id
inner join taxon_name b on taxon_relations.related_taxon_name_id=b.taxon_name_id
where taxon_relationship='potential alternate spelling'

(87185 rows)

```

>taxon status

Nontrival anyway - and that's not controlled so the results couldn't be very meaningful.

**Comment by Jegelewicz** [comment]
OK, from that, I think we need to

1. propose a new relationship "misspelling of" to be used when I go and find an actual misspelling so that it can be disambiguated from "a script found something similar".
2. Maybe add taxon status = quarantine to local classification for quarantined names or at least remove anything that indicates a quarantined name is "valid"?
3. Instead of "potential alternate spelling" how do you feel about "suspect similar spelling". I think that is more of a warning than what we have now?

@ArctosDB/taxonomy

**Comment by Jegelewicz** [comment]
I think we are done here - closing.
