### ISSUE TITLE
Delete taxon names added in error

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4447]
@dustymc the names in this file were added in error, can you delete them for me?
[delete_taxonomy.csv](https://github.com/ArctosDB/arctos/files/8274496/delete_taxonomy.csv)

**Comment by Jegelewicz** [comment]
oh and I found one more

Mesosiderite-A3/4 meteorite

**Comment by Jegelewicz** [comment]
The "/" does something weird they show up in search results 

![image](https://user-images.githubusercontent.com/5725767/158694728-e28832a0-c9be-44c5-ae6b-3f580330a5c8.png)

but then I get this

![image](https://user-images.githubusercontent.com/5725767/158694778-25b109a1-8017-4a53-a3fb-85fceef2d98b.png)

In any case, they should just be deleted. Sorry for the bother!

**Comment by Jegelewicz** [comment]
UGH hold on, I didn't make the list right....

**Comment by Jegelewicz** [comment]
OK - that should be the list...

**Comment by dustymc** [comment]
UGH indeed!

Can we work towards just banning the slashy? Even the stuff that doesn't look like identifications rather than taxonomy make my brain hurt - eg is ``H4/6 chondrite meteorite`` another way to say [H4-6 chondrite meteorite](https://www.mindat.org/min-49646.html) or something else or ???? (I'm guessing its a variation and that's why I just deleted it....)

On the cultural side, 1/3 could be given as ⅓, and eg ``Decapper/Recapper`` seems less confusing as something like 'cap remover and reinstaller" (which might conflict with some external source, but I'm not entirely convinced their taxonomy is actually taxonomy either).

Done....

**Comment by Jegelewicz** [comment]
> On the cultural side, 1/3 could be given as ⅓, and eg Decapper/Recapper seems less confusing as something like 'cap remover and reinstaller" (which might conflict with some external source, but I'm not entirely convinced their taxonomy is actually taxonomy either).

Cultural people need to make that call!

Thanks!
