### ISSUE TITLE
agent name splitter

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ArctosDB/arctos#446]
```
/DataServices/agentNameSplitter.cfm

needs developed to accept upload, return formatted name, maybe integrated
with agent bulkloader
```

Original issue reported on code.google.com by `dust...@gmail.com` on 2 Jun 2010 at 7:34

**Comment by campmlc** [comment]
Name: andy 
Email: ajohnson@unm.edu 
Message: Still trying to get agent bulkloader to work. can't get the name splitter to accept the file. This has been ongoing since April when I last tried. Please tell me to whom I should send the file so that this can be resolved. It is holding up a bulkload of ca. 800 specimen records. An error occurred while processing this page! Error Executing Database Query. [Macromedia][Oracle JDBC Driver][Oracle]ORA-00904: "AGENT_TYPE": invalid identifier

**Comment by campmlc** [comment]
[agent bulkloader July2018.txt](https://github.com/ArctosDB/arctos/files/2190044/agent.bulkloader.July2018.txt)

**Comment by dustymc** [comment]
The file has incorrect columns and is not CSV.

<img width="664" alt="screen shot 2018-07-16 at 5 41 35 pm" src="https://user-images.githubusercontent.com/5720791/42790365-82b78260-891f-11e8-9aae-880fc5493308.png">

<img width="372" alt="screen shot 2018-07-16 at 5 42 06 pm" src="https://user-images.githubusercontent.com/5720791/42790383-958162ee-891f-11e8-9a7f-6e76d64c632f.png">
