### ISSUE TITLE
New Github Repo for Workflows?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4462]
Today in Object Tracking we talked about creating some automated workflows. Mariel has a series of tools she needs to use to get parts created and labels on their containers edited/created (https://github.com/ArctosDB/arctos/issues/4436#issue-1169120085). It is easy to get one step done, then be distracted and the second never happens. It would be fabulous if we could create workflows in Arctos that allowed her to keep track of the steps she needs to complete, then be notified of steps she has left undone. Before we try to build this automation into Arctos proper, we think it would be good to set up some workflows in Github to get an idea of what might be involved and we also thought a new repo to store these workflows in would be a good way to keep them in a single location while we play around.

Another example of this would be Derek's request to get barcodes added as identifiers. - https://github.com/ArctosDB/arctos/issues/2685#issue-618428155

@mkoo thoughts?

**Comment by Jegelewicz** [comment]
I have the first example of this in the new colelction repo -  https://github.com/ArctosDB/new-collections/issues/new?assignees=&labels=&template=workflow--invite-an-new-arctos-operator.md&title=New+Operator+Invitiation

**Comment by mkoo** [comment]
catching up on today's good ideas and issues... to make sure I understand, we need to make a github repo with typical tasks that require multiple steps so people can grab a workflow template to keep track of their steps. So it would be a repo for self-assigned tasks and we provide the issue templates for these workflows.-- do I have this right? I think I love it. I've been writing a manual and new how-to docs for dealing with objects since it's been a learning curve for me and definitely not obvious.

We can discuss tomorrw in the AWG about the repo details but that sounds useful and workable

**Comment by campmlc** [comment]
Yes! This would be in addition to the handbook, providing a clear
progression of steps with links to the different related tools, which
currently may be located in several different dropdowns on the main
interface.

**Comment by mkoo** [comment]
From AWG:

- make public
- available to Arctos Users team
- Name? Arctos-Tasks (arent all our repos tasks?), Arctos StandardOperationalProcedures (ugh?) other?

**Comment by Jegelewicz** [comment]
Arctos Workflows

**Comment by ewommack** [comment]
Newsletter article for April 2022 (https://github.com/ArctosDB/newsletter/issues/145)

**Comment by mkoo** [comment]
Just completed with the first template added from this issue:
https://github.com/ArctosDB/Arctos-Workflows
add more!
