### ISSUE TITLE
Feature Request - common name in specimen results

### ISSUE THREAD

**Issue by byuherpetology** [ArctosDB/arctos#4467]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
Educators are used to finding objects by common name or description of the item. There is no need for locality data for many teaching or education collections.

**Describe what you're trying to accomplish** 
I would like to help educators search and find collection objects more easily, and have access to the data they need.

**Describe the solution you'd like**
Add the option of a common name column in specimen results.  Have the option of removing locality columns in specimen results.

**Describe alternatives you've considered**
Adding common name to the identification box is an option but as I don't know that this is useful to many collections, that may be unnecessary.

**Priority**
normal - would be nice to have but isn't critical

**Comment by campmlc** [comment]
I support this. On a similar subject, if we are making changes to the
Add/Remove Data fFelds options in search results, is to rename
"othercatalognumbers" with "OtherIDs", since most of the
"othercatalognumbers" displayed are actual other identifiers and not
catnums.

**Comment by dustymc** [comment]
Closely related to https://github.com/ArctosDB/arctos/issues/3498 - this would require some sort of cache, perhaps we can solve multiple issues at once.

Note that many taxa have lots of common names - https://arctos.database.museum/name/Thunnus%20albacares is still leading the pack with 216 (and they're all ASCII-ish so there are probably a few hundred more out there waiting to be rounded up).

And from there, sustainability would need addressed - this would require at least several GB of extra data, which affects things like sharing data and backups.

**Comment by Jegelewicz** [comment]
Yes, my first thought was, "what happens when there are a bunch of common names?"

@byuherpetology I'd like to suggest something that is a little work, but might get at what you need for this particular collection.

Identify your records using A {string}

So for this record - https://arctos.database.museum/guid/BYU:Edu:A-102

You would change (or add) the identification to Bivalvia {Bivalve} which would show up in search results as Bivalve but could be found both through a search of Bivalvia or Bivalve. This would customize the common name you are using for your collection to a single term, because right now the common names for bivalves include

> Almejas, Mejillones; Clams And Mussels; Huîtres, Moules, Peignes; bivalve; bivalves

AND it would provide the name you want to see in search results for just this collection.

Fairly easy to accomplish with the identification bulkload tool or with manage identifications from search results. Let me know if you have questions about either of those methods. Try it with this one to see how it functions. If you want to have these labeled as "Clam", then use Bivalvia {Clam}. Whatever you put inside the brackets is what you will see in search results.

**Comment by Jegelewicz** [comment]
But @dustymc this also makes me wonder why "common name" isn't just something else in classification metadata?

**Comment by byuherpetology** [comment]
> You would change (or add) the identification to Bivalvia {Bivalve} which would show up in search results as Bivalve but could be found both through a search of Bivalvia or Bivalve. This would customize the common name you are using for your collection to a single term, because right now the common names for bivalves include
> 
> > Almejas, Mejillones; Clams And Mussels; Huîtres, Moules, Peignes; bivalve; bivalves
> 
> AND it would provide the name you want to see in search results for just this collection.

So I would create a new taxon "Bivalvia {Bivalve}" and then change the identification to that?  Wont that make a giant mess in the Arctos taxonomy? Or should I create a new classification that is just for teaching collections?

Right now I have just put the common name in the identification remarks.  Another option would be making the identification remarks visible in the search results.

**Comment by Jegelewicz** [comment]
> So I would create a new taxon "Bivalvia {Bivalve}" 

Nope - you use the identification formula [A {string}](https://arctos.database.museum/info/ctDocumentation.cfm?table=cttaxa_formula#a__string_). This uses the taxon name Bivalvia and associates it with a string of your choice {Bivalve} which has no affect on taxonomy at all.

We can meet up and walk through it if you like!

**Comment by dustymc** [comment]
>why "common name" isn't just something else in classification metadata?

You can add whatever you want, but the model isn't designed for that because the situation isn't really reflective of that. (I'm not sure what we have is entirely correct - someone who says "iron" might not be thinking about bugs, but they're probably not thinking in classification-level detail either.)

>Bivalvia {Bivalve}

https://handbook.arctosdb.org/documentation/bulkloader.html#taxonomy might be useful in understanding ID formulae.

>identification remarks visible 

<img width="184" alt="Screen Shot 2022-03-23 at 8 38 07 AM" src="https://user-images.githubusercontent.com/5720791/159737730-dc90c731-82b8-4128-9722-a6786eb28692.png">

**Comment by byuherpetology** [comment]
Got it! This is definitely a workable solution.  Would it be possible to see both the {string} and the Scientific name on the search results?

**Comment by byuherpetology** [comment]
And is it possible to get rid of unneeded columns like locality and collector number?

**Comment by byuherpetology** [comment]
> > identification remarks visible
> 
> <img alt="Screen Shot 2022-03-23 at 8 38 07 AM" width="184" src="https://user-images.githubusercontent.com/5720791/159737730-dc90c731-82b8-4128-9722-a6786eb28692.png">

Thanks, I missed that. This is an easy solution!

**Comment by Jegelewicz** [comment]
> Would it be possible to see both the {string} and the Scientific name on the search results?

@dustymc possible?

**Comment by dustymc** [comment]
>both the {string} and the Scientific name

Try FormattedID - it's not exactly what I think you're looking for, but might be close enough.

>locality and collector number?

If you're seeing collector number it's because you've turned it on. Locality is another discussion. (The current UI requires dec_lat,dec_long,guid but you can right-click headers to hide them, the rest of the "required" are not technical requirements.)

**Comment by byuherpetology** [comment]
> > both the {string} and the Scientific name
> 
> Try FormattedID - it's not exactly what I think you're looking for, but might be close enough.
> 
> > locality and collector number?
> 
> If you're seeing collector number it's because you've turned it on. Locality is another discussion. (The current UI requires dec_lat,dec_long,guid but you can right-click headers to hide them, the rest of the "required" are not technical requirements.)

Perfect, thank you!
