### ISSUE TITLE
Code Table Request - new other identifier type = creator number

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4488]
**Goal**
I have an object with a "creator number". I'd like to record this number in the catalog record.

**Context**
Artists will often place numbers or identifiers on their objects (1/200, 10 etc.)

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type

**Proposed Value**
creator number

**Proposed Definition**
An alphanumeric identifier applied to an object by its creator

**Collection type**
Art, EH

**Other ID BaseURL**
[  For OtherIDs, provide the following *or* explain why the unresolvable ID type is necessary:
1. "Base URL" with which to prepend entered values, and
2. A functional example URL, which should consist of the base URL provided in (1) plus a relevant value.  ]

**Priority**
[  Please choose a priority-label to the right.  ]

@AJLinn @marecaguthrie thoughts on this? I have a butter churn with the maker's name and "3". I could just use "collector number" but that is misleading, since I have a creator and it is their number. I could use "other identifier" but I know this number is associated with the creator and that would be lost.

**Comment by AJLinn** [comment]
Well, I guess it comes down to how you are thinking about the creator... are they also listed in the collector role? 
What is the purpose of the number for the creator? Is it the 3rd butter churn they made?

Re: the print run, I'll let @marecaguthrie or @krgomez weigh in... seems like that might be something different? Is there a different field in CDWA to indicate print run? I think maybe that's "Edition" ("record the edition of prints or books"?

I see CDWA also has "creation number" which we could use in the manufactured items realm, with serial numbers or model numbers, so maybe that's what this code table request should be rather than "creator number" ?
https://getty.edu/research/publications/electronic_publications/cdwa/definitions.pdf (see page 15)

**Comment by Jegelewicz** [comment]
> What is the purpose of the number for the creator? Is it the 3rd butter churn they made?

Possibly? I can't really be sure why it is there or what it means, but it is associated with the name of the person who made the churn.

> I see CDWA also has "creation number" which we could use in the manufactured items realm, with serial numbers or model numbers, so maybe that's what this code table request should be rather than "creator number" ?

That would probably work  - however, if we could resolve #4101 maybe I could just use "other identifier" issued by the creator.

**Comment by Jegelewicz** [comment]
Code table committee says OK. Carla says add it near the top for visibility.

**Comment by Jegelewicz** [comment]
Added and generic "lowercase" terms moved to the top.
