### ISSUE TITLE
Add a free text comment section for Notifications 

### ISSUE THREAD

**Issue by ewommack** [ArctosDB/arctos#4500]
**Is your feature request related to a problem? Please describe.**
It would be great to have a free text comment section in the Arctos Notifications notifications page.

**Describe what you're trying to accomplish** 
When I work on clearing my notifications, I'd love to have a comment section so I can make a note to myself and other curators that I worked on this notification on this date, and I marked them as read and reviewed on this date, etc etc. Something to help me keep track of my work flow, or explain why I marked them as read even though they still have the notification present.
![Arctos Notifications suggestion](https://user-images.githubusercontent.com/18562884/160939950-78822a75-27f9-48cb-b9c5-1ba3d0caca45.jpg)

**Comment by mkoo** [comment]
> This needs an administrative decision.
Agreed. Adding to agenda for next meeting
> 
> Notifications are growing by a few KB per day, that's almost certainly not linear, at least a few of us are never going to delete anything. Maintaining that would take considerable resources so my vague intention has been to start a rolling delete whenever this becomes problematic: everything older than {some number of days} would get auto-deleted.
> 
> That approach isn't compatible with what's being requested, although some hybrid might be - "older than x days and has no user notes" might work.

I like this approach. We can discuss options and parameters.

> 
> I'll add a CSV option to next release - that's easy, someone will eventually ask for it anyway, and maybe it will influence this discussion.

It's almost like you read my mind
> 
> FYI the structure is of course normalized, there is a "core" table and a user table, it could support both "note to everyone who got this" and "note to self" functionality.

let's discuss....

**Comment by dustymc** [comment]
>fix the redundancy?

Well that's what it is, but suggest something different and I can swap it.

>BCC

Next release.

>more inclined to read the email 

https://github.com/ArctosDB/arctos/issues/4427#issuecomment-1076769987 - these things are a service, only the mechanism is changing: Notifications are more persistent/stable, less likely to get lost, and hopefully less intrusive, than individual emails. Someone who's actively managing their collection might not even need the emails, they can just use the tab. Someone who isn't can block the emails or decontactify themselves. In either case the intention is to provide a service, not to force anyone to do anything they don't want to. Maybe we don't need emails at all, I'm open to anything (except getting yelled at because someone was expecting and did not get notifications...). 

Can we somehow loop the entire Community into some sort of notification-notification discussion/"email: yes|no" survey/whatever?

Or maybe we need a dedicated "notification email" address type as a sort of subscription mechanism?

**Comment by ewommack** [comment]
> Notifications are growing by a few KB per day, that's almost certainly not linear, at least a few of us are never going to delete anything. Maintaining that would take considerable resources so my vague intention has been to start a rolling delete whenever this becomes problematic: everything older than {some number of days} would get auto-deleted.

Does this mean that the notification get's deleted? Or the red square (you have a problem here fix me!) gets deleted?

I'd be ok with having a note that goes away with the notification on a set time frame. I'd just like to be able to tell that I checked out that notification and I don't have to work on it while reviewing them.

**Comment by dustymc** [comment]
>notification get's deleted?

Not yet, but they're likely to become hard to ignore at some point so I'd like to get in front of that before it can become a problem.

>red square 

If you mean the map border, it's an indication of funky data. That (and all sorts of other data problems) can spawn notifications, but nothing about the notifications themselves can do anything to any data - they're just notices that something could use attention.

>tell that I checked out that notification

You can change how notifications look by setting the status - 'read' is sorta-gray, 'important' gets a red border.

**Comment by mkoo** [comment]
Discussed today in AWG Issues meeting.
Make status shared between the CC'ed users. Many of these issues are collaborative or at least we need to know if someone is checking them out (so the rest can focus on another issue).

Generally need better documentation on what these different status and marking notifications do on the Notifications table.

**Comment by dustymc** [comment]
Going next-task - AWG consensus that this would be useful as a collaborative environment rather than the current "receive-only email."

> what these different status and marking notifications do on the Notifications table.

Change the appearance and provide a search/filter term.

Also needs clarification: Notifications are reports of the way things were at runtime. Deleting the notification doesn't fix anything - you'll get another the next time that report executes. Fixing a problem doesn't do anything to notifications, other than remove the condition which triggered the report (=stops future notifications).

**Comment by dustymc** [comment]
And to get everything linked: Once https://github.com/ArctosDB/arctos/issues/4522 is implemented, I'll use it and it alone to send the 'notification notification' emails - add an email address as that type to get notifications, remove it to stop them.

**Comment by dustymc** [comment]
New textbox in next release, [documentation](https://handbook.arctosdb.org/documentation/notifications.html) updated, I'll open another issue for the maintenance discussion.

**Comment by ewommack** [comment]
Thanks @dustymc! Mwahaha, now I just need the next Arctos Office Hours time so I can work on my notifications again.
