### ISSUE TITLE
Request- new agent addresstype for Notifications

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#4522]
Related to #4427 
After AWG Issues meeting today, we request a new agent addresstype for notifications. This will allow users to opt in or out of emailed notifications. If they opt out of emails, they will still see the notifications when they log in (so this affects only the emails)

**Comment by dustymc** [comment]
I'm still getting less than enthusiastic responses to the notification notifications, so I'm going to go ahead with this now-ish unless someone stops me.

-------

**Goal**

deliver email to only those who request it

**Context**

my inbox

**Table**

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctaddress_type

**Proposed Value**

notification email

**Proposed Definition**

Email address at which the Arctos Agent wishes to receive notifications.

------

@ewommack @lin-fred this probably needs communicated in some way - users will need to add a "notification email" (or whatever that turns into) address if they wish to receive email notifications from Arctos (or let me know and I can recycle their 'email' address).

**Comment by campmlc** [comment]
Perhaps we should recycle any existing emails for this and ask users to opt out if they don't want the emails?We have a very hard time getting users to make changes to their users settings as it is.

**Comment by Jegelewicz** [comment]
Many users cannot do this - they don't have agent edit access.

**Comment by campmlc** [comment]
Should the opt in or out of email notifications be in the login profile?

**Comment by dustymc** [comment]
>recycle any existing emails 

I'm mostly OK with that, I think, I could exclude the folks who I know don't want this. 

>users cannot do this - they don't have agent edit access

Then they probably don't much need the notification-notifications.

I don't want Arctos to be the cause of anyone missing an overdue loan or expiring permit-n-such reminder.

Notifications are persistent (ish, for now) in their own tab, I could be convinced that we don't need notification-notification emails at all.

I'm up for about anything, and I don't know how to balance those probably-sometimes-conflicting needs.

>login profile?

I don't want to mix up things like lost password functionality with this. It could be something new (toggle, additional address, whatever) linked to the profile rather than the agent, but that would mean it could only be changed by the user which seems like it would find some way to cause problems.

**Comment by dustymc** [comment]
Lacking better ideas I'm going to proceed with the type above and bring addresses for existing active operators (excepting those who've asked to be excluded) into it as @campmlc suggested.

Please let me know ASAP if you want removed from this, or just remove any address of type ``notification email`` from your agent profile ~tomorrow.

 @aandroski
 @acdoll
 @acoconis
 @adhornsby
 @AdrienneRaniszewski
 @AJLinn
 @aklompma
 @amgunderson
 @atrox10
 @Awkwardtree13
 @barke042
 @beth3ha
 @bfluker
 @brandon-s-thompson
 @bryansmclean
 @byuherpetology
 @campmlc
 @camwebb/
 @cassandrabarber37
 @catherpes
 @catherpes
 @ccicero
 @cefilipek
 @cjconroy
 @crcarter00
 @Cynthia-Carr
 @diannakrejsa
 @droberts49
 @dssikes
 @dustymc
 @ebraker
 @edyer94
 @ehalverson26
 @ehroalson
 @ejbrock
 @ErinKup
 @ewommack
 @gacatail
 @genevieve-anderegg
 @gracz-UNL
 @gradyjt
 @hippyherpdude
 @hkevans
 @jandreslopez
 @jebrad
 @Jecramb
 @Jegelewicz
 @jessicatir
 @Jesyka15
 @jldunnum
 @jmalaney
 @jrdemboski
 @jrpletch
 @jtgiermakowski
 @juliajchen
 @kat-sterner
 @kderieg322079
 @keg34
 @kmkocot
 @kokkoana27
 @krgomez
 @kyndallh
 @leet1984
 @lin-fred
 @lkvoong
 @lmtabak
 @marecaguthrie
 @Mcilvainevc1
 @megoss
 @mkoo
 @mlbowser
 @msbparasites
 @mvzhuang
 @Nicole-Ridgwell-NMMNHS
 @phrynosoma13
 @SerinaBrady
 @sharonjansa
 @sharpphyl
 @sjshirar
 @skgolden7
 @sreddyumn
 @StefanieBond
 @susitna
 @terrymcglynn
 @tlkane
 @wellerjes
 @zhengoong
 @zmsch
