### ISSUE TITLE
Feature Request - New Attribute Categories

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#4528]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
Requesting the addition of two new attributes:
1) verbatim collection name
2) processing history
We have been entering this information under collection remarks, but if there is a lot of information in remarks, it tends to get lost / jumbled together.

**Describe what you're trying to accomplish** 
1) "verbatim collection name" is more specific category than "description." We are transcribing labels from the collector labels in the herbarium collection and want to capture how the label is presented (if it's from an exchange collection, university collection, etc.) We will use it for other collections in the future.
2) "processing history" will include information about: when the catalog record was inventoried (especially useful for legacy data), who transcribed the label, etc. It shows how other individuals have contributed to the catalog record's history in ways other than identification.

**Describe the solution you'd like**
Adding these attributes to be used across collections.

**Describe alternatives you've considered**
We have been entering this data into "collection remarks"; however, attributes allows this information to be more easily searchable on the search page and visible within the catalog record.

**Additional context**
n/a

**Priority**
normal

**Comment by ewommack** [comment]
> processing history" will include information about: when the catalog record was inventoried (especially useful for legacy data), who transcribed the label, etc. It shows how other individuals have contributed to the catalog record's history in ways other than identification.

A lot of that sounds like attributes that might be available or good to touch base with Archive collections before creating. It sounds like something they might be recording already.

**Comment by wellerjes** [comment]
MVZ and CDSC are the only collections with archival collections in Arctos, correct?
@ccicero @mkoo @Jegelewicz - do you have any thoughts? Is there an archives-related group?

**Comment by AJLinn** [comment]
> "verbatim collection name" is more specific category than "description." We are transcribing labels from the collector labels in the herbarium collection and want to capture how the label is presented (if it's from an exchange collection, university collection, etc.) We will use it for other collections in the future.

EH and Art have an attribute called "inscriptions and marks" but I can't find it on the attribute code table...
<img width="635" alt="Screen Shot 2022-04-09 at 7 58 55 AM" src="https://user-images.githubusercontent.com/17605945/162581764-cd64f616-dadd-4f6d-93ad-fd4e5ce201a7.png">
I wonder if that might work for the label transcription? We use it to transcribe anything written physically on an item, like an artist's signature, a note handwritten by a collector, a price written or stuck with a price tag, etc.)

> "processing history" will include information about: when the catalog record was inventoried (especially useful for legacy data), who transcribed the label, etc. It shows how other individuals have contributed to the catalog record's history in ways other than identification.

In Getty's [CDWA](https://www.getty.edu/research/publications/electronic_publications/intrometadata/crosswalks.html) (Categories for the Description of Works of Art, which is what FA is trying to use to guide many of their decisions) number 25 is "Cataloging History" where one records the cataloger name, cataloger action, cataloging date, and remarks, which sounds like it could easily be an attribute and have a controlled vocabulary list for the cataloger action, which might include things like inventory, update, transcribe, correction, etc.

I couldn't find anything at Dublin Core, which is one metadata schema used by archives (also listed on the amazing mapping table linked to above).

**Comment by mkoo** [comment]
HI Jessica, we have only just started cataloging in the MVZ Archives and already I see some value to these. I have questions though:
1. **verbatim collection name** - how is this different than 'object title'? That is what we are using for things with a name like a folder of material or portfolio; if it's part of series then maybe your suggestion is better. But could this be the same as 'series title'? or 'verbatim series title' (compromise of both suggestions?) Let me know what you think since somehow "collection" is a little vague/redundant since this is all part of a "colleciton" already? (if you know what I mean)

2. **processing history** - I like this a lot. Originally we've been using accessions but cant continue that as the objects in an accession all have independent histories now. I also think this may have value beyond the cultural collections. We could potentially use it to flag specimens which are stored in 70% etoh but not fixed on formalin, for example.
Also, we need to make a Archives team on github-- just havent done it yet! l

**Comment by dustymc** [comment]
>attribute [code table](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_code_tables)

Free-text attributes are only in the "core" table: https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type#inscriptions_and_marks. Agree that encompasses most/all of the above.

> flag specimens which are stored in 70% etoh but not fixed on formalin, 

That should definitely be "partward" - part remarks if it must be a remark, but why not just use the structured and defined [concept](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctpart_preservation#ethanol__70_)?

**Comment by Jegelewicz** [comment]
> "verbatim collection name" is more specific category than "description." We are transcribing labels from the collector labels in the herbarium collection and want to capture how the label is presented (if it's from an exchange collection, university collection, etc.) We will use it for other collections in the future.

This seems more like an other identifier, an agent or an accession. When things come from another institution, do they not also include some kind of number? If not, (because I know people exchanged uncatalogued stuff), then it seems like using an accession to designate the "donor" would make most sense. BUT I realize that accession information is most likely NOT public and in a way, the exchange collection is really just a secondary collector (or even the preparator?). Why not just add that information in the agents section of the record? Use verbatim agent with a remark if you don't want to add a bunch of institutional agents?

**Comment by mkoo** [comment]
> > "verbatim collection name" is more specific category than "description." We are transcribing labels from the collector labels in the herbarium collection and want to capture how the label is presented (if it's from an exchange collection, university collection, etc.) We will use it for other collections in the future.
> 
> This seems more like an other identifier, an agent or an accession. When things come from another institution, do they not also include some kind of number? If not, (because I know people exchanged uncatalogued stuff), then it seems like using an accession to designate the "donor" would make most sense. BUT I realize that accession information is most likely NOT public and in a way, the exchange collection is really just a secondary collector (or even the preparator?). Why not just add that information in the agents section of the record? Use verbatim agent with a remark if you don't want to add a bunch of institutional agents?

**Sometimes...** In archives we often have internal organization with descriptive titles (not 'identifiers') and these need to be captured verbatim because it reflects the internal logic of the donor or creator. This is inherited and inherent value for the archives. It is not enough for the ```object title``` since it has those too at the specific record-level.
EG:

Accession 2022.002
--> records with volume ID of X and a series or collection title (box-level) -->catalog record 1 through 5 (folder-level), each with its own ```object title```
--> records with no volume ID and a series or collection title (box-level) -->catalog record 1 through 3  (folder-level), each with its own ```object title```
--> records with no volume ID and a series or collection title (box-level) -->catalog record 1 through 2  (folder-level), each with its own ```object title```

the only thing keeping records together is the accession and within that, through the shared collection titles. We will not arbitrarily assign another identifier. If one is looking at the physical box of cataloged records it would make a lot more sense.

>>processing history

>>Shouldn't this be an event? I hope that some of you can attend tomorrow's GBIF webinar, because I think we may find that we are under-utilizing events. An event type = "inventory" or "transcription" would allow for much more detailed information about who did the thing, when and what the results were.

Definitely not an event -- we have so much legacy stuff and makes little sense to find anything there for the archives

Hope this makes sense-- I could attend an upcoming meeting to discuss more

**Comment by AJLinn** [comment]
> > processing history
> 
> > Shouldn't this be an event? I hope that some of you can attend tomorrow's GBIF webinar, because I think we may find that we are under-utilizing events. An event type = "inventory" or "transcription" would allow for much more detailed information about who did the thing, when and what the results were.

> Definitely not an event -- we have so much legacy stuff and makes little sense to find anything there for the archives

I 100% agree with Michelle this is not an event. For cultural collections (and I'd guess archival as well) those events are all pre-deposition at the museum. Whether we go with the suggested **processing history** or the CDWA standard of **cataloging history** an attribute has all the fields needed to capture what @wellerjes requests.

**Comment by Jegelewicz** [comment]
Verbatim collection name is being requested specifically for herbarium sheets. @mvzhuang @camwebb thoughts?

**Comment by Jegelewicz** [comment]
Splitting this issue so that we are only discussing one code table request at a time.
