### ISSUE TITLE
Container Check/History Should populate to all children

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#4535]
Request: 1) When a Container Environment parameter (or certain parameters we specify) is entered in Edit Container, this information should propagate to the child containers down to the level of the parts. 
2) Chosen parameters from Container Environment check should show up in the Part Condition History of a given part, or even better, as a part attribute.
Why: When I have a freezer go down, and all 36,000 tissue parts within that freezer are simultaneously exposed to a high temperature event, I need to have that documented at the level of part condition history, or as a part attribute, or some other means that is easily visible and searchable from the Catalog Record and the Parts Table Download pages. Right now, container environment history and part condition and part history are disassociated - I am requesting a means to integrate these. Ideas welcome.

Specific Use Case: I had an ultralow freezer go down today - barcode DGR12749, and I created a container environment check to document the temperature all samples reached. I have now transferred all racks to another freezer, DGR12547, but I would like the data on the high temperature exposure to follow the parts that were affected prior to transfer.

**Comment by cjconroy** [comment]
I agree, that's a good idea. But, what kind of information are you hoping will propagate down? Just because the freezer temperature read one thing, doesn't mean every single tube also warmed up that much.

**Comment by campmlc** [comment]
True, but right now we have no way of documenting that tissues may have
experienced excessive warming when a freezer dies. Recording at the freezer
or container level makes no sense - it is the parts within the container
that count.  We don't know the temperature each tube experienced, but I
think if the overall freezer temp reaches a certain level, we can at least
document the likelihood that all tissues within it were exposed to higher
temp. Ideally, we'd have the time period or duration exposed - but that
would require integrating my freezer monitoring system, which logs every 15
minutes. That would probably require funding - but the same issue would
exist, e.g which samples potentially exceeded some temp threshhold.

This could also work for fluid preserved specimens -e.g. everything in this
jar was discovered to be dried out on xxx date. We might not know the
duration in that case, or it might be a very broad set of dates, depending
on last check.

**Comment by campmlc** [comment]
Could also work for IPM - all skins in this case were treated with xxx for
some infestation on x date.

**Comment by dustymc** [comment]
I sorta-almost-maybe-probably agree, but only because I don't think we have good procedures (and legacy data may not allow them whatever else we do) so don't maintain container history adequately. (If we did the normalization would work fine and this could be seen as a "just UI" problem - albeit one which may or may not have a realistic solution, PG can be a little twitchy with hierarchical data.)

>logs every 15 minutes

Container environment is built to deal with that, but see above. If we do want to do this, we either need a plan to deal with the normalized data, or a plan to deal with many terabytes of data and the possibility of many thousands of attributes on a part.

ANYWAY: I don't think automagic is or is imminently likely to become appropriate here, and I'm not sure how a "some parent at the time" approach might actually work, so how about some sort of 'build a part attributes loader file for contents' widget? I'm not sure how ideal that might be, but it might be both possible and manageable, and would work equally well for the dried-out jar scenario.

Do note that this could only work if the part has been properly/fully "installed" at the time the potential button is clicked, where allowing propagation would work for the tubes themselves, even if they've not yet been updated to record holding whatever material they might actually hold.

**Comment by Jegelewicz** [comment]
How about adding a [condition report](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecpart_attribute_type#condition_report) attribute to every part included in the incident?

**Comment by campmlc** [comment]
Environmental History is temperature in C, hate to go to free text? But
yes, some sort of part attribute?

**Comment by dustymc** [comment]
"build a part attributes loader file for contents" would (very tentatively) build any (one) part attribute; it'd be up to the user to decide which type might be most appropriate for any given situation, and which metadata to include.

**Comment by campmlc** [comment]
Can we get some documentation or instruction on what was done here, so we can use this tool? Where is it, how to use it? Link to this issue?

**Comment by dustymc** [comment]
edit container, click Make Part Attributes

**Comment by campmlc** [comment]
But does this make changes to part condition, or just add an attribute?
Sorry, on my phone so can't check. I need to change part condition in bulk
for a set of barcodes in a container.
