### ISSUE TITLE
Feature Request - Put in Bionomia links to Agent Profiles 

### ISSUE THREAD

**Issue by ewommack** [ArctosDB/arctos#4548]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
Try and add even more identification info to Agent pages, by adding a link to the Bionomia profiles of people to Agent info.

https://bionomia.net/

**Comment by Jegelewicz** [comment]
I think the more important thing would be to add whatever ORCiD or Wikidata Q number that Bionomia has to our agent record. Maybe some sort of background script that runs through Bionomia looking for our agent names, then adding (or suggesting) appropriate ORCiD or Wikidata Q number.

**Comment by ebraker** [comment]
> I think the more important thing would be to add whatever ORCiD or Wikidata Q number that Bionomia has to our agent record. Maybe some sort of background script that runs through Bionomia looking for our agent names, then adding (or suggesting) appropriate ORCiD or Wikidata Q number.

Agreed. And pull in DOB/DOD if possible. Would we automagic these linkages or instead have some sort of suggest on the agent page (or a reporter tool) where a human approves the ingest (and approver name/timestamp are recorded in this process)?

**Comment by ewommack** [comment]
It might help to have some suggestions for Arctos people for their Bionomia page. I just searched for myself, and found out that my profile isn't public. Should it be public, how often should I review it, etc?

**Comment by Jegelewicz** [comment]
> Should it be public, how often should I review it, etc?

Completely up to you! FWIW, if your stuff in Arctos is public, then why not? As for review - again, completely up to you. If we would pass ORCiD in recordedBy, Bionomia might be able to automatically match our stuff. See https://github.com/ArctosDB/arctos/issues/3623

**Comment by dustymc** [comment]
I don't think links would do much - there's explicitly no stability, and Arctos shouldn't be creating - much less handing off to the world!  - arbitrary strings that might need resolved, or at least that's my take....

(And I'm not sure how I can predict links - I could go to eg https://bionomia.net/roster?q=Elizabeth+Wommack but that's a search instead of a destination.)

Exceptionally useful would be passing in what we normally have when we create agents - just a name, generally - and getting back whatever Bionomia can figure out: ideally alternate names and ORCIDs and dates and such, but ANYTHING would be useful. I can't find that in the current API. I can get details if I have an ORCID, but if I have that I'm not worried abound duplicates (and everything else is to some extent icing). Hopefully I'm just missing something, but if not maybe that's an easy collaborative project of some form.

Related: https://github.com/ArctosDB/arctos/issues/4542#issuecomment-1098081015, https://github.com/ArctosDB/arctos/issues/3623, https://github.com/ArctosDB/arctos/issues/4526

**Comment by ewommack** [comment]
> Exceptionally useful would be passing in what we normally have when we create agents - just a name, generally - and getting back whatever Bionomia can figure out: ideally alternate names and ORCIDs and dates and such, but ANYTHING would be useful. I can't find that in the current API. I can get details if I have an ORCID, but if I have that I'm not worried abound duplicates (and everything else is to some extent icing). Hopefully I'm just missing something, but if not maybe that's an easy collaborative project of some form.

That would be helpful. I was just thinking of something that would help us when we're adding in new agents, or trying to find if the agent is the right person.

**Comment by Jegelewicz** [comment]
So, this would be a cool test person - https://bionomia.net/help-others/Q7083144

This is our [Olaus Johan Murie](https://arctos.database.museum/agent/2244) and I have added his Wikidata identifier to his agent profile. If you look in Bionomia, there are a whole bunch of things from Arctos that can easily be attributed to him if we just passed his Wikidata ID in recordedByID

Can we please do a test of some sort????

@dustymc @dbloom

**Comment by campmlc** [comment]
Here's another:
[Robert L. Rausch](https://arctos.database.museum/agents.cfm?agent_id=2570)
I added his wikidata entry to his Arctos profile. This is his bionomia ID: https://bionomia.net/Q47131323

**Comment by Jegelewicz** [comment]
I think this is covered in #3623 closing

**Comment by dshorthouse** [comment]
Although this is closed, I see you've all covered the bases. Just a confirmation that yes, best use the ORCID ID as the URI for your agents and also, I recommend using the concept URI for wikidata-based identifiers. These take the form, http://www.wikidata.org/entity/Q3734567 (note the http instead of the https and the entity in the path) instead of the wiki page, https://www.wikidata.org/wiki/Q3734567. Although you *could* link to the Bionomia representation of these, I highly recommend using ORCID & wikidata.

As for strings to things via search in Bionomia, there are two possible API endpoints for this seen on https://bionomia.net/developers. One is limited for use as a search widget, producing *some* information. The other is a JSON-LD based search that returns considerably more structured data. Example: https://api.bionomia.net/users/search?q=Robert+L.+Rausch

**Comment by Jegelewicz** [comment]
@dshorthouse our current issue is programmer time/processing power. We CAN do this, but we are just not able to make it happen right now. It will remain on the radar in the other issue and I hope we can get something done soon, but fires need putting out and our water is limited....
