### ISSUE TITLE
How to deal with an ambiguous (sort of) agent name F. Hamerstrom

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4549]
[Francis Hamerstrom](https://arctos.database.museum/info/agentActivity.cfm?agent_id=21275045) and her husband [Frederick Nathan Hamerstrom](https://arctos.database.museum/info/agentActivity.cfm?agent_id=21269510) worked and collected together. They are pretty well-known with a lot of richness in their agent data, yet all collections in Arctos for them are attributed to [F. Hamerstrom](https://arctos.database.museum/info/agentActivity.cfm?agent_id=10005160).

I suggest we create a group agent and use that in place of "F. Hamerstrom" so that we aren't attributing all of our stuff to an agent with so little data.

Other ideas?

**Comment by Jegelewicz** [comment]
Although to be fair - it seems like Francis was the real collector....https://en.wikipedia.org/wiki/Frances_Hamerstrom

**Comment by dustymc** [comment]
Agent_name=F. Hamerstrom, type=group, members=them seems reasonable to me.

That also seem the kind of thing some app would "correct," lacking something like https://github.com/ArctosDB/arctos/issues/4542#issuecomment-1098081015 (and assuming it would allow enough complexity to deal with things like groups).

**Comment by Jegelewicz** [comment]
Another option would be to add them both as collector to the affected records (which is possibly the actual scenario anyway?).

**Comment by dustymc** [comment]
>add them both as collector

That's the (or part of the) origin of groups: it's the same data, just less typing for more complexity.

**Comment by Jegelewicz** [comment]
> just less typing for more complexity.

I think we need to think about what happens with groups. I am not sure they do or will ever translate well outside of Arctos (do they even translate IN Arctos? If I search for everything collected by Francis Hamerstrom, would I also get stuff where she was part of a group?)

Maybe groups should be a convenience term, but if selected as a collector or identifier, what actually happens is that everyone from the group gets added? Is that crazy?

**Comment by dustymc** [comment]
>what happens with groups

I doubt it's as predictable as it should be. Issue, I suppose....

> Is that crazy?

Yes, as long as we have one-agent things (eg specimen-event determiner) that can't work (they won't all fit). We also have lots of memberless groups (which I'd probably ban if I could, but maybe they eventually get members so ??), so you'd say "you and me" and the data would end up NULL if we aren't actually listed.

"lots" turns out to be 427, and a bunch of them seem to be organizations and such. Could definitely use some work/documentation/etc.

Maybe we should drop the whole special handling thing and just have another type or relationship (and/or recycle something existing)? This looks like it creates more problem than it solves at the moment.

```
select preferred_agent_name from agent where agent_type='group' and not exists (select group_agent_id from group_member where group_agent_id=agent_id);
```

**Comment by Jegelewicz** [comment]
Changed F. Hamerstrom to a group and added both individuals as members - any change can get cleaned up with groups.
