### ISSUE TITLE
Feature Request - agent address type

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4560]
**Is your feature request related to a problem? Please describe.**

I don't know which address type (https://arctos.database.museum/info/ctDocumentation.cfm?table=ctaddress_type) to use

**Describe what you're trying to accomplish** 

Record "addresses" which are useful datapoints but not suitable for eg USPS usage. We often know "Oregon," that's immensely useful in disambiguating agents, none of the current address types seem quite right to hold it.

**Describe the solution you'd like**

??

**Describe alternatives you've considered**

??

**Additional context**

* https://github.com/ArctosDB/arctos/issues/4554
* https://github.com/ArctosDB/arctos/issues/4559

**Comment by Jegelewicz** [comment]
I don't see a problem putting Oregon in shipping or correspondence, but I guess we could also have something like "general location" - an address not suitable for USPS that provides a general location for the agent.

**Comment by AJLinn** [comment]
I have tried to do that for agents from my collection (could be part of those additional data points referenced in our discussion of single-name agents. A "general location" might be better... I think i've tended to use shipping location since that is more indicative of a physical location that correlates with a place of residence, where a correspondence address might include a PO box, etc.

**Comment by Jegelewicz** [comment]
@ArctosDB/arctos-code-table-administrators
