### ISSUE TITLE
Entity Component Mapping

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4641]
>This mapping occurs when the entity has no event. 

This is true only when the entity is a component of itself, which should probably never be the case (but whatever, I can't and won't try to stop such things, maybe there are good reasons to build self-referencing Entities).

>should be no map if no coordinates

Maybe, but I've come around to the idea that a (0,0) point is more informative than a big empty map. If we're going to change that then maybe we need to entirely rethink the prominent map (which I like!).

_Originally posted by @dustymc in https://github.com/ArctosDB/arctos/issues/3765#issuecomment-1109103309_

**Comment by Jegelewicz** [comment]
>     should be no map if no coordinates
> 
> Maybe, but I've come around to the idea that a (0,0) point is more informative than a big empty map. If we're going to change that then maybe we need to entirely rethink the prominent map (which I like!).

We discussed this today in Entity Meeting. Asserting 0,0 coordinates in maps for things without a georeference seems misleading. 0,0 is an actual point on the planet and there could actually be things with that georeference - let's not make up information when none is available.

**Comment by ccicero** [comment]
Revisiting this because @ewommack is looking at entities for some herp tracking data. She looked at [Arctos:Entity:10](https://arctos.database.museum/guid/Arctos:Entity:10) as an example. The coordinates for one of the two components are encumbered (to protect Golden Eagle nest location). When she is not logged in, she sees this map:

<img width="2048" alt="Screen Shot 2022-08-24 at 11 56 25 AM" src="https://user-images.githubusercontent.com/967275/186729663-a6273777-a4c5-40e4-9418-af1bc0464c9e.png">

But here is the correct map when logged in:

![image](https://user-images.githubusercontent.com/967275/186729770-4ad20620-d120-4b45-81db-14ce3fdb206b.png)

Mapping localities without coordinates or with encumbered coordinates to 0,0 is confusing and misleading. 

This thread is talking about what the map looks like, but first we need to fix how those data are being mapped. We need to fix it so that they don't map if there's no coordinates - not map to 0,0 which is a real place on the globe.

**Comment by dustymc** [comment]
> coordinates for one of the two components are encumbered 

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlocality_attribute_type#locality_access + a public generalized georeference would make this much more accessible (and avoid the mapping thing).

**Comment by ccicero** [comment]
@dustymc What is a 'public generalized georeference' - that doesn't make sense. No (public) coords, no georeference, no mapping. ???

**Comment by dustymc** [comment]
https://arctos.database.museum/place.cfm?action=detail&locality_id=11030595

**Comment by ccicero** [comment]
I'm still unclear. What would the generalized georeference be for the blood sample with encumbered coords in Arctos:Entity:10?

**Comment by dustymc** [comment]
>What would the generalized georeference be

Whatever you're comfortable with. County is generally what the paleo folks generalize to, but ANYTHING is much more useful than nothing, in my view.

(And it's just better way to encumber place data - any human and most machines won't have trouble getting coordinates from your descriptive data, this approach lets you keep that - or whatever you want - private and expose "bay area" or "this county" or whatever is appropriate for the situation.)

**Comment by ccicero** [comment]
County seems reasonable (certainly better than 0,0!), but it seems like it would be useful somehow to distinguish 'real' coordinates from Arctos-created generalized coordinates.

**Comment by campmlc** [comment]
Agree we absolutely need to get rid of the 0,0 mapping for no coordinates.

**Comment by ewommack** [comment]
@Nicole-Ridgwell-NMMNHS - how do you handle having a public and an encumbered locality for your paleo specimens?

**Comment by Jegelewicz** [comment]
@ewommack  - https://handbook.arctosdb.org/how_to/How-to-Encumber-Locality.html#access---private-example

**Comment by dustymc** [comment]
@ccicero I started from https://arctos.database.museum/guid/MVZ:Bird:193206, cloned the event+locality, edited the original 
<img width="254" alt="Screen Shot 2022-08-25 at 4 57 11 PM" src="https://user-images.githubusercontent.com/5720791/186789035-3db1adc5-7390-40c0-9e4e-7434d85f7727.png">

edited the event and locality I just made, starting with...

<img width="399" alt="Screen Shot 2022-08-25 at 4 55 57 PM" src="https://user-images.githubusercontent.com/5720791/186789060-e3b35ba4-7bb1-4c28-87e8-5662c0b8229b.png">

removed your coordinate encumbrance, and now the record has the precise info (along with the generalized) if you're an Operator, and if you're not....


<img width="748" alt="Screen Shot 2022-08-25 at 5 08 19 PM" src="https://user-images.githubusercontent.com/5720791/186790053-ab53eae1-c49f-4d6b-91bb-7f2e711ce1b6.png">

general but still useful for lots of things spatial data.

The "real" are clearly distinguished.

Arctos doesn't generate anything (except by demand), this approach allows you to expose exactly whatever you want exposed, however you want to expose it.

Let me know if you want me to un-do that, but I think this is just a better approach than encumbrances for lots of reasons.

**Comment by ccicero** [comment]
That seems ok to me, but I would make a few edits:

'collection assigned by' should not be Doug since that correct. I would change that to the person who withheld the locality.

change specific locality to "specific locality withheld' - putting 'no specific locality recorded' also is not correct

verbatim locality - maybe something like 'contact collection staff for details' - ?

Thoughts? Would be good to have a consistent approach to this sort of thing.

![image](https://user-images.githubusercontent.com/967275/186791059-5ba3321e-37da-43ae-a167-237f38dfb038.png)

**Comment by dustymc** [comment]
>"specific locality withheld'

I'm not crazy about purposefully violating our [one free-text rule](https://handbook.arctosdb.org/documentation/locality.html#specific-locality) but I don't care if scripts barf on that either so - IDK, maybe we need another "we know but we're not telling" standardization, or maybe that's fine, or ???

Looks like @Nicole-Ridgwell-NMMNHS uses "Specific locality encumbered" (no dot).

Yes standardization is good, IDK how far we can go with that, let me know if I can do something to make it better/easier/whatever.

Otherwise -  edit away!

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
This may be useful to look at: https://github.com/ArctosDB/Arctos-Workflows/blob/main/.github/ISSUE_TEMPLATE/NMMNH_Single_Locality_Entry.md

In verbatim locality we enter "Locality data more refined than county is encumbered, contact collection for details"

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> but it seems like it would be useful somehow to distinguish 'real' coordinates from Arctos-created generalized coordinates.

You can also indicate this in georeference source.
