### ISSUE TITLE
Entities - have I gone crazy?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4745]
For the [iDigBio entity presentation](https://docs.google.com/presentation/d/1Drdv7SY9sxw_wHrapbXYbDwQtrloU1qPeMj1mPqrmF0/edit?usp=sharing), we specifically used Arctos Entity 2 - a golden eagle, but when I go to the entity collection now, Arctos:Entity:2 is the ALMNH dress and apparently the Eagle is now Arctos:Entity:19? What happened? Now the iDigBio presentation (which was recorded and [available for viewing](https://drive.google.com/file/d/14YhYwNZGToMHNCueJfmTaGotmz4Tj2Cc/view?usp=sharing)) is totally WRONG and it appears that our GUIDs are NOT persistent. Did all of us creating the iDigBio presentation somehow get the entity ID wrong or have they changed since then? If they changed, HOW? I haven't been able to prepare for this demo at all and now that I finally can, I feel like I have completely lost my mind. Someone please help me understand what happened.

@ccicero @dustymc @ebraker @mkoo @campmlc

**Comment by Jegelewicz** [comment]
Also, apparently none of the GBIF links are working? One component of the entity is https://arctos.database.museum/guid/MVZ:Bird:193219 which used to have a link to GBIF - I used it in the iDigBio presentation, but now there is none?
![image](https://user-images.githubusercontent.com/5725767/172271777-6c1d493d-11b5-4a85-8412-d53105d6db35.png)

One of the cool things about the entity record for the iDigBio presentation was how I could find all the associated stuff in GBIF by the entity url, I was hoping to show that off, but now don't think I can.

**Comment by Jegelewicz** [comment]
Finally, it seems that updates to the IPT aren't happening? MVZ:Bird:160626 still has the record GUID as dwc:organismID at iDigBio, I would think by now it would have updated to the entity guid?
![image](https://user-images.githubusercontent.com/5725767/172274873-2dd0427a-4a14-499a-8e2d-77f5c5d73449.png)

![image](https://user-images.githubusercontent.com/5725767/172274916-b6b55d38-0307-430b-a511-cc263ed6c441.png)

**Comment by Jegelewicz** [comment]
Sorry for the panic - but I have about 36 hours to figure out what to demo, I am jet lagged and this is taking a toll on my ability to function properly.

And from what I can tell - I just used the absolute wrong entity for the eagle in the iDigBio presentation. Hope nobody decides to go look at it....

**Comment by dustymc** [comment]
>GUIDs are NOT persistent

I suppose anything's possible, but the incoming identifiers seem correct and I don't see anything suspicious in the edit logs so I don't think anything's changed.

>ASAP

http://ipt.vertnet.org:8080/ipt/resource?r=mvz_bird claims to be from 2022-05-23 - maybe @dbloom can flap his magic wand around.

**Comment by ccicero** [comment]
I actually downloaded the eagle entity records after they were in Arctos and they definitely start at #3. So our mistake on the presentation??? Sorry, didn't catch that!

[GoldenEagle_entity_records_Arctosdownload_20220228.csv](https://github.com/ArctosDB/arctos/files/8853765/GoldenEagle_entity_records_Arctosdownload_20220228.csv)

I don't know about the links, but it does look like GBIF links aren't there for some records - but they are for others. The links are missing for 193195-193198 but not for records before/after those numbers (?). I can't explain that at all.

**Comment by ccicero** [comment]
@Jegelewicz I would pick a different eagle record to demo. It's too late for the iDigBio presentation but it would be good to update the slide so it's correct when the presentation is linked from arctosdb.

Sorry for the panick!

**Comment by Jegelewicz** [comment]
It's waaaay to late for me to pick something else. I'll make this work. And there is no way to fix the iDigBio presentation, there is a recording posted in their Google drive. I imagine that nobody will ever watch it, so it's probably no big deal. I'll see if I can pester Dave in the morning.

**Comment by campmlc** [comment]
I talked to Dave, but he needs to know how that link is created.

**Comment by dustymc** [comment]
>how that link is created

If you mean the links from Arctos, they're created magically if the resource's API claims to have the record.

**Comment by Jegelewicz** [comment]
> if the resource's API claims to have the record.

These are definitely there - I can find them in GBIF by searching dwc:organismID = https://arctos.database.museum/guid/Arctos:Entity:19

**Comment by Jegelewicz** [comment]
I'm guessing the recent switch to the weird urls cause some sort of disconnect that is mending itself slowly?

**Comment by dustymc** [comment]
> searching dwc:organismID 

AHA! My scripts were looking for current record=OccurrenceID, which obviously doesn't work with "entity components". I swapped that out to catalognumber, which (sorta-sometimes-maybe) works because we're using things like MVZ:Bird:186653. The links from Arctos should work now.

I think GBIF is still out of date so things don't get properly handled there, an update should (hopefully) fix that.

Big-picture, the "DWC Triplets" probably aren't unique and we need a better record identifier at GBIF.

**Comment by Jegelewicz** [comment]
> we need a better record identifier at GBIF

Agreed. Insight from Symbiota today - collections assign catalog numbers, but Symbiota provides a unique identifier across ALL Symbiota portals. Not saying this is the answer, but that it makes sense if we want to use APIs to set up search portals other than https://arctos.database.museum but still help the world understand that it is the same data. OK - I'm tired, that probably sounds like garbage, but it made sense to me earlier today.

Anyway, check it out

https://portal.torcherbaria.org/portal/collections/individual/index.php?occid=15853761
https://swbiodiversity.org/seinet/collections/individual/index.php?occid=15853761

Same catalog record - different portals, same Symbiota ID = 15853761

**Comment by dustymc** [comment]
I don't have any interest in "15853761" as yet another identifier. We do have a unique ID (``https://arctos.database.museum/guid/MVZ:Bird:193219``), there's just (apparently?!) no place for it in DWC. 

MAYBE we'll want to get a centralized yet "portal agnostic" identifier if someone really gets crazy with APIs, but if I have anything to do with that it'll look and work a lot more like  http://n2t.net/ark:/65665/339ec2704-9d3b-4ee6-a0b1-ddb05dfff745 than "3." (That ARK is used in GBIF as an OccurrenceID which could only directly translate if we radically change how we manage place-data. I can't see going there but it's still a nice identifier, whatever its used for.)

**Comment by dbloom** [comment]
@Jegelewicz et al.  Sitting at the GBIF table with @ManonGros (Marie Grosjean) and we're trying to understand what is happening here. We have some questions, but we also see something that makes us wonder...

@dustymc - that uniqueID (https://arctos.database.museum/guid/MVZ:Bird:193219) is in the GBIF record in the dwc:references field at the top of https://www.gbif.org/occurrence/3094065305. The occurrenceID is almost the same thing, but there is an appendage which makes us wonder where that comes from. The occurrenceID is http://arctos.database.museum/guid/MVZ:Bird:193219?seid=5045187 and it's that "?seid=5045187" at the end that we wonder about. 

So, if @Jegelewicz is trying to find some sort of semantic link with the unique Arctos ID that is in the references field in GBIF she won't find it. We can't even search for the reference in the GBIF UI. We can search fro the occurrenceID. The same thing is true in iDigBio in regard to the locations of these IDs - https://www.idigbio.org/portal/records/94ac457d-1614-4644-8185-03e40d01be3f

We'll be sitting at the GBIF table all day if those of you in Scotland wanna chat.

**Comment by dustymc** [comment]
The ?seid.. exists because some records get split into multiple Occurrences. https://arctos.database.museum/guid/MSB:Mamm:248770 maps to https://www.gbif.org/occurrence/1269500394, https://www.gbif.org/occurrence/1145279361, and https://www.gbif.org/occurrence/1455542249 for example. The ?seid provides a unique (but ephemeral) identifier that leads to the correct place (even if it's been removed from the component it once identified).

We are gluing those back together by using the Arctos GUID as OccurrenceID, which seems correct and works well.

Somehow that lead to using the same identifier for simple "just a dead rat" situations, which is probably a bit of an overstatement but it has been functional.

We have now for various reasons come to the point where stuffing everything into one Arctos record isn't sufficient, so we've created a catalog explicitly for the purposes of gluing things like, but not limited to, Organisms back together. https://arctos.database.museum/guid/MVZ:Bird:193219 is an Occurrence, https://arctos.database.museum/guid/MVZObs:Bird:4795 is another Occurrence from the same Organism, and https://arctos.database.museum/guid/Arctos:Entity:19 is the Organism (or glue that sticks the Occurrences together). 

The problem is that with that arrangement there seems to be no reliable way of finding https://arctos.database.museum/guid/MVZ:Bird:193219 via the API, and I can't build the links from Arctos if I can't do that. I'm currently using http://api.gbif.org/v1/occurrence/search?catalognumber=MVZObs:Bird:4797 (from https://arctos.database.museum/guid/MVZObs:Bird:4797), but there's no real reason to think ``MVZObs:Bird:4797`` is unique, so I guess that'll work until it doesn't.

Once GBIF is refreshed http://api.gbif.org/v1/occurrence/search?organismId=http://arctos.database.museum/guid/Arctos:Entity:19 (what we were using to build links up to yesterday) should find the three Occurrences, but that's not what's desired.

References ("The intended usage of this term in Darwin Core is to point to the definitive source representation of the resource (e.g.,Taxon, Occurrence, Event in Darwin Core), if one is available.") seems like what we want, if that could be added to the GBIF API.

**Comment by Jegelewicz** [comment]
Thanks everyone - the demo went great (thanks to Erica Krimmel noticing the http vs https - I'll put that in another issue)!

**Comment by Jegelewicz** [comment]
Does anyone need this to remain open? @dbloom @dustymc
