### ISSUE TITLE
Advice Request: Tracking Extinct and Endangered Species in Arctos

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#4763]
Has anyone come up with a way to track extinct / endangered / threatened species in Arctos? Whether it is a report or project or attribute, I'm curious to know how this has been addressed.

As a part of our permit process, we report specimens in our holdings to IDNR of endangered and threatened species held in our collections. We also just started a project photographing extinct bird species in our collections. It would be a lot easier to find specimens for these types of projects through an internal Arctos search. Maybe it could be a new feature that is tied to taxonomy?

**Comment by dustymc** [comment]
>Maybe it could be a new feature that is tied to taxonomy?

Agree this makes sense in taxonomy, but I don't think anything new is necessary.

I was going to say you could use the Arctos Legal classification to do this now, but that's in limbo pending https://github.com/ArctosDB/arctos/issues/3311 so you'll have to cheat a bit. Search eg

<img width="692" alt="Screen Shot 2022-06-14 at 10 37 39 AM" src="https://user-images.githubusercontent.com/5720791/173641541-994f8ed0-9fa7-4152-9fba-38f05b2bb2c9.png">

which will find nothing, then change the source to Arctos Legal

<img width="468" alt="Screen Shot 2022-06-14 at 10 37 52 AM" src="https://user-images.githubusercontent.com/5720791/173641640-df20b314-074c-4ee1-86bf-1e7774454b04.png">

finds Cites Appendix II according to Arctos Legal records.

If something's missing (and it probably is) it might be possible to add more sources to Arctos Legal (which is pulled from various places via API), or you could build your own classification to support this kind of thing. (Or you could add something to an existing local classification, but I would not recommend trying that with the big shared trashcan classifications - like "Arctos" - which are inconsistent and probably can't realistically be made otherwise.)

**Comment by mkoo** [comment]
How is "legal" have anything to do with a species extinction status? this is more of a conservation status like what IUCN does already-- there's already a criteria for listing species Extinct or Extinct in the Wild. I do agree taxonomy is a great place to start and I wonder if we can join IUCN status with taxonomy (we do that in AmphibiaWeb). It's maybe a time for a call so we can see if we can use their webservices? Their work covers plants, animals, fungi...

**Comment by mkoo** [comment]
@mkoo assigning to myself so I can remember to contact IUCN for a tech call re: their webservices.

**Comment by dustymc** [comment]
>How is "legal" have anything to do with a species extinction status?

Not "legal," "Arctos Legal" - a source of information. The important thing is the mechanism providing a means to find things by anything in any specified taxonomy source.

Webservices tend to be a little twitchy and the classification bulkloader is currently very good, if something like a spreadsheet can be obtained then it can probably easily be uploaded to some new Source (or old if that's somehow better), and that's probably the best path for almost all situations. Still happy to look for other ways if necessary.

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/4704
