### ISSUE TITLE
Code Table Cleanup - Record Attribute = gonad

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4774]
We currently have what appears to be a part in the catalog record attribute type code table.

[gonad](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type#gonad)

> A mixed gland that produces the gametes and sex hormones of an organism. [Wikipedia](https://en.wikipedia.org/wiki/Gonad)

I think this should probably be gonad length? It requires a numeric value and units of measure.

Suggest we add gonad length, move all gonad attributes to it and remove gonad.

**Comment by Jegelewicz** [comment]
Actually, based on usage, we should also add gonad width and the gonad attributes will need to be moved to the appropriate attribute.

See https://arctos.database.museum/guid/CHAS:Bird:2020.9.9
![image](https://user-images.githubusercontent.com/5725767/174351712-7644aa03-d8d0-44ea-8300-88a83ad569c9.png)

**Comment by dustymc** [comment]
[temp_gonad.csv](https://github.com/ArctosDB/arctos/files/8929686/temp_gonad.csv)

 @wellerjes
 @lin-fred
 @droberts49
 @kderieg322079
 @catherpes,@catherpes
 @acdoll


This should probably be moved to reproductive data (free text) and dropped - it's all sorts of things, including something that weighs 0.0624 fathoms....

**Comment by Jegelewicz** [comment]
I found the fathom thing and alerted the collection....

**Comment by Jegelewicz** [comment]
I think each collection should move it to wherever it makes sense. (The fathom thing should be using gonad weight). They probably need eyeballs on them to get them in the right place.

**Comment by Jegelewicz** [comment]
https://arctos.database.museum/guid/MSB:Bird:19552

seems like it should be gonad length and gonad width

![image](https://user-images.githubusercontent.com/5725767/174353630-1f5774b7-00a9-44d8-8103-48e4dbf63ce1.png)

**Comment by lin-fred** [comment]
> https://arctos.database.museum/guid/MSB:Bird:19552
> 
> seems like it should be gonad length and gonad width
> 
> ![image](https://user-images.githubusercontent.com/5725767/174353630-1f5774b7-00a9-44d8-8103-48e4dbf63ce1.png)

That's also the reason for our NMMNH record as well. If not this way, what would be the better way?

**Comment by Jegelewicz** [comment]
> what would be the better way?

That is pretty much what I am suggesting with this issue. That we add gonad length and gonad width.

BUT

this is a bit of a cluster because we also have

[right gonad length](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type#right_gonad_length)
[left gonad length](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type#left_gonad_length)
[right gonad width](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type#right_gonad_width)
[left gonad width](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type#left_gonad_width)

so when you don't know if it is left or right, you are stuck

**Comment by catherpes** [comment]
that Trotter MSB BIRD record is someone entering data in a nonsensical manner making a lot more work for themselves then and us now. I have updated it.

**Comment by dustymc** [comment]
>cluster because we also have

Question for the ornithologists: how much of this is Research Grade? Are we recording this because someone could have a plausible "sciencey" reason to search by eg right gonad length, or would these data be equally useful in something like [reproductive data](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type#reproductive_data)? (The remarks and such in these data make me think ``gonad`` is not very useful by itself, but that's a tiny sample size.) We probably have to find a way to support whatever is necessary to do science, but having lots of attributes is [not without cost](https://github.com/ArctosDB/arctos/issues/1623). If we can find a way to eliminate some attributes without losing any functionality, we should do so.

**Comment by Jegelewicz** [comment]
@ccicero

**Comment by catherpes** [comment]
Generally, birds have only one ovary, the left, so this mostly refers to male birds, with the exception of Raptors which can have two ovaries and the right one is reduced. In collections where left and right testis sizes have been recorded separately, there has been at least one paper that has looked at that phenomenon. And I don't remember anything about it beyond that. Maybe a collection somewhere has a series of raptors with right ovary measurements already parsed out and would not want to lose that effort. I question why right gonad length would be separated from right gonad width. 'right gonad dimensions' would seem to be fine. 
So, it can be useful to parse out the data that fine. I'm happy with reproductive data being free-form text at this point in this collection because unless one is quite different than the other, we generally do not record them separately.

**Comment by ewommack** [comment]
There has been more work presented at recent conferences that show that there may be differences in testes size depending on species and conditions. I think the fact that more museums are starting to record both testes sizes isn't know yet, but having the data there I think will be really valuable. More so as well, as people are taking one testis for RNAlater sampling, and often we are left with measuring the right for some of those birds. Having both measurements with all the non-sampled birds would make more data available for comparisons.

For the ovaries - actually there are a lot more birds that can have two ovaries then we normally think. Kiwis apparently have two ovaries regularly. It has popped up in a variety of other groups as well. There are probably the most data on it in the diurnal birds of prey, because people know to look for it. Accipiters are the most reliable having two ovaries, but other taxon groups also have it. There are more published articles on this topic. It is still debated on whether the second ovary may be viable. I just always tell me students to check both sides no matter what. We found it in a second ovary in a grebe thanks to that.

**Comment by dustymc** [comment]
```

 guid_prefix | count 
-------------+-------
 MMNH:Bird   |     1
 CHAS:Bird   |     2
 NMMNH:Bird  |     2
 UMNH:Bird   |     1
 MLZ:Bird    |     1
```

**Comment by wellerjes** [comment]
Just removed gonad from CHAS:Bird records.

**Comment by lin-fred** [comment]
NMMMH is removed as well

**Comment by Jegelewicz** [comment]
Slim this down to gonad length and gonad width - move left and right to method.

**Comment by mkoo** [comment]
Alrighty, this was discussed in Issues meeting by the AWG-- here's the conclusions:
add in measurement attributes of gonad length, gonad width, gonad weight-- users should use methods to indicate left or right or unknown

This would make usable for all vertebrates. 
I will start new requests for the above and leave notes on all affected CT requests. This issue can remain open until these 5 records are updated appropriately.

MMNH:Bird   |     1
 CHAS:Bird   |     2
 UMNH:Bird   |     1
 MLZ:Bird    |     1

**Comment by dustymc** [comment]
Fresh data:

[temp_gonad.csv](https://github.com/ArctosDB/arctos/files/14539192/temp_gonad.csv)


Summary:

```

 guid_prefix | count 
-------------+-------
 MMNH:Bird   |     1
 UMNH:Bird   |     1
 MLZ:Bird    |     1

```

contacts


 @barke042
 @adhornsby
 @kderieg322079

**Comment by adhornsby** [comment]
MMNH cleaned up... and we promise to stop measuring our bird testes in fathoms.

**Comment by Jegelewicz** [comment]
UMNH:Bird separated into left gonad length and width

**Comment by dustymc** [comment]
@mkoo help - can I just move this to https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type#reproductive_data ?

```
 guid_prefix | count 
-------------+-------
 CHAS:Bird   |     1
 MLZ:Bird    |     1

```
   ghaddr    
-------------
 @droberts49
 @wellerjes

**Comment by wellerjes** [comment]
Updated CHAS:Bird record.

**Comment by campmlc** [comment]
ANSP:Host have gonad attributes, with more in the component loader associated with @Jegelewicz . Can these be converted?

[attributeDataDownload gonad.csv](https://github.com/user-attachments/files/16852437/attributeDataDownload.gonad.csv)

**Comment by campmlc** [comment]
Also, just to clarify from the bird folks - what gonad is being measured here? Mammalogists measure testes, and need to be able to designate that the "gonad" is a testis measurement. But I don't see that in bird records. How do we distinguish? Mammal folks would prefer to use the term "testes", but can grudgingly use "gonad" only if "testes can be made explicit. Is this "gonad" measurement for birds actually a testis measurement?

**Comment by campmlc** [comment]
@jldunnum @bryansmclean

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/7504
