### ISSUE TITLE
Need ability to add taxon names and classifications from WoRMS into WoRMS (via Arctos) on command 

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#4784]
Moving this request from [Unable to fresh WoRMS (via Arctos)](https://github.com/ArctosDB/arctos/issues/4780#) to a separate issue.

As noted in the above issue, we are again having to frequently add taxon names and classifications that are in WoRMS into WoRMS (via Arctos).  This can be done one at a time or by creating a list of names from WoRMS, bulkloading them, using the match tool to get the WoRMS aphiaID and bulkloading that into the classification and metadata, then refreshing the group.  This is time consuming and only addresses the groups our collection needs.  It cannot create a fully updated WoRMS (via Arctos) source.   

**Describe what you're trying to accomplish** 
Reduce the manual effort required to add taxon names.

**Describe the solution you'd like**
Bringing all taxa from WoRMS into WoRMS (via Arctos) with regular updates would be ideal.  Alternatively, a program that brings over a select group of taxon names and classifications would suffice.

For example, today we are databasing records of Pleurostemma and Idiostemma.  Only the genus Pleurostemma is in WoRMS (via Arctos).  None of the 12 children taxa are there.  For Idiostemma, there are two of the 19 children taxa in WoRMS (via Arctos)

![image](https://user-images.githubusercontent.com/15368365/175074049-0d027ceb-bf57-49b1-b42e-96391537976c.png)
 
![image](https://user-images.githubusercontent.com/15368365/175076999-a230b3d0-ef9e-4c52-af84-aa62c256bc75.png)

If we could click "Add children taxa" on the genus and have it upload all the children names and aphiaIDs that would eliminate a lot of manual work.  If it could refresh as well, that would be great, but we have a tool that works very well that we can use to refresh the group.  If we could use the "Add" tool at the family level - Urocoptidae - that would be fantastic.

**Describe alternatives you've considered**
Keep doing it manually as needed.

**Priority**
Normal priority but we're adding taxa more and more frequently as WoRMS (via Arctos) fails to catch up with new WoRMS entries.

**Comment by Jegelewicz** [comment]
> 
>     a lot of "names" in worms have identification-junk mixed in, there really needs to be a human in the pipeline
>     a lot of (valid) names in worms have multiple classifications, which results in some sort of mess unless there's a human involved

Can I get an example or two? If we can't make use of WoRMS, I suspect nobody can (although apparently GBIF does).

**Comment by dustymc** [comment]
Anything with a subgenus, https://www.marinespecies.org/aphia.php?p=taxdetails&id=1507624 are invalid.

There's a homonym example in https://www.marinespecies.org/tutorial_taxonmatch.php

Not sure where you get "can't make use of"??

**Comment by sharpphyl** [comment]
> I don't see any sustainable way to resurrect automagically pulling names and/or aphiaid from worms without some human guidance, but of course **I'm always up for better ideas.**

I created the attached document that details how we're currently adding taxon names and classifications to WoRMS (via Arctos).  I'm open to any suggestions to streamline this five-step process.  Right now, three different csv files have to be created and uploaded.  @dustymc Can some of them be consolidated as described below?

Would it be possible to add a feature to the Name Checker that would automatically bulkload all names that return a FAIL status?  It would require adding the heading "name_type" to the csv uploaded to the Name Checker, but it would save one step in the process.  

Adding classifications might need human intervention because of the multiple sources possible.  For WoRMS (via Arctos), could the aphiaID, source and a classification term (probably family) be added the Names Bulkload csv so that the name and classification upload at the same time?  That would save another step in the process.

A separate but related issue is in the last paragraph of the document.  We need an explanation of how the "refresh" function works.  It appears that is only refreshes aphiaIDs that haven't been refreshed before.  How does it know which names to refresh when it does the query?  It's a valuable feature in that it helps us know which families need to be refreshed (assuming all the WoRMS names are in the Arctos table), but we don't understand how it's programmed to do that.

@Jegelewicz   Since this could impact any collection needing to add taxon names and classifications to our Arctos table, should we add this to the Taxonomy Committee list for input? 

[Steps to bulkload names to WoRMS (via Arctos) as of June 2022.docx](https://github.com/ArctosDB/arctos/files/8987196/Steps.to.bulkload.names.to.WoRMS.via.Arctos.as.of.June.2022.docx)

**Comment by dustymc** [comment]
> add a feature to the Name Checker that would automatically bulkload all names that return a FAIL status?

That would be about the same as not using the checker at all, I think. You can (technically) just toss names at the loader and see what sticks. I think - from a non-technical/Research Grade/Best Practices standpoint - that more human involvement is valuable. (But this is WoRMS, they seem to have a sorta-limited number of issues, maybe more humans on our end are less-relevant here, I don't know.) The checker is REALLY dicey (because the sources are, and the check is trying to find a consensus where there almost never really is one), the Arctos pattern check is dicey in other ways (it just considers string patterns), there should really be a conscientious human involved. How that stands up to reality I don't know, but I'd like to. (Maybe portions of our checkers are adding garbage and should be removed, or other sources should be included, or maybe we should be running post-load scans or treating taxonomy more like an authority or WHATEVER; I don't know, I don't get much feedback.)

>could .... classification ... be added the Names Bulkload 

At the core of this, I want to say "no" - we've been there, done that, complicated loader/tools find interesting ways to fail, the simple/focused tools are better in every way. BUT, we've recognized that lots of tasks are interrelated (https://github.com/ArctosDB/Arctos-Workflows is a product of those discussions) and I think there's probably a technical side to that as well, but we haven't quite nailed down the details of how a "loader-loader" might work. I think that's largely a matter of user input needed (in a new/dedicated Issue). Maybe that's as easy as a "taxa+classification" tool that simply splits a file and feeds it two ways, or maybe that's pre-Arctos tools, or maybe all of those would confuse users, or ??????????????? IDK, I don't think I'd ever use that, I like the small simple steps, I'd need significant input to make that a technical problem.

>These are subgenera we overlooked that won’t upload

Fair enough, that's why we have checks, but see above - there are LOTS of strings which aren't taxa which will sail right through my checks, I'd really like to see this be a more people-centric task (should reality allow that, and as above maybe more or less depending on the source of the potential names).

>Others are homonyms and therefore duplicate names with multiple aphiaids we missed.

This is the sentence that caused the current state of panic. The classification loader simply replaces ("This form REPLACES classifications; name-at-source will be deleted (even if there are multiple), and data in this file will be loaded into that location."). This situation won't throw any sort of error or indicate any sort of problem, it'll just turn all eleventy bajillion of your clams into whatever's on the other end of the homonym. (Actually you'll probably eventually notice if there are lots of them; it's a few sneaky names in some huge genus or something that'll really mess up everything.)

>need an explanation of how the "refresh" function 

The UI-side just inserts name+aphiaid into a table.

The scheduled task loops for names in that table, starting with deleting the name-at-source (eg adding lots of aphiaids for a name will result in whichever one gets processed last - a close-enough-to-random operation - being retained) and then adding back whatever's found with

```
http://www.marinespecies.org/rest/AphiaRecordByAphiaID/#aphiaID#
```
plus
```
http://www.marinespecies.org/rest/AphiaClassificationByAphiaID/#aphiaID#
```

And I think I found the source of your (accurate!) "haven't been refreshed before" statement - when we controlled terms we used ``aphiaid`` so that's what the form is looking for, but now we don't control and WoRMS returns ``AphiaID`` which leads to what you describe. That'll be fixed (case-insensitive) in next release (tomorrow-ish, I hope).

Let me know if I failed to answer any of your questions.

> add this to the Taxonomy Committee 

I'd say yes - more eyes seems better, maybe things that look like human problems to me could be made into my/technical problems, etc., etc. 

I'd recommend backing WAY up and looking at the procedures. I dug around in the data a bit, but I'm not sure I learned anything useful. Looks like @sharpphyl (I didn't look at other users so that may mean nothing) adds a few names per month (plus some big surges) and a few of those are used in cataloging (plus a few surges) - MAYBE that's an indication that this could be some yearly event, or ???? I don't know, I don't think I understand enough about how any of this works in the collections to say much, but if there's some way to turn many events into one bigger event then maybe that should be investigated; the number of records generally has little impact on the overall work of bulk events.

WoRMS has a monthly (yearly?? some interval...) file that they were making available to me (maybe still are, I'd have to dig for the details) - I never used that, except for the initial import, because it didn't have quite the right kind of data in it. (See above - I still have a make a couple calls to their API, they have a LOT of views of their data floating around for some reason.) Maybe that (or something like it) would make a better entry point than whatever leads to '1.	Find all names WoRMS by searching for the family or other term'?

**Comment by campmlc** [comment]
This is an aside, but I've long wished for a tool that would allow
something like a "tool that simply splits a file and feeds it two ways".
There are other workflows that would benefit from this - part and part
attribute bulkloaders come to mind.

**Comment by dustymc** [comment]
>data from sources that include a unique identifier

I don't think that's a distinguishing feature. I can (maybe? Is that still around?) mint LSIDs for my billions of misspellings, that doesn't make them any more Arctos-friendly or taxonomy-like. (With LSIDs I can *pretend* I've minted those billions and remain almost certain that nobody will notice....) No matter how awesome at identifying an identifier might be, they're not (usually) indicators of data quality or fit-for-use.

>Yes, yes and yes! How about three ways?

Maybe this is one of those places where the only way to know is to try. So sure, send me something (see below first), I'll see what I can do (or what I need or whatever) to parse it out to the various existing tools. (And at least one new one, a CSV-->worms refresh request should but does not exist). Hopefully that will help guide some framework that can extend to things like complex operations involving parts and such.

> unaware of how homonyms functioned when we did the first upload to WoRMS 

Yes, but you didn't have records depending on classifications from them at that time (I think?), and now you do. (And you're far from alone in that, see below.)

> If you could....

I don't think I can, at least not safely, that needs some knowledge that I do not have. I can definitely turn some giant list into data and hopefully eventually tools and such, but I'm not going to notice if I'm turning all of your clams into diatoms or something. I might be SLIGHTLY more likely to notice than full automation, but neither me nor my scripts are very likely to have any "wait, we don't catalog jellyfish..." moments, and I think that something which might have that experience (say, a collection-connected human being...) needs to guide this entire process. I - or my scripts - will absolutely mangle your collections without noticing, un-mangling when you do notice will be orders of magnitude more work than preventing would have been, and then Arctos will be blamed for the whole shebang. No fun.

> collections using WoRMS

Wow, there are 47 of them at the moment! So now I'm really paranoid - that's a LOT of opportunities for even  purposefully changing meanings (aphiaids) to have unforeseen consequences. Even adding could lead to unintended changes, depending on how a collection has arranged their preference stack, and 28 collections have WoRMS listed first (which isn't the only way even an addition could lead to drastic changes, but it makes such things closer to inevitable).

I'm still happy to help with whatever tools I can, but I started off thinking that this probably needs more human guidance, and every new piece of information I uncover has reinforced that. There should absolutely be some sort of "WoRMS users group" reviewing proposed changes and additions. (https://github.com/ArctosDB/arctos/issues/3121 was my idea for a technical solution to that, it could be revived if it has a purpose in this, I don't think I see one at the moment.) 

FWIW if I had to run such a committee I'd base everything off of a spreadsheet (consisting of name, aphiaid, and whatever else is necessary to keep organized - family maybe) in which users could review proposed changes, and which could be loaded to Arctos from time to time. (I might have recommended the hierarchical editor a while back, but the classification bulkloader now essentially has no limits and everything everywhere speaks CSV and I don't see much reason to maybe-ever use anything else.)

Here are current using collections, github users below, should someone wish to organize something.

```
arctosprod@arctos>> select guid_prefix,preference_order from collection inner join collection_taxonomy_source on collection.collection_id=collection_taxonomy_source.collection_id and source='WoRMS (via Arctos)';
  guid_prefix  | preference_order 
---------------+------------------
 MLZ:Herb      |                1
 NMMNH:Inv     |                1
 DMNS:Inv      |                1
 CHAS:Herb     |                3
 ALMNH:Paleo   |                3
 ALMNH:Inv     |                1
 NCWRC:Bivalve |                1
 NCWRC:Gastro  |                1
 ACUNHC:Ento   |                1
 ACUNHC:Paleo  |                1
 JFBM:Inv      |                1
 ALMNH:ES      |                3
 UTEP:Inv      |                1
 UAMObs:Ento   |                2
 NHSM:Inv      |                1
 HWML:Para     |                3
 CDSC:Inv      |                1
 MVZ:Herp      |                3
 MVZ:Hild      |                3
 MVZ:Mamm      |                2
 MVZObs:Bird   |                2
 MVZObs:Fish   |                2
 UNM:Paleo     |                1
 MVZObs:Herp   |                3
 MVZObs:Mamm   |                2
 MSB:Inv       |                1
 UAM:Ento      |                2
 MSB:Para      |                1
 TMCC:Inv      |                1
 TMCC:Fish     |                1
 OWU:ES        |                1
 ACUNHC:Fish   |                1
 OWU:Herb      |                2
 OWU:Para      |                2
 ACUNHC:Inv    |                1
 ASUMZ:Invert  |                1
 OWU:Inv       |                1
 OWU:Fish      |                1
 CHAS:Inv      |                1
 MVZ:Bird      |                2
 MVZ:Egg       |                2
 MVZ:Fish      |                2
 Arctos:Entity |                1
 MLZ:Fish      |                1
 MLZ:Inv       |                1
 NMMNH:Paleo   |                4
 ASUMZ:Bivalve |                1
```

```
select
    replace(get_address(contact_agent_id,'GitHub'),'https://github.com/','@') as ghaddr
from (
    select
        contact_agent_id
    from
        collection_contacts
        inner join collection on collection_contacts.collection_id=collection.collection_id
        inner join collection_taxonomy_source on collection.collection_id=collection_taxonomy_source.collection_id
         and source='WoRMS (via Arctos)'
    where
        contact_role='data quality'
    group by
        contact_agent_id
)x where get_address(contact_agent_id,'GitHub') is not null
;
```

 @wellerjes
 @msbparasites
 @Nicole-Ridgwell-NMMNHS
 @mlbowser
 @lin-fred
 @claypollock
 @mkoo
 @leet1984
 @Jegelewicz
 @campmlc
 @ccicero
 @kmkocot
 @bfluker
 @droberts49
 @zmsch
 @jrpletch
 @phrynosoma13
 @sharpphyl
 @aklompma
 @acdoll
 @atrox10
 @dssikes
 @crcarter00
 @gracz-UNL
 @mvzhuang
 @cjconroy

And @DerekSikes I think your github address in Arctos still needs attention.

**Comment by Jegelewicz** [comment]
> And @DerekSikes I think your github address in Arctos still needs attention.

fixed

**Comment by Jegelewicz** [comment]
> WoRMS distinguishes between homonyms by concatenating the taxon name and the author and giving each a unique aphiaID. If we had a similar capability, each collection could select the correct name without disturbing another collection.

Sigh - I don't know why this is such a hard sell.

**Comment by Jegelewicz** [comment]
>  discuss having a WoRMS (via Arctos) committee at the next Taxonomy Committee meeting?

If anyone is that interested they will show up in the Taxonomy meetings. When enough people show up in Taxonomy who care, we can talk about yet another committee. I see no reason for @sharpphyl and me to meet more than once per month (unless it is to just have coffee and talk about not-Arctos).

**Comment by dustymc** [comment]
>is a distinguishing feature.

Not of what we'd call a valid taxonomic data. https://www.marinespecies.org/aphia.php?p=taxdetails&id=1507624 has both, it's still just a string pretending to be something it isn't.

>distinguishes between homonyms by concatenating the taxon name and the author 

File an Issue! (There's no way that's really unique, and it would cut us off from sharing taxonomy with most sources, but mostly we aren't sharing taxonomy or using more than tiny fractions of the potential of the complex model, I'm not preemptively resistant to completely radical ideas.)

**Comment by Jegelewicz** [comment]
@dustymc we had a long discussion about this in Taxonomy Committee today. Is it even possible that we could use WoRMS taxonomy without importing it to Arctos? I know it is wishful thinking, but grabbing data in their format and transforming it to ours seems to be what is causing all of the extra work...

**Comment by dustymc** [comment]
>use WoRMS taxonomy without importing 

I've been begging and pleading for someone to approach WoRMS (the source) and GlobalNames (a unified API) with that for several years.

**Comment by Jegelewicz** [comment]
I guess I don't know what that means. WoRMS (the source) has an API, what more do we expect?

**Comment by dustymc** [comment]
@sharpphyl the worms dump seems to no longer be available. (``https://www.marinespecies.org/export/arctos/WoRMS_Arctos.zip`` if that's useful for some reason.)

**Comment by sharpphyl** [comment]
WoRMS sent me a link to download all their data but it turned out to be only marine and brackish species and I needed terrestrial and fresh-water.  They're trying to create a list for me of the missing species (or all mollusca) but in the meantime sent me a spreadsheet of Clausiliidae which is the next family I'm working on (8,500+ species).  They were very responsive as you expected.

**Comment by sharpphyl** [comment]
> https://www.marinespecies.org/export/arctos/WoRMS_Arctos.zip

Access forbidden, but let's see if WoRMS will send me the entire Mollusca database.

**Comment by sharpphyl** [comment]
I can't seem to open your link.  Can you post the contents (or a portion of it such as the Stylommatophora) on Google docs if it's an Excel spreadsheet?  If it's the original dump, it may not help, but if it's more recent, it would be worth looking at.  I can go to WoRMS for each family, but they haven't yet sent all terrestrial taxa.  I'll nudge them again if this list is out of date.

<img width="675" alt="Screen Shot 2022-09-28 at 8 49 40 PM" src="https://user-images.githubusercontent.com/15368365/192927538-0440474a-f432-471d-91ed-445ff83b38dc.png">

**Comment by dustymc** [comment]
my dump seems to no longer be available

**Comment by sharpphyl** [comment]
OK.  It seems like this issue has no solution except to continue to manually add taxon names and classifications to WoRMS (via Arctos).  It's doable but time consuming.  If you get a new list from WoRMS, let us know.

**Comment by dustymc** [comment]
I thought you were talking to worms, did I misinterpret https://github.com/ArctosDB/arctos/issues/4784#issuecomment-1267811480?

**Comment by sharpphyl** [comment]
I am talking to WoRMS, but at best, they'll just send me a list of all terrestrial mollusks, for example.  Don't have it yet, and without it, it will take hours to create it from WoRMS downloads.  But even if I get that, there are still three more .csv files to create and clean-up before the refresh stage.  

Clean out all the names with subgenera - Arctos rejects anything with ( ).
csv to run Arctos name checker
csv to add FAIL names to Arctos
csv to add aphiaid and classifications to Arctos
clean up homonyms Arctos rejects (always a manual process)
refresh  

It just takes time and probably needs to be done periodically to catch new names.  I'll take care of Mollusca but leave the rest to other collections.  If any of these steps could be combined, it would be helpful.  Each has unique headings.  For example, could all the names that FAIL be autoloaded (on request) by checking the name_type?
