### ISSUE TITLE
Code Table Request - new other ID relationships

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4796]
**Goal**
From today's discussion with @babogan 
ALMNH:EH has artwork that depicts specimens in the University of Alabama Fish Collection (not in Arctos)

**Context**
This is not media - these are physical, sometimes framed drawings

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctid_references

**Proposed Values**
depiction of
depicted by

**Proposed Definition**
**depiction of** - The cataloged object shows or represents by a drawing, painting, or other art form the object represented by the related identifier.

**depicted by** - The cataloged object is shown or represented by a drawing, painting, or other art form in the object represented by the related identifier.

**Available for Public View**
Yes

**ID_References**
[  If the request involves https://arctos.database.museum/info/ctDocumentation.cfm?table=ctid_references, the changes must be coordinated with the Database Admin team for notifications to function.  ]

**Priority**
This relationship is needed to complete cataloging of the artwork held

**Comment by babogan** [comment]
Thank you!
I know this is quite conditional but hopefully will get mileage outside of our fish artworks.

**Comment by dustymc** [comment]
The idea seems sound, but I think the scope/definition doesn't. 'Art' seems too limiting (and not very useful) - I can't see why this shouldn't work for separately-cataloged derivatives/depictions, whatever the intention and however artful (or not) they might be deemed by someone. Images (of whatever sort), drawings, casts, sculptures, etc., made from or just inspired by, regardless of intention, all seem like they belong in this 'bucket.'

I think "depiction of" works.

I think I like "depicted as" (rather than "by," which makes me think people for some reason) better as the reciprocal.

@Nicole-Ridgwell-NMMNHS relevant to you?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
As written, I think this will work for replica of, which we'll probably need at some point.

**Comment by Jegelewicz** [comment]
added
