### ISSUE TITLE
Duplicating Information on Upload[CONTACT]

### ISSUE THREAD

**Issue by awilkins007** [ArctosDB/arctos#4803]
We are working on associating large quantities of mammal trait data with their specimen records. Much of the data isn't in Arctos already but some of it is. Uploading when data exists just duplicates that part. Is there a way we can upload the information but just append the missing parts rather then duplicating the record?

** Please use the "Report Bad Data" link where available to ensure the correct Curator receives your message. **

** Outages should be reported to the contacts listed at https://arctosdb.org/arctos-down/ **

** Arctos Documentation is http://handbook.arctosdb.org/ **

** Learn more about Arctos at https://arctosdb.org/ **

** Please include enough information to re-create the problem if this request involves Arctos forms. Links and screenshots are helpful. **

**Comment by Jegelewicz** [comment]
> Is there a way we can upload the information but just append the missing parts rather then duplicating the record?

Are you adding parts, attributes or both?

**Comment by awilkins007** [comment]
Just attributes.

**Comment by Jegelewicz** [comment]
There is no way to replace a current attribute - this is because often we have multiple attributes of the same type for a given record (attributes are considered opinions).

There is an [attribute unbulkloader](https://arctos.database.museum/tools/BulkUnLoadAttribute.cfm)

You can use this either before or after loading your new attributes (but before might be easier).

1. Get a download of all catalog records plus attributes for which you want to replace an attribute.
2. Use the above to create an attribute unloader for the ones you will be replacing.
3. Unload those attributes
4. Load your new attributes

If after, the process would work the same, but there would need to be some way to distinguish between the two attributes of the same type.

Let me know if this doesn't make sense. I am free after 2PM mountain time if a meeting would help.

**Comment by dustymc** [comment]
done?
