### ISSUE TITLE
No specific locality recorded.

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4809]
We are not using the recommendation to select "No specific locality recorded." when specific locality is not known, given or otherwise available.

> This isn't a criticism, it's a question. Why did the Arctos team decide to give this advice in the handbook (https://handbook.arctosdb.org/documentation/locality.html)?
> 
> #In these examples, as well as in records for which appropriate data are missing, the correct value for Specific Locality is, “No specific locality recorded.”#
> 
> I ask because it goes against the databasing principle that a field should contain only 1 kind of information, in this case a locality string. You would raise an eyebrow if the Specific Locality entry was "They sell cherry ice cream here", because that's not a locality, and neither is "No specific locality recorded."
> 
> I'm arguing in that GBIF forum post (https://discourse.gbif.org/t/the-vexed-question-of-missing-data-in-darwin-core/3374) that you should use a separate field to explain missing data. Did the Arctos community decide that an explanatory field wouldn't be used properly?
> 
> Here's a real-world example, from the DMNS Marine Invertebrates dataset is DwC-ed in GBIF. Among the DwC "locality" entries are
> 
> No. of records | locality
> 19 |      [blank]
> 2 | no specfic locality recorded
> 1 | no specific
> 2 | no specific date recorded
> 1 | no specific island recorded
> 2 | no specific lacality recorded
> 2 | no specific locaility recorded
> 2 | no specific localilty recorded
> 1 | no specific localitly
> 1 | no  specific locality
> 303 | no specific locality
> 13 | No specific locality
> 1 | no specific locality entered
> 17 | no specific locality given
> 1 | No specific locality given
> 1 | no specific locality located
> 1 | no specific locality recoded
> 2 | no specific  locality recorded
> 3 | no specific locality  recorded
> 8695 | no specific locality recorded
> 16 | no specific locality recorded.
> 247 | No specific locality recorded
> 2733 | No specific locality recorded.
> 4 | no specific locality recorded.   Specific Gulf inferred from context.
> 5 | no specific locality recorded (terrestrial)
> 3 | no specific locality recorded (terrestrial species)
> 1 | no specific locality redorded
> 1 | no specific locality reorded
> 3 | no specific locality reported
> 2 | no specific locality reported.
> 2 | no specific locality specified
> 6 | no specific locallity recorded
> 1 | no specific localtity recorded
> 22 | no specific localtiy recorded
> 4 | no specific location
> 3 | no specific location recorded
> 1 | no specific loclality recorded
> 2 | unknown
> 4 | unspecified
> 
> What happened and why? (I appreciate that a partial answer is given by DMNS use/non-use of lookup tables and validation rules; there are worse issues in this dataset.) From the data user's point of view, wouldn't it have been better if all these entries were blank?
> 
> Best wishes,

Bob
--
Dr Robert Mesibov
West Ulverstone, Tasmania, Australia 7315
Home phone: (03) 6425 2630
https://www.datafix.com.au/ (data auditing and cleaning)

_Originally posted by @Jegelewicz in https://github.com/ArctosDB/arctos/discussions/4807#discussioncomment-3107732_

**Comment by Jegelewicz** [comment]
I spent a considerable amount of time going through the list above and converting these to "No specific locality recorded." (Thanks @dustymc for the easy-to-use button when editing localities!) And it wasn't only DMNS making use of the terms in the list!

BUT there are some that we need to change in bulk because editing 9,000 localities one by one is not my idea of a good time.

@dustymc can you make global changes as follows? Note that searching in localities brings up any form of capitalization, so the count for no specific locality includes No specific locality and so on.

current specific locality | # of localities
 -- | -- 
no specific locality recorded | 6,530 
no specific locality | 1,594 
no specific location | 82 
unknown | 866 
unspecified | 381 
NULL | 94 

I am certain there are other versions of "No specific locality recorded.", but I don't know the most efficient way to find them all. I also do not know how to get people to use this instead of any other version of "Nothing Interesting To Say" and maybe we need to revisit what is going on here.

Finally, how do we end up with NULL here? I have always assumed that this is a REQUIRED field. In the bulkloader builder it is one of the fields given when I select required. If NULL is an option, maybe it is the better option - but we can discuss that in https://github.com/ArctosDB/arctos/discussions/4807

@sharpphyl as your team is entering records - please have them make use of the "No specific locality recorded." button to avoid misspellings and ensure that the proper phrase gets used.

![image](https://user-images.githubusercontent.com/5725767/178015576-4559a0d7-3fab-41df-b098-5a5dee65e23a.png)

If anyone else is manually entering data - please do this too! Bulkloading is another thing and I don't know how to check that stuff for issues.

**Comment by sharpphyl** [comment]
> @sharpphyl as your team is entering records - please have them make use of the "No specific locality recorded." button to avoid misspellings and ensure that the proper phrase gets used.

Yes, that is our standard procedure now.  I really appreciate your asking Dusty to correct all the rest of them on a global basis.  Many of our localities are shared and I've been reluctant to correct them as I would impact other collections without them necessarily approving.  If there is 100% agreement that this can be done by any Arctos User, then I'll be happy to edit any localities we use that have some unaccepted variety of "nothing to see here."

Note that this was discussed on 27 May 2021 in [#3562](https://github.com/ArctosDB/arctos/issues/3562) but was evidently never implemented, maybe because it was buried inside another issue.

<img width="947" alt="Screen Shot 2022-07-08 at 10 17 32 AM" src="https://user-images.githubusercontent.com/15368365/178031140-f0875298-6ec7-4134-bf2b-fdeff892a0f1.png">

**Comment by Jegelewicz** [comment]
MSB is particularly fond of NO SPECIFIC LOCALITY. I don't know how to get the word out about using "No specific locality." but I also know that whoever we reach now, it will eventually be forgotten, overlooked, or otherwise misused. Humans will just not be able to remember this nor will they be inclined to go look it up. It will be a constant struggle and in some ways I'm not sure it matters....

**Comment by campmlc** [comment]
This is why I think the model of using this is incorrect. Any model that
fails with expected and predictable human error isn't going to work  -and
this particular error is expected and predictable. We can train a few
people some of the time, but not all the people all of the time . . . .

**Comment by Jegelewicz** [comment]
In some ways, there is NO good answer here - no matter what we do, locality will need to be free text and we WILL have multiple versions of "Nothing Interesting To Say". However, I think that Bob's point about NULL should be given a hard look AND it should be applied everywhere. I think we would have far fewer issues if the instructions across the board were "If you don't know or don't have information, just leave it blank".

**Comment by Jegelewicz** [comment]
Yes, I think that would be more correct, except that I think your reason for leaving spec_loc NULL should be recorded somewhere. In our model, would that be better placed in collecting event remark or specimen (ugh) event remark? I could see arguments for both. The reason an explanation is warranted is that, as Bob point out, there are variations on "unknown". Is there hope that it will ever be known or is this just always going to be a low-data record? If there is hope, how much and where might I start looking for more details?

In any case, I think this needs a community discussion and we should pick a path together.

**Comment by sharpphyl** [comment]
When we don't have information on habitat, depth, collecting method, etc. we just leave the field blank.  Why would Specific Locality be any different and require an explanation?  It's highly unlikely we'll ever learn more details but, if we do, we'll add them.

**Comment by dustymc** [comment]
>@dustymc can you make global changes as follows?

Sure, but I do need some nod from the collections, and...

>Humans ... nor will they be inclined to go look it up. 

If we can't be bothered to read the most straightforward documentation, then I'm not going to waste my time bashing my head on a problem that we're not willing to solve. We need a solution, not bandaids, and I can't see any way in which that can be a technical problem.

>certain there are other versions of "No specific locality recorded.", but I don't know the most efficient way to find them all. 

You won't find them. That's why we have documentation; the only plausible solution is preventing (most of, perhaps) the variations rather than trying to track them down after the fact.

>how do we end up with NULL here?

I'm not sure where that came from, hopefully there's a discussion somewhere....

>agreement that this can be done by any Arctos User,

Do it. There's a human involved, there's a history, I can't see how this could possibly be a problem. (If I do it I won't look at anything and I'll probably drop constraints and etc.; me updating and you updating are wildly different things.)

>In some ways, there is NO good answer here - no matter what we do, locality will need to be free text and we WILL have multiple versions of "Nothing Interesting To Say". However, I think that Bob's point about NULL should be given a hard look AND it should be applied everywhere. I think we would have far fewer issues if the instructions across the board were "If you don't know or don't have information, just leave it blank".

Correct, "They sell cherry ice cream here" is as good as anything else, but it's not the older-than-Arctos documented value either. I'm happy with what we have, I'm happy with NULL, I'm happy with the ice cream thing (but pistachio is better), as long as we can do one THING, whatever that might be, then this isn't a problem (and it can't not be a problem as long as we refuse to do that one thing).

>. Why would Specific Locality be any different and require an explanation?

The general idea (and the reason that things like Agent Zero exist) is that requiring SOMETHING will lead to better data than allowing things to just be skipped. I'm happy to accept that that is just wrong, but maybe something like https://github.com/ArctosDB/arctos/issues/4384 could provide a more focused/palatable alternative.

**Comment by dustymc** [comment]
Cleaned up some obvious stuff, merging-->https://github.com/ArctosDB/arctos/issues/2662

**Comment by ewommack** [comment]
> The general idea (and the reason that things like Agent Zero exist) is that requiring SOMETHING will lead to better data than allowing things to just be skipped. 

Yep! I think having something is really important. Starting from the data entry where it tells me if the volunteer/student/etc actually entered in data instead of just forgot to fill in the information, to when I download a set of data from a data aggregator where it tells me that no the collection didn't run out of money and didn't fill in their specific localities - there is no info here to get.

**Comment by campmlc** [comment]
I totally agree with this. I've always had an issue with the use of a
required format which is immediately and consistently violated in all the
ways demonstrated. And then we have situations with the use of this term
but with added coordinates, or media, and then these get inappropriately
shared or modified.
