### ISSUE TITLE
Code Table Request - New Identifier Relationship for Botany Collections

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#4825]
**Goal**
New identifier relationship for herbaria collections

**Context**
Some specimens were mounted on the same herbarium sheet as another specimen. None of the current terms/definitions in the ctid_references table best describe the situation. Because the plants are glued to the herbarium sheet, they cannot be separated. We have some historic collectors who have mounted more than one specimen on a sheet.  Because they are glued down, they cannot be separated, even if they were not collected together or have different identifications (either due to mistake or change in taxonomy). We have been keeping track of these specimens in "Part Remarks," but I would prefer a way that links directly to the other specimen(s) through the identifier.

Examples:
https://arctos.database.museum/guid/CHAS:Herb:1895.669.11
https://arctos.database.museum/guid/CHAS:Herb:1895.669.16

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctid_references

**Proposed Value**
"same herbarium sheet as"

**Proposed Definition**
Refers to a cataloged item that is mounted to the same herbarium sheet as another specimen.

**Collection type**
Botany/Herbaria

**Comment by Jegelewicz** [comment]
I'd prefer to make this more generic if possible. Some collections have more than one specimen on a slide (also cannot be separated) and there are other possible scenarios.

How about "same loanable object as"

Refers to a cataloged item that is mounted or associated with the object in such a way that they cannot be physically separated (a loan of one object, requires a loan of all associated objects).

There is also the option of using [Arctos:Entity](https://handbook.arctosdb.org/documentation/entity.html) to create a single "uber" catalog record for the herbarium sheet that then becomes an other ID on the sheet components, but that seems a bit like overkill here?

**Comment by wellerjes** [comment]
> How about "same loanable object as"

This works!

**Comment by Jegelewicz** [comment]
@ArctosDB/arctos-code-table-administrators please weigh in. Also @dustymc

**Comment by dustymc** [comment]
I don't have the bandwidth to really process this now, but we're getting a relatively large pile of "same {thing of some sort}" identifiers that all look interchangeable to me.

**Comment by ccicero** [comment]
I agree with having something more generic, but don't like 'same loanable object as' -the sheet or slide object is loanable as one but the specimen parts are different and it's confusing to say that they are the same loanable object.  I would avoid something that references transactions. 

What about 'mounted on same object as' or 'mounted on same base as' - ? The latter would work for two different taxidermied mounts on the same base, in addition to different specimens mounted on the same slide or herbarium sheet.

**Comment by mkoo** [comment]
quick comment: i like the direction that Teresa (more generic) and Carla (removing 'loanable') are going. 
something like "same base as" or "same as mount as"

And nice thinking to use relationships and not attributes for this!

**Comment by campmlc** [comment]
I like "same mount as" or "mounted with".  Would herbarium folks use this?  It works for two different parasites on a slide, or two taxidermied critters in a display, I assume other objects put together for an exhibit etc.

**Comment by Jegelewicz** [comment]
same mount as may not work for two fossils in the same matrix? @Nicole-Ridgwell-NMMNHS @aklompma

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
This is very similar to the issue we have with paleo specimens where the best term would probably be "same slab as". We could find a more general term that would encompass both "same mount" and "same slab" however the difference between these is that one is an artificial association and the other is a natural association and it might make sense to create them as two different terms. While containers can be used for this, I think there is an advantage in having that explicit relationship between the specimens, especially because it creates direct links in the catalog record.

**Comment by dustymc** [comment]
>artificial association and the other is a natural association 

Excellent point, agreed, even extends to things like necessarily-related data (vs. 'glued together for arbitrary reasons').

If that's the functional distinction, and it looks like it should be, then I suggest vocabulary which reflects that - 'naturally attached' and 'artificially attached' or something of the sort.

>containers

Also agreed, albeit somewhat reluctantly. We've long imagined containers explicitly making these kinds of relationships, but reality keeps leading to the idea that containers are useful for current object tracking and trying to stretch them beyond that doesn't end well.

**Comment by campmlc** [comment]
I agree with using "same mount as" and potentially "same slab as" or "same
matrix as" and keeping the distinction between a natural and an artificial
association. This is similar to "same lot as". Used in different contexts,
conveys different information. And these are different from containers in
that sense.

**Comment by wellerjes** [comment]
> I like "same mount as" or "mounted with". Would herbarium folks use this?

Yes, that works!

> 'naturally attached' and 'artificially attached' or something of the sort.

I like this line of thought; we have some plants that were collected/pressed together (like a vine that wrapped around the stem of the plant) and were mounted together, even though they are different species. Then we have some that were mounted together by someone in 1912 - 1914 who would put different species on the same herbarium sheet (I think because they were from the same place or looked similar), when we would mount these specimens separately today. It would be great to make that distinction in Arctos.

**Comment by Jegelewicz** [comment]
> 'naturally attached'

isn't that [collected with](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctid_references#collected_with)? As I now bring this back full circle to https://github.com/ArctosDB/arctos/issues/1842

OK, I do see a distinction between collected with and permanently attached. Can we nail this down?

naturally attached to - Refers to a cataloged item that is naturally associated with the object in such a way that they cannot be physically separated (a loan of one object, requires a loan of all associated objects). Examples include two species of fossil on a single slab of matrix or a vine that wrapped around the stem of a plant and the two were mounted together.

artificially attached to - Refers to a cataloged item that is artificially associated with the object in such a way that they cannot be physically separated (a loan of one object, requires a loan of all associated objects). Examples include two taxidermy mounts on a single base, two different parasites on a single slide, or two species mounted on a on a single herbarium sheet simply to be economical.

**Comment by ewommack** [comment]
I think we need a term that is more specific then [collected with](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctid_references#collected_with), since the way we currently use collected with is for things that were picked up at the same time, but we are not sure on their exact relationship. I could see using that for a seed someone sampled from the fur of a mammal skin maybe. 

I agree that a natural created relationship versus a collector created relationship seems an important distinction to make some how if we can.

**Comment by campmlc** [comment]
We are confusing the container with the collection objects. This confuses a
relationship ("attached to" e.g. as a parasite to a host) with a position -
attached through some mounting in a collection.
All of this can be eliminated if we use the more precise language in the
relationship fields and define them appropriately. "Same slab as", "Same
mount as".
Perhaps use both "Same slab as" and "collected with" for the fossil.
Use "Same mount as" for the mounted objects such as fleas and exhibit
mounts.
All could share barcodes - indicating shared container objects. But that
would be a separate, optional field.

**Comment by Jegelewicz** [comment]
So what I am hearing is

same slab as
same sheet as
same slide as
same base as

and on to infinity.....

why doesn't

naturally attached to - Refers to a cataloged item that is naturally associated with the object in such a way that they cannot be physically separated (a loan of one object, requires a loan of all associated objects). Examples include two species of fossil on a single slab of matrix or a vine that wrapped around the stem of a plant and the two were mounted together.

artificially attached to - Refers to a cataloged item that is artificially associated with the object in such a way that they cannot be physically separated (a loan of one object, requires a loan of all associated objects). Examples include two taxidermy mounts on a single base, two different parasites on a single slide, or two species mounted on a on a single herbarium sheet simply to be economical.

work?

**Comment by Jegelewicz** [comment]
>  Nobody's going to (or should) go change the relationship after they pry the bryozoan off the clam or saw the bone out of the rock. (Which suggests maybe there's some distinction between 'grew that way' and '... and still stored that way' but that seems overly arbitrary and I hate it.)

perhaps that suggests we need begin and end dates for these relationships?

**Comment by campmlc** [comment]
Two parasites on a slide are not attached to each other, artificially or
otherwise. It is confusing terminology. If anything, they are attached to
the same slide.

**Comment by campmlc** [comment]
They are "mounted with" each other. This is an action performed during
curation. As opposed to an action or event that occurred in nature.

**Comment by campmlc** [comment]
ID metadata

**Comment by Jegelewicz** [comment]
mounted with - Refers to a cataloged item that is artificially associated with the object in such a way that they cannot be physically separated (a loan of one object, requires a loan of all associated objects). Examples include two taxidermy mounts on a single base, two different parasites on a single slide, or two species mounted on a on a single herbarium sheet simply to be economical.

**Comment by campmlc** [comment]
That works.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I'll make a separate thread for the slab/matrix stuff.

**Comment by Jegelewicz** [comment]
> I'll make a separate thread for the slab/matrix stuff.

So we are also shooting down

naturally attached to - Refers to a cataloged item that is naturally associated with the object in such a way that they cannot be physically separated (a loan of one object, requires a loan of all associated objects). Examples include two species of fossil on a single slab of matrix or a vine that wrapped around the stem of a plant and the two were mounted together.

?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I think Mariel's comment about confusing terminology also applies to naturally attached. It makes it seem like the specimens are directly attached to each other as opposed to just being in the same in the same chunk of rock.

**Comment by Jegelewicz** [comment]
> just being in the same in the same chunk of rock.

but there are other things "naturally attached" can we come up with something less specific than same slab as? Maybe not, but I'd like to think about it.

**Comment by Jegelewicz** [comment]
@ArctosDB/arctos-code-table-administrators any issue with this?

**Goal**
New identifier relationship for herbaria collections (broadened to include other collections)

**Context**
Some specimens were mounted on the same herbarium sheet as another specimen. None of the current terms/definitions in the ctid_references table best describe the situation. Because the plants are glued to the herbarium sheet, they cannot be separated. We have some historic collectors who have mounted more than one specimen on a sheet.  Because they are glued down, they cannot be separated, even if they were not collected together or have different identifications (either due to mistake or change in taxonomy). We have been keeping track of these specimens in "Part Remarks," but I would prefer a way that links directly to the other specimen(s) through the identifier.

Examples:
https://arctos.database.museum/guid/CHAS:Herb:1895.669.11
https://arctos.database.museum/guid/CHAS:Herb:1895.669.16

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctid_references

**Proposed Value**
"mounted with"

**Proposed Definition**
Refers to a cataloged item that is artificially associated with the object in such a way that they cannot be physically separated (a loan of one object, requires a loan of all associated objects). Examples include two taxidermy mounts on a single base, two different parasites on a single slide, or two species mounted on a on a single herbarium sheet.

**Comment by dustymc** [comment]
Term seems reasonable, definition needs tightened up.

> cannot be physically separated

Sure they can, but perhaps we won't. Suggest stealing @Nicole-Ridgwell-NMMNHS 's 'additional preparation'

>two species

Not wrong, but perhaps misleading - 'multiple cataloged items' maybe?

Elaborating (maybe by example - 'don't use for bryophytes stuck to clams') on artificially associated might be useful too.

**Comment by Jegelewicz** [comment]
@ArctosDB/arctos-code-table-administrators any issue with this?

**Goal**
New identifier relationship for herbaria collections (broadened to include other collections)

**Context**
Some specimens were mounted on the same herbarium sheet as another specimen. None of the current terms/definitions in the ctid_references table best describe the situation. Because the plants are glued to the herbarium sheet, they cannot be separated. We have some historic collectors who have mounted more than one specimen on a sheet.  Because they are glued down, they cannot be separated, even if they were not collected together or have different identifications (either due to mistake or change in taxonomy). We have been keeping track of these specimens in "Part Remarks," but I would prefer a way that links directly to the other specimen(s) through the identifier.

Examples:
https://arctos.database.museum/guid/CHAS:Herb:1895.669.11
https://arctos.database.museum/guid/CHAS:Herb:1895.669.16

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctid_references

**Proposed Value**
"mounted with"

**Proposed Definition**
Refers to a cataloged item that is artificially associated with the object through preparation in such a way that they cannot be easily physically separated (a loan of one object, requires a loan of all associated objects). Examples include two taxidermy mounts on a single base, two different parasites on a single slide, or two cataloged items mounted on a on a single herbarium sheet.

**Comment by ccicero** [comment]
I'm good with this value and definition (mostly), but don't like word 'artificially' here. What about 'manually' - ?

**Proposed Definition**
Refers to a cataloged item that is manually associated with the object through preparation in such a way that they cannot be easily physically separated (a loan of one object, requires a loan of all associated objects). Examples include two taxidermy mounts on a single base, two different parasites on a single slide, or two cataloged items mounted on a on a single herbarium sheet.

**Comment by campmlc** [comment]
Suggested tweak on Carla's version: 

Proposed Value
"mounted with"
****
Proposed Definition
Refers to a cataloged item that is physically associated with the specified object **through preparation** in such a way that they cannot be easily separated (a loan of one object, requires a loan of all associated objects). Examples include two taxidermy mounts on a single base, two different parasites on a single slide, or two cataloged items mounted on a on a single herbarium sheet.

**Comment by Jegelewicz** [comment]
Suggest adding:

@ArctosDB/arctos-code-table-administrators any issue with this?

**Goal**
New identifier relationship for herbaria collections (broadened to include other collections)

**Context**
Some specimens were mounted on the same herbarium sheet as another specimen. None of the current terms/definitions in the ctid_references table best describe the situation. Because the plants are glued to the herbarium sheet, they cannot be separated. We have some historic collectors who have mounted more than one specimen on a sheet.  Because they are glued down, they cannot be separated, even if they were not collected together or have different identifications (either due to mistake or change in taxonomy). We have been keeping track of these specimens in "Part Remarks," but I would prefer a way that links directly to the other specimen(s) through the identifier.

Examples:
https://arctos.database.museum/guid/CHAS:Herb:1895.669.11
https://arctos.database.museum/guid/CHAS:Herb:1895.669.16

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctid_references

**Proposed Value**
"mounted with"

**Proposed Definition**
Refers to a cataloged item that is physically associated with the specified object through preparation in such a way that they cannot be easily separated (a loan of one object, requires a loan of all associated objects). Examples include two taxidermy mounts on a single base, two different parasites on a single slide, or two cataloged items mounted on a on a single herbarium sheet.

**Comment by Jegelewicz** [comment]
Code Tables says go

**Comment by Jegelewicz** [comment]
added
