### ISSUE TITLE
Distinguish different TYPES of media on Specimen Results table (via differing icons)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ArctosDB/arctos#485]
```
Now that we have more than one type of media and links associated with 
specimens (eg. fieldnotes, images, publication, project, external links to 
GenBank) it would be more useful to have icons representing the types to show 
up in the specimen results table instead of a generic 'media' that shows up 
now. Thus users can see immediately which specimens have images, fieldnotes, or 
GenBank links associated with it.

This was suggested by multiple people once they started seeing specimen detail 
pages with multiple media associated with it.
```

Original issue reported on code.google.com by `koomap...@gmail.com` on 13 May 2011 at 12:29

**Comment by dustymc** [comment]
Needs more discussion. Considerations:

- cost vs. benefit - the more stuff we process the more we tax our servers. The more data we send, the more we tax connections. Changing 'media' to 'image' isn't significant, but...
- cardinality - what happens when there are (pick a number - dozens is likely, anything is possible) of media, or media-types, or whatever we're counting, for a specimen?
- usability - Icons are generally evil, see for example http://ux.stackexchange.com/questions/1795/when-to-use-icons-vs-icons-with-text-vs-just-text-links. I'm not sure text is better - "image" is completely nondescriptive - we have images of whole specimens and labels and multi-specimen labels and writing and diagnostic characters and .....
- Users can already turn on Media and see what's there in detail without clicking through to the specimen. Those who aren't interested in Media can completely avoid this.

I'm not willing to discuss TAGs until #695 is resolved; it may merge TAGs into "normal" media making special handling irrelevant.
