### ISSUE TITLE
Feature Request - move VERBATIMAGENTS outta attributes

### ISSUE THREAD

**Issue by jebrad** [ArctosDB/arctos#4870]
I would like my VERBATIMCOLLECTORS and VERBATIMPREPARATORS to be visible along with the other agent-like-data for that record (so they are visible in the Agents tab or Other IDs tab?). Right now they are stored among the Attributes, so hard to see.

Related to #4554 - I am TRYING to "do more with with verbatim agents" and this change would help me avoid making agents of the low-quality ones.     I think what I'm asking actually helps you move forward with 4554, not prevent it, but I might be confused there.

Also related to my #4270.

I think I might have scared you Dusty when I requested these be moved to Agents tab -  after more thought the Identifiers aka "Other IDs" is probably a better place.

**Describe what you're trying to accomplish** 
Do more with verbatim agents.

**Describe alternatives you've considered**
Having VERBATIMs are harder to see when they are among the attributes.

**Priority**
Important but not urgent.

Thank you!

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/4869

You didn't scare me, you got me all excited - I think the cleanup that happened in that thread is inevitable overwhelming evidence that there's a better path, but it was apparently deemed scary at some meeting so we're still wading around neck-deep in low-information agents (and the occasional not-so-low that we can't find for the mess). Anything that might get us moving in that direction has my support, but at the same time if that path is not something we'll ever go down then I'd rather not invest a bunch of work in something that's not going to be accepted. (Or, if we can't do the obvious then maybe we should be looking for other solutions instead of just hanging out here hoping we don't drown.)

**Comment by Jegelewicz** [comment]
I am reopening because I think that Verbatim should go beneath (and be less prominent than) actual Agents.

![image](https://user-images.githubusercontent.com/5725767/182651134-3d059861-6b2c-4cdc-9136-6f390f02336a.png)

I'd prefer to have verbatim be less visible when there is an agent selected - in the same way we make verbatim locality less visible.

![image](https://user-images.githubusercontent.com/5725767/182651346-b04cbf33-05fe-4e41-b3f9-d25d54334c6e.png)

It is smaller font and below the selected locality.
