### ISSUE TITLE
Agent download

### ISSUE THREAD

**Issue by lin-fred** [ArctosDB/arctos#4907]
Looking for NMMNH agent data. 
NMMNH:Bird
NMMNH:Ento
NMMNH:Herb
NMMNH:Herp
NMMNH:Inv

I know I can download all of my record data from a collection, isolate the agents and remove duplicates, but is there no way Arctos can't do those steps for me? Could this also be a TURD report in the future? @dustymc

**Comment by Jegelewicz** [comment]
Go to agent search and only search for agents used by each collection

![image](https://user-images.githubusercontent.com/5725767/182966829-824a5ec9-c0fe-4886-b77d-d93883744e5d.png)

**Comment by AJLinn** [comment]
I was going to suggest this also. Is there a way to download that list though?

**Comment by dustymc** [comment]
Hu, neat!

Looks like that considers collectors and transactions. https://arctos.database.museum/tblbrowse.cfm?tbl=agent lists other direct links, I can add whatever is necessary/useful.

Indirect links - the stuff that sort of fades off into infinity somewhere past the agent related to the agent related to the agent related to the agent who made an unaccepted identification on a record related to a record related to a record that shares a publication with a record in your collections - aren't so trivial, and hopefully nobody cares....

The docs (which I can't see while my update is grinding) should be explicit about whatever that ends up considering.

I can pull data (and maybe turn that into a download), I just need to know what "columns" are needed.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
It would be helpful to get the record count in the download, that way if you are cleaning agents you can prioritize the ones that are used most frequently.

![image](https://user-images.githubusercontent.com/47402809/186954271-e94766ec-8485-4251-8980-90a89aa4aec7.png)

**Comment by dustymc** [comment]
I think I have some useful insight from https://github.com/ArctosDB/arctos/issues/4930

1. This needs to be a separate app (or maybe just a script that I can run on request) - having everything in a collection (or some significant subset of it) together is EXTREMELY useful. In all of Arctos a B. Jones and a Bob Jones would be ignored, when they're already in the context of 'same collection' then adding 'collecting similar things at similar times' is strong evidence that they're the same person, particularly when it's accompanied by hundreds of other similar records. The agent search will (potentially) avoid that - you won't search for "simth" so you won't get the typos, which are hard to miss in the full pull.
2. Preferred name gets a column because obviously
3. Agent type gets a column, it's a decent indication of quality (lots of 'other agents' seem to be attempts to bypass the rules around persons - ugh...)
4. Last name gets a column, it's the sort that will get B. Jones and Bob Jones near each other.
5. other names gets squished into a column, it's handy (that B. will often have a "Bob" name somewhere) but the structure isn't terribly important; sorting by random stuff that ends up here can't lead anywhere useful.
6. related_to gets a column - useful flag of the 'good' agent when a typoswarm is encountered
7. related_from gets a separate column - this might only make sense if you're changing things faster than they're getting merged, but it was useful for me
8. addresses gets a column - I've only used this for "has=good, lacks=suspect," maybe it'll need something else later, for now this seems to work
9. status gets a column, same use as address

@lin-fred is that a reasonable starting point?

**Comment by Jegelewicz** [comment]
> other names gets squished into a column, it's handy (that B. will often have a "Bob" name somewhere) but the structure isn't terribly important; sorting by random stuff that ends up here can't lead anywhere useful.

Separating first and middle names into columns can really help with the discovery of closely spelled names.

**Comment by lin-fred** [comment]
I think adding first and middle name columns would be helpful too, so that someone wouldn't have to data manipulate to look the preferred name to sort. I think those items are mostly what an agent might have and what we all use first when we put on our detective hat.

@dustymc I think the columns you have stated are great! I like the idea of addresses, statuses etc all being in their own column. Would we also be able to get a column(s) that list the table that Nicole linked as well?

**Comment by dustymc** [comment]
There's code in migration/__agent_report.sql and Reports/agent_report.cfm - I've got to pause this for a bit.

**Comment by dustymc** [comment]
Next release:

<img width="527" alt="Screen Shot 2022-09-19 at 1 37 12 PM" src="https://user-images.githubusercontent.com/5720791/191111916-98365a3e-808f-4c07-8fdd-1d9d32a75d89.png">

This also establishes a backbone from which various slow and/or expensive reports can be run on demand.

**Comment by lin-fred** [comment]
Thanks Dusty!

**Comment by ewommack** [comment]
@dustymc - is this still on pause?
