### ISSUE TITLE
Code Table Request - add species Glaucomys oregonensis

### ISSUE THREAD

**Issue by jebrad** [ArctosDB/arctos#4915]
**Goal**
Add Glaucomys oregonensis as a species, currently it is only a subspecies.   We have several of the specimens used by Arbogast et al to describe the new species

**Context**
[Arbogast et al 2017pdf.pdf](https://github.com/ArctosDB/arctos/files/9285980/Arbogast.et.al.2017pdf.pdf)

**Priority**
Medium (cannot see any labels to my Right)

Not sure if this is the correct way to request this.... 
Thanks.

**Comment by cjconroy** [comment]
https://academic.oup.com/jmammal/article/98/4/1027/3807034

Jeff should be able to add Glaucomys oregonensis to the code table. He should be able to add whatever names to his collection he feels like, just as the rest of us should be able to as well. We won't always agree on taxonomy. Just because someone wrote a paper doesn't mean it is accepted by everyone, or are ready to change their entire collection.

**Comment by Jegelewicz** [comment]
@cjconroy I plan to add it - I just need to figure out what relationships it should have to other names too. Anyone can request access to edit taxonomy!

**Comment by Jegelewicz** [comment]
Added
