### ISSUE TITLE
Test of how to use the shapes listed in #2374

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#4928]
Per https://github.com/ArctosDB/arctos/issues/2374, you can create a shape for a long list of localities.  

Can we start with:  seavox_areas   | INDIAN OCEAN|PERSIAN GULF
which we can use for https://arctos.database.museum/guid/DMNS:Inv:23409 and https://arctos.database.museum/guid/DMNS:Inv:3041
Current higher geography: 10007527

We can also use  eez_land_union | Andaman and Nicobar|Andaman and Nicobar|India|Union EEZ and country for six records.

And we have lots of specimens from Guam (No specific locality recorded.)  eez_land_union | Guam|Guam|United States|Union EEZ and country

Are you proposing to add all of these or only on request?
Will this attach a shape file to the existing higher geography or create a new higher geography?
Is there a csv I should create to request this?  Do I make a request each time? 
Is there a place where we can save the long list in [#2374]( https://github.com/ArctosDB/arctos/issues/2374)?  
Is this higher geography from which I can create a specific locality?

**Comment by dustymc** [comment]
https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=10007527 now does have spatial data and does not have a continent.

https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=4982 is "mini-Guam," I stripped Pacific Ocean out, I think that's what we agreed on.

https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=10016359 is newly-created Mega-Guam


@mkoo @sharpphyl @Jegelewicz let me know if we're on the same page with this plz.

One consideration is the geog looker-upper - a couple minutes ago, you could feed it "guam" mixed in with whatever nonsense, and it would find our Guam, which is generally also mixed in with whatever nonsense (Marianas, which I left out of Mega Guam because - well, mega...). This will break that; the looker-upper should now find two Guams, and nobody who's not intimately familiar with Arctos - and this particular issue - and maybe not even then - is going to be able to tell which one is appropriate.

I sorta think I want to add a "category" (dirt, water, borders, etc.) of some sort, but IDK if that'd make things better or worse.

**Comment by Jegelewicz** [comment]
I don't think I can make an informed comment. When I look at Guam vs. Guam I know there should be a difference, but I don't see any map on the second one I guess because nothing is using the geography.

**Comment by dustymc** [comment]
It's there but you have to scroll when its not being used. (And you can remove the points in the edit screen.)

guam

<img width="1216" alt="Screen Shot 2022-08-11 at 3 39 41 PM" src="https://user-images.githubusercontent.com/5720791/184254382-6f56f0fa-ddef-4551-95b0-eeb69b73fccc.png">


MEGAGUAM
<img width="524" alt="Screen Shot 2022-08-11 at 3 38 07 PM" src="https://user-images.githubusercontent.com/5720791/184254250-4c96a0d2-83b8-4436-86c5-bbe828666101.png">

**Comment by Jegelewicz** [comment]
So some (or maybe all) of @sharpphyl DMNS molluscs will need to get moved to the new Guam?

**Comment by dustymc** [comment]
>moved

<img width="682" alt="Screen Shot 2022-08-12 at 7 29 11 AM" src="https://user-images.githubusercontent.com/5720791/184385946-ed8c2184-c515-43e5-a6c1-971e8a58cb0e.png">

will help find candidates for moving (to somewhere; it's possible some of these are just REALLY lost and georefererenced to Nebraska or something instead of "MEGAGUAM") from miniguam.

<img width="664" alt="Screen Shot 2022-08-12 at 8 16 07 AM" src="https://user-images.githubusercontent.com/5720791/184386216-31f41282-263d-4bd8-a9be-a532515eca50.png">

will find candidates no matter how they're currently organized. Some of them are probably better in 'miniguam' - this is a clear place where having some sort of organization (eg hierarchy) would be nice - the current schema allows for any and all overlaps, so "is within this" doesn't preclude "is also within something else."

**Comment by sharpphyl** [comment]
I'm just starting to understand this.  I took the locality in our record https://arctos.database.museum/guid/DMNS:Inv:29764 which is collected off Anae Island off Guam, at 30-35 meters depth by SCUBA and I changed the higher geography in the locality from United States, Guam to your Mega Guam in the Pacific Ocean.  So here's the before where the point is (I think) just outside the boundaries...

<img width="666" alt="Screen Shot 2022-08-16 at 7 26 18 PM" src="https://user-images.githubusercontent.com/15368365/185014634-9ba9efa5-4743-4fe3-b39c-9dcd7160e35d.png">

and here's the after.  Now the center point is within the boundaries, so it shouldn't generate a notification.  I have no idea which is better in terms of finding the specimen in Arctos or at aggregators.  

<img width="718" alt="Screen Shot 2022-08-16 at 7 27 26 PM" src="https://user-images.githubusercontent.com/15368365/185014881-6229e7e3-6c20-4408-bbf6-0e9b71efd7f1.png">

GBIF made a lot of changes in this record: https://www.gbif.org/occurrence/1913890009

If it matters, Harvard uses Pacific Ocean: Pacific, Western Central: United States: Northern Mariana Island and Guam, and the Water Body Pacific, Western Central in a similar record in GBIF - https://www.gbif.org/occurrence/1436121070.  So we're more in sync with their approach with the Mega Guam.  GBIF seems to just use Guam as the Country (if I'm reading it correctly).  I don't see any obvious answers in what either of them does.  Guam is actually in Micronesia but politically it's in the U.S., so where to put it will probably always be problematic.

So do this seems to make sense to others as one way to deal with Marine localities?  It would seem a mega project to make all these changes - even over time - at least until we feel we better understand what direction GBIF may be heading, but this does seem to work and I'm happy to start the transition process if Dusty's up for making more of these EEZs as they are needed.  

Thoughts?

**Comment by Jegelewicz** [comment]
> If it matters, Harvard uses Pacific Ocean: Pacific, Western Central: United States: Northern Mariana Island and Guam, and the Water Body Pacific, Western Central in a similar record in GBIF - https://www.gbif.org/occurrence/1436121070. So we're more in sync with their approach with the Mega Guam. GBIF seems to just use Guam as the Country (if I'm reading it correctly). I don't see any obvious answers in what either of them does. Guam is actually in Micronesia but politically it's in the U.S., so where to put it will probably always be problematic.

![image](https://user-images.githubusercontent.com/5725767/185153125-13379e2e-7780-4615-8fde-c4c4e9d52dd4.png)

One thing I DO know is that both GBIF and iDigBio use the [ISO country codes](https://www.iso.org/iso-3166-country-codes.html). In ISO, [Guam](https://www.iso.org/obp/ui/#iso:code:3166:GU) is a country, but also listed as a subdivision of the United States. When thinking about how people might use this, I could see someone wanting to get at everything from the political entity "United States of America" (which, by the way is the "official" name of the country) or just things in the 50 actual states, or things just in the lower 48. Anyone using United States as a search tool should beware. However, people also may never look for Guam in the "state" field and if they search it in "country" in Arctos they will get exactly nothing. This seems like a bad thing but I am also not sure what to do about it - synonyms in geography?

> So do this seems to make sense to others as one way to deal with Marine localities?

Seems better than what we were doing internally, not sure it makes one lick of difference at the aggregators.

**Comment by Jegelewicz** [comment]
@sharpphyl totally off topic, but in https://arctos.database.museum/guid/DMNS:Inv:29764 the collector is listed as unknown, but the record indicates that you do know?

![image](https://user-images.githubusercontent.com/5725767/185163015-29eb6c21-c8fb-4dd9-bc95-b9d85ab59907.png)

![image](https://user-images.githubusercontent.com/5725767/185163679-71d976fb-6219-47d1-8781-6c68c767513b.png)

I've been working on agents A LOT so this caught my eye...

**Comment by dustymc** [comment]
>better in terms of finding the specimen 

FWIW if I was trying to make some spatial analysis:

1. I'd search by this stuff - I'd bring my own shapes, or I'd use what GBIF uses. Finding that Arctos has a bunch of stuff that doesn't have spatial data, or that localities don't always use appropriate data, or that we arbitrarily use a bunch of arbitrarily-mixed geography terms wouldn't stop me, but it would make me a little paranoid.

<img width="647" alt="Screen Shot 2022-08-17 at 6 55 24 AM" src="https://user-images.githubusercontent.com/5720791/185152366-98e796a3-ac3a-4073-b8f4-1ba04c956e5a.png">

2. I'd then toss out anything that just outright says it can't be correct. https://arctos.database.museum/Reports/cat_record_reports.cfm?report_name=locality:%20georeference%20does%20not%20intersect%20geography are the most obvious, but then I'd move on to 'is not contained.' I would never check where one point is - Arctos contains no point-only data, it's irrelevant, I'd be looking at shapes (including those produced by point-radius).  "Might not be horribly wrong" is the best possible interpretation of the geography not fully containing the locality, and that doesn't exactly inspire confidence.

(Note that in no circumstances would I consider anything that's not georeferenced - https://github.com/ArctosDB/arctos/issues/4916)

So, from just that

1. What you name the thing isn't important (it might be if there was some consistency in the data and I might be able to predict how records were related to names, but there's not and I can't so I wouldn't try).
2. I would prefer 'contained by big shape' over 'intersects small shape.'

>GBIF

GBIF magicked a datum out of thin air and decided that my confirmed-valid WKT isn't valid (but to be fair it's WKT so....). The record is licensed so they can do WHATEVER they want, I'm never quite sure why we're surprised and appalled when they do just what we've told them they can do??

>actually in Micronesia but politically it's in the U.S.,

That's why I've been advocating for 

1. Just do whatever our source of spatial data does (which is where GBIF gets the country), or
2. Separate political and geographic (and somehow scrounge up data to support that)

(I'm not actually that picky, I'll jump behind just about ANYTHING more consistent than our 'Continent, Ocean which isn't on the continent, sea which also isn't on the continent, island which shares space with none of the continent, ocean or sea, country which used to administer from halfway around the world, drainage for which we'll never have spatial data, county which may be partially within the drainage, quad which bisects the county, feature which may or may not intersect with the county at all' mess! And now we want to add 'lake in the feature!!')

>mega project to make all these changes

https://arctos.database.museum/Reports/cat_record_reports.cfm?report_name=locality:%20suboptimal%20geography - I still don't know if I can trust your georefeference, but I can come up with geography which fits your georeference. (I've also been attempting to advocate for 'just let the machines handle it' but I'm not sure I've been able to pinpoint anything that they can do very well - let me know if you see something...)

>Dusty's up for making more of these 

A clarification, I hope: I'm not "making" shapes, I'm just using them. (Missing from that: I think we are NOT being consistent in assigning names to - using - those shapes, there will never be a time better than now to change that, plz halp.) I am relatively happy to use whatever I can scrounge up - it'll be about the same thing as everyone else is using. The EEZs are kinda OK for small countries, not so great for large (screenshots below). An alternative to that would be to have @mkoo cook up custom shapes, which might work OK locally but would virtually **guarantee that our data will not be consistent with the expectations of things like GBIF**. I'll 100% take that over not having shapes at all, but it is us making a decision to silo ourselves off from the rest of the world (unless The World starts using our shapes, which doesn't seem likely).


-------------------------


Country+EEZ examples:


Russia
<img width="624" alt="Screen Shot 2022-08-17 at 7 42 14 AM" src="https://user-images.githubusercontent.com/5720791/185167880-ce3268df-f8aa-4ad5-b0d3-d0baa9b9ca7e.png">

US

<img width="762" alt="Screen Shot 2022-08-17 at 7 43 26 AM" src="https://user-images.githubusercontent.com/5720791/185168247-c559bdf9-fd53-4ec6-a117-8d685174d0e3.png">


Canada
<img width="489" alt="Screen Shot 2022-08-17 at 7 43 52 AM" src="https://user-images.githubusercontent.com/5720791/185168582-82719075-8aed-4dc9-bb86-016663e4c339.png">



--------------------------

Aforementioned definitely-valid WKT:
```
arctosprod@arctos>> select st_isvalid(ST_GeographyFromText(footprintwkt)::geometry) from  ipt_cache.occurrence where occurrenceid like '%DMNS:Inv:29764%';
 st_isvalid 
------------
 t

```

**Comment by sharpphyl** [comment]
@Jegelewicz 

> @sharpphyl totally off topic, but in https://arctos.database.museum/guid/DMNS:Inv:29764 the collector is listed as unknown, but the record indicates that you do know?

Not really, but probably there's a better way to describe Richard Schaake.  Our curator wants the collector to be the person who picked up the shell.  Arctos defines collector to also include the person who brought together the collection which was Schaake.  Schaake bought every specimen in his collection, so the "collector" who picked up the shell is unknown.  The number that Schaake assigned to the specimen is referred to as the "collector number."  It probably could be "other identifier" but we use that for number from a previous DMNS catalog system.  

Comments and suggestions are welcome.

@dustymc   I need some time to absorb your reply but I see some good ideas....

**Comment by Jegelewicz** [comment]
> the collector to be the person who picked up the shell. Arctos defines collector to also include the person who brought together the collection which was Schaake. Schaake bought every specimen in his collection, so the "collector" who picked up the shell is unknown.

Yeah - I went digging around in his agent and kinda suspected that. The reality is there are two collecting events - one where "unknown" picked up the shell and one where Schaake purchased it (I guess still a collecting event, just one that was "captive"?). Maybe more details than anybody cares about? Still it does appear odd to people from the outside and perhaps just changing the collector number to something else might clarify things (although the comment about collector notes in the attribute is also a point of possible confusion). Honestly, I'm guessing nobody really cares and this is just fine the way it is.

**Comment by sharpphyl** [comment]
And if it helps, the Record/Event Remark is "Schaake purchased most specimens between 1980 and 2011. Purchased from Showcase Shells."

**Comment by sharpphyl** [comment]
@dustymc I'm still working through your comment, but this morning I noticed this "error report" on the [Guam record ](https://arctos.database.museum/guid/DMNS:Inv:29764)where I modified the locality to use our Guam EEZ.   Not sure why this happens but it's confusing.  Before I change more of the "offshore Guam" records, can we figure out a way to make this automation service happy about the higher geography we've chosen for this locality?

<img width="1392" alt="Screen Shot 2022-08-19 at 9 34 39 AM" src="https://user-images.githubusercontent.com/15368365/185655672-504164a6-6f45-4f30-be46-dddb331cae31.png">

Someone has complained about these being public notices rather than internal only and I agree.

**Comment by dustymc** [comment]
>Not sure why this happens

There is (was) a more-precise geography which entirely contains your georeference available.

>public

The notices are absolutely critical for understanding things like fitness for use. If we're [allowing nonsense data](https://github.com/ArctosDB/arctos/issues/4289), and we have the tools to know which data is nonsense, I think we have an obligation to share that.

One big-picture way to remove the notices - by removing the problems rather than by hiding known-bad data - would involve something like https://github.com/ArctosDB/arctos/issues/4916 (let me georeference whatever isn't) plus https://github.com/ArctosDB/arctos/issues/4785 (let me pick the most appropriate geography for the georeferences). That would result in nothing conflicting with itself, and would let the humans focus on the things that need it, rather than things that machines can handle just fine.

All that said, that particular error is:

>Locality [10944694](https://arctos.database.museum/place.cfm?action=detail&locality_id=10944694) is using geography [United States, Guam, Mariana Islands](https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=4982); [Pacific Ocean, United States, Guam](https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=10016359) is a better spatial fit.

and the record is using the suggested geography - you've already done what it's asking for, it will delete itself eventually or you can delete it - I did.
<img width="339" alt="Screen Shot 2022-08-19 at 9 00 50 AM" src="https://user-images.githubusercontent.com/5720791/185659907-da30ba70-e8fd-41b2-bc0b-3d53ec20a4f8.png">

**Comment by sharpphyl** [comment]
> or you can delete it - I did.

Thanks. I'll wait a bit longer before becoming concerned in the future.
