### ISSUE TITLE
Need Help with Arctos Error - Bulk Edit Container

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#4964]
# Error Text
load fail::ERROR: new row for relation "container" violates check constraint "ck_label_noprint" Detail: Failing row contains (15240221, 21724221, cryovial, NK 283667 MCF 177 H Bucephala albeola , null, 2022-08-22 16:01:26.1015, null, MSB1011756, null, null, null, null, MSB, null, null, null, null). 

# Where it happened
https://arctos.database.museum/tools/bulkEditContainer.cfm

# Steps to get there
Load this file

[bulkloadEditContainer(3).zip](https://github.com/ArctosDB/arctos/files/9397886/bulkloadEditContainer.3.zip)

# Problem
**Community response to describe the problem that caused the error**

# Solution
**Community response with directions for how to correct the problem**

**Comment by campmlc** [comment]
I see no "NO PRINT" character when I open this file in text editor.

**Comment by dustymc** [comment]
https://handbook.arctosdb.org/documentation/understanding-errors.html#error-row-for-relation-table-violates-check-constraint-ck_column_noprint
<img width="200" alt="Screen Shot 2022-08-22 at 3 12 20 PM" src="https://user-images.githubusercontent.com/5720791/186027851-f04e772c-36f3-4d9c-ba38-4be9637d0f99.png">

**Comment by campmlc** [comment]
How do you find these? Is there a tool? There are 946 rows, of which only a few had the extra space. Obviously I didn't scroll through and scrutinize all 946. Surely an easier way?

**Comment by campmlc** [comment]
Any way for the Arctos error to highlight the actual error in the error message, or parse the message so it only shows the error?

**Comment by dustymc** [comment]
> see no "NO PRINT" character 

FYI lots of them are not visible in lots of tools. (This is a decent example - my [replace](https://github.com/ArctosDB/PG_DDL/blob/master/function/replaceFreeText.sql) function does OK with vertical tabs and such, but I don't have any way to indicate 'replacing' a trim - in most column-view UIs the input looks just like the output, a text editor is about the only place to actually see the problem, and it can be mixed in with apparently-identical nonproblematic strings.)

>How do you find these? 

Use the same [function](https://github.com/ArctosDB/PG_DDL/blob/master/function/checkFreeText.sql) that the check constraints use.


My text editor (sublime) has regex, but the problem here is a trailing space so you can just search for `` ,`` (space-comma) (which isn't a problem - or a detectable problem, anyway - if its in text, but here its with the separator).

If you want to use Arctos, you can...

<img width="346" alt="Screen Shot 2022-08-23 at 7 13 45 AM" src="https://user-images.githubusercontent.com/5720791/186182887-27b9cf4d-5e97-4dfe-b952-7d66b3cb2221.png">

<img width="191" alt="Screen Shot 2022-08-23 at 7 14 04 AM" src="https://user-images.githubusercontent.com/5720791/186182909-027551bc-de5c-4ca6-91c6-99ecc4fe1bca.png">

<img width="195" alt="Screen Shot 2022-08-23 at 7 14 14 AM" src="https://user-images.githubusercontent.com/5720791/186182928-3d58d521-f0fa-46b7-9c20-9865f8d1716e.png">


```
select label from temp_cache.temp_dlm_uptbl  where checkfreetext(label) is false
```

>Surely an easier way?

Use the UI tools. The bulk tools are powerful, but they also requite a level of attention/knowledge/something that the UI generally doesn't.

>highlight the actual error 

Definitely not a "no" but some flavor of "lots more resources" - it would somehow be more complicated/expensive/etc. than feeding a text file to PG's native very high performance (but a little twitchy) loader.

**Comment by campmlc** [comment]
This would be good to add to an issue or workflow that describes how to find "NO PRINT" characters - do we have one?

**Comment by campmlc** [comment]
Or somehow link related issues to the Handbook entry ?

**Comment by Jegelewicz** [comment]
I have added [my Excel solution](https://handbook.arctosdb.org/documentation/understanding-errors.html#ck) to the error documentation. Perhaps that will help?
