### ISSUE TITLE
Feature Request - ability to download agents associated with collection

### ISSUE THREAD

**Issue by droberts49** [ArctosDB/arctos#4973]
With the interest in improving agent records, I would like to be able to download a list of agents associated with each of our collections.

Could a download option be added in the agents search page [https://arctos.database.museum/agents.cfm]? It's possible to search for agents associated with a collection [selecting collection under "used by collection"], which is one step already present. Could a way to download this list be added please?

**Comment by wellerjes** [comment]
Addendum: Indicating if the agent is shared by multiple collections is not necessarily needed for the download. I think it would be useful to see it on the "Manage Agents" page. Right now, the collecting summary only shows specimens related to your collection:
![image](https://user-images.githubusercontent.com/93737929/186454911-6da4f72a-ace3-4d25-be6f-5f58e47c5a6c.png)

It would be useful to have this (from the "Agent Activity" page (or an abbreviated version of it) appear on the "Manage Agents" page. That way the information is available without having to click back and forth between pages.
![image](https://user-images.githubusercontent.com/93737929/186455185-0077d33f-4922-4b7b-92bb-57e388f71422.png)

**Comment by dustymc** [comment]
Please redirect the download bits to https://github.com/ArctosDB/arctos/issues/4907 - it's not problem, but I need to know (precisely, eventually) what is meant by "associated," and then I'll need to know what the download should look like.

(I suspect that's going to take more power than I can conjure for that form and will involve building a new app - we can evolve and iterate either way, but I need a general idea of the current collectors+transactions mostly does what you need, or if you're looking for something more along the lines of https://github.com/ArctosDB/arctos/issues/4907#issuecomment-1205879642.) 

>Right now, the collecting summary only shows specimens related to your collection:

Going active with this issue for that.

**Comment by ewommack** [comment]
> Addendum: Indicating if the agent is shared by multiple collections is not necessarily needed for the download. I think it would be useful to see it on the "Manage Agents" page. Right now, the collecting summary only shows specimens related to your collection

If you log out and log in again you can see multiples. If you are selecting an agent in a transaction field you can now also see multiple different collections that may be associated with the agent as well as the year when the specimens are associated with.

@wellerjes 
If you think an Agent should be split, but you are not sure because it occurs in multiple collections, there is an issue for that. Fill out: https://github.com/ArctosDB/arctos/issues/new?assignees=&labels=Function-Agents&template=agent-split-request.md&title=Agent+Split+Request
If you think an Agent needs to be merged with another, but it affects another collection you can fill out this issue: https://github.com/ArctosDB/arctos/issues/new?assignees=&labels=Function-Agents&template=agent-merge-request.md&title=Agent+Merge+Request

**Comment by Jegelewicz** [comment]
> If you log out and log in again you can see multiples.

OR you can just view the public page:

![image](https://user-images.githubusercontent.com/5725767/186763025-3e232e7b-1527-40c9-ac84-3013ce3eb6b4.png)

**Comment by ewommack** [comment]
> OR you can just view the public page

Ah I totally forgot that @Jegelewicz! Thanks for the tip :)
