### ISSUE TITLE
Enhancement - Ability to select a common name for a collection

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5025]
> We primarily use this field for common names: a) pulling the common name for our labels and b) being able to see the common name in search results.

Common names should be added to the taxon name - but I can also see how some taxa have hundreds of common names and maybe you only want one of them... Not sure what would be the best way to get to this!

_Originally posted by @Jegelewicz in https://github.com/ArctosDB/arctos/issues/4922#issuecomment-1240844893_

**Comment by Jegelewicz** [comment]
Some collections use common names on labels and like to see them in search results. Some have found roundabout ways to get this as stated above. BUT we have a place for common names that the entire community can share and when sideways methods are used to add common names to records, the community misses out. We need to think about the best method for allowing a collection to select one or more of the potential common names for a given taxon that it prefers. Give me some ideas!

**Comment by dustymc** [comment]
>Move them to classifications where they'll accompany the other preferred data.

(This probably also means creating a 'legacy Arctos common names' classification to hold what's currently attached to the taxon.)

**Comment by Jegelewicz** [comment]
@dustymc what happens on a catalog record with a taxon when there are tons of common names?

**Comment by dustymc** [comment]
Whatever ya'll want - that's "just UI." (Currently nothing, and if something is wanted then you'll need to be careful with the term type, but that should be trivial in the current bulk tools.)

**Comment by Jegelewicz** [comment]
@dustymc can you tell me which name has the most associated common names?

**Comment by dustymc** [comment]
https://arctos.database.museum/name/Thunnus%20albacares

**Comment by Jegelewicz** [comment]
@ArctosDB/taxonomy suggests this as a solution:

Ability to rank common names (add a rank column here)
![image](https://user-images.githubusercontent.com/5725767/189199494-2de29c66-b7da-4514-8fa5-4c7388633571.png)

Pick a number - probably between three and five that will appear on catalog records (so we don't have 50 of them there, but we can still facilitate search by common name - "just UI")

We think this will allow us to continue to use common names for discovery, but limit them so that putting common name on a label would only get a few (or maybe you could pick the rank you want to use when getting data for labels)?

What did I miss?

**Comment by Jegelewicz** [comment]
We also talked about an attribute in identifications "common name" that would be constrained by the list of common names for the name used as the identification, but that sounds really complicated?

**Comment by dustymc** [comment]
>used as an id?


```

     scientific_name     | ncn 
-------------------------+-----
 Lota lota               | 102
 Cephalopholis sonnerati | 102
 Belone belone           | 104
 Carcharias taurus       | 106
 Phycis blennoides       | 111
 Hexanchus griseus       | 113
 Galeocerdo cuvier       | 114
 Squalius cephalus       | 121
 Trachurus trachurus     | 121
 Carcharodon carcharias  | 122
 Myliobatis aquila       | 123
 Balistes capriscus      | 127
 Echeneis naucrates      | 128
 Terapon jarbua          | 129
 Albula vulpes           | 130
 Galeorhinus galeus      | 140
 Prionace glauca         | 146
 Caranx hippos           | 148
 Xiphias gladius         | 152
 Sphyraena barracuda     | 153
 Alopias vulpinus        | 155
 Isurus oxyrinchus       | 164
 Squalus acanthias       | 172
 Solanum lycopersicum    | 193
```

>What did I miss?

Homonyms - that still puts 'laundry' and 'bugs' and 'metal' on every record using Iron, regardless of classification preferences.

We already have a mechanism for preferring metadata of names, common names are just metadata of names, why the push to unnecessarily complicate things??

**Comment by Jegelewicz** [comment]
Lota lota! seems appropriate....

So it looks like the common name list is truncated in the catalog record
![image](https://user-images.githubusercontent.com/5725767/189201714-bc25136d-0544-434f-92c2-f3c8cec45b2e.png)

![image](https://user-images.githubusercontent.com/5725767/189201868-0b040087-1797-462b-82e0-f93b292bb857.png)

all 102 common names don't show up.

**Comment by dustymc** [comment]
>truncated

Your browser is hiding a scrolbar.

<img width="747" alt="Screen Shot 2022-09-08 at 11 49 58 AM" src="https://user-images.githubusercontent.com/5720791/189202414-ed598d10-c178-4bc5-a289-acdc25e3257b.png">

**Comment by Jegelewicz** [comment]
>  common names are just metadata of names, why the push to unnecessarily complicate things??

Aren't they more like synonyms (not in the taxonomic code sense, but in the English language sense) or other identifiers?

When @wellerjes wants a common name to print on her _Lota lota_ labels, she is either going to get 102 of them and her label will be ruined, or she will get the first one (which may be something she doesn't want printed on her label). In trying to keep the one she wants out of identification remark, you are suggesting that she create a new taxonomy source, clone everything in the Arctos taxonomy source over and add all of her "preferred" common names. This means she cannot take advantage of community curation of taxonomy anymore and it seems like a lot of work. The other alternative is to add "CHAS common name" to the metadata of all classifications in the sources she is using and hope that nobody ever over-writes it. Neither of these feel right to me.

In addition, there may be terms in common name that we don't want to be visible (think of the cultural taxonomy that @AJLinn replaced recently) this is also part of the [larger discussion about diversity and inclusion](https://github.com/ArctosDB/internal/issues/183).

**Comment by dustymc** [comment]
>synonyms

Maybe-kinda, but they're different in not being formal taxonomy. Still seems like splitting hairs....

>Arctos taxonomy source

Well yea, the giant trashcan is a giant trashcan, and what I'm suggesting will just result in welding the other giant trashcan to the side of it, which basically changes nothing.

I'd assumed that a collection that wants to curate common names probably wants to curate other stuff too. That can be done as a group (not even limited to Arctos); I don't think there's any sort of isolation inherent in this, I'm not quite sure what you're suggesting - maybe we are not clear enough about what the Arctos source is???

>we don't want to be visible

What I'm suggesting allows "we" to do whatever we want; we're not stuck dealing with anyone else's ideas of WHATEVER. A very local poll suggests the people after whom the machine is named find it flattering rather than "super offensive" - I don't think there are any globally acceptable approaches.

**Comment by Jegelewicz** [comment]
> We already have a mechanism for preferring metadata of names, common names are just metadata of names, why the push to unnecessarily complicate things??

Mulled this over in taxonomy committee today - it just doesn't seem like the right answer. @wellerjes would need to create a taxonomy source that diverges from all others just to get ancillary information. Creating a completely separate classification just to get preferred common name seems like overkill. These kinds of sources would be unlikely to be shared or managed over time because if someone else wants to prefer a different common name, they would have to create a new source with a (probably over time) divergent classification. It sounds like we are getting to - "everyone just make and manage your own taxonomy source". Maybe that's what people want?

We have a place for the common names - why couldn't we allow collections to prefer one of them?

**Comment by dustymc** [comment]
> create a taxonomy source that diverges from all others

Wut?

> "everyone just make and manage your own taxonomy source"

We're not there, nor are we on the other end of the spectrum from which common names as metadata of names can make much sense in the direction of this issue - that structure still works fine for discovery, as long as a few false positives are OK.

>have a place for the common names

That place cannot determine that Echidna-the-butterfly and Echidna-the-fish and etc. would not have the same common names. Adding the appropriate common names to the relevant classification makes that separation without adding any sort of complexity or requiring any new management.

**Comment by Jegelewicz** [comment]
@wellerjes can you send me a file that includes two columns:

Taxon name | CHAS preferred Common Name 

Thanks!

**Comment by wellerjes** [comment]
After discussion in the @ArctosDB/diversity-and-inclusion committee, we have some concerns with creating a separate taxonomic source just for common names (and Indigenous names, etc). By keeping the scientific name separate from the common name/Indigenous name, etc., there's more room for error, re: updating one record but not any of the correlating records.

> We have a place for the common names - why couldn't we allow collections to prefer one of them?

The common name information is already embedded in the taxonomic record. Can we use that to our advantage ?

How I see this functioning: When something is entered into Taxon A and is accepted, it's tied to that taxonomic record, indicated by the field turning green when valid. Could it pull from the common names already in the table from "Edit Taxon Name and Related Data for [taxon name]"? Visually, it would add a line directly underneath Taxon A (it does not need to be a required field like in my mock-up). A drop down would appear with all the common name options already recorded in the taxonomic record.
![image](https://github.com/ArctosDB/arctos/assets/93737929/78a167c3-afa5-4ad5-bafd-ea0c938cc945)

All the information would still be on one page, which keeps the common name and the scientific name more closely linked. It would also incentivize people to make sure the taxonomy page is up-to-date with their preferred common name. The biggest hurdle is determining if we can pull the common names that are already tied to the scientific name from the taxonomy edit page, eliminating the need for a code table for each common name.

**Comment by dustymc** [comment]
I think there must still be some very deep misunderstanding here (but https://github.com/ArctosDB/arctos/issues/4829#issuecomment-1550370462 makes a bit more sense now!).

>The common name information is already embedded in the taxonomic record. Can we use that to our advantage ?

That's _almost_ what I'm suggesting.

The taxonomic record is NOT (quite) what you use when you make an identification. If you're a fish collection, when you say "Echidna" you really mean something like https://arctos.database.museum/name/Echidna#Arctos (eel) because you've set your collection up to prefer the Arctos source. You don't mean "moth" or "virus" or "spiky mammal" - the "taxonomic record" encompasses all of those things, the classification you've preferred does (or should) not.

I am suggesting you just associate "eel" with the thing you're already implicitly choosing, Muraenidae: Echidna, ie https://arctos.database.museum/name/Echidna#Arctos. 

The rest of your verbiage seems to refer to identifications, which are applied to individual records. This is an unavoidable path to having three "mountain lion," 17 "puma," one "mountin line,' and no user successfully finding all of your data. (It's denormalization.)

What happens currently is that users searching for puff adders (yet another historic use of Echidna) also find your eels. False positives aren't great, but they're almost always the least-evil possibility; they tell users what's out there, even if there's an occasional flood involved in the telling. (Call it 'overnormalization' - because it is.)

What I'm suggesting would be more specific that that, but less specific than anything which might happen at the record level. (Just normalization, yay everybody!)

"Mountain Lion" is clearly metadata of a classification (https://arctos.database.museum/name/Felis%20concolor#Arctos), I'm only suggesting to put the data where it's screaming to be.

See also https://arctos-test.tacc.utexas.edu/name/Carcharodon%20carcharias#Arctos

**Comment by campmlc** [comment]
So if we could select a common name or display name with authority, we could make it possible to disambiguate between Echidna the eel and Echidna the mammal?

**Comment by dustymc** [comment]
I think this is adequately addressed in next release. https://arctos-test.tacc.utexas.edu/name/Carcharodon%20carcharias#Arctos leads to https://arctos-test.tacc.utexas.edu/guid/ALMNH:Paleo:904 which contains...

<img width="572" alt="Screenshot 2023-07-07 at 07 46 20" src="https://github.com/ArctosDB/arctos/assets/5720791/6eaccdaa-1be4-44ce-9839-fe8c05bee6a1">
