### ISSUE TITLE
Encumbrance action restrict usage - need better definition

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5032]
The @ArctosDB/arctos-code-table-administrators are not sure exactly what the encumbrance action [restrict usage](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctencumbrance_action#restrict_usage) actually does. The definition is not very helpful:

> Require encumbrance compliance before loaning specimens.

Can someone help us out here? @campmlc ?

**Comment by Jegelewicz** [comment]
@dustymc who all is using this encumbrance type?

**Comment by Jegelewicz** [comment]
Code table today

@campmlc uses this to make sure that loaned items are conditioned with citation of the specimen and NSF grant. Only applies to certain things. This does not DO anything and we need to make that clear in the definition.

**Comment by dustymc** [comment]
There was an unhandled encumbrance "mask collection object remarks" which lead to this issue for some reason.

The logs claim it was created by @Jegelewicz 

It wasn't used and I was able to delete it, but this should never happen - those things aren't magic, if I don't write code then they do nothing except expose allegedly-private data. 

I noticed this only because the encumbrance description was ambiguous.

I can't drop what I'm doing to check right now, but the possibility that something similar has happened to other encumbrances needs thoroughly investigated as soon as possible.

We should review code table procedures. This should not have happened and could easily have gone very wrong.

**Comment by Jegelewicz** [comment]
That came from https://github.com/ArctosDB/arctos/issues/5031

**Comment by dustymc** [comment]
>That came from https://github.com/ArctosDB/arctos/issues/5031

??

```
arctosprod@arctos>> select * from log_ctencumbrance_action where n_encumbrance_action='mask collection object remarks';
  username  |        change_date         |      n_encumbrance_action      |                                                            n_description                                                             | o_encumbrance_action | o_description 
------------+----------------------------+--------------------------------+--------------------------------------------------------------------------------------------------------------------------------------+----------------------+---------------
 jegelewicz | 2022-11-17 15:16:18.092677 | mask collection object remarks | Do not display collection object remarks. <a href="https://github.com/ArctosDB/arctos/issues/5032" class="external">GitHub Issue</a> |                      | 
(1 row)
```

**Comment by Jegelewicz** [comment]
Whew - that was ages ago! But it should have been part of #5031 in any case.

Anyway - apologies for causing mass panic. My code table etiquette has improved since then I hope.

**Comment by Jegelewicz** [comment]
I guess it is my fault for not explicitly tasking @dustymc to make the switch.

**Comment by Jegelewicz** [comment]
Also my bad for apparently copy-pasta the wrong Github issue. Maybe I should just stop doing things.

**Comment by Jegelewicz** [comment]
I don't believe there are any wildfires here - just me being human. Arctos is not broken and this issue should be closed, but 5031 still needs doing.

**Comment by dustymc** [comment]
>human

You're not alone in bearing that burden - that's why I keep looking for procedures (which hopefully WOULD catch this and WOULD NOT drag any 5-minute problems out for weeks...). There's definitely wildfire potential in there, but it's sorta fuzzy and abstract and definitely not new - I keep hoping someone's going to have an AHA! moment in one of these conversations, otherwise I suppose we can keep inching forward and that probably doesn't need to keep this open.

I intend to review the code to make sure all current encumbrances are handled/Arctos is in fact not broken. If it happened without anyone noticing once - well, maybe that's just paranoia, if you're sure that everything is properly handled then this can probably be closed, except...

This happening makes me think we need SOMETHING - again procedures is my preference, but if we can't do that then maybe I can figure out something in code or ??? - to prevent this (and are there others like it? Media relationships maybe) from happening again. Minimally, the CT admin doc needs to mention this this table.

**Comment by Jegelewicz** [comment]
#5031 was on the working group agenda in January - https://docs.google.com/document/d/19i1D5Nq8icKuIRmj8WMiQMz1bA_5M4F6Ac4Emj5TDKM/edit#heading=h.ld7kjld6h405

There is just too much going on and not enough brains to handle it all (that isn't a comment on the quality of brains, but the quantity).

We have decent procedures, but we don't have the capacity to follow them. People will forever be making mistakes and we don't have enough people to do consistent quality checks so they don't get caught in a timely fashion.

Here is the series of events:

1. Code table agreed to change a term to de-specimen Arctos (a long standing effort that everyone supports, I believe)
2. We did things as per usual - create the new term, then request the switch, only this all happened just about the time the panic to immediately re-do the UI began
3. I made two fatal errors - I copied the wrong Github link into the code table description for the new term (I was editing two in the same code table - it isn't too hard to see how that happened) AND I failed to tag you to make the switch (I just set the milestone to next task)
4. Perhaps another fatal error is that instead of pestering anyone, I was being polite during the UI meltdown and trying not to bring up other issues, so I added this as a Code Table issue in the AWG Issues agenda instead of being a huge squeaky wheel.

What could be better?

- Someone is designated to check the code table edits after they get made for errors and omissions? (A single person or a different person each and every time? We can't get through the HUGE list of code table issues because there is not enough asynchronous participation in Code Table issues in GitHub. We can maybe handle 5 in a Code Table Meeting and sometimes we can't even get through one. Asking everyone to do MORE doesn't seem feasible.)
- I need to understand better what the Next Task milestone actually means and whether adding it myself is or is not appropriate.
- I need to better understand what needs to be done NOW, because my impression for the last six weeks or so is that all that mattered was getting the new Search and GUID pages done along with a new header and footer and that if there is even a single Wildfire issue open, that comes before all else.

Honestly, what could be better is having more people. We can create a million procedures, but if we don't have the manpower to follow them, it really doesn't matter.

**Comment by ewommack** [comment]
> (that isn't a comment on the quality of brains, but the quantity).

I now have this vision of cloning brains in jars, and them crawling out and across the floor to come help Teresa...

**Comment by AJLinn** [comment]
Sorry to be late to the issue here... is this something I need to be a part of or is my encumbrance safe? I guess per the process of de-specimening I should update the encumbrance name? Or is this what caused whatever this issue is addressing?

<img width="1230" alt="Screenshot 2023-02-01 at 5 33 51 PM" src="https://user-images.githubusercontent.com/17605945/216217233-ec9bdf04-49bc-459d-9472-75fc616be017.png">

**Comment by Jegelewicz** [comment]
@AJLinn you are safe. It is actually #5130 that caused what we are discussing here. So no de-specimenjng has happened, but it needs to.

**Comment by dustymc** [comment]
>after they get made

That must be BEFORE - once something happens, however it happens, it's often ridiculously difficult, if not impossible, to un-do. (See for example https://github.com/ArctosDB/internal/issues/205 and basically all of https://github.com/ArctosDB/arctos/labels/CodeTableCleanup, and this could have lead somewhere not-great.) No solid ideas how to get there, and what we have now is way better than it used to be, but we're obviously not quite where we need to be.

> what the Next Task milestone actually means 

"Whoever's going to do this knows how to do this" is my interpretation. (Which involves assigning issues to get at who, which I think nobody uses properly, so I always just assume I'll be pushing the buttons....)

>what needs to be done NOW

Yea, ditto. This is a great example of that - it of course needs to happen, but it doesn't change any functionality so ??eventually?? Opposite that, when this was happening I was completely consumed by what to me looked like an imminent crisis, and obviously didn't give anything else whatever attention it needed. 

I think the priority tags are over-used and not very helpful - can we somehow do better there? (At some point one of the committees was going to focus on prioritization, I thought.) I'm up for trying about anything, and would definitely welcome more direction.

>more people

1. If we had more people we wouldn't need procedures - the security team would have caught this if the QA folks didn't, no problem. I see this about exactly opposite you, I think - the fewer resources we have, the **better** our procedures need to be. We _need_ really solid procedures....
2. In some happy theoretical universe, some things could probably be tagged for an intern or student or etc., and others for a consultant, but that's always seemed even more out of reach.

@ewommack if you end up with any extra brains I'll take 'em, no questions asked.

**Comment by campmlc** [comment]
I think the "more people" also means more people who have time to focus on
developing procedures. Teresa is maxed out. The basic problem for all of us
is that we all have full time jobs outside of Arctos, and most of us, as
collection managers in a traditional sense, lack the specialized skills for
web and UI development, cyber security, and organizational management that
we are now in desperate need of. I thought TACC was going to provide
people? Anyone there we could have tapped for these security and UI issues?
A consultant? What we just went through last two months, was insane, and we
will still be dealing with all the ripple effects for some time before we
can focus again on where we were in October.

**Comment by dustymc** [comment]
I'm relatively sure that current encumbrances are all properly handled, and I believe https://github.com/ArctosDB/internal/issues/251 satisfies all the procedural asks and would have prevented any problems. Tentatively closing this in anticipation of formally adopting that.
