### ISSUE TITLE
[ geography request ] Klondike Gold Rush National Historic Park

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#5036]
# Carefully read the documentation at https://handbook.arctosdb.org/documentation/higher-geography.html before submitting a request.

There appears to be no entry for Klondike Gold Rush National Historic Park

https://en.wikipedia.org/wiki/Klondike_Gold_Rush_National_Historical_Park

North America, United States, Alaska, Klondike Gold Rush National Historic Park

**Comment by dustymc** [comment]
@DerekSikes your input on https://github.com/ArctosDB/arctos/issues/5017 would be very useful - I don't know why we have this stuff in geography, don't know if we need to keep it there or its equally functional in locality attributes, so I'm not sure what to do here.

If we do keep this as geographic feature then I'll need spatial data, which I think likely exists because we have it for some other parks. @mkoo help?

**Comment by dustymc** [comment]
Merge-->https://github.com/ArctosDB/arctos/issues/5138
