### ISSUE TITLE
Update Morocco Regions and Provinces

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#5059]
It appears that Morocco has made significant changes in Regions and Provinces (2015).  We have almost none of their Regions in higher geography.  We list provinces in the State/Province field, but that should probably be the 10 regions.

To complete records in the bulkloader, we need Marrakesh-Safi as a Region.  https://en.wikipedia.org/wiki/Marrakesh-Safi 

Note: Marrakech-Asfi was formed in September 2015 by merging the old region of [Marrakech-Tensift-El Haouz](https://en.wikipedia.org/wiki/Marrakech-Tensift-El_Haouz) with the provinces of [Asfi](https://en.wikipedia.org/wiki/Safi_Province) and [Youssoufia](https://en.wikipedia.org/wiki/Youssoufia_Province) in [Doukkala-Abda](https://en.wikipedia.org/wiki/Doukkala-Abda) region

And we need Chichaoua Province (within Marrakesh-Safi Region.)  https://en.wikipedia.org/wiki/Chichaoua_Province

Note: Fes-Meknes is currently in the table as a Province but it appears to be a [region](https://en.wikipedia.org/wiki/Regions_of_Morocco). https://en.wikipedia.org/wiki/F%C3%A8s-Mekn%C3%A8s

* * * * * * * * *

We will respond with a CSV template, or request more information.

**Comment by dustymc** [comment]
Blargh, GADM seems to have pre-2015 data.

@mkoo do you have any way to get fresher data?

The existing data should have dates added (which will make records using them complain about being noncurrent).

```
gadm0::Morocco
 gadm1::Morocco|Chaouia - Ouardigha
 gadm1::Morocco|Doukkala - Abda
 gadm1::Morocco|Fès - Boulemane
 gadm1::Morocco|Gharb - Chrarda - Béni Hssen
 gadm1::Morocco|Grand Casablanca
 gadm1::Morocco|Guelmim - Es-Semara
 gadm1::Morocco|Laâyoune - Boujdour - Sakia El H
 gadm1::Morocco|Marrakech - Tensift - Al Haouz
 gadm1::Morocco|Meknès - Tafilalet
 gadm1::Morocco|Oriental
 gadm1::Morocco|Rabat - Salé - Zemmour - Zaer
 gadm1::Morocco|Souss - Massa - Draâ
 gadm1::Morocco|Tadla - Azilal
 gadm1::Morocco|Tanger - Tétouan
 gadm1::Morocco|Taza - Al Hoceima - Taounate
 gadm2::Morocco|Chaouia - Ouardigha|Ben Slimane
 gadm2::Morocco|Chaouia - Ouardigha|Khouribga
 gadm2::Morocco|Chaouia - Ouardigha|Settat
 gadm2::Morocco|Doukkala - Abda|El Jadida
 gadm2::Morocco|Doukkala - Abda|Safi
 gadm2::Morocco|Fès - Boulemane|Boulemane
 gadm2::Morocco|Fès - Boulemane|Fès
 gadm2::Morocco|Fès - Boulemane|Sefrou
 gadm2::Morocco|Fès - Boulemane|Zouagha-Moulay Yacoub
 gadm2::Morocco|Gharb - Chrarda - Béni Hssen|Kénitra
 gadm2::Morocco|Gharb - Chrarda - Béni Hssen|Sidi Kacem
 gadm2::Morocco|Grand Casablanca|Casablanca
 gadm2::Morocco|Grand Casablanca|Mohammedia
 gadm2::Morocco|Guelmim - Es-Semara|Assa-Zag
 gadm2::Morocco|Guelmim - Es-Semara|Guelmim
 gadm2::Morocco|Guelmim - Es-Semara|Tan-Tan
 gadm2::Morocco|Guelmim - Es-Semara|Tata
 gadm2::Morocco|Laâyoune - Boujdour - Sakia El H|Laâyoune
 gadm2::Morocco|Marrakech - Tensift - Al Haouz|Al Haouz
 gadm2::Morocco|Marrakech - Tensift - Al Haouz|Chichaoua
 gadm2::Morocco|Marrakech - Tensift - Al Haouz|El Kelaâ des Sraghna
 gadm2::Morocco|Marrakech - Tensift - Al Haouz|Essaouira
 gadm2::Morocco|Marrakech - Tensift - Al Haouz|Marrakech
 gadm2::Morocco|Meknès - Tafilalet|El Hajeb
 gadm2::Morocco|Meknès - Tafilalet|Errachidia
 gadm2::Morocco|Meknès - Tafilalet|Ifrane
 gadm2::Morocco|Meknès - Tafilalet|Khénifra
 gadm2::Morocco|Meknès - Tafilalet|Meknès
 gadm2::Morocco|Oriental|Berkane Taourirt
 gadm2::Morocco|Oriental|Figuig
 gadm2::Morocco|Oriental|Jerada
 gadm2::Morocco|Oriental|Nador
 gadm2::Morocco|Oriental|Oujda Angad
 gadm2::Morocco|Rabat - Salé - Zemmour - Zaer|Khémisset
 gadm2::Morocco|Rabat - Salé - Zemmour - Zaer|Rabat
 gadm2::Morocco|Rabat - Salé - Zemmour - Zaer|Salé
 gadm2::Morocco|Rabat - Salé - Zemmour - Zaer|Skhirate-Témara
 gadm2::Morocco|Souss - Massa - Draâ|Agadir-Ida ou Tanane
 gadm2::Morocco|Souss - Massa - Draâ|Chtouka-Aït Baha
 gadm2::Morocco|Souss - Massa - Draâ|Inezgane-Aït Melloul
 gadm2::Morocco|Souss - Massa - Draâ|Ouarzazate
 gadm2::Morocco|Souss - Massa - Draâ|Taroudannt
 gadm2::Morocco|Souss - Massa - Draâ|Tiznit
 gadm2::Morocco|Souss - Massa - Draâ|Zagora
 gadm2::Morocco|Tadla - Azilal|Azilal
 gadm2::Morocco|Tadla - Azilal|Béni Mellal
 gadm2::Morocco|Tanger - Tétouan|Chefchaouen
 gadm2::Morocco|Tanger - Tétouan|Fahs Anjra
 gadm2::Morocco|Tanger - Tétouan|Larache
 gadm2::Morocco|Tanger - Tétouan|Tanger-Assilah
 gadm2::Morocco|Tanger - Tétouan|Tétouan
 gadm2::Morocco|Taza - Al Hoceima - Taounate|Al Hoceïma
 gadm2::Morocco|Taza - Al Hoceima - Taounate|Taounate
 gadm2::Morocco|Taza - Al Hoceima - Taounate|Taza
```

**Comment by sharpphyl** [comment]
> To complete a record in the bulkloader, we need Marrakesh-Safi as a Region. https://en.wikipedia.org/wiki/Marrakesh-Safi and Chichaoua Province (within Marrakesh-Safi Region.) https://en.wikipedia.org/wiki/Chichaoua_Province

No rush right now on the other regions/provinces but we have a catalog record in the bulkloader that needs this Region and Province.  Can we add it even if we have to overwrite it later?

**Comment by dustymc** [comment]
@sharpphyl I got these data from geoboundaries (thanks again @tucotuco) and I'll get them in today, one way or another, but I have a hopefully-quick question and some insight on https://github.com/ArctosDB/arctos/issues/5076

Last first, "do what geoboundaries does" (or what they do that I can access with my primitive tools, maybe) just isn't going to work - along with the necessity to manually figure out which "state" a "county" goes with, they've dumped everything in one string so I end up with things like ``Morocco:Province de Khémisset إقليم الخميسات`` and I just don't think I'm prepared to dump that into county (and these switch direction in the middle which breaks most every UI I can find, most especially Excel). We are going to have to standardize to some extent; we can still avoid mishmashing, but it's not going to be quite as simple as I'd hoped.

Once the Arabic is removed, I'm left with

* Settat Province
* Province d'Ouezzane
* Prefecture d'Oujda-Angad 

and probably some other stuff that I strongly suspect is Fren-arab-glish rather than any sort of faithful transliteration/translation.

I am tempted to remove all the qualifiers, and end up with


* Settat
* Ouezzane
* Oujda-Angad 

Wikipedia isn't any help, they seem to spell everything everywhichway and don't agree with geoboundaries or themselves or anything else. Timely advice on this is greatly appreciated - I'll do SOMETHING before the day is over.

@ArctosDB/geo-group @ArctosDB/arctos-working-group-officers help!

**Comment by dustymc** [comment]
I'm taking the silence as enthusiastic approval and stripping the qualifier-bits.

**Comment by dustymc** [comment]
Existing things should be updated, I'm loading this now-ish, please let me know ASAP if you see any problems.

[temp_geog_morocco - temp_geog_morocco(4).csv.zip](https://github.com/ArctosDB/arctos/files/9620650/temp_geog_morocco.-.temp_geog_morocco.4.csv.zip)

**Comment by dustymc** [comment]
loaded and cleaned

**Comment by sharpphyl** [comment]
Works perfectly. Sorry I didn't get back to you sooner.
