### ISSUE TITLE
session expiration is annoying

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ArctosDB/arctos#507]
```
What steps will reproduce the problem?
1. Log in
2. Half do something
3. Wander off
4. Click button
5. Craps

Figure out how to warn people when their session is about to timeout, and - 
err, - something...

```

Original issue reported on code.google.com by `dust...@gmail.com` on 16 Dec 2011 at 3:27

**Comment by dustymc** [comment]
Cannot currently identify a less-annoying approach.

**Comment by dustymc** [comment]
Yay, technology, finally.....

There's now a "Session expires in xx minutes." widget in the header, it should stay synced up across tabs, and it should turn angry and red when a session is about to expire.

**Comment by mkoo** [comment]
OMG so awesome!

**Comment by dustymc** [comment]
This (BroadcastChannel, probably), like most things, does not work properly on Safari. At least one user met the same symptoms on Chrome. It's now disabled for not-firefox.

**Comment by dustymc** [comment]
Chrome claims to fully support this, and I can't break it. @jrdemboski had some trouble with the same environment I'm using, and I can't determine why. I'd like to turn this on for Chrome if possible. I've set up a test that uses the same protocol and code (plus some debugging stuff). It would be useful if a few people could try it out.

To do so, log in to Arctos using Chrome, and open a few tabs with https://arctos.database.museum/fix/a.cfm.

You should see something like...

<img width="530" alt="Screen Shot 2019-08-02 at 10 39 33 AM" src="https://user-images.githubusercontent.com/5720791/62388317-d5f22b00-b511-11e9-8071-a51a86fa65d1.png">

The number in the box should be the POSIX time of the last session event - opening a new tab or refreshing an existing should change/reset it in all tabs.

The overly-precise xx.xxxxxxx number is minutes since the time in the box. It should get a bit smaller every half-second or so.

You should only see "NOW!" once the timer reaches zero. This was for some reason happening within minutes for a user yesterday. Please let me know if this works as it should, or screenshots and javascript console contents would be very useful if it doesn't.
