### ISSUE TITLE
Improvements to reports table

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5092]
We need to add some columns to the list of reports for sorting and filtering.

Report type - loan, loan header, label
Created by - arctos username of person who added the report
Collection - collection the form was customized for

What else?

**Comment by dustymc** [comment]
@ccicero

**Comment by dustymc** [comment]
This is time-sensitive (see https://github.com/ArctosDB/arctos/issues/5087), I'm going to write code ~early next week.

Unless I am directed otherwise before then, I'll go ahead with:

report_type - free-text, NULLable
created_by - automagic agent reference
collection - free-text, NULLable

@ccicero  and whomever else wanted this, please let me know ASAP if you're looking for something else.

**Comment by ccicero** [comment]
Thanks @dustymc Rather than have 'report_type' be free text, what about a drop down with report categories (that's what I had in mind):

here are some categories to start:
dry label
wet label
loan document
ledger document

and I don't think it should be nullable.

Also for collection, why not just use GUID Prefix versus free text?

???

**Comment by dustymc** [comment]
>why not just use GUID Prefix

IDK how reports are used and can do whatever, but I was thinking this might be better for shared things "ABC & XYZ Fish" or "ABC fish and herps" or whatever.

**Comment by ccicero** [comment]
True, we want to be able to share, but I envision being able to search another collection's reports as a model and having collection be free text seems like it just opens this up to a mess.

I think by categorizing report type - e.g., wet label - then someone can sort on all wet label types and use them for fish, herps, birds, or whatever. So that would be the way to share things.
