### ISSUE TITLE
Are non-US County-level political subdivisions geography?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5109]
### First Step: Explain what geography needs created.

[San Quintín Municipality](https://en.wikipedia.org/wiki/San_Quint%C3%ADn_Municipality) is not included in Arctos, but the other [munis of Baja California](https://en.wikipedia.org/wiki/Municipalities_of_Baja_California) are. This is needed for CSULB data migration.

We will respond with a CSV template, or request more information.

**Comment by dustymc** [comment]
I'm not sure what to do here, neither San Quintín nor San Felipe are in GADM or geoBoundaries (so they must share data or a source?). @mkoo any magic?

**Comment by mkoo** [comment]
I think the municipalities in general are not a sustainable precedent in
HG. Can it not be accommodated in spec_loc?
HG I think needs to firmly require a spatial footprint (at least we're
trying) and municipalities in any country are not super stable and not
reliably in GADM. Exceptions occur of course since US counties are used in
permitting and more or less stable.

Now having said that, we have some for others in Arctos for Baja. But for
those two:
wiki says:
"The municipalities of San Quintín and San Felipe have since been
incorporated from territories previously belonging to Ensenada and
Mexicali."

Is Arctos HG upto date on GADM? If so can verbatim and spec localities
reflect these deprecated admin boundaries?

**Comment by dustymc** [comment]
>HG I think needs to firmly require a spatial footprint

Amen!

>municipalities in any country are not super stable 

I've explored a relatively minor part of the world in some detail from a spatial standpoint recently, and this is a huge understatement. (And I probably don't have the resolution to notice when borders are quietly re-drawn; I'm sure my perspective is still very lacking.)

>s Arctos HG upto date on GADM?

It's getting there, bits and pieces are, overall there's a VERY long way to go. (And some sort of AWG-ish blessing/rejection of https://github.com/ArctosDB/arctos/issues/5076 would help; I've been trying to walk the razors edge between not making the messes messier and not blocking users, not that much fun really.) 


>Can it not be accommodated in spec_loc

One consideration might be how things like geolocate handle various data. County (and island) in specloc seem about the same as in county to me, but I'm usually looking at the weird data that's fell out of something else so IDK how far that holds.

I do suspect I'd see a HUGE functional difference if we had....

```
select count(*) from geog_auth_rec where county is not null;
 count 
-------
  6515
```
6.5K fewer things - or 65% of everything at the moment - to choose from. Some significant portion of our geography errors seem to from users not internalizing the whole thing (which can be far from trivial when it's a little of this and a dash of that and...), there are usability benefits to simplicity.

And I just moved a bunch of "but it says county!" state-level things to where they belong, being more restrictive with county might or might not help on that front.

From a completely opposite perspective, we do have the option to add dates to former geography at this point, things that aren't current could be added if necessary. Those don't generally have spatial data just because I don't like impossible tasks, and I hope everyone will eventually migrate to modern (or [let Arctos take care of it](https://github.com/ArctosDB/arctos/issues/4785) - including [georeferencing](https://github.com/ArctosDB/arctos/issues/4916)) but IDK how realistic that is.

**Comment by Jegelewicz** [comment]
Losing the ability to make the municipalities in Mexico "normal" seems terrible from a discoverability perspective. There will end up being a million ways to spell San Quintin in spec loc and nobody will ever find all of the things from there if that is what they are interested in.

I feel like we are being given a devil's bargain - get the shapes but lose a lot of controlled vocabulary. Maybe I am missing something in all of this, but I kinda don't like it.

**Comment by mkoo** [comment]
That's the beauty of sharing the locality table though! We can fix,
people can find, curators can use 'em
And remember San Quintin municipio no longer exists to MX. So maybe an
attribute...?

This has been basically our working protocol BTW, for admn_2 in non-US
countries for a while, so not making this up on the fly

**Comment by Jegelewicz** [comment]
> This has been basically our working protocol BTW

Whose? I don't think this has been a community protocol because lots of munis and other level 2 localities were being created up until this new "must have spatial" requirement. I'm not saying it is wrong, but it isn't what everyone is doing as far as I can tell and it really sucks when the one you need isn't there, but a bunch of others are - how do we tell incoming collections that theirs isn't "worth" it?

> We can fix, people can find, curators can use 'em

Can we? I need a tutorial. - https://github.com/ArctosDB/arctos/issues/5116

> San Quintin municipio no longer exists to MX

I don't think we can keep up with "current" geography over the long term. This is a huge global issue, but within Arctos, we just cannot do it and all of the legacy data that shows up is potentially going to have "political divisions that no longer exist". I spend a lot of time trying to figure out what higher geography should get used for some of this stuff and it's not fun. It sucks to have stuff like this hold up bulkloading.

Sorry for the rant, but we don't really have a well-documented plan for higher geography and it's making me crazy.

**Comment by dustymc** [comment]
>must have spatial" requirement

I don't think we're looking at that the same way. There's are a TON  - thousands - of things that aren't in any way geography treated as geography, because until now it's just all strings and nobody can tell 'local name for county, country' from some actual county from some actual county that hasn't existed since 1874 and is nowhere near the modern city of the same name  (and infinite variations on all those). The spatial data does lots of things, but a primary function is linking the string to a real, nonimaginary, semirecent place.

>I don't think we can keep up with "current" geography over the long term.

I've proposed lots of things over the years, one that keeps coming back up is moving "curatorially-asserted geography" much more verbatim-ward (that could be a string or have any amount of structure, details are irrelevant at this point) and letting Arctos assert actual geography.

(And I don't see any way that would result in anything other than an easier time in a simpler environment for humans, and data which can't conflict with itself as the computers get involved - maybe that's just a lack of imagination...)

>we don't really have a well-documented plan for higher geography and it's making me crazy.

Yep. Can we convene some emergency meeting to flesh that out, or refuse to talk about anything else at the normal meetings until we have a solution, or come up with some sort of a plan that might lead to a plan for the plan??

**Comment by dustymc** [comment]
>things that aren't in any way geography

Convenient example: I just deleted Kenya, Kakagmega - looks like a bad spelling of Kenya, Kakamega (that's what I assumed for the deletion, anyway). That sort of thing is inevitable when people are typing, impossible when we're pulling from existing sources.

**Comment by genevieve-anderegg** [comment]
> Yep. Can we convene some emergency meeting to flesh that out, or refuse to talk about anything else at the normal meetings until we have a solution, or come up with some sort of a plan that might lead to a plan for the plan??

Yes please! I see it's on the agenda for this week's issues meeting to talk about a more organized Geography Committee, which is a good step forward

**Comment by dustymc** [comment]
Hijacking the rest of this, discussion should focus on https://github.com/ArctosDB/arctos/issues/5109#issuecomment-1261488355

>I think the municipalities in general are not a sustainable precedent in
HG. Can it not be accommodated in spec_loc?

**Comment by dustymc** [comment]
Merge-->https://github.com/ArctosDB/arctos/issues/5138
