### ISSUE TITLE
Wasatch Mountains in UT

### ISSUE THREAD

**Issue by ewommack** [ArctosDB/arctos#5161]
With the new system of geography coming on board I figured I would request help from Arctos before submitting a geography request. 
I have a new locality for an object, where the most specific information is the Wasatch Mountains in UT. That is not the best locality, but it does exclude other mountain ranges in the state, and non-mountain ranges. So better then no locality.
The problem I have run into is that the [Wasatch Mountains](https://en.wikipedia.org/wiki/Wasatch_Range) appears to span through multiple counties, including Cache, Rich, Weber, Summit, and Wasatch Counties. 

With our new geography protocols being developed, what would be the best way to create the locality for this object in Arctos, especially the Higher Geography? I'd like to get it cataloged in the next week if possible, but could mark it to change the geography when we update the system later.

**Comment by dustymc** [comment]
Just use https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=1118 (the state, the smallest GADM-compliant shape that covers all the possibilities) for the geography.

If you can and wanted to scrounge up spatial data for the mountain range we could add it (Fun and Flexible Features!) and then it could be used for searching, but those won't be linked directly to individual records - the link is through spatial overlap - so that would not change anything about how you should catalog.

**Comment by mkoo** [comment]
was going to write exactly what @dustymc said. Wasatch Mtns or Range will be in the verbatim and specific locality so no info lost. When we implement our 'F3' phase (new term!), that can be applied with no further work from you if there are coordinates!

**Comment by ewommack** [comment]
Thanks @dustymc and @mkoo. 

I'll select Higher Geography of just the state (UT), and have in verbatim and specific locality the Wasatch Mountains. 
I can georeference the locality with Geolocate. Somewhere in those mountains is where a quail was collected, and it will at least exclude the other mountains and other areas.
