### ISSUE TITLE
USGS HUC drainage should be a locality attribute

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5223]
Currently the [USGS HUC Drainage codes](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type#usgs__huc_8_digit) are entered as other identifiers. It seems to me that these should really be locality attributes.

BUT

Looking at https://water.usgs.gov/GIS/huc.html maybe these should all be FFFs? If we could do that, would we need these other identifiers?

**Comment by dustymc** [comment]
>[USGS HUC Drainage codes](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type#usgs__huc_8_digit) are entered as other identifiers

Yea, I think that's one of those things that got crammed through without sufficient discussion (and will now consume 10x more resources than discussing it properly ever could have). I agree, makes no sense there....

>should all be FFFs

If someone can send me a shapefile (or perhaps some other stuff), I can probably make that happen. (And we need to have a conversation about resources, but I don't think it needs to block anything.)

>we could do that, would we need 

That's a question for the collections. https://github.com/ArctosDB/arctos/issues/4289 makes me think there may be some desire to assert things that are at odds with the spatial data, but I really hope I'm just not understanding something.

**Comment by Jegelewicz** [comment]
> If someone can send me a shapefile (or perhaps some other stuff),

Can you get this from Digital Spatial Data Sets at https://water.usgs.gov/GIS/huc.html ?

**Comment by mkoo** [comment]
there are many different levels/orders of HUC's (thinking about it there may be a parallel with uncertainty ...) anyway FFF is most appropriate. it's spatial but could you give an example record using it as an otherid?

**Comment by dustymc** [comment]
https://arctos.database.museum/SpecimenResults.cfm?oidtype=USGS%3A+HUC+8-digit

https://arctos.database.museum/guid/MSB:Fish:100

**Comment by campmlc** [comment]
At the time we added HUCs as other UDs, we had no locality attributes as options. Our fish collection had drainage and stream flow and condition parameter info, and we had no where to put anything.  I think adding them as attributes is fine.

**Comment by dustymc** [comment]
>adding them as attributes 

I think they should probably be documentation for https://arctos.database.museum/info/ctDocumentation.cfm?table=ctdrainage if there's some reason to keep that around (rather than just using FFFs).

I'd very strongly prefer not to spread the identifiers out to other nodes unless there's some compellingly-functional use case.

@campmlc stream flow and condition parameter would be collecting event attributes (they change over time). We stashed some of that in catalog record attributes (but I think not for this collection), I'll go open an Issue

**Comment by barke042** [comment]
I was just drafting a note to @campmlc and @Jegelewicz about this in the context of our fish basin/drainage data but I searched for the issue first! Pat me on the head. I agree that it makes sense for HUC codes to be locality attributes, but I wouldn't limit it to the 8 digit versions, since in some cases we might only have data down to the sixth digit. Anything more general than that probably isn't very useful. For context, could somebody please define FFF for me? I can't follow the discussion in that regard.

**Comment by Jegelewicz** [comment]
> We do have at least some basin/drainage data from outside the US, which I guess would still be handled by locality attribute 'drainage' rather than a new locality attribute 'USGS HUC'.

yes to using [drainage](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctdrainage) for this just request any new terms you might need.

> For context, could somebody please define FFF for me

Fun, flexible, features - non-assertable geography with a spatial footprint to facilitate discovery. BUT, I really need a demo of this, because I can't explain it myself. @dustymc

**Comment by dustymc** [comment]
>makes sense for HUC codes to be locality attributes

I'm strongly opposed to two ways of saying the same thing. If we must have 12345678 then let's get rid of whatever that corresponds to in https://arctos.database.museum/info/ctDocumentation.cfm?table=ctdrainage. If we want to keep eg Arkansas River then let's don't introduce some new string that means the same thing. Adding the HUCs as definitions of the terms still looks most correct from here. What ain't I understanding?


>demo

https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=10016796 is a FFF.

<img width="353" alt="Screenshot 2022-11-07 at 2 04 13 PM" src="https://user-images.githubusercontent.com/5720791/200425146-a3e6849e-42d4-4507-a84a-b82d69d4d306.png"> finds stuff from Yosmite (or it would if I had sufficient resources) no matter what's asserted.


<img width="646" alt="Screenshot 2022-11-07 at 2 05 48 PM" src="https://user-images.githubusercontent.com/5720791/200425494-4279ccf3-e0e8-436e-a0ee-3df9cf4fb59a.png">

is the same spatial query plus a search term (also derived from the spatial query) that shouldn't time out and finds about the same thing.

For recently cached things I'm also using Arctos geography (instead of external stuff, because ours is now sane/defensible and can deal with shapes, not just points) to calculate the aforementioned search terms, which looks like...

 North America, United States, California, Mariposa County, Yosemite National Park 

from https://arctos.database.museum/guid/BYU:Herp:41840 (which asserts only "United States, California").

I keep expecting someone's going to want that "assembled geography" passed on to GBIF or whatever, but that'll need an issue (and they're not all that clean, some assertions may contain a dozen states and an ocean or two, for example).

That's probably not everything that I've done, but it's a bit of an overview of what's possible.

**Comment by dustymc** [comment]
>adding them as attributes is fine.

Proceeding with this before cleanup becomes more difficult.

A better cleanup would likely involve removing the attribute I'm about to add, and adding these data to https://arctos.database.museum/info/ctDocumentation.cfm?table=ctdrainage as suggested. I don't have the resources to do that at the moment so I'll just transfer these data as they exist to a more appropriate location.

Table: https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlocality_attribute_type

New attribute: USGS HUC 8-digit

Definition: Consider using drainage instead of this attribute; consult the originating issue for more information. United States Geological Survey hydrologic unit code for hydrologic units which are classified as subbasins in the USGS Watershed Boundary Dataset. 

Doc: https://water.usgs.gov/GIS/huc.html 

Type: free text

**Comment by dustymc** [comment]
Migration data: 
[temp_huc.csv.zip](https://github.com/user-attachments/files/16700537/temp_huc.csv.zip)
