### ISSUE TITLE
New Arctos Report Template Request-MSB Loan Headers and Invoices

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#5245]
**Description of the report** - Loan header and invoice for MSB Mamm collection. Ideally, I'd like this to be transferrable to other MSB Divisions, perhaps by using a standard template for the institution and just changing the Division name by including that as an agent, or some other means of being able to use a single form for all our divisions, depending on which issues the loan?

**Collection for which the report is needed** - MSB Mamm, Bird, Herp, Fish, Para

**Priority** - Urgent

[MSB_Mamm_loan_invoice_2021.zip](https://github.com/ArctosDB/arctos/files/9931561/MSB_Mamm_loan_invoice_2021.zip)

[MSB_Mamm_loan_header_1.zip](https://github.com/ArctosDB/arctos/files/9931559/MSB_Mamm_loan_header_1.zip)

**Comment by campmlc** [comment]
SQL for loan invoice (header has no SQL, but maybe needs it?)

select 
    flat.collection, 
    flat.collection_cde, 
    flat.cat_num, 
    flat.scientific_name, 
case 
      when trim(flat.sex)='male' then 'male'
      when trim(flat.sex)='female' then 'female'
      else '?'
    end sex,
    concatsingleotherid(flat.collection_object_id,'NK') NK,
    specimen_part.part_name as part, 
    coll_object.condition part_condition, 
    CASE WHEN length(coll_object.condition) > 15 or flat.ENCUMBRANCES is not null THEN 'X' end AS has_appendix, 
    concat(higher_geog,'. ',spec_locality,'. ',verbatim_coordinates) as locality,
    item_instructions, 
    loan_item_remarks, 
    coll_object.coll_obj_disposition, 
    flat.ENCUMBRANCES, 
    loan.loan_number,
    trans.trans_date,
    flat.datum,
    flat.verbatim_coordinates
from 
    loan_item, 
    loan,
    trans,
    specimen_part, 
    coll_object,
    flat
WHERE 
    loan.transaction_id = loan_item.transaction_id and
    loan.transaction_id = trans.transaction_id and
    loan_item.collection_object_id = specimen_part.collection_object_id AND
    specimen_part.collection_object_id = coll_object.collection_object_id and
    specimen_part.derived_from_cat_item = flat.collection_object_id and
    loan_item.transaction_id = #transaction_id#
ORDER BY
    cat_num::int

**Comment by jldunnum** [comment]
I support this request too

______________________________________________________________
Jonathan L. Dunnum Ph.D. (he, him, his)
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

Chair, Systematic Collections Committee, American Society of Mammalogists
Latin American Fellowship Committee, ASM

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131

**Comment by dustymc** [comment]
> Division name pulling in based on the loan GUID

Please clarify. (Edit collection or eg https://arctos.database.museum/collection/MSB:Mamm should have the available data.)

**Comment by Jegelewicz** [comment]
I have created MSB Loan Invoice Detail csv download - a csv download of loan items that could be used in a mail merge. I'll work on creating the template in Word as well. SQL from the old MSB_Mamm_Loan_Invoice_2021.

**Comment by Jegelewicz** [comment]
@campmlc Creating these reports in Word is a bit tricky since they are not labels and Word likes to insert section breaks. Anyway, I have created a csv download (MSB Loan Invoice Detail csv download) and a Word mail merge to get the report for the invoice detail. I changed the format of the header so that I could fit more rows on a given page - I can change it to the original format, but you will lose space for the details.

Attached 

A csv download for a single loan
[mamm_loan_data.csv](https://github.com/ArctosDB/arctos/files/11969220/mamm_loan_data.csv)

The Word Template
[MSB_Mamm_loan_list.docx](https://github.com/ArctosDB/arctos/files/11969442/MSB_Mamm_loan_list.docx)

and the results of a merge
[MSB_Mamm_loan_list_2023.003.docx](https://github.com/ArctosDB/arctos/files/11969486/MSB_Mamm_loan_list_2023.003.docx)

BUT
1. I need to modify the SQL for the csv to include "MSB:Mamm:" in the catalog number because adding it manually won't work across collections
2.  I need to modify the SQL for the csv to include information for subsample, because I don't believe anything is being captured for that column?
3. I'd like to make this even more generic so that the header information can be generated from the csv download - that requires some other information to get added
4. I still need to set up the loan header page
5. I am also going to try to set this up as a web report using one of the MVZ templates when I have time

So - there is still a lot to do and I am not sure if this report will be good for every loan - there could end up being weird page breaks depending upon the length of text in some of the columns.  Let me know if anything here is glaringly dumb or needs changing.

**Comment by campmlc** [comment]
This looks great! I agree that for MSB and other institutions we need to figure out a way to make the header imported from the csv, so that we can use it for different collections and institutions. Also, any possibility of pulling in a logo from Arctos collection profiles, or do we need to add that individually to each form?
The only issue I see at the moment is an inserted line break in the address line of the report header. But this is an excellent start, thanks!!

**Comment by campmlc** [comment]
For the invoice - some of our collections or transactions will want to have collector number or some other value other than NK, and parasites will want to have verbatim host ID pulled in as well. Just wanting to get this on the radar for further development. I think the previous hold up was we didn't know what the field names were or how to add in that SQL.

**Comment by Jegelewicz** [comment]
>  an inserted line break in the address line of the report header

Unfortunately, that is in the address in Arctos.

**Comment by Jegelewicz** [comment]
@campmlc I took the MVZ html header and modified it for MSB:Mamm try it out - MSB Loan Header html

Once the report generates in your browser, use the print function from the browser to print as pdf. You may have to adjust margins to get it all on one page and I couldn't see the lines while doing the printing but they showed up on the pdf when it was done. See attached.
[MSB_Mamm_header_html.pdf](https://github.com/ArctosDB/arctos/files/11971701/MSB_Mamm_header_html.pdf)

**Comment by Jegelewicz** [comment]
There is also now an html version of the loan detail - MSB Loan Invoice Detail html 

With headers that print on every page! - Taken from https://medium.com/@Idan_Co/the-ultimate-print-html-template-with-header-footer-568f415f6d2a

I'll see about adding page numbers to the footer and I think the header still needs work also still missing "subsample" information.

**Comment by Jegelewicz** [comment]
I also need to clean up unused stuff in these reports and make sure they have proper instructions.

**Comment by Jegelewicz** [comment]
@campmlc can you clarify what is expected in the "subsample" column?

**Comment by campmlc** [comment]
Just yes/no, meaning we are leaning a subsample of listed part, or not. If
no,we are leaning entire part.

**Comment by Jegelewicz** [comment]
OK - subsample is now in the reports (both csv download and html). That just leaves this:

- [ ] I'd like to make this even more generic so that the header information can be generated from the csv download - that requires some other information to get added. Which will come from this - https://github.com/ArctosDB/arctos/issues/6513

I'd really appreciate some testing of these - let me know what works and what doesn't.

**Comment by Jegelewicz** [comment]
FYI Here is what we have so far:

## Using Word and mail merge
Loan Header - use CSV: loan_data_dump
Loan Details - use MSB Loan Invoice Detail csv download

## Using css/html
Loan Header - MSB Loan Header html
Loan Details - MSB Loan Invoice Detail html (note that this report also has the information from manage_collection displayed to show how a "generic" remoprt would look - not great and we could discuss ways to make it better).

I am done until there is some feedback. Enjoy!

**Comment by campmlc** [comment]
Html looks great! One thing on the html header: signature line needs to be "received by" rather than outside contact.
html invoice: looks good, seems to work for both portrait and landscape.
I haven't figured out the mail merge for csv yet, but will try soon.

Some things we will need for this to work across MSB Divisions: 
1) ability to swap out ID types, or include "or" - for example, use NK or AF or IF; or replace NK with collector number or field number - I assume this relates to ID changes in progress.
2) replace subsample y/n and encumbrance columns with other fields - especially "verbatim host ID" and "location in host".

**Comment by Jegelewicz** [comment]
> Some things we will need for this to work across MSB Divisions:

> 1. ability to swap out ID types, or include "or" - for example, use NK or AF or IF; or replace NK with collector number or field number - I assume this relates to ID changes in progress.
> 2. replace subsample y/n and encumbrance columns with other fields - especially "verbatim host ID" and "location in host".

Both of those things have to be coded into the html and cannot be changed "on the fly", so I either need to know exactly what they want or they need to figure out how to clone and edit one of these.

**Comment by Jegelewicz** [comment]
> signature line needs to be "received by" rather than outside contact.

Changed

**Comment by Jegelewicz** [comment]
> I haven't figured out the mail merge for csv yet, but will try soon.

The mail merge version of the header looks better IMO but the html/css version of the details works better because the table created by the mail merge gets funky as soon as the rows extend over a single page. If I were choosing though, I would just use the html/css versions for simplicity sake. Mail merge is GREAT for labels and single page letters, not so much for tables.

**Comment by Jegelewicz** [comment]
MSB:Herp loan header is ready for review

**Comment by Jegelewicz** [comment]
MSB:Fish loan header is ready for review

**Comment by Jegelewicz** [comment]
MSB:Bird Invoice detail (html) ready for review

**Comment by Jegelewicz** [comment]
MSB:Fish Invoice detail (html) ready for review

**Comment by Jegelewicz** [comment]
MSB:Herp Invoice detail (html) ready for review

**Comment by campmlc** [comment]
For MSB:Para invoice, ideally we need the option of choosing which identifier to use. Is it possible to get the code to select a value with alternates? e.g.  NK if there is one, if not, then AF, if not then IF, if not then collector number? Also, the attribute "verbatim host ID" is really important, or even better - pull from the related host taxon name. I'm not sure if this is feasible.

**Comment by msbparasites** [comment]
Where is it that I can look at the invoice for Parasites? Would like a pull down for identifier, most of the stuff that does not come from MSB birds and mammals is all by collector number (though a while ago many of those got changed to other identifier which was irritating). Verbatim host ID and life stage have been the most useful for me

**Comment by Jegelewicz** [comment]
> Where is it that I can look at the invoice for Parasites? 

The ones I tried to view are all in the old reporter:

<img width="960" alt="Screenshot 2023-07-24 13 10 45" src="https://github.com/ArctosDB/arctos/assets/5725767/9cfa5af9-bfd5-4b92-8efe-bdfd28c83df8">

None of them produce a report, so I don't know what is needed besides the things you have listed.

> Would like a pull down for identifier

This is not possible under the current system. I can build a series of IFs to get NK if there is one, if not, then AF, if not then IF, if not then collector number

> Verbatim host ID and life stage have been the most useful for me

I can try to add these, but depending on what else you need, the report will have a lot of columns and may not be very readable.

**Comment by msbparasites** [comment]
Ok then if and if not will work for IDs that are not MSB#
If it helps, here is what I like, and if something has to go, it would be life stage, unless the slide/vial/DNA column doesn't work, then remove that instead of life stage. 

MSB#  Parasite sp.  Collector#/NK/AF  VerbatimHost  lifestage   slide/vial/DNA(part?)  Locality

Is that ok?

**Comment by jtgiermakowski** [comment]
> MSB:Herp Invoice detail (html) ready for review

Both look and print to PDF great on my end, thank you @Jegelewicz !  I didn't look at the utility of "MSB Loan Invoice Detail", so far it is only used my mammals??

**Comment by Jegelewicz** [comment]
> so far it is only used my mammals??

The Word template has "mammals" all over it and you may not get all the data you need for your invoice detail - it would probably need some tweaking if you want to use a mail merge (but I don't recommend it for this report).

**Comment by msbparasites** [comment]
Hey that looks great!!!! Thank you.

**Comment by Jegelewicz** [comment]
I think we are done here. Closing. File a new issue if a report needs fixing or a new report is requested.

**Comment by campmlc** [comment]
Thank you!
