### ISSUE TITLE
Feature Request - Make agent picker with edit agents better

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5270]
**Is your feature request related to a problem? Please describe.**
Today when I was attempting to add a relationship between two agents, the picker selected a name that I didn't want, but I wasn't easily able to see that. It wasn't an exact match, but it was the only name that kinda matched. It autofilled and I assumed everything was good, until I found out it wasn't!

**Describe what you're trying to accomplish** 
Pick the right agent when creating a relationship

**Describe the solution you'd like**
Only an EXACT match to what I typed should autofill, otherwise I should be offered sorta-matches to choose from (or told there aren't any sorta-matches)

**Describe alternatives you've considered**
Don't autofill anything and force me to pick, but people don't like the extra step...

**Additional context**
Happened during agent cleanup in today's agents meeting.

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.

**Comment by dustymc** [comment]
>Only an EXACT match to what I typed should autofill

That isn't compatible with where we're trying to go (a model in which we have enough data to easily disambiguate  multiple agents with the same name) - going forward with no autofill at all.

**Comment by DerekSikes** [comment]
I Strongly oppose this! The lack of autofill will increase the number of clicks I have to do for each record edit by a unacceptable amount! With all these attributes etc. It's nuts, please revert. To slow down ALL users because of a rare accident that happens ... and without buy-in from all users is not good. If people are worried about mis-matched names they need to be more careful and read the names that appear & fix as needed. This puts the burden where it belongs. Not on the 99.999% other cases where this supposed solution creates new aggravations and slows down work.

**Comment by Jegelewicz** [comment]
Is this also true for login names? Those must be unique so it seems like we could use them to auto fill.
