### ISSUE TITLE
[CONTACT] cat_records feedback - inconsistent results between old & new form

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#5316]
I'm loving the customization available for operators for searching and for organizing the results.
BUT I just found a major problem.
I just entered my standard technique for searching for an object type (Identification = parka) using the old form and got these (expected) results:

<img width="957" alt="Screenshot 2022-11-30 at 8 00 34 PM" src="https://user-images.githubusercontent.com/17605945/204970015-bda9ca23-cc16-4fc4-a711-10a5c10e07c3.png">

But then when I did the same search using the same criteria and fields, I get ALL items in my collection (only 5000 of which will show):

<img width="1325" alt="Screenshot 2022-11-30 at 7 59 18 PM" src="https://user-images.githubusercontent.com/17605945/204970126-4f08e887-3ec5-4f64-a812-6f476be70d08.png">

Did I do something wrong?
Thanks for helping me better understand the new form.

**Comment by AJLinn** [comment]
Incidentally if I just use the "Any taxon" box  I get the full 220 records I expected... guess I'll throw the wide net! :-)

**Comment by AJLinn** [comment]
OH yeah, and one more thing...
I noticed if you have a set of search results, then customize your results, save them, your results go away. Is that a glitch? The old form allows you to "save and refresh" with your same results. That's a nice feature to keep, if at all possible.

**Comment by AJLinn** [comment]
And the last thing (for today)...
Can you make the "Submit query" and "Customize results" / "Customize search" buttons different colors? They're all the same now and that's hard to decipher. (Maybe make the 2 customize buttons one color and the query button a different color - no preference what the color is)

**Comment by AJLinn** [comment]
Oh yeah and only one more thing! 🤣
In the old form when you search attributes that have a controlled vocabulary for the value, that is expressed as a dropdown list in the value so you only search for the proper spelling of that attribute.  Can the new form do that? It's pretty important for a field like culture that expresses the identity of sovereign tribal nations.

Old = easy to pick from a long list
<img width="846" alt="Screenshot 2022-11-30 at 8 37 43 PM" src="https://user-images.githubusercontent.com/17605945/204974982-6e7386f0-7acb-44f8-890f-56912cb6075d.png">

New = hard to guess what the right spelling should be
<img width="1018" alt="Screenshot 2022-11-30 at 8 41 51 PM" src="https://user-images.githubusercontent.com/17605945/204975047-74004db9-2f1a-47a8-ad4e-90f7e22526f1.png">

**Comment by dustymc** [comment]
I patched the identification typo.

>search results, then customize your results, save them,

I'll see what I can come up with. That's intentional - the form has to rebuild - but I think I can find a way to remove some klunks.

>buttons different colors?

Yes, but we need to do something standardized and site-wide. Current colors are at the bottom, we can add a new  'customizeBtn' class. If nobody suggests anything by the time I get there I'll consult the [expert](https://randomwordgenerator.com/color.php).

It should be suggesting, I'm guessing those data aren't very JS-friendly. I'll see what I can do.

<img width="393" alt="Screenshot 2022-12-01 at 7 37 40 AM" src="https://user-images.githubusercontent.com/5720791/205095021-9445f94b-f8cf-4eaa-b19f-ae1b19318e17.png">

Buttons - background-color is the changing value, you can google eg 'color FBD29B' to see what they look like. 
```
 	
	/* save changes */
	input.savBtn {
	   	color:#666666;
	   	font-size:10pt;
		font-weight:bold;
		background-color:#FBD29B;
		border:1px solid;
		border-color:#666666;
		 margin:0.4em;
	}
	
	/* link; go somewhere not terribly scary */
	input.lnkBtn {
		color:#666666;
		font-size:10pt;
		font-weight:bold;
		background-color:#99CCFF;
		border-color:#666666;
		border:1px solid;
		 margin:0.4em;
	}
	
	/* search button: finds something */
	input.schBtn {
		color:#666666;
        font-size:10pt;
		font-weight:bold;
        background-color:#CCCC99;
		border-color:#666666;
		border:1px solid;
		 margin:0.4em;
    }

	/* clears or resets a form */
	input.clrBtn {
		color:#666666;
		font-size:10pt;
		font-weight:bold;
		background-color:#FFCC00;
		border-color:#666666;
		border:1px solid;
		 margin:0.4em;
	}
	
	/* insert: makes something new */
	input.insBtn {
		color:#666666;
        font-size:10pt;
		font-weight:bold;
		background-color:#99CCCC;
        border-color:#666666;
		border:1px solid;
		 margin:0.4em;
	}
	
	/* opens a pick list */
	input.picBtn {
		color:#666666;
		font-size:10pt;
		font-weight:bold;
		background-color:#CCCC99;
		border-color: #666666;
		border:1px solid;
		 margin:0.4em;
	}
	
	/* delete: something dies with clicky */
	input.delBtn {
		color:#666666;
		font-size:10pt;
		font-weight:bold;
		background-color:#FF9966;
		border-color:#666666;
		border:1px solid;
		 margin:0.4em;
	}
	
	/* quit: go somewhere else without saving any changes */
	
	input.qutBtn {
		color:#666666;
		font-size:10pt;
		font-weight:bold;
        background-color:#F1948A; /***#FFFF00***/
		border-color:#666666;
		border:1px solid;
		 margin:0.4em;
	}
```

**Comment by krgomez** [comment]
> It should be suggesting, I'm guessing those data aren't very JS-friendly. I'll see what I can do.

I like the way the field is suggesting terms containing the letters you type, however for subject terms I really like having the dropdown list. There are hundreds of terms in that code table and without a dropdown list I don't think this attribute will get used to its potential, as users won't know what the options are and may miss a term that would be valuable to their search.

**Comment by krgomez** [comment]
Maybe a 'define' link could appear when a particular attribute is selected to search so that the user could see the code table?

**Comment by dustymc** [comment]
> hundreds of terms

Usability of lists starts dropping dramatically at about a dozen items. I'm not suggesting the current UI is any form of "correct" and I'm always up for better ideas, but a hard list of hundreds of items will be "wronger."

A pick with definitions (there must be very precise and fine-scaled differences with that many items, no?) might be best there, but that's also maybe more complexity than we can really support for a single global search form. I'll try to keep it in mind, maybe something will come up.

**Comment by dustymc** [comment]
>define' link 

<img width="201" alt="Screenshot 2022-12-01 at 9 39 59 AM" src="https://user-images.githubusercontent.com/5720791/205122543-e20be218-fe11-4a85-865c-604a6272b372.png">

Hmm, maybe that could do something more complex - maybe something a bit like the collection picker, where a complex form ultimately writes values to the otherwise relatively simple (=sustainable) form?

**Comment by dustymc** [comment]
I'm going to serialize the URL to reload the form, which means

1. There are some limitations - fill in enough stuff and something will fail. Need to figure out how to break it, and try to break it in a least-offensive way
2. Need to confirm that all search options have default and value handling -
3. Since I'm serializing URLs, I added that option to the tools menu

<img width="264" alt="Screenshot 2022-12-01 at 10 59 46 AM" src="https://user-images.githubusercontent.com/5720791/205137681-0501d75c-d898-41a4-bd06-87f718f91195.png">

**Comment by dustymc** [comment]
moved attribute search to new issue

I think the form is all reloading properly now, but there's a LOT of stuff I could have missed something, testing appreciated

randomizer says customize buttons shall be #E7EBDA

**Comment by AJLinn** [comment]
> It should be suggesting, I'm guessing those data aren't very JS-friendly. I'll see what I can do.

It's working! Thanks!

**Comment by AJLinn** [comment]
> randomizer says customize buttons shall be #E7EBDA
That's a very nice green. 
Will continue to test!

**Comment by dustymc** [comment]
Green? Sheesh, no wonder ya'll complain about my color choices, looks beige to me...
