### ISSUE TITLE
Bird parts

### ISSUE THREAD

**Issue by lin-fred** [ArctosDB/arctos#5339]
@ccicero @ewommack For bird skeletons, in which there is no skin, so it should be a 'full' skeleton - Do you all put skeleton and then skull, or just skeleton?

**Comment by ccicero** [comment]
@lin-fred at MVZ we just put 'skeleton' if it is a complete skeleton. If it's partial but mostly complete (e.g, missing a set of wing bones), we still put 'skeleton' but then 'partial' in condition with more details about what's missing. We only use 'skull' if that's the main thing we have (if we have a few other elements plus the skull we would also add those as separate parts). I hope this makes sense.

**Comment by lin-fred** [comment]
Thank you!

**Comment by ewommack** [comment]
Yep! I follow along with Carla's recommendations. We do a lot of partial skeletons here, and I put that in condition and in remarks as well. 
I also do that if I do a skeleton and have a spread wing that goes with it.

**Comment by ewommack** [comment]
Sure here you go: https://arctos.database.museum/guid/UWYMV:Bird:4276

I'd add partial into the condition for the skeleton part, or you could also add post-cranial. 

We had this on going conversation on what to call partial skeletons from skins somewhere in Github, and there were a lot of different ways different collections called their partial skeletons. Trunk skeleton, body skeleton, post-cranial skeleton, etc.
I decided to just stick to partial, because for me a post-cranial skeleton would have all the post-cranial parts (especially the limbs). Most partial skeletons with a skin for birds are just the trunk skeleton, but that can be really depend on the prep type and style. I think if your collection likes post-cranial for your birds, I would just add "partial skeleton, post-cranial" in condition.

**Comment by lin-fred** [comment]
Our museum doesn't really have a 'way'. The way used to be using terms such as SK, SKO, SO and SN, which means things like, skin only, skeleton only, skull only, or skin and skeleton etc. So it never got into the nitty gritty.

I think the current parts for our birds is due to this Github issue discussion that you've mentioned. So I'm really open on how to define it. 

I think I actually prefer your way, because the skeleton is technically not just post-cranial, as it also has, technically, part of cranium still with the skeleton?

**Comment by Jegelewicz** [comment]
You can also add the part attribute [part modifier](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecpart_attribute_type#part_modifier) with the value [postcranial](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctpart_modifier#postcranial)
