### ISSUE TITLE
catalog record search - identifiers - list parsing

### ISSUE THREAD

**Issue by catherpes** [ArctosDB/arctos#5352]
Proposed new Search interface does not seem to be able to deal with strings of other identifiers any better than current page. 
For instance, this string of Personal Catalog numbers was not able to be found by searching them as a string, either with or without the CGS prefix. There's a lot of variability in how numbers are entered, and what they're called within our collection, and that undoubtedly is part of it, but even now that I know that all of these but the last 5 are entered as preparator numbers, when I search "identifier type" as 'preparator number' and "OtherID Operator" as 'list,' I get nothing

CGS 5483,  CGS 5719,  CGS 5720,  CGS 5721,  CGS 5722,  CGS 5723,  CGS 5739,  CGS 5817,  CGS 5819,  CGS 5836,  CGS 5837,  CGS 5838,  CGS 5839,  CGS 5840,  CGS 5841,  CGS 5842,  CGS 5843,  CGS 5844,  CGS 5845,  CGS 5846,  CGS 5847,  CGS 5848,  CGS 5849,  CGS 5855,  CGS 5856,  CGS 5857,  CGS 5858,  CGS 5859,  CGS 5860,  CGS 5861,  CGS 5862,  CGS 5863

**Comment by dustymc** [comment]
>Proposed new Search interface does not seem to be able to deal with strings of other identifiers any better than current page.

Correct. There is no back-end functionality change at all. I'll edit the title of this.

>I get nothing

It's the spaces.

If you search LIST (I'm searching without type, but that doesn't matter) for say

```
CGS 5848, CGS 5723
```

it will parse that out into  ``CGS 5848`` (and find a record) and ``{space}CGS 5723`` (and not find a record, because you - correctly and thankfully -  don't have any space-C data).

```
CGS 5848,CGS 5723
```

gets parsed properly and does what it should.

I'm not sure what I can do about this without mucking something else up, but I'll try.

**Comment by catherpes** [comment]
Okay, that's helpful. 
Maybe simply a note on how to search for these types of numbers that are not NK/AF/institutional catalog numbers. Or maybe  there is already one and I ignored it. 
Thanks!
