### ISSUE TITLE
[CONTACT: Blocked Network]

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5363]
restricted IP: 186.233.186.228

On a VPN, please unblock

**Comment by dustymc** [comment]
I generally don't allow VPNs because I don't have the resources to do so safely. I unblocked that one in case you're looking at a growing fire, but it has a bunch of previous auto-blocks and will almost certainly re-block itself, even if it doesn't try something shady and get hard-blocked again. (And there's always a non-zero chance that "something shady" was actually "something horrible" and will successfully get through our remaining defenses.)

**Comment by Jegelewicz** [comment]
This is my personal VPN, managed by my husband. Using it because I am currently on an unsecure network. Seems like my VPN would be better than some hotel's open WiFi or even my phone's personal hotspot?

**Comment by dustymc** [comment]
You're sharing IP space with datacenters in countries that for various reasons produce a lot of malicious traffic. I don't have tools with the resolution to separate that traffic.
