### ISSUE TITLE
Request for API key

### ISSUE THREAD

**Issue by mvzhuang** [ArctosDB/arctos#5366]
OK i want to try it over the winter break. Can someone give me an API key?
Any info that I need to give?

**Comment by Jegelewicz** [comment]
@mvzhuang whatcha gonna do with it? I need to know to complete the form....

**Comment by Jegelewicz** [comment]
@dustymc where can I find the terms available for use_restrictions and what they mean?

**Comment by mvzhuang** [comment]
Try generating a map on the new collectors pages on our website, maybe try seeing if i can call it with google sheets for data validation?, and maybe create a random image generator from specific plant families?

**Comment by dustymc** [comment]
@mvzhuang I'm not sure I'll get documentation written nor public access fully ironed out before Christmas, but there's a v2 API that you might want to use, mostly because it has a more "normal" (not that there's any such thing) result format, but it also deals with authentication and such. Ping me a URL before you get too deep into building and I'll translate - should be straightforward from there.

> where can I find the terms available for use_restrictions 

Your keyboard.

>what they mean?

Nothing, I can't DO anything other than maybe watch the logs until something happens with https://github.com/ArctosDB/internal/issues/51. Eventually-maybe that'll be functional (read-only) or something concerning data ('must include license') or branding ('use this logo') or WHATEVER, in the meantime I've been assuming the lack of action constitutes approval to just go wild....

**Comment by mvzhuang** [comment]
that's alright - might take me a while to get to it.

**Comment by dustymc** [comment]
@mvzhuang that's all lies, the next version of Arctos will have v2 public access (with a key, IDK what to call that...) and API documentation. As always, let me know if you have any problems following it.

**Comment by dustymc** [comment]
done
