### ISSUE TITLE
Another questionable funky agent

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#5412]
@krgomez created[ this agent ](https://arctos.database.museum/agents.cfm?agent_id=21346662)and it's stuck in the funky agent notification loop.
<img width="700" alt="Screenshot 2022-12-21 at 7 37 51 AM" src="https://user-images.githubusercontent.com/17605945/208957594-17f12e23-1b97-484f-b47c-0b5ffe687fbf.png">

It seems to be fine with alternate spellings re: the non-ascii characters. I wonder if the script would prefer an AKA for the first name alternative instead of two first names? Or does the script not recognize the v-->w replacement?

<img width="735" alt="Screenshot 2022-12-21 at 7 34 14 AM" src="https://user-images.githubusercontent.com/17605945/208957128-3024ffbb-1285-46dc-9245-e51ee1dd6663.png">

**Comment by dustymc** [comment]
>Or does the script not recognize the v-->w replacement?

Exactly, it's really dumb. It's looking for ``E_var_`` (I don't think it even much cares what the substitution characters are, as long as they're ASCII). That's not useful in this case, but it does work with the tools I have available, and allow me to detect what would otherwise be very many unfindable agents. (Maybe [unaccent](https://github.com/ArctosDB/arctos/issues/4783) will change that situation at some point.)
