### ISSUE TITLE
Arctos Down - Not responding

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5421]
Please complete to the best of your ability.

## Unplanned Outage
 - Date and time (**please add time zone from which you are reporting**) outage discovered: December 28, 2022 2:30PM MST
 - Describe the outage (Arctos down or only some part not working?): I am unable to reach Arctos - the connection times out

## Planned Outage
 - Date and time outage will begin:
 - Date and time outage is expected to end:
 - Reason for outage:
 - Expected behavior during and after the outage:

## Communication before/during outage
- [x] Pin this issue
- [ ] Banner updated @jegelewicz @mkoo
- [x] Email sent to AWG  
- [x] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [x] Unpin this issue
- [ ] Banner updated @jegelewicz @mkoo
- [x] Email sent to AWG 
- [ ] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by Jegelewicz** [comment]
Tried both Firefox and Chrome also on mobile - all connections time out.

**Comment by barke042** [comment]
I am down too (Firefox on Mac).

**Comment by lin-fred** [comment]
sent out a tweet, still down for me

**Comment by Jegelewicz** [comment]
Sent email to TACC

**Comment by ccicero** [comment]
Down for me too at 4:47pm. For the record, Joyce wrote:

I logged in, saw that there have been no new logs since 3:18pm today
(which I assume is when Arctos stopped responding), tried to restart
nicely, when that failed I killed the java process and started the box
server again. As far as I can tell, Arctos is still stuck.

According to Dusty "if that doesn't do it the proxy is probably jammed
up, so ping Chris, you're basically out of options."

I'm poking around for a few more minutes but probably will not get any
further. :(

**Comment by Jegelewicz** [comment]
> The frontend proxy got wedged, I restarted it, and am now getting 503 gateway errors which usually mean the backend is not running.
> 
> Thanks

Chris Jordan

**Comment by szaborac** [comment]
Was able to log in and run a quick search successfully just now.

**Comment by lin-fred** [comment]
its been back up for me too

**Comment by Jegelewicz** [comment]
Closing as complete
