### ISSUE TITLE
Feature Request - add culture to agent information

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5438]
**Is your feature request related to a problem? Please describe.**

**Describe what you're trying to accomplish** 

In general indigenous culture affiliation is often provided for artists. For example see https://americanindian.si.edu/collections-search/objects/NMAI_272393

It would be good if we could also create this association for people in Arctos

**Describe the solution you'd like**

Use the [cultures table](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctculture#pueblo__hopi) to associate a person with a culture

**Describe alternatives you've considered**

Create an agent for the culture and associate people via "associated with" relationship. This works, but doesn't seem like the most appropriate method. We have examples of this already - search agents of type "organization" for "Tribe" and you find quite a few.

The [Hopi Tribe of Arizona](https://arctos.database.museum/agent/21315952) is part of the [Pueblo, Hopi](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctculture#pueblo__hopi) culture, correct?

**Additional context**

I thought about this while working on agentifying people. I came across [Wilson Oozeva](https://arctos.database.museum/agent/21280580) and the Smithsonian object page above. I could create an organization agent for [Yuit (Siberian Yup'ik)](https://en.wikipedia.org/wiki/Siberian_Yupik) and add Wilson Oozeva as an "associated with", but wouldn't it be better to add the culture to the cultures table and then add it to his agent record?

@AJLinn @sjshirar if this is nuts, just say so. If you have a better idea, add that please!

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.

**Comment by AJLinn** [comment]
Thanks for this Teresa. My feeling from talking to artists is that many do not want to be defined by their cultural affiliation and most contemporary Indigenous peoples indicate that they identify with a number of tribal peoples. My feeling is that this is more appropriately placed in a narrative biographical summary that we typically place in the remarks field of their agent record. Moreover, this is often based on a summary they wrote themselves.

If that individual is associated as a creator of an object, that item already has a culture of origin designation in the catalog record (see one of several items in the UAM:EH collection that is also by Wilson Oozeva https://arctos.database.museum/guid/UAM:EH:UA99-018-0069). 

I would advise that we not create a relationship with a cultural group because it would be "labeling" a person in a way that they might not appreciate and doesn't represent the complexity associated with cultural identity.

**Comment by Jegelewicz** [comment]
Thanks! Closing.
