### ISSUE TITLE
Feature Request - improve view of customizable terms in new search UI

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#5442]
**Is your feature request related to a problem? Please describe.**
The new UI allows you to customize your search, but when you click on 'Customize Search' the view is a bit confusing. The terms are organized by categories and subcategories, but those different 'blocks 'are not delineated in the list so they're hard to distinguish unless you scroll to that category/subcategory. Also, the terms are not alphabetical within a subcategory because of inconsistency in how the terms display, e.g., capitalized or not, underscore or not, etc. 

**Describe what you're trying to accomplish** 
Make it easier to visualize terms when customizing your search.

**Describe the solution you'd like**
It would be helpful to add some kind of break between at least the different major categories to set them apart from each other in the long list of terms. Within a category/subcategory, make the terms consistent in case and with/without underscores so that terms sort better alphabetically.

**Priority**
High

**Comment by dustymc** [comment]
This was discussed at the last @ArctosDB/search-ui-task-group meeting.

Order was done by the committee, I can pull the data into a spreadsheet if someone wants to mess with it again.

Format is in the same data.

The form is user-sortable, so any sort of sub-sub-grouping or breaks or whatever are going to quickly become very confusing as soon as a user sorts.

I'm not sure where to go from here, but calling this needs discussion so hopefully it's not completely lost.

@campmlc is there some better way to organize??

**Comment by campmlc** [comment]
Is there a way to make the user sort operate only on major categories, with the subcategories linked?

**Comment by dustymc** [comment]
>user sort operate only on major 

Not with my current tools.

(And I like sorting on subcategory, the major are a little weird, some subs - 'basic' for example - span multiple 'majors', etc.)

**Comment by ccicero** [comment]
Sorry, I wasn't part of that discussion but at first glance it just seems to be random - takes a while to figure out the groupings because they don't stand out.

Here's just one example at the top:

![image](https://user-images.githubusercontent.com/967275/210887295-aaf95eb0-488b-4d54-992f-d35f80201080.png)

To start with, why aren't the subcategories grouped together (basic, basic, identifiers, basic in the above screen shot)? and I guess that I don't really understand the subcategories and how those are used. Being able to sort by category and then by subcategory within each category would be a good place to start (i.e., having those linked as @campmlc suggests, vs having them be independent when it comes to sorting).

Also, how do you get back to the original sorting? If I sort by category, I can't get back to how it was sorted before. 

I think also having the different terms be upper/lower case and with/without underscores makes it seem more like a mish-mash.

**Comment by dustymc** [comment]
>why aren't the subcategories grouped together 

Mostly because that's how I got the spreadsheet back....

>get back to the original

I think someone asked to remove the default order column (sorting by it would reset) so I guess you'd have to reload.

>upper/lower case and with/without 

Let me know if you want a spreadsheet....

**Comment by ccicero** [comment]
Sure, would like to see a spreadsheet. Is there any technical reason to have different cases or underscore/no underscore for different fields? Or does it matter from your perspective?

So is the list sorted by the spreadsheet order?

**Comment by dustymc** [comment]
https://docs.google.com/spreadsheets/d/1XOUYr7dqKx_koobGg1tQu98hi_S_SHJMqJsjcuQf8YA/edit#gid=1346364672

Do not touch OBJ_NAME, including case. I don't think that's visible so shouldn't matter, but let me know if something does need changed and I can coordinate it with the code.

Do not touch CATEGORY without talking to me, that's also linked to code. (I definitely don't mind changing this, even radically - I've been gong back and forth between thinking we have too many and thinking we have too few - but it's more involved than just changing it.)

DISPLAY is what you see, I think you can do whatever you want to it. (But it should mostly-sorta match what's on the form, so I suppose that kinda needs coordinated too...)

SUBCATEGORY 'basic' is functional and changes need coordinated, otherwise I think you can do whatever you want, and that came in late so probably could use some help.

DESCRIPTION can always use help.

DEFAULT_ORDER is just what it sounds like, relative integers.


Don't break it!

**Comment by Jegelewicz** [comment]
Can the descriptions just be linked to the code table definitions?

**Comment by dustymc** [comment]
Not exactly or at least not readily, but I can update from that so sorta-yes. There's some complexity linked to doing that in the old form, it'll be easier when that's gone and I don't have to worry about breaking it. Just pulling would definitely be a big improvement, hopefully I'll be able to see how when there's less clutter.

**Comment by sharpphyl** [comment]
We've been customizing all the new tables: Catalog search, locality search, geography search, event search etc.  The biggest frustration is that the titles of the fields in the search screen vs. the customize screen are not identical and are not in the same order.  Trying to figure out what to add or subtract from search and from results becomes very frustrating when you have to experiment repeatedly to find which fields relate.  

**Identifiers** is the simplest search section, yet the order in the search screen is just different enough.  Even the title of the section isn't exactly the same.  

<img width="1401" alt="Screenshot 2023-01-07 at 8 33 35 AM" src="https://user-images.githubusercontent.com/15368365/211159987-3e3da0fa-6f4f-4e43-a33d-b0b7f8775cc6.png">

<img width="859" alt="Screenshot 2023-01-07 at 9 01 50 AM" src="https://user-images.githubusercontent.com/15368365/211159992-199d8cfd-cd28-41bc-84cf-5984b2318e7b.png">

By the time you get to **Catalog Record** aka "record", everything is out of order one place or the other.

<img width="1577" alt="Screenshot 2023-01-07 at 9 07 31 AM" src="https://user-images.githubusercontent.com/15368365/211160000-ac2221ba-e02f-4857-bd7b-04806b74ccf1.png">

If you work in Arctos every day, this is not an issue but if you volunteer once a week for four hours, small inconsistencies become roadblocks.  Scrupulous consistency is really appreciated by our volunteers.  I'm happy to rearrange or rename things in your spreadsheet so that the "customize" screen is the same as the "search screen" (if that has priority), but I'm not sure you want anyone messing with your names/order.

**Comment by dustymc** [comment]
They used to line up....

My intention is to re-shuffle the form around (which is a tedious manual process) after the custom screen is satisfactory. There's a spreadsheet above, and of course your input is most welcome. (But, I think one problem here is that if we have input from 10 people they'll have about 19 ways in which things MUST be ordered and I'm sure you'd prefer not to have your changes immediately un-done - I'll let ya'll deal with that however you want....)

Changing section titles is a little more involved, but just let me know if you want something different and I'll make it happen. (Blame me for that one - what made sense in one place made my brain hurt in another, I added the ``s`` and didn't rebuild the other.)

Custom search is always going to be the outlier - it's whatever you picked, I'm not sure there could be a different approach to that.

I do think there should be some end point to this, some point at which we just quit making large-scale changes and learn to use whatever's there then, but IDK how to organize that either so I'll do whatever ya'll tell me to for now....

**Comment by sharpphyl** [comment]
So would it make sense to wait until the **search form** is set in something resembling concrete, then adjust the **customize form** to list the fields in the same order with the same names?  It doesn't matter exactly what names are used as long as they are the same in both forms.  The same request applies to all these new "customize" screens for search and results.  It's a great feature, but not yet optimized for occasional users.

**Comment by Jegelewicz** [comment]
I think we should talk about this in the UI Task Force meeting tomrrow!
