### ISSUE TITLE
Further customize search results

### ISSUE THREAD

**Issue by jebrad** [ArctosDB/arctos#5460]
Is it possible to customize my search results to show a column for "Institutional Catalog Number" and another column of "Collector Number" (and also maybe "Preparator Number"?  Currently my only option is to select "othercatalognumbers" which returns all of them concatenated into a single column.  I had some success in selecting "mycustomid" as one of those, but that was clunky and also seems to be no longer supported with the new search.

**Comment by dustymc** [comment]
It's easy enough to add stuff, but it also requires several days of full CPU to update. It would have been good to catch this with https://github.com/ArctosDB/arctos/issues/5354. @ArctosDB/arctos-working-group-officers I need help communicating, prioritizing, something-ing-ing, both for this and bigger-picture.

Customid is https://github.com/ArctosDB/arctos/issues/5456 (and can't be cached, so no blockers there.)

**Comment by jebrad** [comment]
OK, my bad for not paying attention to #5354.  But I probably would not have thought to ask for this at that time, I have only ~600 records whose Institutional Catalog Number is important to me, so I can find a workaround in Excel.
Also - as long as you get #5456 to happen (CustomID returned in results) - that will make for an easy workaround, and I hereby withdraw my request to further customize search results #5460.  I will let you close it. Thank you.

**Comment by Jegelewicz** [comment]
I'm gonna say the original is a really useful request and perhaps we should handle it if at all possible. I added this to the project for the UI Task Group and we meet tomorrow.

**Comment by dustymc** [comment]
>paying attention ... not have thought to ask for this

As much as I'd like to just blame you for everything, I suspect that ain't the case and we/me could do a better job of pushing these kinds of communications; I'm mostly hoping someone will have some clever idea for doing better.

>really useful request

Agreed - there are probably 5 or 10 identifiers that could be flattened, I don't think that's much problem, but sustainability demands we try to get them all at once.

>UI Task Group and we meet tomorrow

There are things that are actively breaking Arctos, this isn't one of them, I think that group should focus on the really fundamental stuff. If that's not to be (eg because the core is happy) then PLEASE let me know so I can push forward.

**Comment by Jegelewicz** [comment]
> this isn't one of them

We can prioritize - but we need to know what IS actively breaking Arctos

**Comment by ewommack** [comment]
> There are things that are actively breaking Arctos, this isn't one of them

Issues for the ones that are breaking Arctos please? Maybe we could add a "Breaking Immediate Attention Needed" column to the project.

**Comment by dustymc** [comment]
>Issues for the ones that are breaking Arctos

https://github.com/ArctosDB/arctos/issues/5333
https://github.com/ArctosDB/internal/issues/211

>"Breaking Immediate Attention Needed" column 

https://github.com/ArctosDB/arctos/labels/Priority%20-%20Wildfire%20Potential

**Comment by ewommack** [comment]
Ok I created the Priority Wildlife column and added those two issues to the UI Development Project. 

I've finished co-opting @jebrad's issue, and we should go back to discussing being able to customize search results to be able to see Catalog Number, Collector Number, Preparator Number here.

**Comment by jebrad** [comment]
I was already able to see Catalog Number in my results, and I agree it would be great to also see Collector Number, Preparator Number and Institutional Catalog Number too.  it would really improve the functionality of the search now and especially in the future.  I would agree it has a priority just below "Actively breaking Arctos"

**Comment by campmlc** [comment]
Elevating this to urgent- we critically need the ability to add "customID" to the search results download so that I can have a separate column for NK, isolated out of the concatenated ID field. Without this I cannot process loans, and I have one that my student needs to work on today.

Priority: Urgent, hindering ability to do critical curatorial work.

**Comment by ewommack** [comment]
@campmlc I think I've found what you need. 
When you get your search results, under the Tools menu go down and select the Download Identifiers. This should create a file with all of the IDs for your search results:
![Arctos_download IDs](https://user-images.githubusercontent.com/18562884/212984348-25355227-6b56-4acf-b534-4adf8aa63505.png)

**Comment by campmlc** [comment]
Thanks, @ewommack, that does work, as does Download parts. So that works for a curatorial work around. But that doesn't solve @jebrad issue from the original post, and as I'm thinking about it, it completely hinders the ability of any external collection to find matching records to our records. Most external and public users will not understand this option, whereas the option to download collector and /or collector number, preparator and/or preparator number, and any other ID of choice (e.g. an institutional catalog number or an AMNH number would solve this problem. We have so many records with corresponding records in other collections, and we need these to be disoverable from both ends. I cannot go to AMNH or USNM and search by NK number, as that is in a hidden field. And I have done everything I can to inform them this a problem and see if we can find a solution. And now we are doing the same thing, meaning they can't find all the Arctos records that match theirs.

**Comment by ewommack** [comment]
But won't the ID download find the relationship ID as well, so it would find the ID of the AMNH number in association with your catalogs?
The Tool link sends you to a page where you can select which Other ID you want to put in the download too, so you can customize before you make the download.

**Comment by dustymc** [comment]
I'll have to play with performance to find starting numbers, but I can't possibly cache everything that customID might involve so it will have to be [expensive](https://github.com/ArctosDB/arctos/issues/5080). The first few comments suggest a much more robust approach, at least for the most-common identifiers (certainly including NK), but nothing's going to happen until there's an Issue with some discussion. See also https://github.com/ArctosDB/arctos/issues/5354, IDK how to tell when conversation (should it happen) is done and schedule updates, but I can't run the thing that takes 5 days of CPU every 3 days, which seems to be about where this has been lately.

> ID download find 

Not for public users; I don't think there's any real problem making that more available, but that would also need a dedicated issue.

**Comment by dustymc** [comment]
I just added all identifiers to results (but it'll take a couple hours to show up in production).

They are currently dynamic, so expensive. If someone wants to nominate a few for caching (so they can be cheaper, which means they won't limit results) we can do that here, otherwise this can be closed.

Note that this adds almost six hundred results options. Please let this serve as yet another increasingly-desperate plea to form some sort of policy regarding identifiers.

(As an immediate workaround we might manually remove some from the results options; let me know if anyone wants a spreadsheet in which to do that.)

**Comment by campmlc** [comment]
Spreadsheet to remove some sounds good. I need collector number,
preparatory number, field number, NK, AF, IF, original identifier, and all
the institutional catalog numbers including formal ones such as UAM and
AMNH etc.

**Comment by dustymc** [comment]
for https://github.com/ArctosDB/arctos/issues/5448 - change ``subject`` to ``subject_matter`` and rebuild

**Comment by krgomez** [comment]
I have two remaining requesting for the UAM:Art custom search portal:

- Adding the subject matter attribute as a search option
- Adding the portfolio/series attribute as a search option

Thanks for adding verbatim date and removing subject from the search results!

**Comment by krgomez** [comment]
I noticed we still don't have subject matter as a search field in the UAM:Art custom search portal. I'm following up in case this request has been forgotten about. Subject matter is an essential search field, while portfolio/series is not as important to be able to search, but would still be nice to have there if possible.

**Comment by dustymc** [comment]
@krgomez next release:

https://arctos-test.tacc.utexas.edu/search.cfm?sp=uam_art

<img width="507" alt="Screenshot 2023-04-04 at 4 50 39 PM" src="https://user-images.githubusercontent.com/5720791/229946863-2826202f-b0d7-4436-9ee9-522f9420f6af.png">

I think everything else involves old-model identifiers, I'm calling this next release.

**Comment by krgomez** [comment]
Wonderful, thanks Dusty! I notice that if I start typing a term, a list of terms containing those letters does not appear like it does when we search culture of origin, for example. Also, when I click subject matter, the documentation box says "No documentation is available for subject_matter."
