### ISSUE TITLE
Arctos Report Template Request - printing barcodes

### ISSUE THREAD

**Issue by barke042** [ArctosDB/arctos#5469]
**Description of the report**
This is a request to support printing of barcodes as part of labels, if that is not currently supported. I didn't see any example reports on Arctos Reporter that referred to barcodes.

**Collection for which the report is needed**
JFBM:Fish

Our fish curator Andrew Simons currently prints labels for photodocumentation of specimens that include a 1D barcode that corresponds to the catalog number of the specimen being photographed. This is useful in his workflow as it allows naming of images by scanning.

Does Arctos currently allow for inclusion of 1D barcodes in labels, following any barcode standard? I can't find reference to this in the documentation. If not, a quick Google search turned up this Javascript library: [https://lindell.me/JsBarcode/](https://lindell.me/JsBarcode/). I have a query in with the curator to see what standard (e.g., Code 128) he is currently using.

Is anybody else interested in this functionality?

**Comment by barke042** [comment]
Update from the curator:
The barcode should be in Code 39 format. I think the code contains "JFBM-FISH-“ as static text followed by 7 digits with leading zeros. The idea is to ensure the barcode has the same number of digits regardless of the catalog number.

**Comment by barke042** [comment]
And here is an example of the original label we are interested in replicating:
[Screen Shot 2023-01-12 at 8.23.51 AM.pdf](https://github.com/ArctosDB/arctos/files/10405987/Screen.Shot.2023-01-12.at.8.23.51.AM.pdf)

**Comment by dustymc** [comment]
Using JS tools would require some sort of major change; the tools on which Arctos is built don't allow script tags in this environment. You can try saving this:

<img width="169" alt="Screenshot 2023-01-13 at 8 10 17 AM" src="https://user-images.githubusercontent.com/5720791/212366634-9b8de1ae-9aa6-4a0f-8e5d-45c687a61209.png">

And this will happen:

<img width="171" alt="Screenshot 2023-01-13 at 8 12 36 AM" src="https://user-images.githubusercontent.com/5720791/212366822-6112698e-6aeb-47f1-b71b-bf7058b8ba33.png">

I could potentially find some way to add JS capability, but I suspect that's a long and frustrating road.

I could potentially find some Java generator and install it, but that would make building/maintaining Arctos some amount less magical.

With code 3 of 9, I think you can just ``*upper(text)*`` and specify a font, but that's really limited, requires a careful approach, etc. - might work for this (or not), but it's not very elegant.

This could potentially be a good job for CSV-->word-or-something, but IDK how that might fit in your workflow or what it would require if it's usable in theory.

If the CSV-->program of your choice option isn't great, then I think this might be a good place to fire up a Task Force to discuss, even if it turns out to be the two of us. 

Completely unrelated to printing barcodes, I would 100% get lost in your identifiers. Is there a FISH component or not, are there zeros or not, who knows...

**Comment by campmlc** [comment]
We currently use Bartender or Word to print reports with barcodes, using csv data pulled from Arctos. It would certainly be great to use Arctos directly, but not if it is difficult.

**Comment by dustymc** [comment]
> Word to print reports with barcodes,

@campmlc can you share a sample word doc?

**Comment by barke042** [comment]
I will reach out to Andrew (the curator) to see if printing from CSV through a merge would be adequate for his needs. I have no idea what kind of volume/frequency we are talking about, and what level of effort that would merit to accomodate this use case.

**Comment by Jegelewicz** [comment]
@barke042 instructions for printing barcodes in MS Word are [here](https://github.com/ArctosDB/arctos/issues/1560#issuecomment-396389903). I downloaded this font - https://www.fontspace.com/bar-code-39-font-f28432 and this is what I get when I apply it to JFBM:Fish:38187 and JFBM-Fish-38187.  The colons do not translate well, so using the dashes makes sense to me.

![image](https://user-images.githubusercontent.com/5725767/212477254-5b0044f7-0b14-4270-a345-dc1d4c31a389.png)

Word doc attached, but you will need to download the font and install it to see the results.

[JFBM_barcode.docx](https://github.com/ArctosDB/arctos/files/10417923/JFBM_barcode.docx)

So - doing this label with some data and a mail merge in MSWord seems like a fairly easy task.

**Comment by Jegelewicz** [comment]
Also - I suggest dropping the leading zeros - they just mean that you will have to manipulate catalog numbers to get your barcodes - why waste the time? The barcodes are always the same size depending upon the font.

**Comment by Jegelewicz** [comment]
When building a label with mail merge - you can just use built-in Word tools - https://learn.microsoft.com/en-us/openspecs/office_standards/ms-oi29500/cc4b13c2-c09b-4545-a6ae-4509d943233e?redirectedfrom=MSDN

**Comment by dustymc** [comment]
See https://arctos.database.museum/Reports/reporter.cfm?action=edit&report_id=197 for an example of a report which uses an API to pull barcode images from an external service.
