### ISSUE TITLE
Add missing Japanese Prefectures

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#5482]
### Explain what geography needs created.

Five prefectures are missing from the Arctos Japan higher geography.  GADM shows 47 first-level units while Arctos has 42.

Attached is a csv of what appear to be the missing prefectures.  We need several for our collection.  Note that GADM appears to have misspelled Nagasaki Prefecture as Naoasaki; see: https://gadm.org/maps/JPN/naoasaki.html.  There is no Naoasaki Prefecture.  The spatial profile looks like Nagasaki. 

Please confirm if this is the correct issue to use to add geography and if you want a draft csv or not.

[Japan - missing prefectures.csv](https://github.com/ArctosDB/arctos/files/10419115/Japan.-.missing.prefectures.csv)

**Comment by dustymc** [comment]
Yes this is the correct template, but you've gotten ahead of me with the CSV. Using my workflow gives me a chance to detect any deviations from our 'do what GADM does' view and clean them up (I removed 'Prefecture' from these), doesn't leave me struggling to match data which I don't have, and provides a secondary confirmation that I haven't mangled anything in the form of your review. Please let me know if I can somehow clarify that in the template.

https://github.com/ArctosDB/arctos/issues/5417 complicates this - I had to manually delete Hyōgo because Hyogo exists. Your thoughts would be most appreciated there - I can see decent arguments for allowing whatever (makes any sort of comparisons with GADM, in or out of Arctos, much easier) and sticking with ASCII (do your volunteers know how to type ō?). Somehow resolving that would at least stop us from making larger messes, if we are in fact making messes.

I'm not entirely sure that Naoasaki isn't some legitimate but obscure transliteration, and we should really formally address the length to which we're committed to the 'do what GADM does' thing whether it is or not, but for now I manually deleted it as well.

That leaves me with this - please fill source_authority with a wikipedia link if I've got it right, or let me know what I mucked up.

[temp_geog_create(8).csv.zip](https://github.com/ArctosDB/arctos/files/10420683/temp_geog_create.8.csv.zip)

**Comment by sharpphyl** [comment]
Ok, let's see if you're getting me trained.  Attached is the csv with the source_authority for each prefecture.  I'll open a separate issue for the other countries where we need some missing areas and let you create the csv.

[temp_geog_create(8).csv](https://github.com/ArctosDB/arctos/files/10420733/temp_geog_create.8.csv)

As for ASCII characters, unless we copy/paste them into a search, we probably would never/seldom use them and certainly don't require them.

**Comment by dustymc** [comment]
done
