### ISSUE TITLE
Feature Request - more user friendly info on cache status

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#5511]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**

I've got some citations and parts that are set to autoload in bulkloaders that haven't loaded for a long time. In the past I've been directed to look at cache status:

https://arctos.database.museum/info/flat_status.cfm

which has never explained anything for me. I see a bunch of numbers and there is no explanation of how to interpret them. 

Can we get some explanation there? Eg "If X has more than X records then Arctos Flat is busy and will likely not be responsive to loading new records until... " ??

Or something? 

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.
medium

**Comment by campmlc** [comment]
I absolutely support this. I've never understood what I'm looking at in flat status.

**Comment by dustymc** [comment]
> citations and parts that are set to autoload

That's a different thing - [Component Loader Status](https://arctos.database.museum/info/component_loader_status.cfm). It's fairly predictable (because it's rate limited and doesn't get much use) and will provide time estimates.

>"If X has more than X records then Arctos Flat is busy and will likely not be responsive to loading new records until... " 

.. it gets around to it. The only possible way I could make this predictable would be to rate-limit it. That might be good for stability, I'm not opposed, but I think it would mean things would generally be significantly slower. (And the guesses would still be affected by entries and updates, of which there are many thousands on most days - that might be enough chaos to just make this impossible, I really don't know.)

>Or something?

I'm always up for clever ideas!

**Comment by campmlc** [comment]
I think what we need is an English translation? None of those numbers mean
anything to me.

**Comment by campmlc** [comment]
We need to find more resources, whatever those are, so we don't have to wait three days for the cache to update. Three days of downtime waiting on records to load is unacceptable - what do we need to make that better? @mkoo

**Comment by campmlc** [comment]
Also need some sort of error or notification when the cache us causing problems.

**Comment by dustymc** [comment]
@campmlc ref https://github.com/ArctosDB/arctos/issues/6106#issuecomment-1499854574 can you link that discussion, I can't seem to find it. 

>resources

In this case it's just database speed - I'm running things as fast as it can go without causing too many other problems. 

>some sort of error or notification when the cache us causing problems

I think that would just require infinite resources used in the weirdest way possible, but I'm certainly up for clever ideas.

**Comment by DerekSikes** [comment]
One idea is to plan such cache updates for weekends. This seems like the simplest and best step #1 to implement immediately.

**Comment by dustymc** [comment]
>weekends

That's always done to the extent possible.

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/6705
