### ISSUE TITLE
Feature Request - adjust other ID datatype

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#5529]
The maximum allowable column length in our version of postgres is 59 characters. There are three IDs that exceed that, and so break catalog record search results:

* ISEM: Institut des Sciences de l'Evolution Universite Montpellier
* RSA-POM: Herbarium of Rancho Santa Ana Botanic Garden and Pomona College
* ZRC: Lee Kong Chian Natural History Museum Zoological Reference Collection

I've removed them from the results options, but manually keeping a few things out of there probably isn't sustainable, and having identifiers that can't be viewed is just silly.

I'd like to do something with those types and reconfigure the table.

One is used once, one not at all, and one points to some apparently-unrelated registry - suggest moving them all to other identifier.

I'll interpret silence as enthusiastic approval and do something or another if nobody has better ideas in the next week or two.

**Comment by Jegelewicz** [comment]
> One is used once, one not at all, and one points to some apparently-unrelated registry - suggest moving them all to other identifier.

RSA-POM is used in 244 records that I have access to - https://arctos.database.museum/search.cfm?OIDType=RSA-POM%3A%20Herbarium%20of%20Rancho%20Santa%20Ana%20Botanic%20Garden%20and%20Pomona%20College&OIDNum=%25 and it doesn't have a url, so I don't know how the numbers above were calculated.

I think this is an important identifier to maintain because these represent duplicate sheets at the global scale (GBIF). At GBIF, this collection is designated as [RSA - California Botanic Garden Herbarium](https://www.gbif.org/dataset/9781ce05-2379-4a10-ab3b-c91346510df8). So perhaps this could be shortened to RSA: California Botanic Garden Herbarium

**Comment by campmlc** [comment]
If we had otherID metadata, the identifier could be other identifier or,
for example, "ZRC", and the agent would be the institution. This is the
route I prefer. That would drastically reduce our list of identifiers and
not require new ones be created every time we add a new external
institution.

**Comment by campmlc** [comment]
And ZRC is a Singapore collection that may come into Arctos.

**Comment by campmlc** [comment]
With catalog records at MSB: Bird, although not all are cataloged yet.

**Comment by dustymc** [comment]
done
