### ISSUE TITLE
help with relationships

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#5539]
The Bus 142 project is creating some situations I've not encountered before and I'd appreciate some advice.
When we were cleaning out the inside of the bus we found and cataloged parts that ended up being parts of the bus that our contract conservators are re-attaching to the bus. 

My idea was to create a relationship between the bus (https://arctos.database.museum/guid/UAM:EH:UA2020-008-0001) and the parts that are being re-connected. For example, these wheel wells (https://arctos.database.museum/guid/UAM:EH:UA2020-008-0076 and https://arctos.database.museum/guid/UAM:EH:UA2020-008-0077) were soldered back onto the floor of the bus (https://www.facebook.com/brhowardinc) and became part of the bus again. We decided to assign them a relationship of "same individual as" the bus itself. I was surprised to see that there was no reciprocal relationship that was automatically created in the bus record to show the other "same individuals," like what happens in agents when you make a relationship between two people.

Is that normal? Is it that way for a reason? I haven't been following too closely the other relationship issue (#5349) but maybe this is connected to that? Are there any suggestions for a more appropriate relationship to indicate this process of re-joining these items? We'll have at least four or five other pieces that will also be re-joined to the bus, so we want to make sure we've done it correctly.

**Comment by campmlc** [comment]
At least previously, same individual as relationships within your own
collection may take awhile to auto create the reciprocal, and like
relationships outside of your collection, there is usually an email
notification that links to records to approve.

**Comment by dustymc** [comment]
>no reciprocal relationship that was automatically 

Arctos won't make such assertions - but there's a notification which leads to a download (Unreciprocated Relationships in https://arctos.database.museum/directory.cfm) that can be fed to the bulkloader, or a [bot](https://handbook.arctosdb.org/documentation/bot.html) which you can enable if you want to magic reciprocals.

>like what happens in agents when you make a relationship between two people.

Those are related through Arctos keys - the reciprocal cannot be avoided (but I suppose it could be ignored), there's a limited scope (Arctos data records), and the idea that those have any metadata at all is pretty new. And I think the data themselves are generally straightforward (A is or is not B's student) and we don't really need the complexity.

Catalog item relationships are modeled so that they can work outside of Arctos (eg a relationship to an item in some online collection), to fuzzy ideas of items ("collector number one"), or about anything else, and the relationships are often anything but clear and unambiguous for all sorts of reasons. It's complicated, so so is the model.

You should request a documentation update ("same biological individual") and MAYBE that'll lead to another kind of relationship (I don't think so), and you might want to add the reciprocals (or free the bot to do so), but it sounds like you're on the right track to me.

**Comment by AJLinn** [comment]
Thanks for the input. I'll go ahead and create the reciprocal relationships from now on and will request a documentation update in a new issue.
