### ISSUE TITLE
[ geography task ] fix Asia spatial footprint

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#5604]
I'm checking up on our higher geography for old legacy data, cultural data, and other less than ideal localities with bad higher geography. I'd like to replace the bad footprint for Asia (see below). What's the best way since it came from fs_continent batch? Replace just Asia via the upload option? Or replace the whole continent shapefile? Let me know if you want me to email the latter @dustymc 

![Firefox_Screenshot_2023-02-04T03-44-26 145Z](https://user-images.githubusercontent.com/2523089/216746674-1f3505e7-25f4-46a8-b11c-49cb727f4293.png)

update: might have to send you either replacement for just Asia or the all the continents since ran into errors with all three upload options

**Comment by dustymc** [comment]
I think that's probably from trying to cram a ridiculous amount of data in a browser - Arctos won't allow invalid data.

```

arctosprod@arctos>> \d geog_auth_rec
...

Check constraints:
    "ck_spatial_footprint" CHECK (st_isvalid(spatial_footprint::geometry))

```

But if you want to send me something new as a shaepfile I'll load it (or you are of course welcome to that recipe - you'll need to be able to SSH to the VMs and psql to the DB).

And of course I'd like to move those Feature data to https://github.com/ArctosDB/arctos/issues/5597 because https://github.com/ArctosDB/internal/issues/222.

Yes I think the upload options should probably be removed, they only work in sort of fringe cases (square counties as WKT) and maybe not great then. I'll go active on this for that.

**Comment by mkoo** [comment]
I hate to add new issues to an existing one but based on our conversation this morning:

- [ ] request to make all continents assertable @dustymc 
- [ ] Antartica is a country (non-sovereign according to GADM) @dustymc (done)
- [ ] @mkoo assign Borneo, Africa, etc to appropriate continents
- [ ] @mkoo send Asia shapefile and see if that can be handled (assuming not just a web visualization glitch but data one)

**Comment by dustymc** [comment]
@mkoo I can assign (spatially, but slowly because https://github.com/ArctosDB/internal/issues/222) if that helps

If we're going to make continents assertable then we can just use whatever Asia is in that. I think I've used https://figshare.com/articles/dataset/Continent_Polygons/12555170/3 before, not exactly "authority" but maybe close enough. (And this still needs a dedicated/formal issue including updating of https://handbook.arctosdb.org/documentation/higher-geography.html)

**Comment by mkoo** [comment]
[continentAsia.zip](https://github.com/ArctosDB/arctos/files/10736243/continentAsia.zip)
zipped Asia shapefile - WGS84

**Comment by mkoo** [comment]
> @mkoo I can assign (spatially, but slowly because [ArctosDB/internal#222](https://github.com/ArctosDB/internal/issues/222)) if that helps

Bc this is still mysterious, I can just update Borneo for now and I'll leave the rest to you and the spatial molasses (for now)
> 
> If we're going to make continents assertable then we can just use whatever Asia is in that. I think I've used https://figshare.com/articles/dataset/Continent_Polygons/12555170/3 before, not exactly "authority" but maybe close enough. (And this still needs a dedicated/formal issue including updating of https://handbook.arctosdb.org/documentation/higher-geography.html)

I dont care if you'd rather do that instead of just Asia-- as long as it doesnt look insane!
Let me know when you have a replacement up to see if it passes the visual inspection!
