### ISSUE TITLE
Agent Split Request - William Perry

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5612]
Use this template if you believe an agent represents more than one person or organization.

**Agent that represents more than one person or organization**
Navigate to the agent page, copy the url and paste it below:

https://arctos.database.museum/info/agentActivity.cfm?agent_id=21318610

**New Agent**
Provide details that should be associated with a new agent to be split from the agent above.

 - **Agent preferred name:** 
 - **Agent details:**

**Reason for split**
Please provide the reason you believe that this agent represents more than one person or organization.

The dates indicate that this is more than one person

**Affected Collections**
Please list the collections that will be affected and would use the new agent. If possible provide Github usernames for those who might have an interest in the split.

UAM:EH - @AJLinn maybe dates are incorrect, but this person is also labeled as a tattoo artist and scrimshander. Could be both, but not for 200 years...

**Agent change tool**
For any collection that needs to change to the agent created as part of this split, follw the instructions at [How to Batch Update Agents](https://handbook.arctosdb.org/how_to/How-to-Batch-Update-Agents.html)

Please add this issue to the Agents Project.

@ArctosDB/agents-committee

**Comment by AJLinn** [comment]
Please ignore any of the UAM:EH objects with a 1741 as a start date. When we migrated our collections into Arctos we chose that as an arbitrary start date for all "historic" objects (aka, those made by non-Indigenous creators) as that was the date of arrival by the Russians in Alaska. We're trying to update them but there are thousands... I'll correct the two records associated with this agent.

I reviewed this agent record and added birth and death dates, plus a bit more in the remarks to fill out more of his biography. What else does the agents committee want? This seems like a fine agent record now.

**Comment by dustymc** [comment]
>fine agent record now

Yes.

>What else does the agents committee want? 

From my perspective: We need data which will differentiate agents from other agents, particularly those who might have similar names. It seems difficult or impossible to fully quantify what that means, but I think it involves some sort of explicit assertion. AgentZ (still) exists because they identified something in 1874, but with enough digging it turns out that the ID date came from some other date which came from some other date which wasn't a date at all, but a part of a bracket around a very loose assumption, so.....

There's just nothing in there that makes me think that AgentZ is or is not the same entity as the AgentA that's scribbled on my tag (and so they should both be verbatim agents - and I think this still describes most of the agents in Arctos).

MAYBE 'born city@year' won't fully disambiguate them (perhaps because I have a different piece of not-entirely-conflicting data), but to me it looks like a very good starting point. That plus a died on date surely still leaves some ambiguity, but even for really common names I think it must be sufficient most of the time. IDK if this is really the 'do awesome things' bar, but it looks like it could be.

My only potential complaint is the AKA name looks like a misplaced 'job title' but if that's what his friends called him it's great (and if it's really misplaced its still pretty great...).

@lin-fred

**Comment by Jegelewicz** [comment]
> objects with a 1741 as a start date. When we migrated our collections into Arctos we chose that as an arbitrary start date for all "historic" objects

start and ended dates are no longer required - perhaps we could look at removing those from events used only by your collection?

**Comment by AJLinn** [comment]
> My only potential complaint is the AKA name looks like a misplaced 'job title' but if that's what his friends called him it's great (and if it's really misplaced its still pretty great...).

That was a quote from the article listed in the URL - his son said he was known as that, so figured it was a good aka

> 
> objects with a 1741 as a start date. When we migrated our collections into Arctos we chose that as an arbitrary start date for all "historic" objects
> 
> start and ended dates are no longer required - perhaps we could look at removing those from events used only by your collection?

YES PLEASE! Let me know what we need to do to make that happen. It's so confusing.

**Comment by Jegelewicz** [comment]
@dustymc see https://github.com/ArctosDB/arctos/issues/5612#issuecomment-1421313824 Possible?

**Comment by Jegelewicz** [comment]
> name remarks a workable compromise??)

How about the same info we can collect for addresses?

begin date, end date, remark

after all, people's names change and even though the dates may go mostly unused, they can come in handy in certain situations.

**Comment by dustymc** [comment]
done?
