### ISSUE TITLE
Better UI feedback with Search Results

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#5641]
Problem: When I search catalog records on values that return no results, nothing at all happens on my UI. This happens when I am logged in, when I have customized and expanded my search options so that the search table takes up all real estate and the results pane at bottom is not visible.

Expectation: That something would happen telling me my search has yielded no results. At the very least, the view should jump to the results pane which says "No matching records found" in small print. But ideally, this statement should be more prominent, and certainly should be visible after a failed search no matter how I have my search pane customized.

Priority: High. Currently, it looks to users like Arctos is broken.

**Comment by dustymc** [comment]
If you are seeing something other than

<img width="214" alt="Screenshot 2023-02-14 at 3 44 58 AM" src="https://user-images.githubusercontent.com/5720791/218728728-4c83aedf-0306-4e48-9b1f-a26b1eb0d7c2.png">

then your browser is broken.

**Comment by Jegelewicz** [comment]
I noticed this morning when I did a search that yielded no results the screen did not scroll down to the results section. So while I did get this

![image](https://user-images.githubusercontent.com/5725767/218781900-1c37dd9b-a7a3-4b70-97b6-0fc4c3c0592f.png)

I had to manually scroll down there to see it. Anyone else might just think nothing happened.

**Comment by campmlc** [comment]
Yes, that is the problem. The screen needs to jump to the results section showing that there are no results, and it doesn't do that. And if you have anything other than the default search options opened up, or you are on a small screen, you can't necessarily see the results section, so it looks like nothing happens. 
Action needed: For any search, even one that yields zero results, have the screen view toggle to the results section. @dustymc

**Comment by Jegelewicz** [comment]
I think it would be good for the screen view to toggle to results as soon as a query is submitted. If the results take a while, you also don't know you are getting the streaming blue dots because you have to scroll down there, it just seems like nothing is happening.

**Comment by campmlc** [comment]
Agree.

**Comment by mkoo** [comment]
Other options maybe to anchor the search results section, so when results are returned, the users web view moves down to the anchored results section. And a pop-up or other windowed results for no returns would be good too:
"Your query returned no results. Try searching again with fewer or different parameters. "

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/discussions/5016

**Comment by Jegelewicz** [comment]
@dustymc we talked about this today at tea. If possible, we would like to see the following:

1. Display something other than `Showing 0 to 0 of 0 entries (filtered from NaN total entries)` BEFORE a search has been initiated. Suggest `No query submitted`.
2. Once the `Submit Query` button has been selected scroll down to the results so we can see the 3 scrolling dots and know that something is happening.
3. If a query returns NO results, instead of `Showing 0 to 0 of 0 entries` display `No matching records found` AND scroll down to the results so that the user is aware that the query was submitted without needing to scroll down.

I think that covers it - let me know if anything is unclear or if you want separate issues for these things
