### ISSUE TITLE
Hide encumbrance summary for non-logged in users

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#5643]
Sorry if this is already in another issue, but public users can view an encumbrance summary, even when not logged in. 

https://arctos.database.museum/info/encumbrances.cfm

Full user names are on view (encumbering agent) as well as encumbrance remarks and record count. Even these snippets could reveal sensitive information despite the records being partially/fully masked
e.g, 

- how many human remains records are masked (which could have optics issues esp if a museum has repatriated remains but archives records, it may 'read' as if they still have them in their holdings) 
- "scoop" potential: perhaps a researcher's name and project and taxa they are currently working on are recorded
- even shorthand remarks like @Jegelewicz records, 'Keep the public view clean' - which is not sinister! but could be interpreted as such

Can we keep this page restricted to people with manage permissions?

![image](https://user-images.githubusercontent.com/11336485/218226294-964ba523-2757-47b4-b6e5-788140bf5138.png)

**Comment by campmlc** [comment]
Yes, strongly second this.

**Comment by dustymc** [comment]
That form exists only as a transparency mechanism, it could not make sense to allow access for only "us." ("We" have even more transparent tools).

I very mush like the idea of not completely hiding anything (so that a researcher for whom the encumbrance might be lifted could know there's SOMETHING potentially of interest in a collection) but the details could be adjusted. Maybe we need yet another 'internal remarks' field?

**Comment by ebraker** [comment]
UI group voted to removed from public view 2023-03-27
