### ISSUE TITLE
Blocked from test

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5646]
I need to access test but I cannot remove the block

Your IP (76.18.94.122) or organization has been blocked.

I attempted the unblock, but to no avail. I am able to access production.

**Comment by dustymc** [comment]
```
 Your IP has been removed from the blocklist. 
			  <h1>A full release may take up to five minutes.</h1>
```
???

**Comment by Jegelewicz** [comment]
Still getting this

![image](https://user-images.githubusercontent.com/5725767/218536392-00c59274-5331-4596-8b4f-3ba4ceff1dd1.png)

**Comment by Jegelewicz** [comment]
Got past that, but now my password doesn't work. Attempted to reset and it appears that nothing happens. I haven't received email.

**Comment by Jegelewicz** [comment]
I was able to log in last night and changed my password, but when I returned this morning my password didn't work again. When I selected password reset, I was redirected to the "I agree" thingy instead of the password reset message. I was not asked for my username and email address - just sent here.

![image](https://user-images.githubusercontent.com/5725767/219077581-124eebc1-ac80-4fa1-99f9-a7a2d838ec0a.png)

**Comment by Jegelewicz** [comment]
So, I clicked I agree again and got the expected form, completed it an selected request password - then nothing seems to happen.

![image](https://user-images.githubusercontent.com/5725767/219078189-a9cf302a-8d64-4a8d-b912-a83353e7b527.png)

**Comment by Jegelewicz** [comment]
Also received no email.

**Comment by dustymc** [comment]
Yes of course everything is subject to accepting terms.

You didn't submit anything - test can be a little difficult to wake up.

**Comment by Jegelewicz** [comment]
But I had already accepted the terms before attempting to log in!

**Comment by Jegelewicz** [comment]
And now when I go to test I see this. click the agree button and nothing happens.

![image](https://user-images.githubusercontent.com/5725767/219096692-766ffa1b-e138-4c9f-b800-5528930d45d5.png)

**Comment by Jegelewicz** [comment]
OK - guess you are right about waking up - after posting the above, it looks like I can finally attempt a log in....

**Comment by Jegelewicz** [comment]
Just made another attempt and when I select request password, nothing happens.

![image](https://user-images.githubusercontent.com/5725767/219097257-7816e200-65c9-4c16-970f-6036b4fe61ce.png)

I feel lost in an endless loop of "this isn't the test you are looking for"...

**Comment by Jegelewicz** [comment]
So, no, I haven't made a request, because apparently that is not possible.

**Comment by dustymc** [comment]
>already accepted 

You did something to cause a new session.

I've been running test pretty hard since early this AM, it's been fine.

I fired up another me and was able to recover and use a password no problem, no delays, everything just worked as it should.

<img width="821" alt="Screenshot 2023-02-15 at 8 53 41 AM" src="https://user-images.githubusercontent.com/5720791/219098316-f9ea8596-f961-42f7-ba31-76351e79f64c.png">
<img width="776" alt="Screenshot 2023-02-15 at 8 53 57 AM" src="https://user-images.githubusercontent.com/5720791/219098344-484530ab-71dc-44ba-9338-7e9a57df5ee7.png">
<img width="181" alt="Screenshot 2023-02-15 at 8 54 19 AM" src="https://user-images.githubusercontent.com/5720791/219098378-94609384-bf05-439d-a18b-cb14411ae2ed.png">

(I don't get email, have to cheat on that step - @mkoo )

This is PROBABLY the network-or-whatever, but are you sure you're not blocking something?

**Comment by Jegelewicz** [comment]
HMMMM - yes, it may be my firewall. I will investigate.

**Comment by Jegelewicz** [comment]
OK cleared my cache and this time received the "email has been sent" thing. I'll wait a bit to see if I atually get an email....

**Comment by Jegelewicz** [comment]
OK that worked, but I guess changing my password is what screwed things up yesterday? I will try again today and we will see what happens.

**Comment by Jegelewicz** [comment]
OK - I made this in test - https://arctos-test.tacc.utexas.edu/search.cfm?guid=UAM%3AArt%3AUA0693-0001 it needs a flat update to look as expected.
