### ISSUE TITLE
Media and media_part - can we consolidate?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5650]
In the observation interest group this morning, @ccicero suggested that we find a way in include physical media in "media" rather than having two ways of associating "media" with catalog records.

For example, physical photographs are "media parts", but digital images are "media". Rather than use a part for physical photographs, could we use media without the associated url? This would give us all of the media relationships and labels useful when talking about media without needing to re-create them as part attributes for media - https://github.com/ArctosDB/arctos/issues/5249 or trying to ensure that people understand what is an actual skull and what is an image of one - https://github.com/ArctosDB/arctos/issues/3882 

This also relates to #5326 

What is media in Arctos? - https://handbook.arctosdb.org/documentation/media.html

> Media are any digital objects (such as photographs, sound recordings, or three-dimensional renderings of objects) that can be related to data items in Arctos.

So perhaps this just isn't feasible, or perhaps we need to think differently about "media"?

Please add thoughts to this issue.

**Comment by campmlc** [comment]
What about media associated with parts, such as a photo of a skull or of
part of a cultural object? Do we want to have a way to tag media to parts?
And physical media removed from the parts table would still need part
associated metadata like preservation and loan history?

**Comment by dustymc** [comment]
>just isn't feasible

Correct, those are two types of data objects because they're two types of data.

>could we use media without the associated url?

It's not a URL, it's a URI - in case that somehow addresses whatever it is you're trying to do??

> needing to re-create them as part attributes for media 

Someone/everyone isn't understanding something really fundamental. ( I think people are using nodes they don't need to for reasons I don't understand????)

>physical media removed from the parts table would

... and maybe we're also NOT using nodes that are designed to do things we want to do, still for mysterious-to-me reasons????

Can this be refactored into something like a functional requirements document? I can't quite grasp WHY this sort of thing keeps coming up, I just see round pegs refusing to get hammered into square holes....

**Comment by Jegelewicz** [comment]
> functional requirements

I started a massive mess here.

But let's talk about what we are wrestling with. Right now, how can we do the following? And more importantly how can someone completely unfamiliar with Arctos perform these searches and get reasonably reliable results?

1. Find all skulls EXCLUDING images of skulls (whether digital OR physical)
2. Find all skulls AND all images of skulls (whether digital OR physical)
3. Find only images of skulls (whether digital OR physical)
4. Find only physical images of skulls
5. Find only digital images of skulls

@ccicero what else?
