### ISSUE TITLE
Do not require mangling DOIs

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#5726]
I'm trying to add a publication with the DOI https://doi.org/10.1126/sciadv.abn0250. The crossref worked fine but when I try to save it gives this error: 

DOI https://doi.org/10.1126/sciadv.abn0250 failed validation with StatusCode 404 Not Found

I copied the DOI into a browser and the link worked.

???

**Comment by dustymc** [comment]
>Paste a DOI (the ID only - no prefix)


You need "10.1126/sciadv.abn0250"

And FWIW partial identifiers are a nuisance (at best) for all sorts of reasons and I'd love to completely purge them from the system but any kind of change seems to be met with resistance lately - https://github.com/ArctosDB/arctos/discussions/5310 could use a champion....

**Comment by dustymc** [comment]
I'm taking this next task - the form should handle *the* one unambiguous identifier, the thing that you can copy from your browser's URL bar, not insist on some weird little piece of it. 

(And - like https://github.com/ArctosDB/arctos/issues/4604#issuecomment-1448966173 - maybe we can deal with little weird bits-n-pieces too, because some people like - uhhh - torturing themselves?? IDK, but they insist they like it...)

**Comment by ccicero** [comment]
Thanks @dustymc You're right, I copied the full URL but it seems like Arctos should be able to handle that.

**Comment by dustymc** [comment]
## Source

https://github.com/ArctosDB/arctos/issues/5726

## Summary

Use full DOIs in publications

## User Interface Changes

Use full identifiers; remove the need to disfigure identifiers.

## Data Structure Changes

None, just change the check.

**Comment by Jegelewicz** [comment]
I agree.
