### ISSUE TITLE
Code Table Request - Catalog Record Attribute preparation date

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5748]
**How to Use This Form**

**Goal**
Record the date a cataloged item is prepared for permanent storage in the collection. See also https://github.com/ArctosDB/arctos/issues/5600#issuecomment-1433829408

**Context**
Collection managers have been using [verbatim preservation date](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type#verbatim_preservation_date), but the definition of the term does not support that use.

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type

**Proposed Value**
preparation date

**Proposed Definition**
The date when the preparator finishes preparing the specimen for collections use, i.e., it is mounted, stuffed, taxidermied, etc. and ready to be used for cataloging, research, programming, etc."

**Collection type**
All

**Attribute data type**
date (or should we go with free text and assume the determined_date is the date?

**Attribute value**
[ For categorical attributes, code table controlling value  ]

**Attribute units**
[  For number+units attributes, code table controlling units  ]

**Available for Public View**
Yes

**Priority**
[  Please choose a priority-label to the right.  ]

@wellerjes @ebraker @ccicero @campmlc please add to this.

**Comment by ccicero** [comment]
I think free text for date is good as we may not know the exact date. I've been putting free text dates in a standardized format in the value for verbatim preservation date, and determination date is the same but in date format.

**Comment by Jegelewicz** [comment]
Usage of verbatim preservation date

GUID_Prefix | Count
-- | --
CHAS:Bird | 310
CHAS:Ento | 4
CHAS:Herb | 713
CHAS:Mamm | 31
CHAS:Teach | 125
CSULB:Bird | 14
DMNS:Bird | 8508
DMNS:Mamm | 5509
DMNS:Para | 1
MSB:Bird | 1
MSB:Host | 74
MSB:Mamm | 20
MSB:Para | 166
MVZ:Bird | 3346
MVZ:Herp | 2082
MVZ:Mamm | 411
NMMNH:Ento | 3073
NMMNH:Herb | 863
NMMNH:Herp | 5
NMMNH:Mamm | 105
UAM:Herp | 14
UAM:Mamm | 4692
UNR:Mamm | 19
UTEP:Bird | 159
UTEP:Herp | 2233
UTEP:HerpOS | 110
UTEP:Mamm | 1
UWBM:Herp | 1
**Total** | **32590**

[ArctosDatauQZ84KG7vs.csv](https://github.com/ArctosDB/arctos/files/10875967/ArctosDatauQZ84KG7vs.csv)

**Comment by dustymc** [comment]
>preparing the specimen

You're asking for an Attribute which applies to an idea (cataloged item), but in the definition you're saying it applies to parts (things). Which is it? 

>finishes

I don't think this is final, it's just one step that lead up to whatever's there now, and an item could have lots of them (frozen, skinned, preserved, de-bugged and re-preserved, sample removed from stuffed skin, ....)

**Comment by Jegelewicz** [comment]
> You're asking for an Attribute which applies to an idea (cataloged item), but in the definition you're saying it applies to parts (things). Which is it?

Yes, perhaps this would be better as a part attribute.... 

> I don't think this is final, it's just one step that lead up to whatever's there now, and an item could have lots of them (frozen, skinned, preserved, de-bugged and re-preserved, sample removed from stuffed skin, ....)

I originally entered

`The date a cataloged item is prepared for permanent storage in the collection.`

But then thought I should add what was originally requested to start off. And if this were a part attribute (which I think does make more sense) then,

`The date the part was prepared.`

**Comment by dustymc** [comment]
>cataloged item is prepared for permanent storage in the collection

Yea, concepts don't stack nice on shelves...

>prepared

That now feels too restrictive. Some preparator carefully following some methodology controls what can be done with a part, but so does some klutz OOPS!-ing it into the big vat of formaldehyde. Is this just more values for https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecpart_attribute_type#preservation?

**Comment by ccicero** [comment]
I would be ok with preparation date as a part attribute although it would be a bit more work because you'd have to enter preparation date for each part separately as opposed to once for the cataloged item (see last comment regarding bulkloading). But it would allow you to enter different preparation dates for a given part which is useful. And not all parts may have the same preparation date - e.g., you may quickly take tissue from something on date X but then prepare the specimen on date Y. 

If we do that, it gets back to making it easier to bulkload by adding more columns including part attribute date and determiner. It's very cumbersome to bulkload records and then separately bulkload the part attributes. Related issue: https://github.com/ArctosDB/arctos/issues/5193

**Comment by dustymc** [comment]
>Related issue: https://github.com/ArctosDB/arctos/issues/5193

Yes, and per today's meeting that will happen as soon as I can get there, hopefully within the next couple weeks. That's currently at 713 columns, feel free to claim some more (~600 available) for whatever's most useful, but please do it quickly!

**Comment by Jegelewicz** [comment]
Does this need to wait for #6171 or can we add the part attribute now? @ccicero do you still want this? And if we do this, are we going to do anything with data in verbatim preservation date?

**Comment by dustymc** [comment]
This definitely needs more discussion - this idea (but not this issue, I think there are several near-duplicates) was discussed at last CT meeting. We think perhaps there's some distinction between 'life events' and 'curatorial stuff' but a big-picture roundup  is needed. 

This might be a date on some value of https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type#processing_history

**Comment by ebraker** [comment]
I like the idea of adding "prepared" to processing history. Right now there are values for "cataloged" and "inventoried", so if we add "prepared", the term would be broad enough to incorporate many different collection types (e.g., biological specimens, removing fossils from matrix or a jacket, perhaps repair history and conservation-related tasks) . 

Since this table has the full suite of 'method', 'date', and 'remarks' fields, it would allow users to add a prep date that relates to the entire record vs individual parts (though some may want this level of detail?). I always stuff things like pre-existing injuries encountered during specimen prep into remarks, and it would make sense to have a dedicated field to add these sorts of notes.

**Comment by Jegelewicz** [comment]
> I always stuff things like pre-existing injuries encountered during specimen prep into remarks

Well, now you could use https://github.com/ArctosDB/arctos/issues/6120

!

**Comment by campmlc** [comment]
We also support this, as we record preparation date  on all data sheets, and it is important for determining tissue quality.

**Comment by Jegelewicz** [comment]
@campmlc which proposal do you support? I think there are currently three:

## The original request

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type

**Proposed Value**
preparation date

**Proposed Definition**
The date when the preparator finishes preparing the specimen for collections use, i.e., it is mounted, stuffed, taxidermied, etc. and ready to be used for cataloging, research, programming, etc."

## The part attribute version
 - https://github.com/ArctosDB/arctos/issues/5748#issuecomment-1452648473

just put the date in the determined date for any given part preservation

## The processing history version
 - https://github.com/ArctosDB/arctos/issues/5748#issuecomment-1614757441

**Table**
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctprocessing_history

**Proposed Value**
prepared

**Proposed Definition**
Information pertaining to any preparation event, generally when and by whom the parts were prepared (often recorded in a written ledger). Method should be used to record the type of preparation made (for example, "mounted, stuffed, taxidermied"). Date should be the date the preparation event took place and determiner should be the Arctos Agent who performed the preparation.

**Comment by campmlc** [comment]
Sorry, I was going off the issue title, which is for a record attribute. For MSB, this is what we need for initial data entry at least to flag those records which were processed on the same date as collection and those that are cataloged after processing. But we could also use a part attribute in cases in which tissues were processed sometimes years after the collection event. So it would be ideal to have both attribute and part attribute, honestly, and let collections decide which fits their workflows. The record attribute could be entered at time of initial data entry to record the date the whole specimen was prepared, and if any parts deviate from that the part attribute could be used. 
Since I didn't even know we had a processing history code table, and it's certainly not in our institutional workflow, I can't address whether that would work, but we don't have workflows to track anything except tissues after initial cataloging, because of the volume of incoming material.

**Comment by campmlc** [comment]
@AdrienneRaniszewski

**Comment by Jegelewicz** [comment]
FWIW - processing history is a catalog record attribute with values controlled by a code table - seems like it would be fairly easy to add to the workflow?

**Comment by campmlc** [comment]
Not really - not for us anyway. We don't have the resources to track each of these steps; so the only relevance of the processing history attribute to MSB would be as a place to record preparation date. And this doesn't match our field data sheets, which record this value as "preparation date". We would prefer to have a value that students can easily interpret from the actual recorded data.
Also, given the number of record attributes and part attributes that MSB is currently capturing and the number we anticipate adding in the near future, ideally we'd want a single attribute to minimize whatever is necessary to record these data.

**Comment by campmlc** [comment]
Given these are curatorial values, and not intended for public consumption, is there any problem with providing all three tools and letting collections decide how it fits in their workflows?

**Comment by campmlc** [comment]
@mkoo

**Comment by Jegelewicz** [comment]
@campmlc preparation date as requested and processing history are both catalog record attributes, so equivalent from a "how many things do we have to enter" standpoint.

It seems denormalizing to have two attributes that do the same thing and I don't think we can ever accommodate everyone's data sheets with an exact data entry "field" in Arctos. From my perspective, the processing history attribute with a new value of preservation makes sense, but I am definitely not the final say and @ccicero (who started this issue) should weigh in as well.

The second option is already there - just add a determination date to whatever preservation is being added to a part.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
We have not started adding preparation dates yet, but will need to in the near future. I support adding preparation into the processing history code table. Verbatim preservation date does not work at all for paleo specimens.

**Comment by dustymc** [comment]
>is there any problem with providing all three tools and letting collections decide how it fits in their workflows?

Avoiding this is more or less why databases were invented....

> Verbatim preservation date does not work at all for paleo specimens.

I'd think not!

I don't think this scattered Issue is resolvable, there are various pathways appropriate for various possibilities above, anyone wanting to use one of them can open a focused Issue. Closing.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
New issue created: https://github.com/ArctosDB/arctos/issues/7185
