### ISSUE TITLE
Help Pages

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5763]
I am trying to get Help Pages added for everything that I can in Manage Directory. I have added a page for Loans - Create

![image](https://user-images.githubusercontent.com/5725767/223753140-1aaddadd-1fdb-458d-9547-59c45750c52d.png)

Help page url - https://handbook.arctosdb.org/how_to/How-to-Create-a-New-Loan.html

But no Help shows up on the menu

![image](https://user-images.githubusercontent.com/5725767/223753670-a201af20-939e-4730-924e-9a66d81aac99.png)

Before I spend a lot more time on this - I want to make sure that I am doing the right thing. I am trying to prepare for the Documentation-A-Thon next week and prioritize pages with no Help Page, if this isn't the right place to put these things - I'd like to know ASAP.

**Comment by dustymc** [comment]
For next release:

>Link to handbook or other documentation. Must be attached to bare file path.

and I'll figure out what's going on with the empty menu item.

**Comment by Jegelewicz** [comment]
> bare file path.

Please define for me!

**Comment by dustymc** [comment]
``/accn.cfm`` not ``/accn.cfm?action=createForm``

and maybe this needs clarified as well?

> Absolute path to a form. The bare path (example: /place.cfm) must exist for Arctos to function, but "subpages" (example: /place.cfm?action=geog) are allowable, and often necesary to make appropriate directory listings. 

How can that be made more clear?

**Comment by Jegelewicz** [comment]
OOF - so potentially, the help page needs to get added to something that doesn't have a Title in the Tools Directory? BUT it will still show up in the thing that does that shares the bare file path?

**Comment by Jegelewicz** [comment]
This is kind of a bummer when two different activities share a path - help may not be easy to suss out?

**Comment by dustymc** [comment]
>help page needs to get added to something that doesn't have a Title in the Tools Directory? 

Yes, most of Arctos doesn't have a direct access path??

>How Tos i

That doesn't seem entirely appropriate - some (most? all?) of those carry significant bias - they tell you how some user uses some 'node' but not really what the node does. And the expectation (IDK if it's been met) is that any activity might have many how-tos (again, because they're from a limited viewpoint), where this is necessarily a 1:1 ratio. Easy to change this so whatever, but seems like something that needs a hard look with diversity and sustainability in mind.
