### ISSUE TITLE
last edited by is wonky

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ArctosDB/arctos#579]
```
query voleguy
get uam
wut?
```

Original issue reported on code.google.com by `dust...@gmail.com` on 20 Aug 2012 at 10:14
- Blocked on: #728

**Comment by dustymc** [comment]
Copying https://docs.google.com/document/d/1O9a4WjhRE8BrnuhRx4ti8Y4vk2jaBNThvXlKjAN8flw/edit from https://github.com/ArctosDB/arctos/issues/579#issuecomment-134426539 directly into this thread.

(referencing http://code.google.com/p/arctos/issues/detail?id=579)
Comment#2 needs expanded and addressed before anything happens here.
What precisely (in the form of relationships and rows) is an edit?
What precisely should happen when there is an edit, whatever that turns out to be?
If the answer to (2) is “throwing a username and timestamp on a specimen,” then you can stop reading now. If, however, we’d like to know “what was done to this MVZ record, or why,” this gets complicated. If I…
* edit geography1
* move specimen from geography1 to geography2
* edit locality1 (child of geography1)
* move specimen to locality2, child of geography3
* edit geography1
* move specimen to new collecting event, child of locality1
it’s not trivial to understand which of those edits has changed the specimen from “original” to “current.” The “edited” data and the edits themselves may or may not have anything to do with any object in it’s current form - you have to replay everything to understand what’s ACTUALLY affected the specimen.
There are more or less three ways of approaching this:
1) Oracle’s audit trail - we use it now, and it’s simple/cheap/reliable, but to get very “deep” (eg, “how does this edit to a [taxonomic classification used in an unaccepted identification/agent name/agent merger/geography entry/etc.] affect specimens?”) you’d need an Oracle DB forensicist and some very expensive software. Lam and I can more or less find our way around in there, but doing so is exceedingly slow and perhaps not very precise - certainly not something we can do to answer routine “what happened here?” questions. 
2) Trigger-based “grab old and new” values “auditing” - we do this for geography, and it’s proved useful FOR GEOGRAPHY - it’s little different than the raw audit data from any other perspective (eg, from specimens). It’s expensive in terms of development (requires code), storage (at least triples storage requirements), performance (>triples DB load), and reliability (“our” code is reviewed by us; Oracle built-in functionality is reviewed by eg banks and governments).
3) A wikipedia-like versioning model, which has little applicability to a deeply-relational database.
Something like (2) (or even 3 if we can at some point push CSV updates to IPT - https://basecamp.com/1772144/projects/81018-data/messages/10517802-dynamic-record) might be implemented on FLAT, which is very far from an ideal solution but might serve to adequately address most “what changed?” types of questions. Note that (like the current implementation) this would miss updates to anything not in flat.
I have no great ideas, but this is not a trivial issue and it will almost certainly not have a trivial solution. 
The current implementation trips the “last edited” flag when something updates FLAT, and updates to FLAT don’t necessarily change text data - agent merges (probably what caused Comment #4) often switch in a “new” (duplicate) agent with an identical (or near-identical) preferred name (as collector, identifier, etc.), for example. 
Agent, geography, and taxonomy/classification mergers/updates account for most changes, and only UAM (the schema owner) has access to all of those data. SQL updates made by Lam and I use the same account for the same reasons. Some of those changes might be traced back to the person who requested them (rather than the Oracle user who made them), but that would be non-trivial. I don’t think it’s practical or possible to disallow changes by non-person operators. That said, most “changes” by UAM are not really “changes” (call them refinements), and so just ignoring UAM’s changes might be an improvement.
Lastedit is stored as operator (=Oracle account) name for performance reasons. Translating that to an agent name has a performance cost - one that we could not pay without sacrificing stability when the issue was filed, but perhaps possible now that TACC has upgraded Oracle. This is also part of a broader issue - given un- (or less-) limited computational resources, we could do lots of cool things, but as long as we have limits we’ll have to make compromises to stay within them. Hopefully this is something that can be addressed in the planned proposal.

**Comment by Jegelewicz** [comment]
> That said, most “changes” by UAM are not really “changes” (call them refinements), and so just ignoring UAM’s changes might be an improvement.

Are they refinements that should be communicated to the user who entered the data so that those refinements would not be needed in the future? I too have been confused bay all the UAM edits to the UTEP data....

**Comment by Jegelewicz** [comment]
> 
    What exactly constitutes a "specimen edit"?
  
For me, this would be anything that changes my data significantly. Was my collection locality, identification, or collector information changed in a way that now means my data isn't what I expect it to be anymore? I think that we all understand the sharing of agents, localities and taxa, but I think we might be less clear on what happens when changes are made that affect our specimens. Changes we may not discover until some time far after the time the changes were made. If I have a specimen who's collector is significantly edited (middle name added or birth/death date) and that person is not really my collector, it would be nice to figure that out at the time the change occurs rather than when a curator calls me asking what the heck happened to our data. Off the top of my head, these are the things I think I would like to know about:

Any change in a taxon assigned to my records
Any change in an agent assigned to my records
Any change in a locality assigned to my records
Any direct edit to one of my records.

> What should I do when that happens?

A notification would be good enough for me. Then I could decide if the change is OK or if I need to do something to make my data correct again. I see this as a check on the shared stuff. So, just as we get notifications about the merge of agents or the changes to higher geography, maybe we need notifications for a few other things. No idea if this is possible, but I really dislike the idea of all these edits to my records with no notification that something was done.

**Comment by campmlc** [comment]
Just had this issue come up again today, with a problem record that was last edited by "UAM" and somehow ended up being a Napeozapus instead of a Sorex ,with a lot of missing info that may or may not have been deleted. We need to figure out whether that was a data entry problem or a recent editing change. Is it possible to have not just "last edited by" but a "edited by" history, in the same way we have container history? Maybe leave out any record of "last edited by" if the edit was by UAM, but only display edits by "real" operators who might have directly altered something in the "specimen" record?

I understand that versioning may not be feasible. However, I agree with Teresa about wanting email notification for the following changes:
Any change in a taxon assigned to my records
Any change in an agent assigned to my records
Any change in a locality assigned to my records
Any direct edit to one of my records.

**Comment by dustymc** [comment]
I don't think UAM updates IDs, and if it's possible to change a used taxon name please let me know - that's a bug.

Let me know the GUID and I might be able to dig up something out of the data entry archive.

I still need specifics regarding edited.

>Any change in a taxon assigned to my records

A refresh from GlobalNames? The 3rd author of a publication linked to a related taxon gets a new phone number? Something that propagates to FLAT? (Note that last thing would miss changing "superkingdom" - it's not a column in flat, even though it might be seen as a fundamental change to the ID - and anything about not-currently-accepted IDs.)

>Any change in an agent 

New phone number? New phone number for the agent related to the agent related to the agent that's "assigned to my records"? Just things that change text strings in FLAT? 

>assigned to my records

citation-publication authors? Only collectors??

>locality

same as above...

>Any direct edit 

I would need specifics on this as well.

Sorry this is so convoluted! I know most of the fringe examples above probably don't matter, but there are things equal distances away from cataloged_item that probably DO matter (to some people in some situations, anyway...). I don't want to put any work into doing something that's not useful to you, either because it's too vague (the current situation, I think) or because it's too detailed (mailing you a million mostly-irrelevant changes every day isn't going to be much fun for anyone). I really need SPECIFIC events that would trigger a notification to act.

**Comment by ccicero** [comment]
Revisting this issue...again! Let's prioritize this for discussion at the next AWG meeting. Another case in point based on recent exchange with Peter Miller at UWBM. He entered an accession 2018-45 which should have 45 specimens, but somehow there are now 4220 specimens in the accession. He has no idea why/how that happened. A look at a couple of records shows last edited by as UAM on 2018-09-18. NOT HELPFUL in trying to figure out this problem.

**Comment by dustymc** [comment]
new table
last_edited_by
* collection_object_id
* agent_id
* date

**Comment by dustymc** [comment]
patched in to production
