### ISSUE TITLE
Feature Request - Constraining GeoRef bot

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#5813]
Can we prevent the georeferencing bot from asserting coordinates that lie outside the WKT of the associated higher geography? Please see this "No specific locality recorded." locality for Cuba:
https://arctos.database.museum/editLocality.cfm?locality_id=11666780
It appears that we have a WKT for Cuba, but the bot is placing the coordinates in the middle of Haiti for some reason. If we could check the bot generated coordinates for inclusion within the Higher Geography's polygon we could prevent these types of mis-assignments. IMHO no coordinates is way better than bad coordinates. I'll be happy to fix this one locality for all the collections that use it, but it would be great to catch these obvious errors before they get populated into our records.

**Comment by dustymc** [comment]
In general: I think geography assertions are wrong about as often as anything else, pretending otherwise would 

>no coordinates is way better than bad coordinates

No coordinates are just invisible for many (most?) users. Bad coordinates are easy to find, especially when they're this bad. (But I'm resource limited so it can take a while - https://github.com/ArctosDB/internal/issues/222 - and I haven't yet tried to DO anything about bad coordinates, other than flag them).

ANYWAY - I'm not sure what happened here. I can't re-create this. The locality looks the same to me in test, I removed the attribute and coordinates and the bot refuses to do anything at all with it. Change the specloc and it does stuff, clear that back out and use the "No..." button and it does nothing. https://arctos-test.tacc.utexas.edu/demo.cfm is set up to be verbose about that at the moment. I'm not sure where it happened, but this looks like a bug that's been fixed.

**Comment by acdoll** [comment]
Can we tell the bot that if Specific Locality = "No specific locality recorded.", then replace it with Higher Geography string? Would that help it have any better luck?

**Comment by dustymc** [comment]
It does handle (by ignoring) ``No specific locality recorded.`` (unlike, say, ``unknown`` which usually matches SOMETHING and maps weird), but geolocate has some structural requirements so the options are pretty limited. Just replicating is a bad idea for the same reason avoiding that's in the [documentation](https://handbook.arctosdb.org/documentation/locality.html): It leads to things like Maine, Maine (and there are a LOT of reused placenames out there).

**Comment by cjconroy** [comment]
Only ignores if the locality is EXACTLY "No specific locality recorded". Of the first 5000 MVZ mammals I found bot-reffed, I found 122 mammals that include "no specific". E.g. "No specific locality recorded., Warwick County". That's a fun one. From wikipedia, "Warwick County was a county in Southeast Virginia that was created from Warwick River Shire, one of eight created in the Virginia Colony in 1634. It became the City of Newport News on July 16, 1952."  So, how does the bot plot it?  See below. Kind of far off. 
<img width="1060" alt="Screenshot 2023-03-10 at 10 54 20 AM" src="https://user-images.githubusercontent.com/5749672/224402406-ab6c3351-ecf9-445d-a1f4-4f38598069b5.png">

**Comment by cjconroy** [comment]
Here is another weird one. How does the bot come up with that latitude?  And only 5421 m error for all of Malaysia?  
<img width="920" alt="Screenshot 2023-03-10 at 11 00 45 AM" src="https://user-images.githubusercontent.com/5749672/224403681-bc632973-53e6-4779-913d-dd7bbd1368c2.png">

**Comment by dustymc** [comment]
That seems to be another instance of the same situation as the first - it currently won't do anything with that.

**Comment by cjconroy** [comment]
Here's another one. Locality is "no specific locality recorded; Arizona?". The bot seems to have a really good idea of where to put it. Error radius of only 301 meters in the SW tip of the state. 
<img width="1161" alt="Screenshot 2023-03-10 at 11 07 20 AM" src="https://user-images.githubusercontent.com/5749672/224404947-9729d11c-d2b5-4698-a0ce-13ba506bb102.png">
<img width="502" alt="Screenshot 2023-03-10 at 11 10 13 AM" src="https://user-images.githubusercontent.com/5749672/224405146-cec4ab16-d884-4ec2-8a57-eb7daba12172.png">

**Comment by jldunnum** [comment]
As this is closing I have another question. When we reverted back to preBot coordinates what exactly happened to all original values?
I came across a bunch of Panamanian records which I had previously georeferenced that had been redone by the bot. When I went back into those records after the reversion there were no georeference values at all. I know these had been previously done because this or a similar text string was still in the locality remarks field "UTM converted using https://www.engineeringtoolbox.com/utm-latitude-longitude-d_1370.html. Original UTM data: 377038 Easting, 923742 Northing."
So I had to re-georeference all those. Did I lose thousands more that I haven't discovered yet?

Also I had two issues trying to use the built-in coordinate converter.

  1.  The converter disappears when you move off of it to copy and paste another value into it. Only way to use it is to type in the values all at one time.
  2.  Got a failed status when trying to convert UTMs

_[cid:f0042c33-518f-411f-a3e0-d05f44aa2989]
Thanks, Jon
_____________________________________________________________

Jonathan L. Dunnum Ph.D. (he, him, his)
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

Chair, Systematic Collections Committee, American Society of Mammalogists
Latin American Fellowship Committee, ASM

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by jldunnum** [comment]
Hmm, OK not sure what transpired then

______________________________________________________________

Jonathan L. Dunnum Ph.D. (he, him, his)
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

Chair, Systematic Collections Committee, American Society of Mammalogists
Latin American Fellowship Committee, ASM

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by dustymc** [comment]
> not sure what transpired

Links are very useful, but I think you must be referring to https://arctos.database.museum/place.cfm?action=detail&locality_id=11129261. Like all localities, there's a history. The bot added coordinates on {ts '2022-10-05 18:22:03'} You changed them later, but did not alter the 'georeference source' attribute. I then used the georeference source attribute to strip coordinates which claimed to have been produced by the bot, as requested.

**Comment by jldunnum** [comment]
OK I think I got it, thanks

______________________________________________________________

Jonathan L. Dunnum Ph.D. (he, him, his)
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

Chair, Systematic Collections Committee, American Society of Mammalogists
Latin American Fellowship Committee, ASM

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________
