### ISSUE TITLE
Request addition to dwc archive published to IPT - dwc:scientificNameID

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5814]
Additional term needed for OBIS in the dwc archive that goes to the IPT. 

dwc:scientificNameID = lsid from preferred classification metadata

![image](https://user-images.githubusercontent.com/5725767/224191494-bc30fd3e-77a4-477c-abef-03ec8d1152ad.png)

We are going to need this if Ocean Genome Legacy selects Arctos - they do this now from their internal database and if we expect to meet their needs, we need to be able to send this.

This was agreed to, but hasn't been implemented? https://github.com/ArctosDB/arctos/issues/4776#issuecomment-1205699991

**Comment by sharpphyl** [comment]
Just checking on the status of this issue.  Is it moving forward to the AWG soon?

**Comment by Jegelewicz** [comment]
@dustymc possible to implement this? It isn't going to change anything for most collections but would be super useful for @sharpphyl and the new OGL collection.

https://github.com/ArctosDB/arctos/issues/4776#issuecomment-1205699991

**Comment by dustymc** [comment]
This still largely seems like magic from here.

BUT, after next release (ish) these data will be available in the record cache, someone can probably patch that together into whatever's needed and pass it on or ??

See https://arctos-test.tacc.utexas.edu/guid/DMNS:Inv:23162
<img width="594" alt="Screenshot 2023-06-27 at 3 57 33 PM" src="https://github.com/ArctosDB/arctos/assets/5720791/203abefe-a9b2-4d31-a973-5b6bd4ba462a">

or

```
@arctos>> select previousidentifications from flat  where guid='DMNS:Inv:23162';

**Comment by dustymc** [comment]
See also

>This would be an optional field the same as the Sensu and Taxon Concept fields. This is today's "edit ID" format

?

**Comment by Jegelewicz** [comment]
@dustymc I don't know what to do with that - we need to get this into the stuff that goes in the IPT somehow. This is going to become a critical need in the near future as people start using identifiers instead of names to match classification to identifications. Maybe we need to meet up and talk it through? Let's put it on the Taxonomy Committee Agenda - July 13, 10AM your time.

**Comment by dustymc** [comment]
>somehow

https://github.com/gbif/model-material#readme is nice...

>critical need

Not while pretending that the world is flat!

> Taxonomy Committee Agenda

Maybe, but I think this is bigger that that - it's almost inevitably going to be a significant cost (in complexity and CPU) with a very short reach, even if you can tell me precisely what to do.

I hopefully clicked the right button on my calendar.

**Comment by sharpphyl** [comment]
> This would be an optional field the same as the Sensu and Taxon Concept fields. This is today's "edit ID" format
?

We're suggesting we add the term "dwc:scientificNameID = lsid from preferred classification metadata" in order to add the WoRMS LSID to the catalog record in the identification section.  It could look like this.  

<img width="686" alt="Screenshot 2023-06-29 at 7 16 46 AM" src="https://github.com/ArctosDB/arctos/assets/15368365/dbd9ff50-3e3a-4e83-88f9-3ee80c449513">

If the LSID can come automatically from the metadata in WoRMS (via ARctos), that's fantastic.  If we have to do it manually, we will.  

It doesn't help us with OBIS to only have the LSID in the taxonomic metadata.  It has to be somewhere in the catalog record for OBIS to pick it up.  Not sure I fully understand, but it sounds like the WoRMS LSID will be somewhere in the catalog record Identification data with the next release, but we'd have to somehow identify it as the scientificNameID.

Good idea to discuss at the next Taxonomy Committee meeting on the 13th.  Genna and I will be there.

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/6532
