### ISSUE TITLE
Code Table Request - other identifier

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#6005]
## Instructions

This is a template to facilitate communication with the Arctos Code Table Committee. Submit a separate request for each relevant value. This form is appropriate for exploring how data may best be stored, for adding vocabulary, or for updating existing definitions.

Reviewing documentation before proceeding will result in a more enjoyable experience.

* [Issue Documentation](http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html)
* [Code Table Documentation](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html)
* [Video Tutorial - Submit a Code Table Request](https://youtu.be/t2jHbsRA3lk)

------------------------------

## Initial Request

**Goal**: Describe what you're trying to accomplish. This is the only necessary step to start this process. The Committee is available to assist with all other steps. Please clearly indicate any uncertainty or desired guidance if you proceed beyond this step.

[other identifier](https://arctos.database.museum/info/ctDocumentation.cfm?table=CTCOLL_OTHER_ID_TYPE#other_identifier) is inappropriately defined. The definition should be more inline with the current model. Also, [the "other" embedded in the name/label/type also carries implications of "less-worthy" and that is not true](https://github.com/ArctosDB/arctos/issues/6005#issuecomment-1470751720).

**Proposed Value**: Proposed new value. This should be clear and compatible with similar values in the relevant table and across Arctos. 

~~no change, definition only~~
[identifier](https://github.com/ArctosDB/arctos/issues/6005#issuecomment-1470751720)

**Proposed Definition**: Clear, complete, non-collection-type-specific **functional** definition of the value. Avoid discipline-specific terminology if possible, include parenthetically if unavoidable.

[This type is proper for a wide range of identifiers that can be disambiguated by the agent that issued them. This identifier type is not indicative of low-quality data but allows for ease of identifier searches across specific uses for specific purposes. Use a more specific type if appropriate.](https://github.com/ArctosDB/arctos/issues/6005#issuecomment-1573950882)

~~[This type is proper for a wide range of identifiers that can be disambiguated by the agent that issued them. This identifier type is not indicative of low-quality data but allows for ease of identifier searches across specific uses (ear tags, studbooks, museum collections) for specific purposes (issuers).](https://github.com/ArctosDB/arctos/issues/6005#issuecomment-1468931844)~~

> I need help crafting a definition. This value is proper for a wide range of identifiers disambiguated by asserting agent (and the not-so-great not attached to an agent are fine here as well). The type itself doesn't have to do the heavy lifting; the agent can bear that burden. A less-specific type (such as this one) is, under the current model, *not* indicative of low-quality data. Attempts to narrowly define types are not used properly (see: data on most any of ~200 recent issues), this type is suitable to carry a vast array of data (when accompanied by an issuer). The definition should reflect all of these things. HELP!

**Context**: Describe why this new value is necessary and existing values are not.

structure has changed

**Table**: Code Tables are http://arctos.database.museum/info/ctDocumentation.cfm. Link to the specific table or value. This may involve multiple tables and will control datatype for Attributes. OtherID requests require BaseURL (and example) or explanation. Please ask for assistance if unsure.

(https://arctos.database.museum/info/ctDocumentation.cfm?table=CTCOLL_OTHER_ID_TYPE

**Priority**: Please describe the urgency and/or choose a priority-label to the right. You should expect a response within two working days, and may utilize [Arctos Contacts](https://arctosdb.org/contacts/) if you feel response is lacking.

High: the obsolete definition is being used to [justify](https://github.com/ArctosDB/arctos/issues/5969#issuecomment-1468904428) not-great data.

**Project**: Add the issue to the [Code Table Management Project](https://github.com/ArctosDB/arctos/projects/13#card-31628184).

**Discussion**: Please reach out to anyone who might be affected by this change. Leave a comment or add this to the Committee agenda if you believe more focused conversation is necessary.

## Approval

All of the following must be checked before this may proceed.

The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality).

- [x] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [x] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection

If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc. 

1. Can a suitable solution be found here? If not, proceed to (2)
2. Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)
3. Take the discussion to a monthly Arctos Working Group meeting for final resolution.

## Implementation

Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made.

Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel. 

Make changes as described above. Ensure the URL of this Issue is included in the definition. 

Close this Issue.

**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result.

## Special Exemptions

In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases.

1. Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step.
2. The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology.

**Comment by Jegelewicz** [comment]
To begin - current definition is

> Other values that link a specimen with its data. For example, label values applied by an agency project, or various values that are not known to be of a more defined identifier type. Documentation

**Comment by Jegelewicz** [comment]
Draft

This type is proper for a wide range of identifiers that can be disambiguated by the agent that issued them. This identifier type is not indicative of low-quality data but allows for ease of identifier searches across specific uses (ear tags, studbooks, museum collections) for specific purposes (issuers).

**Comment by campmlc** [comment]
Disagree strongly with including studbook numbers, and ear tags, when these
are in use for repeat sampling.

**Comment by jebrad** [comment]
What is the best place for ear tag numbers, if not Other ID?   I have a lot of ear tags.  I assume no one will ever search for those except within records that are already sorted by eg collector, so my instinct is that having them in a catch-all field like Other ID would work for those needs, as long as they always include a prefix "ear tag".  Also needs to be uncontrolled so we can include left, right, colors, and alpha-numeric numbers.
(Am I thinking about this right?  I feel like I am late to these conversations)

**Comment by dustymc** [comment]
@jebrad agreed - the important thing is the identifier (and who issued it and so might have data), not the media on which the identifier is printed.

**Comment by dustymc** [comment]
I have an amendment to propose: I'd like to also change the name of the type to "identifier." The "other" embedded in the name/label/type also carries implications of "less-worthy" and that is not true.

**Comment by Jegelewicz** [comment]
Edited ask above and added to Code Table Meeting for tomorrow

**Comment by DerekSikes** [comment]
![Screenshot 2023-03-15 at 1 45 05 PM](https://user-images.githubusercontent.com/9099827/225451077-792e62d8-9542-4d0b-9584-603766a57500.jpg)
This is a problem. Will it be fixed? I'd like the display to be compact like it was before.

**Comment by dustymc** [comment]
Is it tomorrow yet? Is there some way we can not lose sight of this?

**Comment by campmlc** [comment]
I support changing other identifier to identifier for when that is used. 
I don't support things like studbook and ear tag being changed to identifier under the proposed model because we have those values in projects where a single agent may assign more than one type of identifier - such as NPS catalog number and NPD accession number. The same is true for the above IDs.

Assuming they will be findable because "ear tag" is always entered as a prefix is not viable. It isn't possible to correct for the variations of "ear tag 1234", "eartag 1234", "eartag # 1234", "ear tag: 1234" etc. 

The only way to solve this without keeping at least some standard types of identifier in the code table is to convert ALL identifiers into agents, which I believe was the scope of the original proposal at least as some people understood it. This would eliminate the need to have identifier type as a field and eliminate the need for an ID code table.  This would mean every different type of ID created by every agent, including studbooks and ear tags for different agencies and projects, as well as different individuals prep catalogs and collector catalogs, would all be treated as agents. If this happens, we would need to change the Agent code table to " Agents and Identifiers" code table. Is everyone willing to go that far?

**Comment by ewommack** [comment]
> The only way to solve this without keeping at least some standard types of identifier in the code table is to convert ALL identifiers into agents, which I believe was the scope of the original proposal at least as some people understood it.

This wasn't what I understood from the original proposal, and I'm really wary of this change. I do not think it will be clear for regular researchers or agency members to go to agents to search for this type of material. I know that our faculty will not conduct searches for our museum's tissue catalog that way, and no matter how much training or videos Arctos creates they will not find the info. They will give up before they learn, and I'm just going to have to pull the data out of Arctos and keep it in an excel for them instead. Looking under agents makes no sense to find a catalog number or a tissue number.  IF we have to go through with this, I think we need the search to be redone and working where we can set a simple search field for identifiers from the agent menu, with a drop down for terms that are needed for collections. Having to make sure people type in the specific name with no typos or errors will make these terms unsearchable.

Having set identifiers meant that I could help them set-up profiles that showed these types of identifiers every time they searched. It also meant that I could set Arctos detailed record pages to show these numbers at the top of the page. I could specifically tell the UWYMV catalog records to show specific identifier info for every record entry. If we switch everything to agents how will that work? And no, I don't mean setting it up for catalog number to show at the top. We had specific identifiers set up to show.

**Comment by dustymc** [comment]
>I support changing other identifier to identifier

Awesome, scroll up and check one of those CTAdmin boxes, maybe we can get @Jegelewicz to check the other, then we can move on. This still seems entirely uncontroversial to me, it's obviously causing confusion elsewhere and that stuff is bleeding back here, IDK why we're still here!

-------------------------



Unrelated and better discussed in the issues regarding specific types, but maybe still causing hangups so....

>eliminate the need for an ID code table

That's not the proposal, nobody has suggested that.

>ear tag

We obviously do need some sort of decision matrix - we have amply demonstrated the problems with just making everything into an identifier type - and I lean towards the functional (as always) for that. Ear tag is a great example: an ear tag is a device, or media, not a type. Finding an ear tag that says "3" on it tells you absolutely nothing, leads you nowhere, has no value at all. "Ear tag" as an identifier type is precisely as useful as "paper" as an identifier type - neither are, at all, because they're used for all sorts of things to the point of being uninformative. The identifier could have been encoded into a PIT tag, tattooed on the skin, or WHATEVER without changing anything: the tag is the carrier, not the type. The issuer of the identifier is clearly the important thing, the bit of information that might lead back to data that'll tell you what that particular "3" means. What am I not understanding regarding that? (Maybe it's just that that keeps getting confounded with things that perhaps aren't so simple and clearcut?? Or I'm well and truly lost?? I don't know, help me understand, please!)

Also unrelated to this, way out on the other end of the spectrum things like AF and NK seem completely safe to me. I still can't quite say WHY, I can't tell what all might be in that pool, I might open an issue looking for documentation or clarification or understanding, but there's clearly SOMETHING about them, even if it's just that the 'typeness' makes it really easy to pretend that they're columns in spreadsheets. My goal isn't to get rid of them, it's just to understand them (hopefully so I can understand a bunch of the middle ground) and I think that's true for everyone else as well.

**Comment by Jegelewicz** [comment]
> Is it tomorrow yet?

Well only 4 of us were there when tomorrow came and we didn't handle any of this....but I have indicated my approval.

See also https://github.com/ArctosDB/arctos/issues/6032

**Comment by campmlc** [comment]
I support the change of other identifier to identifier. I support the definition but only if the specific suggestion "(ear tags, studbooks, museum collections)" is removed. These should be addressed separately, as the examples given are specifically ones that MSB needs to retain.

**Comment by dustymc** [comment]
>only if the specific suggestion ... is removed

I agree, lists of examples as definitions are near-always problematic. The definition has been adjusted (thanks @Jegelewicz), please check the box if that's satisfactory.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I support this and the revised definition.

**Comment by dustymc** [comment]
Excellent, I thing we now have what's necessary to proceed. This will probably keep things busy updating for a day or so - @Jegelewicz could you coordinate that? Maybe this Friday? (And you can create a new CT value if you want - I can just move and then clean up.)

**Comment by Jegelewicz** [comment]
Before proceeding - I want to make sure the community is aware and understands the reasoning. How can I be sure that once this change is made everyone will understand the reasoning?

# Issue Summary

## Goal
Describe what you're trying to accomplish. This is the only necessary step to start this process. The Committee is available to assist with all other steps. Please clearly indicate any uncertainty or desired guidance if you proceed beyond this step.

[other identifier](https://arctos.database.museum/info/ctDocumentation.cfm?table=CTCOLL_OTHER_ID_TYPE#other_identifier) is inappropriately defined. The definition should be more inline with the current model. Also, [the "other" embedded in the name/label/type also carries implications of "less-worthy" and that is not true](https://github.com/ArctosDB/arctos/issues/6005#issuecomment-1470751720).

## Proposed Value
Proposed new value. This should be clear and compatible with similar values in the relevant table and across Arctos. 

[identifier](https://github.com/ArctosDB/arctos/issues/6005#issuecomment-1470751720)

## Proposed Definition
Clear, complete, non-collection-type-specific **functional** definition of the value. Avoid discipline-specific terminology if possible, include parenthetically if unavoidable.

[This type is proper for a wide range of identifiers that can be disambiguated by the agent that issued them. This identifier type is not indicative of low-quality data but allows for ease of identifier searches across specific uses for specific purposes. Use a more specific type if appropriate.](https://github.com/ArctosDB/arctos/issues/6005#issuecomment-1573950882)

## Context
Describe why this new value is necessary and existing values are not.

The structure of identifiers has changed

## Table
Code Tables are http://arctos.database.museum/info/ctDocumentation.cfm. Link to the specific table or value. This may involve multiple tables and will control datatype for Attributes. OtherID requests require BaseURL (and example) or explanation. Please ask for assistance if unsure.

https://arctos.database.museum/info/ctDocumentation.cfm?table=CTCOLL_OTHER_ID_TYPE


## Priority
Please describe the urgency and/or choose a priority-label to the right. You should expect a response within two working days, and may utilize [Arctos Contacts](https://arctosdb.org/contacts/) if you feel response is lacking.

High: the obsolete definition is being used to [justify](https://github.com/ArctosDB/arctos/issues/5969#issuecomment-1468904428) not-great data.

## Approval

All of the following must be checked before this may proceed.

The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality).

- [x] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [x] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)


## Implementation

Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made.

Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel. 

Make changes as described above. Ensure the URL of this Issue is included in the definition. 

Close this Issue.

**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result.

**Comment by dustymc** [comment]
I think that any gaps in understanding come from being trapped in between two systems. (Eg the definition is clearly wrong NOW.) The immediate functional difference of this is just using a slightly different term. I believe that any delays will cause many more problems then they solve, and suggest this should proceed with all possible haste.

**Comment by ebraker** [comment]
Code table committee approves change 2023-06-15. Suggest adding a quick 'did you know' update in the next newsletter to inform community @ewommack.

**Comment by Jegelewicz** [comment]
I have created the new code table item. @dustymc let me know if you need anything else in order to move these from "other identifier".

**Comment by ewommack** [comment]
> 'did you know' update in the next newsletter to inform community 

An article on "did you know that Other Identifier has changed to Identifier and is now defined as:
This type is proper for a wide range of identifiers that can be disambiguated by the agent that issued them. This identifier type is not indicative of low-quality data but allows for ease of identifier searches across specific uses for specific purposes. Use a more specific type if appropriate.

That is what you are looking for?
