### ISSUE TITLE
Add arkID to other identifiers

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#6024]
Just found arkIDs in the USNM database that actually link to a record.
I would like to be able to create a relationship to this arkID via Arctos, but arkID is not yet in the identifiers code table. 
Since this is specific to an individual catalog record, it cannot be added to an agent, unless we want to create agents for every USNM record . . . 

proposed identifier type: ark
url: https://arks.org/
definiton: ?Archival Resource Keys (ARKs) serve as persistent identifiers, or stable, trusted references for information objects. 
See for example: http://n2t.net/ark:/65665/32dc62b24-383f-4466-b0ff-427b6eb6444f

Not to be confused with "ark Ids" used for creatures created in some gaming platforms . . . ?

**Comment by dustymc** [comment]
Your URL and your example do not align.

In general, I'm not convinced that most users understand the structure of ARKs in sufficient detail to deal with partial identifiers, and I can see no reason that we'd want to type them, deal in partial identifiers, or add unnecessary complexity in any way. Copy the whole thing, paste it into https://github.com/ArctosDB/arctos/issues/6005, and be done.

The same is true of all resolvable identifiers, and much of the recent cleanup is a direct result of users not understanding our mostly-unnecessary complexity and being forced to deal with partial identifiers that cannot DO stuff. This of course does not stop at the boundaries of Arctos: https://github.com/ArctosDB/arctos/discussions/5310

Issuers are much less important on resolvable IDs (or I haven't seen the light yet, maybe) - just like they type themselves (by doing stuff), you'll have a pretty good idea of who issued them when you get to where they go. These however are not ambiguous: USNM isn't going to let anyone other than USNM issue USNM identifiers.

There is in fact an ARK ID type, but I wouldn't suggest anyone use it and I hope it has a very short life expectancy: https://arctos.database.museum/info/ctDocumentation.cfm?table=CTCOLL_OTHER_ID_TYPE#ark

**Comment by campmlc** [comment]
I just found the ARK id in use in Arctos for exactly this purpose, so someone beat me to to it: https://arctos.database.museum/guid/MSB:Para:28915

I can't imagine why we wouldn't want to use this if it is available to link to USNM records. Maybe it isn't perfect, but it is better than linking to a aggregator - this is the primary data source. And until recently they had no way at all to link to a record.  ????

**Comment by campmlc** [comment]
And apologies if I didn't submit in the correct format. This is not my area of expertise. That is why we have this forum.
But I stand by my question - we have a resolvable identifier in use by USNM. I do not understand why we should reject linking to it.

**Comment by dustymc** [comment]
>can't imagine why we wouldn't want to use this 

That is not what I said. Absolutely, use it. It's a great identifier, and good on them for having it. 

>not my area of expertise.

THAT is my point! You (and every user to come after) can 

1. do some complicated thing that involves ripping an identifier apart, selecting the right type, and hoping it comes back together - after you save - by some magic, a system which exists only inside Arctos, or you can 
2. copy and paste, same as you'd do anywhere.

The first has you dealing with 65665/3777ecb64-7edc-4479-8486-a0b584092bd0 (is that the right thing? Are you sure? How would you know?).

The second has you dealing with http://n2t.net/ark:/65665/3777ecb64-7edc-4479-8486-a0b584092bd0 - your browser (and a bunch of other tools, including github as soon as I submit this) will happily tell you if that's the right thing by DOING STUFF.

IF we can find a way to get through some small changes, we can make some otherwise-complex thing usable by most anyone, expert or not.

**Comment by campmlc** [comment]
I definitely did not intend for the original ask to require leaving off the http:// etc prefix. I'm not sure if that is how the current ARK is formatted. I am actually very happy to copy paste the full url. 
But I think we have solved this issue with using other identifier and issued by the Smithsonian Division of XXX, with the http// ark address as the url?
https://github.com/ArctosDB/arctos/issues/5995
Closing
