### ISSUE TITLE
other identifier search on numeric is wonky

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#6030]
See the search and results below--
search is for identifier = BSI + numeric= 184 
results includes BSI values that include the last 2 digits? even with the ```=``` qualifier 
So what is up?
![Catalog Record Search](https://user-images.githubusercontent.com/2523089/226488499-6cb23ae1-3e67-451e-bccc-3534fe3560bb.png)

**Comment by dustymc** [comment]
https://arctos.database.museum/search.cfm?customoidoper=BETWEEN&oidtype=BSI%3A%20Biotic%20Survey%20and%20Inventory&id_numeric=184

Use this thing and I won't have to guess what you're doing:

<img width="301" alt="Screenshot 2023-03-20 at 4 43 57 PM" src="https://user-images.githubusercontent.com/5720791/226489011-1cd636a9-df15-4885-a5a7-62f329b07219.png">

Screenshot suggests you're searching value, not numeric, you can mouseover and it'll tell you what it's doing

<img width="444" alt="Screenshot 2023-03-20 at 4 45 45 PM" src="https://user-images.githubusercontent.com/5720791/226489227-fa958031-0518-4ddd-9f50-a85bb247f6df.png">

**Comment by campmlc** [comment]
I'm having a similar problem. Trying to search on Mexican wolf studbook number 2698. I enter 2698 in Values - because its not clear whether I should use Numeric..
I get one result: for a wolf with studbook number 1698.
If I put 2698 in Numeric, I get nothing. Whether or not there really is nothing for 2698, I shouldn't be getting results for a different studbook number.

![Screenshot 2023-03-22 13 42 34](https://user-images.githubusercontent.com/14808196/227019386-eb996671-3c7c-46f9-89e0-e62f24a77a38.png)

![Screenshot 2023-03-22 13 42 46](https://user-images.githubusercontent.com/14808196/227019435-b4abef33-dddf-44e7-9b8b-d342bfa5e5b3.png)

**Comment by campmlc** [comment]
Note that this wolf has an other identifier of 1698. But that's not the studbook number, and I explicitly choose to search for the studbook number value.
This is one of my concerns about shifting everything to "identifier" as an ID type.

**Comment by dustymc** [comment]
Please use the tool mentioned above to provide links, I cannot re-create what you describe.

**Comment by campmlc** [comment]
https://arctos.database.museum/search.cfm?customoidoper=IS&oidtype=Mexican%20wolf%20studbook%20number&oidnum=2698

?

**Comment by dustymc** [comment]
whoa - thanks!

**Comment by Jegelewicz** [comment]
It seems like the issue is that "value" finds things that are similar. If I put an = in front of 2698, I get the expected nothing.

Is this what we want? It seems like maybe it should be in order to find things that may not be formatted entirely correctly. But we need to make it clear that without an = in front of value, you are going to get results for things that are "like"

**Comment by dustymc** [comment]
>seems like the issue

Na, just a bug.
