### ISSUE TITLE
[external CONTACT] Place Terms search question

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#6065]
@dustymc @mkoo I did a search of all MVZ:Bird with part name like 'ectoparasite' and got 51 results. Here is the [saved search](https://arctos.database.museum/saved/MVZ%3ABird-ectos). Then I tried to limit it to just California by selecting state_prov in the Place Terms field and got only 3 returns:

![image](https://user-images.githubusercontent.com/967275/228014509-1f6f112a-52fb-4d97-b35d-bb7e75478a7a.png)

Next I tried putting 'California' in the Any Geographic Element field. That gave me 42 entries which is correct ([new saved search](https://arctos.database.museum/saved/MVZ%3ABird-ectos-CA)).

Why does the Place Terms search not include all of the records with state_prov of California?

**Comment by dustymc** [comment]
Short version: https://github.com/ArctosDB/internal/issues/222

Hopeful solution: https://github.com/ArctosDB/arctos/issues/5597

https://github.com/ArctosDB/arctos/issues/5654 is making Arctos geography comprehensive, but processing that is slow. Once that's complete, search by familiar Arctos terms should be comprehensive (as the cache catches up). In the meantime there's still a bunch of old data from various services hanging around, but at least the rank components aren't very predictable. (At least "GADM1" and "STATE" mean about what state_prov does, for example.)

https://arctos.database.museum/search.cfm?guid_prefix=MVZ%3ABird&customoidoper=BETWEEN&part_search=ectoparasite&geog_shape=United%20States%2C%20California is basically the above but live, and explicit in the intersection - that's 'contains', I can't get 'intersects' to work at the moment (which is why there's all this complication about caching, it would be AWESOME to skip all that nonsense and deal with shapes, but here we are).

https://arctos.database.museum/search.cfm?guid_prefix=MVZ%3ABird&customoidoper=BETWEEN&part_search=ectoparasite&state_prov=California is "as asserted by you" - things that you claim to be in CA but which don't map there will be included. I think your practices support this and BM suggests the data aren't crazy, so that might be the easy choice. (There's also some 'chosen event' complexity that would make this a poor choice for some uses - eg cultural collections or those with lots of opinions via automation or etc - but that can generally all be ignored for your data too, I think.)

**Comment by ccicero** [comment]
now I'm just trying to search on MVZ:Bird for taxon 'Zenaida macroura' for Any Geographic Element 'California' but am getting 0 returns. There are definitely specimens from California. Shouldn't that work at least? 

![image](https://user-images.githubusercontent.com/967275/229642252-668fd6ae-d6d5-4a02-9a19-493e7bb62678.png)

**Comment by dustymc** [comment]
https://arctos.database.museum/search.cfm?guid_prefix=MVZ%3ABird&customoidoper=BETWEEN&taxon_name=Zenaida%20macroura&any_geog=California

finds 180 records for me. Please use links, otherwise we're all guessing.

**Comment by ccicero** [comment]
How do I use a link if I don't get any returns?

**Comment by dustymc** [comment]
<img width="219" alt="Screenshot 2023-04-03 at 4 17 15 PM" src="https://user-images.githubusercontent.com/5720791/229646975-bcf28377-e62e-46cf-a064-903d234ff6ca.png">
<img width="123" alt="Screenshot 2023-04-03 at 4 17 26 PM" src="https://user-images.githubusercontent.com/5720791/229646986-ae021876-8be5-4bfb-b443-aeab7e67ee13.png">
<img width="393" alt="Screenshot 2023-04-03 at 4 17 43 PM" src="https://user-images.githubusercontent.com/5720791/229647004-c53993dd-dab3-42bf-9b17-e4d259614d30.png">

https://arctos.database.museum/search.cfm?cat_num=afasdfasfasfasdas&customoidoper=BETWEEN

**Comment by ccicero** [comment]
Ah, ok. Will try again. Not sure why I was getting 0 returns. Maybe something cached?
