### ISSUE TITLE
Account for issued by when assessing duplicate identifiers

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6101]
When attempting to upload identical identifiers into a catalog record, duplicates will fail. But duplicates are only being assessed for identifier type, value, and relationship. An assessment for duplicates should also include issued by.

I was not able to load some identifiers today because of this and had to change the type to get them to load.

An example can be found in https://arctos.database.museum/guid/UTEP:Herb:52971

Are [Natural History Museum of Los Angeles County Herbarium](https://arctos.database.museum/agent/21347942) and [California Botanic Garden Herbarium](https://arctos.database.museum/agent/21347681) the same institution? Quite possible, but until I figure that out, I should be able to record both identifiers.

This also points out a possible scenario - I discover these are the same institution and mark the agents to merge. Now we really would have duplicate identifiers - how does Arctos handle that?

**Comment by dustymc** [comment]
Interesting problem.

I suspect the index is correct and your assertion is redundant - some institution assigned a number, gave the item to another institution (who kept the first number, which you've now entered twice) and also assigned their own (which you have not entered). "Drive to LA" might be the first step in solving that mystery, which means it's just not going to be solved, you just know what you know. I'm sure this is a common situation. What you've done - wrong though it may be - does seem like the best way to make sure that gets found (maybe by someone who does know more about the identifiers).

Agent mergers which violate referential integrity will just fail - there's no other possible pathway.

It's easy enough to adjust the primary key, I think this is entirely a social problem.

I think I might support the most inclusive model, which would just be dropping the constraint. That will just about certainly result in some record having 36824 identical GenBank numbers (which might incite an "interesting" response from GenBank....) or something - some folks like to check to see if the same input will result in the same error a few dozen times - but maybe that's just a price we have to pay in order to accommodate less-known identifiers.

**Comment by campmlc** [comment]
I support dropping the constraint - worse case, we have duplicate identifiers. Or we have an identifier assigned to the older name of an institution. Best case, we find and resolve problems. In this case, having both terms might be good - we shouldn't presume that everyone is using or searching on the most current agent name, or knows that these agents are in fact the same, or that we've captured all variants of all names in an agent profile.

**Comment by dustymc** [comment]
https://arctos.database.museum/guid/ALMNH:Inv:760 - I can't update with this (and I think several thousand like it), and I'm not willing to assume those are duplicates via denormalization (even though they almost certainly are).

The implications for things like genbank are apparently understood by 2 code table admins, and I can't see any way out of this that doesn't involve resources we don't have, so I'm loosening the constraint.
