### ISSUE TITLE
All Arctos identifiers

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#6163]
**Is your feature request related to a problem? Please describe.**

There are a bunch of Arctos identifiers where we deal with the various components individually (and poorly). This is demonstrably ineffective, necessarily has a limited scope, and is messy in tabular views. 

This is essentially a code table request, but I'm using this format to accommodate as much discussion as is necessary.

These are all base URI starts with ``http://arctos.database.museum/guid/`` values in https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type

I am proposing that we deal with the actual GUIDs, never bits and pieces of them. ``https://arctos.database.museum/guid/MSB:Para:23576`` is available from the URL bar in my browser, is specified and accompanied by a 'copy' button in the record...

<img width="510" alt="Screenshot 2023-04-19 at 7 09 35 AM" src="https://user-images.githubusercontent.com/5720791/233101700-4097784e-f7ac-4826-8ddb-5991d2bb50ae.png">

... and I think just is not in any way ambiguous.

In the current system, https://arctos.database.museum/guid/MSB:Host:21074 refers to ``http://arctos.database.museum/guid/MSB:Para:MSB:Para:23576`` - a nonsensical identifier resulting from an overly-cryptic system forcing users to deal with clearly-ambiguous 'bits.'

**Describe what you're trying to accomplish** 

Cleaner, less-confusing data.

**Describe the solution you'd like**

1. Change all Arctos guid-url-identifiers to some other type. 'Identifier' is probably my first choice, but that issue seems stuck so that type doesn't exist, and type is mostly irrelevant with resolvable identifiers so whatever. MAYBE we need some 'is URL' type, but every time I look at the data it screams that complexity leads to worse data so ??
2. Some understanding of what, if anything, we might need to do in the UI with the existing base URLs. (Some sort of "identifier builder" popup, or ?????????) FWIW I'd just flush it all, it clearly leads to cruddy data (about 10% obvious, who knows how much more subtly broken, data below), 'copy the URL' is simple and anyone can understand it, anything more complex - well, here we are.

**Describe sad alternatives you've considered**

Bad data, limited portability, confused users

**Describe happy alternatives you've considered**

Do whatever we do here with all (or nearly all) baseURL-having identifiers.

**Additional context**

https://github.com/ArctosDB/arctos/discussions/5310 is this but generalized - we've been making messes and confusing external users for a while.

Data:

```

create table temp_arctos_guid_ids as select
flat.guid,
flat.collection_object_id,
replace(base_url,'http://arctos.database.museum/guid/','')||display_value as idbits
from flat
inner join coll_obj_other_id_num on flat.collection_object_id=coll_obj_other_id_num.collection_object_id
inner join ctcoll_other_id_type on coll_obj_other_id_num.other_id_type=ctcoll_other_id_type.other_id_type
where base_url like 'http://arctos.database.museum/guid/%'
;

SELECT 167458


alter table temp_arctos_guid_ids add idbits_exists varchar;

update temp_arctos_guid_ids set idbits_exists = flat.guid from flat where temp_arctos_guid_ids.idbits=flat.guid;


UPDATE 152122


select count(*) from temp_arctos_guid_ids where idbits_exists is null;


 count 
-------
 15336

```

[temp_arctos_guid_ids.csv.zip](https://github.com/ArctosDB/arctos/files/11273878/temp_arctos_guid_ids.csv.zip)

**Priority**

IDK, I'd hoped we could address this after we'd got through the "easy" identifiers but that seems completely blocked.  I can't see any realistic way to address https://github.com/ArctosDB/arctos/issues/6162 without this.

**Comment by Jegelewicz** [comment]
Just for a demo - here is what is happening.

https://arctos.database.museum/guid/MSB:Mamm:70543 includes an identifier of type HWML:Para with a value of 62672A

![image](https://user-images.githubusercontent.com/5725767/233110092-30aaac60-19ec-4b45-839d-2ad7187ffd5f.png)

The HWML:Para type automatically adds https://arctos.database.museum/guid/HWML:Para to the value, which results in https://arctos.database.museum/guid/HWML:Para:62672A which throws an error because that catalog number does not exist.

![image](https://user-images.githubusercontent.com/5725767/233110790-344a21f6-5be0-4d23-b5d1-62f94dd9576d.png)

I believe what Dusty is saying is that if the person doing data entry had been required to go and get the actual GUID (url), they would have seen this and we wouldn't have this unusable link. And there are about 15K of these things in Arctos right now. These give our links a bad rap and makes Arctos appear to be broken.

The solution is to do away with the magic addition of the "base url", do the data quality work up front, and instead just plop down the entire url. But we have become accustomed to the magic and I know that there will be those who find this just one more bit of work that they don't have time to complete.

My take is that I think using the entire url is the right way to go and we should be directing everyone to do this everywhere. If we want real magic (like automatic linking to publications) using these "long form" but absolutely globally unique identifiers ourselves is the first step in creating community awareness and buy-in.

So the question for the community is can we work up something that gets us there?

**Comment by Jegelewicz** [comment]
FWIW I did some testing on this record:

https://arctos.database.museum/guid/MSB:Mamm:70543

Note that even https://arctos.database.museum/guid/HWML:Para:62672 does not exist. Given that, These identifiers should really be recorded as my Teresa test entries:

![image](https://user-images.githubusercontent.com/5725767/233115614-5df574e0-19a2-4878-8c5c-00cb8dde20cb.png)

**Comment by dustymc** [comment]
There are cases where the identifier should be to something that doesn't exist (eg, because you're going to catalog it next, or because it's encumbered, or etc.), so the overall picture might not be quite as simple as 'copy the thing with the copy button' but I think that's sort of "advanced usage" and the people doing that probably understand the system.

Opposite that (and at the root of many of the recent ID cleanup issues)  ``https://arctos.database.museum/guid/HWML:Para:62672`` may not exist because ``62672`` is something other than the catalog number (local freezer-system-number, collector number, accession, part barcode, something some agency scribbled on something - they all show up from time to time). That is a common thing, I think it's mostly a symptom of the complexity I'm trying to get rid of (someone entered '62672' into an appropriate-looking place and then Arctos magicked it into something else and now it looks more authoritative than it really is), and they're NASTY to find - much of the time the URL resolves just fine, but goes to some unrelated item.

> accustomed to the magic

Yep, that's my (2) above - if the complexity does something useful then we can try to find a way to accommodate that.

**Comment by dustymc** [comment]
A possible example of the above: https://arctos.database.museum/guid/MSB:Para:30961 (NK 131066) claims to be collected with ``https://arctos.database.museum/guid/MSB:Para:131066`` which doesn't exist. Maybe that's real, maybe it's something like the above, whatever the case it's probably going to take some sort of curatorial staff digging through papers or something to sort out, and if it's what I suspect (student put an identifier into the wrong slot) it could have been easily prevented by just not using partial identifiers.

**Comment by dustymc** [comment]
>Can we postpone this discussion?

That's entirely up to The Community, but this controls how other stuff may proceed. I don't propose many things unless there are some functional implications, and a bunch of those have become stuck. I think those critical issues are behind a couple blocks already, I'd rather this doesn't become another layer.

**Comment by campmlc** [comment]
Can we make some headway on the interface issues that are affecting alll users first? And get reports functional? These are my critical priorities. 
HWML linkages to MSB:Para are in desperate need of some project management level cleanup - but I can't do that right now. And changing the identifiers to something other than HWML:Para is not a viable solution. These are legitimate catalog records, and the MSB records need to be able to link to them once they are cataloged.

If I understand the proposal here as forcing all collections in Arctos to change their data entry protocols to include the base urls typed in by students, and then calling these "identifiers" instead of catalog numbers - that is not going to go over well, and the timing is atrocious.

**Comment by campmlc** [comment]
I've fixed all the problem examples in this issue. If there are others
associated with MSB and HWML, please provide a csv and I will fix those as
well.

**Comment by msbparasites** [comment]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

Describe the bug

The relationship links are not working in Parasites and Hosts- need to restore the link
restore the link to the locality of the related record - it used to pull the host identification and locality into the parasite record and vice versa
To Reproduce
Steps to reproduce the behavior:

Go to https://arctos.database.museum/guid/MSB:Para:19503
Click on in Identifiers and Relationships either "parasite of" or "search" neither send you to the host record which is this: https://arctos.database.museum/guid/MSB:Host:15491. The reverse is true to if you want to see a parasite record directly linked out from host (or bird, or mammal, or fish etc...) record
Expected behavior
I expected to click the MSB catalog number of the host listed as "parasite of" and then be taken directly to that record and visa versa. The only places the links take you are to the code table definition or to catalog search, neither of which I want.

When making host and parasite records, to save typing, I like to pull the data from either the host or parasite records to move on quickly since they are exactly the same.

Screenshots
Screen Shot 2023-07-31 at 13 20 41

Desktop (please complete the following information):
-iOS

Browser chrome
Version 115.0.5790.114
Additional context
It is fine to have flexibility to look up definitions and get a new catalog search window, but one of the whole points of an active catalogued number was that it too you directly to the record, and you didn't have to copy and paste the catalog number and search, and whole step that is unnecessary. Same for the pull feature for these related records. I use these feature a lot and would like them back. Thank you.

Priority
ASAP because we are starting a project where we need easy access to parasite and host (or bird, fish etc..) records with a single link and well as create new related records efficiently. Thank you

I am not sure I fully understand why we can't have this feature and I will be happy to meet briefly with anyone to figure out how I can get that back. I realize for most maybe this is not a critical feature to have/lose, but for us it is.

**Comment by Jegelewicz** [comment]
@msbparasites this will work once the identifiers have been converted. @dustymc is working on it now.
