### ISSUE TITLE
Catalog record (aka Specimen) Event and the Georeference Bot

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6170]
Today the Code Table Managers did not do Code Table work. Instead, we worked on building a better bulkloader, but we also went down a rabbit hole with regard to the Georeferencing bot

 - https://github.com/ArctosDB/arctos/issues/5813
 - https://github.com/ArctosDB/arctos/issues/6151

Which led us to a discussion of why Arctos is not more explicit about who added coordinates to a locality.

 - https://github.com/ArctosDB/arctos/issues/4866

And there are related issues with things in the Catalog Record Event which seemingly are more appropriate in the Event

 - https://github.com/ArctosDB/arctos/issues/5703

For me, it seems clear that we are not properly recording information about who determined the locality information (both specific locality and coordinates) and we are placing data from an event that should be shared by any record using the event at the record level (habitat, collecting method, event type)

I would propose that most of the information we currently place in catalog record event should be moved to locality or event:

Field | Move to 
-- | --
specimen_event_type | event
event_assigned_by_agent |  
event_assigned_date |  
verificationstatus | locality
collecting_method | event
collecting_source | event
habitat | event

This would mean the the catalog record event would really just be recording who decided that this event belongs with this catalog record and when they made that determination.

[EDIT]
I forgot to mention, that we also desperately need better documentation of who added coordinates to a locality and when. We at least need a coordinate_determiner and coordinate_determined_date, but we may also need expanded protocols and/or a determiner and date for the specific locality (I'll let Dusty explain that one - you will enjoy the foggy shoreline and a $10K GPS...)

Before we proceed with a bulkloader rebuild that is meant to last 5 years (#5193), we thought that this should get attention.

@ebraker @Nicole-Ridgwell-NMMNHS @campmlc please weigh in if I have misquoted or left anything out.

@DerekSikes I believe you will want to see this too.

**Comment by dustymc** [comment]
> why Arctos is not more explicit about who added coordinates to a locality.

In part: https://github.com/ArctosDB/arctos/issues/5120 is stuck behind some things that keep changing. (And in general, I think the thing that's capable of carrying metadata and complexity is often viewed as somehow inferior to "a field" - it's not!)

>Dusty explain

We often view descriptive data as primary and coordinates as derived. That's not always true, coordinates can be primary (GPS, Loran, or just someone with a compass and three landmarks). Descriptive data are often added to that, and then it's often no longer possible to tell what the original is, nor how precise it might be. ("The original" might be transmitted data from a very precise device or a vague description of a place - and a bad description or overly-precise georeference might be added to that.) If we're going to add some sort of a determiner, then we also need to say something about what they're determining. 

(And sometimes I think that should be extended to to geography and such, but maybe that's adequately covered by proper use of verbatim locality.)

**Comment by ebraker** [comment]
Sorry I had to suddenly jump ship yesterday - I had a visiting researcher at the door. I had a thought when we talked about flattening data, not sure if it helps anything...

What if coordinates, determiner, verification_status etc. were housed in separate  "Coordinate" table pulled out from Locality but connected via Locality ID? This would allow, potentially, one version of "Boulder" [Colorado] that many collections will converge/overlap with, but, with the option to record different coordinates based on different pinpoints, error, historic maps, etc. That way, there is one and only one "Boulder" Colorado (great for discovery), but infinitely many ways that coordinate determiners can interpret it.

@dustymc if this doesn't make sense or is a bad/unworkable idea, I'll just delete this comment. Otherwise, agree with @Jegelewicz.

**Comment by dustymc** [comment]
>What if coordinates, determiner, verification_status etc. were housed in separate "Coordinate" table pulled out from Locality but connected via Locality ID? This would allow, potentially, one version of "Boulder" [Colorado] that many collections will converge/overlap with, but, with the option to record different coordinates based on different pinpoints, error, historic maps, etc. That way, there is one and only one "Boulder" Colorado (great for discovery), but infinitely many ways that coordinate determiners can interpret it.

I'm not a fan for a few reasons.

* that's something like the original model, and there was always a disconnect - someone would georeference, then someone would change the locality, then the georeference makes no sense, etc.
* the original model had one or zero 'accepted' georeferences, this would be something else - you'd have to somehow pick a locality, then also pick a spatial representation of it
* this is entirely incompatible with coordinates-first, and I think that's entirely incompatible with reality (in part because GPS are cheap and accessible)

I remain convinced that descriptive and spatial data are all inseparable parts of the same THING, whatever the details of that THING turn out to be.

>flattening data,

I think I heard that the current structure (or something like it) is necessary/desirable, so the idea that we can simplify/flatten the structure if we're going to treat localities more like determinations than facts is probably dead.

**Comment by Jegelewicz** [comment]
> that descriptive and spatial data are all inseparable parts of the same THING, whatever the details of that THING turn out to be.

I agree with this assessment. Although there may end up being 5, 10, or 1,000 "Boulder" in locality, I think we just have to live with that. Some of them should maybe have more descriptive specific localities and some should maybe just be combined, but it will take a person with knowledge of the place and the objects associated with it to do that. People searching for "Boulder" would still find things from any one of those localities, so.....

**Comment by ebraker** [comment]
That's fine and makes sense, just throwing it out there to see if it would help anything.

**Comment by dustymc** [comment]
5120 is completed, there's an information-rich locality-attached way of describing the source of the coordinates (or most anything else), closing.
