### ISSUE TITLE
ER Diagrams and general database admin

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ArctosDB/arctos#619]
```
Figure out a better way to generate ER diagram for Arctos data model - email 
thread with Dusty and Carla 16 Apr 2013
```

Original issue reported on code.google.com by `carla...@gmail.com` on 16 Apr 2013 at 11:17

**Comment by dustymc** [comment]
There are two primary related problems with generating and maintaining ER diagrams:

1) They're a lot of work. We change things often, and making those changes in ER software is a significant workload (and does nothing for us - something we could perhaps change with adequate software).

2) They're misleading and not very useful. Much of Arctos is not "typical" tables and keys, but instead is dynamic, data-driven, trigger-controlled, and/or drawn from non-local resources. The boxes and lines on a typical ER diagram do not accurately represent the scope or precision of Arctos. Media relationships are not in fact a dead end; attributes are rigorously datatyped and controlled despite their structure, and much of the taxonomy data in Arctos is merely a constantly-updated cache of GlobalNames, none of which could be realized from an ER diagram. (Code tables have traditionally been eliminated from our ERs as well. They - or most of them - are easy enough to add, but would add another ~100 tables and ~1000 relationships to an already-crowded graphic.)

DLM suggestion: Create a simplified "artist's conception" in something like PowerPoint. Provide people who need more information access to the DDL repository, or to an Oracle server from which appropriate ER software can extract relevant information.

**Comment by ccicero** [comment]
An artist conception might work, but that seems like a lot to maintain and keep updated. The main goal I think is to create an updated diagram of tables for SQL queries.

**Comment by mkoo** [comment]
The priority would not be the 'artistic' concept but as stated, for
identifying table structures and relations to facilitate SQL.

A figure-friendly sketch is a good idea too for presentations but I would
say, just not a priority.

**Comment by dustymc** [comment]
Nothing could possibly be more work for less benefit than fighting with our evil ER software. I haven't used it in a decade and still have nightmares....

We could discuss how far to extend the "artwork" - if all you want are major tables and obvious lines, perhaps we can use some simpler ER software. I think LKV has been trying to make things complete and nicely-arranged, both of which are mostly impossible with the aforementioned evil ER software.

If we do need anything approaching complete (useful for SQL) ERs, then buying TOAD (which has some other cool features) is almost certainly cheaper than paying someone to drag boxes around on what we have now, and the result will be much more than a misleading printout.

One of the problems with our (printed) ER is that is is NOT (always) useful in constructing SQL queries; a bunch of things that exist in the DB are created dynamically, a bunch more are data-dependent, etc. I really don't have a solution. I think if you drop a completely naive (but Oracle-savvy) user in and pointed them at the DDL directory they'd figure things out, but not in any straightforward path - they'd need to refer to keys and triggers and comments and etc. to figure out data-dependent constructs and ...

TOAD (and maybe some other stuff) can pull all of that out of the DB, and as SOFTWARE probably is a reliable path to anywhere in Arctos. As a printout/PDF, not so much.

What are you trying to SQL?

**Comment by ccicero** [comment]
I use the (old and outdated) ER diagram regularly to look for field names
which do not match label names on forms when I am doing SQL queries. And
also the relationhips between tables. See SQL examples in
https://goo.gl/ZkboV

So basically, table names, field names, and table relationships.



On Wed, Sep 2, 2015 at 9:23 AM, dustymc <notifications@github.com> wrote:

> Nothing could possibly be more work for less benefit than fighting with
> our evil ER software. I haven't used it in a decade and still have
> nightmares....
>
> We could discuss how far to extend the "artwork" - if all you want are
> major tables and obvious lines, perhaps we can use some simpler ER
> software. I think LKV has been trying to make things complete and
> nicely-arranged, both of which are mostly impossible with the
> aforementioned evil ER software.
>
> If we do need anything approaching complete (useful for SQL) ERs, then
> buying TOAD (which has some other cool features) is almost certainly
> cheaper than paying someone to drag boxes around on what we have now, and
> the result will be much more than a misleading printout.
>
> One of the problems with our (printed) ER is that is is NOT (always)
> useful in constructing SQL queries; a bunch of things that exist in the DB
> are created dynamically, a bunch more are data-dependent, etc. I really
> don't have a solution. I think if you drop a completely naive (but
> Oracle-savvy) user in and pointed them at the DDL directory they'd figure
> things out, but not in any straightforward path - they'd need to refer to
> keys and triggers and comments and etc. to figure out data-dependent
> constructs and ...
>
> TOAD (and maybe some other stuff) can pull all of that out of the DB, and
> as SOFTWARE probably is a reliable path to anywhere in Arctos. As a
> printout/PDF, not so much.
>
> What are you trying to SQL?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ArctosDB/arctos/issues/619#issuecomment-137153568>.
>



-- 
Carla Cicero, Ph.D
Staff Curator of Birds
Museum of Vertebrate Zoology
3101 Valley Life Sciences Building
University of California
Berkeley, CA 94720-3160
TEL: (510) 642-7868
FAX: (510) 643-8238

http://mvz.berkeley.edu/
http://carlacic.googlepages.com/home
http://vertnet.org/
http://en.wikipedia.org/wiki/Bird_collections
http://www.americanornithology.org/

**Comment by dustymc** [comment]
>I use the (old and outdated) ER diagram regularly to look for field names which do not match label names on forms when I am doing SQL queries. 

I can see that being useful when we're systematically calling "quad" "USGS Map Name" or something, but that's often (usually?) not the case - you're seeing some sort of processed data on the form, and an ER won't get you to the source. (And much of that mapping is in "field-level documentation.")

The Arctos DDL-fetcher or the writeSQL widget will get current table descriptions.

Probably 99% of my report-type SQL queries hook into FLAT or use some function or both or.... all of which is not "data" and so would probably not be on an ER diagram - and if it was you'd still need the things that build it to understand what you're looking at (the flat-to-data mappings are very complex - if they weren't we wouldn't need flat! - and column names aren't always what you'd guess from DWC descriptions, etc.)

>See SQL examples in https://goo.gl/ZkboV

The first few things on there:

- dates: use flat
- admin/logs: not ER-stuff
- type status: MAYBE an ER would be useful here - you've taken one of the two paths back to specimens - the other leaves by identification_id - would that be obvious from an ER?
- GenBank Numbers: relies on code tables, not in ER, and processed data ("display value" is the only single queryable field, and is not on any edit form/you need the trigger to understand it).
- Bulkloader: not in ER
- taxonomy: outdated, won't work. ER diagram won't much help; "real" answer is very complicated, partially relies on something that won't be on an ER (preferred classification) - probably-what-you-want answer is in FLAT (which isn't in the ER)
- QUERY TISSUE PARTS WHERE TISSUE FLAG IS "0" - CTtables, not in ER

I think you're mostly using that to ask "fringe" questions which often aren't on the ER (or have a much simpler path which isn't on the ER) - presumably because Arctos is pretty good at answering the more common stuff.

>basically, table names, 

You can get a list at the table-ddl tool - but see above, often there's a much easier path through a "query table" or view or function or .....
 
> field names,
writeSQL, select * from tablename where 1=2, or the DDL tool

> and table relationships.

those are also in the DDL tool, but as all the above they have limited utility.

I remain unconvinced that maintaining a full ER is a useful exercise, but I think I'm starting to understand what you're up against. It is not at all clear how we can help.

For example, coming from Accn (first thing in the DDL-getter), if I wanted to get to agents I'd use functions getPreferredName() and/or getAgentID(). If I wanted to get to specimens, I'd follow the keys to trans and then skip over to FLAT (which has a pulled-from-key column I can join on). In this case you can follow keys to get what you want, but it's a lot of work/joins/places to introduce problems.

Other than working with it every day and just knowing it's there, I have no idea how I can communicate those pathways. They're certainly not anything that's in an ER diagram.

I'll add some of that to the SQL document, but I can't add it all - that would just be the DDL folder....

Lam will look at SQL Developer - perhaps a quick-n-dirty ER in conjunction with some of the above could be useful, if that's possible with the tools and access we have.

????

**Comment by mkoo** [comment]
I'm closing this although it's not resolved. We can revisit after API improvements may render parts of the need obsolete.
