### ISSUE TITLE
Profile delete position

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6200]
Once you select a profile, the delete option appears directly below the selection, hiding (for me anyway) the adopt button. Most people will be coming here to adopt a profile. I think we should switch the order.

![image](https://user-images.githubusercontent.com/5725767/235167957-59c52e7e-04f6-43d0-a242-cba9f3048e0a.png)

**Comment by dustymc** [comment]
>switch the order

The first section is things regarding the selected profile - I don't think the delete button can possibly make sense anywhere else.

It's stretched out because you wrote a bunch of stuff. Is that necessary? (We go back and forth - angrily, sometimes -  between "why isn't there documentation!?" and "what's all this crap, I'm not reading that?!" I like the option, but it it's going to force us into some less-organized layout then I'll happily join forces with the 'no words!' faction and kill it....)

Or, perhaps that should look different based on screen size (for which hiring a CSS developer is probably Step One): It looks pretty different on my 15 inch laptop which is currently set on font size "old man."

<img width="1669" alt="Screenshot 2023-04-28 at 7 11 30 AM" src="https://user-images.githubusercontent.com/5720791/235171067-1c1113ff-6008-41eb-b169-fc770df58e85.png">

**Comment by Jegelewicz** [comment]
I also use a 15 inch laptop, with my browser zoom set at 90%

>  because you wrote a bunch of stuff. Is that necessary?

Yes - I am sick and tired of not knowing what the heck things are and/or do. I hope that bunch of stuff will help others decide if they can use this profile or not (I'm looking at you @dbloom )

See also #6202

**Comment by dustymc** [comment]
>what the heck things are and/or do. 

Good! One no-screen-space option is what I've done elsewhere:

<img width="603" alt="Screenshot 2023-04-28 at 7 40 59 AM" src="https://user-images.githubusercontent.com/5720791/235178181-f000f9c8-008a-42c7-aadf-21cbc7eb216a.png">

I think that's a bit fragile and I'm not necessarily suggesting it, just that perhaps we can be less verbose by default with some sort of 'hu?' click/hover/whatever.

**Comment by campmlc** [comment]
I would prefer less text and clearer options for the buttons, with the option of expanding or opening links/popups for explanation.  I now realize I am much more sensitive to visual clutter than most people, and my response to all that text is to tune it out and focus in on the one thing I need. Maybe I'm not so different, though,since no one reads all that stuff, apparently.

**Comment by Jegelewicz** [comment]
Closing this since I now know that delete only appears when I select profiles that I also created.
