### ISSUE TITLE
search profile management

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#6215]
Can we delete profiles under some conditions? The following is actionable but certainly not the only option.

-----------

Some maintenance schedule (delete profiles attached to users who haven't logged in within the last year or whatever) would be AWESOME.

_Originally posted by @dustymc in https://github.com/ArctosDB/arctos/issues/6212#issuecomment-1531842056_

**Comment by ewommack** [comment]
Maybe? What if profiles are created as part of a project or grant?

**Comment by mkoo** [comment]
I think having profiles available only to the users profile mitigates many concerns and allows users to test etc. Let's propose a mechanism to request a profile to be shared publicly if they meet certain criteria including having a description. For now, due to code of conduct concerns, profiles will only be avialable to the user who created them. 
File a request to have your favs publicly available -- include a brief description to their purpose or intended audience

We will also have this in a future AWG meeting demo since there's also clear confusion about saved searches vs saved query options!

**Comment by dustymc** [comment]
>means that you cannot share a profile

Not quite.

I can share my profiles - here you go: https://arctos.database.museum/search.cfm?sp=attrsandexam

I can even share your profiles: https://arctos.database.museum/search.cfm?sp=UWBM%3AMamm%20Tissues

Click Customize and Option 3 and either of those can be yours too. (Option 1 would have to go away under a more restrictive model.)

Restricting the list to the creator (and "Arctos" probably) would just mean that the creator would have to make the offer, things can't just be taken.

**Comment by dustymc** [comment]
AWG Issued discussed, no special requests

https://docs.google.com/document/d/1fKM_nC-pHv4FUnBPZCKF4FJVW2wC2CuQDrBYjdvv-3E/edit
