### ISSUE TITLE
Improvements to Log In and Log Out page - UI Committee suggestion

### ISSUE THREAD

**Issue by ewommack** [ArctosDB/arctos#6239]
From the UI Committee - decided by discussion:
Log in and Log Out Issues and Suggestions
When you log out of Arctos have the log out page jump straight to the home page instead of landing on a page to ask you to go to the home page
On the opening page of Arctos -> inside the security acknowledgement box:
Add a button next to “I Acknowledge” -> Log In button
Add a button next to “I Acknowledge” -> Create an Account button
Change the acknowledgement box color to the light/baby blue coloration

**Comment by Jegelewicz** [comment]
![image](https://user-images.githubusercontent.com/5725767/236321395-44f862eb-255e-4a16-aa87-1a435428e99c.png)

The buttons take the user to

I agree, continue - search
I agree, log in - login splashpage with cursor in username field
I agree, create an account - create an account page with cursor in the top field

## Dream Big!
Also, could the first button be "highlighted" so that using enter would select it or using tab would move you over to the next one? (Mouse free use of the screen?)

**Comment by Jegelewicz** [comment]
> When you log out of Arctos have the log out page jump straight to the home page instead of landing on a page to ask you to go to the home page

OK - I think I asked for this NOT to happen in the past, but I think it would be OK now, because of the I agree thingee. My previous complaint was that I would get an error because the search page was trying to something I couldn't do as a public user.

**Comment by Jegelewicz** [comment]
I made this next task - but feel free to change the milestone if necessary!

**Comment by Jegelewicz** [comment]
Also part of #5852

**Comment by dustymc** [comment]
>e log out page jump straight to the home page

I usually log in and out to access something other-me can't, being forced somewhere else would be super annoying. Surely I'm not alone in that?

Multiple paths to the same thing (several ways to log in) has been an emotional issue in the past. Is this arrangement acceptable on that front?

> first button be "highlighted" 

I thought https://github.com/ArctosDB/arctos/issues/6238 was uncontroversial and I could experiment with this there, but now I'm not sure??

@DerekSikes I can't remember specifics but I think much of the current login page is from your comments, any comments on this?

>next task 

I think we need to fill in the gaps in https://github.com/ArctosDB/internal/issues/258 and use that process, whatever it becomes.

**Comment by DerekSikes** [comment]
I greatly dislike multiple ways to do the same thing. A single path is simpler to learn and use & train etc. I would be in favor of this if the [log in or create account] link in the upper right corner was removed. 

Currently I find it a minor UI annoyance that that link is in the far upper right and when clicked the next button to actually login is far to the left - getting these buttons as close together on the UI so one doesn't have to navigate the cursor across such a vast region of screen space between them would be an improvement.

Perhaps a distraction to this discussion but it was sometime before I learned that one can ignore the 'agree' button and just click the login button first to bypass the 'agree' statement. Although that saves clicking I do like Teresa's UI mockup better since it forces people to realize/state they 'agree' and prevents them from ignoring this (if the upper right link goes away - but I'm not sure how that works with the rest of the UI, eg logging out etc.

**Comment by dustymc** [comment]
> if the [log in or create account] link in the upper right corner was removed.

That'd mean...


* accept terms
* do stuff as a public user
* find a way to reset your session to force yourself back to the pre-auth screen with the button when you want to log in

**Comment by campmlc** [comment]
@DerekSikes can you confirm that your comments are supporting the mockup above, as that would solve your concerns?  I strongly support the proposal for exactly that reason.
I'm also happy to get rid of the Login or Create Account on the top right as redundant to what we are proposing to build here, but I can also see keeping both since it doesn't really hurt anything?

**Comment by DerekSikes** [comment]
Dusty,

The buttons of Teresa's mockup = anyone with an account would click the middle button to agree & login.

& I suppose having the upper right link to login is ok despite it being redundant. >1 way to do 1 thing is bad in principle tho.

**Comment by dustymc** [comment]
> anyone with an account would click the 

SOMETHING, which in some situations would remove the possibility of later clicking something else.

>bad in principle 

It's also harder to deal with in code (I'll end up the the expected 'thing' plus a 'thing1' or something equally arbitrary) and adds a maintenance cost and etc. I think that's all pretty minor in this case, but even very minor things add up. There's also clearly a perceived benefit (also minor??), and I have no idea how to balance those things. Perhaps considering sustainability should be some explicit part of https://github.com/ArctosDB/internal/issues/258.

**Comment by campmlc** [comment]
From the point of view of operators like myself having to log in and out multiple times a day, I believe the benefit in this case outweigh the minor cost. We keep the dropdown on top right to make sure people always have a way back or out, no matter what form they end up in . And we make the initial login easier. If we do this, and one or the other is a problem, we get rid of one. But keeping the top right option for now at least means we don't utterly change something people may have gotten used to, but we add improved functionality in the main login. My two cents.

**Comment by ewommack** [comment]
> & I suppose having the upper right link to login is ok despite it being redundant. 

@DerekSikes it might not be redundant if you had already agreed, moved onto another page, and then said "ooh now I want to log in". I think once you are into Arctos there becomes only one way to login. Does that help?

**Comment by campmlc** [comment]
Any progress on this? It would be good to finish this and resolve. It appears other projects are now underway - please let's complete ones already in progress.

**Comment by Jegelewicz** [comment]
I think this is now dead and everyone is just going straight to Login?

@ewommack @campmlc

**Comment by campmlc** [comment]
It would be nice to have the login option in the same box or at least adjacent to the I agree to conditions box. That would save everyone some searching and clicks.

**Comment by DerekSikes** [comment]
yes, I agree - It would be great to move all the clicking buttons/boxes for login (I agree) etc. to the same small portion of the screen! Details like this make the UI more efficient and everyone happier!

**Comment by dustymc** [comment]
I don't know what's being requested, nor how to reconcile it with eg https://github.com/ArctosDB/arctos/issues/3514, https://github.com/ArctosDB/arctos/issues/6239#issuecomment-1535377848, https://github.com/ArctosDB/arctos/issues/6239#issuecomment-1535457311, and I think a few more. I am tabling this; please open a new focused+comprehensive issue (mockups are always super helpful!) if there are any actionable outstanding requests.

**Comment by DerekSikes** [comment]
Surely you understand "move all the clicking buttons/boxes for login (I agree) etc. to the same small portion of the screen"

&  is simple, uncontroversial, and actionable?

**Comment by dustymc** [comment]
try for https://github.com/ArctosDB/arctos/issues/6239#issuecomment-1535370563 thanks @Jegelewicz  

@DerekSikes if I understood I'd be writing code instead of telling ya'll I don't and feeling like a moron for it, a nudge in the right direction is always appreciated.

**Comment by DerekSikes** [comment]
![Slide1](https://github.com/ArctosDB/arctos/assets/9099827/297e12b1-0b7f-436c-870a-7bf1b644dd69)
and
![Slide2](https://github.com/ArctosDB/arctos/assets/9099827/b0564bf6-654e-4b85-a24a-665403635a38)

**Comment by DerekSikes** [comment]
or... move the log in or create account hotlink to the far left above all the other buttons etc.

**Comment by DerekSikes** [comment]
Forgot one:
![Slide3](https://github.com/ArctosDB/arctos/assets/9099827/8c720d0a-cac9-4cdd-bf06-8fa24df5b52d)
