### ISSUE TITLE
Code Table Request - not examined for

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6261]
## Instructions

_This is a template to facilitate communication with the Arctos Code Table Committee. Submit a separate request for each relevant value. This form is appropriate for exploring how data may best be stored, for adding vocabulary, or for updating existing definitions._

_Reviewing documentation before proceeding will result in a more enjoyable experience._

* [Issue Documentation](http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html)
* [Code Table Documentation](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html)
* [Video Tutorial - Submit a Code Table Request](https://youtu.be/t2jHbsRA3lk)

------------------------------

## Initial Request

_**Goal**: Describe what you're trying to accomplish. This is the only necessary step to start this process. The Committee is available to assist with all other steps. Please clearly indicate any uncertainty or desired guidance if you proceed beyond this step._

See background in https://github.com/ArctosDB/arctos/issues/6222#issuecomment-1533529551 and the comments that follow.

A place to put the no valued in examined for as it exists now.

_**Proposed Value**: Proposed new value. This should be clear and compatible with similar values in the relevant table and across Arctos._

not examined for

_**Proposed Definition**: Clear, complete, non-collection-type-specific **functional** definition of the value. Avoid discipline-specific terminology if possible, include parenthetically if unavoidable._

The record was not examined for the given value. 

_**Attribute data type** If the request is for an attribute, what values will be allowed?
free-text, categorical, or number+units depending upon the attribute (TBA)

categorical

_**Attribute controlled values** If the values are categorical (to be controlled by a code table), add a link to the appropriate code table. If a new table or set of values is needed, please elaborate.

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctexamined_detected 

_**Attribute units** If numberical values should be accompanied by units, provide a link to the appropriate units table.

N/A

_**Context**: Describe why this new value is necessary and existing values are not._

See Goal and background. Also agreed to at Parasite/Pathogen Meeting today.

_**Table**: Code Tables are http://arctos.database.museum/info/ctDocumentation.cfm. Link to the specific table or value. This may involve multiple tables and will control datatype for Attributes. OtherID requests require BaseURL (and example) or explanation. Please ask for assistance if unsure._

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type 

_**Collection type**: Some code tables contain collection-type-specific values. ``collection_cde`` may be found from https://arctos.database.museum/home.cfm_

Mamm, Bird, Herp, Rept, Amph, Fish

_**Priority**: Please describe the urgency and/or choose a priority-label to the right. You should expect a response within two working days, and may utilize [Arctos Contacts](https://arctosdb.org/contacts/) if you feel response is lacking._

_**Available for Public View**: Most data are by default publicly available. Describe any necessary access restrictions._

yes

_**Project**: Add the issue to the [Code Table Management Project](https://github.com/ArctosDB/arctos/projects/13#card-31628184)._

_**Discussion**: Please reach out to anyone who might be affected by this change. Leave a comment or add this to the Committee agenda if you believe more focused conversation is necessary._

@ArctosDB/arctos-code-table-administrators 

## Approval

_All of the following must be checked before this may proceed._

_The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality)._

- [x] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [x] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

## Rejection

_If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc._

1. _Can a suitable solution be found here? If not, proceed to (2)_
2. _Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)_
3. _Take the discussion to a monthly Arctos Working Group meeting for final resolution._

## Implementation

_Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made._

_Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel._

_Make changes as described above. Ensure the URL of this Issue is included in the definition._

_Close this Issue._

_**DO NOT** modify Arctos Authorities in any way before all points in this Issue have been fully addressed; data loss may result._

## Special Exemptions

_In very specific cases and by prior approval of The Committee, the approval process may be skipped, and implementation requirements may be slightly altered. Please note here if you are proceeding under one of these use cases._

1. _Adding an existing term to additional collection types may proceed immediately and without discussion, but doing so may also subject users to future cleanup efforts. If time allows, please review the term and definition as part of this step._
2. _The Committee may grant special access on particular tables to particular users. This should be exercised with great caution only after several smooth test cases, and generally limited to "taxonomy-like" data such as International Commission on Stratigraphy terminology._

**Comment by dustymc** [comment]
The definition needs clarified; it should (somehow) be made explicit that this cannot be Research Grade, that the presence of this attribute should be treated identically to NULL for research purposes.

**Comment by dustymc** [comment]
sciencey?

If there's some nonadministrative difference between this and nothing, I can't see it. If I just can't see it then the definition clearly needs made better. If we're really saying something that looks like maybe it should be used in prevalence studies, but absolutely should not be used in prevalence studies (because most of the records that experienced the same treatment - of nothing - do not carry this assertion) then that should be made clear to the user.

**Comment by Jegelewicz** [comment]
>  we're really saying something that looks like maybe it should be used in prevalence studies, but absolutely should not be used in prevalence studies (because most of the records that experienced the same treatment - of nothing - do not carry this assertion) then that should be made clear to the user.

Not disagreeing, but are prevalence studies the only place this could be misused?

**Comment by dustymc** [comment]
>only place this could be misused

There's the problem! Listing some of the things that didn't happen when an infinite number of things could have happened just adds confusion. Having a confusing thing seems to be the cost we must pay to get out of a denormalization situation, I'm just asking for a clear definition.  (And I'm guessing at what that might be, I clearly don't understand the need for this.)

**Comment by campmlc** [comment]
Actually, we should leave the decision to use or not to the researcher. This SHOULD be used to determine prevalence, because it specifically flags records that any knowledgeable researcher would know not to include in the calculation. It is therefore a valuable piece of data that is needed for prevalence determination. Again, we should not be the data police here - we are the data publisher. It is up to the researchers to determine fitness for use. But we need to be as explicit as possible as to what data we have, how, when, where, why, and by whom they were collected.  That is the point of this attribute.
Suggest we modify the definition:

Records carrying this attribute were "not examined for" only the specific value as given; additional metadata should be recorded in the attribute methods, date, determiner and remarks sections. Attributes lacking these metadata may be legacy data for which no additional data are available; users are highly encouraged to determine fitness for use in prevalence analysis and other usage by closely examining metadata fields.

**Comment by dustymc** [comment]
>leave the decision to use or not to the researcher.

That involves clearly communicating the meaning. I believe this to be an arbitrarily-applied value. If that's not the case then a more appropriate definition should be proposed.

**Comment by campmlc** [comment]
It is not arbitrary. I am in the field surveying mammals and their parasites. I collect 100 rodents, but I only have the time and resources to examine 80 of them for ectoparasites and 30 of them for endoparasites - and maybe another subset for hantavirus. These are all collected in the same collecting event, same examiner. But some will have the "examined for" attribute with my name, date, and methodology, and others will have "not examined for" attribute, with same info on name, date, and methodology.  
A researcher will want to find all the animals from this project/accession/collecting event, and filter for those that were examined for parasites to use in the prevalence calculation. Unfortunately, we have a huge amount of missing examined for (endo/ecto/parasites) data because 1) the attribute didn't exist at time of data entry,  2) once the attributes existed, host collections ran out available attributes in the bulkloader or or 3) these data were shoved into some other remarks column because of reasons. Once the fields existed and collections were able to capture negative values for examined for, the data were entered, and that is highly useful information as it tells the collection manager and the researcher not to waste time looking for or using those data.
This all makes sense to every person who collects and uses these data. This protocol has been in place in parasitology research for at least a century. What would be arbitrary would be failiing to record these data according to standard methods.
Can we just go with the updated definition, please? This is holding up conversion of parasite/endoparasite/ectoparasite examination attributes.
@acdoll 
@jldunnum 
@bryansmclean 
@msbparasites

**Comment by campmlc** [comment]
Some relevant examples of these data already in Arctos:
 4,685 records at MSB with "%not examined%"in collection object remarks - because there was no where else to put the data. https://arctos.database.museum/saved/MSB%20not%20examined%20in%20collection%20object%20remarks

These include older Beringian Coevolution Project and CIIBA data where parasites were explicitly collected, but the host data lacks the attribute information. With this proposed attribute, we would have an explicit place to migrate these data.

Also includes Rausch data, with explicit details on which individuals (and which organs) were and were not examined:
![Screenshot 2023-05-09 13 56 37](https://github.com/ArctosDB/arctos/assets/14808196/0b39ac85-783f-400a-a9c2-1c036a622e28)

**Comment by ccicero** [comment]
New code table value added 18 May 2023!
