### ISSUE TITLE
how to query NULL on attribute, and other things

### ISSUE THREAD

**Issue by cjconroy** [ArctosDB/arctos#6290]
As part of the RANGES project, I'd like to find all of a species that does NOT have any measurement in, for example, total length. What can I put in the attribute value box to do that?
Sort of related, the attribute value box has light grey text that, on my computer screen in Chrome, reads "value; prefix with = for"   I assume there is more text there. I see even less on Safari.

On a related note, does anyone have any thought as to how to populate arctos to indicate something like no attribute data found, by who, what date. For current attributes, does there need to be a value to save it? Could one create an attribute of total length, no value, but have a remark like "no data found in field catalog or skin tag" with an agent of whoever searched. 
Again, related. I noticed that in data entry, you cannot have an unpopulated attribute. This is sometimes challenging where some specimens lack an attribute, but the next one has it, so you are repeatedly adding and removing attribute names. It would be helpful if Arctos could just ignore it.

**Comment by dustymc** [comment]
See also https://github.com/ArctosDB/arctos/issues/5759 - but I think RANGES now does not need that and intends to assert everything that didn't happen. (I still fail to see how this is possible, perhaps someone else can explain, and perhaps that will answer your question.)

The placeholder is cut off on my screen as well, perhaps the 'howto' bits should be removed from it?

**Comment by mkoo** [comment]
This is really 3 issues-- for better results please file 3 different ones: the first one seems to be addressed w/ https://github.com/ArctosDB/arctos/issues/5759 which implemented Null search on attributes.

Second one: you cannot add an attribute with no values (the value field is yellow when you add an attribute so that's the clue it's required). If you have a strong use case for that, please file an issue

Third one: I'm not sure what you're referring to but again please file an issue if you need this. This may require a demo at an Issues meeting so we know what you're talking about!
Thanks
