### ISSUE TITLE
saved searches created from portals give unexpected results

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ArctosDB/arctos#630]
```
What steps will reproduce the problem?
1. Log in to Arctos as an operator
2. Find something; save search
3. Log out; go to saved search

What is the expected output? 

The saved search

What do you see instead?

The saved search PLUS everything else that the search terms find, in any 
collection

Maybe explicitly add collection_ids to all results of operators???? (Lam? How 
can we get at those data?? Some VPD call@session initialization maybe?)

```

Original issue reported on code.google.com by `dust...@gmail.com` on 5 Jun 2013 at 7:45

**Comment by dustymc** [comment]
Adding to wish list - this may be best dealt with as part of a larger discussion about how the VPD works, eg, #250

**Comment by dustymc** [comment]
Saved searches involving customID are strange too

**Comment by mkoo** [comment]
Resurrecting this ancient issue on Saved Searches. Also amping it's importance since this is a really useful means to communicate with  outside agencies and others about our assets like media, which is bizarre to outsiders how to search. If there's issues with specimen searches, I havent been able to see that yet.

Save Searches appear broken for MEDIA searches 
Example below from the auto-email gives a 404 error
------
To view specimens, click the following link:
media%2DHistoricGrinnellSurvey%2Dsearchterm%2Dcamp
or paste this address into your browser:
https://arctos.database.museum/saved/media%2DHistoricGrinnellSurvey%2Dsearchterm%2Dcamp
