### ISSUE TITLE
[external CONTACT] help with claiming barcodes

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#6313]
@dustymc I still have trouble figuring how how to claim barcodes in Arctos (syntax is confusing to me). I want to barcode our bird cases that have uncataloged materials for better tracking. I'd like the barcode to look something like "MVZ3101-BIRD01; MVZ3101-BIRD02; etc.). 

I'm also not clear on how to test a barcode. I tried entering the UCM barcode into the 'Enter a barcode to test' field and they all fail. What part of the barcode do you put in the field? This is what I put: ^UCM_[A-Z0-9_-]*$ (I also tried the whole thing but it didn't work either: barcode~'^UCM_[A-Z0-9_-]*$')

Help? Thanks!

**Comment by dustymc** [comment]
``^MVZ[0-9]{4)-BIRD[0-9]{2}$``

is "{start}MVZ{4 numbers}-BIRD{2 numbers}{end}"

That said, I can't think of a single "smart" barcode system that hasn't eventually come around to haunt everyone. 100% recommend MVZCASE{1.....9999999} or ANYTHING that doesn't confound the identifier and physical position (or whatever that it).

The test just accepts a barcode - https://arctos.database.museum/info/barcodeseries.cfm?barcode=UCM_JAR-4727

.... and will reveal when there are overlapping claims (one more common problem with "smart" barcodes!)

@ebraker 

<img width="827" alt="Screenshot 2023-05-19 at 9 27 14 AM" src="https://github.com/ArctosDB/arctos/assets/5720791/49133c09-827b-484a-9c38-4f55086e935a">

**Comment by ccicero** [comment]
@dustymc Thanks. So how about "{start}MVZ{4 numbers}-BIRDCASE{2 numbers}{end}" ?

And to test, I would enter 'MVZ3101-BIRDCASE01' ?

**Comment by ccicero** [comment]
Or, if in the future all cases are eventually barcoded, then maybe

"{start}MVZ{4 numbers}-BIRDCASE{4 numbers}{end}" which would look like 'MVZ3101-BIRDCASE0001' ?

**Comment by dustymc** [comment]
@ccicero I guess it depends on what those numbers mean. If 3101 is some room, then eventually someone will find a way to lug the case into 3102 (or relabel the door, or....) and then it'll confuse everyone. "01" is going to become "1" in anything that deals with integers. Maybe someone (possibly someone with a screwdriver) will find a way to stuff BIRDCASE0001 into MVZ3102 (or vice-versa, IDK what those things mean!). Etc., etc., etc. 

As a string-separator I don't think there's much functional difference between ``-`` and ``-BIRD`` and ``-BIRDCASE``.

Some unique prefix (because of the Actos-wide unique constraint) then start at 1 and work towards infinity, maybe with some more-compact encoding (base36 is easy and compatible with most barcode encodings and scanners, but unicode might support base~150K if you really want to go wild!) would always be my first choice.

Lots of Arctosians clearly do have more complex schemas, I'm probably being more conservative than reality really demands, but I'm still a big fan of simple.

Slightly different view of the above: Barcodes are purposefully difficult to change, labels are super easy. If your barcode says "room1case1" and then 'room1' becomes 'room3' and case1 becomes 'case 17' then people will get confused and it's sort of a pain to do anything about it without breaking some bigger system/idea. If the *label* of barcode 'MVZ{randomnumber}' needs to change from 'room1case1' to 'room3case17' then you just reprint (or sharpie) the label and everything keeps working. (But under that view the label might be "MVZ Bird Collection Room ...."  - something that's completely clear to humans, even though it would not make a great barcode.)

**Comment by ccicero** [comment]
@dustymc @cjconroy OK, change the room to 3103 which is the main MVZ space (thanks for the map Chris). Those cases are highly unlikely to move to a different room so I think we're safe there.

I don't totally understand what you're saying. I could do ""{start}MVZ{4 numbers}-BIRD-CASE{4 numbers}{end}" which I think would look like 'MVZ3103-BIRD-CASE1' based on what you're saying (but allows for up to 4 digits after case). Is that correct?

Label would be descriptive, e.g., 'MVZ Curatorial Area-Bird Working Case 1' or something like that.

???

**Comment by dustymc** [comment]
The actual regex (what you want to enter into the form) for "{start}MVZ{4 numbers}-BIRD-CASE{between 1 and 4 numbers}{end}" (my maybe-unnecessary attempt at explaining the regex - and note the change) would be

``^MVZ[0-9]{4}-BIRD-CASE[0-9]{1,4}$``

MVZ3103-BIRD-CASE1
MVZ0000-BIRD-CASE000
MVZ0000-BIRD-CASE0001
MVZ9999-BIRD-CASE9999

should all pass that.

**Comment by mkoo** [comment]
Sorry I wasnt around to help with this but I would NOT include a room number. the containers are already assumed hierarchically structured and that redundancy will not be helpful

SQL = barcode~'^MVZ-BIRD-CASE[0-9]{1,4}$' is ok or drop the 'MVZ' part is better.

This makes sense today, probably not 'tomorrow'
