### ISSUE TITLE
Bring back ability to page through catalog records with navigation arrows

### ISSUE THREAD

**Issue by genevieve-anderegg** [ArctosDB/arctos#6341]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
There used to be navigation arrows at the top of a catalog record page that allowed you to navigate forward and backward through records. I believe they were at the top right of the catalog record page. This was especially useful when navigating through catalog record search results. Currently I have to individually open up each record from the search result list in a new tab, review the record, and then close that tab, which is slow and rather annoying.

**Describe what you're trying to accomplish** 
Create a way to "page through" catalog records quickly and easily, probably by bringing back those navigation arrows.

**Describe the solution you'd like**
Reinstate the navigation arrows. 

**Describe alternatives you've considered**
Individually opening up each record at a time, which is not ideal.

**Comment by dustymc** [comment]
I'm sure this is a duplicate, but I can't find the other....

This worked previously because Arctos was session-based: your last search always followed you around. That has not been the case for some years (and so the buttons were probably doing something sorta randomish for some years...), so that mechanism is not available.

The usual approach would be to send a sorted list of IDs with the guid-page requests, but under the current limitations this would be a maximum of 500K identifiers (each  ~16bytes) repeated 500K times - plenty to melt everything everywhere.

I think this is probably just incompatible with the current UI, but I am very open to clever ideas. 

(Or there's an API if someone wants to build something around this idea!)

**Comment by genevieve-anderegg** [comment]
I would love to know what other people are doing to navigate through catalog records and if there is an easy solution I'm not thinking of. 

> I think this is probably just incompatible with the current UI, but I am very open to clever ideas.
Shoot! Other ideas on how to achieve a similar function would be greatly appreciated!

**Comment by DerekSikes** [comment]
I just open each in a new tab until I have enough tabs open that span my browser window. When done with each I return to the list and open more, etc.

**Comment by genevieve-anderegg** [comment]
Ah and then just Ctrl+Tab through them, that makes sense

**Comment by Jegelewicz** [comment]
Some sort of "open all in new tabs" button?

**Comment by genevieve-anderegg** [comment]
Would have to be able to adjust that to the amount of records you want to open at a time. You could have a list of 5000 catalog records, but don't want to open all of those at once in different tabs and create a mess.

**Comment by wellerjes** [comment]
> I'm sure this is a duplicate, but I can't find the other....

https://github.com/ArctosDB/arctos/issues/5660

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/5660
