### ISSUE TITLE
add "credit line" attribute to all collections

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#6347]
**Is your feature request related to a problem? Please describe.**
The credit line attribute is currently only applicable for Art and Teach. I am finding documentation in accession records for other collections that also request a credit line.

**Describe what you're trying to accomplish** 
Consistently document credit within attributes.

**Describe the solution you'd like**
Add the ["credit line" attribute](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type) to all collections.

**Describe alternatives you've considered**
Add the credit to remarks or another field

**Additional context**
n/a

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.

**Comment by Jegelewicz** [comment]
No objection from me - seems like something useful for all collections.

**Comment by Jegelewicz** [comment]
@ArctosDB/arctos-code-table-administrators

**Comment by dustymc** [comment]
I'm not sure all collection types are even used, some could exist because someone didn't want to share attributes, etc. It's no problem to fulfill specific requests (and there's an expedited path to handling this situation in the [code table template](https://github.com/ArctosDB/arctos/issues/new?assignees=&labels=Function-CodeTables&projects=&template=code-table-request.md&title=Code+Table+Request+-+)), but I think there's no reason to force any attribute on anyone who doesn't request it.

Please revise the request for specific collection codes.

**Comment by AJLinn** [comment]
> Please revise the request for specific collection codes.

Please make available for EH.

**Comment by mkoo** [comment]
> but I think there's no reason to force any attribute on anyone who doesn't request it.
> 

well, it can be ignored!

> Please revise the request for specific collection codes.

at any rate, ARCH will need this!

**Comment by dustymc** [comment]
>can be ignored!

Maybe, definitely no tech-thing with a clear answer, I'm OK with being wrong here.

>EH

Done

>ARCH

https://arctos.database.museum/collection/MVZ:Arch says EH, so done.

**Comment by Jegelewicz** [comment]
I am calling this done. Thanks everyone!

**Comment by wellerjes** [comment]
Can you add it to Herb as well? Thanks!
