### ISSUE TITLE
Add "Report bad data" to Agent Record

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#6361]
Add this button to Agent Record page:
![image](https://github.com/ArctosDB/arctos/assets/12507297/829d9849-7a72-4fc8-839c-5cbfd257d457)

**Comment by AJLinn** [comment]
I just wonder if we know there’s bad data, since Agents is shared table, what’s stopping an operator from just updating the record and making curatorial remarks re: what we did? 

Or are you proposing this be placed on the public view page? If so, I’d say to be sure to note that on the issue and then I’d definitely say yes, it’s a necessary and useful button to add!

**Comment by dustymc** [comment]
Yes, https://arctos.database.museum/agent/21334341 is public.
