### ISSUE TITLE
Requesting feedback on Arctos bulkloader geography and locality data organization

### ISSUE THREAD

**Issue by kmkocot** [ArctosDB/arctos#6377]
Hello,

During our recent Antarctic research cruise (www.icyinverts.com) we used a custom Excel spreadsheet with controlled vocabulary look-up tables to enter specimen data (here it is in case anyone is interested: [https://alabama.box.com/s/p453k7eugmotsnz2k0ibhc00nepa642x](https://alabama.box.com/s/p453k7eugmotsnz2k0ibhc00nepa642x)). After the cruise, I massaged these data into the correct format to bulkload records into Arctos ([https://alabama.box.com/s/0z5t00ivzco4f0kdtrd6i1vww3ysxi4q](https://alabama.box.com/s/0z5t00ivzco4f0kdtrd6i1vww3ysxi4q) - part information is still in there following our modified syntax and needs to be organized correctly and column headers will need to be renamed before bulkloading so ignore that). 

Before I bulkload these records I was wondering if I could ask the experts to take a peek at the file in the third link above and note how I have treated the following fields:
locality_id
locality_name
spec_locality
collecting_event_id	collecting_event_name
locality_remarks
verbatim_locality

They are columns R-V in the spreadsheet. I'm still a bit confused on the different locality and collecting event fields.

Any other feedback about how we are doing things are very welcome.

Thanks!!
Kevin

**Comment by mkoo** [comment]
I like how organized this is-- either @Jegelewicz  or I will try to review ASAP!

**Comment by Jegelewicz** [comment]
@kmkocot I am on the road, but I'll try to catch everything!

You don't need a minus on the degrees when using degrees decimal minutes if it is South or West. You are already telling Arctos that with the dec_lat_dir and dec_long_dir.

Most of what you have in locality remarks feels like habitat (Soft sediment) or collecting method (Plankton removed from pre-filters on ship's water sampling system.) to me. But it also seems like you know what you want in those fields, so if that all feels right for you, then leave it as is.

Locality and event ids are assigned by Arctos - you don't need those column headers.

Locality and event names are up to you! You could create them in advance and use the names to assign locality and/or event + locality to a record - which means you don't have to enter all the other locality and/or event information, but it seems like you don't need to do that and so you can also leave those columns blank.

Your depth units all need to match the [code table](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlength_units#m) and should be "m" instead of "meters"

I only made a quick review - let me know if any of the above is confusing! I love how you have made your own field data collection protocol!!!

**Comment by kmkocot** [comment]
Thank you so much, @Jegelewicz and @mkoo! I made the suggested edits and some more tweaks and as of today records and parts are uploaded and my image metadata bulkloader is ready to go once I get the files up to TACC. 

Thanks again!
Kevin
