### ISSUE TITLE
Feature Request - preventing incomplete taxonomic classifications

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#6388]
**Is your feature request related to a problem? Please describe.**
I am frustrated when I try to pull information on a certain classification level and do not get all of the applicable records because the Arctos Classification Source is incomplete.

**Describe what you're trying to accomplish** 
Having to check for NULL values classifications and fill them in in order to get accurate results.

**Describe the solution you'd like**
Going forward: When cloning a classification from GlobalNames into an Arctos Classification Source, make some of the fields required, including classification levels and metadata.

**Describe alternatives you've considered**
Search and update taxonomic records manually.

**Additional context**
n/a

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.

**Comment by Jegelewicz** [comment]
@wellerjes I can only sigh - but this is nearly impossible - many taxonomies (minerals, paleo, cultural) DO NOT have ranks and even some biological classifications purposely end up without some rank or another. Also, the fact that we are cloning in things from external sources that are already missing ranks in the external source indicates that enforcing some ranks is perhaps not a best practice.

To some degree, we should not be responsible for this! Most of us are not taxonomists and even those who are taxonomists are not taxonomic experts in the entire tree of life! We cannot be held responsible for maintaining a perfect set of taxonomy for every possible thing - nobody has been successful at doing that, otherwise we would have a global taxonomy of life that everyone would just use.

We do have tools for finding classifications with missing ranks in a given source. Let me know how I can help to get you where you want to be.

**Comment by Jegelewicz** [comment]
@wellerjes there isn't a technical solution to this issue at the moment. The best answer is to find an awesome classification source and add it to Arctos, then maintain it as necessary. I am closing this - but let me know if you would like to meet up to talk through the tools I mentioned above.
