### ISSUE TITLE
Feature Request - Make error message for container exceeds load capacity more user friendly

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#6447]
From the Working Group/Issues meeting 6/22/2023:

> Error message -> more user friendly if get a banner warning that says ->”you are over capacity”. Just take the first part of the ERROR_MESSAGE to pop up into a banner

**Describe what you're trying to accomplish** 
Help people understand why they are getting an error message here.

**Describe the solution you'd like**
A banner message with a simple phrase that clearly explains the error.

**Additional context**
Current error message is:
<html>
<body>

ERROR_ID | B89A47BA-47E4-4D1D-9E5CE9BB5B79D81F
-- | --
ERROR_TYPE | SQL
ERROR_MESSAGE | ERROR: Weight capacity of container 22384011 exceeded. Where: PL/pgSQL function trigger_fct_trg_container_weight_control() line 60 at RAISE
ERROR_DETAIL |  
ERROR_SQL | update container set parent_container_id=22392892, label='NMMNH:Paleo:43685 long bone', description=null, container_remarks=null, barcode=null, width=null, height=null, length=null, number_rows=null, number_columns=null, orientation=null, positions_hold_container_type=null, institution_acronym='NMMNHS', container_type='collection object', weight=105, weight_units='lb', weight_capacity=null, weight_capacity_units=null, last_update_tool='EditContainer.cfm' where container_id=20562819

</body>
</html>

**Comment by dustymc** [comment]
I don't think a piecemeal approach to error handling (eg, do something special for some particular error) is supportable (or usable - consistency is important).

All of the stack does support the mechanism that's used as the core of most error handling systems, I don't think there would be technical barriers to expanding this into some sort of comprehensive error handling system.

**Comment by Jegelewicz** [comment]
Possible to start by just putting the ERROR_MESSAGE at the top?

**Comment by mkoo** [comment]
Agree that we can rework all errors but this is the use case since technically when you exceed the container capacity, it's not a database ERROR, it's a warning! (and the db is working correctly)

At any event, the AWG proposed: when someone gets an error, show at the top the ERROR_MESSAGE without the field name, just the value. Maybe in div with some background color? The table can still be viewed below but perhaps with a message like "The following information may be useful and may be requested to help troubleshoot"  and then display the table.

**Comment by dustymc** [comment]
Generalized to https://github.com/ArctosDB/arctos/issues/8049
