### ISSUE TITLE
Feature Request - Ability to search multiple agents in issuedBy

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6459]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**

There are three identifiers issued by Albuquerque Biopark Zoo, which means 3 issued by agents - I want to find all records with identifiers issued by Albuquerque Biopark Zoo. Currently I can only select one at a time.

**Describe what you're trying to accomplish** 
An clear and concise overview of the goals; why are you asking for this?

Find all records with identifiers issued by Albuquerque Biopark Zoo

**Describe the solution you'd like**
How might we accomplish your goals?

Allow wildcards in Issued By OR allow me to select more than one issued by

**Describe alternatives you've considered**

Search all three and combine the results outside of Arctos

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.

**Comment by Jegelewicz** [comment]
Alternatively, search all issued by that are "divisions" of some agent?

**Comment by dustymc** [comment]
>divisions

Yes, that's clearly more powerful, but I think it needs some dedicated discussion (probably involving updating some agent relationship definitions, and being written such that it can be used elsewhere, and then tested because I'm not sure what sort of CPU that would require).

A "works now" hack: just make sure the names share substrings eg


* Albuquerque Biopark Zoo: some program
* Albuquerque Biopark Zoo: some other program

can both be found in one search.

(And please clarify the priority tag? This is clearly something that can be done in one model and cannot be done in the other yet we're stuck in the middle.)

**Comment by Jegelewicz** [comment]
> clarify the priority tag

This is requested in order to help get us unstuck!

However, I didn't know that I could use any old thing and that I can already do what I initially requested.

I'm gonna leave this open with wishlist priority because I think the more powerful option deserves a chance when we have time (HAHAHAHA - like that's ever gonna happen...).

**Comment by dustymc** [comment]
>more powerful option 

Yes, but also more complex - eg I doubt there's one approach that meets all needs, I think this would *somehow* involve the user specifying "US NPS and all divisions thereof" or "Denali Park + Denali Preserve but not Denali State park" or "person plus students, but not parents" or.... 

https://github.com/ArctosDB/arctos/discussions/6524 might be an alternative.

**Comment by dustymc** [comment]
Tabling pending a compelling use case.
