### ISSUE TITLE
Taxonomy confusion with Siphonaptera insect order and Siphonaptera or Siphonaperta foraminifera genus?

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#6466]
Do we have any foraminifera currently cataloged in Arctos? There is major confusion between trying to use Siphonaptera to catalog the order of fleas in Arctos for a current grant, and the existence of some sort of synonomy or mispelling with a genus of foramifera - e.g. Siphonaptera agglutinans or Siphonaperta agglutinans.
Is this coming from WoRMS? 
If possible to fix, that would solve a lot of current data entry problems. . . .

**Comment by dustymc** [comment]
> Is this coming from WoRMS?

Are you cataloging in a collection that prefers WoRMS?

I think the answer will be in https://handbook.arctosdb.org/documentation/taxonomy.html but if you can provide some more information (eg links) here we can clarify.

**Comment by Jegelewicz** [comment]
Both of these are in Taxon Names

[Siphonaperta agglutinans](https://arctos.database.museum/name/Siphonaperta%20agglutinans)
[Siphonaptera agglutinans](https://arctos.database.museum/name/Siphonaptera%20agglutinans)

[Siphonaperta agglutinans](https://arctos.database.museum/name/Siphonaperta%20agglutinans)
is a synonym of [Quinqueloculina agglutinans](https://arctos.database.museum/name/Quinqueloculina%20agglutinans) and yes, it is coming from WoRMS

Nobody is using this term, but because it is coming from WoRMS, I think we need to keep it. @dustymc can we quarantine it? Will that mess up anything with the WoRMS refreshes?

**Comment by dustymc** [comment]
Oh I see, maybe - entry people are picking the wrong thing, and the wrong thing might be a typo (Siphonaperta is real, Siphonaperta agglutinans maybe not so much)? 

There are a LOT of things that look similar in Arctos, seems like a real problem that needs a real solution (maybe more information in taxa picks or ??).

Not 100% sure about the refresh, but I think it would still work.

**Comment by Jegelewicz** [comment]
Well, let's try it out...

I will quarantine [Siphonaperta agglutinans](https://arctos.database.museum/name/Siphonaperta%20agglutinans).

**Comment by Jegelewicz** [comment]
@campmlc this should mean that your data entry team won't be able to select [Siphonaperta agglutinans](https://arctos.database.museum/name/Siphonaperta%20agglutinans). Close this issue if that solves the problem.

**Comment by campmlc** [comment]
Yes, I think that is the problem - they are picking the wrong thing, and
that wrong thing has a misspelling.

**Comment by campmlc** [comment]
So it looks like the foraminferan term is Siphonaperta, in the family Siphonapertidae, although this is an old name that has been changed. So we can unquarantine that, and then flag any foraminferan taxa that are listed as Siphonaptera (note spelling change) as invalid/unaccepted/erroneous?
https://es.wikipedia.org/wiki/Siphonaperta

**Comment by Jegelewicz** [comment]
@campmlc I'm not 100% sure what you are asking.

> foraminferan taxa that are listed as Siphonaptera

I don't think there are any, but that is hard to know. Anyone can make a bad pick from the taxonomy list if they aren't paying attention. The only name I quarantined was [Siphonaperta agglutinans](https://arctos.database.museum/name/Siphonaperta%20agglutinans) since that was in the original issue and it is already marked by WoRMS as a synonym of [Quinqueloculina agglutinans](https://arctos.database.museum/name/Quinqueloculina%20agglutinans).

There are a lot of Siphonaperta names

[Siphonaperta](https://arctos.database.museum/name/Siphonaperta)
[Siphonaperta agglutinans](https://arctos.database.museum/name/Siphonaperta%20agglutinans)
[Siphonaperta agglutinata](https://arctos.database.museum/name/Siphonaperta%20agglutinata)
[Siphonaperta ammophila](https://arctos.database.museum/name/Siphonaperta%20ammophila)
[Siphonaperta arenata](https://arctos.database.museum/name/Siphonaperta%20arenata)
[Siphonaperta aspera](https://arctos.database.museum/name/Siphonaperta%20aspera)
[Siphonaperta bhallai](https://arctos.database.museum/name/Siphonaperta%20bhallai)
[Siphonaperta crassa](https://arctos.database.museum/name/Siphonaperta%20crassa)
[Siphonaperta crassatina](https://arctos.database.museum/name/Siphonaperta%20crassatina)
[Siphonaperta dilatata](https://arctos.database.museum/name/Siphonaperta%20dilatata)
[Siphonaperta distorqueata](https://arctos.database.museum/name/Siphonaperta%20distorqueata)
[Siphonaperta enoplostoma](https://arctos.database.museum/name/Siphonaperta%20enoplostoma)
[Siphonaperta hallockae](https://arctos.database.museum/name/Siphonaperta%20hallockae)
[Siphonaperta hallocki](https://arctos.database.museum/name/Siphonaperta%20hallocki)
[Siphonaperta hauerina](https://arctos.database.museum/name/Siphonaperta%20hauerina)
[Siphonaperta horrida](https://arctos.database.museum/name/Siphonaperta%20horrida)
[Siphonaperta inculta](https://arctos.database.museum/name/Siphonaperta%20inculta)
[Siphonaperta irregularis](https://arctos.database.museum/name/Siphonaperta%20irregularis)
[Siphonaperta leonensis](https://arctos.database.museum/name/Siphonaperta%20leonensis)
[Siphonaperta longidentata](https://arctos.database.museum/name/Siphonaperta%20longidentata)
[Siphonaperta lucida](https://arctos.database.museum/name/Siphonaperta%20lucida)
[Siphonaperta macbeathi](https://arctos.database.museum/name/Siphonaperta%20macbeathi)
[Siphonaperta osinclinatum](https://arctos.database.museum/name/Siphonaperta%20osinclinatum)
[Siphonaperta ovalis](https://arctos.database.museum/name/Siphonaperta%20ovalis)
[Siphonaperta petrophila](https://arctos.database.museum/name/Siphonaperta%20petrophila)
[Siphonaperta pittensis](https://arctos.database.museum/name/Siphonaperta%20pittensis)
[Siphonaperta prominentis](https://arctos.database.museum/name/Siphonaperta%20prominentis)
[Siphonaperta quadrata](https://arctos.database.museum/name/Siphonaperta%20quadrata)
[Siphonaperta sabulosa](https://arctos.database.museum/name/Siphonaperta%20sabulosa)
[Siphonaperta subagglutinata](https://arctos.database.museum/name/Siphonaperta%20subagglutinata)
[Siphonaperta subrugosa](https://arctos.database.museum/name/Siphonaperta%20subrugosa)
[Siphonaperta vellai](https://arctos.database.museum/name/Siphonaperta%20vellai)
[Siphonaperta wiesneri](https://arctos.database.museum/name/Siphonaperta%20wiesneri)

**Comment by campmlc** [comment]
Siphonaperta are all ok, as they are older names of real taxa. Siphonaptera
is a misspelling of these genus names. But Siphonaptera is a valid name for
an order of insects. Not sure what options exist to help distinguish for
data entry when students type Siphonaptera for fleas, as they should. I
need them to select the flea order, not the misspelled foram genus.

**Comment by dustymc** [comment]
> Siphonaptera is a misspelling 

I don't believe that is true. The *one* that @Jegelewicz quarantined seems to be a misspelling/mix-n-match mess. The rest, as far as I can tell, are legitimate. See eg https://www.researchgate.net/figure/1-Siphonaperta-irregularis-dOrbigny-side-view-Kusadasi-6-2-Cycloforina-contorta_fig8_265600739

> sure what options exist to help distinguish

https://github.com/ArctosDB/arctos/issues/6466#issuecomment-1611430747

**Comment by campmlc** [comment]
Yes, Siphona"perta" is correct for forams, including that species. For
forams, Siphon"aptera" is an erroneous term. But Siphonaptera is the
correct name for the insect order.

**Comment by dustymc** [comment]
>erroneous term

Oh, thanks. Maybe that is erroneous, but it looks like it might be a "validly published" erroneous term eg https://www.mindat.org/taxon-7421814.html, and eg GBIF recognizes it - https://arctos.database.museum/name/Siphonaptera#GBIFBackboneTaxonomy. I suppose I don't have any real opinions on how to handle this (as long as nobody's suggesting deletion, these are clearly *important*, however right or wrong they might be), at least until someone shows up with better info (or a type specimen) - @ArctosDB/taxonomy thoughts?

**Comment by campmlc** [comment]
Do we quarantine the misspellings so they don't get perpetuated? But we'd
have to do that at species level here? Or can we quarantine based on name +
classification?

**Comment by campmlc** [comment]
That GBIF link is for the flea order, which is valid, and what I'm trying
to get the students to pick.

**Comment by Jegelewicz** [comment]
I still don't understand the problem. It doesn't matter what we do, someone could mistake Siphonaperta for Siphonaptera. And if someone with forams uses Siphonaptera, I expect they will eventually find out that they have selected something that doesn't pertain to them.

If your students are picking Siphonaptera and your collection is preferring TPT (via Arctos) you will get the flea genus.

**Comment by dustymc** [comment]
>That GBIF link is for the flea order
<img width="204" alt="Screenshot 2023-06-29 at 8 39 59 AM" src="https://github.com/ArctosDB/arctos/assets/5720791/26952b88-5afd-424a-a2ed-9cd5ca8229df">

>what I'm trying to get the students to pick.

There's only one monomial, tell them to pick it, this doesn't seem like an obstacle??

**Comment by campmlc** [comment]
It's obviously a mess. What we need is to be able to avoid contributing to
it by students who can't tell the difference. Maybe allow collections to
prefer or encumber certain names + classifications? Or put scary red boxes
around ones you don't want students to use?

**Comment by Jegelewicz** [comment]
Is the issue that students are picking Siphonaperta instead of Siphonaptera? If that is the problem, there is nothing we can do! Both are names that could be used in identifications.

**Comment by Jegelewicz** [comment]
Well - look at that! The TPT taxonomy is incorrect! Time to let them know that...

**Comment by Jegelewicz** [comment]
![image](https://github.com/ArctosDB/arctos/assets/5725767/4842bd49-4b46-4510-bb53-049b4e35bc58)

**Comment by Jegelewicz** [comment]
Closing - seems like this has been resolved?
