### ISSUE TITLE
Agent Merge Question

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#6530]
I was looking through notifications and saw that agent Juan Sebastián Torres Alba was merged to unknown:
![image](https://github.com/ArctosDB/arctos/assets/11336485/a1b3c3d1-a0dd-45df-a4fc-8feee62952bf)

Being a name that seems fairly unique, I looked him up and found him online. I am now trying to locate him as a verbatim agent in Arctos through the Manage Agent search, as well as a basic catalog record search (while logged out) in either Agents or the Attribute search fields and get nothing. I also tried removing the diacritic without success.

Why can't I find him? 

![image](https://github.com/ArctosDB/arctos/assets/11336485/98c35862-09cd-4840-98cc-268bf3111729)

**Comment by dustymc** [comment]
>Why can't I find him?

Probably didn't do anything that would get 'verbatimized.'

**Comment by Jegelewicz** [comment]
See https://github.com/ArctosDB/arctos/issues/6476

**Comment by ebraker** [comment]
confused...I assumed everything getting changed to unknown would get pushed to verbatim agent. So are we actually purging data?

**Comment by Jegelewicz** [comment]
This was NOT a verbatim agent (it was originally created as [J. S. Torres](https://arctos.database.museum/agents.cfm?agent_id=21348959) but I changed it to the name in the "possibly" comment, because either it is or it isn't Juan Sebatian Torres Alba. Phyllis was not comfortable making the assump[tion, so she manually added J. S. Torres to her record and this agent (which has never actually been used) has been set to merge with unknown, because probably nobody will ever use it.

**Comment by Jegelewicz** [comment]
So yes, in a way we are purging unused data.

**Comment by ebraker** [comment]
Gotcha. Apologies - I had assumed that Juan Sebastián Torres Alba was connected to UCM records since I received the notification, but I guess it goes out to everyone. Was just trying to track info down to improve the records!

**Comment by dustymc** [comment]
>received the notification

Agent 'unknown' was involved, so near everyone would have received the notification.
