### ISSUE TITLE
Placement of Collecting Event Bulkload in Tools Directory

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6537]
[Bulkload Collecting Events](https://arctos.database.museum/tools/BulkloadCollectingEvent.cfm)
[Bulkload Event Attributes](https://arctos.database.museum/tools/BulkloadEventAttrs.cfm)

Are located in the Data Entry Tile on the Tools Directory. I think they would be better placed in the Places & Events tile.

Any opposition to them being moved?

**Comment by mkoo** [comment]
We had discussed this since they were originally in the Place and Events tile (I recall)

Others wanted all data entry/ bulk load tools together.... But of course we have a bunch of locality bulkeditng and loading tools under Places and Events. (I know I can talk myself into both)

 I'd prefer to just get used to one spot! Any opposed to this move?!

**Comment by Jegelewicz** [comment]
All I know is that I needed to show someone bulkload collecting events and it took me forever to figure out where it was (before I wised up and splat-F).
