### ISSUE TITLE
Agent Merge Request - R. Leiner 

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#6563]
Use this template when you discover two agents that you believe represent the same person or organization.

**Agent that should remain after the merge**

unknown

**Agent that will no longer remain after the merge**

https://arctos.database.museum/agent/21349050

**Reason for merge**

Zeroish-information agents should not exist.

Please add this issue to the Agents Project

@ArctosDB/agents-committee

**Comment by Jegelewicz** [comment]
This agent was created by [Jayce Williamson](https://arctos.database.museum/agents.cfm?agent_id=21263033)

@DerekSikes do you know this person? If so, can you help us make Agents better? If not, do you know who might?

They need a little instruction on agent creation. Surely if they know R. Leiner was alive today they have some more substantial information so that we know who R. Leiner actually is? The Agents committee is trying really hard to make agents useful and this kind of agent is not. I am happy to meet up and provide more information if needed!

Thanks!

**Comment by Jegelewicz** [comment]
@ArctosDB/agents-committee I don't know what to do here and the list of these kinds of agents just seems to be growing. I am beginning to think that agents need to be treated like a code table and that only a few people should have access to add. Could we separate adding from editing, so that anyone could make an agent better, but only "Agent Admins" could add an agent?

**Comment by ewommack** [comment]
> but only "Agent Admins" could add an agent?

That might create a huge work load for the "Agent Admins" team. When I'm accessioning for a year, I may have over 10 names to add at once. I imagine the same might be true for people working to add publications, projects, loans, permits, etc. 

Perhaps more stringent training? Like with localities?

**Comment by dustymc** [comment]
>10 names to add at once

I'm confident that I can do that (and a lot more) in less time than we've spent on this one issue! (Which exists only because something in an error log caught my eye - there may be YEARS worth of future cleanup sneaking by.)

I agree with @Jegelewicz here - if we want data of a quality capable of treating people like they want to be treated, providing proper attribution, etc., etc., then we need to see agents more like an authority and less like some sort of specimen-supporting metadata. I'm not sure what the best path to that is, but I've got some pretty clear ideas about what doesn't lead there and I'm willing to try something that might go where I think we all want to be.

**Comment by Jegelewicz** [comment]
> 10 names to add at once

If you provide some good metadata about those names (not just "alive on" or "associated with"), then it is easy-peasy to add things. I am currently working on a list of over 800 agents and determining if they are different from all of the initial plus last name, plus no good metatada agents is next to impossible. This means I get frustrated and we have duplicate agents or more low-quality agents. As long as R. Leiner can exist in agents then we will just grow the mess.

**Comment by ewommack** [comment]
Yeah but instead of me sitting down with a stack of Accession sheets or loan information in front of the computer with my student and just chugging away, it becomes:

- Is the Agent Team available?
- File an issue with the Agents I want loaded?
- Wait a day to make sure they are there?
- Come back next week and try again to get the rest of the info added
Adding a code table value at the moment can happen really fast, but it can also take months. Do you want this responsibility? Just because you can do, doesn't mean that is the best way or the best use of your time. There were just notices about how back-uped the Code Table Committee and issues were.

**Comment by mkoo** [comment]
I see huge workflow issues with this emphasis solely on data quality. We cannot allow data entry to stall because of current lack of data on agents. I think we need to balance the need for progress and management with data quality and not have the latter prevent the latter. I think we need to come up with automated tools for data quality reporting so we have 'R. Leiner' get cleaned up but not prevent people from getting records into Arctos. Arctos is a data management solution so get the data in and manage. Could we have new agents with no bios or other information just sit as verbatim until they are better known? And then make converting to full profiled agent easier? 
For example, I have a lot of legacy agents we are cleaning up through our work in the Archives but the original data entry was decades ago and valuable. So some messes are needed in order to cleanup and make better

**Comment by dustymc** [comment]
>Could we have new agents with no bios or other information just sit as verbatim 

Yes, and I think that's what should have been done here (and in most similar situations). It saves work for everyone, doesn't hold up entry, and carries all the information most agents have. (And this one looks like a 'give it whatever it takes to get through the form' situation to me - if that's true then negative value has been added.) 

The ask is only to somehow not create agents unless there's some need to create agents - some data which can't be derived or carried by a verbatim exists.

**Comment by lin-fred** [comment]
> Could we have new agents with no bios or other information just sit as verbatim until they are better known? And then make converting to full profiled agent easier?

This is supposed to be the current workflow.

**Comment by Jegelewicz** [comment]
I suggest we close this. There is no way for us to clean it up.

**Comment by AJLinn** [comment]
I think this is "Roseann Leiner" as listed on pages 23, 24, 27, and has a photo, job title, affiliation, and contact info on p. 58 in this publication: 
https://scholarworks.alaska.edu/bitstream/handle/11122/2231/aes2005.pdf?sequence=1&isAllowed=y
@DerekSikes Jayce entered this agent. Do you think this is the correct R. Leiner?


Lots of other publications with this person listed.

**Comment by dustymc** [comment]
>block people's progress in cataloging

I don't think that's even possible - we couldn't do it if we tried as long as verbatim exists!

>better training

agree

>no way for us to clean it up

Then we need a policy - letting someone make messes that can't be fixed absolutely will block us from our goals (eg, of no longer requiring unique preferred names).

**Comment by Jegelewicz** [comment]
> our goals (eg, of no longer requiring unique preferred names)

I am not sure that is an actual community goal. I think it is a goal for some of us, but not for everyone, yet. It is interesting to me that taxonomy (names for not-human stuff) seems more sacred than people's names, but I think that is where we are. The only path to an agent authority is to limit access to the addition of agents as we do for other "authorities" in Arctos (where we still don't do a great job of creating good terms and sometimes we can never agree, leaving data hanging somewhere), but the community is not willing to do that. An expectation of "more training" will never be met - we cannot control every operator with access to manage_agents and how they train the operators they pass that ability on to. As long as I can reasonably make up information in order to create an agent (alive today, associated with my collection) this will never be solved.

Given that, discussions at the Agent Committee Meeting this week, and discussions with @ebraker and @mkoo I think we need to drop this. Agents have been a messy pile since the table was created and we have managed to get work done. We have created a path for "verbatim agents" but it really only works for people in the collector roles. If we don't provide a path for verbatim agent everywhere that agents might be used, we can fully expect continued creation of agents like this one. As it is we have a partial solution and it isn't working. At this point, I would prefer that we just let agents like ABC exist so that I can just add agents for incoming collections and move on. There is a belief in the community that "we will clean it up" (although I definitely think that is wishful thinking) and maybe we will, but having two ways of recording something is just making things more difficult.

In short, I think we need to be OK with the fact that our Agent table is NOT an authority, it is a way to standardize name spellings for MOST people and organizations. For some of these it becomes an authority, when we can say something meaningful about the agent. Will some agent profiles include the actions of two or more people or organizations? Yep, but eventually (or never) someone will figure that out and split things. Will some people or organizations be represented by two or more agent profiles? Yep, but eventually (or never) someone will figure that out and merge them. Even with the verbatim agent attribute, both of these scenarios continue to happen.

Based upon recent discussions, I think this is what the community actually wants. We are all interested in data quality, but are overwhelmed with the quantity of data we are tasked with managing and at this moment in time, ease of use trumps quality.

I see this across all of the places we are attempting to create "research-grade" data and not really accomplishing our goal because it is just too time-consuming to create that data in the granular fashion that normalization requires. We either need technology to do some of this for us (see #6623 ) or we need to let go of some of our expectations (see #6622 ).

Apologies for the rant - but this has really been weighing on me for months and I think we need to consider it and how to make things work for everyone.

**Comment by dustymc** [comment]
>managed to get work done

That's not the issue (or not all of it): Nobody should be OK with not receiving proper attribution, nor should anybody be comfortable with not _giving_ proper attribution. That (along with a complete inability to call people what they'd like to be called) is the inevitable outcome of our current approach.

>interested in data quality

Maybe the current model isn't understood?? That's available, and there's a path for instantly "creating agents" - I'm having a hard time seeing whatever problems seem to be preventing adopting functionally useful data standards.

>technology

I can't employ that without it being backed by procedures.
