### ISSUE TITLE
Feature Request - add Curatorial Remark (internal) in the agent bulkloader

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6572]
**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_

I have approximately 800 agents from an incoming collection to load some of which include ~~more than the 3 addresses currently allowed in the agents bulkloader. I also have some private remarks for just about all of them to add in~~ Curatorial Remark (internal), which is ~~also~~ not in the agent bulkload tool. I don't want to be making manual additions....

**Describe what you're trying to accomplish** 
_An clear and concise overview of the goals; why are you asking for this?_

Load all the available information about an agent at one time.

**Describe the solution you'd like**
_How might we accomplish your goals?_

~~For this bunch I need at least 6 addresses. Can we add three more to the tool?~~

~~Also need to~~ add Curatorial Remark (internal) to the tool.

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

Use the tool to enter what I can, then manually edit to get the rest. This will end up being about 700 manual edits.

Ask Dusty to add stuff to the agents I loaded

Ask Dusty to load everything

**Additional context**
_Add any other context or screenshots about the feature request here._

If we want people to create richly annotated agents, let's make that easy?

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.

Adding milestone direct implementation because this is all additive and can only make agents better....

**Comment by Jegelewicz** [comment]
See also https://github.com/ArctosDB/data-migration/issues/1512

**Comment by dustymc** [comment]
>private remarks 

That part's easy.

>6

I hate denormalization. If we do this, the next batch will have 8. BUT, agents are generally the most painful part of a migration, surely nobody actually has >6 addresses in any not-Arctos system, etc. - right?! - tentatively going with the suggested direct implementation.

**Comment by Jegelewicz** [comment]
> I hate denormalization.

How is adding addresses denormalization? Seriously, I don't get it....

**Comment by dustymc** [comment]
There's no limit on the number of (child) any (parent) can carry. We have a bunch of

parent-child-child

things (including this). Those are denormalized in that they allow only 2 (or, some finite number of) child records. Having two loaders

parent

and 

parent_key-child

allows handling any number of child records via two loads.

Here, we can add some addresses to the already-address-having loader on the theory that there are practical limits to that sort of thing (what's suggested ^^ up there) and that agents are always painful (because they are!) and simplicity carries extra weight, OR we could add a dedicated address loader (I think there's an issue somewhere) which would deal with....


parent_key-child1
parent_key-child2
...
parent_key-child36789235

... absolutely anything, including the stuff we're not capable of predicting today.

The data suggest clear answers in lots of cases, I don't think this is one of them - I'm pretty happy to roll in either of those directions. Seems this is holding something up so you pick and I'll go....

One unique concern here is that the addresses are used as a proxy for agent data quality, so we probably can't completely denormalize without finding a better measure of that. That might be a vote for going with the simple/flat/denormalized approach.

**Comment by Jegelewicz** [comment]
Ah-ha. I see. I would be totally fine with loading stuff using the current loader, then adding addresses with an address loader but we don't have a "load more stuff to an Agent" tool. Give me that, and I can work with it.

**Comment by Jegelewicz** [comment]
OK - changed this request to just add the curatorial remark - if I can have that, I can get through these. Thanks!

**Comment by dustymc** [comment]
I think I'd already added some extras (partially with the idea that one of the extra THINGs might prevent a duplicate - and https://github.com/ArctosDB/arctos/issues/6198 will be made to consider them) when test melted on me - I'll do something when I can again....

**Comment by Jegelewicz** [comment]
OK - just keep me posted. I have to keep things going though or OGL will never get their data in. If I load their agents, then provide a csv with preferred_name and curatorial_remark could you add those in?

**Comment by dustymc** [comment]
Delay if you can, please - I think I'm a ~day from having something useful once I get my tools back. If that's absolutely impossible then do what you must and we'll figure it out.

**Comment by Jegelewicz** [comment]
I am adding stuff manually right now - it is a mental break and at least I feel like something is getting done.
