### ISSUE TITLE
can't add pub

### ISSUE THREAD

**Issue by cjconroy** [ArctosDB/arctos#6574]
I am trying to add an online publication. There is a DOI, but Arctos couldn't find it. Tried saving anyway and got this error. Glitch, or did I do something wrong?

<br class="Apple-interchange-newline">

ERROR_ID | EE45FC78-CC70-4B91-9EB6F2AF077D7F04
-- | --
ERROR_TYPE | SQL
ERROR_MESSAGE | ERROR: new row for relation "publication" violates check constraint "ck_publication_doi" Detail: Failing row contains (10011950, 2023, other, null, null, 1, Francis, C. M.; N. B. Simmons, V. Van Cakenberghe, N. S. Upham, ..., Francis et al. 2023, 10.5281/zenodo.7696845, null, null).
ERROR_DETAIL |  
ERROR_SQL | insert into publication ( publication_id, published_year, publication_type, publication_loc, full_citation, short_citation, publication_remarks, is_peer_reviewed_fg, doi, datacite_doi, pmid ) values ( 10011950, 2023, 'other', null, 'Francis, C. M.; N. B. Simmons, V. Van Cakenberghe, N. S. Upham, and C. Burgin, on behalf of the Global Bat Taxonomy Working Group of the IUCN SSC Bat Specialist Group. 2023. On the taxonomy of Lasiurus (v1.0). Zenodo. https://doi.org/10.5281/zenodo.7696845', 'Francis et al. 2023', null, 1, '10.5281/zenodo.7696845', null, null )

</div>

**Comment by dustymc** [comment]
Use ``https://doi.org/10.5281/zenodo.7696845`` instead of ``10.5281/zenodo.7696845``

**Comment by cjconroy** [comment]
Tried that. See fail attached. The instructions say to use only the guts of the DOI, not the http etc. prefix. 
<img width="1109" alt="Screenshot 2023-07-28 at 9 36 19 AM" src="https://github.com/ArctosDB/arctos/assets/5749672/6401f920-7327-4827-860e-968cc5ee0ebe">

**Comment by dustymc** [comment]
>instructions

Were wrong, I stripped that out, see https://github.com/ArctosDB/arctos/issues/5726

''https://doi.org/10.1111/jbi.12995" gets stored and should work anywhere, but - for CrossRef DOIs, anyway - Arctos will figure it out from most any format - "10.1111/jbi.12995" and "DOI:10.1111/jbi.12995" and several more will work.

>fail

This behavior needs clarified somehow, I'm not sure how, someone HELP!

The crossref button will do what you see above, because that's a datacite DOI. Crossref didn't issue it and doesn't have data for it, you're going to have to type the publication bits in manually.

This bit still works:

<img width="880" alt="Screenshot 2023-07-28 at 12 19 50" src="https://github.com/ArctosDB/arctos/assets/5720791/5a35a70b-8a24-43a6-918b-2300bb07d6b6">

https://arctos-test.tacc.utexas.edu/publication/10011777

I think that's defensible - the DOI is still a good publication identifier, even if it doesn't know how to play in the CrossRef Ecosystem - but I'm totally open to the idea that non-Crossref DOIs belong somewhere else because they don't carry comparable functionality.

**Comment by cjconroy** [comment]
I was able to create the pub by leaving the doi blank. The new pub has the giant red button about adding a doi. When I click the red button it is not happy. See attached. 

<img width="1594" alt="Screenshot 2023-07-28 at 1 02 43 PM" src="https://github.com/ArctosDB/arctos/assets/5749672/0672ee31-09ff-46f6-88da-064f019aae9f">

**Comment by dustymc** [comment]
giant red button 

It worked, someone noticed, yay!! 

>attached

It's still not crossref, but you can add the DOI and save (but not without authors or I'd have done it for you).

**Comment by cjconroy** [comment]
Looks good now.
