### ISSUE TITLE
Error - Insufficient Information Given (Bulkload Citations)

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#6590]
I'm trying to bulkload citations and am receiving this error: Insufficient Information Given

I'm assuming it has to do with identification? We used to have USE_EXISTING_ACCEPTED_ID which made things very easy (1s and 0s) vs. doing lookups....not sure what the issue is.

[BulkloadCitationsData.csv](https://github.com/ArctosDB/arctos/files/12233764/BulkloadCitationsData.csv)

**Comment by dustymc** [comment]
https://arctos.database.museum/tools/BulkloadCitations.cfm?action=ld will tell you what's necessary.

I'm up for whatever re: existing IDs - it will take an ID, there could be some way to getting those, that might have some overlap with https://github.com/ArctosDB/arctos/issues/6579. FWIW I'd always consider a citation to be an independent ID (because it is and the authors deserve full credit for it) and so would never try to re-use an existing. 

And I'd move the citation remarks to publication remarks, assuming it's not changing by record or something.

I did this, in case it's helpful:

```
create table temp_cs as select * from temp_cache.temp_dlm_uptbl ;
alter table temp_cs add use_identification_id varchar;
update temp_cs set use_identification_id=(select string_agg('https://arctos.database.museum/guid/'||flat.guid||'/IID'|| identification.identification_id,'|')
    from flat inner join identification on flat.collection_object_id=identification.collection_object_id where identification.identification_order>0 and 
    flat.guid=temp_cs.guid);
```

[temp_cs.csv](https://github.com/ArctosDB/arctos/files/12233893/temp_cs.csv)

**Comment by ebraker** [comment]
Thanks. Yeah, it would be nice to not have to look up identification IDs or current names, so some equivalent of use accepted ID would be nice to have a simple approach alongside the complexity. The only time I don't use the current ID is when entering type descriptions (rare for us) or a historic pub surfaces that references an old synonym. 95% (more?) of the time I'm using the current ID when attaching citations.

**Comment by Jegelewicz** [comment]
> I'm using the current ID when attaching citations.

I agree with @dustymc that robs those who made an ID of their attribution. I always create a new ID, even if the name is the same and add the paper authors as the determiners. No need to find an old ID and everyone gets credit.

**Comment by ebraker** [comment]
@dustymc I'm still not sure where I can grab USE_IDENTIFICATION_ID from?

I've got another csv to load.

[citations.xlsx](https://github.com/ArctosDB/arctos/files/12243302/citations.xlsx)

**Comment by dustymc** [comment]
>author is using occurrence data and not physically examining specimens or not making assertions about IDs

I'm sure somewhere there's some publication that somehow references records or items and fails to make any implicit or explicit identifications ("Interesting Observations Regarding Things Which Shall Remain Unnamed...."), but I don't think I've met it. Kinda everything at least fails to reject the hypothesis that the individual is sorta like the ID you gave them. (Or, they probably don't, but they just silently toss those out - the scientific community's failures at documenting failures is a subject unto itself!)

> decouple identifications from citations

The coupling was added because of the above - citations just kinda always involve identifications, the ability to not make that very explicit by re-using some existing IDs is what (erroneously, perhaps) remains.

ANYWAY....

>grab USE_IDENTIFICATION_ID

It's in "Identifications" in search results, but that would take some extraction. Might be best to open an issue if you want it in some form, I think that's probably lost in other issues by now.

Assume I mangled everything when I'm starting from Excel, but I used writeSQL to ...

```
select
flat.guid,
string_agg('https://arctos.database.museum/guid/'||flat.guid||'/IID'|| identification.identification_id,'|') as use_identification_id
from flat
inner join identification on flat.collection_object_id=identification.collection_object_id and identification.identification_order>0 where guid in (
'UCM:Mamm:1195','UCM:Mamm:13092','UCM:Mamm:13094','UCM:Mamm:7879','UCM:Mamm:7894','UCM:Mamm:7908','UCM:Mamm:7920','UCM:Mamm:7880','UCM:Mamm:7890','UCM:Mamm:7909','UCM:Mamm:7911','UCM:Mamm:7916','UCM:Mamm:7918','UCM:Mamm:23804','UCM:Mamm:13087','UCM:Mamm:13095','UCM:Mamm:13103','UCM:Mamm:13104','UCM:Mamm:13107','UCM:Mamm:7878','UCM:Mamm:7892','UCM:Mamm:1194','UCM:Mamm:7888'
) group by flat.guid
```
[temp_cache.user_sql_tbl_dlm(6).csv](https://github.com/ArctosDB/arctos/files/12243619/temp_cache.user_sql_tbl_dlm.6.csv)

**Comment by ebraker** [comment]
Thanks. I get all that but it also prioritizes the ID above all else (the thing itself, collecting data, etc. which are all sort of conflated as the ID), so I think there is a world where one could just cite the record/gestalt vs. the ID (while certainly this could remain an option when an author is asserting something specifically about the identification). But I will leave it alone unless someone else wants to take this up.

I'm still unable to find or grab  USE_IDENTIFICATION_ID through any download. I've tried separately downloading Search Results, Identifications, and "for Citation bulkloader". Is there any way Identification_ID can just be included as part of the download option -> "for Citation bulkloader"?

**Comment by dustymc** [comment]
>"for Citation bulkloader"

Perfect, I can do something there, thanks! I'll go direct on this for that (and make something happen as soon as I get my test box back).

**Comment by dustymc** [comment]
Added the list of >0 IDs to citation loader download.

Something better/different might come out of https://github.com/ArctosDB/arctos/issues/6607#issuecomment-1677619546
