### ISSUE TITLE
Feature Request - closing loans

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#6598]
I'm reviewing notifications related to open loans and realized a lot have a "closed date", but the status is still set to "open". Would it be possible to have the status automatically update to "closed" once a date is entered in "closed date" field?

![image](https://github.com/ArctosDB/arctos/assets/93737929/62ff123b-28be-41ab-8301-a64c9cc6d92b)

**Comment by AJLinn** [comment]
My use of it varies depending on the type of loan. If it's a media loan (e.g., when someone requests an image to publish) I create a loan, create a shipment to document when I sent the digital file, but then keep it open until I get the required copy of the publication. If it's a returnable loan, I close it after I get the objects back, they're condition reported, then put away. The status changes with each activity. 

In general, I typically change the status to closed the same time I enter the closed date. I also use the Remarks field to keep track of various activities:
<img width="609" alt="Screenshot 2023-08-03 at 12 44 09 PM" src="https://github.com/ArctosDB/arctos/assets/17605945/c631755e-ee5d-4edb-94b2-c6de1df449fa">

I can see how others might use it differently since you mention that @ewommack. I also have been frustrated like @wellerjes in reviewing my loans to find things that were returned and put away and have a closed date but status open... or vice versa of a closed status but no closed date. Following along to see how others are using this!

**Comment by campmlc** [comment]
As all my loans are consumable, I keep it open until we get a publication. But frequently that doesn't happen , especially with grad student research projects that are issued multiple loans- grad students are terrible about sending pubs.

**Comment by campmlc** [comment]
Maybe this could be an optional setting in Manage Collection?

**Comment by ebraker** [comment]
I record closed date when specimens are returned, but do not officially close out the loan until resulting publications and NCBI links (if applicable) are captured. Ideally the researcher passes these things along but I do a once annual sweep through Google Scholar to look up all loan borrowers and that usually surfaces quite a few papers. I also bug people after 3-5 years if I haven't found anything online and close out if I get no response or nothing came of that project.

**Comment by dustymc** [comment]
>3-5 years i

Pleasepleaseplease use Agent Rank - others deserve to know if some borrower can't be bothered to honor loan agreements!

<img width="393" alt="Screenshot 2023-08-03 at 15 42 03" src="https://github.com/ArctosDB/arctos/assets/5720791/0df5a5fe-9ecf-4406-a02b-fcc5ebd21ffa">

**Comment by campmlc** [comment]
That would be most of them . . .and our time would be consumed by agent ranking. Actually, most do eventually publish and even cite, but just don't bother letting us know.
