### ISSUE TITLE
[external CONTACT] identification order

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#6600]
@dustymc I was trying to update some IDs yesterday and I didn't think they were saved because the form was a bit confusing to me regarding ID order. However, it turns out that the IDs were saved but with ID order = 0 for both the old and new IDs. The records are MVZ:Bird 195400-195411. It looks like the default order (e.g., of the original IDs) should be 1 but it would be helpful to show the order in the table where you're updating IDs.

![image](https://github.com/ArctosDB/arctos/assets/967275/222f0b3c-1f3e-4c85-89b2-e2dbd5ddc6d3)

I manually updated the ID order for the old records from 0 to 1, and the new records to 2, but I'm not sure if that's correct and I have some questions about this.

Is the idea that a higher number is the more current ID? So if a record has ID=1 as the baseline, then does ID=2 mean it's a more current ID?

Should the default be "Set all existing IDs to order = 0" versus "do nothing" ? It seems like you get into trouble when you set them to 0, and the detail page doesn't show all of the metadata for IDs = 0. Without seeing the ID order in the table of what you're updating, it's hard to know what you're actually doing plus I didn't see that drop down option of setting all IDs to order 0 (not sure when/why you would want to do that?).

Finally, it would be helpful to have a helpful tip about ID order in the "Special Magic Sauce" section. There is a link to a long Github issue but that's not super user friendly.

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/6552 is linked because I figured we'd end up here. I don't like the defaults either, but I got outvoted.

>Is the idea that

https://handbook.arctosdb.org/documentation/identification.html#identification-order

>Special Magic Sauce"

My intention is to kill that, https://github.com/ArctosDB/arctos/issues/6591#issuecomment-1662443156

**Comment by dustymc** [comment]
multiidentification: add all IDs with their current order in the pre-update table

**Comment by DerekSikes** [comment]
Following on my earlier points regarding the best practice being to ask users to opt-in to this new ranked order ID system (rather than requiring users who don't want it to constantly opt-out of its use)... I will reiterate that the default on the batch ID update form should be to set all prior IDs to 0 since this most closely mimics the prior system. I wish the default for the ID order of the new name could be set to 1, which will remove the constant need to set this to 1 manually. If I forget to set it to 1 and complete the form & click apply I get an error message and have to start over & refill the form again. (Muscle memory is important - I still often hit command-s unconsciously even when working on a google doc that autosaves because I've been so traumatized about losing all my recently typed text due to OS crashes despite those crashes having mostly stopped happening when Mac switched to a unix based OS.)

I've used this Arctos batch ID form thousands of times and often hundreds of times a week when doing lots of IDs. Changing it so I have to remember to do something different in order to achieve the same goals is bothersome. Those who want to use the new ranked order IDs should have to click new stuff to get the new stuff to work.

And I think Carla and I are still wondering about the answer to "So if a record has ID=1 as the baseline, then does ID=2 mean it's a more current ID?"

I understand that 0 is equivalent to 'not accepted' and 1 is equivalent to 'accepted' but what does 2 or 3 mean?

**Comment by ccicero** [comment]
@DerekSikes Per the Arctos issues meeting today, here's my understanding of the rankings (@dustymc please confirm):

0 = unaccepted
1 = currently accepted
2+ = older legacy names that are still valid but not currently accepted

Biological collections will likely use just 0 or 1, but other types of collections that have older legacy names can now add those as well.

**Comment by genevieve-anderegg** [comment]
> 0 = unaccepted
1 = currently accepted
2+ = older legacy names that are still valid but not currently accepted

This is how DMNS:Inv is structuring identifications, as we have a lot of legacy identifications that we want to capture but represent outdated taxonomy

**Comment by dustymc** [comment]
>0 = unaccepted

yes


> 1 = currently accepted

yes (but note that this is no longer unique)

>2+

Also accepted, but not as preferred as lower numbers.

>Biological collections will likely use just 0 or 1,

You can, but there's now the capacity to say "these 27 methods all agree with each other, and we give them equal weight."

**Comment by dustymc** [comment]
Stuff discussed in https://github.com/ArctosDB/arctos/issues/6591 will be in next release.

I made the label for the (weird to me and apparently @ccicero) default harder to miss (but still missed it a couple times while testing...).

Can we please discuss this as a whole, https://github.com/ArctosDB/arctos/issues/6607#issuecomment-1677619546 ?

<img width="754" alt="Screenshot 2023-08-14 at 10 36 43" src="https://github.com/ArctosDB/arctos/assets/5720791/734c4195-4ecd-4d51-8b32-c021ecc6095b">
