### ISSUE TITLE
agents with same name

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#6611]
I am about to bulkload some specimen data and realized that there is already an agent record for an individual named Larry McNeil. However, he is not the same individual as the artist from UAM:Art: https://arctos.database.museum/agents.cfm?agent_id=21290113

Since the CHAS Larry McNeil that I want to create a record for is an employee and specimen preparator, I want him to have his own agent record, as opposed to "verbatim agent". 

In order to prevent a [repeat of this issue](https://github.com/ArctosDB/arctos/issues/6112), where the new agent is mistakenly tied to another, what should I do? Did we come to a conclusion about how to handle agents with the same name (post-agent cleanup)? If so, can you please direct me to the GitHub issue?

@ArctosDB/agents-committee

**Comment by Jegelewicz** [comment]
@wellerjes I can see that our documentation is lacking for this situation, so I am going to write it here, then add it to documentation.

When two different people have identical names, the only way to create two separate agents is to give one of them a parenthetical remark after their preferred name. I really dislike this, but because we use preferred name as the "index" for agents, there is no other way.

That being said, I suggest you create a new agent

`Larry McNeil (CHAS)`

And add the [not the same as](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctagent_relationship#not_the_same_as) relationship to the original Larry McNeil (and back from them to the new agent) and please document WHY in the relationship remark.

Let me know if that doesn't make sense.

Here are some examples of this treatment, although they are all lacking in completing the directions above in some way.

[Carl Johnson (Albuquerque)](https://arctos.database.museum/agents.cfm?agent_id=21325605)
[David Smith (Texas)](https://arctos.database.museum/agents.cfm?agent_id=21331803)
[David Stephen Taylor (MVZ)](https://arctos.database.museum/agents.cfm?agent_id=21309995)

**Comment by wellerjes** [comment]
Thank you!

**Comment by dustymc** [comment]
https://handbook.arctosdb.org/best_practices/Agents.html#different-agent-same-name

**Comment by AJLinn** [comment]
As an aside, I just "upgraded" the UAM Larry McNeil's record so it's no longer a low-data agent. Hope that helps to distinguish him from the CHAS one!  :-)

**Comment by dustymc** [comment]
>"upgraded" the UAM Larry McNeil

And he now has available a unique name - is there some reason Larry Tee Harbor Jackson McNeil (or Larry T. or...) can't be preferred and the parenthetical (which the most excellent metadata now suggests is misleading - this person seems to be affiliated with all sorts of stuff, not just UAM) be dropped, from both agents?

**Comment by AJLinn** [comment]
I agree that I can shift his preferred name to Larry T. so we disambiguate him.

**Comment by AJLinn** [comment]
> parenthetical ... dropped, from both agents?

Done and done!
