### ISSUE TITLE
Identification Order?

### ISSUE THREAD

**Issue by jebrad** [ArctosDB/arctos#6614]
Hello all, not sure if this is the right way to try to solve (start?) an argument.  But here at UWBM we were arguing about what this new Identification Order means.  I assumed it refers to the order in which the IDs were assigned, but the handbook definition (pasted below) instead it makes it sound like Identification Order is a proxy for Identification Confidence, but Confidence still exists as an Attribute of the Identification. 

So - how is this Identification Order supposed to be used?    Or do you have a recommended workaround?  (eg make all of ours 1 unless we have a good reason to rank them otherwise).

Thanks, Jeff

From: https://handbook.arctosdb.org/documentation/identification.html#identification-order
Identification Order
A record may carry any number of identifications which may be in any order. (Order is currently confined to integers between zero and ten.) Order zero is generally treated as “unaccepted” in the UI; all other values are “accepted.” Order is non-unique; multiple determinations may be ranked 0 (eg if they are later determined to be incorrect), or multiple determinations may be ranked ‘1’ (=”most preferred”) - for example, if they consider different aspects of a cultural item (parka and -Gulo_).

**Comment by Jegelewicz** [comment]
> how is this Identification Order supposed to be used?

This replaces the old system of accepted/unaccepted and for the purposes of retaining that, 0 = unaccepted and 1 = accepted

BUT

you can also assign any number above 1 to mean accepted, but not as much as 1. 

See [this](https://github.com/ArctosDB/arctos/issues/6579) for one explanation of how this is used. 

You can also have more than one order = 1 to indicate that there are more than one accepted identification related to the catalog record. This is important for cultural and geological collections that may need to have more than one accepted identification on a record (a fossil in a bead of amber for example). It might also be used in biological collections when several different determiners have reached the same conclusion about the Id assigned to a biological individual.

Make sense?

**Comment by Jegelewicz** [comment]
Also forgot - order 1 identifications are what will get passed to the data aggregators.

**Comment by dustymc** [comment]
>order in which the IDs were assigned

No, that's made date, there's no connection. 

>make all of ours 1 unless we have a good reason to rank them otherwise

Perfectly valid approach, and what I think @DerekSikes has in mind. MAYBE it loses some of the subtleties of "all these techniques landed on the same answer" and such (or not, they probably share names and that remains fairly obvious), but it's also a big simplification. There are no rules forcing you into the old system, but it remains available for anyone who wants to use it. (And everything's running through an API, so if someone wants to build their own UI that supports or limits WHATEVER then that's available too.)

>order 1 identifications are what will get passed to the data aggregators

Not quite. I'm currently passing a single 'best' >0 ID, which was *the* '1' post-migration but could be fairly arbitrary (because there are 17 apparently-equal 'bests') or a 10 (because there are no other >0 IDs from which to choose) or nothing (nothing's forcing you to accept anything at all) or probably other weird things as the data get more complicated.

As far as I know nobody's ever done anything remotely like this, so I expect Best Practices, forms, DWC mapping, etc. to be refined as we all figure out what this means in practice.

**Comment by jebrad** [comment]
OK thanks very much, this is helpful.  (You were right @hippyherpdude ) - closing now.
