### ISSUE TITLE
Media: "subject" - new structure?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ArctosDB/arctos#665]
```
Is label "subject" a new kind of data better implemented as "tags"? "audio 
vocal type" is the same type of information and should share a fate with 
subject.
```

Original issue reported on code.google.com by `dust...@gmail.com` on 14 Nov 2013 at 4:34

**Comment by dustymc** [comment]
Still unclear to me that more structure would improve these data, in part because I still don't understand why the data (esp. subject) exist. 

Additional structure would imply that there are a finite/small-ish number of total possible "subject" and "audio vocal type" values, and that we can accurately and uniquely identify them (and get users to assign labels correctly). Can we be sure that an audio file marked "hoot" doesn't have a "call" mixed in? Is there an unambiguous distinction? Is "camp/people" mutually exclusive from "habitat"? Etc., etc., etc. This needs more discussion, and should probably involve others with similar data - Cornell, whale vocalization folks, bat-people, etc.

Current data:

UAM@ARCTOS> select distinct LABEL_VALUE from media_labels where MEDIA_LABEL='subject';

LABEL_VALUE
------------------------------------------------------------------------------------------------------------------------
camp/people
habitat
bird roosting before it was captured
building/landscape
prepared specimen
habitat/landscape
building/structure
fish
Lectotype
1946-06-14
1925-06-17
people/camp
mammal
reptile
plant-annual/perennial
insect
1946-07-15
MVZ 10716
amphibian
plant-tree
1946-06-16
1959-04-11
plant-shrub
1950-07-23
1948-07-16
plant-annual/perrennial
Mammal
habita/landscape
Amphibian
bison mount
unprepared organism
invertebrate
data/drawing
map
2013 04 02 1119
bird
map/data/drawing
amphibian, reptile
In Field Notes: v1435, s1, p103
habitat/ landscape
Grizzly bear (Ursus arctos)
habitat/lanscape

42 rows selected.

UAM@ARCTOS> select distinct LABEL_VALUE from media_labels where MEDIA_LABEL='audio vocal type';

LABEL_VALUE
------------------------------------------------------------------------------------------------------------------------
position notes
tapping, drumming
trill
dives and arcs
No neg.
whee note
flight, arcs
flight and display
howl
song
call
Mixed
whistle
flight
Glass negative. Slide 2@16.
mixed
Image labeled J.M. Linsdale #111
song
alarm calls
rattle
unknown
scream
hoot
mixed
shows object on exhibit
