### ISSUE TITLE
Feature Request - Agent bulkloader gives un unhelpful error

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6652]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_

Just loaded some agents and about half of them resulted in "fatal errors detected". I have no idea what is wrong with them.

**Describe what you're trying to accomplish** 
_A clear and concise overview of the goals; why are you asking for this?_

Get an error that helps me fix whatever cause them to be rejected.

**Describe the solution you'd like**
_How might we accomplish your goals?_

Tell me what trigger caused the "fata error".

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

Enter them manually to figure it out.

**Additional context**
_Add any other context or screenshots about the feature request here._

They are still in the loader - https://arctos.database.museum/loaders/bulkload_agents.cfm

**Priority**
_Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair._

**Comment by Jegelewicz** [comment]
Looked through and it looks like "NA" is the problem - but we still need better error reporting.

**Comment by dustymc** [comment]
You should never be seeing errors in the loader - those should all have been fixed in the pre-loader, which should give you better errors. I grabbed your data and stuck it in the pre-loader to see if that stands up to reality.

Those two tools were built when we we loading lots of low-quality agents, I believe because there was a request (from you?!) to allow naive users to access the tools. I wonder if we can rethink that and perhaps merge them now? If not, the inline docs should be beefed up.

**Comment by Jegelewicz** [comment]
These had all been through the preloader, but without the addresses.

**Comment by dustymc** [comment]
> but without t

then it's some other data that's been through the preloader....
