### ISSUE TITLE
Feature Request - catalog record edit UI - updates or improvements

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6684]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_

I have been editing a lot of identifiers today and when I hit "save changes" it is not really possible to tell if the changes saved unless I refresh the record and edit again (because I am just removing spaces, my edit isn't obvious when looking at the record). 

**Describe what you're trying to accomplish** 
_A clear and concise overview of the goals; why are you asking for this?_

It would be nice to know that my changes have been saved.

**Describe the solution you'd like**
_How might we accomplish your goals?_

How about a scree color change? The edit screen is white when it opens, after hitting save, could it change to green? Or could "Changes saved" be printed on the form?

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

I just keep my fingers crossed that I have actually hit "save Changes" and that I won't have to come back and do something again because my clicked missed the mark.

**Additional context**
_Add any other context or screenshots about the feature request here._

**Priority**
_Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair._

**Comment by dustymc** [comment]
That was designed to run under a 56K modem, can't imagine the constraints have changed....

The simplest solution is probably to make all of the edit apps into standalone pages (eg what's there now plus the header) and let them behave as normal forms. That would also mean the main page would have to reload after a change, which (unlike now) would keep it current (at the expense of reloading the entire page a lot more, which seems affordable for both the back end and everyone's network). I'm definitely up for most anything else.

**Comment by dustymc** [comment]
From https://github.com/ArctosDB/arctos/issues/6988:

The idea of a save+close button in the current setup is a little scary in that it provides a pathway to 

1. pick the wrong agent-or-whatever
2. save and close
3. don't notice the error as the "main page" is cached and doesn't reload with a successful save

and I don't quite know how to address that. (Consider it a remote possibility which would never see reality with our careful users and rock on, perhaps?)

Perhaps an 'edit everything' page would make more sense than the various (and not always perfectly clear) 'edit node' overlays?

Perhaps "we" should get (by default, or by switching to 'edit mode', or ??????) a less-cached page in which we can see current data, and the 'save and close' button should reload it, or each "field" should reload asynchronously, or ???? 

As above the tech stack has changed radically since the page was designed, and the edit-bits haven't much changed since then. I'm up for anything, including to a blank-slate start (and will edit the title of this issue accordingly). How can we make the single-record form awesome-er?

**Comment by Jegelewicz** [comment]
I'd actually settle for a change in color to indicate a save has happened.

**Comment by dustymc** [comment]
>change in color

The current form uses iframes - the popup does a normal POST then reloads, at which point I can't know if you just opened or if something was successful. Your browser should handle that (but it's also generally faster than you can see so it doesn't really). A color/style change would probably be part of a REST rewrite. I could do some sort of 'success click to continue....' bit instead of a redirect on a good save, but I think that's about the opposite of https://github.com/ArctosDB/arctos/issues/6988 (more clicks).

**Comment by dustymc** [comment]
I'm tentatively tabling this; I can't identify anything immediately actionable, this might be part of a bigger UI update or ??
