### ISSUE TITLE
geography request - Mediterranean Sea

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6688]
### Explain what geography needs created.

Explain in sufficient detail for us to locate standardized spatial data. For GADM-based data, a country is usually sufficient and appropriate. Please request distinct countries in distinct issues. We will respond with a CSV template and instructions for proceeding, or a request more information if necessary.

Mediterranean Sea which is an IHO Sea Area - https://www.marineregions.org/gazetteer.php?p=details&id=1905

We have a lot of subsections of Mediterranean Sea, but not the whole. This is needed for an incoming collection.

If the above does not seem correct, usable, or ideal, please open a request for information Issue (you may use this template). We are happy to discuss specifics or alternates; please bring any potential concerns or problems to our attention *before* assembling data or requesting that we do so.

**Comment by dustymc** [comment]
1. I'm about 92% sure that wasn't in the "authority" we adopted, but I also can't quite nail down what that was - my [notes](https://github.com/ArctosDB/arctos/issues/5138) just say https://iho.int/ and I can no longer find any spatial data there. It would be great if we could better define the Standard.

2. Your link (after I provided way more information than anyone needs...) downloaded a thing called 'World_Seas_IHO_v3.zip' which inflated to....you guessed it, USGSEsri_GlobalIslandv2s_Big_allnames_geo (which is in fact a ~~big~~ huge list of ~~all~~ random islands). I'm not entirely sure what a marineregions.org is, but I'm pretty sure it's broken....

@mkoo halp?!

**Comment by Jegelewicz** [comment]
I don't know why we picked IHO, but it seems super limited. https://www.marineregions.org/gazetteer.php is much better populated and includes all of the IHO geography listed above.

IHO is so weird - why no [Gulf of Maine](https://www.marineregions.org/gazetteer.php?p=details&id=8940), but includes [Bay of Fundy](https://www.marineregions.org/gazetteer.php?p=details&id=4289) which is also in Marineregions.org. It is weird because Bay of Fundy is just a portion of Gulf of Maine as our Geography makes clear [Gulf of Maine, Bay of Fundy](https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=10016562). For marine collections, more options and a little more granularity in higher geography would be nice and in some cases a little less too "Mediterranean Sea".

@sharpphyl @genevieve-anderegg @kmkocot @happiah-madson @falco-rk any thoughts on this?

**Comment by Jegelewicz** [comment]
I'd also like to bemoan the way the marine stuff is named. There is no hierarchy, so we have

[South China Sea, Gulf of Thailand](https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=10007852)
[Pacific Ocean, South China Sea](https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=10007858)

BUT IHO doesn't include Pacific Ocean, so I would expect

North Pacific Ocean, South China Sea, Gulf of Thailand
North Pacific Ocean, South China Sea

Also stuff like

[Atlantic Ocean, Gulf of Mexico](https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=10006518)
[North Atlantic Ocean](https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=1143)
[North Atlantic Ocean, Greenland Sea](https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=1144)

BUT IHO doesn't have "Atlantic Ocean"

so I would expect

North Atlantic Ocean, Gulf of Mexico
North Atlantic Ocean
North Atlantic Ocean, Greenland Sea

Can we figure out a way to make these more consistent? It is maddening trying to find marine higher geography matches.

**Comment by dustymc** [comment]
>Can we figure out a way to make these more consistent?

Some/all of that's probably me learning how this can work and how it can be integrated with our legacy data. The answer became clear somewhere through GADM: faithfully follow the Standard or make giant messes. I'll open an Issue.

**Comment by sharpphyl** [comment]
I would much prefer to use https://marineregions.org/ instead of (or in addition to) IHO.  In addition to offering a better breakdown of the oceans, it offers [EEZs](https://marineregions.org/eezmapper.php) which would be helpful for just offshore localities.  Additionally, it is the source for OBIS distribution maps.  

As to what oceans should be in higher geography, Marine Regions seems to go with North Atlantic etc. rather than Atlantic and Pacific Oceans.  https://marineregions.org/gazetteer.php?p=image&pic=119334.  That is an issue for us only when we only have the larger ocean as the locality so there's nothing in higher geography.

**Comment by dustymc** [comment]
>super limited

That's kinda how Standards work - they never seem to do quite what anyone wishes they did, but they're still the only effective way to communicate outside of tiny little groups.

https://xkcd.com/927/

I'm pretty confident in saying that marineregions.org can't serve as a standard - it contains eg https://marineregions.org/gazetteer.php?p=details&id=64226, that ain't geography.

Some subset of marineregions.org might be suitable, if it turns out to be useful and available and stable and all that jazz. The closest I can find to eezs is "PlaceType | Territorial Sea" eg https://marineregions.org/gazetteer.php?p=details&id=49147

I was able to pull MarineRegions:eez_12nm from there, but it was just MX - I suspect I'd need GIS support (https://github.com/ArctosDB/arctos/issues/5597 would be nice...) if this somehow turns into reality. (First question would be whether the Territorial Sea data is EEZs or if I just picked a bad example.)

>That is an issue for us only when we only have the larger ocean as the locality so there's nothing in higher geography.

I think that might be often overlooked (and it's clearly the solution to "someone insists on doing something outside the Standard") - just use https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=10016350 for geography and maybe something like https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlocality_attribute_type#previous_geography if some sort of semi-formal assertion is somehow useful. If there are decent coordinates then it's easy to dynamically put the place into ANY spatial system, and if there's not then none of this can carry much weight anyway - picking a correct-but-not-great geography doesn't eliminate any magic.

**Comment by Jegelewicz** [comment]
I agree that all of the things in marineregions.org are not geography, but there are things that could be

[Gulf of Maine](https://www.marineregions.org/gazetteer.php?p=details&id=63490)
{Mediterranean Sea}(https://www.marineregions.org/gazetteer.php?p=details&id=1905) - which the gazeteer says is from IHO....

![image](https://github.com/ArctosDB/arctos/assets/5725767/d66e812d-17ee-4149-8326-58feec3fef04)

[Bahamas Exclusive Economic Zone](https://www.marineregions.org/gazetteer.php?p=details&id=8404)

Maybe we just need to be more flexible with marine geography and allow more than just IHO, which seems a bit too limited. We could set rules about what can be used from marineregions.org if that will help to eliminate stuff that is just too small or weird to be geography

You can search by place type = EEZ

![image](https://github.com/ArctosDB/arctos/assets/5725767/1ad761b0-a403-4278-8128-998e599000b1)

I also thing the Freshwater Ecoregions of the world would be nice spacial features to to include. Just day dreaming...

**Comment by genevieve-anderegg** [comment]
Should we put another Geography committee meeting on the calendar to discuss?

**Comment by dustymc** [comment]
>flexible

Pretty sure that's just "don't follow the Standard" and should terrify anyone who remembers where we came from!

>Geography committee meeting

Seems reasonable. I think the goal would be to identify some subset of the data and nominate it for assertable geography, https://handbook.arctosdb.org/documentation/higher-geography.html. (And maybe discuss the functional implications of  overlaps with other "authorities" if that turns out to be the proposal - I just can't deal with that at the moment.)  Would be useful to invite (or maybe pre-coordinate with) @mkoo - doesn't matter how spiffy the idea is if we can't make it work (and downloading hundreds of shapes individually is probably not workable).

> Freshwater Ecoregions of the world

Is someone trying to assert that, or ??????? 

The bar for Features is much lower - but there are also infrastructure limitations at the moment, https://github.com/ArctosDB/arctos/issues/5597 could use a champion (and should make just sucking everything from https://www.marineregions.org into Features trivial).

**Comment by Jegelewicz** [comment]
> Is someone trying to assert that,

No - but it would make for cool searches

**Comment by genevieve-anderegg** [comment]
Should we put another geography committee meeting on the calendar? @dustymc @Jegelewicz @mkoo

**Comment by genevieve-anderegg** [comment]
> The bar for Features is much lower - but there are also infrastructure limitations at the moment, https://github.com/ArctosDB/arctos/issues/5597 could use a champion (and should make just sucking everything from https://www.marineregions.org/ into Features trivial).

Marine Regions just released some new boundaries and updated others: https://www.marineregions.org/files/newsletter_v12.htm

I'll put this issue on the Geography agenda for next week so we can discuss 1) if and how to add data from Marine Regions and other sources of geography that aren't GADM, 2) the current status of Features for geography, and 3) procedures and workflows related to all of this.

**Comment by dustymc** [comment]
>sources of geography that aren't GADM

For the sake of completeness, the current model was born that way - https://handbook.arctosdb.org/documentation/higher-geography.html#iho-world-seas

Adding more sources is a social issue (excepting the below). (And FWIW I'll probably oppose anything that looks like a pile of arbitrariness and support anything that acts like a Standard.)

> current status of Features for geography,

https://handbook.arctosdb.org/documentation/higher-geography.html#unassertable-higher-geography - ?? what's not clear? 

>3) procedures and workflows

https://github.com/ArctosDB/arctos/issues/6521#issuecomment-1751489551 is my request for help. (Options seem to include getting TACC to fix whatever's preventing me from doing something I've previously done literally thousands of times, or finding some way to implement something like https://github.com/ArctosDB/arctos/issues/5597.)

**Comment by genevieve-anderegg** [comment]
Bear with me as I read up and reacquaint myself with where we're at on all the different issues and discussions around Geography in Arctos as I prepare for our first meeting on Monday!

> Adding more sources is a social issue

And perfect discussion material for our committee! If we want to include data from an outside source that appears as a pile of arbitrariness, we'll have to discuss what we want to select from that pile (and what is not useful).

> ?? what's not clear?

Nothing, just saying we'll have to discuss if there's other things/shapes from other sources we want to make a FFF

> https://github.com/ArctosDB/arctos/issues/6521#issuecomment-1751489551 is my request for help. (Options seem to include getting TACC to fix whatever's preventing me from doing something I've previously done literally thousands of times, or finding some way to implement something like https://github.com/ArctosDB/arctos/issues/5597.)

Ah I see I see. I'll add this to the agenda so we can talk about it. #5597 would be fantastic
