### ISSUE TITLE
Operator activity statistics

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#6706]
I need to collect some information about the data entry activities of my students in 2023. I thought I could go into Status and Stats and get the info from the Data Entry Statistics tool.

I entered this:
<img width="607" alt="Screenshot 2023-09-05 at 8 59 14 AM" src="https://github.com/ArctosDB/arctos/assets/17605945/a526093d-723d-44b0-a29f-6a2729a5ed0a">
Which I thought would provide me the number of records entered by Hannah Witherington since she was hired back in March. But I know that number is not correct.

then I did an agent search and found this:
<img width="607" alt="Screenshot 2023-09-05 at 9 00 26 AM" src="https://github.com/ArctosDB/arctos/assets/17605945/8c75b5d7-b052-44a1-aec2-fb40fc3ffef3">

Can someone explain to me why the data entry report is not showing the 73 catalog records Hannah created this year so far, and/or suggest a better way to get this information by year and by agent?

Thanks!

**Comment by Jegelewicz** [comment]
That report is showing that she is the preparator for those objects, not that she entered those records.

**Comment by Jegelewicz** [comment]
However, the Arctos activity for the agent shows entry of 91 records:

![image](https://github.com/ArctosDB/arctos/assets/5725767/5c962f18-c31b-402f-ad30-35c739b546ff)

so maybe something is still weird? or maybe records were entered after 2023-08-31...

**Comment by dustymc** [comment]
>thought would provide me the number of records entered by Hannah Witherington

Sorta, but probably not what you're looking for - if a cat walks across her keyboard and makes 19876 duplicates, they'll show up there.

That was also reset with the recent structure change, so wouldn't go back that far even if that was what you want.

Try WriteSQL and

```
select
    guid_prefix,
    to_char(coll_object_entered_date,'YYYY-MM') as emon,
    count(*) c
from
    coll_object
    inner join cataloged_item on coll_object.collection_object_id=cataloged_item.collection_object_id
    inner join collection on cataloged_item.collection_id=collection.collection_id
    inner join agent on coll_object.entered_person_id=agent.agent_id
where
    preferred_agent_name='Hannah Witherington'
group by
    guid_prefix,
    to_char(coll_object_entered_date,'YYYY-MM')
order by 
    to_char(coll_object_entered_date,'YYYY-MM')
```

That's not exactly what you asked for, but I think it's a little more likely to be useful in the future - let me know if you need something else.

It's also (still) not quite "entered" - it doesn't count those theoretical aforementioned duplicates, it doesn't count anything that's been "entered" (correctly or otherwise) but which hasn't been finalized into a record, and it doesn't include anything that might have made it through that and then been deleted.

**Comment by AJLinn** [comment]
Thanks for this - I'll test it out!
