### ISSUE TITLE
Feature Request - Shift-Click Boxes for Remove Record

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#6777]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
In the "old" Arctos interface, we could click a box to remove/keep a row in our search results. These boxes had the "shift-click" capability, which was super convenient when you needed to remove dozens of rows from the search results when casting a wide search net. 

The new remove/keep row function are two separate boxes that a user must click individually to mark each row. I request that we add the boxes (like those that appear in the Notifications interface) so we can select MANY rows to remove in one click.

**Describe what you're trying to accomplish** 
Trying to remove many rows from the search results view when the keep/remove row search/result customization is enabled.

**Describe the solution you'd like**
A checkbox for removing records with a shift-click capability.

**Describe alternatives you've considered**
Clicking the "remove" box hundreds of times... 😢

**Additional context**
<img width="1641" alt="Screenshot 2023-09-28 at 11 36 02 AM" src="https://github.com/ArctosDB/arctos/assets/17605945/da9af473-1365-49a7-adcb-5229695e63a3">

**Priority**
Normal / Wish List (though at the AWG meeting others seemed to agree this would be a welcome addition)

**Comment by dustymc** [comment]
I thought this would be a quick project, but it got super weird with a bunch of libraries conflicting with each other so ended up completely different than previously. Please let me know ASAP if something is not acceptable in some way.

The ONLY thing I could find which consistently supports shift-click in datatables is a datatables extension, so that's what I'm using. 

Clicking anywhere on the row (even the links, which can be pretty annoying) selects the row - the button doesn't really do anything special, but I left it on the theory that having a column is less confusing than not having a column. (DataTables has a nice fake-check-lookin'-thingee, but it *really* doesn't like to coexist with some coreward stuff I've done - mostly dynamic column positions.)

After selecting, I think the keep/remove buttons work more or less as before, but it is a completely different pathway (and the selectors involve weird datatables-specific things, but hopefully that won't find a way to be a problem).
