### ISSUE TITLE
Archived search DOI?

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#6788]
I've archived a search to attempt to use this as a persistent identifier to send to loan recipients outside of the museum community. The instructions say this will mint a DOI. How do I access the DOI? Or is the archived search url the doi?

**Comment by dustymc** [comment]
<img width="244" alt="Screenshot 2023-10-04 at 11 18 14" src="https://github.com/ArctosDB/arctos/assets/5720791/a4d1d5be-4745-42b0-bb32-5d56f746a42b">

Please CAREFULLY read the red stuff and https://handbook.arctosdb.org/documentation/archive.html, there is and can be no flexibility in the warnings.

**Comment by mkoo** [comment]
@campmlc the DOI's show up under your profile Saved Searches (what dusty screen saved above) at top of the page.

but you can also send them the saved search link URL. Technically the URL from a saved search is not a DOI but can function as one in the moment-- it's a dynamic search (only saving the search parameters). The Archive saves the cat_num list.

So whatever fits your needs.
If this answers your question, please close!

**Comment by campmlc** [comment]
Yes, I acknowledge I've read the instructions and documentation. I would like to actually use the DOI in this case because these are zoo samples being loaned to external researchers who have no idea what museum catalog numbers are or how to cite them, but I'm pretty sure they can understand a request to cite a DOI for specimen use. 
Some questions: 
1) I understand that once the archived search is locked and the doi is minted, that these records cannot be encumbered or deleted, but they can be edited. However, the archive link will go to the records and their associated data as it existed on the date of the archive url being generated. That's fine. I would like to know, however, if there is a process we can use to create re-directs for records that we cannot and do not want to delete or encumber, and if so, how that process works?
2) Can we add the link to the handbook documentation to the Saved Searches page, so it is readily obvious?

Here is the doi I've minted for this search: https://doi.org/10.7299/X7542NXX

**Comment by dustymc** [comment]
>However, the archive link will go to the records and their associated data as it existed on the date of the archive url being generated. 

Arctos does not have that capacity, and I don't understand what's suggesting it might.

**Comment by mkoo** [comment]
@campmlc I think the original issue has been addressed so I'd like to close this one. 
Before I do, I'll try to address your various questions:
1. I'm not sure what you're really asking here but you can create redirects from the Redirect: bulkload tool or manage tool (under Records tile in the Tool Directory). So let's say your doi needs to be updated since you have 8 more records to add, but you've shared the doi somewhere (who knows, doesnt matter). so mint a new one and redirect the old to the new doi uri. It will be in a sense a double redirect but it's possible to do. Someone in the doi world might complain! If this misses the mark on your question, bring it up at an Issues meeting.

2. I'll add as another issue since I think it's buried here.

**Comment by mkoo** [comment]
Documentation link added.
