### ISSUE TITLE
Format for verbatim attribute

### ISSUE THREAD

**Issue by adhornsby** [ArctosDB/arctos#6900]
Inspired by the Arctos newsletter blurb from @Jegelewicz !

I may have missed this somewhere, but is there a recommended format for verbatim attributes, e.g.:
ATTRIBUTE: value

And related, if there are multiple verbatim attributes should they be listed separately or in the same free-text box, e.g.:
ATTRIBUTE1: value1; ATTRIBUTE2: value2

Just thinking about how these would be easier to parse down the road, if/when needed.

**Comment by Jegelewicz** [comment]
> is there a recommended format for verbatim attributes, e.g.: ATTRIBUTE: value

That is the exact format I am using now. The important thing is to document how you are using it so that your future self (or those who come after you) can enter new data in a consistent way.

> if there are multiple verbatim attributes should they be listed separately or in the same free-text box, e.g.:
ATTRIBUTE1: value1; ATTRIBUTE2: value2

I would probably choose to list them separately to make them easier to find and deal with if they are transitioned to a dedicated attribute.

**Comment by adhornsby** [comment]
Makes sense, thanks @Jegelewicz !
