### ISSUE TITLE
Remove Issued by from Identifier downloads

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#6905]
Recently any view or download of data including indentifiers prefixes the identifier value with the full name of the Issued by agent. This does not fit easily in a flat column download and makes viewing and sorting on these columns exceedingly difficult. It is also affecting Reports. We are requesting to have this removed and just have the identifier value as the default in all forms and tools as soon as possible while the situation is sorted out to avoid work disruptions and added complications. We should provide an option of adding the issued by agent, but it should not be included as a default prefix for all identifier views, downloads, and reports.

**Comment by campmlc** [comment]
#6904

**Comment by Jegelewicz** [comment]
I would instead propose that we make better use of the labels name type?

<img width="960" alt="Screenshot 2023-11-02 10 05 38" src="https://github.com/ArctosDB/arctos/assets/5725767/38cf1fd0-748b-4b59-9f4e-ec03edce2092">

Issued by is the most important piece of information in disambiguating identifiers, in some cases it may be the ONLY disambiguating information.

It would be useful to know what exactly is happening so that we can discuss a solution that doesn't involve wholesale changes across all of Arctos.

**Comment by dustymc** [comment]
>what exactly is happening 

A label was using a function that didn't do what was desired. I swapped it out for a different one. 

Not sure why withholding attribution from Agents (to make ambiguous data!!) would ever be a consideration?!

**Comment by campmlc** [comment]
The problem is in the way the data are displayed and downloaded in the flat and download columns. For users, this obscures the actual value of the ID with a long text string of a full name in front of the value that requires an extra series of steps to remove in order to actually view the ID value.  If it is needed, we need it in a separate column, not prefixiing the ID value.

**Comment by AdrienneRaniszewski** [comment]
agree

**Comment by campmlc** [comment]
> Issued by is the most important piece of information in disambiguating identifiers, in some cases it may be the ONLY disambiguating information.

If all identifiers are ID type = identifier, that is true, which is why I absolutely disagree with this model. But that is not the case. The example that led to this isssue was ID type = collector number, and we needed to be able to display the collector number in a report by the ID value without including the issued by agent. This is true across many different tools in Arctos, including search and download as well as loan forms and reports. This is affecting the user interface in ways which are not being considered. We need to pause and address the UI aspects and how this is affecting people's workflows, which it is doing significantly.  It's not "just UI" when the UI is sitting directly on top of the data structure - we need to make sure users and operators can still function. @mkoo

**Comment by mkoo** [comment]
thanks Mariel, this is a good use case but not the only one here. We need to be able to accommodate all possible identifiers since many records have more than one. For the Issuers with long names then handling alternatives at the agent profile level seems a good way to go (as Teresa suggested) -- i.e., using labels or aka's or a different preferred form 

This is easily used for reports (no need to show the full name)

As for the downloadable exports, I think this issue might be better addressed as providing options in tools/identifier_download.cfm for replacing the Issuer's full name with this shorter label name or display name or whatever. I would definitely NOT want 'Issued by' removed by default! 

I have thought that a ```display``` name type might be useful and this is definitely one such case

**Comment by campmlc** [comment]
Request an in person meeting to discuss..  This is a broader issue related to using agent names as identifiers which is greatly impacting workflows and tools.

**Comment by mkoo** [comment]
I am going to schedule a meeting for Thu Nov 9th either at 9 am PT/ 10 am MT (before the Taxonomy Committee meeting) or between 12-3 PT
 Othe
Let me know your availability but this is the soonest I can meet up! Otherwise we can take the Arctos tea time 11/13 at 1130 PT

**Comment by mkoo** [comment]
scheduled. See Arctos calendar for Thu at 9 am PT/ 10 am MT for zoom details.

**Comment by mkoo** [comment]
> scheduled. See Arctos calendar for Thu at 9 am PT/ 10 am MT for zoom details.

The Arctos calendar event now has a zoom link so anyone can join. Reviewing the initial issue, this seems pretty straightforward so let's talk about the initial issue and what works (this wont be a discussion about anything else)
thanks!

**Comment by dustymc** [comment]
Per meeting: add issuedby column for CustomID to part_data_download
