### ISSUE TITLE
Feature Request - Single search interface for all Code Tables

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#6920]
**The challenge**
To search for any value in any Code Table, one must know WHICH Code Table (CT) to search on, which is not easy if you cant remember the table! (Especially if you cannot remember the specific term and only have the definition in mind)

**The proposal**
A new search interface where we can search for a term or phrase in the values or definition (or alt name) in all CT's at once. The results would link to all possible solutions, maybe ordered by whether search parameter matches the value, alt name or something in the definition.

This can be a public query form with the results leading to editable tables as determined by the usual user permissions

**Priority**
This will be a great function for new users and migrating collections but also useful for the CT administrators and committee, so a priority but not urgent

**Comment by mkoo** [comment]
BTW, the search all box can go on the top of this page- Code Table documentation:
https://arctos.database.museum/info/ctDocumentation.cfm

**Comment by dustymc** [comment]
@mkoo this is ugly and I feel a little dirty for having written it this way but it's also super-cool (and I think I can get away with it since it can only ever involve a few thousand rows), let's call it a primitive preview of https://github.com/ArctosDB/arctos/discussions/6524 - which I ***need*** before I do this sort of thing again....

Break it ASAP, please. 

https://arctos-test.tacc.utexas.edu/info/ctDocumentation.cfm

<img width="563" alt="Screenshot 2023-11-17 at 13 29 18" src="https://github.com/ArctosDB/arctos/assets/5720791/47ee8cb2-29ed-4953-b0a4-6bf1d92cb286">

**Comment by Jegelewicz** [comment]
cool

![image](https://github.com/ArctosDB/arctos/assets/5725767/ceb3e188-4f4f-4864-8e66-91bd12e37af1)

but I can also foresee wanting to get ONLY terms with the searched text.

**Comment by Jegelewicz** [comment]
because for some things, the list can get long

![image](https://github.com/ArctosDB/arctos/assets/5725767/b4d2c17a-7ce8-44fe-a594-e71ef6a32f4b)

and if all I care about is the actual term, still hard to find?

**Comment by dustymc** [comment]
>foresee wanting to get ONLY t

Sounds like the start of functional requirements for https://github.com/ArctosDB/arctos/discussions/6524

(You'll get what you get and don't have a fit as long as I'm magicking SQL out of our messy DDL!)

**Comment by mkoo** [comment]
i love it-- even the long results lists!
thanks!
