### ISSUE TITLE
add "Media" as a tag type

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ArctosDB/arctos#695]
```
We need to add media as a tag type so that you can associate media such as 
field notes with other related media such as a photograph on a page. This is 
needed for the MVZ CLIR grant, among other things, so I have labeled it with 
high priority.
```

Original issue reported on code.google.com by `carla...@gmail.com` on 7 Jul 2014 at 6:55

**Comment by dustymc** [comment]
> Would it be possible to 
write a trigger which pulls the media-PK from the TAGing data, and inserts it 
as a row in media relationships with a relationship_type of "TAGed in document"?

I like this, I think (mostly because it makes development easy and behavior consistent - and the string after the last space has to be a table name, but that's just details). 

Functionally this would change the nature of TAGs - now they're "way better than some arbitrary remarks field, but I can't be bothered with real relationships." This would make them "way to create real relationships (and some other stuff)." Essentially TAGs become a create-and-refine tool instead of the separate thing that sort of hangs awkwardly off the side of the model which they are now.

Is that somewhere we want to go?

If so,

alter table tag add media_id foreign key....

which leaves us with...

desc tag
....tagstuff...
 COLLECTION_OBJECT_ID							    NUMBER
 COLLECTING_EVENT_ID							    NUMBER
 LOCALITY_ID								    NUMBER
 AGENT_ID								    NUMBER
MEDIA_ID...


and then a new trigger, onChange to TAG when...

**new MEDIA_ID then auto-insert media_relationship:**
*{document_you're_tagging} something-something MEDIA {media you pick in the tagger-tool}*

**new COLLECTION_OBJECT_ID then auto-insert media_relationship:**
*{document_you're_tagging} something-something CATALOGED_ITEM {specimen you pick in the tagger=tool}*

**new COLLECTING_EVENT_ID then auto-insert media_relationship:**
*{document_you're_tagging} something-something COLLECTING_EVENT {event you pick in the tagger=tool}*

**new  AGENT_ID then auto-insert media_relationship:**
*{document_you're_tagging} something-something  AGENT {agent you pick in the tagger=tool}*

There are 15 tagged Localities. Can we get rid of them as part of this? You know it doesn't reference tomorrow, that might later be useful information, such data is inherent to events and impossible with Localities, and there's absolutely no reason to throw data away or make linking to place-and-maybe-time twice as complicated and half as findable as it could be.

"TAGged in document" is, I believe, exactly backwards. The "document" (which can be any JPG - no reason to get overly specific here) originates the tag, and should be the subject of the relationship "sentence." To use a slightly less awkward example, an Agent isn't "TAGged in media," but the Media "shows agent."

Maybe we don't need new vocabulary at all. (All relationships are currently functionally identical - "some string TABLENAME" does precisely the same thing as "opposite of that other thing TABLENAME.") If there a useful difference between "shows **AGENT**" and "something about TAGs **AGENT**"?

I need:
* Approval (or refinement) of the model change and trigger
* vocabulary
* approval to remove Locality (and probably someone to repoint those 15 to events)

**Comment by dustymc** [comment]
If this is rejected, reopen #503
