### ISSUE TITLE
updating Media URLs

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#6962]
If I can tag on a related question...
@dustymc   We are upgrading much of our media over the next few months which entails deleting the existing media and replacing it.  I'm keeping a csv of all the deleted media IDs including thumbnails.  I haven't been able to delete them myself (although Arctos tells me I should).  Do I periodically send the csv to you through GitHub or can you find unused media and delete them as it seems you've done in this issue?

_Originally posted by @sharpphyl in https://github.com/ArctosDB/arctos/issues/6954#issuecomment-1805859624_

**Comment by dustymc** [comment]
>deleting the existing media

Maybe local storage would be better for that, we should chat. @mkoo we're going to need guidance here.

>deleted media IDs 

Deleting media just removes them - I won't be able to do anything with them once the object they represent is gone. 

That will however break all existing links, which I hope there's a plan to deal with?!

>find unused media and delete them

I can delete (if I have the URI or bucket and filename), but it's a fairly painful process. No problem if you've accidentally uploaded a picture of your credit card, but this is meant to be archival storage and this sort of use case has not been considered.

>delete them as it seems you've done in this issue

That is not what https://github.com/ArctosDB/arctos/issues/6954 proposes, at all!!!

**Comment by mkoo** [comment]
@sharpphyl Hi Phyllis, trying to understand the request here. It sounds like you are moving digital media so there will be a new URL or path for the media (including thumbnails?!). So is this a simply replacement task? Or is this more extensive? Can you email me a time for a quick chat to clear this up? It will be likely a lot faster than messages back and forth! Thanks

**Comment by genevieve-anderegg** [comment]
Phyllis can give more details, but basically we are updating the images of some of our marine invert specimens. This includes taking pictures of various views of a specimen that were separate images and putting them together into nice plates. We would like to have those new images be associated with the record to replace the old ones.

**Comment by mkoo** [comment]
OK makes sense -- so @dustymc can DMNS provide you with a CSV for replacing URIs?
@genevieve-anderegg @sharpphyl it sounds like you do not want to to delete the media records since the metadata remains unchanged but just need to update the URLs to the your new storage source. And you've been tracking this in a spreadsheet so the next step should be simple

So adjusting the current bulkloader (https://arctos.database.museum/tools/BulkloadMedia.cfm?action=ld) maybe something like this? 

Media_id
old_media_uri 
old_preview_uri
new_media_uri 
new_preview_uri

Does that work @dustymc ?

**Comment by dustymc** [comment]
>Does that work

Yes and no.

It's nice because it preserves links/URIs (most of the reason Media works like it does), if the new carries about the same information as the old (not clear??).

It's horrid because it requires me to delete archival media from an environment that's REALLY not supportive of deletion.

Less-evil might be to just orphan the "old" files?? Someone would still have to pay for the storage, but that's probably trivial. Seems like we need more - documentation? something - going forward, or maybe a more disposable (=cheaper) sort of media storage, or different expectations from one or all of us, or ????????? 

Least-evil from my perhaps-very-lost perspective would just be to add, leaving the old (presumably still useful, perhaps used in research and etc., but not as pretty??) media-with-files intact.

In any case, my concerns mostly involve the original title (including the implied bits!), deleting media from (archival!) storage.

An idea of scope might be useful as well - is this 3 blurry pictures or 20 petabytes of data and a brazillion records or ?? - somehow the ends of that spectrum feel different.

**Comment by Jegelewicz** [comment]
> just be to add, leaving the old (presumably still useful, perhaps used in research and etc., but not as pretty??) media-with-files intact.

YES!!! We are museums - DO NOT throw that away!!!!

**Comment by genevieve-anderegg** [comment]
> Seems like we need more - documentation? something - going forward, or maybe a more disposable (=cheaper) sort of media storage, or different expectations from one or all of us, or ?????????

Agreed. I'll talk with the others after Thanksgiving, but it would be nice to have these new higher-quality pictures be at the forefront on the record while the older ones are less prominent. Perhaps still maintained, but not linked to the catalog record specifically? For clarification, the old and new media actually have the same exact pictures of the specimens, but the new media compiles them together in a standardized plate that is our preferred standard.

**Comment by sharpphyl** [comment]
We are replacing media of several types.  Typically, as Genna described, we are consolidating multiple images into one plate so that the dorsal and ventral (and sometimes lateral) views are shown together.  Here is an example of this.  

Before
<img width="587" alt="Screenshot 2023-11-26 at 3 30 21 PM" src="https://github.com/ArctosDB/arctos/assets/15368365/0b5b6953-206c-4fe3-b36d-87b9197eb7a8">

After
<img width="337" alt="Screenshot 2023-11-26 at 3 57 40 PM" src="https://github.com/ArctosDB/arctos/assets/15368365/91309cec-1d8b-4e85-bc46-5e25805eb913">

Everytime I delete an image, I get this warning: -you deleted media 10588215-
The files
https://web.corral.tacc.utexas.edu/arctos-s3/sharpphyl/2018-11-20/ZC_29288_Boonea_impressa_ventral.jpg and https://web.corral.tacc.utexas.edu/arctos-s3/sharpphyl/2018-11-20/tn/tn_ZC_29288_Boonea_impressa_ventral.jpg are unaffected. You should delete them if you don't need them around anymore.

Sure enough, those URLs are still active, just not linked to the catalog record.

In other cases, we have replaced inaccurate images with better ones; added species, catalog number and DMNS  copyright; corrected identifications (documented in the catalog record) and misspellings; and updated taxa etc.

I'm keeping a cvs that lists the media identifier (e.g. 10588215 above) and the URLs.

We've replaced hundreds of images and have hundreds more to go. There is nothing in the deleted images that hasn't been retained in the replacement.  There is no value in archiving them or keeping them around unless it's just cheaper and easier to do that.  If so, should the warning be modified?  I'm happy to delete the URLs but can find no way to do that and Dusty's comment ("it's a fairly painful process") is a bit ominous.

Hope this explains why I asked the initial question about deleting media URLs.

**Comment by Jegelewicz** [comment]
@sharpphyl when images are loaded to TACC - they are expected to be "permanent". I don't see any reason for you guys to waste a bunch of time removing images from catalog records. Just add the new images! TACC's mission is to make data available - deleting things violates that mission. Id anyone has used the url for any of the media you want to "delete" they will get 404 errors - not what we want! Just add new images and save yourself a lot of time and ensure that any usage of those "old" images remains linked and available for future users.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I wonder if it would be possible/useful to have some kind of rank added to media so that the best images show up at the top?

**Comment by dustymc** [comment]
I don't think there are any action items here, tabling.
