### ISSUE TITLE
Bulkload carried coordinates to no-locality records

### ISSUE THREAD

**Issue by adhornsby** [ArctosDB/arctos#6966]
I bulkloaded a set of records around 14 Oct 2023 which contained a mix of specimens with and without coordinates.  I allowed Arctos to auto-increment the catalog numbers.

It appears that, as Arctos assigned the GUIDs, it carried the coordinates into any records lacking them from whatever proceeded in the GUID order.  I attached a file that shows what I loaded vs. what's in Arctos now, sorted by GUID so you can see this easily.  This particular affected set is UMZM:Mamm:22907 through 22983.

That said... UMZM:Mamm:22984 & beyond were individually entered and also have some bogus coordinates that I haven't been able to discern an obvious pattern from.

[LatLong_comparison_summary.xlsx](https://github.com/ArctosDB/arctos/files/13343768/LatLong_comparison_summary.xlsx)

**Comment by dustymc** [comment]
There's a trigger which saves "old" records as they're deleted (which can be from successfully loading or someone deleting them). I pulled all UMZM:Mamm records since the bulkloader update into https://docs.google.com/spreadsheets/d/1K-8xOqTzg4qZxAWSGdH6S1CdQNheDv9zS1MIl4eFsYc/edit#gid=650891992, and anyone should be able to view it. I checked a few records (search for an identifier) and I can't find any discrepancies; please let me know if you do.

It is not impossible that the entry form is somehow doing something unexpected, but I can't see what that might be either.

Please let me know if you see anything in these data!

**Comment by dustymc** [comment]
Thanks @Jegelewicz.

**Comment by dustymc** [comment]
Data:

[temp_loc_carryover.csv.zip](https://github.com/ArctosDB/arctos/files/13354245/temp_loc_carryover.csv.zip)


All of these seem to be the same pattern, coordinates only, no metadata, which I'm fairly sure means they're all of the same source.

I'll update all of these localities to NULL (dec_lat,dec_long) in a bit, unless there's something in here to suggest that's not the proper course of action. Timely feedback greatly appreciated, lemme know if you need some other data.

**Comment by adhornsby** [comment]
Thanks @dusty, I'll take a look and get back to you by the end of tomorrow.
Did I trigger this bug by doing something wrong, or was it a fully Arctos-end problem?  Just need to know if I should adjust my behavior.

**Comment by dustymc** [comment]
Nope, all me, no you - thanks!

**Comment by dustymc** [comment]
Fixed the loader, adjusted the constraint, removed the errant coordinates.
