### ISSUE TITLE
multiple-record annotations

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ArctosDB/arctos#704]
```
Figure out how to manage multiple-record annotations in the annotations table, 
not just as email
```

Original issue reported on code.google.com by `dust...@gmail.com` on 10 Sep 2014 at 6:21

**Comment by dustymc** [comment]
See also #526.

Proposal: File all specimen-related reports to Annotations, where they become "part of the specimen record" and remain accessible everyone.

Situation and problems: Users find a number of specimen records (many thousand isn't uncommon) and report an issue. How should we deal with that?

- do we need to group related annotations? (probably?)
- do we need to distinguish between "this specimen...." and "this specimen as part of a single report"? (probably? Group annotations less specific/possibility of being misguided)
- how should the curatorial tools work?
- can we extend this as a service, and if we do will GBIF/VertNet/etc., use it? (sure, not a lot of luck in the past)

Somewhat related, how can we encourage people to use the "report bad data" button (which delivers to collection's contacts) instead of the "report a bug" button (which delivers to admin)?

Flagging high-priority; without this we have no permanent record of multi-specimen annotations.

**Comment by dustymc** [comment]
v7.2.4
