### ISSUE TITLE
specimen detail: show implied "co-parasite" relationships

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ArctosDB/arctos#707]
```
What steps will reproduce the problem?
1. A parasite of B
2. C parasite of B
3. A<--- no relationship -->C

On specimen detail, figure out and display the A<-->C relationship 

```

Original issue reported on code.google.com by `dust...@gmail.com` on 23 Sep 2014 at 6:19

**Comment by dustymc** [comment]
1) Should these data be searchable? If so, perhaps we should periodically script in relationships for them rather than doing something in display.

2) What derived relationships should we create (or fake in display)? Obvious possibilities:

* offspring of -->  sibling of 
* parasite of -->co-parasite with (new relationship)

@campmlc

**Comment by dustymc** [comment]
This seems too important to abandon, but I can't proceed on my own.

Finding the processors to do this dynamically seems unlikely.

Scripting in 'derived' relationships should be possible and affordable, but it's the system asserting data. I'm not going there until everyone's happily on-board (and maybe there's some documentation).

Perhaps a report which allows users to load or ignore derived relationships is more appropriate?

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/4101
