### ISSUE TITLE
verbatim agents not showing up as collectors in 'summarize by'

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#7135]
**Describe the bug**

Did a search on family Acrididae, collection = UAM:Ento

did a summarize results and chose to summarize by year and by collectors

The summary results had a bunch of rows with no collectors which I thought odd. Particularly odd was a row from 2023 with 36 specimens with no collectors. I inspected those and here's one: https://arctos.database.museum/guid/UAM:Ento:492028

The record has a collector but it's a verbatim agent. I would like verbatim agents to be summarized like regular collector agents so we can do these summaries. Otherwise I will have to stop using verbatim agents to avoid problems like this.

See data

[catalog_record_summary(57).csv](https://github.com/ArctosDB/arctos/files/13687570/catalog_record_summary.57.csv)

**Expected behavior**
Verbatim agents and regular agents should appear in all results and summaries as if they were the same thing. Those interested in the data do not care that some are verbatim and some aren't - that is a back-end distinction of no interest to users.

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.
medium

**Comment by DerekSikes** [comment]
Upon further examination I see that the verbatim agent for https://arctos.database.museum/guid/UAM:Ento:492028

and presumably the other 35 associated records lack 'method' for the verbatim agent. I will try to fill that in with 'collector' and see what happens. Not sure how this lack of data happened - maybe 'method' should be required in order to use verbatim agents?

**Comment by DerekSikes** [comment]
Nope. 2019 has 2 records that have no collectors and I see they also have verbatim agents but in that case they have 'method' filled in as 'collector'.

Also, what is the meaning of this that appears near the verbatim agent:
"Agents acting only in method-specified role. Please use the "comment or report bad data" link if you have more information. "
on these records, eg: https://arctos.database.museum/guid/UAM:Ento:406119

**Comment by DerekSikes** [comment]
Also, seems the manage agents tool (for the cat records results list) does not allow one to manage verbatim agents. Thus, for me to add 'collector' to these 36 records that lack 'method' for this verbatim agent will require lots of clicking.

**Comment by DerekSikes** [comment]
Seems verbatim collectors are not appearing in the catalog records results as agents either, even when they have method 'collector'. Until this is fixed (and I really don't understand how it could have been implemented to begin with without tending to these obvious needs) I will no longer use verbatim agents. Collector is critical and basic data to have!

This screenshot shows the lack of collectors for two records that have verbatim collectors.
![no collectors](https://github.com/ArctosDB/arctos/assets/9099827/a077fcf8-b20d-4cbf-844d-fc57e03864dd)

**Comment by Jegelewicz** [comment]
@ArctosDB/agents-committee

**Comment by DerekSikes** [comment]
update, for the 36 records from 2023 with no collector.... I deleted all the verbatim collectors and added the collector as an agent for those. I'll no longer use verbatim collectors and will work to delete all & turn into actual agents.

**Comment by mkoo** [comment]
HI @DerekSikes , this is the right conclusion!
I've also gone through the tasks of [converting our verbatim agents to high quality agents and the last time I wrote it down in this doc](https://docs.google.com/document/d/1UrJkEa_gvO6krsBpoqo30FwAng1XdRiuk3_hEuZRBQY/edit?usp=sharing)

This will be updated in the handbook soon. But feel free to let me know if you have any tips too.

As for the original issue you filed, maybe we should consider some tips to explain that not all is visible?!

**Comment by DerekSikes** [comment]
This is insane. You're actually proposing that we pay lab techs to undo massive damage to our data caused by database design changes? Why not have those responsible for making the original changes undo them? We are talking about hundreds of person hours costing many thousands of dollars per collection.

**Comment by DerekSikes** [comment]
Note also that verbatim collectors are not being mapped to collector agents in GBIF: https://www.gbif.org/occurrence/1145899608 they appear as cryptic 'verbatim agent=" in something called 'Dynamic properties ' with no mention they are collectors

**Comment by mkoo** [comment]
> This is insane. You're actually proposing that we pay lab techs to undo massive damage to our data caused by database design changes? Why not have those responsible for making the original changes undo them? We are talking about hundreds of person hours costing many thousands of dollars per collection.

Umm, what are you referring to? I made no such suggestion. did I link to something else? I just shared my steps to clean up MVZ verbatim agents as needed. It's what you said you were going to do. These are not database structure changes -- these are usually legacy data entry issues (typos, inconsistent names etc). Although I definitely agree we need a smoother workflow for these steps which I hope we can get some suggestions.

Of course there's another alternative but this is not the forum to discuss. Should probably go to the Issues or AWG meetings

**Comment by DerekSikes** [comment]
My memory is fuzzy, but I recall that at least in my collection's data we had virtually no verbatim agents - all were real agents. Then a change was made to convert real agents (low quality) to verbatim agents. Now we have hundreds, maybe thousands of verbatim agents. I'd like all my verbatim agents to become actual agents, regardless of how low quality they are. That should be possible to do with some backend magic rather than costly technician time handling one agent at a time.

**Comment by camwebb** [comment]
As a temporary solution, one can use the user SQL to summarize as requested above:

```SQL
SELECT
  year, concat_ws(', ', collectors, attributes.attribute_value) as coll, count(*)
FROM flat
LEFT JOIN attributes
ON flat.collection_object_id = attributes.collection_object_id AND
  attribute_type = 'verbatim agent'
WHERE guid ~ 'UAM:Ento' AND
  year in (2001,2002,2003)  -- or something
GROUP BY year, coll
ORDER BY year, coll;
```

**Comment by DerekSikes** [comment]
Clearly collectors were alive the year they were collecting so I'd like all my verbatim collector agents to become real agents with status = alive on date = year of one of their collections.

**Comment by mkoo** [comment]
Agreed, that makes sense. We're going to work on that and try to make it easy transition here. Probably will contact you directly next

**Comment by dshorthouse** [comment]
> And, of course, when this is done they should be linked to their records as collectors and their verbatim agents deleted.

I of course have no idea how your backend and frontend interact with one another, but wouldn't you want to preserve verbatim agents as a version of record to backtrace issues just as is being discussed here?

**Comment by Jegelewicz** [comment]
@dshorthouse when the actual agent name and the verbatim agent match, it seems like unnecessary duplication. Also, there is a backstory here because we recently completed an experiment to remove "no data" agents from our formal agent table to a separate verbatim agent (strings only) attribute. We are re-thinking that and looking to reinstate some of the strings-only agents.

**Comment by dshorthouse** [comment]
@Jegelewicz Gotcha. Sounds to me like the rules for what gets an entry in the formal agent table (and subsequent rendering) dissolved into the more concrete expectation for what is a verbatim agent. Both are string-based. However, a verbatim agent is meaningless without its context whereas an entry as a formal agent may bear its own meaning provided there are other attributes. At the risk of being an unhelpful interloper, I'd ask if verbatim agents are actually verbatim (i.e. a single field, meant to contain all manner of orthographic/linguistic entries, inclusive of an apparent team of agents, rendered only as a reference to their particular context) and whether formal agents are actually formal, perhaps by inclusion of a visual tag/icon on the front-end. If the rules, lines or intent have blurred between the two concepts, I'd rename one of them plus introduce some iconography or other in an attempt to help users understand the difference. The challenge here, I suspect, comes with search. The lack of differentiation in search results between the two has users asking, "WTF?" And so, perhaps it's worth asking oneself if a user is searching for an agent or if they are searching for materials on which an agent string might be mentioned. These are two very different use cases, but it's tempting to combine them into one.

**Comment by Jegelewicz** [comment]
@dshorthouse you said it all. People and organizations are sometimes referred to in cryptic ways, especially on legacy museum records (labels, catalogs, etc.). The original use for verbatim agent (a free-text attribute, that does also carry the following: determiner, date, method, remark) was to record what is being transcribed, whether an actual agent was created to match that or not, has been up to the person doing the transcription (if my verbatim agent "TJM" is known to be Teresa J. Mayfield-Meyer, then creating and using that agent makes sense, when it isn't known exactly who "TJM" refers to, it really doesn't, but for a long many years, it happened anyway - leaving our agent table full of these essentially "unknown" agents that carry nothing but a string (or maybe a few strings that are still uninformative). As I try to help people migrate data into Arctos, attempting to determine if their Tim J Meyer might also be the existing "TJM" based solely upon whatever had been associated with TJM became untenable and infuriating. So, we attempted to remove TJM (and a lot of other agents that had nothing but name strings associated with them) from the formal agent table. The result has been upset collection data managers and really no relief for me because we could only do this for the namestring only agents participating in collector and preparator roles (there are a lot who are also identification determiners, determiners of other things in Arctos, and participants in transactions). I have now come around to a return to the old ways and to making my job less onerous by just adding in Agents when there is no exact match. This will most certainly mean we have duplicate agents, but we have a merge process, so when they are discovered, it is easy enough to merge them. It will also mean that some agents are actually more than one person. When one of these people can be disambiguated, we have ways to help do that too.

> if a user is searching for an agent or if they are searching for materials on which an agent string might be mentioned. These are two very different use cases, but it's tempting to combine them into one.

We were trying to facilitate this as the current search functions allow for searching across both, but the results may seem strange depending upon what you have selected to show there and as this thread demonstrates it is not perfect for all situations.

I agree that we should make these two things clearly separate but also provide some method for people to search across both when it makes sense for them to do so. I think we will also attempt to provide our agents with some sort of data quality ranking to help those who are using them in data entry and search know if the name they are using represents a known agent or might be a bit vague due to lack of disambiguating information.

In the end though, the thing that really makes me sad is that we are not the only people doing this. Arctos is a community, so we are combining the efforts of all of the members to make better agents. Nearly all of the the other CMS are stand-alone and EVERY SINGLE COLLECTION is attempting to maintain their own separate list of known agents. What an expensive and absolute waste of resources when many of the known agents are participants in more than one collection's activities. After Taxonomy, I think that some sort of "agent management" infrastructure that the entire biodiversity community could contribute to would be an excellent way to co-create and ease the burden of managing data for everyone involved in the process.

**Comment by dshorthouse** [comment]
> I agree that we should make these two things clearly separate but also provide some method for people to search across both when it makes sense for them to do so.

Indeed. What I'd do, should it be helpful, is to actually separate out the search results into two distinct sections or tabs: (1) content definitively linked to a searched & known agent and, (2) here be dragons, you mileage may vary. To be sure, there will be partial overlap between the two (formal agents linked to content still have verbatim agent entries there), but limit the "here be dragons" to their own unique subset.

**Comment by dustymc** [comment]
>Clearly collectors were alive the year they were collecting 

I very strongly oppose this. The inference is always going to be unavoidably available from the structure of the data itself. Elevating an inference to look like data is just a recipe for disaster: someone WILL discover that the collecting date is wrong, fix it, skip the agent (normalization....), and then all of the data will be slightly worse and more cryptic than it needs to be. If we're going to abandon experiments in less-structured agents then fine, but I don't think there's any remotely defensible position from which we can do that and retain the "requirements" for additional data. Such information clearly doesn't exist and pretending that it does cannot be useful. I can see no need to make this more complicated for ourselves, nor to make the data less understandable to future users.

>preserve verbatim agents 

I think we mostly have to - I use them when duplicate agents are merged. (Collections are free to remove that if they don't care, bulk tools are available.)

>actual agent name and the verbatim agent match

Still seems like something the collections can decide for themselves if we're abandoning the experiment, but "don't try to pull info from strings, they clearly can't carry it" is the essence of the problem we've been trying to solve. The label says "John Doe" so agent John Doe is selected - never mind that the agent was centuries dead when the event took place.... We've been trying to move towards data in which multiple ``John Doe`` are easily distinguished by their metadata (we do try to acknowledge reality from time to time!). I think this issue unavoidably leads in a direction where there might be 50 ``John Doe`` agents, perhaps all of whom are doing about the same things in about the same places at about the same times and none of whom carries any disambiguating information. (And I'm not suggesting that that's necessarily *bad* - or avoidable - but it's definitely a change of direction, and one which we should make purposefully; nobody should just find themselves in the aforementioned situation in a couple years!)

>Both are string-based.

Nope. Agents are data objects which can carry other data (dates, relationships, etc.) 'Verbatim agents' can carry only minimal metadata and a pkey/fkey relationship to a catalog record. (And the idea was that agents who don't have any of the information which Agents can carry don't need the complexity of the structure.)

>verbatim agent is meaningless without its context

A verbatim agent can't exist without context (that pkey/fkey relationship) - it MUST be attached to a catalog record. An Agent however can just be "John Doe" - all of the metadata/usage is optional. (And if we're going where I think we are, perhaps we could agree to periodically purge that - a bunch of unused agents indefinitely hanging out adding to the clutter surely can't be a good thing??)

>unhelpful interloper,

Absolutely not! Bigger viewports are kinda-always useful/welcome, one with some focus especially so. Thanks for showing up!

>The challenge here, I suspect, comes with search. 

Within Arctos, that's easy - I think the complaints have mostly involved presentation/search results. (But I'm clearly lost somewhere in here - it's easy to make real Agents if there's any sort of data, data-free entities are clearly something different, but somehow we want to treat them the same, only differently, and ??????? IDK....)

>leaving our agent table full of these essentially "unknown" agents ..... As I try to help people migrate 

I think that's the biggest problem. In the current model, which I've always assumed was aimed at disambiguation, we can have only one TJM. (Every Agent has one preferred name, it wears a unique key, plus there are some formatting rules which would require that to be ``T. J. M.`` lest we end up with 20 whitespace-variations.) I think this issue is implicitly suggesting we drop even that, so we'll end up with 20 'TJM' agents, then when the next collection comes in  we'll increment to 21 (they don't have any independent data, none of the existing have any independent data, what else could they do?! https://xkcd.com/927/). I think that means that we will never be able to be even sorta-sure that we're giving https://arctos.database.museum/agent/21300608 proper attribution for her work. (Which seems like an awful thing to me, but I'm not steeering, just trying to make sure nobody is surprised by this....)

>less onerous by just adding in Agents when there is no exact match.

We need to make a choice here (probably expressed in the form of a Best Practices doc, because I don't think there are many other possibilities in where this is going): Is having one clearly-overloaded TJM (Teresa, Tim, and who knows what else in there) or a bunch of TJM (several of which probably refer to Teresa) Agents less-evil? (Something like asking if one would like to be kicked in the left or right shin - maybe this is a full surrender and we don't need further guidance after all??)

>some sort of "agent management" infrastructure

We do have that (and would 100% buy into something deeper, at least from my perspective). https://arctos.database.museum/orcid/0000-0002-1970-7044 for example - a little nifty UI that I threw up under the expectations that we are striving for information-rich Agents to whom we can give proper attribution. There's no reason 15 of those 21 aforementioned ``TJM`` agents can't wear that identifier in the model I think this is going towards - maybe external identifiers could still do *something*,  but I don't think they'd be able to do quite what they do now. (And maybe I'm just wildly lost, I'll add a request for discussion tag - and perhaps someone can invite @dshorthouse if that happens!)

>separate out the search results into two distinct sections or tabs: (1) content definitively linked to a searched & known agent and, (2) here be dragons

That's what we've done. This Issue is (I think) a request to merge them (in ways the data can't quite support, perhaps).

>partial overlap between the two

That's expected. Traditionally we've done cleanup at the worst possible time - once the Agents have been separated from the data and made unique, before anything is migrated, where any possible context is, at best, difficult to find. The verbatim agent model allows us to just load ``TJM`` with the 'specimen data,' and then - in the context of all available data, and without having made any messes capable of escaping the context of the catalog record - to decide if that particular ``TJM`` is in fact https://arctos.database.museum/orcid/0000-0002-1970-7044 (or not, TJM can hang around for as long as necessary - perhaps waiting on additional resources/support). I believe the proposed change would unavoidably force us back to out-of-context Agent creation.

**Comment by Jegelewicz** [comment]
> so we'll end up with 20 'TJM' agents, then when the next collection comes in we'll increment to 21 (they don't have any independent data, none of the existing have any independent data, what else could they do?

They will (and always have) just use the (only existing) TJM because literally nobody investigates an agent that matches - they just happily use it!

**Comment by dustymc** [comment]
> use the (only existing) TJM

I am fine with that, and clearly it's been working for some time. However, there are (obviously) multiple TJMs out there, and if we can find a way to allow that without making bigger or more important messes then I think we should. I can't quite see how one or the other is *better* but they're absolutely functionally *different*. My goal at this point is to try to understand where "we" want to be, and hopefully keep anyone from being too surprised when we find ourselves there. I am not trying to influence the destination.

https://handbook.arctosdb.org/documentation/agent.html#identical-agent-names

**Comment by dustymc** [comment]
Merge-->https://github.com/ArctosDB/arctos/issues/7326
