### ISSUE TITLE
blocked IP

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#7187]
A family member of a donor indicated she was blocked from accessing the catalog record of the object her brother donated.

I've had this happen to a number of Alaskans from the general population trying to look at our records. Is there something going on with our IP addresses up here to cause concern? It's troubling when tribal citizens are being told they're blocked...

Please unblock:
![image0](https://github.com/ArctosDB/arctos/assets/17605945/2ddc7978-2e6f-4588-8eeb-92cfd04ff361)

**Comment by dustymc** [comment]
Released, should clear within 10 minutes.

That IP is in CA, and was blocked because it shares space with a datacenter in MO, which was blocked to protect Arctos. I always try to balance accessibility and safety, but the resources given our security team demand that any errors in that judgement are biased towards the security of the system. 

https://github.com/ArctosDB/internal/issues/290 is a related request for resources.

**Comment by AJLinn** [comment]
Thanks for the explanation Dusty. I understand the security concerns - it's hard to explain to novices when they're blocked and then never try again! 

Guess it's another point to add to our FAQ page on my museum website.

**Comment by dustymc** [comment]
>add to our FAQ page on my museum website

And maybe somewhere on https://arctosdb.org/ @mkoo ?

FWIW I'll always do whatever I can to get a human access. That's not always easy or even possible, but I'll always do whatever I can, and if I had more resources I'd try to put them to good use. Please let me know if anyone has any clever ideas for making that more obvious.
