### ISSUE TITLE
Feature Request - make it so commas don't break this form

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#7188]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_

![image](https://github.com/ArctosDB/arctos/assets/5725767/05374fdf-de1a-4ddb-877e-169aa8e0f299)

I don't know what breaks, and I haven't noticed anything, but that warning was enough to make me file this issue...

**Describe what you're trying to accomplish** 
_A clear and concise overview of the goals; why are you asking for this?_

A LOT of organization agent names include commas, so disallowing commas in issued by is no bueno.

**Describe the solution you'd like**
_How might we accomplish your goals?_

Fix this to allow commas, or do something in agents so that commas cannot be used (never gonna happen?).

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

**Additional context**
_Add any other context or screenshots about the feature request here._

this isn't helpful in getting issued-by buy-in

**Priority**
_Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair._

**Comment by dustymc** [comment]
I don't think the implications are quite as drastic as laid out - the absolute worse case scenario is just to download everything, then filter. Wild guess, most users won't want to filter by comma-containing issuers anyway, in which case there's no affect at all. (I'll try to clarify that on the form.)

I'm removing the wildfire label, I don't think this has any potential to spread, nor even to do much damage locally.

I can drop the ability to choose multiple issuedby, thereby removing the "data characters are also delimiters" situation (because there are no delimiters if there's only one possible value). This doesn't seem great when there are lots of things not affected by the situation, and an easy workaround for things that are involved.

I can do something expensive and likely fragile (eg replace the natural delimiter with something else - which would probably find a way to not work, would break indexes, might pollute downloads, etc.). Don't think there's any way to justify that for this, but please let me know if I'm somehow wildly misreading the situation.

Not sure what else is realistic - just remove the commas from preferred name if you need the functionality....

I'll update the suggestion with a link to this Issue for next release.

<img width="1606" alt="Screenshot 2024-01-08 at 08 39 18" src="https://github.com/ArctosDB/arctos/assets/5720791/d437649e-95ae-4fa2-8049-beee227d9b1c">

**Comment by Jegelewicz** [comment]
OK - I used this over the weekend and had no issues - I don't think there is actually a problem - I was just addressing the warning.
