### ISSUE TITLE
Advice needed for setting up MSB Arctos portal for LTER site

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#7330]
Hi all, we have been approached by members of our department to begin archiving genomic materials for a long-term ecological research program (LTER) associated with our university. This program has already provided funding for purchase of part of a cryotank to archive frozen samples collected since at least 2018 (the actual LTER collections date back to 1989).  Samples are currently plant leaf and root material, biocrust, and soil from long term plots. We also expect additional types of samples to be added, especially environmental and fungal metagenomic samples. Some of these may be archived with herbarium vouchers in our new MSB:Herb portal, but others will be separately collected, funded, and managed through the LTER program in collaboration with MSB Division of Genomic Resources. 
My thought was that this would best be a separate portal exclusively tied to LTER. As such, it would need to be able to accommodate many different record and sample types, including environmental samples of soil and water as well as DNA metabarcoding extractions linked to these.
Alternately, we currently have an pending request for a new MSB:Env portal that is on hold - but we need to archive plant material as well as environmental samples, and we need to specifically link all these to the LTER project and give the samples a catalog number that will refer to the LTER. I'm conflicted.
Has anyone else in the community worked with archiving for an LTER site, and if so, how have you handled it?

**Comment by andrew-hope** [comment]
Hi Mariel, the timing here is good. The Konza LTER is having conversations about similar things and I have been linked in to minimally be a part of the conversation.

I think funding for archive of whatever samples it may be is the big hurdle because NSF has not to this point indicated additional funding for specimen archive might be a possibility, at least in the current round of funding.

I would be happy to loop in the PI(s) of Konza but at this point, just sending out a reply.
Thanks for including me here.
Andrew


_____________________________________________

Andrew G. Hope (Assistant Professor), Division of Biology, 116 Ackert Hall, Kansas State University, Manhattan, KS 66506 USA; Office-111 Bushnell Hall; Lab-423 Ackert Hall.

Zoom - Personal Link - 337 911 1881(https://ksu.zoom.us/s/3379111881); Office-785-532-0155; Cell-785-477-1876; Website: https://www.k-state.edu/hopelab/; Scholar: https://scholar.google.com/citations?user=UicqcSQAAAAJ&hl=en<https://scholar.google.com/citations?user=UicqcSQAAAAJ&hl=en>
_____________________________________________

________________________________
From: Mariel Campbell ***@***.***>
Sent: Wednesday, January 24, 2024 6:16 PM
To: ArctosDB/arctos ***@***.***>
Cc: Andrew Hope ***@***.***>; Assign ***@***.***>
Subject: [ArctosDB/arctos] Advice needed for setting up MSB Arctos portal for LTER site (Issue #7330)


This email originated from outside of K-State.


Hi all, we have been approached by members of our department to begin archiving genomic materials for a long-term ecological research program (LTER) associated with our university. This program has already provided funding for purchase of part of a cryotank to archive frozen samples collected since at least 2018 (the actual LTER collections date back to 1989). Samples are currently plant leaf and root material, biocrust, and soil from long term plots. We also expect additional types of samples to be added, especially environmental and fungal metagenomic samples. Some of these may be archived with herbarium vouchers in our new MSB:Herb portal, but others will be separately collected, funded, and managed through the LTER program in collaboration with MSB Division of Genomic Resources.
My thought was that this would best be a separate portal exclusively tied to LTER. As such, it would need to be able to accommodate many different record and sample types, including environmental samples of soil and water as well as DNA metabarcoding extractions linked to these.
Alternately, we currently have an pending request for a new MSB:Env portal that is on hold - but we need to archive plant material as well as environmental samples, and we need to specifically link all these to the LTER project and give the samples a catalog number that will refer to the LTER. I'm conflicted.
Has anyone else in the community worked with archiving for an LTER site, and if so, how have you handled it?

**Comment by Jegelewicz** [comment]
It seems to me that a single collection would work. This is what OGL is doing and they have biofilms, cell cultures and other sample types. As we move to selection of parts and attributes by collection, the collection type isn't really all that important (as far as I can tell). If you will be managing these samples at MSB, maybe just add a collection where all of the LTER samples are cataloged. It could even be SEV:LTER but created under the MSB institution code. We can also talk more when the genomic collections get together. Maybe better ideas will come from more brains!

**Comment by andrew-hope** [comment]
Certainly, both Sev and Konza also have abundant mammal and parasite materials that are all in MSB:Mamm and KSB:Mamm, so there's a foundation of sorts to build on. Konza is also looking at environmental samples, including water, soil, inverts, etc...



_____________________________________________

Andrew G. Hope (Assistant Professor), Division of Biology, 116 Ackert Hall, Kansas State University, Manhattan, KS 66506 USA; Office-111 Bushnell Hall; Lab-423 Ackert Hall.

Zoom - Personal Link - 337 911 1881(https://ksu.zoom.us/s/3379111881); Office-785-532-0155; Cell-785-477-1876; Website: https://www.k-state.edu/hopelab/; Scholar: https://scholar.google.com/citations?user=UicqcSQAAAAJ&hl=en<https://scholar.google.com/citations?user=UicqcSQAAAAJ&hl=en>
_____________________________________________

________________________________

**Comment by campmlc** [comment]
I like the idea of an LTER collection code that could be used across different Arctos institutions, but I also wanted to indicate the collection would be part of MSB. So SEV:LTER is very clear, and then we could have another LTER for Konza -  but would that show up as part of MSB and KSB, respectively?

It will be great to figure this out collectively with KSB so we have a consistent path forward! NSF is now requiring specimen management plans, which hopefully will start a lot of similar conversations so we should think about developing a system that works.

**Comment by mkoo** [comment]
> I like the idea of an LTER collection code that could be used across different Arctos institutions, but I also wanted to indicate the collection would be part of MSB. So SEV:LTER is very clear, and then we could have another LTER for Konza - but would that show up as part of MSB and KSB, respectively?
> 
I agree that a collection code for LTER data would be a good consistent way to also handle the data types from LTER sites. What I am a tad concerned with is the longterm responsibilities as reflected in the institution code. If it is coming under the management (storage, loaning, longterm preservation etc) as well as administrative responsibilities of the Museum of Southwestern Biology then it should be simply MSB (or whichever institution has an agreement with the LTER site, e.g.,  MVZ or DMNS etc). It would still be distinguishable as MSB:LTER data regardless of Sevillata or Jornada Basin locallities (we have better ways to find things spatially anyway)

The MVZ have had experience with the challenges of getting field stations and reserves to operate as a museums (it's unfair to expect that of them in retrospect) and a better solution is to come up wtih an agreement that plays to the strengths and missions of the different institutions. So if MSB is accessioning samples from Sevillata that would be instantly understandable with a catalog record of MSB:LTER 

We should absolutely discuss broadly this new collection type of LTER since we would want to encourage more than one museum to take on such partnerships! And ecological data will present some unique situations too

**Comment by Jegelewicz** [comment]
@mkoo I strongly disagree - as my example of how the BELL operates - there is absolutely NO reason the GUID prefix has to reflect the institution code! I think @dustymc will agree?

**Comment by Jegelewicz** [comment]
Also, collection type has nothing to do with GUID prefix....

**Comment by mkoo** [comment]
Then I am lost to what is being requested here.... your example seems to support what I am suggesting actually....

**Comment by dustymc** [comment]
GUID_Prefix is arbitrary and attached to nothing else. It has some (semi-flexible) formatting rules and should involve a long-term (permanent) commitment (the important thing), otherwise it's just a string.

Collection Code will do nothing at all very soon - maybe next week, depending on what happens in a couple hours. (And then I'll probably advocate for removing it, since it obviously causes some confusion.)

**Comment by mkoo** [comment]
Yep-- and I'm not a fan of proliferating lots of collections with little oversight ore requiring lots of boutique search methods so there we are... let's talk in real time at the AWG!

**Comment by mkoo** [comment]
AWG discussed this with Mariel and she will take considerations to her institution for discussion since this is ultimately a MSB decision. OK to close? @campmlc can open a new issue once she's ready for a new collection
