### ISSUE TITLE
Add Map to Default profile

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#7361]
Currently the preset_default search option shows the Map category but does not display a Map:

![image](https://github.com/ArctosDB/arctos/assets/11336485/33e6995a-3e42-4979-8cd9-65f6a772d3a9)

I think this might look like something is broken to an outside user. I suggest we add the Map tool to this preset (or delete).

**Comment by dustymc** [comment]
>Map category but does not display a Map:

That's because someone insisted on moving Geography Shape Name (exact, case-sensitive) up to the Place segment, and I think removing it from the defaults. Maybe removing the spatial pane (I think the misleading name came along about the same time as the confusing rearrangement) up makes more sense, but IDK how that would play with other stuff. (Not sure I'm a fan of any pigeonholes at all.....)

Performance is also a consideration for adding things to default. Spatial queries are expensive, but IDK I can't break it at the moment with sorta-realistic things so maybe it's OK. https://github.com/ArctosDB/arctos/issues/5597 would be handy.

**Comment by ebraker** [comment]
I'm fine with the category going away as well...right now it just looks like it's not functioning properly.

**Comment by dustymc** [comment]
AWG: yep, move (if I can figure out how to...)

**Comment by mkoo** [comment]
Approved at AWG!
