### ISSUE TITLE
Search Any media type fails to return records with PDF media

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#7422]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**

@jebrad says

> a search of all UWBM:MAMM for Media=Any does not return this (or any other records with a PDF as media)?
> https://arctos.database.museum/guid/UWBM:Mamm:84151
> 
> Attached is a grab of my search attempt that did not find it, although it found 106 other things with media.  I had to search for media created by me on my Agent page in order to pull up these records with PDFs.

**To Reproduce**
1. Go to [catalog record search](https://arctos.database.museum/search.cfm?guid_prefix=UWBM%3AMamm&customoidoper=LIST&media_type=any)
2. Expect this record to be in the list https://arctos.database.museum/guid/UWBM:Mamm:84151
3. It isn't

**Expected behavior**

Expect this record to be in the list https://arctos.database.museum/guid/UWBM:Mamm:84151

But also a search for text media fails to bring up anything - I would think that would bring up all records with PDF?

**Screenshots**

![Screenshot 2024-02-15 at 12 44 35 PM](https://github.com/ArctosDB/arctos/assets/5725767/aebfa084-6dab-43ea-8c2c-e2c6a743d739)

**Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.

**Comment by dustymc** [comment]
For results problems, please use ...

<img width="297" alt="Screenshot 2024-02-16 at 08 24 02" src="https://github.com/ArctosDB/arctos/assets/5720791/c7350f51-92c4-479d-a2e1-fdb068badb7d">

... instead of screenshots.

Anyway, that searches 'shows cataloged_item' and this is (correctly, I think) 'documents..'

I have no strong feelings on changing search to include both, but maybe-probably most users want to see pretty pictures?? If nothing else, should be documented.

https://arctos.database.museum/MediaSearch.cfm (which needs a nifty URLilizer) and..

<img width="788" alt="Screenshot 2024-02-16 at 08 29 26" src="https://github.com/ArctosDB/arctos/assets/5720791/151aa6af-b9c7-4e31-a63a-68830239d6a2">

will find it.

**Comment by Jegelewicz** [comment]
> that searches 'shows cataloged_item' 

OK that makes sense, but is definitely NOT clear to the average person searching. I'll file another issue to see what is expected and how we can make it better for everyone.

**Comment by Jegelewicz** [comment]
@jebrad see Dusty's solution above - what are you trying to do with this search?

**Comment by jebrad** [comment]
@Jegelewicz  -This was an unusual search, I am unlikely to need to do it again, and this solution works for me if I do, I can remember to select "documents" when I want to find media like this and the default of "shows" makes sense.

I was just trying to find one of the records that recently had a PDF of the animal's stranding report added as media, as part of a conversation with a Wildlife person who is sending me the stranding reports for a new batch of marine mammals.

(Also, this is now my go-to example any time I hear someone claim that the Arctos search is broken, so this is gold. Thank you!)
