### ISSUE TITLE
Feature Request - New Agent Attributes: event values are confusing

### ISSUE THREAD

**Issue by ewommack** [ArctosDB/arctos#7437]
In the Diversity and Inclusion Committee today we played around in the new Agent system in test: https://github.com/ArctosDB/arctos/issues/7352

We had a suggestion to replace "dead" with "deceased" under Events. It seemed a gentler term to use for people who we are creating profiles for.

We also noticed that you can now include method for dead, alive, birth, death. We release that this cannot be changed, but it might be something that might create question. At the same time, we also could brainstorm instances where we might want to include method for some of these attributes.

**Comment by dustymc** [comment]
Data:

```

arctosprod@arctos>> select agent_status,count(*) from agent_status group by agent_status;
 agent_status | count 
--------------+-------
 alive        |  3264
 born         |  2447
 died         |  1782
 dead         |   214
```
Quick skim suggests that many/most (not quite all) of those few 'dead' are misplaced 'died' - I wonder if we need 'dead' (however we spell it) at all, or if it just encourages lowering the quality of data? Died=year-precision date, method="somewhere around here, not sure" - same idea for the rare case that died really can't be determined, but with one less corner for people to get lost in?

Sorta-related, I think birth/death should be merged into something like "life" (defined such that begin_date==birth and end_date==death).

>ight want to include method

Always! (It ain't for how I got dead, it's why you think I'm dead....)

**Comment by ewommack** [comment]
> Always! (It ain't for how I got dead, it's why you think I'm dead....)

That one we did not discuss, but a possibility.

> Sorta-related, I think birth/death should be merged into something like "life" (defined such that begin_date==birth and end_date==death).

That's an idea. We did find it weird that we could have a begin and end date for death. I could see that with an opera where people can take 15 minutes to sing through their death, but I hope we do not have to record the amount of time it takes someone to die in other circumstances.

Looking at the numbers you pulled, I do think it looks like more people are using died. I wonder if that is the attribute we use most to mark the date of death. 
It does still convey info to note on a certain date that someone is dead, but I wonder how many of those we need to record. I mark them dead on one date, and then 2 years later I confirm they are still dead.

**Comment by Jegelewicz** [comment]
> That one we did not discuss, but a possibility.

Not a possibility but the definition of method! For all attributes the method should detail the reason the attribute is being assigned. "obituary" would be an appropriate method.

**Comment by dustymc** [comment]
>more people are using died

In case it isn't clear: They're not the same things, people are just not reading the documentation and using them wrong, lowering the quality of the data.

>"life dates"

Ugh. "Begin_date life date" don't really roll off the tongue....

"life span" from the same thread, maybe?

**Comment by Jegelewicz** [comment]
> "Begin_date life date" don't really roll off the tongue....

https://arctos-test.tacc.utexas.edu/info/ctDocumentation.cfm?table=ctagent_attribute_type#life_dates

**Comment by Jegelewicz** [comment]
While messing with this in test - it occurred to me that we should NOT be making birth dates public for people who are living but exposing birth and death dates for those who are not seems like an important bit of information. Anyone else have thoughts on this?

**Comment by ewommack** [comment]
I agree. Birth dates for living individuals should be something we keep private if we can.
It is helpful archival information for those who have passed. Maybe make birth private, and the new life dates/life span public, with instructions to only be able to use if you have both dates?

**Comment by dustymc** [comment]
>for people who are living

We don't have great data (mostly strings), we're heading into a situation with a lot more of that, I don't think we're ever going to have the ability to be very confident about such things for most agents. (That is, I don't think the data could be expected to support any sort of 'conditionally public' flag.)


>birth private, and the new life dates/life span public

Good design demands that we have at most one way of saying eg 'birth date.'

> instructions to only be able to use if you have both dates?

I know one date for lots of people, including me. The other is more elusive in many cases.

**Comment by AJLinn** [comment]
> > birth private, and the new life dates/life span public
> 
> Good design demands that we have at most one way of saying eg 'birth date.'
> 
>> instructions to only be able to use if you have both dates?
> 
> I know one date for lots of people, including me. The other is more elusive in many cases.

We've talked about this before and our consensus was to not include birth dates for living people _unless_ it is already published in public locations (e.g., wikipedia, IMDB, LOC, their personal website, etc). As Dusty points out, historical data is not consistently complete and instructing/requiring adding both will simply remove valid points of data that can be useful for disambiguating John Smith (dob: 1815) from John Smith (dod: 1983). 

I think we're going to have to rely on documentation for this one and teaching our users "best practices".

**Comment by Jegelewicz** [comment]
If you want to see an example of how these terms are confused/confusing, especially now that we have begin and end dates for agent attributes, check out [Abel J. Grout](https://arctos.database.museum/agent/21291334).

![image](https://github.com/ArctosDB/arctos/assets/5725767/46d34ca7-7809-4081-bd5b-bd90d6271dea)

Do you record date of death in dead or died? Either way, should the date be recorded in begin or end date? I used alive to record both birth and death dates, but can we be sure those are birth and death dates or just some range that I happen to know the person was alive because they worked somewhere? These are structured on the agent page as `begin date - end date` and end up looking weird for born and died.

I still feel like these terms are interchangeable and not well understood or consistently used and they will probably be less-so now that they aren't defined with a code table. I am also not super clear as to why these are treated in this manner, which is different from all other attributes which are listed in the code table. I think we should take a look at what we are doing with these terms and try to come up with better options so that it will be clear to both those creating data and those using it what the terms and dates actually mean.

**Comment by dustymc** [comment]
>Do you record date of death in dead or died?

died

> should the date be recorded in begin or end date? 

just anticipating the zombie uprising....

>interchangeable

They're not, but even when they had directly-attached definitions they were clearly used that way.

**Comment by Jegelewicz** [comment]
> They're not, but even when they had directly-attached definitions they were clearly used that way.

Exactly my point. I don't think these terms are doing us any favors and we have new capabilities, so maybe we should change our ways?

Here is my suggestion

get rid of born, died, dead and alive in favor of a single option.

life dates = free text value (where anyone can add information about the dates if they like) that is allowed to be NULL. Begin date is birth date and end date is date of death and at least ONE of the two are REQUIRED.

I think nobody will complain about losing dead, but alive will cause heartache. My argument there is that all of the "alive" attributes can probably be converted to relationships or addresses with dates. How did one determine "aliveness"? Probably because the agent was encountered by, employed by, etc. a related agent or had a specific address. The associated date(s) for any of these demonstrates aliveness, doesn't it? 

I also think that there will be protests over losing separate birth and death attributes, but it is unclear to me why I should record these separately and if I do, they look crazy on the public agent page (that's just UI, so we could just change that - but I am 100% certain we will still get nonsensical data with these separated terms that each include a begin and end date).

I am just trying to simplify and make it clear to those entering data and looking at agents either as part of disambiguation or just interest in people and organizations exactly what all of these things mean.

More examples of things that just aren't clear:

![image](https://github.com/ArctosDB/arctos/assets/5725767/f9d227dc-7baf-4121-a18a-81b9561d8690)

there is hidden data here though

![image](https://github.com/ArctosDB/arctos/assets/5725767/21312051-de2e-4250-97f1-cbe4457bfae1)

Those alive attributes could be recorded as relationships. The complaint I have heard here is that time for creating another agent just to make the relationship is not available, especially when the only thing that agent will be used for is the relationship. That is a fair argument! We could just use "unknown" as the official agent and record the "verbatim" agent in method. Later, when I can find 50 instances of the verbatim agent, I can create an agent and update the relationships (maybe that will never happen, but that is a problem for another day...) OR we could add the "relationship" as an address - no need for an official agent, but easy to see "who" it was as the name could be the address.

I can work with what we have, so no change is also an option. I just see that this could be better and wanted to offer my ideas.

**Comment by dustymc** [comment]
Bogert is just the typical 'what could have been good data isn't because it was stuffed into remarks,' no? (And maybe we need to expose more/all metadata on the detail page?)

Maybe that's true for all 'alive' assertions (although I suspect we'd have a hard time making the conversion): They're all just poorly-entered addresses ('in Denver today') or relationships ('saw them') or such?

About a third of current 'alive' assertions have remarks (and a fair number of them are URLs).

I [still](https://github.com/ArctosDB/arctos/issues/7437#issuecomment-1955298065) agree on one 'life' assertion.

**Comment by DerekSikes** [comment]
Not following all the ideas here but I do not think birth day or death day should be required. This information is unknown and will remain unknown for most agents.

Alive assertions are easily inferred for most agents & thus very helpful for disambiguation.

**Comment by Jegelewicz** [comment]
I never suggested that birth or death dates should be required, just that a date must be entered if you are asserting an event.

**Comment by Jegelewicz** [comment]
From today's agent meeting

How are these used in data quality? How should they be used?

Current usage

attribute_value | count 
 -- | --
 alive     |  3359
	 birth           |     2
	 born            |  2598
	 dead            |   218
	 death           |     2
	 died            |  1889

**Comment by Jegelewicz** [comment]
@dustymc there is some secret sauce?

Use dead for one attribute and add a begin date and is shows up as birth in the UI

Use dead for another attribute and add an end date and get death in the UI

See my adds to https://arctos.database.museum/agent/21291334

**Comment by Jegelewicz** [comment]
OK nevermind - I was tripping...

**Comment by dustymc** [comment]
I'm upping priority, data are clearly being entered in various ways, it's not going to be any fun to dig them out and put them wherever we decide they should be, the sooner we make a decision the happier future-us will be.

**Comment by Jegelewicz** [comment]
I am going to stand by my solution.

Get rid of all of these and add replace with one attribute = life dates.

Life dates are for birth (begin date) and death (ended date) and would be used as checks against activity by the agent. 

To record "observed alive" dates just add a date or date range to the address, job title, name or relationship that is the source of the knowledge. This really simplifies things!

Note these two attributes in [Charles Mitchill Bogert](https://arctos.database.museum/agent/10001239)

![image](https://github.com/ArctosDB/arctos/assets/5725767/d9c80bb1-bed2-4101-919e-25b0e73144b4)

They both say he was alive, one is just way more explicit.
