### ISSUE TITLE
Curatorial Search Request how do I search for a list of identifiers?

### ISSUE THREAD

**Issue by amgunderson** [ArctosDB/arctos#7454]
I would like to find specimens with these GenBank numbers,
AF010154,HQ596479,JN037366,JN037367,AY422252,AY422256,AY422259,AY422260,AY422288,AY422304,AY422306,DQ067367,JN037397,JN037398,

searching with this comma delimited list in the identifier "value" field produces nothing. Searching for 1 at a time works but there has got to be a better way and I know I used to do this. How do I search for a list of identifiers that are not catalog numbers?

**Comment by dustymc** [comment]
https://arctos.database.museum/search.cfm?oidnum=http%3A%2F%2Fwww.ncbi.nlm.nih.gov%2Fnuccore%2FAF010154%2Chttp%3A%2F%2Fwww.ncbi.nlm.nih.gov%2Fnuccore%2FHQ596479%2Chttp%3A%2F%2Fwww.ncbi.nlm.nih.gov%2Fnuccore%2FJN037366%2Chttp%3A%2F%2Fwww.ncbi.nlm.nih.gov%2Fnuccore%2FJN037367%2Chttp%3A%2F%2Fwww.ncbi.nlm.nih.gov%2Fnuccore%2FAY422252%2Chttp%3A%2F%2Fwww.ncbi.nlm.nih.gov%2Fnuccore%2FAY422256%2Chttp%3A%2F%2Fwww.ncbi.nlm.nih.gov%2Fnuccore%2FAY422259%2Chttp%3A%2F%2Fwww.ncbi.nlm.nih.gov%2Fnuccore%2FAY422260%2Chttp%3A%2F%2Fwww.ncbi.nlm.nih.gov%2Fnuccore%2FAY422288%2Chttp%3A%2F%2Fwww.ncbi.nlm.nih.gov%2Fnuccore%2FAY422304%2Chttp%3A%2F%2Fwww.ncbi.nlm.nih.gov%2Fnuccore%2FAY422306%2Chttp%3A%2F%2Fwww.ncbi.nlm.nih.gov%2Fnuccore%2FDQ067367%2Chttp%3A%2F%2Fwww.ncbi.nlm.nih.gov%2Fnuccore%2FJN037397%2Chttp%3A%2F%2Fwww.ncbi.nlm.nih.gov%2Fnuccore%2FJN037398

**Comment by mkoo** [comment]
HI @amgunderson Sorry it took a while to respond but we've been discussing this issue and functional need-- you arent the first one with this search need. So some of the scripting that allowed Dusty to take your comma-delimited values and turn it into a query that will return GenBank identifiers is now in a new search option that will be put into implementation soon. You'll see in Customize panel 'GenBank Lookup' where you can put those search parameters in the future. It's not an ideal query field because of the behind the scenes manipulation (best to search on the entire GenBank identifier which means the whole URL) but it gets you to this point at least!

**Comment by amgunderson** [comment]
That sounds fine for GenBank numbers but I need to do this for Alaska Fish and Game numbers, USFWS sea otter or walrus numbers, NMFS numbers, etc. Every identifier needs to be queried with lists. Arctos used to work fine with that. I tried switching "My Other Identifier" in my user profile to "identifier" and using that field to search for a list but it did not work there either.

**Comment by mkoo** [comment]
That will entire depend on how you are listing the values of the identifier. So this works for a search where value is
"PL20GAM013,PL20GAM042" because that is the actual value for Issuer Alaska Department Fish and Game. If it is purely a numeric, it should also work (but didnt test yet). 

eg:
![Firefox_Screenshot_2024-03-06T22-53-43 118Z](https://github.com/ArctosDB/arctos/assets/2523089/296c4c98-192f-4ada-860c-442c374307b1)


At any rate if these are regular searches maybe we can discuss ways to accommodate in a chat since there's probably a better solution for all. Doing this for GenBank is broadly used by a lot of collections (I have had a few requests already) so I wanted to get this out there for now.

**Comment by mkoo** [comment]
here's an example where my example above would have some trouble finding:
https://arctos.database.museum/guid/UAM:Mamm:145657 (two identifiers with a space and a comma)
![Firefox_Screenshot_2024-03-06T22-53-43 118Z](https://github.com/ArctosDB/arctos/assets/2523089/faf00094-17ac-4efd-9e76-f04829081204)
