### ISSUE TITLE
Feature Request - drop requirement for verification status/verified by

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#7474]
**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_

Currently we are required to provide verification status, verified date and verified by at the time a record is entered into Arctos. This is more often than not just a repeat of assigned by and assigned date and because verification status MUST be unverified upon data entry, this becomes a strange duplication of effort.

Also, I struggle to explain what verification status IS

![image](https://github.com/ArctosDB/arctos/assets/5725767/8e9b1888-8637-4ff1-8881-6b1da52472e5)

[verification status code table](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctverificationstatus)

The only thing I think I know about it is that if I set the status to verified and locked it takes a bit more effort to edit a locality, which is also weird because one record may be using a locality and be "verified and locked" and another may be "unaccepted". I cannot explain why something so far removed from locality is doing something to a locality that may not be useful to all of the records associated with it?

**Describe what you're trying to accomplish** 
_A clear and concise overview of the goals; why are you asking for this?_

Less work, better data

**Describe the solution you'd like**
_How might we accomplish your goals?_

Remove the requirement to complete verification status, verified date, and verified by at the time a record is entered into Arctos. NULLs provide all that is needed here if there is no information available. Also, allow the entry of verified and even verified and locked - because why should I have to do this twice if I know I want one of those?

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

Just keep repeating data and stumbling over explanations for why others should do the same.

**Additional context**
_Add any other context or screenshots about the feature request here._

I am truly not certain what verification status is intended to accomplish. If it is meant to make a locality or event un-editable - let's just make a locality or event attribute for that. If it is meant for something else, someone please help me understand what!

**Priority**
_Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair._

**Comment by dustymc** [comment]
# Core Functional Bits

>Remove the requirement to complete verification status, verified date, and verified by at the time a record is entered into Arctos. NULLs provide all that is needed here if there is no information available.

Agreed, but I have an expansion request: let's also drop convert any unverified [[ link ]](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctverificationstatus#unverified) to NULL and drop that term.

# Not-So-Core Still-Functional Bits

>allow the entry of verified and even verified and locked

The logic is that you can't verify things before they're in Arctos - that'd be meaningless because Excel does who knows what, can't actually lock anything, probably isn't typed, etc.

# Not-So-Functional Bits

>struggle to explain what verification status IS

``verified_by_agent_id`` on ``verified_date`` thinks ``verificationstatus`` - the data [[do not](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctverificationstatus#unaccepted) | [do](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctverificationstatus#accepted) | [do and we really like it](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctverificationstatus#verified_and_locked)] represent what they claim to represent (eg place-time event occurred).


>something so far removed from locality is doing something to a locality that may not be useful to all of the records associated with it?

So fork-edit your "this ain't that" records (which possibly should never have been in the locality in the first place) into a cloned-and-corrected locality. 

(But yea, there's some weird 'never quite got there' hanging around, I'd not be opposed to some sort of complete revision of the locality model. Tell me what The Community wants to do and I'll design a model which does that...)

>meant to make a locality or event un-editable

Yes, but I think that's all from before we started keeping a complete history. So without the lock we could still end up with someone verifying "there" and now it says "here," but we could also tell how it got that way.

>make a locality or event attribute

No terribly strong feelings from me, attributes can certainly do this, but we've also got a functional model and I'm not sure why we'd mess with (only) that little corner of it. (If we're gonna change it then let's change it, not dabble in changing!)

**Comment by DerekSikes** [comment]
I'm pretty sure the who verified and date verified fields on data entry are not required. Loading new records as 'unverified' is key to my workflow (which itself is a workaround because I lost the argument that I wanted to be able to verify localities, not specimens-from-localities). I use this to find all unverified records and check that the localities are OK (quick checks like if any AK specimens are mapping in China etc) and if they look OK I change them to 'accepted' - just a simple data quality check step that would be hard to do without some flag like this.

**Comment by dustymc** [comment]
>lost the argument that I wanted to be able to verify localities

I don't think there's any argument to be had, file an Issue for a locality attribute and use it for whatever you want to do.

**Comment by Jegelewicz** [comment]
Need to add NULL option to search for this too.

**Comment by dustymc** [comment]
Issues meeting

* drop all requirements
* change all unverified to NULL and remove from code table
* make sure search supports "is null"

**Comment by dustymc** [comment]
## Source

https://github.com/ArctosDB/arctos/issues/7474

## Summary

Remove requirements for specimen-event verification

## User Interface Changes

1. Drop any requirements for 
    * verificationstatus
    * verified_by_agent_id
    * verified_date
2. Make sure verificationstatus search supports "is null"


## Data Structure Changes

* allow NULL in specimen_event.verificationstatus
* update bulk checks accordingly

**Comment by camwebb** [comment]
Please remove the yellow 'mandatory' box  for verification status in the Bulkload Builder.
