### ISSUE TITLE
Inconsistency in Container Details

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#751]
Container Details are inconsistent between 'find container' and 'part locations' 

In 'find container' it shows the Barcode, but that doesn't show in the details when you get to it by 'part locations'

In 'part locations' it shows other useful details including catalog number, install date, and scientific name - but those don't show when you get to details by 'find container'

Can we make all of those details show in container details no matter how you are getting there?

**Comment by dustymc** [comment]
Find Container/catnum search results and part locations are the same view (collection objects derived from the cataloged item and all their parents).

(And there's a bug in searching by catnum - I'll fix that now.)

Searching by barcode finds a container (and collection object containers cannot have barcodes) and its parent tree. It's different because it's starting at a different place.

I'm not sure where you're seeing install date, so maybe we're talking about different things. Screenshots/URLs/specific examples if so, please.
