### ISSUE TITLE
Allow collections to opt out of the Arctos Relationships classification source

### ISSUE THREAD

**Issue by camwebb** [ArctosDB/arctos#7543]
Following on from conversations about managing synonymy via classification (@dustymc, @Jegelewicz), I realized that as long as the 'Arctos Relationship' is included by default in all taxon name searches (searches which use classifications), a collection cannot have full control over the synonymy search, because the `taxon_relation` table is managed centrally, and may contain errors or deprecated relationships.

This limitation can be fixed (relatively easily, I hope) by making 'Arctos Relationships' one of the sources that a collection can opt into, or out of, in 'Manage collection'.  By default for a new collection (and for existing collections), it should be included in the ranked list of chosen sources, so as not to change expected search behavior. But a collection can simple remove it in the 'Manage collection' page, thus drawing only on the terms in the chosen source(s) for the 'taxon name' (fuzzy) taxonomy search.

**Comment by dustymc** [comment]
That's not quite how things work. 

There are three 'via taxonomy' paths to records:

1. https://arctos.database.museum/search.cfm?guid_prefix=UAM%3AHerb&taxon_name=Erigeron%20acris is "stuff someone sorta-maybe thought was Erigeron acris, despite whatever convoluted and conflicting things the collections might have done." I think that's what you're asking to change, and I'd be VERY resistant to changing it - it's the only sorta-predictable path to data. It completely ignores everything about the collection's preferences.
2. https://arctos.database.museum/search.cfm?guid_prefix=UAM%3AHerb&species=Erigeron%20acris is "things the collection's preferred classifications - whatever those might be - ended up with species==Erigeron acris." 
3. https://arctos.database.museum/search.cfm?guid_prefix=UAM%3AHerb&tax_trm_1=Erigeron%20acris&tax_src_1=UAM%20Plants is "Erigeron acris according the the UAM Plants classification" - note that this also ignores the collection's preferences, I can find your names by ANY classification, 'local' or otherwise, and I can now find anyone else's stuff by the UAM Plants classification.
4. (And not really taxonomy, but https://arctos.database.museum/search.cfm?guid_prefix=UAM%3AHerb&scientific_name=Erigeron%20acris is "show me things the collection called - not classified as - Erigeron acris.)

I suspect setting up a profile to guide users towards (2) or (3) will do what you're looking to do.

**Comment by camwebb** [comment]
Thank you. To confirm that I understand, our goal is for the user to have a way, by entering string X, to:

* A. return only specimens originally called (by an identification of any order, 0-n) exactly name X (I think this is (4) above)
* B. return all specimens that were named originally (by an identification of any order, 0-n) name Y1, Y2, Y2..., where in 'UAM Plants', for name Y1, Y2, Y3... we have listed X in field 'synonym of' (I think this is (3) above)

Please confirm.

> I suspect setting up a profile to guide users towards

Not sure what you mean by 'profile', but yes, this would be good to do...

**Comment by dustymc** [comment]
Yes.

(4) is by your identification strings (so might be weird when you've used A {string} IDs or whatever)

(3) is "according to UAM Plants" and the "rank" (if left NULL in the search) doesn't matter - 'https://worldfloraonline.org/taxon/wfo-0000085388' and 'Erigeron acris' and 'Conyzinae' all lead to the same place. 

(https://arctos.database.museum/search.cfm?guid_prefix=UAM%3AHerb&tax_trm_1=Erigeron%20acris&tax_rnk_1=species&tax_src_1=UAM%20Plants makes the rank matter - eg its still possible to avoid the synonyms)

 but that's ONLY by that path, so any oddities will prevent access. Ferexample...

```
arctosprod@arctos>> select family from flat where guid='UAM:Herb:130696';
         family         
------------------------
 Asteraceae; Asteraceae
```

because https://arctos.database.museum/name/Erigeron%20acris#UAMPlants has some replication, I presume because you're experimenting with the local editor. The classification bukloader just overwrites and won't have that problem, but of course there are an unlimited number of ways to make a mistake. (Which explains my attachment to the 'anything' search - everyone here and in globalnames has to make the same mistake for that to fail to find a record.)

(That's searchable by...

<img width="213" alt="Screenshot 2024-03-15 at 07 11 09" src="https://github.com/ArctosDB/arctos/assets/5720791/06dbc805-955b-4ecb-af63-6010734e9eec">

... and the default substring will still work, but an exact match there would cause a miss.)


> what you mean by 'profile',


https://arctos.database.museum/search.cfm then


<img width="417" alt="Screenshot 2024-03-15 at 07 02 22" src="https://github.com/ArctosDB/arctos/assets/5720791/99938e17-cdee-4e1f-927a-efb6d12c0214">

https://handbook.arctosdb.org/how_to/record-search.html#presets-and-profiles
should get you started.

You can build URLs with profiles plus other stuff, so eg

https://arctos.database.museum/search.cfm?sp=copy%20of%20other%20thing&guid_prefix=UAM:Herb&tax_src_1=UAM%20Plants

should open with a certain search config, a results config, and a couple fields filled in.

One step further, you can use redirects to make that pretty (and stable, by changing the output) - eg https://arctos.database.museum/uameh is a different flavor of the above, a shaped search+results and some prefills.

(And of course that's all fed by an API if you want to get serious about customization.)

Please add whatever we missed to the docs!

**Comment by camwebb** [comment]
> has some replication, I presume because you're experimenting with the local editor. The classification bukloader just overwrites and won't have that problem

I panicked for a moment when I realized that bulkloaded classifications won't allow for duplicates for a single name (due to overwriting), because we _need_ duplicated classifications to allow for different meanings of the canonical name. Then I realized I could probably overload a single classification record, and maybe even a single taxon_term field name, and... yes, it works! Phew. See the current [Erigeron acris][1]: prefix 1...n for different meanings of the Arctos name. Field `x_synonym_of` providing a single term to restrict synonyms to.

`search.cfm?tax_trm_1=Dummy taxon&tax_src_1=UAM Plants&tax_rnk_1=x_synonym_of` works, finding all specimens named canonical "Erigeron acris" via a search for "Dummy taxon". _But_, I don't understand why it is also finding specimens named "Erigeron acris var. asteroides". This is not the behavior I had hoped for.

(More on profiles later) Thanks



[1]: https://arctos.database.museum/name/Erigeron%20acris#UAMPlants

**Comment by dustymc** [comment]
You can drop the prefixes if you want, I desecrated your demo as a demo.

<img width="319" alt="Screenshot 2024-03-15 at 13 35 01" src="https://github.com/ArctosDB/arctos/assets/5720791/30814797-a2a6-4828-8f50-46f5e5460f1d">

>var. asteroides

<img width="1196" alt="Screenshot 2024-03-15 at 13 36 46" src="https://github.com/ArctosDB/arctos/assets/5720791/cae0397a-0923-41a6-b3a2-3216efadf0d8">

https://arctos.database.museum/search.cfm?guid_prefix=UAM%3AHerb&identification_order=%3E0&tax_trm_1=%3DErigeron%20acris&tax_src_1=UAM%20Plants

should do it.

**Comment by camwebb** [comment]
Ah yes, I hadn't actually looked at the position of the ID. So, ~~This is not the behavior I had hoped for~~ This _is_ the behavior I had hoped for.

Now to 

1. make and bulkload the classification, 
2. use a profile to guide the user...

(1) will take a while, so I'll close this now.  Thanks!
