### ISSUE TITLE
Feature Request - link taxon names in identification to related resources

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#7557]
**Is your feature request related to a problem? Please describe.**
We used to be able to link out from taxon names in identification to related resources in Arctos. See attached figure by @ebraker that we are using for the Arctos paper. That doesn't seem to be the case anymore. Can we bring that feature back so that if you click on a taxon name, you get all related Arctos resources?

**Describe what you're trying to accomplish** 
I'm asking for this because it's a cool feature that we highlight in the Arctos paper!

**Describe the solution you'd like**
Link taxon names in identification to related Arctos resources.

**Priority**
High! (Arctos paper revision is due this month)

[Fig6_EHRecord.pdf](https://github.com/ArctosDB/arctos/files/14621477/Fig6_EHRecord.pdf)

**Comment by dustymc** [comment]
>all related Arctos resources?

The links are now to the collection's preferred classification rather than the name (which might mean lots of things). That wasn't so much the case when that was first developed, Arctos is now much more diverse and things have evolved to reflect that.

The current setup also does a lot better job in linking to multiple taxa, or other various cases where the identification string and taxon name don't line up.

The entirety of all used classifications are now included on the record as well.

https://arctos.database.museum/guid/UAM:EH:UA91-014-0001


<img width="688" alt="Screenshot 2024-03-15 at 16 11 03" src="https://github.com/ArctosDB/arctos/assets/5720791/3b19cf29-3276-4baf-9e9c-9e13beb0f2f9">

**Comment by ccicero** [comment]
Ah, ok. Thanks @dustymc. I can work with this to revise then caption and make it clear.

@ebraker do you think the figure is ok as is or should we update it to reflect the way it works now?
