### ISSUE TITLE
Redirects for Deleted or Encumbered Records

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#7588]
This is a request for clarification/instructions on how to set up a redirect for a duplicate record that needs to be deleted/encumbered. Instructions need to be added to the Manage Redirects Tools page to make this tool functional.  Neither the tool nor the existing documentation provide enough information. 
Can someone provide a step by step with an example? 
I have also posted to a Needs Documentation issue with more info here: https://github.com/ArctosDB/documentation-wiki/issues/304

**Comment by Jegelewicz** [comment]
Please advise on how this needs to be updated - https://handbook.arctosdb.org/documentation/redirect.html

**Comment by campmlc** [comment]
> Please advise on how this needs to be updated - https://handbook.arctosdb.org/documentation/redirect.html

I can't advise until I understand how the tool is supposed to work? I was hoping someone else who has used it can advise. And we should make updates to the tool itself to clarify was is expected, because I failed to understand either the tool or the documentation for it.

**Comment by mkoo** [comment]
Just updated your documentation comment-- https://github.com/ArctosDB/documentation-wiki/issues/304 (I am going to leave it open for now)

So you dont have to look that up, I'll reiterate: your redirect was already created, exists and is working (I tested that!) so the delete option is only if it needs to be recreated because it is wrong and needs to be redone. The instructions on the tool page says that-- redirects cannot be edited but you can delete and make a new one. 

So first step: find redirects. Might need to be deleted so that option is below if it exists. If not create it! hope that helps
