### ISSUE TITLE
Feature Request - New Agent "unrecorded"

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#7608]
**Is your feature request related to a problem? Please describe.**
There are inconsistent uses of the agent "unknown". It is sometimes not an accurate representation of the status of certain kinds of agent roles. As a result there are likely hundreds of thousands of agent roles attributed to "unknown" when in actuality, someone knows the answer, it is just currently not available to the cataloger.

**Describe what you're trying to accomplish** 
A new agent that can be meaningfully and intentionally attributed that accurately reflects the current status of knowledge surrounding that agent and does so in a more respectful manner.  (E.g., creators of cultural objects and art are known by someone, but a collector either forgot who made the item or it was not written down based on field collecting standards of the time.)

**Describe the solution you'd like**
A new agent "unrecorded" would allows users to meaningfully assign an agent role that shows intent and truthfully represents the actions leading to the assigned agent. It will also indicate to viewers that the collection would welcome input from other users and members of the public to try and resolve the unrecorded agent.

**Describe alternatives you've considered**
1. using agent "unknown"
2. not adding an agent in the roles in question

**Additional context**
We would need guidance on migrating current uses of "unknown" agent to the new "unrecorded" agent. We would also require clear documentation on how to distinguish between agent "unknown" and agent "unrecorded."

@DerekSikes do you have any additional comments or rationale to add?

**Priority**
Normal priority.

**Comment by AJLinn** [comment]
Brought over from Issue #7434.

**Comment by dustymc** [comment]
First hat, technical perspective: Until and unless the @ArctosDB/agents-committee wants to set rules/guidelines/guardrails, there are no restrictions on agents or agent names. If you want to do WHATEVER, you can.


-----------


Second hat, usage perspective: There's definitely some (sometimes very subtle) distinction between things like 'we know nothing' (always best represented by NULL) and "we're not telling you" and "we don't know and we'd like to tell you that" and "we looked and still don't know" and etc., and making that distinction would add a bit of utility to the data. Agent Zero has been carrying all of those roles and more, in part because we have required SOMETHING at various times and places - clearly a recipe to lose those distinctions. I think it would take a very careful set of users to avoid arbitrary application, and if that happens it would become a bit more difficult to find the "doesn't have data" stuff of any flavor in the mess (which isn't exactly disastrous, but still!).

**Comment by AJLinn** [comment]
Agent "unrecorded" created
https://arctos.database.museum/edit_agent.cfm?agent_id=21352057

Can I get assistance in changing all of my instances of:
creator: unknown ==> creator: unrecorded

**Comment by dustymc** [comment]
I doubt the personhoodedness of this agent...

Confirm that this is them and I can update.

[temp_uam_eh_unk_c.csv.zip](https://github.com/ArctosDB/arctos/files/14765266/temp_uam_eh_unk_c.csv.zip)

**Comment by dustymc** [comment]
I still doubt the personhood....

**Comment by AJLinn** [comment]
Updated to "other agent"

**Comment by Jegelewicz** [comment]
> Updated to "other agent"

I spent 5 hours last week trying to get rid of "other" agents - is that a lost cause?

**Comment by dustymc** [comment]
done
