### ISSUE TITLE
Need a report

### ISSUE THREAD

**Issue by jldunnum** [ArctosDB/arctos#7609]
We have the USGS Biological Survey collection here at MSB. Each year I have to submit a usage report to USGS. I list the loans and number of USGS specimens included in each.  I have a project (https://arctos.database.museum/project/10002364) which contains all the USGS specimens at MSB. Is there a tool that will allow me to cross reference those specimens and our loans for a given year? Thanks

**Comment by Jegelewicz** [comment]
Maybe this?

https://arctos.database.museum/search.cfm?customoidoper=LIST&loan_number=%252023%25&project_id=10002364

I first used the link from the project to get all records in the project, then I added all loan numbers that include 2023 because I think you guys always include the year in the loan number?

![image](https://github.com/ArctosDB/arctos/assets/5725767/d8e130b4-9147-4060-951a-8239aeb80daa)

But there is probably a better way...

**Comment by jldunnum** [comment]
Seems like that might work. I'll play around with it a bit a check. Thanks!

______________________________________________________________
Jonathan L. Dunnum Ph.D. (he, him, his)
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
Research Assistant Professor (LAT)
Department of Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

Chair, Systematic Collections Committee, American Society of Mammalogists
Latin American Fellowship Committee, ASM

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by dustymc** [comment]
Done?
