### ISSUE TITLE
Feature Request - Add all objects in a container to a loan

### ISSUE THREAD

**Issue by falco-rk** [ArctosDB/arctos#7611]
**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_
I would like to easily add all objects in a container to a loan.

**Describe what you're trying to accomplish** 
_A clear and concise overview of the goals; why are you asking for this?_
When adding objects to a loan, you can add items by part container barcode, but it only works if there is a single item in the container (i.e., it works for a cryovial but not a freezer box). I would like to be able to give the tool the barcode of a container (in my case, a freezer box that contains all the samples I want to loan out) and have it add all the samples in that box to the loan.

**Describe the solution you'd like**
_How might we accomplish your goals?_

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

**Additional context**
_Add any other context or screenshots about the feature request here._

**Priority**
_Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair._
@Jegelewicz @dustymc

**Comment by Jegelewicz** [comment]
I am in favor of this. It may need its own tool?

**Comment by megulbranson** [comment]
There is a way to do this, I've done it previously for a loan of over 2000 individuals that were in small cryovials organized in 96-well plates. You go to "container:find" then type the barcode for the box with all of your samples into "Container Barcode" then click "see all collection objects in this container" (see below)


<img width="1399" alt="Screenshot 2024-03-29 at 3 44 49 PM" src="https://github.com/ArctosDB/arctos/assets/134456825/89fb30d3-9c69-4541-ad9d-3e9502151072">


Then you should have a list off all the cryovials or objects scanned into the box (not seen in the image below because my example is an empty box) and you should be able to use the buttons at the bottom to add all items to a loan and update dispositions.


<img width="940" alt="Screenshot 2024-03-29 at 3 46 22 PM" src="https://github.com/ArctosDB/arctos/assets/134456825/0c921272-0261-4272-bdec-bb90de3bfe20">

**Comment by dustymc** [comment]
added to https://handbook.arctosdb.org/how_to/How-to-Add-Loan-Items.html
