### ISSUE TITLE
Help moving all KWP:Ento containers to UAM:Ento

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#7626]
I'd like to have all containers owned by KWP:Ento be changed to be owned by UAM:Ento.

Can someone help with that or tell me how to do it?

thanks!

**Comment by dustymc** [comment]
>owned by KWP:Ento 

There's no such thing, see https://github.com/ArctosDB/arctos/issues/7466

I still think I know what you mean, but one question: Should I convert **all** containers from KWP to UAM, or only those NOT of type ``collection object`` (==part-containers)?

I think probably the latter, the collection should continue to own its own parts, but not sure what you're trying to do so?????

Here's data in case that's helpful.

```
create table temp_kpwbc as select * from container where institution_acronym='KWP';
```

[temp_kpwbc.csv.zip](https://github.com/ArctosDB/arctos/files/14845429/temp_kpwbc.csv.zip)

**Comment by DerekSikes** [comment]
Yes, I'm not 100% clear on how this works - however, it might help to explain what motivated me: 

these barcodes are on pins of Lepidoptera specimens that had been in KWP:Ento but were moved to UAM:Ento

UAM100373734,UAM100378515,UAM100378511,UAM100378510,
UAM100378509,UAM100378508,UAM100378507,UAM100378506,
UAM100373733,UAM100378513,UAM100378514,UAM100378503,
UAM100378505,UAM100378504,UAM100378502,UAM100373732,
UAM100373731,UAM100392982,UAM100393085,UAM100393017,
UAM100393021,UAM100393086,UAM100393081,UAM100393082,
UAM100393079,UAM100392979,UAM100392946,UAM100393097,
UAM100393113,UAM100393020,

but the parts appear to still be in KWP:Ento (I discovered this when my collection manager, who had access to UAM:Ento but not KWP:Ento, was unable to find the records for these parts when she scanned those barcodes. I gave her access to KWP:Ento and then she was able to find them. But I'd simply like to solve this problem so we don't get confused again.

I'd like all parts & containers that are in KWP:Ento which are being used by UAM:Ento records to become UAM:Ento parts/containers. 

Does that make sense?

**Comment by dustymc** [comment]
Thanks, more information is kinda always useful, yes I think that makes sense (and leads me somewhere pretty far from where I was aiming...).

The first part I was going to suggest is easy:

```
SELECT 0
```

there are no KWP not-part containers. (Or I've badly mangled something that I'm hoping you're going to catch, which is why I always post lots of data in these.)

Here are not-KWP parts in KWP containers.

[temp_kpw_ornot_prt.csv.zip](https://github.com/ArctosDB/arctos/files/14852057/temp_kpw_ornot_prt.csv.zip)


and a summary

```

arctosprod@arctos>> select institution_acronym,count(*) from temp_kpw_ornot_prt group by institution_acronym;
 institution_acronym | count 
---------------------+-------
 KWP                 | 22998
(1 row)

Time: 14.642 ms
arctosprod@arctos>> select parent_institution_acronym,count(*) from temp_kpw_ornot_prt group by parent_institution_acronym;
 parent_institution_acronym | count 
----------------------------+-------
                            |   201
 UAM                        | 22797
(2 rows)
```

I think I need to convert ``container_id`` in the above to institution_acronym UAM.

You can check those at eg https://arctos.database.museum/findContainer.cfm?container_id=597648

Check and in details you should see the mismatch:

<img width="362" alt="Screenshot 2024-04-03 at 08 25 40" src="https://github.com/ArctosDB/arctos/assets/5720791/5239bc60-f2b7-4579-a436-45207f47f233">

**Comment by DerekSikes** [comment]
Excellent, yes, that seems correct. 

Please proceed with convert container_id in the above to institution_acronym UAM. Thanks!

**Comment by dustymc** [comment]
done

**Comment by DerekSikes** [comment]
thanks!
