### ISSUE TITLE
Code Table Request - change Alaskapox to borealpox in Attributes detected and not detected

### ISSUE THREAD

**Issue by amgunderson** [ArctosDB/arctos#7632]
Alaskapox has had a name change to borealpox so the corresponding attributes need to be changed. See https://health.alaska.gov/dph/Epi/id/Pages/Borealpox.aspx for documentation.

I would do this myself but it appears I can no longer manage code tables....

**Comment by mkoo** [comment]
Thanks for the update. I am going to reformat this request into our usual CT request. Please see the updated definition below and leave a comment!

## Initial Request: update to borealpox

### Goal
Alaskapox virus has an updated name: Borealpox
Thus the CT value ```virus: Alaskapox``` should be renamed ``` virus: Borealpox```

### Table
This impacts: https://arctos.database.museum/info/ctchange_log.cfm?tbl=ctexamined_detected

### Proposed Value
virus: Borealpox 

### Proposed Definition

Borealpox virus is a species of the Orthopoxvirus genus first documented in 2015 in Alaska, United States as Alaskapox (https://en.wikipedia.org/wiki/Alaskapox_virus). It is known to infect mammals, especially small mammals, as well as humans (https://health.alaska.gov/dph/Epi/id/Pages/Borealpox.aspx).




### Priority
Normal 

### Available for Public View
no restrictions



### Helpful Actions

- [ ] Add the issue to the [Code Table Management Project](https://github.com/ArctosDB/arctos/projects/13#card-31628184).

- [ ] Please reach out to anyone who might be affected by this change. Leave a comment or add this to the Committee agenda if you believe more focused conversation is necessary.

@ArctosDB/arctos-code-table-administrators 

## Approval
_All of the following must be checked before this may proceed._

_The [How-To Document](https://handbook.arctosdb.org/how_to/How-To-Manage-Code-Table-Requests.html) should be followed. Pay particular attention to terminology (with emphasis on consistency) and documentation (with emphasis on functionality). **No person should act in multiple roles**; the submitter cannot also serve as a Code Table Administrator, for example._

- [ ] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [ ] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [ ] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [ ] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)


## Rejection
_If you believe this request should not proceed, explain why here. Suggest any changes that would make the change acceptable, alternate (usually existing) paths to the same goals, etc._

1. _Can a suitable solution be found here? If not, proceed to (2)_
2. _Can a suitable solution be found by Code Table Committee discussion? If not, proceed to (3)_
3. _Take the discussion to a monthly Arctos Working Group meeting for final resolution._

## Implementation
_Once all of the Approval Checklist is appropriately checked and there are no Rejection comments, or in special circumstances by decree of the Arctos Working Group, the change may be made._

- [ ] Review everything one last time.  Ensure the How-To has been followed. Ensure all checks have been made by appropriate personnel.

- [ ] Add or revise the code table term/definition as described above. Ensure the URL of this Issue is included in the definition. URLs should be included *_as text_*, separated by spaced pipes. Do not include HTML in definitions.

**Comment by amgunderson** [comment]
That is all correct and good, thanks.

**Comment by mkoo** [comment]
Great! This is easy since it's basically a definition update with no programming requirements-- are there records with this value? I couldnt find any.... that would be the last item to check and plan for updating
