### ISSUE TITLE
single "container" to hold all UAM:Ento loaned specimens?

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#7639]
I'd like to make a container in Arctos that is called something like:

UAM:Ento-on-loan

and we'll change our loan protocol so that all specimens will be scanned into this "container" before going out.

Can I get advice on:

1) thoughts on this idea
2) how to proceed? I was thinking of taking a container like:

https://arctos.database.museum/EditContainer.cfm?container_id=11775275

and cloning it and changing the barcode & label appropriately & then moving to have only the parent 'The Universe'

I don't want to have to make a separate container for every loan, or put barcodes on mailing boxes and keep track of them separately - I want a simple single 'fake container' that we can put all loaned specimens into.

The major advantage is:
1) the last scan dates will be updated immediately before the loan goes out
2) the 'parts locations' report will make it clear which specimens are on loan and which aren't

**Comment by Jegelewicz** [comment]
@campmlc @megulbranson @falco-rk thoughts?

**Comment by falco-rk** [comment]
I created a range in our object tracking for all of our loans for a similar purpose. I do create boxes for each individual loan (mostly to help keep track of things before they have been shipped) but I don't plan to put barcodes on these temporary boxes. My loan range is in my institution rather than just the universe, but that's mostly for convenience of finding it without knowing the barcode.

So your plan makes sense to me, but I set mine up very recently (like 2 weeks ago) so I can't say that it will work in the long run.

**Comment by campmlc** [comment]
I have DGR_LOAN as a container under the umbrella of my Division. It works great if Im loaning entire objects scanned into boxes, intead of subsamples, but I don't do that often.  I can name the box for the loan, put the whole box into my "loan" container and be able to still track positions within the box,  which is helpful to provide the researcher.  I don't do this often because I mostly send unbarcoded subsamples. I have a lot of random stuff in my loan container, but it works for the purpose of showing which objects are on loan and not physically located in the collection.

**Comment by campmlc** [comment]
And if I don't want to put the whole container in the loan, eg I don't want to send a physical box, I just scan individual items into the loan container. Works both ways.

**Comment by DerekSikes** [comment]
Thanks for these comments!

Is my idea to clone a UAM:Ento container & edit it good too? I've not done that before and worry I might goof up due to some restrictions on creation of new barcodes/containers etc.

**Comment by campmlc** [comment]
I haven't cloned containers. But you can just use the Container Bulkload tool in the Tools Directory and loan a single container. It would have to be one you've reserved the series for.  I created mine as a virtual container, but I'm not sure if that is allowed anymore . . . things change a lot. The alternative would be to use "Range" or something.

**Comment by campmlc** [comment]
I agree that trying to Clone any container that has anything in it would/should throw errors. I can't see the link you provided. It might be interesting to try and see what happens or what breaks . . . . But the more certain way is just to use the container bulkload tool.

**Comment by DerekSikes** [comment]
can someone (eg @dustymc ) with deep knowledge of how the container & object tracking system of Arctos works, comment on the best way for me to make such a "loan" container? (if cloning a container doesn't work, why does that button exist?)

**Comment by campmlc** [comment]
I've never used it in a decade and can find no documentation. Anyone else? 
Regardless, the Container Bulkload tool at https://arctos.database.museum/loaders/bulkCreateContainer.cfm works. But you need to pick a barcode value to assign to your container, and I don't see that you have anything in your current reserved UAM Ento series that would be appropriate, unless you want to give it the barcode value of an ento tag and just change the label. It would be better to reserve a value for your collection to use in these situations. Go to Stake a Claim at https://arctos.database.museum/info/barcodeseries.cfm. For example, you could request "UAMEnto_loan" as a value, or 

For my "DGR_LOAN" barcode, here is my reserved series info: 
the free text description:     DGR followed by 8 characters, numeric,text, _ or - 
 and the SQL:   barcode~'^DGR[A-Z0-9_-]{0,8}$'
