### ISSUE TITLE
Issue with password reset

### ISSUE THREAD

**Issue by Awkwardtree13** [ArctosDB/arctos#7641]
After a few months of inactivity on my Arctos account due to focusing on other tasks in the collection I work in, I am once again having an issue with the system not letting me log in or reset my password- See issue #6720 for the last time this happened to me. I believe the correct course of action here is to ask @babogan to deal with this, as that was what was done last time? Additionally, my sister (JillianLHenning on Arctos, she's never gotten around to making a GitHub account, but we work in the collection together) is having the same issue, and presumably requires the same fix? I apologize for the inconvenience.

**Comment by babogan** [comment]
Hello!
I have unlocked and reset both accounts. Please let me know if there are any issues

Brooke Bogan
She/Her/Hers
Department of Museum Research and Collections
Alabama Museum of Natural History
356 Mary Harmon Bryant Hall
Box 870340
500 Hackberry Ln
Tuscaloosa, Alabama 35401
***@***.******@***.***>
(205)-348-5625
***@***.***

From: Awkwardtree13 ***@***.***>
Sent: Friday, April 5, 2024 2:41 PM
To: ArctosDB/arctos ***@***.***>
Cc: Brooke Bogan ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] [ArctosDB/arctos] Issue with password reset (Issue #7641)


After a few months of inactivity on my Arctos account due to focusing on other tasks in the collection I work in, I am once again having an issue with the system not letting me log in or reset my password- See issue #6720<https://github.com/ArctosDB/arctos/issues/6720> for the last time this happened to me. I believe the correct course of action here is to ask @babogan<https://github.com/babogan> to deal with this, as that was what was done last time? Additionally, my sister (JillianLHenning on Arctos, she's never gotten around to making a GitHub account, but we work in the collection together) is having the same issue, and presumably requires the same fix? I apologize for the inconvenience.

-
