### ISSUE TITLE
Help searching for multiple unrelated species in a single search

### ISSUE THREAD

**Issue by falco-rk** [ArctosDB/arctos#7652]
I want to search for a bunch of unrelated species to see how many records of each species there are in my collection. I assume there is a way to do this, but I can't figure it out. 

If I put a comma list in either "Any taxon, ID, common name" or "Identification" with any Match Type, I get no records even though I know I have records.

@Jegelewicz @campmlc

**Comment by campmlc** [comment]
By unrelated, do they not share any common higher taxonomy? Can you search by class or phylum and filter in the excel download?
You can also search your entire collection just by selecting OGL, and you can do the same, if you minimize your results download so that you don't exceed 500,000 record limit.
Once you get your search results, you can use Tools and Summarize Results to get the following:
![Screenshot 2024-04-09 10 18 50](https://github.com/ArctosDB/arctos/assets/14808196/edf806d0-0df9-4520-a539-62c7ee5ec22c)

**Comment by falco-rk** [comment]
> with no spaces

Ahhh I had spaces! Thank you!
