### ISSUE TITLE
Project Search

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#770]
Project search will not return results for any project lacking a description of at least 100 characters. This is a source of duplicate project creation. Perhaps instead of refusing to show search results, there could be a red pop up box during project creation requesting the minimum no. characters be entered? Or refusal to create a project without a minimum description length?

**Comment by dustymc** [comment]
That doesn't address the 200 existing short project descriptions (below).

The intent is not to prohibit concise descriptions, just to filter out those projects which don't really add any value to anything so that those which do add value become more prominent. Project description length is far from perfect in that role and so I'm very hesitant to make this a rule. It's also (arguably) better than nothing, so I'm somewhat hesitant to drop it from the interfaces as well.

The project creation and edit forms have had a red warning label since before the interfaces began filtering.

UAM@ARCTOS> select PROJECT_NAME,PROJECT_DESCRIPTION from project where length(PROJECT_DESCRIPTION) <=100 order by project_name;

PROJECT_NAME
------------------------------------------------------------------------------------------------------------------------
PROJECT_DESCRIPTION
------------------------------------------------------------------------------------------------------------------------
"Doing Natural History" in <i>BioScience</i>
"Doing Natural History" by M. Sunderland, K. Klitz and K. Yoshihara.

2007 Nunatak Rapid Ecological Assessment
Nunataks on the Kenai NWR side of the Harding Ice Field were sampled quickly in July, 2007.

A catalog of moa eggs (Aves: Dinornithiformes)
Inventory of moa eggs in museum collections.

A five-year change in an assemblage of wood rat houses
behavior; natural history

A molecular analysis of selected taxa of the genus <i>Primula</i>. (Herbarium Z)
Alessia's Ph.D. Thesis.

A novel phylogenetic approach to the analysis of bat phylogenetics and morphological evolution.
NSF grant DEB 1020890.

Alaska Quaternary Center Paleoecology Study
Anthers removed from herbarium specimens of Empetrum

Alaskan blueberry identification
Comparing Vaccinium uligonosum and Vaccinium caespitosum

Alaskan cinquefoil identification
Comparing Potentilla nivea and Potentilla villosa

Alaskan monkshood identification
Comparing Aconitum delphinifolium and Aconitum maximum

Amphibians, reptiles, and mammals of eastern Madagascar
<p>Terrestrial vertebrate surveys of upland and lowland rainforest of eastern Madagascar.</p>

An experimental analysis of orientation to the homesite in two rodent species
behavior

An experimental examination of an artificial dispersal sink
movement; natural history

An experimental study of dispersal in the California ground squirrel
movement; natural history

Anthro 450/550 Paleoecology
UNM anthropology department, paleoecology class ANTHRO 450/550.

Arboreal sprint failure: lizardfall in a California woodland
behavior; natural history

Arctic Valley Snow Telemetry Sites


Arnica identification
Comparing <i>Arnica frigida</i> and <i>Arnica lessingii</i>

Babesia screening
Screening rodents in Alaska for babesiosis at Harvard Medical School.

Balsam poplar identification
Comparing Populus balsamifera subsp. balsamifera and Populus balsamifera subsp. trichocarpa

Bandicoot interrelationships
Studying bandicoot (Marsupialia: Peramelidae) relationships using mtDNA and nDNA.

Bats of Montserrat
Study on distribution and evolution of bats of Montserrat Island.

Bearberry identification
Comparing Arctostaphylos alpina and Arctostaphylos uva-ursi

Beringia Paleovegetation Project
Sample herbarium specimens for d13C and d15N

Birch identification
Comparing Betula glandulosa and Betula nana subsp. exilis

Bistort identification
Comparing Polygonum bistorta subsp. viviparum and Polygonum bistorta subsp. plumosum

Blueberry identification
Comparing Vaccinium alaskensis and Vaccinium ovalifolium

Bog orchid identification
Comparing Platanthera dilatata and Platanthera convallariaefolia

Botanical Survey, Kodiak National Wildlife Refuge, 2013
Vascular collections by Stacy Studebaker from Kodiak Island, Summer 2013

Bringing the Condors Home
Exhibit on California Condors at the Lindsay Wildlife Museum, 19 Mar 2008 - 6 Jul 2008.

Calamagrostis taxonomy
Examine morphology of Calamagrostis specimens--no subsamples taken

Canine SNP arrays.
Assessment of genome-wide canine SNP arrays and implications for canine disease association studies.

Cannibilism in Chacophrys tadpoles
Examining specimens to document cannibilism in juveniles/froglets of Chacophrys.

Checklist of the mammals of Alaska
Checklist of mammals known to occur with the state of Alaska

Chromosomal analysis of the Bolivian bamboo rat, Dactylomys boliviensis (Rodentia : Echimyidae)
Karyotypic analysis of D. boliviensis.

Cinquefoil identification
Comparing Potentilla nivea and Potentilla arenosa

Class anthropology 101
testing project creation at Ann Arbor

Cloudberry and salmonberry identification
Comparing Rubus chamaemorus and Rubus spectabilis

Comparative phylogeography of the Puerto Rican Emerald Anole (Anolis evermanni) and the Puerto Rican Yellow-chinned Anol
e (Anolis gundlachi)
One of multiple studies on phylogeography, evolution, and historical biogeography of Anolis lizards.

Comparative skeletal morphology of Cardueline finches
This project involves a comparative study of Cardueline finches, using skeletal morphology.

Conservation phylogenetics of the Asian box turtles (Geoemydida, Cuora): mitochondrial introgression, numts, and inferen
ces from multiple nuclear loci
Phylogenies based on sequence data from 69 individuals.

Contact zone of black salamander (<i>Aneides flavipunctatus</i>) in Mendocino County.
Tissues in 95% ethanol. These are consumable.

Corydalis identification
Comparing Corydalis aurea and Corydalis sempervirens

Cup lichen identification
Comparing Cladonia pleurota and Cladonia borealis

DNA barcoding of Cambodia mammals
DNA barcoding of Cambodia mammals

Demography, migration, and metapopulation structure of pond breeding salamanders
demography; movement

Different climatic envelopes among invasive populations may lead to underestimations of current and future biological in
vasions
This project downloaded Hieracium data from Arctos

Dispersal in the monogamous rodent, <i>Peromyscus californicus</i>.
movement; behavior

Dispersal, gene flow, and allelic diversity between local populations of Thomomys bottae pocket gophers in the coastal r
anges of California
genetics

Distribution and Ecology of Snowshoe Hare <i>(Lepus americanus)</i> in New Mexico
Malaney masters thesis on snowshoe hare.

Distribution and Habitat Preferences of the Amphibians and Reptiles of Hastings Natural History Reservation
distribution

Dwarf dogwood identification
Comparing Cornus suecica and Cornus canadensis

Dwarf willow identification
Comparing Salix bebbiana and Salix scouleriana

ECOCHANGE DNA Barcode Database
Assembling a DNA barcode database for arctic and north boreal species.

Evolution of spiny hairs in rodents: a role for Edar?
To investigate the evolution of Edar in spiny haired rodents.

Evolution, Phylogeny, and Systematics of the Family Caviidae (Mammalia: Rodentia).
Ph.D. dissertation in Zoology at Texas Tech University.  Major advisor Jorge Salazar-Bravo.

Evolutionary Biology of Spea
Evolutionary Biology of Spea

Examination of a Mus contact zone in Europe
This project uses an Illumina assay (1536 SNPs) to genotype mice from across the hybrid zone.

Examination of the History of Black Oystercatchers Eating Northern Abalone
Examination of the history of black oystercatchers eating abalone.

Exhibition at Pacific Grove Museum of Natural History: "Living with Mountain Lions"
Exhibition will include MVZ Archive photo "J. Bruce and three mountain lions" (MVZ 4339).

FNSB School District
Borrowed marine mammals to create 3D graphics for a webpage.

Fall 2007 University of New Mexico Student Health Fair.
Specimens used to demonstrate rodent hosts of infectious diseases.

Fireweed identification
Comparing Epilobium angustifolium and Epilobium latifolium

Flora of North America Illustration Voucher
Specimens used for illustrations in Flora North America volumes

Floristic Survey of the Kilbuck Mountains, sponsored by the U.S. BLM
a plant collection from the Kilbuck Mountains from a basecamp along Slate Creek, 11-16 July 2006.

Fluctuating asymmetry and allozymic heterozygosity among natural populations of pocket gophers (<i>Thomomys bottae</i>).
genetics

Genetic Diversity of Chaetodipus hispidus
Pilot study examining genetic diversity across the range of Chaetodipus hispidus.

Genetic diversity of Vancouver Island Marmots
Uses microsatellites and mtDNA to examine temporal change in diversity of Vancouver Island Marmots.

Genetic variation and immune response in natural populations of pocket gophers
genetics

Genetic variation in Thomomys bottae pocket gophers: macrogeographic patterns
genetics

Geographic variation in genic and morphological characters in <i>Peromyscus californicus</i>
genetics

Geranium identification
Comparing Geranium bicknellii and Geranium erianthum

Goosefoot Identification
Comparing Chenopodium capitatum and Chenopodium album

Gopher snake attraction to bird's nests
behavior; feeding ecology

Great Basin movements in <i>Marmota flaviventris</i>
A molecular study of movements of marmots in the Great Basin.

Grinnell Resurvey Project: Coast Range Transect
Resurvey of the bird sites in the Coast Range of California using bird point count methods.

Growth and size of the western fence lizard (Sceloporus occidentalis)
demography; natural history; feeding ecology

Growth, reproduction , and sexual dimorphism in Thomomys bottae pocket gophers
demography; natural history

Habitat preferences and the distribution of <i>Uta stansburiana</i> and <i>Sceloperous occidentalis</i> in coastal Calif
ornia
distribution; natural history

Hantavirus Host Specificity, viral species identity and distribution in Alaska, 2004-2014.
A study of hantavirus host specificity, viral species identity and distribution in Alaska, 2004-2014

Hantavirus screening in Alaskan small mammals.
Frozen heart and lungs tissues from small Alaskan mammals for Hantavirus screening.

Herbarium ILL Betula Pollen Study
removed portion of catkins from herbarium specimens for pollen study

Herbarium TENN Betulacaeae phylogeographic study
sample herbarium specimens for leaf tissue for phylogeographic study

Historic Grinnell Survey: Alaska
Collecting expeditions to Alaska led by Annie M. Alexander (1907-1909).

Historic Grinnell Survey: Coast Range Transect
Original survey of birds in coastal ranges of California.

Homerange in the western fence lizard (Sceloporus occidentalis occidentalis)
demography; natural history; behavior

Homing in the California vole, Microtus californicus
behavior; movement

Homing in the western harvest mouse, Reithrodontomys megalotis
behavior

Investigation of the phylogenetic placement of a western Guatemalan <i>Dendrotriton</i>
Investigation of the phylogenetic placement of a western Guatemalan <i>Dendrotriton</i>

Kodiak National Wildlife Refuge, USFWS-2012 Botanical Survey
Stacy Studebaker collections from Kodiak NWR-2012

Kodiak National Wildlife Refuge-2010 Botanical Survey
Vascular plant survey of select areas within the Kodiak NWR during 2010

Labrador tea identification
Comparing Ledum palustre subsp. decumbens and Ledum palustre subsp. groenlandicum

Lady fern identification
Comparing Athyrium distentifolium subsp. americanum and Athyrium filix-femina subsp. cyclosorum.

Ladyslipper identification
Comparing Cypripedium passerinum and Cypripedium guttatum

Life history and demographic variation in the California tiger salamander (<i>Ambystoma californiense</i>)
demography; natural history

Lifetime reproductive success and its correlates in the monogamous rodent, <i>Peromyscus californicus</i>
natural history; behavior

Limb morphology in relation to locomotion in a phylogenetically broad sample of lizards.
Includes functional data as well as morphological measurements.

Locoweed identification
Comparing species in Oxytropis sect. Arctobia

Long term patterns in coastal California grasslands in relation to cultivation, gophers, and grazing
natural history

Lupine identification
Comparing Lupinus nootkatensis and Lupinus arcticus

Microspatial genetic heterogeneity in pocket gophers: non-random breeding and drift
genetics; demography; movement

Migration and evolution of arctic <i>Alnus</i> in response to past climate change.
sampled leaf tissue from herbarium specimens

Miniaturized portable flow-through amperometric immunosensor device for fast field analysis of rodent viruses.
Create hand held field device to detect rodent viruses.

Molecular Study of Deschampsia
Subsample tissue from herbarium specimens to extract DNA for molecular analysis

Molecular Systematics of Montieae (Portulacaceae)
Systematics of the genus Claytonia sens. lat., Robin O'Quinn, grad student at WS with Larry Hufford

Molecular and Morphological Phylogeny of the Lizard Genus <i>Mesaspis</i>  and Other Anguids (Anguidae: Gerrhonotinae)
Mesaspis needed from Oaxaca and Chiapas, Mexico, southward to Panama.

Molecular phylogeny of the Sicalis genus (Passerformes, Aves): focus on systematics and conservation
Reconstruction of molecular phylogeny of Sicalis genus based on mitochondrial and molecular markers

Molecular phylogeography of the tundra vole <i>Microtus oeconomus</i> in Beringia.
A Master of Science dissertation at University of Alaska Fairbanks.

Molecular systematics of bipolar Carex species
Research by Dr. Leo Bruederle on Carex species with bipolar distribution patterns.

Molecular systematics of the Pardosa groenlandica species complex (Araneae: Lycosidae): Large sample sizes fail to find
monophyletic species
Master's Thesis research project for Jozef Slowik under mentorship of Derek Sikes.

Mongolian Paleoclimate Project
Used herbarium specimens as a source of pollen for pollen reference slides

Monkshood identification
Comparing Aconitum delphinifolium subsp. delphinofolium and Aconitum maximum

Morphological diversity in <i>Peromyscus maniculatus</i> and <i>P. truei</i> in Yosemite National Park and surrounding a
reas.
Includes photography of skulls and geometric morphometric analysis of landmarks.

Morphological variation in southern short-tailed shrew (<i>Blarina carolinensis</i>).
Project will include external examination of skins, label data, and cranial measurements.

Morphometrics and geographic modeling of Thomomys gophers in California
A study of Thomomys gopher distribution in California based on morphology and soil types.

Mount St. Helens
Post eruption ecological monitoring of animal communities.

Multi gene phylogenetic study of Neotoma
Combining past work of Marjorie Matocq and that of Bradley, and adding more genes.

NMMNHS "Meet the experts" day"
Scientists display and present their research at the NM Museum of Natural History and Science.

Native Plant Inventory in the Bering Glacier Region, Alaska
Floristic Inventory of the Bering Glacier study area

Natural history and systematics of the tundra hare (<i>Lepus othus</i> Merriam) in western Alaska.
http://arctos.museum.uaf.edu:8080/projects/0050

Natural nidality in Bolivian hemorrhagic fever and the systematics of the reservoir species
Natural nidality in Bolivian hemorrhagic fever and the systematics of the reservoir species

Oleaster identification
Comparing Shepherdia canadensis and Eleagnus commutata

Origin of the fauna of Sicily
For comparative phylogeographic work on the origin of the fauna (amphibians and reptiles) of Sicily.

Panama
Hantavirus

Parrya molecular systematic study
remove small amounts of leaf tissue from Herbarium specimens for molecular analysis

Partitioning of space, food, and time by syntopic Peromyscus boylii and P. californicus
behavior; distribution

Patagonian small mammals.
Diversity of small mammals of the Patagonian region, and dynamics of their differentiation.

Pattern and Process in the Radiation of Ground Dwelling Squirrels
Dissertation Project for Bryan McLean, Joseph Cook's student.

Phylogenetic analysis for Geckos of the world project.
This is an NSF funded project with over 600 species of geckos.

Phylogeny and biogeography of the lizard genus <i>Eremias</i>
Phylogeny and biogeography of the racerunner lizards (genus <i>Eremias</i>) in Asia.

Phylogeny of <i>Charina (Lichanura) trivirgata.</i>
I've been working on a nuclear dataset to follow up my 2008 mtDNA study.

Phylogeographic study of house mice, <i>Mus musculus</i>.
A study incorporating tissues from around the world to investigate movements of house mice.

Phylogeography and systematic analysis of western US chipmunks.
Tissues will be used in a project to produce a multi-gene phylogeny

Phylogeography and systematics of the genus <i>Sternotherus</i>.
Part of the NSF funded "Turtles of the World" grant. See correspondence.

Phylogeography of <i>Tamias merriami</i> and <i>T. obscurus</i>
Student project, investigating phylogeographic variation across California for these two species.

Phylogeography of Bufonids in Europe and nearby areas, specifically <i>Bufo viridis.</i>
Phylogeography of Bufonids in Europe and nearby areas, specifically <i>Bufo viridis.</i>

Phylogeography of Microhyla heymonsi
Phylogeography of Microhyla heymonsi in Taiwan, with outgroups from Southeast Asia.

Phylogeography of Mustela frenata.
UNM Ph.D. dissertation under T. L. Yates and F. Smith

Phylogeography of the striped skink <i>Trachylepis striata</i> in southeastern Africa
Phylogeographic study of striped skinks (<i>Trachylepis striata</i>) in southeastern Africa.

Poplar identification
Comparing Populus balsamifera and Populus tremuloides

Population dynamics of small mammals in an oak woodland-grassland-chaparral habitat mosaic
distribution; natural history

Population genetic study of the endangered Pacific Pocket Mouse (Perognathus longimembris pacificus).
A genetic study to assess inter- and intra-population genetic diversity in this group.

Prince William Sound Alaska Exxon Valdez Oil Spill - Shallow Subtidal Research
Specimens associated with research conducted after the Exxon Valdez oil spill.

Rapid diversification and dispersal during periods of global warming by plethodontid salamanders
Rapid diversification and dispersal during periods of global warming by plethodontid salamanders

Rasmuson Art Acquisition Fund
Grant fund available to Alaska museums to purchase contemporary Alaskan artwork.

Relationships between genetic variability and niche dimensions among coexisting species of Peromyscus
demography; genetics; distribution

Reptiles of Honduras
Book

Revision of the genus <i>Plestiodon</i> in Asia.
Matthew C. Brandley PhD dissertation project, UC Berkeley, Departmetn of Intergrative Biology, 2008.

Rollo Beck files, California Academy of Sciences
Materials used: Rollo Beck correspondence and field notes.

Rose identification
Comparing Rosa nootkatensis and Rosa acicularis

Screening small mammals for coccidia.
Fecal samples from arvicoline rodents for coccidia screening.

Seasonal aggression independent of seasonal testosterone in wood rats
behavior; physiology

Sevilleta National Wildlife Refuge Food Web study
Alaina Pershall

Snakes of Arizona
Verifying specimen records for inclusion in book Snakes of Arizona

Social organization and nest co-occupancy in Peromyscus californicus, a monogamous rodent
behavior; natural history

Some effects of deer browsing on chamise sprouts after fire
feeding ecology

Sterile dwarf willow identification
Comparing Salix bebbiana and Salix scouleriana

Striking color variation in tuco-tucos: a role for the melanocortin-1-receptor?
Relationship between coat color polymorphism and allelic variation at MC1R.

Study of long bone growth and vascular supply to the femur in non-mammalian vertebrates.
Histological sampling and high-res synchrotron micro-CT scanning of Crocodilian and Varanid Femora.

Systematic revision of Leptophis ahaetulla
Systematic revision of Leptophis ahaetulla

Systematics of Caryophyllaceae
Remove leaf tissue for molecular analysis (by Dr. Wagner)

Systematics of Dermanura (chiroptera).
This study will use morphology, microsatellites, AFLP, cyt-b to resolve species limits.

Systematics of Ototylomys
Systematics of Ototylomys.

Systematics of South American Dipsas
Systematics of South American Dipsas

Systematics of the genus Ochotona.
Multi-mitochondrial gene phylogeny.

Taricha torosa (California newt) response to fire
natural history; physiology

The California ground squirrel: A record of observations made on the Hastings Natural History Reservation
natural history

The adrenal cortex and its hormones in the California ground squirrel, Spermophilus beecheyi
physiology

The distribution and phylogeography of the Alaskan hare (Lepus othus).
Michelle M. Cason's master's degree thesis research.

The dusky footed wood rat: A record of observations made on the Hastings Natural History Reservation
natural history

The effects of an artificial water supply on free-living Peromyscus truei
natural history; physiology

The energy budget of a lizard on a tree trunk
behavior; physiology

The history of U.C. field science and the origins of the NRS
One of the chapters in a book about the U.C. Natural Reserve System.

The internal anatomy of home range
movement; behavior

The major histocompatibility complex (MHC) diversity in wild canids.
Tissues will be used in a study looking at MHC diversity in wild canids.

The major histocompatibility complex (MHC) diversity in wild felids.
Tissues will be used for a characterization of MHC in cats.

The monogamous mating system of <i>Peromyscus californicus</i> as revealed by DNA fingerprinting
behavior; genetics

The stable carbon and nitrogen isotopic composition of East Beringian grasses
Removed leaf tissue from herbarium specimens for iotopic analysis.

The status of the California tiger salamander (Ambystoma californiense) at Lagunita: A 50 year update
natural history; movement

The times of mating and oviposition of the western fence lizard, Sceloporus occidentalis occidentalis
natural history

The use of water as bait for Microtus californicus
behavior

Three Parameters Plus, Inc. 2013 Sheep Cr. Survey
Botanical survey of AEL&P powerline above Sheep Creek valley, Juneau AK

Three Parameters Plus, Inc. 2013 Sheep Creek Survey, Juneau
Botanical survey along AEL&P powerline above Sheep Cr. valley, Juneau, AK

Three Parameters Plus, Inc. Sheep Creek Botanical Survey, 2013
Plant collections from a 2013 survey done by 3PPI, Sheep Cr., Juneau AK

Three Parameters Plus, Inc.-2014 Annex Creek Botanical Survey
Miscellaneous collections from this project.

Trichome production and water use efficiency of Arabidopsis kamchatica
11 Herbarium specimens of Arabidopsis kamchatica, 1 leaf of tissue was taken from each specimen

U.S. Fish and Wildlife Service, Alaska Maritime NWR - 2013-2014 Botanical Survey
Collections made in the Aleutian Islands by Stephen and Sandra Talbot

U.S. Forest Service-Alaska Region
Collections made by Brad Krieckhaus, 2011 and 2012

USFWS Kodiak National Wildlife Refuge-2014 Botanical Survey
Collections by S.Studebaker in KNWR and near Kodiak town

United States Forest Service, Alaska Region, Tongass NF
Plant collections from SE Alaska contributed by Mary Stensvold and Brad Krieckhaus in 2015.

Urban Winter Roost of Euderma maculatum
Acoustic monitoring of an Albuquerque Warehouse

Valles Caldera National Preserve Project
Bob Parmenter PI; Cervus elaphus samples

Video series on climate change, National Science Foundation
Materials used: Various photo retakes from Grinnell Resurvey Project, available online.

Viola identification
Comparing Viola renifolia var. brainerdii and Viola epipsila subsp. repens

Water stress of free-living Peromyscus truei
natural history; physiology

Wintergreen identification
Comparing Pyrola chlorantha and Pyrola grandiflora

Work with vertebrate animals on the Hastings Natural History Reserve.
demography

Zooarcheology (Anthropology 415)
Undergraduate class in the identification of animal remains from archeological sites.

**Comment by campmlc** [comment]
I would argue that there is considerable information in these projects - hiding them from everyone including their authors serves no purpose. Why not just delete all 200, if they really have no value? And if they have value, then they need to be searchable using project search.  If the descriptions need more information, then we should send a notification to the project creators. But personally, I find it difficult o come up with 100 character project descriptions in many cases, given the information I have available. And to my mind duplicate projects are a bigger problem.

**Comment by dustymc** [comment]
My job will never be to delete data. I presume some of these are works in process.

In order to make a duplicate, an operator needs to ignore all the red warnings, create a short project, ignore the red stuff again so the search fails, then do it all again. How does that happen/what can we do about it?

Perhaps I don't understand the process - why are we creating projects if we have little or no information available?

This seems like something that needs discussed via skype/phone/person with the AC; someone should arrange periodic issue discussion sessions.

**Comment by campmlc** [comment]
The duplicate projects happen when a short project exists but does not show
up on a search because it is too short to come up in the search results.
Then I create a brand new project for the same thing, because I cannot find
the older project someone else already created.
