### ISSUE TITLE
part counts needed

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#7743]
As part of our reaccreditation process, we need counts of the number of objects in each of our collections, i.e., the number of parts per catalog record. I tried "View/Download - Parts", but this does not pull quantity. I also tried "Manage - Parts", which pulls the counts, but does not include a way to download the data.

Is this a new feature/addition to "View/Download - Parts" that I should request, or something that needs to be pulled by @dustymc? This is something we need for each CHAS collection.

Thanks!

**Comment by dustymc** [comment]
>new feature/addition to "View/Download - Parts"

Sounds right.

**Comment by droberts49** [comment]
Hi Dusty -- this data download is not working correctly. For example, I downloaded the parts for our ornithology collection; see attached file. In the download, it created a line for each loan the specimen part is affiliated with. So, for [CHAS:Bird:15305](https://arctos.database.museum/guid/CHAS:Bird:15305), which has 1 "part" (skin), there are actually four lines in the dataset, one for each loan of that specimen part. That is artificially inflating our specimen numbers in the dataset.
[chas-bird-download_2024-05-10.xlsx](https://github.com/ArctosDB/arctos/files/15279083/chas-bird-download_2024-05-10.xlsx)

Can you please help fix this so that it is an accurate reflection of the parts associated with each catalogue record.
