### ISSUE TITLE
dead columns in search results

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#7757]
ref https://github.com/ArctosDB/arctos/issues/6928#issuecomment-1839089357

* feature
* island
* island_group
* quad

Those are I believe mapped to things that can never resolve to data. I'll remove them from search results options and FLAT unless someone proposes some viable remapping in the very near future.

**Comment by mkoo** [comment]
A couple of comments so I wont forget-- overall always good to clean-up since these in particular have new better places (btw before anyone misunderstands, no records are changed in this request):

    feature 
- this legacy attribute needs to be tackled by the Geog Comm; it's outlived its former usefulness as a spatial grabbag and we can do so much better! see below
```
    island
    island_group
```
- consolidate into a searchable locality attribute or make the Associated Names data easier to work with in the search fields. Can we rely on Geography shape Name for our needs to search in islands and island_groups?! maybe this doesnt even need this here?

```
    quad
```
- already in loc attributes and easier to search on there. I have my preferences to find 15 m vs 7.5 but can live with this too
Thanks!
