### ISSUE TITLE
crazy agent data

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#7771]
The [event](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctagent_attribute_type#event) agent attribute should have some constraints, but there's some surprising data:

```
                   agent_id                    | preferred_agent_name  | attribute_type | attribute_value |    creator     |     created_timestamp      
-----------------------------------------------+-----------------------+----------------+-----------------+----------------+----------------------------
 https://arctos.database.museum/agent/21351255 | Dennis Grisco         | event          | birth           | Alison Whiting | 2024-03-02 16:43:31.436335
 https://arctos.database.museum/agent/21351255 | Dennis Grisco         | event          | death           | Alison Whiting | 2024-03-02 16:43:31.436335
 https://arctos.database.museum/agent/21351900 | D. Frank McKinney     | event          | birth           | Alison Whiting | 2024-03-05 18:43:44.074551
 https://arctos.database.museum/agent/21351900 | D. Frank McKinney     | event          | death           | Alison Whiting | 2024-03-05 18:43:44.074551
 https://arctos.database.museum/agent/21351271 | Robert Forest Wagoner | event          | birth           | Phyllis Sharp  | 2024-03-05 11:45:18.211812
```

@byuherpetology @sharpphyl do you have any idea how that might have happened? 

Hopefully some short-lived bug or forgotten experiment and I can just clean up and move on....

**Comment by genevieve-anderegg** [comment]
I switched Robert Forest Wagoner's 1934 event date to "born", to reflect what we know of him: https://conchology.be/?t=9001&id=31210 Unsure as to his current status.
![image](https://github.com/ArctosDB/arctos/assets/83782023/065f1bb2-ada9-498e-b890-c5d003fe33ef)
Does that fix the weirdness?

**Comment by dustymc** [comment]
@genevieve-anderegg thanks, they will all need cleaned up at some point, I'm mostly interested in how this happened though (eg is there some bug still in the UI?).

**Comment by genevieve-anderegg** [comment]
It could be because there is a range for these dates presented. If the attributes are `dead,alive,died,born`, I kind of think it makes sense for `dead, alive` to have ranges, because it's a statement of "being", but `died, born` are singular events that happen on one day (hopefully). So for Wagoner the only info we have on his is he was born in 1934, but it is likely he is no longer alive. So the attribute value `dead` makes sense, but then because we are presented with a date range it's a little confusing. So "1934" for "began" date makes sense because that was when he was born, but we don't know when he died.
That's my reading of it. The UI is a little confusing. Maybe `born` and `died` should only have one date value presented instead of a range?

**Comment by Jegelewicz** [comment]
@dustymc when I look at https://arctos.database.museum/agent/21351900

![image](https://github.com/ArctosDB/arctos/assets/5725767/632aace2-f9dc-4143-8c62-5e0993647429)

he has two dead dates

![image](https://github.com/ArctosDB/arctos/assets/5725767/3d81d66e-913e-4f31-81a0-5aa2575c74ac)

but trying to change one results in

![image](https://github.com/ArctosDB/arctos/assets/5725767/b3897ce8-6708-4364-a345-7332109414d0)

I can try changing both, which would possibly work, but I'll leave it for now.

Also wondering if this guy came in through the bulkloader and maybe there is some check missing there?

**Comment by Jegelewicz** [comment]
@genevieve-anderegg how did you guys get Birth in there? It isn't in the dropdown!

**Comment by genevieve-anderegg** [comment]
I'm not seeing it. Does @dustymc have that in behind the scenes for "born"?

**Comment by Jegelewicz** [comment]
That's what we are trying to work out - how did these things get birth when apparently nobody can select it....

**Comment by byuherpetology** [comment]
I think that I entered both Grisco and McKinney by hand rather than through the bulk loader. When you create an agent, there is no range of dates available for these events, so I don’t think that could have been the problem. I don’t understand why when I look at the agent summary it says birth and death with the dates, but when you go to edit the agent you see both dates under dead. I know that I entered the dates under birth and death, I have never used the dead option.

**Comment by Jegelewicz** [comment]
@dustymc see also https://github.com/ArctosDB/arctos/issues/7703

**Comment by Jegelewicz** [comment]
So I maybe remember - I need to verify [D. Frank McKinney](https://arctos.database.museum/agent/21351900) with https://www.wikidata.org/wiki/Q21914417

**Comment by dustymc** [comment]
Thanks @byuherpetology, that's the clue I needed. I think I fixed a bug (but apparently not quite quick enough!) on the (recycled, multiple times) create form, some old (now aliased) terms there are AWFULLY suspicious....

I'll clean these data up ASAP, and I think the problem no longer exists.
