### ISSUE TITLE
Bulk add part attribute fails

### ISSUE THREAD

**Issue by cjconroy** [ArctosDB/arctos#7924]
I have a series of phalli that are in arctos as preserved in formalin and preserved in ethanol. Now, they are cleared and stained. I searched for the specimens, went to manage parts, used option 4 to add cleared and stained attribute to all of them. Click the button. Nothing happens. Is this a known problem? I tried this in front of Michelle Koo and she did not see any mistakes on my part.  MacOS, Chrome. MVZ specimens 233124, 233130, 233131, 235821, and 235842. 

<img width="1028" alt="Screenshot 2024-07-09 at 1 50 23 PM" src="https://github.com/ArctosDB/arctos/assets/5749672/3a47033c-347a-4217-9049-3fb721672bb0">

**Comment by dustymc** [comment]
I did

<img width="979" alt="Screenshot 2024-07-09 at 14 54 26" src="https://github.com/ArctosDB/arctos/assets/5720791/a9e8067e-189b-4ad4-ae6e-6e188f9d2898">

and it came back with

<img width="935" alt="Screenshot 2024-07-09 at 14 54 39" src="https://github.com/ArctosDB/arctos/assets/5720791/32faa47e-2867-4951-a233-c0b6244d57c9">

--- 

>Chrome

Yea, sounds like it....

**Comment by dustymc** [comment]
>tools just look broken 

They're not, they work for me (and so should work with a standard browser on a decent network within certain limitations - a fuzzy line, but certainly a few records are on the safe side of it).

(I can't ask you to try in test because https://github.com/ArctosDB/internal/issues/326).

>what is the solution

Component loaders are much more scalable (the expensive stuff can happen in bite-size chunks), are easier to debug (the important stuff happens where I can see it, not in your browser), and can do all the things the 'manage' tools do. I'd fully transition to them if that was up to me.

**Comment by dustymc** [comment]
Noted in https://github.com/ArctosDB/arctos/discussions/8014, nothing else to do here.
