### ISSUE TITLE
"split from lot" relationship

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#793]
Any comments on the idea of "split from lot"? I have immediate need for this relationship. However, I need to link to the catalog number of the source lot, so a more appropriate reciprocal relationship could be "same lot as", unless anyone has a better idea.

As an example, I have whole frozen fish and fish tissues from individuals that were cataloged as part of a lot. I need to create the relationship between the original lot cataloged item and the individual fish removed and cataloged separately for genetic analysis.

So the relationship could be:
Source cataloged item: MSB:Fish:4806, relationship "same lot as"  individual fish MSB:Fish:99108  and vice versa.

The alternative is to specify which is the source lot and which the "split" cataloged item, e.g.
MSB:Fish:99108 = "split from lot" MSB:Fish:4806, and MSB:Fish:4806 "source lot of" MSB:Fish:99108

**Comment by campmlc** [comment]
I propose a modification:  "split from lot" and "source lot of" as the reciprocal terms.

**Comment by campmlc** [comment]
Created  "same lot as" relationship, with "same lot as" as the reciprocal.

**Comment by Jegelewicz** [comment]
I'm reviving this because I think the original option proposed by @campmlc was better. I think it makes life easier if I can see which specimen was split from an original lot and which remains the original lot number. Putting "same lot as" on the original lot with a relationship to the split item creates a connection but doesn't specify which was the original lot, which may be important if there are publications related to the original lot. Any objections? How many currently existing relationships would this affect and how difficult would it be to figure out what the relationships should be? Shoot me down if this is crazy, but give me a good reason why please!

**Comment by dustymc** [comment]
>publications related to the original lot.

Meh, I'd think they'd be pretty low-quality at absolute best. Any actual examples?

>objections

Not exactly objections, but changing relationships is a bit of code (to generate the reciprocal notification, and I think some in clone-land). This isn't entirely arbitrary, and I'm not sure I see any real benefit to a change.

```
UAM@ARCTOS> select count(*) from coll_obj_other_id_num where ID_REFERENCES='same lot as';

  COUNT(*)
----------
      5074

```
