### ISSUE TITLE
allContainerLeafNodes/add to loan is broken

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#802]
Should use guid_prefix instead of collection

**Comment by campmlc** [comment]
Dusty,
I am still having the problem of trying to "Add All Items To Loan and update part disposition to "on loan"
Collection" from the "show all collection objects in this container" tab in object tracking. Because I have access to more than one collection, the dropdown menu does not differentiate which mammal or parasite collection to choose from in order to add the loan number.
![screenshot 2016-01-20 13 27 01](https://cloud.githubusercontent.com/assets/14808196/12462169/19e06566-bf7a-11e5-81fc-2e0646711895.png)

**Comment by dustymc** [comment]
It's fixed, just not pushed to production yet.
