### ISSUE TITLE
Request barcode series + help getting started with object tracking

### ISSUE THREAD

**Issue by asemerdj** [ArctosDB/arctos#8080]
Hello,
I'm not sure if this is the right place to ask, but how do I go about reserving a barcode series and do you have tips for getting started with object tracking?

Thank you!
Alyssa

**Comment by campmlc** [comment]
@asemerdj Hi Alyssa, we are in the process of updating the documentation and workflows, but I'd be happy to set up a zoom to go over the steps and answer any questions. What is your timeline?

**Comment by campmlc** [comment]
Yes, barcoding at the same time as inventorying would be ideal, as you only having to pull out the samples from the freezer once rather than twice. You can also scan the barcoded samples into Arctos object tracking at the same time, so that you don't have to rely on an Excel spreadsheet. It would definitely be good to have a call before you get too far into the process. Would next Wednesday Sept 11 after 1pm MDT work?

**Comment by campmlc** [comment]
Sounds good. I'll send a link. 2pm MDT, correct?

**Comment by LitsaWoo** [comment]
Hi Mariel! Would it be possible for Andrew and I to piggyback off of this meeting? We're about ready to get started with object tracking as well. If not we can always set up another time to meet with you

**Comment by campmlc** [comment]
Of course! You should be able to see the link on the Arctos calendar? Let me know.

**Comment by dustymc** [comment]
Discussed via zoom https://docs.google.com/document/d/16EzdTupMg27GJ9OJjh769GeW9o5cxtPSJh96w9uSItY/edit

Important points from my perspective:

* please barcode early/everything if at all possible; backlog is no fun
 * claim a series by filing an issue (or using the UI)
* the current unique index is on (barcode, institution) - it's fine to use eg ``P[A-Z0-9]`` even though some other Arctos institution might also be using the same or an overlapping series
   * (history: https://github.com/ArctosDB/arctos/issues/6789)
   * possibly documentation needs adjusted?
  
 Tentatively closing.
