### ISSUE TITLE
Help needed in Arctos: making a container without bulkloading?

### ISSUE THREAD

**Issue by happiah-madson** [ArctosDB/arctos#8111]
We are making freezer boxes in Arctos object tracking. Sometimes we need to just one one box at a time for Reasons. Is there a way to create a freezer box in object tracking _without_ using bulkloaders? 

@falco-rk @campmlc @dustymc

**Comment by dustymc** [comment]
There's not. There used to be, it *always* made messes. Creating containers should be part of some near-sacred procedure (because presumably they'll involve barcodes, and procedures should likely be examined if they don't).

* Create 50 (500000,, whatever..) [labels](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcontainer_type#container_label) for eventual Reasons
* Pull one out and edit the container object when a suitable Reason shows up

**Comment by happiah-madson** [comment]
Understood. At least we are not crazy.

**Comment by campmlc** [comment]
Permissions now are more stringent for creating positions, for example, so it makes much more sense to create boxes a bulkload at a time. We create them and fill several racks with empty boxes for the students to grab when they need one. They then only have to add a label and scan it where it needs to go; the box itself, it's barcode, dimensions, positions grid etc are already created, standardized and consistent. And that way students don't accidentally add positions to a cryovial.
