### ISSUE TITLE
component loader priority

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#8114]
From https://github.com/ArctosDB/dev/issues/53#issuecomment-2353461079 on behalf of @campmlc 

Is there a way to allow the loader to automatically prioritize small, faster requests over larger, slow ones? The primary reason for needing to change the processing order is to expedite a small, urgently needed process, such as a bulkload for a loan that needs to go out that day, over a larger, slow request that will clog up the pipeline for hours or days.

**Comment by dustymc** [comment]
>automatically

Short answer: no.

"small" and "fast" do not necessarily have any correlation. The machine can't know what's a priority for any user at any time, nor how that compares to any other user's priority. Assuming that large requests have lower priority does not seem reasonable.

I'm not sure expectations align with resources; can that somehow be clarified (or built up, or ??)?

**Comment by campmlc** [comment]
Could users indicate their level of urgency? E.g. 1) need this within 1 hr 2) need this by end of day 2) need within 24 hours 3) no rush

**Comment by acdoll** [comment]
I have avoided messing with this because of the statement "Be courteous; do not de-prioritize active recently-prioritized runs without first talking to the user."  However, I saw things re-prioritized over my uploads repeatedly this week by multiple operators. 
We don't have the ability to see who owns the things processing in the loaders - we can only see what's in the loaders for operators that have permissions in our collections. There's no way we can reach out to the user if we don't know who is loading the data. Is it possible to add a column to this table with a list of operators (and/or their emails) with data set to autoload? Kind of like what's on the BulkloadSpecimens page.

**Comment by campmlc** [comment]
We also need to adopt some sort of rule system. There were several loads of over 5000 records put at the top of the list at the beginning of the week. I need to be able to load 50 items for a loan and have it load within an hour;  I can't wait a week for 10000 locality attributes to finish loading.

**Comment by dustymc** [comment]
>don't have the ability to see who owns the things processing in the loaders

Yep, that's actionable, I'll open a dev issue.

> load within an hour

Nothing unlimited resources can't solve....

I still can't make sense of what seems like an assertion that large jobs can't be a priority. They absolutely can be, and I can think of a bunch of scenarios where locality attributes could be extremely critical. I have no idea if that's what's actually going on or not, but I don't think there's any situation in which one can safely assume that someone else's job is of lesser importance than anything else.

**Comment by campmlc** [comment]
Given that a large job that takes days can block small jobs that take minutes, I do think there is reason enough for some sort of priority so that one collection or operator does not hog the system and prevent other collections from doing any work. If this isn't possible, then we desperately we need to find a way to have more than one pipeline to load records through the component loader.

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/internal/issues/351
