### ISSUE TITLE
Help needed in Arctos - How arctos handles passages in cell lines

### ISSUE THREAD

**Issue by RJSS8** [ArctosDB/arctos#8118]
# Tell us what you are trying to do 

Some upcoming collections I will be working for have cell lines and register there passages I want to know how Arctos handles passages in cell lines, how that information is loaded, and how it is organized.

**Comment by dustymc** [comment]
Based on my extensive knowledge of this subject (I skimmed the AI summary of https://www.atcc.org/-/media/resources/technical-documents/passage-number-effects-in-cell-lines.pdf ....) - could this be derived by counting https://arctos.database.museum/info/ctDocumentation.cfm?table=ctpreparation_method#subculturing?

Please elaborate on the shape of the data (applies to parts? number or category or descriptive? etc. - examples are always useful) if I'm lost or an explicit assertion is needed for some reason.

A scholarly reference would be very useful as well.

**Comment by dustymc** [comment]
@happiah-madson

**Comment by happiah-madson** [comment]
Okay, very belatedly, I am here. In our previous database we had a separate bacteria section where we tried to track passages. It went very mediumly and was dropped from further documentation. Instead of tracking passages we only accession things into the collection once there is a bacterial stock that is going into a freezer. If all that @RJSS8 is looking to track is a _count_ of passages, then verbatim attribute could be an option. If it's the number of the passage, that seems like it could be a processing number.

**Comment by happiah-madson** [comment]
Yeah, verbatim attributes is how we handle specific attributes that are used for a single accession but that is probably not widely present in all our data. If all of your cultures are going to have a "number of passages," than I would suggest asking for a new attribute field.
