### ISSUE TITLE
Default search results 10 rows, should be all results

### ISSUE THREAD

**Issue by amgunderson** [ArctosDB/arctos#818]
A search result rarely has ten or fewer specimens, the default number of rows should be all results or some large number that doesn't break Arctos.

**Comment by jtgiermakowski** [comment]
I see your issue!

**Comment by campmlc** [comment]
I agree. We should increase the default (5000?) and/or move the tiny little
box for how many rows to display to up top and make more prominent.

**Comment by dustymc** [comment]
I don't think "all" is wise for several reasons - it increases network activity (for which some users are charged), impacts performance (due to network limitations, available memory, etc.), and is very likely to eat browsers (leading to the inevitable conclusion that "Arctos is broken"). Arctos itself can support any number of returns, the bottleneck is in the user's environment. I bumped the default to 100 (for post-7.3). 500 or 1000 might be OK if that's still irritating; re-open this if we want to explore that (or try various settings on eg, a phone on a flaky 3G network and report back).

Manipulating the controls deserves it's own Issue. (It's at least somewhat non-trivial; that's the tradeoff when using a plug-in library like we do versus writing our own code, which would come with different costs.) And please include screenshots if you open that Issue - the controls are the same size as everything else for me??
