### ISSUE TITLE
identifier type ASK - numeric?

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#8199]
ASK was added through https://github.com/ArctosDB/arctos/issues/1648 without control. There are some non-numeric/nonsense data causing errors/people to fail at finding:

```

arctosprod@arctos>> select display_value from coll_obj_other_id_num where other_id_type ='ASK' and is_number(display_value)=0 order by display_value;
    display_value     
----------------------
 1066a
 1066b
 1116 and BJB690
 1117--BJB691
 4062/ASK4860 embryos
(5 rows)
```

If that's intentional, this can be closed. If you'd like to support numeric search operations, clean those records up, let me know, and I'll add datatype control.

@rwilhoyt

**Comment by rwilhoyt** [comment]
Yes, I'd like to investigate our files and clean those records up since those definitely look like some type of typo or something that can go in remarks/parts/other identifier. 

Would datatype control impose limits to entering an ASK identifier to prevent this in the future? Basically in data entry, ASK numbers would be limited to integers and exclude non-numeric characters? If so, that sounds like a great plan.

**Comment by dustymc** [comment]
>ASK numbers would be limited to integers 

I can do whatever you can define. It will be done as a data type control so it will apply everywhere, not just data entry. Limiting to integer is simple, probably sufficient for most things, and what other similar types have done, but the roles can be more complex if necessary.

**Comment by rwilhoyt** [comment]
I think limiting ASKs to integers should suffice for our purposes!

**Comment by dustymc** [comment]
Agreed, let me know when you've cleaned up (or if I can help) and I'll add the control.

**Comment by rwilhoyt** [comment]
Records are cleaned up!

**Comment by dustymc** [comment]
constraint added
