### ISSUE TITLE
Request - deprecate part2container.cfm

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#8220]
Help us understand your request (check below):

**Describe what you're trying to do** 

[Container: Add Parts](https://arctos.database.museum/part2container.cfm) uses a lot of code that isn't used by anything else, and I don't think it can contain enough information to use safely in most cases. The parts tab from the guid page carries all necessary information and now can do what this app was developed to do ("install" parts into containers). [Part: Bulkload to Containers](https://arctos.database.museum/loaders/BulkloadPartContainer.cfm) provides a bulk option.

Can we drop this form, or is it doing something useful? 

Here's all access in the last year - I don't think any of this looks like usage.

```

      username      | count 
--------------------+-------
 acdoll             |     1
 AdrienneR          |    15
 aerochild          |     2
 ajlinn1910         |     7
 alisonwhiting      |     1
 aolivas            |     1
 aren               |     1
 asemerdj           |     8
 Bcarroll           |    11
 campmlc            |     7
 camwebb            |     9
 ehertger           |     4
 erincanney         |     9
 esdearmon          |    12
 hannahb2402        |     5
 jecramb            |     2
 jegelewicz         |     2
 jrykken            |     1
 jtgiermak          |     8
 jvanveldhuizen     |     1
 jweller            |     1
 KatherineLAnderson |     1
 kderieg            |     3
 ksamlaska          |     7
 ktarango1          |     1
 lexibaca           |     1
 libby              |     1
 litsawooten        |     4
 lnkeller620        |     2
 mbreslin           |     3
 mclean             |    12
 mgwyatt            |     3
 NICOLERIDGWELL     |     3
 oschapman          |     1
 rosiepoulin        |     7
 rpianka            |     1
 wilsonp2           |     2
 xzhang26           |     4
(38 rows)
```

**Comment by dustymc** [comment]
Let's call https://github.com/ArctosDB/arctos/issues/8230 an endorsement of this.

**Comment by campmlc** [comment]
The object tracking committee met today and agreed with removal pending approval from UAM operators who may still be using it: @megulbranson @DerekSikes @amgunderson @cjconroy

**Comment by amgunderson** [comment]
This is the page I asked for to barcode all our unbarcoded tissues and how we barcoded all our unbarcoded skins and skeletons. I know there is a bulkload form but that just adds more steps to the process - you have to add all the data to the bulkload form then bulkload it then troubleshoot that bulkload file because some extra space at the end of roll x column y made it fail producing an incomprehensible error page that must be made into a github issue in order to be explained. Rather than just typing the catalog number in, choosing a part, and scanning the container barcode. 

This page/widget represents everything I like about Arctos. I needed a tool to manage my collection, Dusty made it, it works great. The alternatives are complicated, require more clicks and typing, saving of extra files and loading via a bulkload page that is not simple. Calling for it's removal is everything a do not like about Arctos - putting collection management and managers second to the software's whims and convenience. Arctos is supposed to work for us, not the other way around.
I will someday need to barcode hundreds of parts that are still unbarcoded, this is the best way to do that. 

I think all bulkload processes should be made into exactly this kind of form that asks for only the needed data and doesn't require you to understand the definitions of a hundred different irrelevant fields in order to craft a successful bulkload file.
Please do not remove it.

**Comment by campmlc** [comment]
I can understand that. If it is in use, then I support keeping it. We just need to rename the bulkload version to be consistent #8229

**Comment by amgunderson** [comment]
I would suggest this page is not getting use because new collections are being pushed to bulkload everything. This page works perfectly if you have a tray of vole skins and skeletons that you are assigning barcodes to right in front of you. You can type the catalog number of the specimen you are holding into that field, choose the part from the dropdown menu (no spelling errors or debate about whether this is part skeleton or part whole organism etc), then scan that barcode to get a green confirmation that you just did digitally what you just did physically to the specimen. Most importantly, any student tech can do this all day without having to consult with a mentor or Dusty or Teresa or ME! about which fields need what values. The form chooses from existing tables, asks only for the necessary info - it is simple and easy and I am certain if collection managers knew about it they would be less reluctant to take on the task of barcoding their collections.

**Comment by campmlc** [comment]
We don't use the single record tool for adding tissue parts to cryovials because we have a different protocol that accomplishes that during data entry. For legacy cryovials and boxes, we use the bulkloading tools to minimize handling and warming of vials. But I can  totally see the usefulness for the application @amgunderson describes.
