### ISSUE TITLE
having trouble logging in to transfer files to TACC

### ISSUE THREAD

**Issue by asemerdj** [ArctosDB/arctos#8234]
Hi Dusty,
I'm getting access denied messages when I try to log into tacc through WinSCP. I double checked my password etc, so I was wondering if anything changed with the host name or something? 
![image](https://github.com/user-attachments/assets/31d7112b-b8f9-4086-b4ec-7e1e06b30192)

Thank you,
Alyssa

**Comment by dustymc** [comment]
Possibly this (but I don't use GUIs or windows so probably can't be very helpful!)

SMS Delivery Issues for MFA
From: Mark Brueschke

The service which provides MFA tokens via SMS is experiencing nationwide issues. This is preventing some users from logging in if they are unable to receive the message in a timely manner.  

Unfortunately, there is not ETA for when this service will be restored to full functionality.

If you are having problems logging in due to delayed SMS messages, you may switch to an MFA token app such as Duo or Google Auth. We provide instructions for setting up your MFA here: https://docs.tacc.utexas.edu/basics/mfa/

To manage your TACC Announcements subscriptions, please visit https://accounts.tacc.utexas.edu/subscriptions
