### ISSUE TITLE
Request - possible new(ish) record attribute - stomach content

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#8255]
Help us understand your request (check below):

- [x] a new term for data entry or management 

**Describe what you're trying to do** 

Create an appropriate migration target for https://github.com/ArctosDB/code-table-work/issues/48, which involves

* an attribute with an inconsistent spelling, and
* a definition which conflicts with the term

at least @ebraker has indicated that 'stomach content' (not gut) is the intent, so I think we need the new term. 

These are NOT my data and I'm also very open to the idea that this isn't the correct approach at all - eg possibly this is better recorded as part of https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#stomach_content: disposition makes it easy to indicate when the part isn't actually available and that would very likely make the information more discoverable, but I'm totally open to about anything that doesn't involve inconsistent terms that conflict with their own definitions.

## proposed term: 

stomach content

## proposed definition:

Content of the stomach.

## references

* https://www.sciencedirect.com/topics/immunology-and-microbiology/stomach-content
* https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#stomach
* http://purl.obolibrary.org/obo/UBERON_0000945

HELP!

**Comment by campmlc** [comment]
Can we get a list of records by collection that have either the attribute or the part name? 
At MSB we have both.

**Comment by Jegelewicz** [comment]
I am working on a bunch of attributes for @jebrad and many of them would be loaded as the stomach contents [[ link ]](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type#stomach_contents) attribute.

> possibly this is better recorded as part of https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#stomach_content: disposition makes it easy to indicate when the part isn't actually available and that would very likely make the information more discoverable

I see that point, but I think that the community generally does not like to record parts when none were prepared. My opinion, if anyone wants it, is that the attribute is a great place to DESCRIBE the stomach contents, while the part indicates that someone could actually look at some stomach content that was prepared for that purpose.

I agree that the definition of this term is not correct, but I don't agree that changing the pluralization is a good idea - why make that disruption? the following plurals exist in the code table:

* dimensions
* inscriptions and marks
* keywords
* materials
* unformatted measurements
* user contributed comments

and these make sense because the values can be plural or combinations of things.  I suggest instead just updating the definition for this attribute:

stomach contents - Description of the contents of the stomach.

This also creates a separation between the part (stomach content) and the attribute (stomach contents)

If that is not acceptable, then I would suggest:

stomach content description - Description of the content of the stomach.

**Comment by campmlc** [comment]
I support the approach be suggested by @Jegelewicz .

**Comment by dustymc** [comment]
This is premature and distracting, closing.
