### ISSUE TITLE
can search results be color-coded by species? --followup to #823

### ISSUE THREAD

**Issue by jsmetzgar** [ArctosDB/arctos#828]
For multi-taxon searches it would be extremely useful (especially for educational activities) to have results color coded on the map by species. Can this be added to the map of results on the search results page?

**Comment by dustymc** [comment]
This seems possible, but there are some complications/considerations.

1) Adding text (eg, species) to the markers data object (and more markers because the text is a denormalizer) requires some additional browser resources - limited experimentation suggests roughly tripling (~800 records goes from 6932K to 21194K and 48 to 140 markers, ~8000 records goes from 17772K to 62749K and 486 to 1984 markers). That will probably lead at least some users to "Arctos is broken" when their browser runs out of resources, so I think we'd need something more elegant (=expensive to build and maintain) on the server side. (The current results map is built while the page loads, which is possible because it's generally very small - I think this would add enough complexity to require an asynchronous operation.)

2) Coloring by species seems like a limited-utility solution; some users will be more interested in {not-species}.

3) Really more of (2), but I'm not sure what dropping multiple different-colored dots on the same coordinates (eg, because someone searched by locality, collector, etc.) will look like - seems potentially confusing.

Is this something we could pass off to BerkeleyMapper? It currently seems limited to coloring by collection (which IIRC arose because of a similar request - some users, probably those wanting to borrow material, think that's the important split), but expanding capability there (eg, add a color-by-whatever option) might be trivial??

If not, should we explore a "color by {pick an option}" option on Arctos, or just color by species, or ????

**Comment by dustymc** [comment]
BerkeleyMapper knows about this, should provide a solution at some point.
