### ISSUE TITLE
Help needed in Arctos - Creating Storage Locations as Containers: Barcode series

### ISSUE THREAD

**Issue by Kmullineaux** [ArctosDB/arctos#8304]
# Tell us what you are trying to do 

I am attempting to record the locations of objects in storage/on display in Arctos for internal collection management purposes. I'd like internally approved users to be able to see where in storage an item is if they need it. Based on the literature, it seems that I need to claim a barcode series and then use that series to create containers, i.e., each barcode will be assigned to a room, shelf, or cabinet as needed, and then I can place individual records 'in' containers in Arctos to note where the object is in storage or on display. Is this correct? 

I'm sorry if I'm misunderstanding the process. My institution doesn't have the resources to place barcodes on all our specimens at this time. If there is a better way to track object locations that you suggest, please let me know! 

# What are relevant pages in Arctos
**Provide a link to or a description of the page where you need help.**

**Comment by dustymc** [comment]
One alternative to containers is https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecpart_attribute_type#location (a free-text field associated with parts).

Most of the work of barcoding seems to be getting the individual parts associated with machine-readable labels (after which they can easily be scanned into other containers). I've usually thought that partial barcoding was not a good investment because of this, but I believe it's working for OGL - maybe @happiah-madson will chime in.

**Comment by Kmullineaux** [comment]
Thanks for your reply! I was aware of the Parts option, but I was hoping there was a more centralized, searchable alternative for inventorying. Maybe one day we can use the barcoding system.

**Comment by AJLinn** [comment]
Here at UAM:EH we migrated into Arctos before we used barcodes. As a result, we added the part attribute location. It's a super easy field to use, can be searched for on the main page, can be shown in the search results, which can then be sorted by that column (you just have to customize your search and results options).

We also use barcodes, but don't have the staffing power to barcode the entire collection all at once, so we just do it as new collections come in, as we use objects in transactions, and when putting away those objects we try to barcode the rest of the materials in that drawer or shelf. When we scan an object into a location, we ALSO manually enter the location into the part attribute field, which adds one piece of redundancy, but the usefulness of having it in the search results makes up for that extra step.

(Search & Results customized options to search for and show results of part remark location)
<img width="1323" alt="Screenshot 2024-11-15 at 5 40 05 AM" src="https://github.com/user-attachments/assets/f61ab222-b715-4d41-b80b-9bab6832845b">

(How you search for location once you've customized search results)
<img width="1323" alt="Screenshot 2024-11-15 at 5 38 20 AM" src="https://github.com/user-attachments/assets/79cd3834-4e9e-43ea-8a95-41bd214bc6ae">


(Search results with part location activated & sorted by location code)
<img width="877" alt="Screenshot 2024-11-15 at 5 28 45 AM" src="https://github.com/user-attachments/assets/f473e74b-fae2-4564-9d45-21c61353deab">

(Catalog record view showing both barcode & part location as part attribute in use)
<img width="1323" alt="Screenshot 2024-11-15 at 5 30 45 AM" src="https://github.com/user-attachments/assets/82703e3e-15b8-4c89-a648-1e00fec683e1">

(Part attribute edit view for adding location as a part attribute)
<img width="1299" alt="Screenshot 2024-11-15 at 5 44 50 AM" src="https://github.com/user-attachments/assets/0f4a3f0d-01c4-493f-a264-826572f431d5">

Hope those screenshots help explain how functional using the part attributes field is both for searching, displaying, and entering object location information!

**Comment by campmlc** [comment]
Note that the advantage of using barcodes is that you do not have to manually change the location of every record part attribute if there is a bulk move. For example, we can move an entire freezer rack or freezer box of hundreds of parts from one freezer or room to another with a single scan of the parent container barcode - all children of the parent barcode move, and there is history tracked as to the original source and the new position, who did it on what date.Also, it is easy to add items to a loan by using the part barcode, or to scan several loan items into a single container and use the parent container to add all items to a loan. 
I have several freezers worth of unbarcoded material, but we have an ongoing project to inventory and barcode those as the advantages of using object tracking for our situation is fundamental.  However, in the meantime, we have legacy part location in remarks, and since the part attribute has been available we use that for material that is not yet barcoded.
One last comment- if you have barcodes (even just virtual ones) for large containers such as rooms or freezers or cases or jars, you can add items to those without barcoding the individual items. This is very helpful when entering accessions, as you can add the barcode of the location where all items in the accession are stored, even if they have not yet been cataloged.

**Comment by mkoo** [comment]
Resolved
