### ISSUE TITLE
Deleting Catalog Records

### ISSUE THREAD

**Issue by LitsaWoo** [ArctosDB/arctos#8320]
We have some duplicate catalog records in Arctos. I have a short list of the ones we've caught so far but there are, without a doubt, more. Is there a way that I can delete them as I find them?

**Comment by campmlc** [comment]
The current process is to create an encumbrance to mask record with your name and use the description "delete as duplicate records". Add the records to the encumbrance. Then you can mark all to delete. 
There is a way to create a redirect from a deleted record to the correct existing record, but I've never been able to do this successfully. The documentation was not clear. 
I would recommend that you at least add the deleted catalog number to the existing catalog number (as the guid) as an institutional catalog number with relationship self to the existing record.  Don't use any other relationship type as that will prevent deletion. 
Anyone else want to weigh in?

**Comment by LitsaWoo** [comment]
I'm trying to create an encumbrance but I'm being met with this error. I can't seem to figure out what it means

https://arctos.database.museum/Encumbrances.cfm
![error](https://github.com/user-attachments/assets/f3f3027b-3dbe-461e-9ebe-c6b97f735431)

**Comment by campmlc** [comment]
Can you take a screenshot of what you enter before you click create?

**Comment by dustymc** [comment]
Unless you are absolutely sure that there's no possible way the (actual) GUID changing can ever create problems - you've personally created it in the last 5 minutes should be safe! - I would not recommend deleting anything. (Might not be a possibility in an ideal world...)

I don't think redirects are inaccessible.

Please DO NOT use arbitrary identifier types.

It's not possible to add nonfunctional GUIDs as identifiers.

The error is from a lack of an agent, probably your browser being 'helpful' - make sure something happens when you pick and tab out of that field.

**Comment by LitsaWoo** [comment]
I'm confident that we won't have issues if we delete the duplicates, the collection is fairly small right now and we're sorting through the duplicates specifically right now.

By arbitrary identifier types do you mean what @campmlc mentioned doing? Like adding the duplicate GUID as the institutional catalog number?

I had the agent in (or at least I thought I did) but I reloaded the page and tried again and it went through this time

**Comment by campmlc** [comment]
@dustymc does not like "institutional catalog number", but we use it at MSB because it specifically means what it says, and catalog numbers are real things. Usually we use it for external collections which do not have Arctos guids. If you are deleting a record that has been around for awhile and could have been published to GBIF, I recommend at least adding it as an "identifier" with value of "KSB:Mamm:12345". This would not be an arctos guid as it would be listed as an "identifier" and not have the required https url. 
Judging from the list of "delete record" encumbrances, the use of encumbrances for deleting records is widespread in Arctos and has a very long history of usage. If redirects are desired, then that has not been communicated to the community at large. In the case of a true duplicate that has not been externally published, this to me is a valid use case.

**Comment by mkoo** [comment]
@LitsaWoo I understand that this is part of the clean-up as you triage and fix up your collection. I'm going to email you to set up a time to make sure  things are going well for you on this topic and all the other migration issues you've posted. 

Can you update this issue? Did you take care of the dups? if so, let's close this issue but it can still be part of our meeting agenda.

**Comment by LitsaWoo** [comment]
@mkoo I can close this issue. We're still finding the duplicates as we begin our installation process but I was able to create the encumbrance and will delete the catalog records once everything we suspect was duplicated from out legacy collection is installed
