### ISSUE TITLE
Arctos reporter note

### ISSUE THREAD

**Issue by asemerdj** [ArctosDB/arctos#8351]
Hello,

I saw that arctos reporter wants reports written in separated SQL, can I get some help with that? I don't have a lot of experience with SQL and don't really know that means. 

The reports in question are "HSUVM big vials", "HSUVM skinny vials" and "HSUVM small box"

Thank you!
Alyssa

**Comment by dustymc** [comment]
>can I get some help

Yes!

Some questions to get started, I'm looking at the SQL on https://arctos.database.museum/Reports/reporter.cfm?action=edit&report_id=267 (because I'm guessing the others will be the same query or less, please point me to the most complex thing you've got going if that's not the case).

instead of answering the below, also feel free to just tell me what data you want (examples are always useful).

* what are you wanting to print for 'place'? (I suspect detangling 'locstr' inthe SQL and building whatever you want in the label is a more sustainable approach to this, but there are some things better done in SQL.)
* what are you wanting for collectornumber? (That's MVZ-centric code - and maybe you want identifiers in general?)
* what are you wanting to print for collectors? (getlabelname is very MVZ-ish)
* what are you wanting to print for parts? (you guessed it, more MVZ)

**Comment by dustymc** [comment]
>MVZ's format

I am more concerned with data - MVZ is using specialized (and expensive) functions, in part to support data that I think nobody else maintains. If you're working with those data (eg agent name type labels and identifiers issued by https://arctos.database.museum/agent/21347703) then I can definitely reuse that stuff, if not I'd rather not pointlessly burn the CPU and need to know what of your data you want on your labels.

If you're sure you want what the MVZ parts function returns (and you catalog such that commas are delimiters and not data) you can change delimiters in CF (https://docs.lucee.org/reference/functions/listchangedelims.html - and I'm happy to help with that part as well if we get there).

**Comment by dustymc** [comment]
Here's your report before I changed anything:

[HSUVM_big_vials.csv.zip](https://github.com/user-attachments/files/18000551/HSUVM_big_vials.csv.zip)

Let me know if anything still needs to change.
