### ISSUE TITLE
Creating barcoded positions in bulk!

### ISSUE THREAD

**Issue by KyndallH** [ArctosDB/arctos#863]
I can create new barcodes in bulk under Create Container Series. Under container type, it has listed “positions” even though I cannot enter positions using this form. It is still called an invalid container type.

I’d like to
1)	Be able to create in bulk barcoded positions using the Create Container Series
2)	Be able to add more information regarding those barcodes in Create Container Series. Currently, I have to make a 2nd bulkloader file under Bulk Edit Container to add in the height, length, width, and number of positions to the positions that I hope to one day be able to create under Create Container Series.

**Comment by dustymc** [comment]
I think we dropped the "can create positions" (the only usable-at-create container type for a while) when we came up with the (much better, I think) "you can move positions until they're used" rule. Under the "create lots of labels, use them for whatever" model, having details like the size of the container they'll ultimately be stuck to available at create is weird/confusing - that's something you'd edit in (while changing type anyway) once you know what you're going to do with the labels. I'm not sure I see why positions should be different.

Anyway, that's the theory from afar. I'm ambivalent on your specific request mostly because it seems likely that someone will eventually find a way of using this to make a mess, and very possibly one which extends beyond their collections. I don't see how it could be TOO dangerous - some XYZ-Collection freezer positions popping up in an ABC-Collection nunc tube or something maybe - but I didn't see most container messes coming. If we make potentially-dangerous things happen across two steps (create, edit), there's a chance someone will see it coming the logs BEFORE anything weird actually happens.

Addressing #745 (and I have no idea how that might be done) would make me less-hesitant to introduce potentially-dangerous tools.

Technically, letting you create "real" containers, adding metadata to the create form, and/or doing more with the edit form are all pretty trivial under our current model - this is mostly a social issue, and my only interest is in protecting us from ourselves. If ya'll decide you're willing to accept whatever risk is associated with this, I'm happy to alter the forms.

**Comment by KyndallH** [comment]
When I create the position barcode LN25C5, I know exactly what I'm going to use it for (position C5 in LN2 vat 5), and it doesn't just hang out in Arctos universe until then. If we are just using that form to create barcodes, why do we have to specify the container type or description? Shouldn't that be something we change when we "assign" the barcode? Should the create barcode bulkload form then just be entering the barcode into Arctos with no data? And FYI - If I was to enter them one by one, there is a space for dimensions. 

By having two steps, you just make it harder to enter barcodes and more prone to errors (2 places to screw up). I will go and enter my barcodes with the WRONG container type so that I can get them entered. I will then have to create a brand new bulkloader file to add data and change the information RIGHT AFTER I do the first bulkloader form. That is not enough time for you to catch me making a big mess unless you now want waiting periods between creating the barcode and editing the barcode. 
 
Yes, one day something very bad will happen. We can do it with any container type except positions. I'm not sure why positions are so scary and forbidden. It is just another container type.

**Comment by dustymc** [comment]
>When I create the position barcode LN25C5, I know exactly what I'm going to use it for

You're not who I'm worried about!

> If we are just using that form to create barcodes, why do we have to specify the container type or description? 

Short answer is users have asked for that - those aren't (very) functional fields. To make the model work, we need container_id, parent_container_id, and a machine-readable proxy to them (unique barcodes - which are also the only visible element of the functionally-required junk) - everything else exists only because someone at some time thought it would somehow make something better.

Specifically, http://arctos.database.museum/info/ctDocumentation.cfm?table=CTCONTAINER_TYPE is container types, and I have no idea why about half of those exist. container label,cryovial label,specimen label are the "label" (=can be created in batches, cannot be parents or children) containers - we should probably have one plain ol' "label" OR a corresponding "whatever label" for each "real" container type. (But see below.)

>If I was to enter them one by one, there is a space for dimensions

Yup, there's no "rule" that you can't create fully-functional containers, just some experience suggesting that the review process is/has been occasionally useful when working with bigger batches.

>2 places to screw up

That's a very real possibility.

>not enough time for you to catch me 

You're probably right, because **you** don't show up in the error logs very often. If **I'm** trying to do that (incorrectly), I may end up in the logs, someone may notice, and we may avert a problem.

Positions are not (should not be...) handled differently than any other container type. They initially were under the new rules model, ya'll came up with #803, and the handling - at least until they're "installed" - should now be identical to all other types. 

Again, I don't have a stake in this and I don't much care if we do something different. Things that get stopped by these procedures (or somehow detected) get added to the hard rules, so at least some of them are probably no longer needed anyway. A bunch of this was developed by Gordon working alone and doing things that had never been done before, and we have several people-decades of experience now. Etc. I seriously won't be offended if ya'll tell me we need something drastically different (especially if it means I can ditch some complexity!), and I think everything under discussion here would be quick and simple to change. I'm just trying explain what we have now and how we got there so you can make an informed decision....

**Comment by dustymc** [comment]
Please re-open if this requires further discussion.
