### ISSUE TITLE
event media mapping to wrong specimens

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#869]
There is an MVZ legacy photo of a bat linked to collecting_event "Oregon: no specific locality recorded (9 Jun 1917)" (http://web.corral.tacc.utexas.edu/MVZ/images/MVZ_img/cards/jpg/img_card_2383.jpg) erroneously mapped to a UCM rabbit (http://arctos.database.museum/guid/UCM:Mamm:8021), a DMNS sea snail (http://arctos.database.museum/guid/DMNS:Inv:7862), and a UAM vole (http://arctos.database.museum/guid/UAM:Mamm:125075), all from Oregon. The nature of the VPD prevents folks from linking media directly to cataloged objects outside of their institution, except in the case of shared collecting events. Is there a way to flag the media screen or event picker in a similar way to other screens that notify users that they may be including/affecting outside data when attaching events to media (e.g. along the lines of "Red is scary. This form is dangerous. Make sure you know what it's doing before you get all clicky.") ? Even though it may not eliminate this kind of error, I think it would give people pause and reduce accidental inclusion of irrelevant records.

**Comment by ccicero** [comment]
This is an interesting issue. The MVZ image does reference a catalog number, but the specimens doesn't seem to match (it's a skin + skull, the card says it should be a fluid - and ID is different).

From the media, if you click on the event link it takes you to the Find Localities window and then lists the number of specimens associated with that locality at the bottom of the screen. It would be better if it took you to the Find Collecting Events window instead, because that's really what is being linked from the media. Then the list will be limited to only those specimens that share the same event - BUT I think the list should be expanded to include both specimens AND media that share the same event.

**Comment by dustymc** [comment]
Mouseover the green Media Results bit for a bit of a clue as to why you're seeing that image there. I think there are 5 or so ways to get media on a specimen page now, and I don't think anyone's ever read the tooltip.... How SHOULD we communicate what you're seeing/why you're seeing some Media?

https://github.com/ArctosDB/documentation-wiki/wiki/How-to-understand-locality-media is a bit more about what the "shares locality via events" media box contains, and #860 is where it came from.

Anyway, there's nothing accidental/broken, just very weird data - I can't fathom why there's a random prepared bat linked to a low-data collecting event. (Someone found it all pinned out somewhere in Oregon??) Can the bat be cataloged as an observation which uses that event or something?? 

IF the image was of some usefully-sized locality (eg, something smaller than Oregon), then it might add some value to the bunnies and whelks - maybe it's an eroding coastline documented by specimens (and probably field notes etc.) or something else equally interesting. Given state-sized errors and images of not-places, not so much.

The link Issue is #873. That does include links to Media, but it won't include links by way of event-->locality-->event (what you're seeing in the confusing box) so might not be very useful in understanding this particular situation.

**Comment by dustymc** [comment]
Please re-open if this requires further discussion.
