### ISSUE TITLE
Related specimen ID is pulling from unaccepted identification

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#870]
The related specimen ID in search results and in Relationships is pulling from the first identification, which may no longer be the accepted identification. The displayed ID should be the current, accepted identification.

example:
http://arctos.database.museum/guid/MSB:Para:23513
http://arctos.database.museum/guid/MSB:Mamm:274502

**Comment by campmlc** [comment]
A second issue on this topic: related items can only display a single related item in search results? Can we choose which related item to display when there is more than one?

**Comment by dustymc** [comment]
>The related specimen ID in search results and in Relationships is pulling from the first identification

No, it isn't, it's pulling from the public cache (filtered_flat). The problem is that the related specimen cache is way out of date - we're adding relationships faster than the cache refreshes! I'll up the refresh rate and it should catch up in a few days.

>A second issue on this topic....

File a new Issue with an example, please - I'm not sure what you're talking about.

<img width="215" alt="screen shot 2016-05-02 at 1 52 20 pm" src="https://cloud.githubusercontent.com/assets/5720791/14967618/1fb592c4-106d-11e6-9f44-b2fed59ad47f.png">
