### ISSUE TITLE
Parent contains positions error

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#871]
We need to revisit the issue of positions. I have legacy freezer racks that contain boxes scanned directly into racks that don't have positions, and I cannot edit any specimens in the boxes in object tracking without getting the error below. Kyndall and I are both having issues with trying to create positions in freezers and racks and running into difficulties  with the constraints put on creating and editing positions.  I think we need to remove the restraints on scanning either positions or freezer boxes into freezer racks. 
Rack position is not an essential field for smaller racks - it should be possible to scan boxes directly into racks when necessary. And CMs should not lose editing capability for the part label because the box it is scanned into is in a rack instead of a rack position.

An error occurred while processing this page! 
Error Executing Database Query. 
[Macromedia][Oracle JDBC Driver][Oracle]ORA-20000: FAIL: Parent contains positions and cannot contain not-position containers ORA-06512: at "UAM.UPDATECONTAINER", line 60 ORA-06512: at line 1
This message has been logged. Please contact us with any information that might help us to resolve this problem.

**Comment by dustymc** [comment]
Allowing positions and not-positions to share a parent will break position-forms and will encourage lower-quality data (eg, 500 tube-sized-things in a box which physically fits 100 tube-sized things is allowable). If everyone is OK with that I can drop the offending rule.

That said, I don't understand the issue here. Positions (and every other container) are optional - simply don't use whatever's getting in the way.

**Comment by KyndallH** [comment]
I don't think by getting rid of the rule, you'll have the box problem you used as example. I want to keep "create positions" and it make a nice 100 slots grid to scan my vials into a box. We would like it to be easier to create, edit, and manage positions. Not sure if removing that rule would make life easier or what would make dealing with positions easier. It would make it easier for me to scan a bison into a freezer (parent) that has positions. 

I'm guessing to fix the problem Mariel is having - she needs to delete all the parts in the rack without positions. Then barcode the stages in the rack, create positions, and move the boxes back into the correct positions.

**Comment by atrox10** [comment]
Are you guys talking about positions of boxes in racks? or actual positions
in boxes?
I want to keep constraints on positions in boxes, this is essential to us.
is Mariel trying to put larger tubes into boxes with positions?




On Mon, May 2, 2016 at 9:45 AM, KyndallH <notifications@github.com> wrote:

> I don't think by getting rid of the rule, you'll have the box problem you
> used as example. I want to keep "create positions" and it make a nice 100
> slots grid to scan my vials into a box. We would like it to be easier to
> create, edit, and manage positions. Not sure if removing that rule would
> make life easier or what would make dealing with positions easier. It would
> make it easier for me to scan a bison into a freezer (parent) that has
> positions.
>
> I'm guessing to fix the problem Mariel is having - she needs to delete all
> the parts in the rack without positions. Then barcode the stages in the
> rack, create positions, and move the boxes back into the correct positions.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ArctosDB/arctos/issues/871#issuecomment-216288844>
>



-- 
Carol L. Spencer, Ph.D.
Staff Curator of Herpetology & Researcher
Museum of Vertebrate Zoology
3101 Valley Life Sciences Building
University of California, Berkeley, CA, USA 94720-3160
atrox10@gmail.com  and  atrox@berkeley.edu
510-643-5778 /FAX: 510-643-8238

http://www.herpnet.org
http://mvz.berkeley.edu/
http://www.vertnet.org

**Comment by campmlc** [comment]
I'm talking about box positions in a rack, not positions of tubes within a
box. The later is critical, and I don't want to mess with that. This also
applies to rack positions within a freezer. Unless I am missing something,
we don't have a form to autocreate either box positions within a rack or
rack positions within a freezer - correct? So everyone is using a different
format for creating these, or not creating them. At MSB, we put actual
barcodes on the sides of the rack, and then create these as box positions,
and we put actual barcodes on the freezers to show the location of the
racks. Then we have to create these as positions and move the positions
into the freezer and rack containers - a process that has become difficult
since Dusty put in place the new rules against moving positions. I believe
Kyndall has been having similar issues, although she does things slightly
differently.
The issue I am having now is with some small legacy racks that had boxes
scanned directly into the rack before this rule went into effect. These
racks have no positions created for the boxes. This is not a problem
because the racks are small, and the boxes are labeled and easily located
within the rack. These racks are in one mechanical freezer that holds 6,000
specimens. I'd really rather not go through and create positions manually
for all these racks, since the samples are eventually going to be moved.
But right now I can't edit any of the 6000 specimens in object tracking
because I get an error related to the fact that they are in boxes scanned
into racks that are supposed to have positions that don't exist.
??

**Comment by dustymc** [comment]
The rule exists because the problem exists, but maybe the other (all new-ish) rules cover the situation sufficiently - I don't really think that's true here, but it's certainly been the case elsewhere so maybe.

The freezer box positions form can not work if there's anything unpredictable (like positions AND nuncs) in the parent (box), which is the situation I'd like to prevent. That is, if we drop the position-mixing rule someone WILL scan a nunc into a box with positions and then the position-forms can not be available for that box.

I have no way of creating or enforcing sometimes-rules. The rule preventing dumping tubes directly into a position-having freezer box (contains container_type="position") so the forms work is the same rule that prevents dumping a bison into the half of the freezer which doesn't have positions (or a box into a position-having rack), even though there may be no forms which could be broken by those data.

Some possible workarounds:

1) Create a new container type which avoids the rules. I think Aren intends to create (has created?) a "big box" to avoid the "parent and child can't be the same type" rule (which exists to prevent eg freezer racks in freezer racks), for example. Maybe we need to somehow differentiate between freezer box positions (which are "real" - you can't physically put a tube between the slots) and eg freezer positions (which are just map coordinates - you CAN put the racks anywhere you want, lay them down, dump a frozen bison in beside them, or whatever).

2) Avoid using stuff you don't need. You CAN just scan tubes into freezers (or boxes into racks or WHATEVER), and if you have really big tubes (or dead bison) you probably SHOULD. Containers exist to make it easy to find stuff - don't use them if they're not doing that. Does having ~30 positions for racks in a freezer really help anything, or would it be faster to just dump the racks in the freezer? You can make that decision for every individual container - giving up rack positions for the bison-freezer does NOT have to affect how you treat anything else.

The rule about moving positions only applies to positions which have a parent (a fairly recent change), so

>Then we have to create these as positions and move the positions into the freezer and rack containers - a process that has become difficult since Dusty put in place the new rules against moving positions.

should not be a problem, or should be easy to work around via procedures (eg, create stuff in a certain order).

Creating "big" positions - for freezer racks etc. - has been a rare and unpredictable process (eg, LN2 freezers have weird shapes, hold weird racks, and we don't buy new ones very often), and I don't think there is a form similar to creating positions in freezer boxes (which is common and involves only a few variants) for racks/freezers/etc. File a new Issue if new forms/capabilities are needed.

I could eliminate the problematic positions - dump boxes directly into racks - if that's useful. I can't so easily create data - given a box in a rack (esp. one which is supposedly fully occupied by positions), I have no idea where it actually is and can't guess at positions. I assume the positions must have been useful for someone at some time by virtue of having been created, so maybe it's best to address that in small batches if tossing out specific rack-position data seems like the most pragmatic approach.

**Comment by dustymc** [comment]
Please re-open if this requires further discussion.
