### ISSUE TITLE
images tied to collecting events, not specimens

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#876]
Images that are related to collecting events show on the specimen detail page in the Locality/Event block. This is confusing if the image has nothing to do with the specimen itself. I talked about this with Dusty at one point and we can do an easy fix: 

Within the block that contains images related to the event, add a label in bold: "Media that share this Collecting Event" or something along those lines.

Examples:
http://arctos.database.museum/guid/MVZ:Herp:12345
(Ascaphus specimen, sheep photo)

http://arctos.database.museum/guid/MVZ:Herp:226468
(frog specimen, shrew photo)

**Comment by dustymc** [comment]
>Ascaphus specimen, sheep photo)

This actually seems really useful to me - within days of all those sheep being there, there were still frogs running around (or laying around having been stomped - part condition would be good here...). Interesting! From a frog's perspective, a bunch of sheep stomping around seems very much a part of the habitat.

>(frog specimen, shrew photo)

This is simple denormalization. The photo is already linked to http://arctos.database.museum/guid/MVZ:Mamm:186403 which is linked to the event, there's no reason to also link the photo to the event. There are lots of reasons NOT to do that - it makes for weird data, it creates needless work, etc. https://arctosdb.org/documentation/media/#guide

>add a label in bold: "Media that share this Collecting Event" or something along those lines.

We can do that - the "title" attribute of the green "Media Results" text (mouseover to see it) says "Media linked to a Collecting Event which shares the specimen's Locality." That media widget is injected into several places, verbiage input on all of them would be appreciated - search "mrdescr" at https://github.com/ArctosDB/arctos/blob/master/form/inclMedia.cfm.

@DerekSikes

**Comment by ebraker** [comment]
I agree. I think your suggested label would be very helpful. 

This relates to issue #869, though we may want to consider discouraging media linked to low-data collecting events to minimize confusion (as with that case, a bat image from "Oregon, no specific locality data" is linked to 4 non-related "Oregon" records).

**Comment by campmlc** [comment]
I agree with Dusty: the first photo is useful for describing the collecting
event, but the second should not be there. The image of the shrew should be
linked to the shrew cataloged item, not to the collecting event. Sounds
like that is the case with Emily's bat as well?
On May 10, 2016 1:21 PM, "Emily Braker" <notifications@github.com> wrote:

I agree. I think your suggested label would be very helpful.

This relates to issue #869 <https://github.com/ArctosDB/arctos/issues/869>,
though we may want to consider discouraging media linked to low-data
collecting events to minimize confusion (as with that case, a bat image
from "Oregon, no specific locality data" is linked to 4 non-related
"Oregon" records).

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/ArctosDB/arctos/issues/876#issuecomment-218262381>

**Comment by ccicero** [comment]
I agree about the importance of #1, but wouldn't it also be useful to know that a moonrat was collected at the same place/time as a frog? Why not? Adding that label will clarify that these are media objects that share events, and I think that adds value to the frog event as well as the moonrat event.

Re: Emily's point about low quality events: if we have a (in this case) historic bat photo from Oregon, and don't know much more about where the photo was taken, it's better to relate it to Oregon than to no geography at all. It's historic, so someone might be able to figure it out sometime. BUT I think it makes more sense to apply that to an image of a landscape/habitat where a bat was taken, vs a bat specimen with only "Oregon" as the data.

Dusty - suggestions on the green label: That would be better INSIDE the box (dotted lines) containing the media, vs under Elevation (was it there before? didn't notice it, and I'm guessing others will also miss it). Second, we need to make the "title" more obvious than just a mouseover.

**Comment by campmlc** [comment]
"wouldn't it also be useful to know that a moonrat was collected at the
same place/time as a frog?" - yes, but I can see this getting out of hand
very quickly. I have multiple parasites from the same host, that all share
collecting events with each other and with the host. But to have images of
all of them all cluttered together with the collecting event of each
specimen page would be distracting and confusing. That is why we have
"collected with" relationships, to show the linkage between specimens
related in that way. Why not have a link to related media, without actually
displaying the thumbnail?
I think it is better to put specimen images with the specimen record, and
habitat images with the collecting event.

**Comment by dustymc** [comment]
>I agree. I think your suggested label would be very helpful. 

> That would be better INSIDE the box (dotted lines)

<img width="382" alt="screen shot 2016-05-10 at 8 11 03 pm" src="https://cloud.githubusercontent.com/assets/5720791/15168980/6a2e91fa-16eb-11e6-8c60-44945a60cf6e.png">

<img width="384" alt="screen shot 2016-05-10 at 8 12 27 pm" src="https://cloud.githubusercontent.com/assets/5720791/15168998/8ca70820-16eb-11e6-9078-55667c0cedc1.png">

How's that?

> discouraging....low-data

Yup, but it happens/might turn out to be more valuable than we suspect. Wouldn't be much of a problem if the data were where we expect them to be, which leads to....

>The image of the shrew should be linked to the shrew cataloged item, not to the collecting event. Sounds like that is the case with Emily's bat as well?

There is no cataloged item for the bat - it's just an image (which was probably cataloged - there's a long history). Observation collections are easy nowadays, and the bat ("vouchered" by the image) belongs in one of them - just a matter of cataloging it there and shuffling the media links.

>BUT I think it makes more sense to apply that to an image of a landscape/habitat 

Yes, I agree - we should be as specific and organized as possible. Cataloged items are the data objects capable of bearing identifications, we know that bat-picture shows a bat, the media link should be to a cataloged item.

>wouldn't it also be useful to know that a moonrat was collected at the same place/time as a frog?

I sure think so! (And place alone is interesting too, which is what "Media linked to a Collecting Event which shares the specimen's Locality" does.) Scattering "click here for more stuff from this something-with-a-primary-key" links around is trivial - let me know what you want to see and where. More than links (eg, pre-fetching a summary or media of vaguely-related specimens or whatever) is less-trivial and likely to lead to other problems (screen real estate, computational limitations, etc.). I'm not sure if those problems are worth solving or not - maybe a fun "discoverability" proposal?

Also, we have huge variation in how we define places and times. "Some big country, sometime before tomorrow" vs. "within 3 meters of my GPS in this 5-second time interval" vs. "the exact same thing as above, but I grabbed a new whatever_ID because I can." This would all be much more useful if we could let the user specify parameters - "show me media of everything within a mile and month of here."

>But to have images of all of them all cluttered together with the collecting event of each specimen page would be distracting and confusing.

I'm probably lost, but it seems to me that the host's habitat on a parasite page would be great for discovering bad IDs, bad locality data, unrecorded captivity, etc. (Why's this polar bear habitat full of palm trees?) 

>Why not have a link to related media, without actually displaying the thumbnail?

Because I'll click it, find some mysterious picture of a bat, and not bother clicking any more thereby failing to discover that thing I was looking for in the first place. I think the thumbnails are valuable and unobtrusive, while links are mostly invisible. I suppose it wouldn't be too difficult to implement a "don't ever show me this type of media again" option or something.

**Comment by dustymc** [comment]
>wouldn't it also be useful to know that a moonrat was collected at the same place/time as a frog?

To clarify, link both those Media to their respective specimens and we can add them to a "all media from all specimens sharing this event" box or whatever - we can follow keys as far as you want to go, and use those data to display whatever, wherever. Denormalization is not necessary or desirable; linking to specimens and their events can do nothing but cause problems.

**Comment by ccicero** [comment]
Dusty - Yes, that labeling is better. Hard to tell without seeing the whole page, but so far it looks good to me.

Re: the other comments, I agree mostly with what Dusty said. If I understand correctly. link images of specimens only to cataloged items (if we know them - we don't in the case of the Oregon bat, but it's formally cataloged in the MVZ image collection so we don't want to discard it) and then sprinkle media related by the same collecting event in appropriate places (e.g., detail page under event for other specimens) without directly relating it to the collecting event?

So the moonrat would show under 'Media linked to this specimen' on its specimen detail page, but under 'Media linked to a collecting event that shares the same locality' on the detail pages for other specimens? 

Is that what you're thinking?

**Comment by dustymc** [comment]
> Hard to tell without seeing the whole page

It's running @ test

>link images of specimens only to cataloged items

Yup

>don't in the case of the Oregon bat, but it's formally cataloged in the MVZ image collection so we don't want to discard it

Excellent use for Observations - catalog it and add an OtherID holding the MVZ Image number so people can find it through the expected interfaces.

>without directly relating it to the collecting event

Yup. Denormalization - doing things that can be found through existing pathways in this case - sorta always causes problems.

>the moonrat would show under 'Media linked to this specimen' on its specimen detail page

yup

>but under 'Media linked to a collecting event that shares the same locality' on the detail pages for other specimens? 

Currently, no - if there's a picture of the moonrat's habitat (and the image of the moonrat is currently recorded as "habitat" by way of it's link to events), it'll show up on other specimens that share the locality or event. Media of specimens (my vote for what the moonrat-picture SHOULD be) is currently limited to the specimen's page (and Media interfaces, of course).

We have a fully modular media widget, so if someone WANTS to see "media of specimens linked to events used by the locality this specimen's event uses" (or anything else one can get at by following key-pairs around the model), we can easily drop it in - write some (complicated, but very possible) SQL, add one short line of code to wherever we want to include the results of that SQL, there it is. There's no reason to do more than link Media to the single "best" (most specific, ish) thing represented by the media.

**Comment by campmlc** [comment]
My vote is to keep the image of the moonrat itself tied to the specimen's
page, and keep images of habitat with the collecting event. If it is
necessary to record that the moonrat and the frog were collected together,
set up a "collected with" relationship between the two. This is easily done
across divisions using other IDs.

**Comment by dustymc** [comment]
>set up a "collected with" relationship

Not to wander too far off towards left field, but I think the utility of this is curatorial (chasing down field notes, etc.) and not necessarily *ogical (where a user may be working at a scale of meters and minutes or miles and decades). Users who want "same place" data will have their own idea of what a "place" is and can find that via search despite the temporospatial variability of our events or whatever situation lead to (or didn't) an asserted relationship.

**Comment by campmlc** [comment]
For parasites, it is a useful relationship for worms sharing the same
host/organ, collected at exactly same time/place/host/tissue. I believe
Derek is also using it for pitfall trap contents. With such a relationship,
you can find on all mice collected with frogs, or all cestodes collected
with flea intermediate hosts from dogs in New Mexico.

**Comment by dustymc** [comment]
>For parasites...host

You're using a much more specific, definable relationship for hosts/parasites. And like everything else, we can follow them across keys - cestode-->flea-->dog is not a problem (or not a query problem - lots of presentation/performance obstacles in there) and doesn't require any sort of special handling or denormalization.

>same tissue...pitfall

Definitely useful for (some) *ogical questions, but still doesn't do me any good unless I can differentiate between "same organ" and "shot one in the morning then wandered over the hill and shot another in the evening" (and we have a LOT of collecting events carrying that level of precision - and worse!).

If you want to record "same organ" specificity (and doing so sounds very useful to me), then you need to somehow disambiguate it from the "someone for some reason considered these to be close enough" data (eg, you need a new relationship).

**Comment by ccicero** [comment]
I like the change in the label, but it seems like unnecessary duplication. 

Shouldn't "Media linked to a Collecting Event which shares the specimen's Locality" also include "Media linked to a specimen's Collecting Event" ???

If a media object is related to a collecting event, it will automatically share the locality - correct?

Examples where same image is duplicated under the two 'boxes':

http://arctos.database.museum/guid/MVZ:Bird:183616
http://arctos.database.museum/guid/MVZ:Bird:183623

Also, on the aesthetics: the box outlines should be the same for both. Not sure why on one page they are different from each other, but not on the other page. Looks funky when they are not the same, e.g., http://arctos.database.museum/guid/MVZ:Bird:183616

**Comment by dustymc** [comment]
>duplicated....

https://github.com/ArctosDB/documentation-wiki/wiki/How-to-understand-locality-media

>Note that in the case of Media linking to the event used by the Specimen, the Event-Media is displayed twice: Once in the Locality Media box (because it is spatially relevant), and again in the Event Media box (where is is both spatially and temporally relevant).

-

>the box outlines should be the same for both

It's the same object injected with different contents, so the box itself is the same. The stuff around and in it can influence the size, if that's what you're talking about - I'll set it to always be full-width and see if that's better or worse.

**Comment by dustymc** [comment]
Is this resolved/can this be closed?

**Comment by dustymc** [comment]
Closing, re-open and comment if issues remain
