### ISSUE TITLE
Bulkload Parts 

### ISSUE THREAD

**Issue by KyndallH** [ArctosDB/arctos#902]
The template for bulkload part doesn't have a column for label.
Why is it missing and can I get it added?

Thanks!
<img width="809" alt="screen shot 2016-06-22 at 9 19 40 am" src="https://cloud.githubusercontent.com/assets/16887896/16276458/f026b3a6-385a-11e6-8ed8-77bc6749e249.png">

**Comment by dustymc** [comment]
Hu? What are you trying to do?

**Comment by campmlc** [comment]
I agree that would be useful. A barcoded part could be added to a record
and converted from a label to container and given a label in one step,
rather than multiple.
On Jun 22, 2016 12:26 PM, "dustymc" <notifications@github.com> wrote:

Hu? What are you trying to do?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ArctosDB/arctos/issues/902#issuecomment-227816716>, or mute
the thread
<https://github.com/notifications/unsubscribe/AOH0hFM1yYDFbZx8nhVBlZrBre4X7zUCks5qOXA3gaJpZM4I8BYJ>
.

**Comment by dustymc** [comment]
Oh - this is a request for a "change_container_LABEL" field? Is that common? I'm not really sure I've ever understood why it's possible to have a label that's different from the barcode - just seems confusing to me - so a bit more about what you're trying to do still seems useful.

**Comment by KyndallH** [comment]
For what I'm doing, I'd like to just have the well number (A01, G03, etc.) as the label (A01 is labeling that well) instead of the whole CCDB-198754-G03 barcode in it. I don't want to put the well number under remarks since there is other information there and it may get lost in the other info.

I always thought "barcode" and "label" were different otherwise we would just have one field. Little redundant then to have two fields if they are the same thing.  

That is why I'd like either barcode and label to merge OR label to be added to the bulkloader part spreadsheet so I can enter something other than barcode for the label. 

This brings me to why I dislike that we just have label on a specimen data page under parts instead of label AND barcode since they are different things. That is another rabbit trail and possibly a future GitHub when I'm frustrated more about it. 

<img width="554" alt="screen shot 2016-06-22 at 1 14 35 pm" src="https://cloud.githubusercontent.com/assets/16887896/16283920/5f2a0878-387b-11e6-95f8-dfc0e289427f.png">

<img width="565" alt="screen shot 2016-06-22 at 1 10 57 pm" src="https://cloud.githubusercontent.com/assets/16887896/16284033/c4d9b4d4-387b-11e6-9654-66301b62746e.png">

:)

**Comment by KyndallH** [comment]
This request is only to have label added to the CSV part bulkloader sheet.

<img width="781" alt="screen shot 2016-06-22 at 1 36 37 pm" src="https://cloud.githubusercontent.com/assets/16887896/16284581/67dc63aa-387e-11e6-82b0-6cf1dc1dd061.png">

**Comment by dustymc** [comment]
>I always thought "barcode" and "label" were different otherwise we would just have one field

Whoever designed that part of the model obviously agrees with you. There are very obvious differences in the quality of the data (eg, how likely are you to be able to you find your stuff?) produced by machines and people, and in a perfect world I don't think we'd need the label (which probably encourages the use of imperfect input devices, like keyboards) at all. I'm not wandering around with a scanner though, so it that happens it's going to have to start with someone who is working in the collections and better understands why we have (or don't need or whatever the case may be) the two fields. I presume without the label we'd occasionally have to resort to something even less controlled, and if that's true then it's probably worth keeping.

>That is why I'd like either barcode and label to merge OR label to be added to the bulkloader part spreadsheet so I can enter something other than barcode for the label.

To be clear, you want to use the barcode to find containers (no changes there), and provide a new value used to update the label of the container found via the barcode - right?

>This brings me to why I dislike that we just have label on a specimen data page under parts instead of label AND barcode since they are different things. That is another rabbit trail and possibly a future GitHub when I'm frustrated more about it. 

Yup, file an Issue - the only real constraint to what you see there is screen real estate - we can only cram so much junk into a cell without stretching the table out into an unreadable mess.

**Comment by campmlc** [comment]
I use labels, even if occasionally flawed, as a searchable field with some
information content and to provide a way to find parts in containers
between the the time they are scanned into position and the time the record
is cataloged. They also provide a double check between what is on the label
(in our case a field number and part type)and what the Arctos record
provides. If there is a discrepancy, it merits a closer look. I find labels
to be extremely useful. and agree with Kyndall's suggestion.
On Jun 22, 2016 5:42 PM, "dustymc" <notifications@github.com> wrote:

I always thought "barcode" and "label" were different otherwise we would
just have one field

Whoever designed that part of the model obviously agrees with you. There
are very obvious differences in the quality of the data (eg, how likely are
you to be able to you find your stuff?) produced by machines and people,
and in a perfect world I don't think we'd need the label (which probably
encourages the use of imperfect input devices, like keyboards) at all. I'm
not wandering around with a scanner though, so it that happens it's going
to have to start with someone who is working in the collections and better
understands why we have (or don't need or whatever the case may be) the two
fields. I presume without the label we'd occasionally have to resort to
something even less controlled, and if that's true then it's probably worth
keeping.

That is why I'd like either barcode and label to merge OR label to be added
to the bulkloader part spreadsheet so I can enter something other than
barcode for the label.

To be clear, you want to use the barcode to find containers (no changes
there), and provide a new value used to update the label of the container
found via the barcode - right?

This brings me to why I dislike that we just have label on a specimen data
page under parts instead of label AND barcode since they are different
things. That is another rabbit trail and possibly a future GitHub when I'm
frustrated more about it.

Yup, file an Issue - the only real constraint to what you see there is
screen real estate - we can only cram so much junk into a cell without
stretching the table out into an unreadable mess.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/ArctosDB/arctos/issues/902#issuecomment-227899332>, or mute
the thread
<https://github.com/notifications/unsubscribe/AOH0hA2J2dWKZOODDgoSlnzGT-cHVJGrks5qOboagaJpZM4I8BYJ>
.

**Comment by dustymc** [comment]
updating to next task: use the barcode to find containers (no changes there), and provide a new value used to update the label of the container found via the barcode

**Comment by campmlc** [comment]
I'd like to bring this issue back into play and second Kyndall's request to add a label field to the parts bulkloader, so that we can add both barcode and label on this form. Currently the only way to add a label is through BulkEditContainer in object tracking.

**Comment by dustymc** [comment]
for next release
