### ISSUE TITLE
Herbarium attributes

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#918]
As I work on our herbarium data I have the following questions and I would like other herbaria to chime in:
1. We have a lot of specimens where the flower color is identified in the data.  Would it be useful to have an attribute in the Herb databases for "flower color" and if so, would it be better to have a controlled text for the colors or just an open string?
2.  We have a lot of specimens where the entire plant was not preserved, but the (approximate) height of the plant the specimen was taken from is recorded in the data.  Would it be useful to have an attribute in the Herb databases for "original specimen height" with the attribute vale being a numeric value and the attribute units being either ft or m?
Not being a plant biologist, I don't know if these values might be useful search options, or if they can just go in a specimen remark field.  Any input would be helpful.

**Comment by ebraker** [comment]
Hi Teresa,

I am not coming from an herbarium but from a data structure standpoint, I would say that you might as well place ‘flower color’ and ‘original specimen height’ as separate Attributes rather than tuck these values into Remarks given that they seem to be recorded with some regularity. Placing them in the Attribute field makes them readily searchable/findable, whereas they are more likely to be overlooked in the kitchen sink of Remarks. You never know what a given user’s entry point might be to exploring your data -perhaps these descriptions are exactly what someone needs to identify odd color variants, examine patterning in species height, etc. etc.

For ‘color” I would leave an open text field unless all descriptions are standard ROYGBV and lack any modifiers (e.g., “blue” vs.“dusky blue with olive-brown speckles”). For heights use a numeric value field with the length_units code table which contains both metric and imperial units (http://arctos.database.museum/info/ctDocumentation.cfm?table=CTLENGTH_UNITS).

My two cents at least ☺
Emily


Emily Braker
Vertebrate Collections Manager, Zoology Section
University of Colorado Museum of Natural History
265 UCB, Bruce Curtis Building
Boulder, CO 80309-0218
Phone: 303-492-8466
https://cumuseum.colorado.edu/vertebrates

**Comment by ccicero** [comment]
I agree with Emily's comments about putting these data in as attributes vs remarks.

We already have a 'colors' attribute type for birds and herps, so we can just add the same attribute type to the 'Herb' collection code. It would be better to use an existing and more general attribute type ('colors') rather than something different and more specific for the same thing ('flower color').  We use 'colors' with an open text string for birds, e.g., "irides orange, tarsus gray" . 

For height, we would need to create a new attribute type which I would add as "original height" with a numeric value and the length_units code table.

Let me know if you want me to go ahead and do that now.

**Comment by Jegelewicz** [comment]
Carla,
That would be great!  Thank you!

**Comment by dustymc** [comment]
All sounds good to me, except....

>original height

should just be "height" unless it needs distinguished from something else (and that should still probably happen in the documentation instead of the attribute name).

And FYI the mere existence of an attribute is a powerful search tool, even if the data are a mess. Instead of downloading all millions of records that might have what I need or guessing at which of the very many possible remarks fields someone has used to misspell or cryptically abbreviate something about colors etc., I can just download the generally-small subset of things with the "colors" attribute and probably find close to what I want, no matter how creatively people have failed to spell "blue."

**Comment by Jegelewicz** [comment]
That sounds fine to me.

**Comment by Jegelewicz** [comment]
Can we get the following attributes added for Herb collections?

colors
height

**Comment by campmlc** [comment]
Done. Let me know if any problems.
