### ISSUE TITLE
Fossil taxonomy and search (ES collections)

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#921]
I have a question for the ES collections crowd.  We can use the A cf. and A ? taxa formulas when the entire taxon is in question and it makes sense.  However, we have some specimens where confidence in the genus is high and it is only the species identifier that is in question.  In the past, we have indicated this by labeling the specimen "Lepus cf. californicus".  We can do this using the A {string} taxa formula, but it means that anyone searching for Lepus californicus will not find the specimens we have labeled Lepus californicus {Lepus cf. californicus} and the only way those specimens would ever show up in a search would be if someone specifically searched Lepus cf. californicus.

One option is to use the taxa formula Lepus californicus cf. and place  Lepus cf. californicus in the ID remark field.  This allows the specimens to show up in a search, but it also might mean a researcher misses the fact that it is only the californicus portion of the taxonomy that is in question.

Any other suggestions or ideas?

From a development standpoint - as searches relate to the A {string} taxa formula, would there be a way to have an identification search use the Associated Taxa field instead of the identification string?  Or have that as a choice when searching?

Thanks everyone!

**Comment by dustymc** [comment]
> I have a question for the ES collections crowd. We can use the A cf. and A ? taxa formulas when the entire taxon is in question and it makes sense. However, we have some specimens where confidence in the genus is high and it is only the species identifier that is in question.

I suspect this is how everyone views the situation, whatever the various semi-formalities regarding the use of cf. might be.

> In the past, we have indicated this by labeling the specimen "Lepus cf. californicus". We can do this using the A {string} taxa formula, but it means that anyone searching for Lepus californicus will not find the specimens we have labeled Lepus californicus {Lepus cf. californicus} and the only way those specimens would ever show up in a search would be if someone specifically searched Lepus cf. californicus.

You can still find them by searching for taxonomy or (maybe) identification starts with (the default condition). But yes, you can't expect people to predict the unpredictable things you might do in uncontrolled fields (and when using the "A {string}" formula identification is an uncontrolled text field).

> One option is to use the taxa formula Lepus californicus cf. and place Lepus cf. californicus in the ID remark field. This allows the specimens to show up in a search, but it also might mean a researcher misses the fact that it is only the californicus portion of the taxonomy that is in question.

A clarification in remarks is always good - I'd encourage WHY you think it looks like L. californicus, not just that someone thought that (which won't always be available, of course). 

>Any other suggestions or ideas?

I don't think this is any sort of actual problem, or at least I can't think of any user confusion regarding the Arctos structure of cf. (which was created, like most everything else, primarily to be predictable/discoverable rather than "traditional"). "Looks a lot like the most specific given taxon, might be something one up the tree or maybe some weird hybrid or something" - and it's a pretty easy "tree" to navigate when there's a multinomial in question. (I have no idea what it is we're trying to COMPARE when when cf is used with a mononomial, but those IDs exist as well?!?)

In any case, this is why we have taxonomy and identifications. We do a LOT of weird things in identifications and in "accepting" taxonomy and etc. A huge percentage of the stuff in Arctos gets a different name depending on when it was collected, or by which collection (eg, because we can't agree on, or haven't updated to, Myodes/Clethrionomys, Mustela/Neovison, Alopex/Vulpes, etc.), or we all agree on something that the user didn't expect, or etc. Taxonomy (as long as someone - and not necessarily someone in Arctos - records relationships) avoids that mess, and whatever we might do in identifications, entirely.

>From a development standpoint - as searches relate to the A {string} taxa formula, would there be a way to have an identification search use the Associated Taxa field instead of the identification string? Or have that as a choice when searching?

Those are entirely different concepts - associated taxa is a text field in the "specimen remarks" table, intended for eg, the type of tree under which bunnies like to grow. It contains taxon names, "habitat types" ("oak scrubland"), common names, any everything else that anyone ever felt like typing.

**Comment by Jegelewicz** [comment]
We will just use the cf. or ? at the end and note the difference in the remarks.
