### ISSUE TITLE
Radiometric Date Attribute in ES collections

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#922]
I would like to have an Attribute in ES Collections for radiometric date.  What do interested parties think of this:

Attribute - "radiometric date"
Attribute value - numeric
Attribute units - controlled vocabulary-numeric age units (Would we have to add units besides years to this list?)
Attribute remarks - 
Attribute date - date measurement was made
Attribute det method - this is where we can explain the method used to determine the date
Attribute determiner - Agent who completed the dating

Any comments are appreciated.

**Comment by dustymc** [comment]
Done.

**Comment by Jegelewicz** [comment]
Numeric age units does not work for radiometric dates which are in the millions of years and are effectively negatives unless I put -26,100,000 in the numeric field to represent 26.1 Ma

This looks really weird
![image](https://user-images.githubusercontent.com/5725767/82074932-b8551300-9698-11ea-93f1-57b5a2d6d264.png)

Also, now wondering if this shouldn't be an attribute of the locality (in this case, the age was not determined directly from the specimen, but from the surrounding strata).

Thoughts paleo people?
@Nicole-Ridgwell-NMMNHS @aklompma @dperriguey

**Comment by dustymc** [comment]
I don't think anyone would have trouble inferring "before present" in there; I don't think the negative is necessary.

Attributes should be used for things derived from the specimen.

If by "from the surrounding strata" you mean someone assigned a number to Whatever Formation, I thought we'd agreed to just pull that from macrostrat.

If you mean "as measured from a nearby rock" then that rock should be cataloged and the number entered as "things derived from the specimen."

**Comment by Jegelewicz** [comment]
The measurements came from a publication that infer a date.
![image](https://user-images.githubusercontent.com/5725767/82075938-45e53280-969a-11ea-9317-7515c53a10f5.png)

![image](https://user-images.githubusercontent.com/5725767/82075905-3bc33400-969a-11ea-8113-22bac9eae7db.png)
 Sorry - can't copy text from the PDF. Really not sure how to handle this, but seems like documenting it somewhere would be useful? I could be wrong tho...

**Comment by dustymc** [comment]
So it's metadata of geology, correct? It applies (according to something) to every specimen from Whatever Formation, not just this one? 

If so that seems like something that should be addressed in https://github.com/ArctosDB/arctos/issues/2498 and https://github.com/ArctosDB/arctos/issues/2244 - eg, maybe we need a more complex geology code table that allows assertions, some of which might come from services and some of which might be typed in, or something.

In any case I would only use radiometric date if the specimen itself has been dated.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I agree with Dusty, this should not go with the specimen, it belongs with the geology. Can this go in as a geology attribute?

**Comment by dustymc** [comment]
> this should this should go in as a locality attribute.

That actually makes a lot of sense - instead of attaching extra data (that may or may not be accepted at some time by some person) to the geology, just add the age (and perhaps use the publication as method, or authors as determiners, or etc.) when it's desirable to do so. People who don't buy into your time-data can still use the litho data without being forced to implicitly accept anything else. 

We can still go crawl around macrostrat and company, this approach would make it easier to distinguish between curatorial assertions and stuff we pulled from some service. 

It would mean that you'd have to add two "geology" determinations to everything for which you think both Whatever Formation and 2.5Myr whatever-we-call-it apply.

That easily fits in the proposed structure, which will be designed to accommodate number-plus-units.

Suggest we turn http://arctos.database.museum/info/ctDocumentation.cfm?table=CTNUMERIC_AGE_UNITS into "cttime_units" and use it for this.
