### ISSUE TITLE
Potential use for the "secondary identifier" coll_other_id_type

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#940]
My Herp curator created accession numbers that include a unique identifier for each specimen in the accession (ugh).  I have convinced him to drop the identifier if I can keep it elsewhere in the data.  I would like to put those numbers in an Other ID Number field and call them "secondary identifier" in the associated Other ID Type field.  I see that "Nobody knows why you should ever use this.", but I think I have a reason now.

Example:
Cat no     Current Accn no  Proposed Accn no     Proposed Other Id no     Proposed other ID type
2000        HXP.1980.9.5       HXP.1980.9                HXP.1980.9.5                   secondary identifier
2001        HXP.1980.9.6       HXP.1980.9                HXP.1980.9.6                   secondary identifier

Seem reasonable?

**Comment by dustymc** [comment]
Seems reasonable to me.

(My general dislike of "secondary identifier" is only that nothing obviously sets it apart from other loosely-defined IDs. "Institutional catalog number" [="number assigned by the owning institution"] or "original identifier" [="values that link a specimen with its data"] or new "{something} UTEP ID" or ..... all seem potentially valid for that type of data. To find things bearing those numbers, users must either 1) search everything, or 2) hope they make the same arbitrary choices as the person who assigned the ID.)

**Comment by Jegelewicz** [comment]
I agree, should we add an identifier that is more specific?  It's Friday and my brain is overloaded, so I am having trouble coming up with something.  Suggestions?

**Comment by dustymc** [comment]
>should we add an identifier that is more specific?

Dumping everything that's slightly ambiguous (and/or unlikely to become resolvable) into one "generic random ID" - going LESS specific instead of more - would get around making users guess what we've done, and making data entry folks guess what we should be doing, but that idea is obviously not entirely palatable (probably for good reason).

Creating (eventually thousands, I suppose) of more-specific IDs for things like this may be even less useful/usable. (Things that might eventually become resolvable probably SHOULD have their own specific IDs - eg, if "AB: Albuquerque Biopark" sets up a useful database then we can link all "their" specimens to it with a simple code table update. And they can use that ID to easily find "their" specimens now.)

I don't think there's any globally "correct" approach, so I'm amenable to just about anything.

**Comment by Jegelewicz** [comment]
Since this is something only UTEP people will care about, I vote that I just use the generic "secondary identifier" if that's OK with you..

**Comment by dustymc** [comment]
Still sounds reasonable to me!
