### ISSUE TITLE
Need new Herp part

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#945]
Can we add brain to the Herp parts?

Thank you

**Comment by dustymc** [comment]
frozen or ??

**Comment by Jegelewicz** [comment]
"fixed in paraformaldehyde, then sectioned"
I suggest just using brain and I will put this in the part condition.
Any thought of adding a field to the parts for preservation method instead of making that part of the part name?  I think we've discussed this before, but I can't remember what the answer was.....

**Comment by dustymc** [comment]
Plain ol' brain it is then.

Given "brain fixed in paraformaldehyde, then sectioned" what is the part, what is the condition, what is the preservation method, is it a tissue or a part, did any of that change between pulling it out of the frog and now, and would any of that change if you were to do something else to it in the future?

Turns out there are a LOT of ways to respond, and when we had preservation method split out (and "tissues" separate from "parts") we had a couple orders of magnitude more "part strings" than we do now (and with many fewer specimens of much less diversity). I'm not really a huge fan of our parts model - I whine about how messy it is all the time, it's hard to find ribs when what's recorded is "skeleton" or "whole animal," etc., etc. - but users are still MUCH more likely to find all of what they want under it than they were under the more structured system.

**Comment by campmlc** [comment]
I second that. With explosion of new preservation methods for DNA etc, plus
adding new collections with new parts, the part+preservation model is
untenable. And then you have the issue of changes in preservation, eg
formalin fixed but ethanol preserved, etc. I strongly believe part and
preservation methods need to be split.

**Comment by Jegelewicz** [comment]
"Given "brain fixed in paraformaldehyde, then sectioned" what is the part, what is the condition, what is the preservation method, is it a tissue or a part, did any of that change between pulling it out of the frog and now, and would any of that change if you were to do something else to it in the future?"

It seems to me that tissue is a preparation (I am not a fan of it being a part name) and that for a tissue like this you would have:
part name: brain
part condition: tissue
part disposition: in collection
part preservation method: fixed in paraformaldehyde, sectioned
part storage medium: frozen (or 95% ethanol, etc.)

There - I just created two new part fields :-)

With a note in the remarks of the whole organism that the brain has been removed or partially so, this should cover the bases.  I don't know what you might do to something like this in the future that would change it.  If there is some change to it, then the condition would change and a note could be made in the part remarks.

If we decide that tissue is actually a part, then I would suggest this:
part name: brain tissue
part condition: whatever the condition of the tissue is - poor, good, etc.
part disposition: in collection
part preservation method: fixed in paraformaldehyde, sectioned
part storage medium: frozen (or 95% ethanol, etc.)

It would mean a bunch of xxxx tissue parts, but they would be far fewer than all of the tissue (liver - 95% ethanol), tissue (liver - frozen), etc.

Alternatively, the preservation method and storage medium could just go in the remarks, but I don't like putting so much information in one field - eventually someone is going to have to split it up.  I'm all for one field for each discreet data point (as much as possible, anyway).

I'm tired, so I hope that isn't just a bunch of nonsense!

**Comment by dustymc** [comment]
Perhaps we should schedule a call? Some points for consideration:

To be perfectly clear, I'm not defending or rejecting anything. The current model is nothing more than an escape from the old model (="the MVZ model" - https://web.archive.org/web/20100712042954/http://mvz.berkeley.edu/cis/MVZ1pgERdiagram020201.pdf) which somehow ended up with dozens or hundreds of ways to say most things, and so no way to FIND anything. Design a model that works better and I'll happily write code to it.

I have two major problems with the current model (both of which may be at least partially social rather than modeling problems):

1) It should be possible to search "brain" and get the not-de-brained/not-de-headed "whole organisms" etc.

2) It's heavily denormalized WRT containers. "Frozen" should come from the part being in a freezer, not the part name - and more below.

And one minor(??) concern: Give a tube of "heart, liver, spleen" to each of the "original three" institutions and they'll do three different things with it, which means I have to perform at least three searches to find all of that part type.

Individually, people are pretty consistent - each of us seems to make fairly predictable choices as to what is "part name" and what's "preservation method." Collectively, not so much. We (and there were not so many of us back then) quickly created ~10K ways of describing ~250 types of vertebrate-bits (representing well under a million specimens) in the old model. If we go back to something with more structure it cannot allow arbitrary choices, and it certainly cannot allow arbitrary combinations of arbitrary choices.

Part condition, preservation method, storage medium all change without changing the part name, and are all inter-related/confounded.

- Condition is perhaps least-problematic. Changes are maintained, it can be used to see eg, who breaks things on loan, etc., but it only contains people-provided information. And FWIW I'd be confused by "tissue" in condition - I'd expect "smashed up" or "very good" or similar.

- "Storage medium" is best handled through container environment (which also maintains a history), and you can do so by hooking a data logger between Arctos and your freezers (or anything else with an environment), or recording the measured ethanol concentration of a jar of 900 Batrachoseps. (Individual parts are not stored in isolation, so Arctos doesn't force you to manage them in isolation - just deal with the thing in which they're stored.) Historical data are critical - a part in LN2 (yay!) may have been degrading in a -20 freezer or an overcrowded jar of stinky "95% ethanol" for decades (not so yay...). "Storage medium" should have a close link to condition; it controls what I can do with the part.

- Preservation method fits in the same model - just scan the thing into a jar of formalin, then into ethanol, then into a freezer, then.... Any other approach is denormalizing - saying the same thing in multiple ways. As a user, I may not care WHY you had the thing in {pick some chemical/etc.}, I just care that it was there - the tissues that fell into a vat of formalin are not more useful to me than the ones you placed there. Storage/preservation data answer the same sorts of questions.

But reality. My second choice is part attributes. (Presmeth is part of what we built part attributes for, but I don't see any of those data in there.) Attributes also allow a history (each part can have many of them), which seems really critical to me - next week that brain will be "fixed in paraformaldehyde, sectioned, somethingelsed." Assuming someone has "somethingelsed" a specimen before, that should not require the creation of a new code table value (and certainly not one which acts as a multiplier on all parts) - you've done three things to the part, there's no need to stuff them all into one "field."

Disposition would ideally be an attribute of the container which holds the part. We are demonstrably not so good at updating disposition, while machine-tracked containers are pretty much impossible to lose (given solid procedures).

We tried hard and failed to find inherent tissue-ness in parts, so added the flag to the code table to allow for curatorial assertions. "Tissueness" is an arbitrary and inconsistent (albeit useful) thing, never something to recommend building a data model around, and I would strongly resist any effort to re-separate some parts from the rest.

Or perhaps you were just objecting to "tissue" as a part name - if so, I agree, see the "three institutions....three methods" thing above. We somehow have a LOT of ways of saying "we don't know much" (mixed in with a bunch of things that I at least occasionally think are overly specific).

Remarks - uncontrolled text in general - cannot be searchable. "No brain" in remarks will preclude any possibility of including that information in searches or analyses. (We have limited ability to do that now, but there's no reason to formally paint ourselves into any corners.)

**Comment by campmlc** [comment]
Perhaps we can discuss via the Working Group?
