### ISSUE TITLE
More Attribute Fields for Data Entry

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#967]
Would people be opposed to adding more attribute fields to the data entry screen? For birds in particular, we typically record 15 attributes per specimen. The DE screen allows us to record 9 of our standard values, but then we must make a note to go back and add in the remaining values to the specimen record(s) once loaded (increasing the likelihood that these attributes never actually make it into the specimen record). I believe more attributes can be pushed in through bulkloading, but students only use the DE screen since we tend to enter records individually as we prep specimens, or in small batches (5-15 records).

**Comment by dustymc** [comment]
I'm not really opposed, but the file format is already huge and unwieldy and I feel some obligation to put up token resistance....

Each attribute takes up 7 columns in the table, so accommodating your "typical" data would require 35 new columns. (The bulkloader table currently has 288 columns.)

All that said,  recent versions of Excel (I assume that's what most of us are using) are OK with >256 columns, so perhaps just adding anything that anyone asks for is now a workable approach.

Could/should we do something to the attribute (and friends) bulkloader(s) (what "add more..." in Data Entry writes to) instead? Perhaps some sort of "automagically load this when the specimen pops up" flag (that could be auto-set from data entry) or similar?

**Comment by campmlc** [comment]
I thought we were constrained to 10 for some reason? This is hugely
problematic for us as well, because we can never enter all the parasite
related attributes with the host. Dusty developed a tool to add attributes,
but then they go to an attribute bulk load table or something until someone
figures out how to load them, which no one at MSB has yet been able to do.
Until then they create an unwieldy URL identifier on the specimen re off.

On Oct 28, 2016 4:22 PM, "dustymc" <notifications@github.com> wrote:

I'm not really opposed, but the file format is already huge and unwieldy
and I feel some obligation to put up token resistance....

Each attribute takes up 7 columns in the table, so accommodating your
"typical" data would require 35 new columns. (The bulkloader table
currently has 288 columns.)

All that said, recent versions of Excel (I assume that's what most of us
are using) are OK with >256 columns, so perhaps just adding anything that
anyone asks for is now a workable approach.

Could/should we do something to the attribute (and friends) bulkloader(s)
(what "add more..." in Data Entry writes to) instead? Perhaps some sort of
"automagically load this when the specimen pops up" flag (that could be
auto-set from data entry) or similar?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ArctosDB/arctos/issues/967#issuecomment-257042824>, or mute
the thread

**Comment by dustymc** [comment]
>constrained to 10 for some reason

We are, but the constraint may no longer be anything to worry about. In the past we had a lot of problems with overly-wide tables, which may have been due to constraints that no longer exist in Excel. I don't remember details, but right this second I can't seem to think of any compelling reason to not make a huge table huge-er....

>no one at MSB has yet been able to do

I think Adrienne has used it - or ping me, we can go through it together and write some docs. The procedure is similar to relationships, if you've used that loader.

>unwieldy URL identifier

You probably mean the UUIDs - yes, I need SOMETHING that's known to be unique to match things back up after specimens and before parts/attributes/etc. have loaded - no such thing normally exists until the specimen gets a GUID so I have to make one.

**Comment by ebraker** [comment]
I'm fine with adding more bulkloader columns or with flagging the DE screen to indicate that overflow attributes in the attribute bulkloader should be loaded once the specimen record is available. I think the former is a more streamlined workflow than the latter despite an even clunkier table, but as long as I can be confident that we aren't forgetting to amend partially-captured specimen records once they are loaded, I am happy with either option.

**Comment by dustymc** [comment]
I think I'm fine with trying either as well.

One of the "data entry extras" is specimen_event, which is lots of columns (~100) in the table and probably cannot be denormalized in any usable way, so exploring a "just do it when you can" option for the bulkloaders may be useful no matter what else we might do. Should I try giving the DE-driven bulkloaders (Attributes seems like a good test subject) more autonomy, then revisiting the idea of more columns if that somehow proves less than satisfactory?

If that all sounds OK, should the flag be an option or should it be automatic? Options will likely lead to it SOMETIMES getting checked, and things indefinitely disappearing into some obscure bulkloader seems likely when eg, a student does something different to a few records for some reason. Automatic would somewhat dilute the review process - the person marking the record for load would be responsible for tracking down ready-to-autoload data wherever it might be hiding and reviewing it as well. (Or maybe there's some other option that I'm not seeing??)

**Comment by AdrienneRaniszewski** [comment]
I’m in favor of being able to enter more attributes within the Data Entry screen. The “add more…” function has been helpful, but it's not perfect. We enter hundreds of records at a time and having to track down other bulkloader files or go back and amend records after they are loaded makes completing records in a timely manner that much more difficult. Adding more columns to an already unwieldy excel file doesn’t bother me at all. Our typical record has 11 attributes, but it is not uncommon for a record to have 14 or 15 attributes. I would be thrilled to be able to enter all the attributes at once, with no extra steps.

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/2178 would provide a scalable approach to this.
