### ISSUE TITLE
unrestrict project description to posix-only characters

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#968]
Usability issue right now that anything not posix "Print" class will break constraints in Project description text-entry box.  The current work-around is to simply not introduce ANY line breaks (eg. carriage returns) or other rather innocent actions and write up your description as a giant text blob with embedded <br> and <p></p> tags to hopefully make it legible on the output side.

If we want to encourage people to write up useful and well documented Project descriptions we should make it easier for users to do so. 

Hey, here's a wild idea: allow Markdown?

**Comment by campmlc** [comment]
I agree. This is also an issue with loan forms. Hard to copy/paste from
loan request docs the purpose of the loan etc.  It would be much easier if
carriage returns at least were allowable.

**Comment by dustymc** [comment]
>anything not posix "Print" class will break constraints 

... everywhere. I believe the original consensus was that disallowing all nonprinting characters everywhere was the least-confusing approach to handling characters that often cannot be seen. 

>tags to hopefully make it legible on the output side.

There are many "output sides" (and that's what lead us to banning nonprinting characters in the first place) - rendered HTML, in a HTML:text box, in HTML:input box, packaged as DWC, downloaded as CSV, parsed to JSON, etc., etc., etc. - those all have different display "engines" and certain combinations of nonprinting characters are capable of "breaking" all of them in their own unique little ways, some of which are difficult to detect. (I believe the original issue involved vertical tabs, introduced by filemaker, visible by default in pretty much no interface, and somehow fatal to GBIF's XML-unwinder, which excluded records - for several years!)

>If we want to encourage people to write up useful and well documented Project descriptions we should make it easier for users to do so.

I strongly agree - that's why the HTML-markup control things exist in various places. I could add to those fairly easily...

>allow Markdown

...or that's potentially even easier and more approachable, and comes with some nice "readable anywhere" benefits. We'd need to talk about details, but sounds like a good idea to me.

>Hard to copy/paste from loan request docs the purpose of the loan etc

Aside from anything we might change from this discussion, nonprinting characters are still characters, even when you can't see them, and Arctos still has bitwise indexes. A search for "some data" cannot find "some{chr7} data." Those two things LOOK the same in almost all interfaces (they SOUND different in some old word processors). Copy/pasting from anything that uses control characters can cause that situation. And there are at least a half-dozen ways of encoding "carriage returns."

If we go to markdown, perhaps the interfaces could automagically deal with some of that. (And how to handle bulkloaders??) We could do also more with the existing noprint-finder tool (eg, integrate it into various text boxes). Etc. I'm always up for making things better, I just want to approach with everyone fully aware of what/how/why this stuff matters. 

Should we explore markdown?

**Comment by mkoo** [comment]
I am in favor of Markdown-- especially since there are preview options
which would make it easier to perhaps find any nonprinting characters that
interfere with rendering at least on the html side. Maybe previewing before
other Arctos tasks (date entry? even reports and labels- oh my!) could also
be taken advantage of.

**Comment by dustymc** [comment]
>make it easier to perhaps find any nonprinting characters

I'm not 100% sure at this point, but I THINK....

Markdown requires some nonprinting characters, and treats others as "data" (eg, leaves interpreting/ignoring them up to the output device). If we're all editing to a known "standard" (markdown) in a known "text editor" (HTML:textarea) then I could probably figure out intent - things which are visible in that environment (eg, linebreaks) are intentional, things which are not in :PRINT: and are not visible in that editor are not intended and can be silently removed, or similar. If that all holds up, users might not really need to know or care than they pasted in 5000 vertical tabs (which got stripped out before save).

If we do build something, it would certainly be portable - we could plug it in wherever. Reports and labels have their own interpreters, but if we're coming from a known format (markdown) we could build tools to "translate" for them. Markdown itself is just text, so if eg, we're allowing markdown in something that gets eg, displayed on HTML project pages then we'd need to translate it anyway.

FWIW, here's what the first 32 ASCII characters look like (between the [square brackets]) in GitHub's version of Markdown.

declare
  c char(1);
  clist varchar2(255);
begin
  for i in 1..32 loop
    execute immediate 'select chr(' || i || ') from dual' into c;
    clist:=clist || c;
  end loop;
  dbms_output.put_line('[' || clist || ']');
end;
 11  /
[


]

PL/SQL procedure successfully completed.

**Comment by mkoo** [comment]
win-win: universal text environment for Arctos!

are you seeing any standardization in the different renderings of Markdown
'flavors'? Github has its quirks but not used elsewhere? Generally the
differences seem minor to our uses but just wondering.

I do see a lot more inline/browser based md editors and previewers! so
intent should be transparent for both input and output

happy to test whatever you get going!

**Comment by dustymc** [comment]
>win-win: universal text environment for Arctos!

Yea, agreed - I don't think it's very clear to users how stuff can/should be formatted in various places, and I certainly never have a known "language" to start with when something needs formatted for some purpose.

>are you seeing any standardization

Not really, and the lack of a standard is always a little spooky. (But eg, CSV also has no real Standard and has worked fine for us.) I think we'd just have to pick something (probably browser-based) and let them set our "standard."

Know anyone using md who might be able to provide some input/guidance?

Does anyone think this ISN'T a good idea?

**Comment by mkoo** [comment]
@tigerhawkvok has implemented md textinput in all the projects he's built with me!

**Comment by dustymc** [comment]
No objections, moving to next task.

Details on "translators" might still be useful.

**Comment by dustymc** [comment]
This is now (partially) implemented for project description in test.

http://arctos-test.tacc.utexas.edu/project/evolution-of-tamiops-in-se-asia contains a lot of markdown.

http://arctos-test.tacc.utexas.edu/project/uncrowding-rehousing-and-electronic-migration-of-the-mammal-collection-at-the-denver-museum-of-nature-science-dbi contains a bare URL, which the md translator should automagically make clickable.

http://arctos-test.tacc.utexas.edu/project/phylogenetic-and-biogeographic-relationships-of-south-american-grass-mice-of-the-genus-akodon-rodentia-muridae-and-its-allies contains HTML, which should still render as expected.

http://arctos-test.tacc.utexas.edu/project/developmental-patterning-of-stripes-in-rodents contains markdown (linebreaks).

http://arctos-test.tacc.utexas.edu/project/phylogeny-of-caniformia-mammalia-carnivora-based-on-dna-hybridization is the same text (contains linebreaks), with the "ignore markdown" flag enabled.

Break it, please.
