### ISSUE TITLE
project meta-issue [was:new function, add specimen results to project]

### ISSUE THREAD

**Issue by amgunderson** [ArctosDB/arctos#984]
I'd like to be able to link specimens to a project. For instance a grant funded project to process marine mammals into UAM Mamm added thousands of specimens from many accessions but I can only add whole accessions to a project I use to track the results of that grant. I want to add a search result list of specimens to that project.

**Comment by amgunderson** [comment]
This is for a proposal that includes funding for arctos development that is due in 2 weeks but would be a very sexy thing to show other funding source - here is a link to your project that shows all the specimens archived and science done because of your support!

**Comment by mkoo** [comment]
Aren, that's a great idea to have a project for a grant proposal! Here's a
suggestion to associate a tailored specimen list to a project since this
was a problem for us too. ( All the historic accessions included lots of
"incidentals" that had nothing to do with the historic surveys). Any
transaction can be associated with a Project, not just accessions. So you
can create a data loan (just a long specimen search list) and associate the
loan transaction with the Project.

here's an example:
http://arctos.database.museum/project/historic-grinnell-survey-joshua-tree-national-park

hope this helps, good luck

**Comment by dustymc** [comment]
Data Loans work for this. Someone "used" those specimens, even if the "use" was only to improve the data, and usage is tracked by loans.

See also https://github.com/ArctosDB/arctos/issues/909. 

I maintain that what we have now is "correct." Projects currently demonstrate the specimens doing something - being collected, borrowed, cited, etc.  (And from projects I can get to the metadata of that activity - publication authors, loan recipients, etc.) Allowing that to be manually adjusted would, I think, lessen the value of all projects - I could never be sure if I'm seeing a specimen in a project because something sciencey happened, or just because someone clicked some button for some arbitrary reason.

That said, projects also contain "ancillary data" (like Media), and perhaps it would be somehow useful to add to that - somehow link Archives (arbitrary list of specimens) to Projects or something. And of course I'm always up for discussing how data are displayed - perhaps data loans should somehow be separated from "real" loans or ???

**Comment by amgunderson** [comment]
Thanks Michelle, that may work to track things internally, though it would skew loan statistics dramatically if I added 7,000+ specimens to a loan, and would not be viewable to the public. I already use projects for tracking NPS, USFWS, and Alaska Fish and Game specimens, and it works great and is very impressive for administrators to see on one page the numbers of loans, specimens, and publications coming from their specimens. If it could be possible to add specimens directly to a project I could show the North Pacific Research Board that their previous award to us has produced 7,371 new specimen records in Arctos on a project page that is publically accessible.

**Comment by amgunderson** [comment]
I wouldn't call performing grant funded work on specimens a loan. Everything we do with specimens is grant or contract funded since we get no operating budget from the university. So I guess this would require a new designation similar to "contributed by" or "used by" or "cited by", maybe "funded by"? I'll do this off arctos for now and make a list of catalog numbers then archive a search result from that list. There are bigger fish to fry...

**Comment by campmlc** [comment]
We do need to added "funded by" to the project page - we currently have
amount of funding, but not the funding source or grant number. This was
raised in a previous issue.

**Comment by dustymc** [comment]
I agree that's not a proper loan, but I still think the loan data model is correct - some "transaction" involving specimens happened, you want to document that and it's impact on future activity. (E.g http://arctos.database.museum/project/alaska-native-harbor-seal-commission-anhsc - a "contribution" facilitated a bunch of other projects happening.)

Loans and accessions could (I think) be merged in the model, which would open up the possibility of a completely different type of "transaction" (some activity involving specimens - "funded curatorial activity" or whatever). Doesn't seem insurmountable, but probably not trivial either.

How about another type of loan which is functionally identical to data loans (specimens-->transaction), but which could be displayed differently (and excluded from "real loan" stats etc.)? That probably is a trivial (few days?) development, and might serve as a bridge to something more formal.

I'm re-opening this. I think we need a standardized solution, even if it's only better documentation of loan procedures.

**Comment by dustymc** [comment]
>We do need to added "funded by" to the project page - we currently have amount of funding, but not the funding source or grant number. This was raised in a previous issue.

Those things exist (I think...). Send me what you have and the related project; I'll add it (or figure out what's missing!) and write documentation.

**Comment by jldunnum** [comment]
I think funded by is a good addition with a place to add grant numbers


______________________________________________________________

Jonathan L. Dunnum Ph.D.
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by mkoo** [comment]
I like funded by...
and how about project loan (in addition to data loan)? so we can still use
the data loan model but be clear about its use and definitely leave off of
loan stats. I do not include any data loans in our loan stats by the way
right now.

**Comment by dustymc** [comment]
>funded by

That was released in May. Documentation is https://github.com/ArctosDB/documentation-wiki/wiki/How-to-understand-Project-Funding, a demo project is http://arctos-test.tacc.utexas.edu/project/beringian-coevolution-project (funded for $17 by NSF grant 12345 according to the test data).

>project loan

I like it. If anyone will use it, that should be easy to make happen. (But we need a resolution on #799 before I do too much to "specimen loans." I think we should restrict data loans to containing only cataloged items.)

**Comment by campmlc** [comment]
I just talked with Sara Brant, and she needs the same thing - a way to link
a project to only parasite larvae, which would represent only parts of
multiple accessions.  We discussed the possibility of having a saved search
that could link to the project page, or, even better, a way to save the SQL
and integrate it into the project page, e.g. "Search all specimens related
to this project" - so that when you click the link, it executes the SQL
search and pulls up the current search results.
Is this possible?
Mariel

**Comment by campmlc** [comment]
The search would be not on the project name, but on a particular search
string related to  specimens - e.g "taxon name = schistosom%, attribute =
age class, attribute value = larvae).

**Comment by dustymc** [comment]
Saved searches ARE executable SQL - they're dynamic and find whatever matches the query at the time. (And Archives are static lists of GUIDs.) 

I don't think I have any objections to attaching either of those to projects in the same way we handle Media, but I also don't see how that would be functionally different than just adding a link to the specimens (or search) from the project description. Either approach bypasses a significant portion of the reason projects exist - a list of specimens can't be used to demonstrate how activity (transactions - collecting and usage) lead to other other activity (more usage, citations, funding, etc.). The only way I know of to get at "the project loop" is through Transactions.

**Comment by campmlc** [comment]
Is there any reason we couldn't have both? Add a link to projects to a
specimen search (saved, archived, etc), and also create project loans?
Maybe we need to rename "project loan" to something else - I'm still having
trouble with the terminology.

As for "funded by" - in the current test model, NSF goes into the
description as plain text., and is only searchable that way. Leads to
issues with mis- or alternate spellings leading to incomplete search
results.   Could we create a "funded by" box and have "NSF" be entered as
an agent (from the Agent table)?

**Comment by dustymc** [comment]
>Add a link to projects

Do you mean FROM?

You can use HTML (eg, links) in project description now. (And you'll be able to use markdown in the next release, unless someone breaks #968.)

"Attaching" saved searches and/or archives through some sort of data structure would take some development, and I'd need to understand more about what you're trying to accomplish before I could write that code.

Nothing about projects is exclusionary - you can attach as many of anything as you need.

If we go there, I don't much care what we call "project loans" but I do need some stability in the terminology (especially if it's functional - eg, if they somehow look different on project pages).

NSF should be entered as a project agent, NOT as text.

<img width="513" alt="screen shot 2016-11-30 at 4 32 52 pm" src="https://cloud.githubusercontent.com/assets/5720791/20777253/a8bc4ee2-b71a-11e6-994e-5b5849e0c18e.png">

Along with being searchable as project agents, that creates links from the public project page (http://arctos-test.tacc.utexas.edu/project/beringian-coevolution-project) to the agent summary (http://arctos-test.tacc.utexas.edu/agent.cfm?agent_id=1015634&agent_name=U.%20S.%20National%20Science%20Foundation), which links back to the project, which links to other project, which.... - starting from any of those points (or anything else that links to projects), you can click around and see what NSF has directly funded, and what activity that directly-funded activity has in turn supported (eg, projects using specimens to produce publications - http://arctos-test.tacc.utexas.edu/project/the-distribution-and-phylogeography-of-the-alaska-marmot-and-collared-pika-in-alaska used a bunch of stuff from BCP, contributed more specimens, those got used by 12 more projects, etc. - all of that, no matter how "deep" it eventually gets, leads back to NSF, and that works because of how projects relate to loans and accessions.)

**Comment by Jegelewicz** [comment]
> Let's make this an AWG agenda topic please.

Agenda has been created and this item added! https://docs.google.com/document/d/1LF_h0vb2pSLuHlxu3q_Hg0fzzlVkFPVEI9yQWj0qdvs/edit?usp=sharing

**Comment by dustymc** [comment]
From "Projects contributing specimens" email with @ccicero 

Generally, 
* "Contributing" means someone linked a project to an accn.
* "Using" means someone linked a project to a loan.

Specifically

* Specimens Used:  specimens in loans which are linked to this project
* Specimens Contributed: specimens in accessions which are linked to this project
* Projects contributing specimens: Projects which contributed (accessioned) specimens which were loaned to this project. The loaned specimens are in the "specimens used" section. Those projects are supporting the research recorded by this project.
* Projects using contributed specimens: The reciprocal to "Projects contributing specimens." Specimens were contributed (accessioned) by this project, and subsequently loaned to those projects. This project is supporting the research of those projects.
* Media: Media which was created for this project and is not suitable for linking to more specific things, such as individual specimen records.

**Comment by dustymc** [comment]
update project documentation (BCP=funded collecting + funded usage vs. Carla=general collecting + multiple usage)
