### ISSUE TITLE
fossil

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#991]
See #989: We now have "shell" (used by eg, earth science collections) and "shell (fossil)" labels for exactly the same types of material, which actively prevents users from finding what they're looking for.

It's not clear to me that there's any consensus on what "fossil" means ("petrified," "of a former geologic age," "from the remote past", etc.), and so I'm very hesitant to adopt something like the DWC:basisOfRecord suggested vocabulary (eg, "FossilSpecimen").

If there some value in distinguishing "fossil" shells (etc.) from "not-fossil," and if so how might we accomplish that?

**Comment by Jegelewicz** [comment]
I am going to face this issue when I get to my inverts.  We have fossil shells in our malacology collection.  Fossil is problematic.  The definition is something like "evidence of the existence of life from a previous geologic age".  Now that we have entered the Anthropocene, would that mean that almost everything in any collection is technically a fossil? :-)

Because my ES collection uses non-numeric catalog numbers (site number - catalog number), I have thought that I might give my fossil inverts a "site" number and then use their current catalog numbers as the rest of the ES catalog number.   I don't know if setting up an ES collection is feasible for everyone, but why not?  It would mean access to the geology fields and then we could just use "shell".  If you use the site number - catalog number formula for Arctos catalog numbers, then you can have fossils from any collection in one ES collection.  What would be nice in my case would be some way to note in the INV collection that the specimen has been moved to ES.  Suggestions?

**Comment by campmlc** [comment]
From the perspective of a predominantly alcohol-preserved fish collection,
I think it would be very valuable to distinguish "fossil" fish or fish
parts from something in a jar. Obviously it might make a difference for
loan requests. Thus goes back to the problem if conflating both the part
itself with the method of preservation, which I disagree with. Fossilized
should really be a form of preservation, independent of the part.

**Comment by dustymc** [comment]
Creating collections is easy, but inferring anything from collection type is almost always dangerous - most mammal collections have a snake, some parasites, maybe a suicidal sparrow, .... If "fossil" is worth saying at all, we should explicitly say it.

Ditto information cryptically buried in some ID string etc. - that's often useful for some local limited purpose, but nobody is going to find "ABC-123-XYZ-f" on GBIF and think "AHA! Fossils!"

Alcohol is (theoretically) easy - it SHOULD be a container environment ("storage medium"), and we just mix it up with parts to make things like printing labels and finding pickled specimens easy. Alcohol concentration (and temp, etc.) can be measured - there's not any ambiguity in the data. 

"Fossil" is, from what I can tell, an entirely arbitrary designation. UAM (including "modern" collections) has a fair bit of good-condition frozen tissue from Pleistocene animals - those are "fossil" by some definitions, and they're in tubes in freezers, treated about the same as any other tube in a freezer. Hadrosaur "bones" (petrified - probably anyone's definition of fossil, except when they're not - http://www.sciencemag.org/news/2015/06/signs-ancient-cells-and-proteins-found-dinosaur-fossils) are stored alongside mammoth-bits ("fossil" to most people, maybe??), which are largely made of bone (and commonly have holes drilled in them for things like https://www.ncbi.nlm.nih.gov/nuccore/EF632344). http://arctos.database.museum/guid/UAM:ES:14480 was likely collected because it MIGHT contain (micro-) fossils. 

It's not really clear to me why a "fossil" (whatever that means!) shell (otolith, bone, whatever) would need to be treated (in a database or collection) any differently than a modern equivalent.

"Secondarily mineralized" or "dry and bony" or "smells like slightly freezerburned bison meat" looks like part condition to me. If for whatever reason there is a need to assert (and search) "fossilness" perhaps we could do something in specimen part attributes (http://arctos.database.museum/info/ctDocumentation.cfm?table=CTSPECPART_ATTRIBUTE_TYPE) - in part because unpredictable data "downstream" of specimen parts is unlikely to interfere with most searches.

????

**Comment by dustymc** [comment]
Closing this in favor of #1020, which is more generic
